### ISSUE TITLE
Bug: Export Archive does not include images

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#1001]
**Summary:**
May be expected, but we should probably take a look at.

**Steps to reproduce the behavior:**
1. Go to a board and create cards with images.
2. Export board archive
3. Go to another board 
4. Import Archive
5. No images present.

**Expected behavior:**
Images to be able to be exported/imported

**Comment by chenilim** [comment]
This is tracked by [this card](https://community.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/shared/47aa9bb4-6967-4a96-83c7-11bd6b20f1eb/7e38eab4-890a-4fc3-8f48-a1f9bd1ab822?r=762db9c6-305c-4d13-8ce6-9f11e5232c24&c=6f393f58-00fe-471a-8ea1-cbb338e59fa4), which is currently unscheduled.

This should be technically feasible, with client-side code to download and encode images to include in the archive. This will require an extension to the archive format though. Welcome additional comments and input. cc @jespino.

**Comment by chenilim** [comment]
Cleaning up old issues - this has been resolved by the new `.boardarchive` format.
