### ISSUE TITLE
Bug: "Add board" contextual menu overflows the screen on the left

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/focalboard#1004]
**Summary:**

**Steps to reproduce the behavior:**
1. Go to a board
2. Create a template
3. Open the "+ Add board" on the bottom left of the screen
4. Click the contextual menu of the template 

**Expected behavior:**
The menu should not get cut by the screen.

**Screenshots:**
![image](https://user-images.githubusercontent.com/223323/129597023-d09bc9b3-f6e8-4083-ac34-5576e155bff2.png)

**Comment by chenilim** [comment]
@asaadmahmood, another fit and finish bug for v0.9. Longer term, we probably need to revisit our menu implementation so that they don't get clipped by their containers. For now, I think we can just make sure this menu is fully visible. cc @jespino, @sbishel.

**Comment by ogi-m** [comment]
Tested and passed - verified the contextual menu now opens to the right
