### ISSUE TITLE
Bug: Shared-boards modal needs some padding

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#1005]
**Summary:**
The shared-boards modal looks like it could use some padding.

**Steps to reproduce the behavior:**
1. Go to any board
2. Click on ...
3. click on share board
4. See modal window

**Expected behavior:**
More padding around popup windown

**Screenshots:**
![Screen Shot 2021-08-16 at 10 26 09 AM](https://user-images.githubusercontent.com/12704875/129597248-88bb43d8-986b-4a1b-bb53-199ba9a656a9.png)

**Comment by chenilim** [comment]
This is a regression, and we should fix it for 0.9. Should be (hopefully) a simple fix. @asaadmahmood, can you take care of this as part of the style update / review? Thanks.

**Comment by ogi-m** [comment]
Tested and passed on v0.9.0 RC8 - the spacing is now adequate
