### ISSUE TITLE
Bug: Editing card template's description doesn't work

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1006]
**Steps to reproduce the behavior:**
1. Create a template from a card
2. Click on "Add a description..."
3. Enter some text
4. Press Esc or click outside the edit box
5. The text disappears
6. Clicking on "Add a description..." again makes the text appear, but only during editing
7. Adding additional content (text, divider, checkbox, image) also exhibits the same issue

**Expected behavior:**
1. The description should be set, just like a normal (non-template) card.
2. Adding additional content to the template card should also work.

**Screenshots:**
https://user-images.githubusercontent.com/46905241/129597384-70d8deb2-172e-4715-8adb-2c8acdc2e512.mov

**Platform:**
 - v0.9.0 RC5 on Community
 - Chrome 91 on macOS

**Additional context:**
If you subsequently create a card from the template, the description appears, but may appear multiple times if you edited the text multiple times.

**Comment by chenilim** [comment]
@sbishel, assigning to you to reassign, and marking this for 0.9. It looks like the card content logic has issues when editing it as a template.

**Comment by kamre** [comment]
@hahmadia @jespino it seems that regression was introduced during the transition to Redux.

In particular here is how the problem happens:
* `CardDialog` component extracts the card content via `contents = useAppSelector(getCardContents(props.cardId))`
* `getCardContents(cardId)` uses internally `getCards(...)` which returns `state.cards.cards`
* `state.cards.cards` doesn't contain cards from `state.cards.templates`

**Comment by ogi-m** [comment]
Verified this is fixed on RC6
