### ISSUE TITLE
Bug: popup menu disappears when mouse is not over

### ISSUE THREAD

**Issue by kamre** [mattermost/focalboard#1007]
**Summary:**
Some components contain a button that appears only on hover and allows to show popup menu. Such popup menus disappear when the mouse is moved away and reappear when mouse is over the component.

**Expected behavior:**
Popup menu should be visible until user clicks somewhere.

**Screenshots:**
Kanban card:
![PopupMenuKanbanCard](https://user-images.githubusercontent.com/5587620/129602031-800438b4-8e3c-4dce-ac7e-1ddf2233fee2.gif)

Gallery card:
![PopupMenuGalleryCard](https://user-images.githubusercontent.com/5587620/129602085-93d8cc02-83b7-481c-8ad9-9afaba28fe90.gif)

Card comment:
![PopupMenuComment](https://user-images.githubusercontent.com/5587620/129602144-e5128b3d-2b0b-4caf-8f8e-09f6e36098b6.gif)

Card description:
![PopupMenuCardDescription](https://user-images.githubusercontent.com/5587620/129602173-926ff843-efa3-4ac3-9ad9-a3ee23d46914.gif)

**Platform:**
 - Browser and version: Chrome 92
 - OS and version: Windows 10

**Comment by chenilim** [comment]
Thanks @kamre, good catch! Not sure why this happens for some menus as you noted, but not others (e.g. board menu, board column menu). In any case, the menus should remain visible until the user selects an option, clicks away, or presses Esc. cc @asaadmahmood, @jespino, @sbishel.

Putting this up for grabs.

**Comment by Pinjasaur** [comment]
> Wouldn't a better solution be just to add a class to the card who's menu is open, and then just increase the z-index on it?

> I think we can then also use that functionality to make sure that the menu remains even if you hover outside of that card, and only remove that class on a blur event or on a click outside.

Taken from https://github.com/mattermost/focalboard/pull/3486#issuecomment-1201035635.

**Comment by kamre** [comment]
Hi @wuwinson, I am working on this bug and will soon create a pull request with the fix. So you can assign it to me.

**Comment by wuwinson** [comment]
Awesome, thanks @kamre!
