### ISSUE TITLE
Bug: Text (and other) property values are truncated in the card view

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1010]
**Steps to reproduce the behavior:**
1. Open a card with a text property
2. Enter a long string into the property, save it
3. The text is truncated after just a few words

**Expected behavior:**
The property values should take up the full horizontal space in the card editor.

**Screenshots:**
<img width="999" alt="Card editor" src="https://user-images.githubusercontent.com/46905241/129607150-0ed2eb7a-981e-428b-9f6a-d5e9b6a6cdb1.png">

**Platform:**
 - v0.9.0 RC5 on Community
 - Chrome 91 on macOS

**Comment by chenilim** [comment]
@asaadmahmood, what do you think the right layout should be? I think it should be relatively easy to make the values take 100% of the remaining width in the card editor, but there may be some special cases for things like URLs, which have an on-hover link button at the end.

If you agree it's an easy fix, let's make the change for 0.9. cc @ogi-m, @sbishel.

**Comment by ogi-m** [comment]
Tested and passed on RC8 - verified they now take up the whole width of the card.
