### ISSUE TITLE
Bug: Clicking on a link in the card description also edits the description

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1011]
**Steps to reproduce the behavior:**
1. Open a card with a link in the description markdown
2. Click on the link
3. The link opens in another tab (as expected)
4. Switch back to the card tab
5. The card description is being edited

**Expected behavior:**
The card description should not be edited when clicking on a link.

**Screenshots:**
https://user-images.githubusercontent.com/46905241/129611485-56232645-3335-42ff-bb48-349143192be2.mov

**Platform:**
 - v0.9.0 RC5 on Community
 - Chrome 91 on macOS

**Comment by chenilim** [comment]
Note that the markdown editor normally ends editing when it loses focus, so it might have been a change in timing that caused this. While it's relatively low severity, it's a good fit-and-finish issue as clicking on links is a fairly common action.

**Comment by kamre** [comment]
@chenilim @harshilsharma63 the reason for such behaviour is that link generated for markdown has the following logic:
```js
renderer.link = (href, title, contents) => {
    return '<a ' +
        ...
        ((window as any).openInNewBrowser ? 'onclick="event.stopPropagation(); openInNewBrowser && openInNewBrowser(event.target.href);"' : '') +
    '>' + contents + '</a>'
}
```
So if there is no `window.openInNewBrowser` it will **not** stop propagation of the click event and it will be used to start editing of the card description.

Possible fix is to always use `onclick="event.stopPropagation();` for the generated links.
