### ISSUE TITLE
Select option clear button display is inconsistent

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1013]
**Steps to reproduce the behavior:**
1. Open a table with select and multi-select properties
2. Notice that the select options have a clear (X) button on them
3. Notice that the multi-select options do not, unless editing
4. Open a card, notice a similar inconsistency in the X button display

**Expected behavior:**
Select options should not show a clear button when not editing, across all views.

**Screenshots:**
<img width="846" alt="Table select option" src="https://user-images.githubusercontent.com/46905241/129619543-e9c1d158-b671-43c7-a800-dff46245ccee.png">

When editing a multi-select property, the clear buttons appear:
<img width="844" alt="Table multi-select edit" src="https://user-images.githubusercontent.com/46905241/129619549-a6782742-5664-4406-ab62-7a0c744c5fd6.png">

**Platform:**
 - v0.9.0 RC5 on Community
 - Chrome 91 on macOS

**Comment by chenilim** [comment]
@asaadmahmood, please weigh in if you agree with the proposed behavior, and assign to @sbishel to reassign if you do. While this is a low-sev issue, I'd like to take it as a fit-and-finish polish issue particularly for table views.

**Comment by asaadmahmood** [comment]
@chenilim This makes sense to me.

**Comment by chenilim** [comment]
Thanks. One more thing: The clear button remains visible after editing a multi-select property (in the table and in the card editor):
https://user-images.githubusercontent.com/46905241/129620904-56b3ac3f-58a1-487b-98e1-fbbbfab1f5bf.mov

The clear button should be hidden when not actively editing a select property.

**Comment by sbishel** [comment]
@chenilim I have spent a couple of hours looking at this, trying a couple quick and not so quick fixes. Fixing this is going to take looking at the `CreatableSelect` component in more depth and possibly reworking how we are using it.

I suggest removing from `0.9.0` as it is functional and works currently.

**Comment by chenilim** [comment]
Yup, agree. If it's not a simple fix, we can fix this after 0.9. Removing the milestone.

**Comment by kamre** [comment]
@chenilim @sbishel I have started working on this issue.

[Initial fix](https://github.com/kamre/focalboard/commit/06e766f84a2ba9d97f4cf3f116e32e73286165d3) is done. Also I want to perform a small refactoring extracting the code for `select` type from `PropertyValueElement` mega component.

**Comment by chenilim** [comment]
Thanks for fixing this @kamre!
