### ISSUE TITLE
Bug: Board Favicon is not set when switching to Boards (nor always set when changing boards)

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1014]
**Steps to reproduce the behavior:**
1. From a channel with a board, open the App Switcher and switch to Boards
2. The browser tab favicon is not changed

**Expected behavior:**
The browser favicon should be set to the board's icon

**Platform:**
 - v0.9.0 RC5 on Community
 - Chrome 91 on macOS

**Additional context:**
The board favicon is not always set when switching to a board from another board.

**Comment by chenilim** [comment]
@jespino, assigning this to you for investigation as this appears related to #944. Please reassign / rebalance as necessary. I'm seeing some general flakiness with the favicon setting, which may indicate a deeper issue. FYI @sbishel, @ogi-m.

**Comment by jespino** [comment]
I think this was fixed in the PR #972, that is after rc5

**Comment by ogi-m** [comment]
Tested and passed on RC6 -  favicon is updated on each board change
