### ISSUE TITLE
Bug: Add content button doesn't disappear when editing card description

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1016]
**Steps to reproduce the behavior:**
1. Open a card
2. Click on Add a description
3. The "Add content" button remains visible while editing the description

**Expected behavior:**
The "Add content" button should only be visible when hovered over.

**Screenshots:**
https://user-images.githubusercontent.com/46905241/129643113-1130d0aa-e847-49ef-af52-813060302991.mov

**Platform:**
 - v0.9.0 RC5 on Community
 - Chrome 91 on macOS

**Comment by chenilim** [comment]
This is a low-sev issue, but is a regression from 0.8.

**Comment by kamre** [comment]
@chenilim this was changed via #449, in particular look at [this comment](https://github.com/mattermost/focalboard/issues/449#issuecomment-891288871).

**Comment by jespino** [comment]
@chenilim I think I remember a conversation about this with @asaadmahmood and I think the final decision was "show it while hover and while focus", that is the reason of the current behavior.

**Comment by asaadmahmood** [comment]
Yup @chenilim @jespino Lets keep it, there's an issue where it's not discoverable, let's see if people actually find it irritating.

**Comment by chenilim** [comment]
Ah, thanks, I had missed that note. Yup, this behavior is "by design" then, and I'll close this issue. I'll defer to @asaadmahmood on the design, but my guess is we need to rethink where we apply the visible-on-hover controls in general. We've run into issues where other things like the board description button is also not discoverable.
