### ISSUE TITLE
Not able to register user on local server

### ISSUE THREAD

**Issue by darkLord19** [mattermost/focalboard#102]
**Summary:**
Getting error "invalid email format" when trying to register user in local server

**Steps to reproduce the behavior:**
1. Build server binary using steps provided in Readme
2. Try to register new user
3. Enter details

**Expected behavior:**
Account registration should have been successful.

**Screenshots:**
![image](https://user-images.githubusercontent.com/16662014/111626084-99bd2c80-8813-11eb-9b4e-fc3ad5e94b24.png)

**Platform:**
 - Browser and version: Firefox
 - OS and version: macOS

**Comment by jespino** [comment]
Yes, sorry, this is because a wrong check merged early this morning, I'll fix that soon.

**Comment by jespino** [comment]
@darkLord19 now should be fixed.
