### ISSUE TITLE
Bug: Cannot use mouse to select property name on FireFox and Safari

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1021]
Use FireFox or Safari

**Steps to reproduce the behavior:**
1. Open a card
2. Add a property
3. Try to select the property name text with the mouse
4. Unable to select with mouse

**Expected behavior:**
Should be able to select text with mouse

**Screenshots:**
https://user-images.githubusercontent.com/46905241/129783034-956a8ca2-03c0-4c74-9439-45279528696b.mov

**Platform:**
 - v0.9.0 RC5 on Community
 - Safari 14.1.1 on macOS 11.4
 - ForeFox 91 on macOS 11.4

**Additional context:**
This doesn't repro on Chrome, nor (more interestingly) in the macOS App

**Comment by chenilim** [comment]
This appears to be related to #1015, and might affect other text input fields as well.

**Comment by ogi-m** [comment]
Verified this is fixed on RC5

**Comment by ogi-m** [comment]
Tested and passed on v0.9.0 RC8 in Firefox 👍🏻
