### ISSUE TITLE
Bug: Table row height is increased on hover

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1024]
**Steps to reproduce the behavior:**
1. Open a table
2. Hover over a row
3. The height of that row is increased (appears to be by one pixel)

**Expected behavior:**
The row height should remain constant on hover. This is a minor issue, but a UI distraction.

**Screenshots:**
https://user-images.githubusercontent.com/46905241/129807164-5b7e0d7b-d820-4e6b-a917-8387885bfce0.mov

**Platform:**
 - v09.0 RC5 on Community
 - Chrome 91 on macOS

**Comment by chenilim** [comment]
FYI @asaadmahmood. This is a minor UI annoyance, so setting it as up for grabs, but you might want to consider it if you're planning an overall table restyling.

**Comment by kamre** [comment]
@chenilim @asaadmahmood I also see such behaviour with increased row height on hover, and I use custom larger font size in my browser.

The reason for this is definitely appearing "Open" button. Currently it has the height [equal to 90%](https://github.com/mattermost/focalboard/blob/main/webapp/src/components/table/tableRow.scss#L14) and this seems to be the reason for the increasing of table row height.

Changing this height for example to `24px` prevents the issue. Is this a proper fix?

**Comment by dazzlerkumar** [comment]
I can fix this issue.

**Comment by asaadmahmood** [comment]
Test

test

**Comment by ogi-m** [comment]
Verified the table no longer changes height on hover
