### ISSUE TITLE
Bug: opening URL from kanban card also opens card dialog

### ISSUE THREAD

**Issue by kamre** [mattermost/focalboard#1033]
**Summary:**
When URL property is visible on the kanban card its possible hover and click on the link with URL. After the click the card dialog is also opened.

**Steps to reproduce the behavior:**
1. Create new empty board
2. Create new card in the board and add URL property to it
3. Close the card dialog
4. Click to _Properties_ menu in the board and enable URL property
5. URL property is visible on the kanban card
6. Hover and click on the link for URL in the card
7. Browser opens URL in the new window
8. Also card dialog is opened

**Expected behavior:**
Card dialog should not be opened.

**Platform:**
 - Browser and version: Chrome 92
 - OS and version: Windows 10

**Additional context:**
Can probably be fixed by adding `onClick={(event) => event.stopPropagation()}` handler to `a` inside `URLProperty`

**Comment by chenilim** [comment]
Thanks @kamre! Agree clicking on the link button should not open the card. Should be a straight-forward fix. Putting it up for grabs. FYI @sbishel, @asaadmahmood.

**Comment by ogi-m** [comment]
Tested and passed - the card dialog no longer opens when clicking on the url
