### ISSUE TITLE
Open final documentation page when clicking on help icon in global nav

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1034]
When running as a plugin:

**Steps to reproduce the behavior:**
1. Click on the help button in the global nav
2. It opens https://www.focalboard.com/guide/user/

**Expected behavior:**
It should open the new Boards documentation page on docs.mattermost.com

**Screenshots:**
<img width="146" alt="Nav bar right" src="https://user-images.githubusercontent.com/46905241/129978402-2b7d255e-d0d6-4a0d-abd1-1f308fe96093.png">

**Platform:**
 - v0.9.0 RC6 on Community

**Additional context:**
Note that the help button should continue to open the existing URL (https://www.focalboard.com/guide/user/) when running as Personal Server or Personal Desktop.

**Comment by chenilim** [comment]
@justinegeffen, is there a URL we can use for now, that will be the entry point for the user documentation? cc @sbishel, @jespino.

**Comment by justinegeffen** [comment]
The URL will be https://docs.mattermost.com/boards and the PR will be ready to review on Monday AM. Can we leave this link as-is until then?

**Comment by chenilim** [comment]
Thanks @justinegeffen, yup, lets review the doc PR and make this change once the new docs are up.

**Comment by chenilim** [comment]
@justinegeffen, I notice that the URL is currently https://docs.mattermost.com/guides/boards.html. Will this be the final one for v0.9 / Oct? Or should the link in the app go to https://docs.mattermost.com/boards? If so, when will that be live? Thanks.

**Comment by justinegeffen** [comment]
Yep, that's the final URL - the "guides" part is the landing page which is the same across channels, playbooks, and boards. :)

**Comment by chenilim** [comment]
Thanks @justinegeffen! We're all set then. For future reference, that URL is stored in [the doc-boards fwlink](https://github.com/mattermost/focalboard/blob/main/website/site/content/fwlink/doc-boards.html), which is opened by the in-product link, so we can easily change this later if needed.

**Comment by justinegeffen** [comment]
Brilliant, thank you!! :)

**Comment by ogi-m** [comment]
Verified on v0.9.0 RC9, help links opens https://docs.mattermost.com/guides/boards.html
