### ISSUE TITLE
Bug: Card property display styles are inconsistent

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1035]
**Steps to reproduce the behavior:**
1. Open a card with properties of various types
2. Note that the styles are inconsistent, e.g.:
* Created Time and Last Update Time font is smaller that Dates
* Dates are bold
* User properties have a larger font than text
* Date and User property values have different padding from others

**Expected behavior:**
Styles should be consistent

**Screenshots:**
<img width="402" alt="Card properties" src="https://user-images.githubusercontent.com/46905241/129979975-d3cd93c1-c61b-4a20-a8f5-d363cd3a680e.png">

**Platform:**
 - v0.9.0 RC6 on Community
 - Chrome 91 on macOS

**Comment by chenilim** [comment]
@asaadmahmood, this is not a high priority, but probably can be cleaned up with a quick pass.

**Comment by asaadmahmood** [comment]
Should be fixed with this, closing it as its a dup.
https://github.com/mattermost/focalboard/pull/1875
