### ISSUE TITLE
Bug: The border of some kanban cards is cut

### ISSUE THREAD

**Issue by zJudGenie** [mattermost/focalboard#1040]
**Summary:**
As you can see in the first screenshot, the left border of all cards in the first column is cut.
A solution could be to remove [`this padding`](https://github.com/mattermost/focalboard/blob/7b5a45dc6cf53fb044b99cb9b4d3ae09a4dcc958/webapp/src/components/centerPanel.scss#L50) and add a `padding-left` set to `1px`

**Steps to reproduce the behavior:**
1. Create the first column
2. Add some cards

**Expected behavior:**
The left border is visible 

**Screenshots:**
![immagine](https://user-images.githubusercontent.com/25179403/130044918-8d835cdf-0497-488b-bcc7-b920d223afc7.png)

**Platform:**
 - Browser and version: Firefox 91
 - OS and version: Windows 10

**Additional context:**
Self-hosted using the docker container
Focalboard v0.9.0

**Comment by chenilim** [comment]
Repros on Chrome, and on the community server with v0.9.0 RC6 as well.

**Comment by ogi-m** [comment]
Tested and passed on v0.9.0 RC8, the left border is clearly visible on cards in the first column
