### ISSUE TITLE
Bug: In plugin mode, the share url should be in the form of `/plugins/focalboard/shared/whatever`

### ISSUE THREAD

**Issue by jespino** [mattermost/focalboard#1046]
**Summary:**
This is because the `/boards/`url now requires logged in user, so we can solve that problem using directly the plugin api for that.

**Comment by chenilim** [comment]
Thanks @jespino, when did / or will this behavior (requiring a logged in user) change? Both `/boards/` and `/plugins/focalboard/` work for shared boards on community-daily right now, at least for me. In any case, if that behavior is changing, I agree we'll need to make this change on our end.

We should revisit the ability to change that url in the future (i.e. to remove "focalboard" from it), but if this let's shared boards work for now, we should do it.

Assigning to you to reassign @sbishel. I guess it's a re-fix of #989.
