### ISSUE TITLE
Bug: Card title alignment is inconsistent

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1051]
**Summary:**
Card title alignment is inconsistent and depends on the emoji that's allocated to the card.

**Steps to reproduce the behavior:**
1. Open board view
2. Create several cards in a column
3. Observe the card title alignment

**Expected behavior:**
Card titles should be aligned

**Screenshots:**
![Image Pasted at 2021-8-19 11-45](https://user-images.githubusercontent.com/15314183/130122994-ac32a311-7042-43e9-8d82-e0e2c981e3dc.png)

**Platform:**
 - plugin v0.9.0 RC6 on master (community-daily)

**Additional context:**
@lindy65 brought up this issue as being problematic for Rainforest UI automation since the screenshots don't match exactly, causing tests to fail.

**Comment by chenilim** [comment]
Thanks @ogi-m. Hmmm, any ideas @asaadmahmood? Maybe we need to set a min-width on the icon?
