### ISSUE TITLE
Bug: horizontal lines are truncated in table view

### ISSUE THREAD

**Issue by kamre** [mattermost/focalboard#1053]
**Summary:**
On narrow viewport when the table view has horizontal scroll the horizontal lines for table rows are truncated.

**Expected behavior:**
Horizontal lines for rows should be full width.

**Screenshots:**
![TableViewHorizontalLines](https://user-images.githubusercontent.com/5587620/130241531-69794dd3-41f8-4546-8247-9fe7267da43d.gif)

**Platform:**
 - Browser and version: Chrome 92
 - OS and version: Windows 10

**Comment by chenilim** [comment]
Thanks for finding and fixing this @kamre!
