### ISSUE TITLE
Feature Idea: Property value controls should highlight on hover in the card editor

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1057]
**Summary:**
In the card editor, hovering over a property name highlights it, but not when hovering over the value. this makes it hard to select the control to edit a property. The value control should have a similar gray highlight on hover.

https://user-images.githubusercontent.com/46905241/130283892-60ae3cf6-8ff5-4dcd-a730-65e1402adf51.mov

**How important this is to me and why:**

Importance: Medium

**Additional context / similar features:**
This should be a simple change, with a relatively high boost to usability.

**Comment by chenilim** [comment]
FYI @asaadmahmood, please update if you prefer a different approach.

**Comment by kamre** [comment]
@chenilim please assign to me, I have started working on this feature.

@asaadmahmood propose to also have the same width for buttons that are used for property name so that it looks similar to Notion:
![GH-1057-property-name-button-size](https://user-images.githubusercontent.com/5587620/130324811-b7e712e3-b7bd-4fea-8c21-5f3f2a61b592.gif)

**Comment by kamre** [comment]
@asaadmahmood I have added highlighting for the property values and here is how it looks for almost all empty values:
![image](https://user-images.githubusercontent.com/5587620/130326787-ba6b916a-2a36-48de-83ed-ad7d81af522e.png)
Look at how clickable areas vary in width! Should we change this to be more consistent?

**Comment by asaadmahmood** [comment]
@kamre Yes we should. They should ideally be consistent, I think we can use the email field as a standard and have that width.
And then obviously if the content expands that width, the container should also expand.
