### ISSUE TITLE
UI: Change the date range arrow (->)

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1058]
**Steps to reproduce the behavior:**
1. Open a card with a date range property
2. It shows as "Date -> Date", but the two-character text "arrow" is not vertically aligned

**Expected behavior:**
Replace the two-character text arrow with a single character, → (U+2192).

**Screenshots:**
<img width="387" alt="Date display" src="https://user-images.githubusercontent.com/46905241/130287035-05a16af3-ac76-4ed0-ba49-06705c8000fb.png">

**Platform:**
 - v0.9.0 RC6 on Community
 - Chrome 91 on macOS

**Comment by chenilim** [comment]
@asaadmahmood, this should be a simple fix, but what do you think? Any issues to consider? Or should we use another arrow or character? I think an arrow is better than the word "to" since it avoids the need for translation.

**Comment by asaadmahmood** [comment]
@chenilim Should probably be fine.

**Comment by chenilim** [comment]
Thanks Asaad! Putting this up for grabs. Should be a simple fix.

**Comment by ArpitRathore2020** [comment]
is this still open? I am a first-timer.

**Comment by jespino** [comment]
@ArpitRathore2020, sorry, looks like somebody else already submitted a PR for this.
