### ISSUE TITLE
Bug: Number property should show "Empty" placeholder in card editor

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1059]
**Steps to reproduce the behavior:**
1. Open a card with a number property that is not set
2. The field placeholder is blank

**Expected behavior:**
* The field placeholder should show the text "Empty" in the card editor for all property types
* However, the placeholder should be blank in tables

**Screenshots:**
<img width="391" alt="Number empty" src="https://user-images.githubusercontent.com/46905241/130287653-c3ff7c19-a8ef-49ff-b511-59c217e26472.png">

**Platform:**
 - Main branch build, Aug 20, 2021

**Additional context:**
This is a regression caused by #966, see [thread](https://community.mattermost.com/core/pl/aaz64xgkspri3ff8k7cxoatbmo).

The property value display logic needs to be refactored, probably with a "showEmptyPlaceholder" flag. True for the card editor, and false for tables.

**Comment by kamre** [comment]
@chenilim I can look into this while working on somewhat related #1057
