### ISSUE TITLE
Bug: Boards App Switcher should open /boards/...

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1060]
**Steps to reproduce the behavior:**
1. Select Boards from the app switcher
2. It opens `/plug/focalboard/...` (notice the URL on hover)

**Expected behavior:**
It should open a path under `/boards/...`

**Screenshots:**
<img width="469" alt="Boards url" src="https://user-images.githubusercontent.com/46905241/130294581-1763be88-6108-450f-bba4-a7eb4d591acb.png">

**Platform:**
 - v0.9.0 RC6 on Community

**Additional context:**
See [thread](https://community.mattermost.com/core/pl/k1ksyfrhmbb3te1izdxmw54w4r).

**Comment by jespino** [comment]
I added this to the thread, but I don't think this is needed. The generated url is correct because is how you register custom urls in plugins. We have to figure out how to solve this from the desktop app, but I don't think the solution needs to be change that url.

**Comment by chenilim** [comment]
Closing this as "by design" per the [thread here](https://community.mattermost.com/core/pl/jhm7px34a3yydpen5ioeiwytah).
