### ISSUE TITLE
Bug: Dragging a card's text content shows the entire card as its preview

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1072]
**Steps to reproduce the behavior:**
1. Open a card
2. Create multiple text content blocks
3. Drag a text content block to reorder it
4. The drag preview shows the entire card

**Expected behavior:**
The drag preview should show just the text content.

**Screenshots:**
https://user-images.githubusercontent.com/46905241/130526428-258789fd-fe11-472b-b9ef-54c8739752cc.mov

**Platform:**
 - v0.9.0 RC6 on Community
 - Chrome 91 on macOS

**Additional context:**
Dragging a checkbox, image or divider content block shows the correct preview.

**Comment by chenilim** [comment]
@jespino, I remember you had looked at a similar issue before. Do you think this is a regression? Would you like to take a look at it, or should we put it up for grabs?

**Comment by kamre** [comment]
@jespino @chenilim looks like [this issue](https://github.com/react-dnd/react-dnd/issues/832#issuecomment-442071628) is related 

So adding this style seems to fix the issue on Chrome at least:
```ts
<div
    ref={itemRef}
    className={className}
    style={{transform: 'translate3d(0, 0, 0)'}}  // <=== added this style
>
```

**Comment by jespino** [comment]
@kamre thanks! I'll apply that solution.

**Comment by ogi-m** [comment]
Tested and passed on v0.9.0 RC8 - only the selected text is shown in the drag preview.
