### ISSUE TITLE
Table Calculations: Checkbox Property

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#1082]
**Summary:**
Implement the following table calculation functions for the checkbox type property

1. **Checked**: Count of a checkbox (boolean) property that is checked
1. **Unchecked**: Count of a checkbox (boolean) property that is unchecked
1. **Percent checked**: Percentage of a checkbox (boolean) property that is checked
1. **Percent unchecked**: Percentage of a checkbox (boolean) property that is unchecked

**Additional context / similar features:**
The calculations go in here - https://github.com/mattermost/focalboard/blob/main/webapp/src/components/calculations/calculations.ts

**Comment by aditya2712** [comment]
Is this issue completed? I can see commits related to this issue.

**Comment by nishantwrp** [comment]
++ I think this issue can be closed as #1323 is merged.

**Comment by sbishel** [comment]
completed.
