### ISSUE TITLE
Bug: Channel header hint text should read "Boards Workspace"

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1086]
**Steps to reproduce the behavior:**
1. Hover over the Boards channel header icon
2. It reads "Focalboard Workspace"

**Expected behavior:**
It should say "Boards Workspace", per the branding update

**Screenshots:**
<img width="169" alt="Channel header hint" src="https://user-images.githubusercontent.com/46905241/130669704-9d46572f-c2d4-4866-8c8a-46eaec01c844.png">

**Platform:**
 - v0.9.0 RC6 on Community

**Comment by ogi-m** [comment]
Tested and passed on v0.9.0 RC8 - button hint now says "Boards".
