### ISSUE TITLE
Getting Blank screen on Mac app if port 8088 is in use

### ISSUE THREAD

**Issue by rdrahul** [mattermost/focalboard#109]
**Summary:**
after opening the app there is just a blank screen. rest of the ui does not load.

**Steps to reproduce the behavior:**
1. Go to Appstore
2. Install focalboard
3. Open focalboard.
4. Focalboard load with blank screen no ui is visible

**Expected behavior:**
After opening the ui should load properly and i should be able to create the board and add tasks.

**Screenshots:**
![image](https://user-images.githubusercontent.com/11667215/111671049-87a4b380-883e-11eb-98e1-90f4ce1e8b67.png)

**Platform:**
 - Browser and version: Chrome Version 89.0.4389.90
 - OS and version: macOS 10.15.7

**Comment by chenilim** [comment]
Thanks @rdrahul for reporting this! A few things to try:
* Select `Home` from the `File` menu, or relaunch the app
* Is the page still blank?

The Focalboard Mac app uses port 8088 to serve the UI (in the future we plan to have this dynamic). Make sure there isn't another service using the port. E.g. open a browser to http://localhost:8088 to test.

**Comment by rdrahul** [comment]
Hey thanks working now.  Something was running on 8088.

**Comment by gaberogan** [comment]
Same for me something was running on 8088. I have no clue what else could have caused that except Focalboard itself though. I imagine this would turn a lot of people off as this happens the first time you open the Mac app. (i'm on Big Sur btw)

**Comment by chenilim** [comment]
Updating the title to reflect issue. We should use a random unassigned port like the Win32 app does.
