### ISSUE TITLE
Bug: values of properties in the card dialog are not aligned vertically

### ISSUE THREAD

**Issue by kamre** [mattermost/focalboard#1096]
**Summary:**
In the card dialog not all types of properties are aligned vertically.

**Steps to reproduce the behavior:**
1. Create empty board
2. Add card with properties of different types
3. Look at the placeholders or checkbox switcher
4. Elements for values are not aligned vertically

**Expected behavior:**
Elements for values should be aligned vertically

**Screenshots:**
![image](https://user-images.githubusercontent.com/5587620/130805308-45db3a4c-5f6e-4c77-bf52-ddbe43e94e24.png)

**Platform:**
 - Browser and version: Chrome 92
 - OS and version: Windows 10

**Additional context:**
Reproducible on `v0.9.0-rc7`

**Comment by chenilim** [comment]
Thanks @kamre! What do you think @asaadmahmood? I don't think this is necessarily a P1 for 0.9, but LMK if you want to take care of this during a pass, or rather put it up for grabs. Thanks.
