### ISSUE TITLE
Bug: Hard to read tags in default theme settings

### ISSUE THREAD

**Issue by it33** [mattermost/focalboard#1098]
**Summary:**
Hard to read tags in default theme settings 

**Steps to reproduce the behavior:**
![image](https://user-images.githubusercontent.com/177788/130810823-60097194-d99f-4413-a386-828842275212.png)
![image](https://user-images.githubusercontent.com/177788/130810860-c698044a-061c-4869-a6fa-38b763176756.png)

**Expected behavior:**
Not hard to read tags in default theme settings 

**Screenshots:**
See repro steps 

**Platform:**
 - Browser and version: [e.g. Chrome 88, Safari 12]
 
![image](https://user-images.githubusercontent.com/177788/130811047-12d90e99-b97b-44ce-87b5-1b7e35d277c6.png)

 - OS and version: [e.g. Windows, macOS 10.15.7, iOS 13.1]
![image](https://user-images.githubusercontent.com/177788/130810999-e6b02884-0573-4886-a5f0-97cb619273da.png)

**Additional context:**

**Comment by chenilim** [comment]
This should have been resolved with the move to using Mattermost themes.
