### ISSUE TITLE
Feature request: Multiple Select property type

### ISSUE THREAD

**Issue by Victor239** [mattermost/focalboard#110]
Currently there's only a (Single) Select property type, a Multiple Select property would instead allow you to select multiple of the available options.

**Comment by chenilim** [comment]
Thanks @Victor239! Yup, this is something we expect to support. Have to think about how to best represent this in the object model, i.e. would it be better to represent all select properties as multi-select, but limit some to just one in the UI? This affects the filter and display logic.

**Comment by Victor239** [comment]
Airtable shows them all the options selected in the cell, but it's not wrapped so you might have to adjust the column width manually to show them all.

**Comment by alerque** [comment]
Multi-select appears to be implemented already and this issue status is stale. I believe there is a related issue somewhere about grouping by multi-select fields, but I can't find it. Perhaps that was in one of the project roadmap boards...
