### ISSUE TITLE
Bug: Remove additional plugin steps

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1105]
**Steps to reproduce the behavior:**
1. Open the Focalboard plugin page in the System Console
2. It shows a section with "For additional setup steps, please see here"

**Expected behavior:**
That section should be removed now that the additional websocket config is no longer required by [PR-1079](https://github.com/mattermost/focalboard/pull/1079).

**Screenshots:**
<img width="560" alt="Focalboard plugin additional steps" src="https://user-images.githubusercontent.com/46905241/130859481-d739d85f-46f2-4678-8286-a69af5e8d305.png">

**Platform:**
 - v0.9.0 RC7

**Comment by justinegeffen** [comment]
Thanks, @chenilim! Change is noted; no docs impact.
