### ISSUE TITLE
Bug: Crash when grouping a table with an incomplete view

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1106]
**Steps to reproduce the behavior:**
1. Download, unzip and import the attached archive (this has a view without the `collapsedOptionIds` property)
[Table without collapsedOptionIds.focalboard.zip](https://github.com/mattermost/focalboard/files/7050056/Table.without.collapsedOptionIds.focalboard.zip)

2. Open the table
3. Group by Status (or any property)
4. Crash

**Expected behavior:**
The app should not crash

**Platform:**
 - v0.9.0 RC7
 - Chrome 91 on macOS

**Additional context:**
This archive simulates a legacy block data without all the properties.

**Comment by ogi-m** [comment]
Tested and passed on v0.9.0 RC8 - items grouped as expected, no crash.
