### ISSUE TITLE
Bug: tooltip popup height is too small

### ISSUE THREAD

**Issue by kamre** [mattermost/focalboard#1111]
**Summary:**
Tooltip popup for property name in kanban card has too small height.

**Screenshots:**
![image](https://user-images.githubusercontent.com/5587620/130969026-47329a94-761a-4836-82a8-cee65a0e702b.png)

**Platform:**
 - Browser and version: Chrome 92
 - OS and version: Windows 10

**Additional context:**
Regression caused by #1078

**Comment by chenilim** [comment]
Hi @kamre, was this repro on the Personal Server v0.9.0 RC7? I don't see a repro on v0.9.0 RC8 (community server or Mac app), nor on RC7 Mac app. In any case, the fix in the PR looks straight forward, but I'll defer to @asaadmahmood to review. Thanks.

**Comment by kamre** [comment]
Hello @chenilim, this is a recent regression in `main` and not reproduced on `v0.9.0`
