### ISSUE TITLE
Bug: Sort and Filter buttons not highlighted when set

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1112]
This repros with the plugin, but not Personal Server:

**Steps to reproduce the behavior:**
1. Open a board or a table
2. Set the filter and the sort settings from the header
3. The buttons are not highlighted

**Expected behavior:**
The Filter and Sort buttons should be highlighted (bold) when set.

**Screenshots:**
Plugin:
<img width="484" alt="Plugin filter sort" src="https://user-images.githubusercontent.com/46905241/130990102-0efd8c5c-45d6-4258-916b-e37f8262ac09.png">

Personal Server:
<img width="301" alt="Personal Server filter sort" src="https://user-images.githubusercontent.com/46905241/130990152-5e593aa8-9142-47cb-8689-a3de03d64a33.png">

**Platform:**
 - v0.9.0 RC7 on Community
 - Chrome 91 on macOS

**Comment by ogi-m** [comment]
Verified on v0.9.0 RC9 - Sort/Filter is highlighted if sorting/filtering is applied
