### ISSUE TITLE
Bug: global header user menu is not fully visible

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/focalboard#1122]
**Summary:**
When clicking on the user avatar at the global header top right, the menu is shown half outside the screen. 

**Expected behavior:**
The menu should be fully visible inside the screen.

**Screenshots:**
![image](https://user-images.githubusercontent.com/223323/131104710-5ef8f1d9-25fd-4ea8-a405-4133494bb740.png)

**Platform:**
- Community daily, Focalboard 0.9.0

**Comment by chenilim** [comment]
Thanks @mgdelacroix! Sorry, I filed a dup in #1131 before I saw this and Scott's already submitted a PR to fix that. To avoid confusion, I'm closing this as a dup of #1131.
