### ISSUE TITLE
Bug: Refresh required after every action

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1125]
**Summary:**
After every action (e.g. board creation, card creation, moving a card, etc), the user needs to refresh to see the action executed.

**Steps to reproduce the behavior:**
1. Install latest plugin build from main
2. Open boards
3. Click _+Add Board_ and select a template

**Expected behavior:**
New board opens and appears in the sidebar without having to refresh

**Platform:**
latest main build on mattermost master

**Comment by mgdelacroix** [comment]
It was a broader problem that the one described on #1109, will try and repro that one with the patch applied
