### ISSUE TITLE
Bug: Focalboard is not inheriting theme from Mattermost if NOT opened via global header

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#1129]
**Summary:**
Bug: Focalboard is not inheriting theme from Mattermost if NOT opened via global header

**Expected behavior:**
The theme should be inherited from Mattermost.

**Screenshots:**
![Screenshot 2021-08-25 at 8 36 50 PM](https://user-images.githubusercontent.com/11034289/131353568-9e6c0082-da9d-43eb-ac9f-be68a3af7526.png)
![Screenshot 2021-08-25 at 8 38 04 PM](https://user-images.githubusercontent.com/11034289/131353572-a4fc5402-022b-4f89-b130-cbca1d4a80dc.png)

**Platform:**
 - Chrome Version 92.0.4515.159 (Official Build) (x86_64)
 - MacOSX Big Sur 11.4

**Comment by chenilim** [comment]
@jespino, are you still looking into theme issues? Also, when opening Boards via the Channel Header, it doesn't appear to inherit the Mattermost theme either. cc @ogi-m, @sbishel.

**Comment by chenilim** [comment]
We should default to the new demin theme colors in any case.

**Comment by jespino** [comment]
This bug is because the user has no theme configured in the database, so it is using the default theme in mattermost and the default theme in focalboard. that should be fixed making the default theme match the mattermost channels theme.
