### ISSUE TITLE
Feature Request: Add possibility to delete tasks in table view (like in board view)

### ISSUE THREAD

**Issue by dataCobra** [mattermost/focalboard#113]
**Summary:**
When in table view there is no option to easily delete a task. Before you can delete a task you need to open it.

**Steps to reproduce the behavior:**
1. Open a table view with tasks
2. Find option to delete task in table view
3. Need to open the task
4. Click on "3 dot" drop-down menu
5. Click delete

**Expected behavior:**
It would be nice to have the option to delete them directly in table view. Maybe with a "3 dot" drop-down menu like it
is in board view at the end of the row.

**Comment by arvinDarmawan** [comment]
Hi  @chenilim @jespino   could you assign it to me? I want to try it

**Comment by jespino** [comment]
Hi @arvinDarmawan, sure i can assign it to you. Let me know if you need anything from us.

**Comment by arvinDarmawan** [comment]
Hi @jespino , is it the expected result ?
I just using MenuWrapper component in tableRow component (I'm not yet implement the delete functionality, just the UI)

<img width="1133" alt="Screen Shot 2021-07-05 at 09 40 27" src="https://user-images.githubusercontent.com/28821618/124410697-3846ac80-dd75-11eb-943e-68cfc2e64f6f.png">

**Comment by harshilsharma63** [comment]
@dataCobra thanks for the implementation. This is certainly a useful feature.

I don't like the design though. It works fine when you only have as many columns visible as the width of the browser. When you have more, you need to perform a horizontal scroll to reach the menu, which removes all the convenience.

Let's wait for @asaadmahmood to provide a design for this.

**Comment by asaadmahmood** [comment]
Yup, will have a look at this.

**Comment by dataCobra** [comment]
Thanks for the mention, but I didn't implement the feature that was @arvinDarmawan. :+1:

**Comment by asaadmahmood** [comment]
@jespino @harshilsharma63 @arvinDarmawan This is what I'm thinking about the delete option placement.
https://www.figma.com/proto/UPbYxPDsg1aIzozyysRPeO/Focalboard-Base-Design?page-id=11%3A3265&node-id=11%3A3273&viewport=14926%2C8782%2C5.783653736114502&scaling=min-zoom

So we show the icon buttons on the left when hovering a row.

**Comment by arvinDarmawan** [comment]
> @jespino @harshilsharma63 @arvinDarmawan This is what I'm thinking about the delete option placement.
> https://www.figma.com/proto/UPbYxPDsg1aIzozyysRPeO/Focalboard-Base-Design?page-id=11%3A3265&node-id=11%3A3273&viewport=14926%2C8782%2C5.783653736114502&scaling=min-zoom
> 
> So we show the icon buttons on the left when hovering a row.
> Obviously we can ignore the add below and the drag options if we don't have these yet

Oke, i will check it

**Comment by jespino** [comment]
@arvinDarmawan Thanks!, by the way, sorry for the inconveniences, we have talked about it, to try to avoid not-fully-defined help wanted tickets.

**Comment by arvinDarmawan** [comment]
> @jespino @harshilsharma63 @arvinDarmawan This is what I'm thinking about the delete option placement.
> https://www.figma.com/proto/UPbYxPDsg1aIzozyysRPeO/Focalboard-Base-Design?page-id=11%3A3265&node-id=11%3A3273&viewport=14926%2C8782%2C5.783653736114502&scaling=min-zoom
> 

> So we show the icon buttons on the left when hovering a row.
> Obviously we can ignore the add below and the drag options if we don't have these yet


Hi @asaadmahmood  is this the right image from figma ? it seems different if I click the link.

<img width="1303" alt="Screen Shot 2021-07-14 at 18 41 15" src="https://user-images.githubusercontent.com/28821618/125616318-709a01dd-4beb-44bb-91fa-c61b5352e89f.png">

**Comment by asaadmahmood** [comment]
Sorry @arvinDarmawan this is the link:
https://www.figma.com/file/nIyq6YPnKUxurCr0AyklZj/Issue-633-Sidebar-Active-State-Copy?node-id=101%3A7882

**Comment by arvinDarmawan** [comment]
hi @harshilsharma63  @jespino  to implement this style, I think that we  can't create hidden <td> to store the row option except we add hidden <th> in the left side too, right ? What I see in current code the  table column is generated dynamically  from db since we can add new column dynamically, right ?

**Comment by jespino** [comment]
@arvinDarmawan we can add a column (no necesarilly hidden) there, with a fixed width, and show/hide the icons based on the hover state.

**Comment by arvinDarmawan** [comment]
> @arvinDarmawan we can add a column (no necesarilly hidden) there, with a fixed width, and show/hide the icons based on the hover state.
 @jespino , if we add new column, it means we need to add new TableRowHeader too, right?
Do we need to store this  new column  in database too ?

**Comment by harshilsharma63** [comment]
> Do we need to store this  new column  in database too ?

No, we do not want to store this column in database. Its something you can add to the list of columns in each row.

For reference, see how we add the first column in table view here - https://github.com/mattermost/focalboard/blob/77a90a473c5eb016b0ccb0c33f7151b27b6667ef/webapp/src/components/table/tableRow.tsx#L83

**Comment by wiggin77** [comment]
Reassigning as this has not been worked on since July.

**Comment by Rajat-Dabade** [comment]
Hello @wiggin77, can I take this issue and work on it?

**Comment by Rajat-Dabade** [comment]
I've added the delete feature in the Table view. let me know if it looks okay?

##### Added delete feature in Table view
![Screenshot from 2022-02-23 09-07-37](https://user-images.githubusercontent.com/26198062/155261059-3f4f8d1f-2202-4921-aa79-d214fb2fd32e.png)

##### Deleting the card with confirmation pop-up
![Screenshot from 2022-02-23 09-08-11](https://user-images.githubusercontent.com/26198062/155261848-1ca43240-07e9-48af-b7cc-68f4a3002b70.png)

##### After deletion
![Screenshot from 2022-02-23 09-08-22](https://user-images.githubusercontent.com/26198062/155261925-6f9e1e86-f0f0-403f-8e6f-6499de93eaa8.png)

**Comment by uptonking** [comment]
- delete in table is very userful. 
- when can this feature be merged?

**Comment by angeljsnava** [comment]
Hello, there is a way to multi-select tasks in table view to delete the selected tasks as well?
