### ISSUE TITLE
Bug: today and date from the input are not selected in the day picker calendar

### ISSUE THREAD

**Issue by kamre** [mattermost/focalboard#1130]
**Summary:**
Day picker calendar doesn't select the date when today button is clicked or the date is entered in the input field.

**Steps to reproduce the behavior:**
1. Create empty board
2. Create new card and add Date property
3. Start editing date
4. Clicking _Today_ button doesn't select the date in the calendar
5. Entering the date in the input field changes the value but it is not selected in the calendar 

**Expected behavior:**
Today should select the date in the calendar and update the value.
Entered date should be selected in the calendar.

**Screenshots:**
Today:
![TodayCalendar](https://user-images.githubusercontent.com/5587620/131356627-e338bb57-5246-4a18-851c-f159ab41e6ff.gif)

Input:
![InputDateCalendar](https://user-images.githubusercontent.com/5587620/131357137-126a18b4-1e3c-402d-8c6b-88005823fe3e.gif)

**Platform:**
 - Browser and version: Chrome 92
 - OS and version: Windows 10

**Additional context:**
Reproducible on `v0.9.0-rc8`

**Comment by chenilim** [comment]
Thanks @kamre! I'd classify these as sev-2 bugs, and am putting them up for grabs. FYI @sbishel, @ogi-m, @asaadmahmood.
