### ISSUE TITLE
Bug: "Something went wrong" error after converting multi select property to URL

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1136]
**Summary:**
Converting multiselect property to URL causes the board to return "Something went wrong" error with no apparent way to fix it. Reopening the board results in the same error.

**Steps to reproduce the behavior:**
1. Open boards from Mattermost
2. Create a card
3. Create a URL property and add a link to the card
4. Change the URL property to multi select
5. Change the property back from multi select to URL

**Expected behavior:**
"Something went wrong" error is displayed and there's no way to access the board.

**Screenshots:**
![SharedScreenshot](https://user-images.githubusercontent.com/15314183/131502993-286284ab-0538-4507-af83-3275bbdd1810.jpg)

**Platform:**
Focalboard plugin v0.9.0 RC8 on community-daily (master)

**Comment by chenilim** [comment]
We should at least not permanently crash on load.

**Comment by sbishel** [comment]
@ogi-m I am not able to reproduce, tried on main as well as community-daily. We can look at tomorrow.

**Comment by ogi-m** [comment]
Tested and passed on v0.9.0 RC12 
- not seeing the error anymore
- property converted back to URL
