### ISSUE TITLE
Bug: Link icon placed far away from the URL

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1137]
**Summary:**
Link icon is placed to the far right of the card regardless of the length of the URL.

**Steps to reproduce the behavior:**
1. Open a board
2. Create a URL property on a card
3. Add a short URL to the URL property field
4. Observe the link icon on the URL property

**Expected behavior:**
I expect the link icon to be placed near the end of the entered URL

**Screenshots:**
![card_url_property](https://user-images.githubusercontent.com/15314183/131503842-74b72c92-b166-4dc1-a2ef-facac7eeb939.jpg)

**Platform:**
Focalboard plugin v0.9.0 RC8 on community-daily (master)

**Additional context:**
Probably related to https://github.com/mattermost/focalboard/pull/1047

**Comment by kamre** [comment]
This will be fixed in #1065 where autosize for input field was added.

**Comment by ogi-m** [comment]
This was fixed by https://github.com/mattermost/focalboard/pull/1065
