### ISSUE TITLE
Personal Server Installation Guide does not link to the latest release

### ISSUE THREAD

**Issue by dataCobra** [mattermost/focalboard#114]
**Summary:**
While installing the focalboard server via the guide I stumbled across the problem that the provided release is not the latest.
Furthermore the release was packed into two archives with zip and tar.gz. Like mentioned in #77.

**Steps to reproduce the behavior:**
1. Go to https://www.focalboard.com/download/personal-edition/ubuntu/
2. Scroll down to "Install Focalboard"
3. Check link "Download the Ubuntu archive package" + Steps to download and unpack the archive are wrong
4. See that the link and wget are pointing to an old version and that there is only the command for unpacking tar.gz not zip

**Expected behavior:**
The link and wget should point to the current release of focalboard. Even pointing to the latest release page of GitHub is better
than the old version pointer.

**Comment by chenilim** [comment]
Thanks @dataCobra! I'll update the docs. We might move this again in the future, but the latest binaries will be in the [GitHub releases](https://github.com/mattermost/focalboard/releases) for now.
