### ISSUE TITLE
Bug: Web app crashes on updateFavicon

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#1141]
**Summary:**
Seeing a couple crashes related to favicon updating today on community-daily. Seem to happen when I click into some channels/threads but not sure of exact repro steps. Anyone else seeing it or have an idea what might cause it?

**Steps to reproduce the behavior:**
1. Go to any channel.
2. Click global header, and open focalboard for that channel.
3. Open a card.
4. Click the back button 2 times to go back to original channel.
5. Observe crash

OR

1. Having some mentions in Channels so the favicon has the red dot
2. Open a board and add a personal tasks view which will change the favicon
3. Switch back to channels and read all the mentions to cause it to try to change the favicon
4. Crash

**Expected behavior:**
Able to change back to channels without crash

**Screenshots:**
<img width="1486" alt="Screen Shot 2021-08-12 at 10 01 25 AM" src="https://user-images.githubusercontent.com/12704875/131557527-a43f5c40-70a9-4f00-bb05-b0d34fe980c4.png">
<img width="1491" alt="Screen Shot 2021-08-12 at 11 30 39 AM" src="https://user-images.githubusercontent.com/12704875/131557523-ae0b0c32-09d7-4000-a6db-39480cba757b.png">

**Additional context:**
Original Jira Ticket
https://mattermost.atlassian.net/browse/MM-37924

**Comment by sbishel** [comment]
Per original Jira ticket - 

This is happening because Focalboard removes the link tags in the HTML that the web app uses to control the favicon ([link](https://github.com/mattermost/focalboard/blob/e10229031feb5029ee3c36bb9a28070d7f8d8c14/mattermost-plugin/webapp/src/index.tsx#L66)), so after viewing Focalboard, any attempt to update the favicon from the web app side causes a crash ([link](https://github.com/mattermost/mattermost-webapp/blob/master/components/favicon_title_handler/favicon_title_handler.tsx#L126).) I think Focalboard needs to be updated to restore those when it’s closed, or we need to change both apps to use the same mechanism for setting the favicon.

**Comment by chenilim** [comment]
Unless someone has strong opinions, I propose just disabling the Focalboard favicon code when running as a plugin. The favicon is currently used to communicate if a user has unread messages, and in the long run that should be consistent.

In any case, agree this needs to be fixed for 0.9 / 6.0. cc @asaadmahmood, @jespino.

**Comment by asaadmahmood** [comment]
Disabling it makes sense to me @chenilim

**Comment by ogi-m** [comment]
Verified on RC11 - Mattermost icon is now shown in Boards
