### ISSUE TITLE
Bug: Navigation with Desktop App doesn't work correctly.

### ISSUE THREAD

**Issue by devinbinnie** [mattermost/focalboard#1142]
**Summary:**
Focalboard uses the `react-router-dom` history module to navigate between its pages without refreshing. Unfortunately the desktop app is not aware of the changes this module makes and cannot facilitate any navigation between tabs this way.

We need to either:
a) Switch Focalboard to use the provided `browserHistory` module in the webapp (under `window.WebappUtils.browserHistory`)
b) Create a shim around the `react-router-dom/history` module that will do the same thing as the webapp to facilitate desktop navigation between tabs.

**Steps to reproduce the behavior:**
Click on the Global Header and go to Boards OR
Click on a link in Channels that links to a board

**Expected behavior:**
Boards should open on the intended board.

**Observed behavior:**
With the first step, Boards opens in the wrong tab because it is doing a redirect
With the second, the Boards tab opens but doesn't navigate to the desired link

**Platform:**
Desktop App v5.0

**Comment by sbishel** [comment]
@harshilsharma63 Can you take a look.

**Comment by chenilim** [comment]
Note (from @devinbinnie): The Desktop 5.0 changes are currently in this PR: [Desktop App PR-1680](https://github.com/mattermost/desktop/pull/1680). There will eventually (eta tomorrow) be a link in the PR to download the Desktop App to repro.

**Comment by harshilsharma63** [comment]
@devinbinnie I'm working on this once. I'll be contacting you to verify the changes I'll be making.
