### ISSUE TITLE
Show all workspaces (even with no boards) in the workspace picker

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1145]
**Summary:**
The Workspace Switcher (in PR #1052) currently only returns workspaces (channels the user is a member of) with one or more boards. Let's change this to:
* Return all user channels (even with no boards) instead, and
* Display workspaces with no boards below the ones that do in the dropdown

**How important this is to me and why:**

Importance: High

The main reason for this is so users can create boards in workspaces (channels) that don't currently have boards, without needing to switch to the Channels UI.

**Additional context / similar features:**
Discussed in the Sep 2 Dev meeting, and is a step towards the [v6.0 nav update spec](https://docs.google.com/document/d/1Q0eujL89EU39Z3R1mer-tZMksEbyLtPGNqO-JsAe9Gg/edit#).

**Comment by chenilim** [comment]
Filing this issue to track as discussed @harshilsharma63. FYI @asaadmahmood, @sbishel, @ogi-m.

**Comment by harshilsharma63** [comment]
I'll be working on this independent of the original workspace switcher. That once can be tested and merged while this one continues in development.
