### ISSUE TITLE
Bug: Use the compass-icons from mattermost-webapp when we are in plugin mode

### ISSUE THREAD

**Issue by jespino** [mattermost/focalboard#1153]
**Summary:**
When we are in plugin mode, we are using our own compass-icons version and that is overwritting the icons font from mattermost-webapp. Focalboard should share the compass-icons from mattermost-webapp instead of using its own version.

**Comment by chenilim** [comment]
Thanks for filing this @jespino. Should this be fixed for v0.9? I assume so, otherwise we will continuously run into conflicts. Assigning to @sbishel to reassign. Also, here's the [link to thread](https://community.mattermost.com/core/pl/5c8rwawnib8pmy8j47maaf63sy) with more details.
