### ISSUE TITLE
Bug: Refresh required after every action in HA

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1154]
**Summary:**
Same as the [previously reported bug](https://github.com/mattermost/focalboard/issues/1125), but it only reproduces in HA environment

**Steps to reproduce the behavior:**
1. Install latest plugin build from main in an HA environment
2. Open boards
3. Click +Add Board and select a template

**Expected behavior:**
New board opens and appears in the sidebar without having to refresh

**Platform:**
latest main build on HA master

**Comment by chenilim** [comment]
Thanks @ogi-m. We can discuss more at the team meeting tomorrow. But it sounds like we need to fix this for v0.9. Do you have a test environment set up with the repro? cc @sbishel, @jespino, @mgdelacroix.

**Comment by ogi-m** [comment]
@chenilim I've created an HA test environment with the cloud plugin [here](https://boards-ha.test.mattermost.cloud/) ( sysadmin / Sys@dmin123 ).
