### ISSUE TITLE
Add link to Give Feedback form

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1161]
**Summary:**
Add a link to give feedback.

**Additional context / similar features:**
Provide a low-friction way for our users to provide product feedback.

**Comment by ogi-m** [comment]
Verified on v0.9.0 RC9 
- _Give Feedback_ link is present next to the version in the top right
- Opens a feedback form in google docs

Possible enhancement - should the form open in a new tab maybe? @chenilim @asaadmahmood

**Comment by chenilim** [comment]
Thanks @ogi-m. Agree that opening in a new tab is preferable. I'll fix it with #1196.
