### ISSUE TITLE
Bug: User dialog has large extra white-space

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1172]
**Steps to reproduce the behavior:**
1. Open Boards
2. Click on the user avatar at the top right
3. The user dialog has a large extra space under "Do not disturb"

**Expected behavior:**
Should look the same as the dialog in Channels

**Screenshots:**
<img width="295" alt="User dialog 1" src="https://user-images.githubusercontent.com/46905241/132767422-e9eac654-cf6c-464e-83f6-13740ec59259.png">

**Platform:**
 - v0.9.0 RC9 on Community
 - Chrome 91 on macOS

**Comment by chenilim** [comment]
@asaadmahmood, do you have bandwidth to take a look at this? I suspect it's a regression from #1132. FYI @sbishel, @ogi-m.

**Comment by ogi-m** [comment]
Tested and passed on v0.9.0 RC11
