### ISSUE TITLE
Bug: Screen position judders when hovering over "Show Description" button

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1173]
**Steps to reproduce the behavior:**
1. Open a board or table
2. Hover over the "Show Description" button at the top
3. The content below is pushed down, resulting in a visual judder

**Expected behavior:**
The other page content location should not change on hover.

**Screenshots:**
https://user-images.githubusercontent.com/46905241/132768286-e9e6cb88-9b76-4879-b6ed-6cb5699f2dad.mov

**Platform:**
 - v0.9.0 RC9 on Community
 - Chrome 91 on macOS

**Additional context:**
This is a regression from v0.8

**Comment by chenilim** [comment]
@asaadmahmood, this is similar to #1024, but is a regression. I think we can live with this for v0.9, but it's a poor first impression, and if you think it's an easy and safe fix, we can take it for v0.9. cc @sbishel, @ogi-m.

**Comment by kamre** [comment]
The reason is that `min-height` for the container is `28px` and button `height` [was changed](https://github.com/mattermost/focalboard/pull/1138/files#diff-3821ab810407205c0e9df9f20311ddedf382208a89ca3e90a2935573e698da46R16) to `32px`.
Possible fix:
```diff
diff --git a/webapp/src/components/viewTitle.scss b/webapp/src/components/viewTitle.scss
--- a/webapp/src/components/viewTitle.scss	(revision 09e35ae7c2a8e71cd0aaabdc2abc8644d15ebea9)
+++ b/webapp/src/components/viewTitle.scss	(date 1631252076594)
@@ -9,7 +9,7 @@
 
     > .add-buttons {
         flex-direction: row;
-        min-height: 28px;
+        min-height: 32px;
         color: rgba(var(--center-channel-color-rgb), 0.4);
         width: 100%;
         align-items: flex-start;
@@ -23,7 +23,6 @@
         }
 
         .Button {
-            min-height: 28px;
             display: none;
             line-height: 1;
         }
```

**Comment by ogi-m** [comment]
Tested and passed on v0.9.0 RC11
