### ISSUE TITLE
Bug: "Set language" menu opens over the root menu and pushes it to the left

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1182]
**Steps to reproduce the behavior:**
1. Open Boards from Mattermost
2. Click on the Settings button in the top right corner
3. Move the mouse over "Set Language" option

**Expected behavior:**
Menu should open to the left of the settings menu (as the arrow indicates)

**Screenshots:**
https://user-images.githubusercontent.com/15314183/132895008-9c926916-f6d8-4616-97bf-102265f19515.mp4

**Platform:**
 - Plugin v0.9.0 RC9 on master

**Comment by chenilim** [comment]
Thanks @ogi-m! This is a regression from RC8, and should be fixed for v0.9. Might be related to #1172, and hopefully is just a CSS change. @asaadmahmood, could you help investigate? I'm concerned that this bug could affect other UI as well. cc @sbishel, @jespino.

**Comment by moicool6** [comment]
Is it impossible to save the record of setting language, and you need to set it again every time.

**Comment by chenilim** [comment]
Thanks @moicool6! What version are you running? I'm not able to repro this on v0.9.0 RC9 (running as a plugin on our community server). Are you running one of the desktop apps or Personal Server 0.9.0 RC9? Thanks.

**Comment by ogi-m** [comment]
Tested and passed on v0.9.0 RC11
