### ISSUE TITLE
Feature Idea: Get the binary back ?

### ISSUE THREAD

**Issue by paulpremont** [mattermost/focalboard#1183]
I'm in a hurry to test that soft.

But when you read the documentation (https://www.focalboard.com/download/personal-edition/desktop/) , it says that you can get the focalboard-linux.tar.gz archive.

I don't find this file from the link of the documentation.

Is is possible to upload it ?

Many thanks.

**Comment by chenilim** [comment]
Thanks @paulpremont, and sorry for the confusion. The latest published release is [v0.8.0](https://github.com/mattermost/focalboard/releases/tag/v0.8.0), which includes all the binaries. Some of the releases are "plugin-only" and don't have the desktop binaries.

If you want to check out the latest (soon to be released) build, that's currently [v0.9.0 RC9](https://github.com/mattermost/focalboard/releases/tag/v0.9.0-rc9).

Please reopen or LMK if you run into any issues. Thanks!
