### ISSUE TITLE
Bug: kanban column header is overlapping with the scrolled content

### ISSUE THREAD

**Issue by kamre** [mattermost/focalboard#1189]
**Steps to reproduce the behavior:**
1. Go to [v1 Focalboard (read-only)](https://community.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/shared/47aa9bb4-6967-4a96-83c7-11bd6b20f1eb/7e38eab4-890a-4fc3-8f48-a1f9bd1ab822?r=762db9c6-305c-4d13-8ce6-9f11e5232c24)
2. Select _By Status_ view
3. Scroll horizontally to see the last column
4. Scroll vertically so that some cards go above the column headers
5. Look at the overlap between the column header and the card

**Expected behavior:**
Card content should be below column header and should not be visible.

**Screenshots:**
![KanbanHeadersOverlap](https://user-images.githubusercontent.com/5587620/133043615-ae765088-d5f8-4e7f-bf1d-5190e25d9bde.gif)

**Platform:**
 - Browser and version: Chrome 91
 - OS and version: Windows 10

**Additional context:**
**This only happens when there is a horizontal scroll bar and some column headers are not visible initially.**
Seems to be the issue similar to #1053 but with kanban board.

**Comment by ogi-m** [comment]
This is not limited to read-only view, I can repro in regular view as well
cc @chenilim

**Comment by chenilim** [comment]
Thanks @kamre and @ogi-m! @asaadmahmood, could you investigate this too? It seems there might be some z-order issues in the UI. @ogi-m, what platform were you able to repro this on? I couldn't repro on Mac (Chrome, FF, Safari), or Windows Edge.

**Comment by ogi-m** [comment]
@chenilim I can see it on Windows Chrome, Firefox & Edge. Try scaling down the browser width and make sure it's scrolled all the way to the right horizontally, that should help repro.

**Comment by ogi-m** [comment]
Tested and passed on v0.9.0 RC11
