### ISSUE TITLE
Bug: menu for card content item is covered with other items

### ISSUE THREAD

**Issue by kamre** [mattermost/focalboard#1191]
**Steps to reproduce the behavior:**
1. Create new empty board
2. Create new card
3. Add couple of checkbox items to card content
4. Activate popup menu for the first item
5. Menu is covered with other items below the current one

**Expected behavior:**
Menu should be on top of any other items

**Screenshots:**
![CardContentItemMenu](https://user-images.githubusercontent.com/5587620/133073715-1b9f8163-bd68-4c91-9242-220773c25673.gif)

**Platform:**
 - Browser and version: Chrome 92
 - OS and version: Windows 10

**Additional context:**
Reproducible on `v0.9.0`
Regression was introduced by fix in #1097

**Comment by chenilim** [comment]
Thanks @kamre! Confirmed this is an issue on Chrome Mac as well. Looks like the menu z-order is incorrect? @asaadmahmood, this may be related to the other menu issues, and we should fix for v0.9. Could you take a quick look? If it's a more involved fix, let's discuss. cc @sbishel, @ogi-m.

**Comment by ogi-m** [comment]
Tested and passed on v0.9.0 RC11
