### ISSUE TITLE
Feature Idea: Provide way to go back or cancel after clicking provide feedback button at top right

### ISSUE THREAD

**Issue by tjbortz1s** [mattermost/focalboard#1196]
**Summary:**

Right now after clicking the feedback button at the top right of the program gets caught in a stuck state where the only way to progress is to give feedback.  If you're a curious user who doesn't want to actually give feedback that means you have to close and re-open the program to get back to the original screen.

**How important this is to me and why:**

Importance: Low

**Comment by chenilim** [comment]
Thanks @tjbortz1s! Are you using this via a web browser? If so, the back buttons should take you back to the board. Please LMK if that doesn't work.

On the Desktop v5, there's currently a bug (#1142), where the back navigation is broken.

**Comment by tjbortz1s** [comment]
No urgency here at all, just to be clear, I am fine not clicking the feedback button and this isn't an issue for me, opening this ticket here is more a "here's something!" than a "I'm having a problem".

I am on the Windows app - latest prerelease - there is no back button visible I am aware of.

Here is what I see after opening the feedback page:
![image](https://user-images.githubusercontent.com/6193065/133338685-08f6ad4c-1fe6-4b60-a4e2-e4739bae51a0.png)

**Comment by chenilim** [comment]
Ah, thanks! Looks like the root issue is the link should open in a browser from the app, like the help button. I'll submit a PR.

**Comment by ogi-m** [comment]
Verified on v0.9.0 RC12 - form now opens in a new tab
