### ISSUE TITLE
Bug: Import archive menu item missing from settings menu

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1197]
**Steps to reproduce the behavior:**
1. Open the settings menu from the Global Header
2. The import archive option is missing

**Expected behavior:**
The import archive option should be selectable

**Screenshots:**
<img width="283" alt="Settings menu bug" src="https://user-images.githubusercontent.com/46905241/133158157-7f8626f1-35f2-4c9e-97fa-d9701835fb94.png">

**Platform:**
 - v0.9.0 RC9 on Community
 - Chrome 91 on macOS

**Additional context:**
This might be related to #1182.

**Comment by chenilim** [comment]
Hi @asaadmahmood, your PR #1194 might have fixed this already, but this appears to be a related issue - where the menus aren't bounded by the window. In any case, we need to fix and verify this for v0.9. cc @ogi-m.

**Comment by asaadmahmood** [comment]
@chenilim Yup, this is fixed.

**Comment by ogi-m** [comment]
Tested and passed on v0.9.0 RC11
