### ISSUE TITLE
Bug: Theme styling not applied to modals opened from the header

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1201]
**Steps to reproduce the behavior:**
1. Set a dark theme in Mattermost
2. Go to Boards
3. Click on the avatar in the header
4. Open Custom Status or Account Settings modal

**Expected behavior:**
Modal styling should match the theme

**Screenshots:**
![modal_theme](https://user-images.githubusercontent.com/15314183/133265664-091bcbfc-7220-49f2-a45e-3261732c2dbb.jpg)
![modal_theme1](https://user-images.githubusercontent.com/15314183/133265667-b9e9ed18-0953-4452-8aeb-0b267dc95a2a.jpg)

**Platform:**
 - plugin v0.9.0 RC9

**Additional context:**
Related issue with the styling of the about modal - https://github.com/mattermost/focalboard/issues/1166

**Comment by chenilim** [comment]
@jespino, do you think we should take this for v0.9? The change looks small, but has the potential to break other things. cc @ogi-m, @asaadmahmood, @sbishel.

**Comment by chenilim** [comment]
My opinion is: If the only impact is some text in the custom status dialog is unreadable, then it's ok not to fix for v0.9. However, are there other higher-sev impacts?

**Comment by ogi-m** [comment]
I've installed the plugin from the fix PR on [this](https://focalboard.test.mattermost.cloud/ ) cloud test server (sysadmin/Sys@dmin123) to take a quick look.

It affects the three modals (Custom Statuses, Account Settings & About), but only Custom Statuses is at a point where it's unreadable @chenilim

**Comment by ogi-m** [comment]
@chenilim With all of the default themes I tested the global header modals and menus, as well as board views, cards, dropdown menus etc and all looks good.
