### ISSUE TITLE
Bug: Title and Document Count is off with long group message names

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#1205]
**Steps to reproduce the behavior:**
1. Create a long Group Channel with 4 or 5 members
2. Go to Workspace Selector
4. See how title and number of boards is jumbled.

**Expected behavior:**
The Title should not overflow and use an elipses.

**Screenshots:**
![Screen Shot 2021-09-14 at 10 33 51 AM](https://user-images.githubusercontent.com/12704875/133297951-462cde39-c1f9-420e-ba32-8a4dfd09b22b.png)

**Comment by chenilim** [comment]
Thanks @sbishel. @harshilsharma63, I think we should fix this for v0.9 - the title should push the content below down, or (worst case) cut off at a single line and not overlap. cc @asaadmahmood, @ogi-m.

**Comment by asaadmahmood** [comment]
Cut off on a single line and overflow elpissis should probably be fine for now.
