### ISSUE TITLE
Bug: Comment are sorted by oldest month first but most recent comment is at the top of the month

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1206]
**Steps to reproduce the behavior:**
1. Go to Focalboard
2. Open a card with a long history of comments
3. Observe the comment sorting

**Expected behavior:**
Cards are presented from oldest to newest (or newest to oldest?)

**Screenshots:**
![comment_ordering](https://user-images.githubusercontent.com/15314183/133306706-bb6ef54d-946d-4bd8-b518-664bcf299944.jpg)

**Platform:**
 - plugin v0.9.0 RC9 on community

**Additional context:**
Note the ordering in the screenshot screenshot, where the oldest month is put on top, but the most recent comment in the month is at the top of the month
- July 27
- August 24
- August 17
- September 14
- September 07

**Comment by ogi-m** [comment]
These cards are both on community, but the ordering is opposite - one is oldest to newest and the other is newest to oldest.

![oldest_to_newest](https://user-images.githubusercontent.com/15314183/133307762-a3308f22-84d1-4810-838e-6ace6c7619d5.jpg)
![newest_to_oldest](https://user-images.githubusercontent.com/15314183/133307757-8c9ad097-7a19-42d3-9c0e-1a7c30ca3204.jpg)

cc @chenilim

**Comment by chenilim** [comment]
Thanks @ogi-m. I took a quick look and it seems that the comments are not being sorted (see [getCardComments](https://github.com/mattermost/focalboard/blob/main/webapp/src/store/comments.ts#L53)). I think this is a regression, but am not sure. In any case, I believe we should fix this for v0.9 as out-of-order comments can be confusing. The order should be oldest-on-top.

Good news is the fix appears to be straight-forward, and I'll submit a PR for review. cc @sbishel, @jespino.

**Comment by ogi-m** [comment]
Tested and passed on v0.9.0 RC12 - comments are now sorted from oldest to newest
