### ISSUE TITLE
Provide portable Windows version

### ISSUE THREAD

**Issue by brownhamer** [mattermost/focalboard#121]
**Summary:**
I would like to use a portable version on Windows instead of an installed version managed via the Microsoft marketplace.

**How important this is to me and why:**
Importance: Medium

Use cases:
1. For usage on Windows systems on which installation and/or the MS marketplace are blocked.
2. For usage on USB stick to go.

**Comment by jespino** [comment]
Very good point, thanks for the feedback @brownhamer.

**Comment by citydelver** [comment]
I'm on Windows 8.1 and about to open an issue requesting for extending compatibility, but then I found this feature request, which is... BETTER. :-)

**Comment by wadbr** [comment]
Yes please, not everyone has access to the store (some windows 10 versions dont have the store at all)

**Comment by chenilim** [comment]
Fixed in #99 (dup).

**Comment by Kryptortio** [comment]
> Fixed in #99 (dup).

To fully make it portable I think it would be good to also add support for a relative data folder. There is a [separate issue related to this here](https://github.com/mattermost/focalboard/issues/2657).
