### ISSUE TITLE
Bug: Dashboard does not show names of DM channels

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1214]
**Steps to reproduce the behavior:**
1. Open the new Boards dashboard
2. Notice that the DM channel workspaces have no titles

**Expected behavior:**
Titles appear for DM channels on the dashboard and workspace picker dropdown.

**Screenshots:**
<img width="1079" alt="Screen Shot 2021-09-15 at 8 47 40 AM" src="https://user-images.githubusercontent.com/46905241/133466640-6842e43b-4c38-42f9-8f49-cb0972446ed7.png">

The names of the DM channel workspaces appear in the picker after being selected (but not before):
<img width="324" alt="Screen Shot 2021-09-15 at 8 52 45 AM" src="https://user-images.githubusercontent.com/46905241/133466986-c82c8168-b571-43f4-8baa-0c3a6e611f09.png">

**Platform:**
 - v0.9.0 built from `release-0.9.0` branch on Sep 15.
 - Chrome 91 on macOS

**Comment by chenilim** [comment]
@harshilsharma63, this was an issue we discussed at the team meeting. Just filing a bug to track it. Not sure if it should go to you or @hahmadia. cc @sbishel, @ogi-m. The new dashboard and workspace picker is really awesome! :)

**Comment by harshilsharma63** [comment]
@chenilim it's already done and cherrypicked in `release-0.9` via #1179

**Comment by harshilsharma63** [comment]
@chenilim my bad, it wasn't cherry picked. Have done it now.
