### ISSUE TITLE
Bug: its not always possible to hide the side bar

### ISSUE THREAD

**Issue by kamre** [mattermost/focalboard#1215]
**Steps to reproduce the behavior:**
1. Create new board (for example "Meeting Notes" from template)
2. There is a horizontal scroll bar because not all kanban columns are visible
4. Its not possible to hide the side bar

**Expected behavior:**
It should be always possible to hide the side bar.

**Screenshots:**
Look for example at these kanban boards from default templates, they all have horizontal scroll:
![BoardsScroll](https://user-images.githubusercontent.com/5587620/132796112-71ba9899-2351-4699-a541-484262f01a15.gif)

Here is the threshold for width when the button to hide the side bar appears:
![HideSideBarThreshold](https://user-images.githubusercontent.com/5587620/133469314-2736c46c-83b9-4291-863c-dbb973c46487.gif)

**Platform:**
 - Browser and version: Chrome 92
 - OS and version: Windows 10
 - Laptop with **150% scale** in Windows settings.

**Additional context:**
This is a regression introduced in #1052
Reproducible in `v0.9.0`

@chenilim @asaadmahmood FYI

**Comment by chenilim** [comment]
Thanks @kamre! In general, the collapse sidebar feature is mainly for mobile web support, but I see your notes in [PR-1052](https://github.com/mattermost/focalboard/pull/1052/files#r705821384), and agree this is an unintentional regression for Personal Server at this point.

I took a quick look and the fix looks like a simple css selector change. I'll submit a PR.

Mid-term (Oct / Nov), we are going to refactor the sidebar for the plugin. Longer term, we might also want to rethink the sidebar layout for Personal Server. cc @asaadmahmood.
