### ISSUE TITLE
Bug: Clicking off card can lose content in FireFox

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#1217]
**Steps to reproduce the behavior:**
1. Create or edit a card; add text to the description
2. Click away from the card, meaning click somewhere else on the board
3. See card closes
4. Re-open card
5. See text added in step 1 is lost

**Expected behavior:**
Card content is saved when clicking away from a card

**Additional context:**
If user clicks another field before clicking away from the card, then content is saved correctly.

**Comment by chenilim** [comment]
Thanks @wiggin77! Could you add the OS / browser / edition this repros on? I couldn't get a repro on the Community server. I tried:
1. Create a new card
2. Type '123' in the description
3. Click on the gray background
4. Card closes, but content was saved

Was it another specific sequence of steps?

**Comment by wiggin77** [comment]
FireFox / Linux.  Yesterday's main branch, running locally.  I'll check again with today's build.

**Comment by wiggin77** [comment]
Latest main, Firefox, Linux.  Running as a plugin with latest channels server:

![fb_bug](https://user-images.githubusercontent.com/5024605/133491316-c6090f1c-4e5d-4dc8-9db4-cce95c07eee6.gif)

**Comment by chenilim** [comment]
Thanks @wiggin77! I took a quick look and it appears to be a strange timing issue with onClose in `Dialog.tsx` and onBlur in `MarkdownEditor`. If I add a `setTimeout(0)` to the dialog code, that seems to fix it. I'll submit a PR, but there may be other unexpected timing issues like this elsewhere.

**Comment by chenilim** [comment]
Tested this against v0.82, and this is a regression (did not repro on the older build). So I propose we take this for v0.9, as the fix is relatively simple - at worst, it changes the order of calls when closing the card. LMK if anyone sees any potential issues. cc @sbishel, @ogi-m.

**Comment by ogi-m** [comment]
Verified on v0.9.0 RC12 - text is now saved as expected
