### ISSUE TITLE
Bug: Workspace switcher and dashboard don't show any channels

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1227]
**Steps to reproduce the behavior:**
1. Open Boards from Mattermost
2. Open the workspace switcher

**Expected behavior:**
Workspace switcher should list all the channels and not show the error on the dashboard

**Screenshots:**
![Image Pasted at 2021-9-16 16-34](https://user-images.githubusercontent.com/15314183/133644721-93e19da2-8f8b-408b-bea6-045d67224530.png)

**Platform:**
 - main branch on mattermost 6.0

**Comment by chenilim** [comment]
Confirmed this repros on v0.9.0 RC12 (on community). However, it does not repro on my v6.0 test server. One guess might be that community has multiple teams?

**Comment by ogi-m** [comment]
@chenilim I just tried RC12 on two cloud test servers, one HA and the other non-HA, with a single team and then with multiple teams but I couldn't repro in any scenario.

**Comment by chenilim** [comment]
What platform was your original repro on Ogi? Can we set up a repro for @harshilsharma63 so he can take a look at it asap when he's back online? Thanks.

**Comment by chenilim** [comment]
Ok, I've confirmed that this repros on a MySql-backed server. I set one up with `/cloud create SERVERNAME --database mysql-operator --version master`, then [manually installed](https://www.focalboard.com/download/mattermost/latest-plugin/) v0.9.0 RC12.

**Comment by chenilim** [comment]
@harshilsharma63 / @ogi-m, should this be closed now that #1252 is merged?

**Comment by harshilsharma63** [comment]
@chenilim nope. Still testing on mysql test instance and its failing there.

**Comment by ogi-m** [comment]
Tested and passed on latest v0.9 branch
