### ISSUE TITLE
Trying to drag and drop cards not working in desktop version on Linux Kubuntu

### ISSUE THREAD

**Issue by backit** [mattermost/focalboard#123]
**Summary:**
Trying to drag and drop cards not working in desktop version on linux kubuntu 

**Steps to reproduce the behavior:**
1. got to "By status" view in your project template
2. try drag n drop a card from one status to another

**Expected behavior:**
Card change status.

**Got behavior**
Card return to its place and status does not change.

**Screenshots:**

**Platform:**
- focalboard desktop v 0.6.0
- kubuntu 18.04.5

**Comment by jespino** [comment]
Thanks for reporting it, I'll investigate it.

**Comment by jespino** [comment]
Looks like the https://github.com/webview/webview library is not passing properly all the drag and drop events to the underneath application. I need to investigate it a bit more.

**Comment by hamid-m** [comment]
Same issue on:
  - focalboard desktop v0.6.1
  - Ubuntu 20.04

Cannot drag and drop tasks to change status (e.g. TODO to DONE) or to change order of tasks.

**Comment by fabiancrx** [comment]
Don't know if it's helpful but I can reproduce the same issue with Pop OS(ubuntu based) 20.10

**Comment by Tashima42** [comment]
Same thing on Zorin OS, wich is also Ubuntu based.

**Comment by polszews** [comment]
same on Linux MInt

**Comment by jespino** [comment]
After a refactor done in the DnD using `react-dnd` looks like it is working :)
