### ISSUE TITLE
Bug: Boards don't update when using Desktop App v5

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1236]
**Steps to reproduce the behavior:**
1. Download Desktop App v5 (e.g. [Sep 16 build](https://community-daily.mattermost.com/core/pl/6nn7pgfhq3fq8f1npg78w9r9ph))
2. Connect to a Mattermost v6.0 server, e.g. community.mattermost.com
3. Open a board
4. Make an edit, e.g. rename a card
5. The edit is not persisted, e.g. when re-opening the card

6. Drag a card from one column to another
7. The card doesn't move

**Expected behavior:**
Edits are persisted.

**Edition and Platform:**
 - Edition: Mattermost plugin
 - Version: v0.9.0
 - Browser and OS: Desktop app v5 on macOS 11.4

**Additional context:**
If you open a web browser to the same board on the server, you'll see the edits are actually recorded, but not reflected in the Desktop app.

Cmd+R in the desktop app also causes the edits to appear.

Speculation: The websocket updates are not going through on the Desktop App.

Also note: This does not seem to repro on Desktop App v4.7 or in the web app.

**Comment by chenilim** [comment]
FYI @sbishel and @ogi-m. I'm not sure who should investigate this first, so please reassign @sbishel.

**Comment by sbishel** [comment]
@chenilim I can't duplicate. In fact, I can edit board in web app and Desktop V5.0 gets the changes as well. I'm opening Boards via channel header...not via the Global Header which seems to have its own issues.

**Comment by chenilim** [comment]
Hmmm... I'm continuing to investigate. This is reproing for me with Desktop app v5.0.0-develop.13204 on macOS. It's reproing on older Mattermost server + Boards builds as well, so I wonder if it's an issue in the Desktop app v5 or my setup.

**Comment by chenilim** [comment]
Ok, this is truly wild: I rebooted my Mac and the problem no longer repros. Haven't seen this before, but my best wild guess is some resource was exhausted. Closing this, but also cc @devinbinnie in case anyone sees something similar.
