### ISSUE TITLE
Bug: Sidebar item hover highlight extends outside of the border

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1238]
**Steps to reproduce the behavior:**
1. Go Boards
2. Hover on an item in the sidebar
3. Observe the highlight

**Expected behavior:**
The highlight should be within the borders of the sidebar

**Screenshots:**
![highlight](https://user-images.githubusercontent.com/15314183/133693611-7a56eef4-d8a1-4ce6-b5be-956987e5be60.jpg)

**Edition and Platform:**

- Edition: Mattermost plugin
- Version: v0.9.0 RC12
- Browser and OS: Chrome 93 on Windows

**Comment by chenilim** [comment]
Thanks @ogi-m. Interestingly, this seems to only repro with the Quartz, Indigo, and Onyx themes (repros for me on Chrome 91 on macOS 11.4). @asaadmahmood, could you take a look? I propose this is low-sev and we can take it for post v0.9, but if it's a safe fix, we can consider for v0.9.1. cc @sbishel.
