### ISSUE TITLE
Bug: "No workspace" error first time switching to Boards via App Switcher

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1243]
**Steps to reproduce the behavior:**
1. Open a private browser window, or clear the server localstorage
2. Open Channels on the server
3. Click on the App Switcher and select Boards
4. See "no workspace" error

**Expected behavior:**
Boards should load

**Edition and Platform:**
 - Edition: Mattermost plugin
 - Version: v0.9.1 RC1
 - Browser and OS: Chrome 91 on macOS

**Additional context:**
If you first open Boards via the Channel Header, that loads, and subsequent opens via the App Switcher also load.

**Comment by chenilim** [comment]
I believe this might be related to the FTUE / dashboard changes. Please reassign as appropriate @sbishel. cc @ogi-m.

**Comment by harshilsharma63** [comment]
Will be fixed by #1259

**Comment by chenilim** [comment]
@harshilsharma63, please confirm that the fix is in the `release-0.9.0` branch, then close this issue. Thanks.
