### ISSUE TITLE
Bug: After installing Focalboard 0.9.1(mattermost plugin) I get a: something went wrong page.

### ISSUE THREAD

**Issue by luistiktok** [mattermost/focalboard#1246]
Log:
{"level":"info","ts":1631998581.799376,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"error [2021-09-18 20:56:21.798 Z] server not bind to any port caller=\"mlog/mlog.go:228\"","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998588.132103,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 20:56:28.131 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998588.2590666,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 20:56:28.258 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998588.261827,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 20:56:28.261 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998588.2641413,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 20:56:28.263 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998588.265005,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"error [2021-09-18 20:56:28.264 Z] API ERROR caller=\"mlog/mlog.go:228\" code=401 error=\"<nil>\" msg=\"user does not have workspace access\" api=/api/v1/workspaces/0","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998588.2658784,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 20:56:28.265 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998588.2689726,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"error [2021-09-18 20:56:28.268 Z] API ERROR caller=\"mlog/mlog.go:228\" code=403 error=\"access denied to workspace\" msg=\"Access denied to workspace\" api=/api/v1/workspaces/0/users","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998588.270247,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"error [2021-09-18 20:56:28.269 Z] ERROR GetUserWorkspaces caller=\"mlog/mlog.go:228\" error=\"Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%\"isTemplate\":false% JOIN Channels ON ChannelMembers.ChannelId = Channels.Id WHE' at line 1\"","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998588.2704263,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"error [2021-09-18 20:56:28.269 Z] API ERROR caller=\"mlog/mlog.go:228\" code=500 error=\"Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%\"isTemplate\":false% JOIN Channels ON ChannelMembers.ChannelId = Channels.Id WHE' at line 1\" msg= api=/api/v1/workspaces","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998588.2779636,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 20:56:28.277 Z] GetBlocks caller=\"mlog/mlog.go:213\" parentID= blockType= block_count=36","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998593.7435365,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 20:56:33.743 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998593.9199588,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 20:56:33.919 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998593.9217494,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 20:56:33.921 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998593.9221225,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 20:56:33.921 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998593.9228742,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 20:56:33.922 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998593.9245431,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"error [2021-09-18 20:56:33.923 Z] ERROR GetUserWorkspaces caller=\"mlog/mlog.go:228\" error=\"Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%\"isTemplate\":false% JOIN Channels ON ChannelMembers.ChannelId = Channels.Id WHE' at line 1\"","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998593.9246922,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"error [2021-09-18 20:56:33.923 Z] API ERROR caller=\"mlog/mlog.go:228\" code=500 error=\"Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%\"isTemplate\":false% JOIN Channels ON ChannelMembers.ChannelId = Channels.Id WHE' at line 1\" msg= api=/api/v1/workspaces","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998593.9269538,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"error [2021-09-18 20:56:33.926 Z] API ERROR caller=\"mlog/mlog.go:228\" code=403 error=\"access denied to workspace\" msg=\"Access denied to workspace\" api=/api/v1/workspaces/0/users","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998593.9278617,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"error [2021-09-18 20:56:33.927 Z] API ERROR caller=\"mlog/mlog.go:228\" code=401 error=\"<nil>\" msg=\"user does not have workspace access\" api=/api/v1/workspaces/0","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998593.9341693,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 20:56:33.933 Z] GetBlocks caller=\"mlog/mlog.go:213\" parentID= blockType= block_count=36","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998611.5480528,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 20:56:51.547 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998611.660143,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 20:56:51.659 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998611.6614337,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 20:56:51.660 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998611.661555,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 20:56:51.661 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998611.6616657,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 20:56:51.661 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998611.6642895,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"error [2021-09-18 20:56:51.664 Z] ERROR GetUserWorkspaces caller=\"mlog/mlog.go:228\" error=\"Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%\"isTemplate\":false% JOIN Channels ON ChannelMembers.ChannelId = Channels.Id WHE' at line 1\"","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998611.6644418,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"error [2021-09-18 20:56:51.664 Z] API ERROR caller=\"mlog/mlog.go:228\" code=500 error=\"Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%\"isTemplate\":false% JOIN Channels ON ChannelMembers.ChannelId = Channels.Id WHE' at line 1\" msg= api=/api/v1/workspaces","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998611.6662774,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"error [2021-09-18 20:56:51.666 Z] API ERROR caller=\"mlog/mlog.go:228\" code=401 error=\"<nil>\" msg=\"user does not have workspace access\" api=/api/v1/workspaces/0","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998611.6677973,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"error [2021-09-18 20:56:51.667 Z] API ERROR caller=\"mlog/mlog.go:228\" code=403 error=\"access denied to workspace\" msg=\"Access denied to workspace\" api=/api/v1/workspaces/0/users","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631998611.6739314,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 20:56:51.673 Z] GetBlocks caller=\"mlog/mlog.go:213\" parentID= blockType= block_count=36","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631999181.7995791,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"error [2021-09-18 21:06:21.799 Z] Unable to clean up the sessions caller=\"mlog/mlog.go:228\" error=\"no update allowed from focalboard, update it using mattermost\"","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631999195.7365606,"caller":"expirynotify/worker.go:85","msg":"Worker: Job is complete","worker":"ExpiryNotify","job_id":"ck7grgkjwib3tje6nb155gwf4e"}
{"level":"info","ts":1631999208.4367614,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 21:06:48.436 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631999208.5377543,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 21:06:48.536 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631999208.5383503,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 21:06:48.537 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631999208.539892,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 21:06:48.537 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631999208.5411673,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 21:06:48.540 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631999208.545819,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"error [2021-09-18 21:06:48.544 Z] API ERROR caller=\"mlog/mlog.go:228\" code=403 error=\"access denied to workspace\" msg=\"Access denied to workspace\" api=/api/v1/workspaces/0/users","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631999208.5462382,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"error [2021-09-18 21:06:48.544 Z] ERROR GetUserWorkspaces caller=\"mlog/mlog.go:228\" error=\"Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%\"isTemplate\":false% JOIN Channels ON ChannelMembers.ChannelId = Channels.Id WHE' at line 1\"","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631999208.546439,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"error [2021-09-18 21:06:48.544 Z] API ERROR caller=\"mlog/mlog.go:228\" code=500 error=\"Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%\"isTemplate\":false% JOIN Channels ON ChannelMembers.ChannelId = Channels.Id WHE' at line 1\" msg= api=/api/v1/workspaces","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631999208.549011,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"error [2021-09-18 21:06:48.548 Z] API ERROR caller=\"mlog/mlog.go:228\" code=401 error=\"<nil>\" msg=\"user does not have workspace access\" api=/api/v1/workspaces/0","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631999208.5594492,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 21:06:48.557 Z] GetBlocks caller=\"mlog/mlog.go:213\" parentID= blockType= block_count=36","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631999305.9022386,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 21:08:25.901 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631999306.001545,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 21:08:26.001 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631999306.0029867,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 21:08:26.002 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631999306.006847,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 21:08:26.005 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631999306.0073183,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 21:08:26.005 Z] attachSession caller=\"mlog/mlog.go:213\" single_user=false","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631999306.0105817,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"error [2021-09-18 21:08:26.010 Z] API ERROR caller=\"mlog/mlog.go:228\" code=401 error=\"<nil>\" msg=\"user does not have workspace access\" api=/api/v1/workspaces/0","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631999306.0129168,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"error [2021-09-18 21:08:26.011 Z] ERROR GetUserWorkspaces caller=\"mlog/mlog.go:228\" error=\"Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%\"isTemplate\":false% JOIN Channels ON ChannelMembers.ChannelId = Channels.Id WHE' at line 1\"","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631999306.0131793,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"error [2021-09-18 21:08:26.011 Z] API ERROR caller=\"mlog/mlog.go:228\" code=500 error=\"Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%\"isTemplate\":false% JOIN Channels ON ChannelMembers.ChannelId = Channels.Id WHE' at line 1\" msg= api=/api/v1/workspaces","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631999306.0142956,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"error [2021-09-18 21:08:26.013 Z] API ERROR caller=\"mlog/mlog.go:228\" code=403 error=\"access denied to workspace\" msg=\"Access denied to workspace\" api=/api/v1/workspaces/0/users","plugin_id":"focalboard","source":"plugin_stdout"}
{"level":"info","ts":1631999306.026831,"caller":"go-plugin@v1.4.2/stream.go:15","msg":"debug [2021-09-18 21:08:26.025 Z] GetBlocks caller=\"mlog/mlog.go:213\" parentID= blockType= block_count=36","plugin_id":"focalboard","source":"plugin_stdout"}

**Comment by chenilim** [comment]
Thanks @luistiktok! This looks like a dup of #1242 - SQL errors on MySQL related to the new workspace switcher. A possible workaround is to use the channel header button to open Focalboard, but in general the workspace switcher is broken on MySQL until this is fixed.
