### ISSUE TITLE
Why is capitalization in issue labels inconsistent? 

### ISSUE THREAD

**Issue by it33** [mattermost/focalboard#125]
Just wondering, is the capitalization in labels inconsistent because they are hooked up to some backend processes that keep up from fixing the issue, or is it just that we haven't gotten around to picking a capitalization standard? 

![image](https://user-images.githubusercontent.com/177788/111780524-c2c1d980-8874-11eb-95ab-607e5e56e91e.png)

**Comment by jasonblais** [comment]
The Mattermost labels (`Do Not Merge`) etc use title case. Looks like the default labels provided by GitHub (`bug`, `documentation`, ...) now use non-capital letters.

**Comment by it33** [comment]
Thanks @jasonblais 

Does anyone know if we remove the capitalization from the labels Mattermost added, would we break any automation? 

Also, I'm wondering if we should just remove the Mattermost labels and use the standard GitHub ones to make this repo more friendly to contributors.

**Comment by jespino** [comment]
Good question maybe @metanerd knows it.

**Comment by metanerd** [comment]
The lower case labels are the default GitHub labels. Renaming them might break automations that query GitHub. Feel free to make them consistent in this repository though. This needs a rework across all our projects.

**Comment by justinegeffen** [comment]
I've edited the labels for consistency. As far as I understand, changing the case shouldn't cause any issues. @metanerd, it seems like you can edit labels across an organization but not sure whether it means you can do a bulk update of labels or if each project needs to be done individually. [LMK if this helps](https://docs.github.com/en/organizations/managing-organization-settings/managing-default-labels-for-repositories-in-your-organization).

**Comment by justinegeffen** [comment]
Ah thanks so much @chenilim and apologies for any issues caused! Definitely good to know and also well-worth documenting in the Handbook (which I will do). :)
