### ISSUE TITLE
Bug: Label and text not aligned for column list

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#1261]
**Expected behavior:**
The text and label count should be vertically aligned.

**Screenshots:**
![Screenshot 2021-09-20 at 8 38 42 PM](https://user-images.githubusercontent.com/11034289/134031274-7d6b0d46-917d-4a14-8e7c-5db22608b629.png)

**Comment by chenilim** [comment]
Thanks @asaadmahmood, putting this up for grabs.

**Comment by DIVYA-19** [comment]
Hi @chenilim, I have created a PR on this issue https://github.com/mattermost/focalboard/pull/1309. can you please look into it

Thanks

**Comment by akshitarora921** [comment]
Hi, Is it still open?

**Comment by gdguesser** [comment]
Can this one be closed? Since the PR [#1309](https://github.com/mattermost/focalboard/pull/1309) has been already merged.

**Comment by sbishel** [comment]
fixed
