### ISSUE TITLE
Bug: Session Expiry after first time clicking boards icon in the header of a channel

### ISSUE THREAD

**Issue by hahmadia** [mattermost/focalboard#1262]
**Steps to reproduce the behavior:**
Logged in for the first time in Mattermost using Desktop App V5, after click the Focalboard header Icon, I got a Session expiry. 

When I relogged back into Mattermost and clicked the boards icon in the header of channel, it worked. 

**Expected behavior:**
Shouldn't have session expiry and should go to the boards on the first time logging in as a new user after clicking the boards header icon.

Mac OS
Desktop App V5

![image](https://user-images.githubusercontent.com/17804942/134031627-0a3d69a4-37d9-4b2f-8819-cd4024bd8293.png)

![image](https://user-images.githubusercontent.com/17804942/134031671-eab0b1ab-7bde-40db-9ff1-45f4c037d7d3.png)

**Comment by hahmadia** [comment]
Afterwards, when I click sign in on the Channels tab, it redirects me to the boards tab and shows a infinite `Signing In...` on Channels tab unless I do CTRL + R and then sign in.

![image](https://user-images.githubusercontent.com/17804942/134031939-5d9a3616-895e-436b-9ed6-be500bf0551a.png)

**Comment by chenilim** [comment]
Related to #1264, and might be addressed in #1258. In any case, we should confirm this works on new "out of the box" Desktop app instances. cc @ogi-m, @sbishel.

**Comment by harshilsharma63** [comment]
Will wait for other related PRs to merge in before spending time on this.

**Comment by harshilsharma63** [comment]
@hahmadia can you try this again on local with the latest `main` or `release-0.9.0` branch?

**Comment by hahmadia** [comment]
@harshilsharma63 Thank you Mr.Wondeful for fixing it <3 Works for me now (But I'll let QA close this)

**Comment by chenilim** [comment]
@ogi-m, any update on this? If we believe this is fixed in release-0.9.0, in general we should close the bug to validate.

**Comment by harshilsharma63** [comment]
Closing this as it's fixed by other PRs combined.
