### ISSUE TITLE
Bug: Can't use the scrollbar in the sidebar, and the scrollbar is cut as well.

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#1263]
**Steps to reproduce the behavior:**
1. Add multiple boards in the sidebar
2. Squish your window height.
3. Try to scroll by clicking the scrollbar
4. Notice that you can't scroll by using the scrollbar.

**Expected behavior:**
- The scrollbar should not be cut
- Users should be able to use it by clicking on it
- It should be inside the sidebar.

**Screenshots:**
![Screenshot 2021-09-20 at 8 44 54 PM](https://user-images.githubusercontent.com/11034289/134032318-76269f6c-63a5-46b0-9792-8e155cfba57c.png)

**Edition and Platform:**
 - Edition: Mattermost plugin
 - Version: 0.9.1
 - Browser and OS: Chrome 93 MacOS

**Additional context:**

**Comment by chenilim** [comment]
Good catch @asaadmahmood! This is a regression from v0.8.2, and we should investigate it for v0.9 - it could be high severity for users using a mouse without a scroll wheel - it would be impossible to scroll the sidebar. Could you help investigate?
