### ISSUE TITLE
Bug: Updating anything doesn't reflect immediately?

### ISSUE THREAD

**Issue by hahmadia** [mattermost/focalboard#1268]
**Steps to reproduce the behavior:**
Change the name of my board, the change doesn't reflect until I do a CTRL + R?

**Expected behavior:**
It should change and show the change right away?

**Screenshots:**
![image](https://user-images.githubusercontent.com/17804942/134033293-944135b2-d7d0-4e6c-81e3-6bb667e09e35.png)

Switching between another board and coming back

![image](https://user-images.githubusercontent.com/17804942/134033385-69b75a12-f9e0-4b8c-8073-bf413f6bc853.png)

Doing a CTRL + R

![image](https://user-images.githubusercontent.com/17804942/134033439-df6af20d-7734-49fc-bbc2-e3a5fb4b298a.png)

MAC OS
Desktop App V5

**Comment by chenilim** [comment]
Closing this as a dup of #1270 that Scott filed.
