### ISSUE TITLE
Bug: Can't scroll in card view on mobile (IOS)

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#1271]
**Steps to reproduce the behavior:**
1. Open card view
2. Use a small screen, or have a card with multiple properties
3. Try to scroll

**Expected behavior:**

**Screenshots:**
![IMG_67E5CE8B4243-1](https://user-images.githubusercontent.com/11034289/134034324-06fc8c18-1f5e-49e0-ae72-b54792578129.jpeg)

**Edition and Platform:**
 - Edition: Mattermost plugin
 - Version: 0.9.0
 - Browser and OS: Safari 93 iOS 14.7.1

**Comment by chenilim** [comment]
Followup from our team meeting: Let's investigate and try to fix at least the scroll / read-only use cases for v0.9. cc @sbishel, @ogi-m.

**Comment by asaadmahmood** [comment]
Should be fixed with this PR, based on Ogi's comments.
https://github.com/mattermost/focalboard/pull/1310
