### ISSUE TITLE
Bug: Hide X on Select similar to Multi Select unless clicked into to Edit

### ISSUE THREAD

**Issue by hahmadia** [mattermost/focalboard#1277]
**Steps to reproduce the behavior:**
Hide the X of Select similar to MultiSelect unless you click into the field to edit it

**Expected behavior:**
No X should be shown

**Screenshots:**
![image](https://user-images.githubusercontent.com/17804942/134037088-bdcfa42c-0e64-4980-b2cd-d6104f8aac13.png)

**Comment by chenilim** [comment]
Looks like a dup of #1013, which is fixed in main.
