### ISSUE TITLE
Feature Idea: Confirm delete when deleting board

### ISSUE THREAD

**Issue by justinegeffen** [mattermost/focalboard#1278]
**Summary:**
Confirm that the user wants to delete the board prior to deletion.

**How important this is to me and why:**

Importance: High

Use cases:
"Delete" and "Duplicate" are close together and it's very easy to select "Delete" inadvertently. The board is deleted immediately and is not recoverable. If a user has a very detailed, long-standing board it means all the work is lost. 

**Additional context / similar features:**
1. Further down the line deleting items could also be permissions-based (e.g., only the board's team/owner can delete boards/items).
2. Here's an example of how Confluence does it:
<img width="674" alt="Screen Shot 2021-09-20 at 18 20 12" src="https://user-images.githubusercontent.com/4223530/134037735-e3cfd074-6ae4-4d46-87d2-57a9e482d9ce.png">

**Comment by asaadmahmood** [comment]
Here's how we should do it:
https://www.figma.com/file/a3SJgKolniXEU2G4zG8Uc0/Issue-512-Deleting-a-property?node-id=214%3A3130

**Comment by justinegeffen** [comment]
> Here's how we should do it:
> https://www.figma.com/file/a3SJgKolniXEU2G4zG8Uc0/Issue-512-Deleting-a-property?node-id=214%3A3130

Yep! That's perfect.

**Comment by chenilim** [comment]
Thanks @justinegeffen and @asaadmahmood!

Putting this up for grabs. It's also related to #512 and #1140. We should use the same dialog code.

**Comment by gtanczyk** [comment]
I'll take this one

**Comment by sbishel** [comment]
closing as fixed
