### ISSUE TITLE
Bug: Shared Boards do not work.

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#1279]
**Steps to reproduce the behavior:**
1. Go to a board
2. Click on ...
3. Select Share Board
4. Copy Link
5. a. Paste into New tab
Receive "Team Not Found" error

6. b. Paste into Incognito Window
Sent to Login Form

**Expected behavior:**
Share board should work in read-only mode

**Edition and Platform:**
 - Edition: Mattermost plugin
 - Version: [v0.9.0]
 - Browser and OS: [e.g. Chrome 91 on macOS]

**Additional context:**
Appears to be an issue with the URL not getting created correctly.

https://boards-bugbash.test.mattermost.cloud/shared/6578c946-8515-4144-87b3-66e5cd0a1d75/7fba6bef-511f-4fc6-8ed7-3718bd3f6cbe?r=6e7b1c91-8b15-42b8-85dd-509232d750e9

**Comment by chenilim** [comment]
@sbishel, I am not able to repro with the steps above. The link that is copied is correct in my case: https://boards-bugbash.test.mattermost.cloud/plugins/focalboard/workspace/dqgeahsj8id8mf9cbz6wrcygea/shared/6578c946-8515-4144-87b3-66e5cd0a1d75/7fba6bef-511f-4fc6-8ed7-3718bd3f6cbe?r=6e7b1c91-8b15-42b8-85dd-509232d750e9

I tried this on both Chrome and Safari on macOS. @ogi-m, are you able to get a repro?

**Comment by sbishel** [comment]
I can't repo locally either...but on the bugbash machine I can repo with either Safari or Chrome...Not sure what's up with that.

**Comment by chenilim** [comment]
Ok, let's investigate this then. Not sure what might cause the share link URL to be incorrect (it's missing the workspace sub-path in your repro steps).

**Comment by sbishel** [comment]
I'm pretty sure this is related to the Web Socket issue we have been seeing. If I test this, then try changing a title on a card. They either both work correctly, or both work incorrectly. 

I will keep open to retest after Web socket issue has been fixed.

**Comment by sbishel** [comment]
Retested on the bugbash server which has the web socket fixes. It works fine now with those updates. Closing.
