### ISSUE TITLE
Bug: adding board using template created by someone else, nothing happens

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#1281]
**Steps to reproduce the behavior:**
1. Create new channel; press Boards button
2. Select "Add Board"
3. See template(s) created by someone else listed
4. Select one
5. List is dismissed but nothing happens

**Expected behavior:**
New board created with selected template

**Screenshots:*
![add_board_issue](https://user-images.githubusercontent.com/5024605/134038110-c066ab1d-fcfd-4bda-a967-895140634a98.gif)

**Edition and Platform:**
 - Edition: Mattermost plugin
 - Version:  v0.9.0 bugbash
 - Browser and OS: Chrome 93 on Linux

**Comment by chenilim** [comment]
This might be related or a dup of #1280.

**Comment by chenilim** [comment]
Also related to #1237. @mgdelacroix, assigning this to you to track. Please verify and close it with the fix for #1280. @ogi-m, let's verify again when that fix and the fix for #1237 are merged and cherry picked. Thanks.

**Comment by harshilsharma63** [comment]
I believe it was related to this PR - https://github.com/mattermost/focalboard/pull/1319. It's working fine on main now.

**Comment by mgdelacroix** [comment]
Fixed on https://github.com/mattermost/focalboard/pull/1319
