### ISSUE TITLE
Feature Idea: Auto-populate a property field with the selected property name

### ISSUE THREAD

**Issue by justinegeffen** [mattermost/focalboard#1283]
**Summary:**
When I select a new property, the name of the field remains "New Property". The only way I can see which property I've selected is by clicking on that new property and confirming. 

The name field should automatically reflect the chosen property so that the user doesn't have to rename it - it should remain editable though, so it can be modified.

**How important this is to me and why:**

Importance: High

Use cases:
The user won't have to try figure out which property is which in the Property sort filter if they didn't know to rename the property type when adding it.

<img width="637" alt="Screen Shot 2021-09-20 at 18 25 51" src="https://user-images.githubusercontent.com/4223530/134038952-6c42282e-ee5f-479b-a8e1-8893dad2c4b7.png">

<img width="246" alt="Screen Shot 2021-09-20 at 18 25 57" src="https://user-images.githubusercontent.com/4223530/134038656-67c147d5-38da-4823-9b91-32e32657233c.png">

**Comment by chenilim** [comment]
Thanks Justine! Looks like this is already covered by #705, and a prototype is in the works. Please add any additional input there though.

**Comment by justinegeffen** [comment]
Oh awesome, thank you! I didn't see that. :)
