### ISSUE TITLE
Feature Idea: Fix alignment between fields in cards

### ISSUE THREAD

**Issue by justinegeffen** [mattermost/focalboard#1284]
**Summary:**
Field alignment is off-kilter in cards.

**How important this is to me and why:**

Importance: High

Use cases:
Having aligned fields improves the overall look and feel of the product. 

<img width="583" alt="Screen Shot 2021-09-20 at 18 11 43" src="https://user-images.githubusercontent.com/4223530/134039420-5846fef1-0afe-46fa-a07c-2eb57fbfe7b4.png">

**Comment by chenilim** [comment]
Thanks @justinegeffen! This is related to #1035. Assigning to you @asaadmahmood to track - more generally, we should take a UX cleanup pass on the Card Editor and other main UI. We can also break these out into up for grab items if you prefer.
