### ISSUE TITLE
Bug: A filter "not include" makes the new card to select one value for that field

### ISSUE THREAD

**Issue by jespino** [mattermost/focalboard#1285]
**Steps to reproduce the behavior:**
1. Go to a table view
2. Filter by a filed with "not include"
3. Add a new card.

**Expected behavior:**
The new card doesn't have anything in that field. But it is adding one value to that field (that is not the filtered one)

**Edition and Platform:**
 - Edition: Personal Desktop
 - Version: v0.9.0
 - Browser and OS: Desktop app

**Comment by kamre** [comment]
Here is [how select property is processed](https://github.com/mattermost/focalboard/blob/main/webapp/src/cardFilter.ts#L124-L132) when new card is created:
```ts
if (template.type === 'select') {
    const option = template.options.find((o) => !filterClause.values.includes(o.id))
    if (option) {
        return {id: filterClause.propertyId, value: option.id}
    }

    // No other options exist
    return {id: filterClause.propertyId}
}
```
Is this really needed?

**Comment by chenilim** [comment]
Thanks @kamre! I was just looking at the same thing. Submitted a PR to remove the unnecessary code.
