### ISSUE TITLE
Bug: setting custom emoji for a custom status doesn't work

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#1286]
**Steps to reproduce the behavior:**
1. Go to a workspace; in this case empty (no boards)
2. Click on user profile icon top right
3. Select "Set a custom status"
4. Select emoji picker
5. screen goes blank

**Expected behavior:**
Select emoji for custom status

**Screenshots:**
![custom_status_bug](https://user-images.githubusercontent.com/5024605/134039628-27c70792-7efa-45c4-badc-d010c588ebcd.gif)

**Edition and Platform:**
 - Edition:Mattermost plugin
 - Version:  v0.9.0 bus bash
 - Browser and OS: Chrome 93 on Linux

**Comment by chenilim** [comment]
@sbishel, we should investigate and fix this one - I don't think it strictly needs to go into v6.0, but we can consider it if it's an easy / safe fix. cc @ogi-m, @asaadmahmood.

**Comment by sbishel** [comment]
I wonder if this is also a web-socket issue. When I tried it. It worked, although there is definitely a CSS issue. 
![Screen Shot 2021-09-20 at 11 52 02 AM](https://user-images.githubusercontent.com/12704875/134050429-ff663cb2-eff4-45fa-adf1-dce7b5ecc4ca.png)

**Comment by sbishel** [comment]
@asaadmahmood - Could you take a look at the CSS? If you encounter the original issue, assign back to me.

**Comment by wiggin77** [comment]
> I wonder if this is also a web-socket issue.

I'm not seeing any WS errors in the log.  I do see this exception:
```
react-dom.production.min.js:209 TypeError: Cannot read properties of undefined (reading 'name')
    at Function.mapToProps (index.js:23)
    at r (wrapMapToProps.js:41)
    at Function.r.mapToProps (wrapMapToProps.js:50)
    at r (wrapMapToProps.js:41)
    at selectorFactory.js:22
    at connectAdvanced.js:319
    at Object.useMemo (react-dom.production.min.js:165)
    at t.useMemo (react.production.min.js:25)
    at F (connectAdvanced.js:304)
    at Xo (react-dom.production.min.js:153)
as @ react-dom.production.min.js:209
a.callback @ react-dom.production.min.js:226
fo @ react-dom.production.min.js:131
ss @ react-dom.production.min.js:212
pu @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Gn @ react-dom.production.min.js:122
gu @ react-dom.production.min.js:248
ru @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Gn @ react-dom.production.min.js:122
Vn @ react-dom.production.min.js:123
Kn @ react-dom.production.min.js:122
R @ react-dom.production.min.js:287
Vt @ react-dom.production.min.js:68
index.js:3404 [Util] handleError::  Uncaught TypeError: Cannot read properties of undefined (reading 'name')
focalboard_0060d90727481ce3_bundle.js:2 [Util] handleError::  Uncaught TypeError: Cannot read properties of undefined (reading 'name')
react-dom.production.min.js:123 Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at Function.mapToProps (index.js:23)
    at r (wrapMapToProps.js:41)
    at Function.r.mapToProps (wrapMapToProps.js:50)
    at r (wrapMapToProps.js:41)
    at selectorFactory.js:22
    at connectAdvanced.js:319
    at Object.useMemo (react-dom.production.min.js:165)
    at t.useMemo (react.production.min.js:25)
    at F (connectAdvanced.js:304)
    at Xo (react-dom.production.min.js:153)
```

**Comment by sbishel** [comment]
"No Boards" is the key to duplicate as is...

**Comment by sbishel** [comment]
I will create a separate ticket for the CSS issue....

**Comment by chenilim** [comment]
I filed #1290 with more detailed steps - this seems to repro if Boards is opened via the channel header, or direct link to board. I'll close 1290 as a dup of this, but see the additional steps there.

**Comment by jespino** [comment]
I'm fixing this as part of the mattermost-webapp repo, changing the emoji picker to allow it to be shown in no-team context.

**Comment by chenilim** [comment]
Is this still an issue? I can't repro it on community-daily, which is running v0.9.1 RC2.

**Comment by wiggin77** [comment]
> Is this still an issue? I can't repro it on community-daily, which is running v0.9.1 RC2.

Works now on daily.  Still broken on community (as expected).

**Comment by ogi-m** [comment]
PR: https://github.com/mattermost/mattermost-webapp/pull/8901
