### ISSUE TITLE
Bug: Incorrect styling for custom status emoji picker.

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#1287]
**Steps to reproduce the behavior:**
1. Go to a workspace; make sure you have a board in the workspace.
2. Click on user profile icon top right
3. Select "Set a custom status"
4. Select emoji picker

**Expected behavior:**
Emoji picker shouldn't be translusent.
Modal should display in middle vertically as well.

**Screenshots:**

![Screen Shot 2021-09-20 at 11 52 02 AM](https://user-images.githubusercontent.com/12704875/134051588-a2399c85-862d-4b82-85a1-3fc92dcd1886.png)

**Edition and Platform:**
 - Edition:Mattermost plugin
 - Version:  v0.9.0 bus bash
 - Browser and OS: Chrome 93 on Mac

**Comment by asaadmahmood** [comment]
@sbishel This issue requires us adding the app__body class to the body tag.
I think @jespino had a PR for that. Not sure if that went in, and if we wanted to take it for 0.9.

**Comment by ogi-m** [comment]
PR: https://github.com/mattermost/focalboard/pull/1202

**Comment by chenilim** [comment]
@jespino, what do you think the risk is to take this for v0.9? What's your recommendation?
