### ISSUE TITLE
Feature Idea: Add option to hide/show empty table groups

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1304]
**Summary:**
Add a toggle option to the Table's Group By menu, "Hide empty groups" with a checkmark if set. When set, groups with no items are not shown.

**How important this is to me and why:**

Importance: Medium

Use cases:
1. OKRs grouped by objective when each quarter has different objectives
2. In general, this is also easier to use than individually hiding empty groups

**Comment by chenilim** [comment]
cc @sbishel and @asaadmahmood, thoughts on this enhancement?

**Comment by vish9812** [comment]
I'll take this one

**Comment by vish9812** [comment]
Hi, I was testing the currently implemented GroupHide feature in TablesView. 
But can't find the feature to Unhide the group again.
Is it a pending feature or a bug?

**Comment by vish9812** [comment]
What should happen when the Checkbox is already in "checked" state and now a group is made empty by moving cards out of the group? 
Possible Solution: group can stay visible until the user re-toggles the Checkbox to the "checked" state.

**Comment by chenilim** [comment]
Thanks @vish9812! You got it!
* Yes, the inability to unhide a group is a bug (https://github.com/mattermost/focalboard/issues/1273)
* Agree - if "hide empty groups" is on, and a user moves the last card (row) out of a group, then it becomes hidden. Unchecking "hide empty groups" will allow them to drag the card back.
  * The group can also be changed directly in the card, as a workaround

cc @asaadmahmood, @wuwinson.

**Comment by vish9812** [comment]
I've added the toggle, let me know if it looks okay?

#### Checked - hide empty groups
![checked](https://user-images.githubusercontent.com/13468514/155014367-90f3b025-fe34-4f8d-b580-23259d448bb7.jpg)

#### Unchecked - unhide empty groups
![unchecked](https://user-images.githubusercontent.com/13468514/155014368-4e144504-9441-461d-851b-e2213abb980b.jpg)

**Comment by jespino** [comment]
@asaadmahmood @wuwinson @chenilim What do you think? It looks good to me.

**Comment by asaadmahmood** [comment]
@jespino Don't mind that!

**Comment by chenilim** [comment]
Thanks @vish9812! Thanks for the quick turnaround. I took a quick look at the PR, and realized there are some subtleties:
1. The "hide empty groups" setting is not persisted (so refreshing the page would make it false by default)
2. It's possible to have a state where "hide empty groups" is on, but non-empty groups are hidden, e.g.:
  * Turn on the switch
  * Open a card, and change its property to a hidden group

So, we need to either change the implementation to store the setting, or change the UX to reflect the actual behavior. I think changing the UX is easier. I propose that instead of the toggle, add 2 menu options:

1. Add a menu option to "Hide N empty groups" (N is populated at run-time, and this option is hidden if N = 0)
2. Add a menu option to "Show M hidden groups" (M is populated at run-time, and this option is hidden if M = 0)

I believe this would also fix #1273. Anyone see any issues with this?

**Comment by vish9812** [comment]
@chenilim Yes, it seems the 2 menu options can solve both the issues.
It can look something like this
![2options](https://user-images.githubusercontent.com/13468514/155210551-7ef71ddd-2c5c-4f16-9789-ee1d0243209e.jpg)

**Comment by chenilim** [comment]
Looks like this issue has been fixed. Closing.
