### ISSUE TITLE
Bug: Creating a board from template doesn't work

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1311]
**Steps to reproduce the behavior:**
1. Open Boards
2. Click on "+Add board"
3. Select an existing template

**Expected behavior:**
Board is created from the template (instead, nothing happens)

**Edition and Platform:**
 - Plugin, latest v0.9.1
 - Mattermost v6.0
 
 **Additional context:**
Creating an empty board works, so it's only an issue with the templates

**Comment by harshilsharma63** [comment]
@ogi-m this is fixed on `main` now.
