### ISSUE TITLE
Bug: Opening Boards from app switcher opens login screen

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1321]
**Steps to reproduce the behavior:**
1. Open Boards from app switcher (exit boards and repeat several times)

**Expected behavior:**
User should be taken to the dashboard

**Screenshots:**
![login](https://user-images.githubusercontent.com/15314183/134484679-89ce9091-c2d5-4193-97b0-b5077bc6888c.jpg)

**Edition and Platform:**
 - Edition: Mattermost plugin 
 - Version: 0.9.1
 - Browser and OS: Chrome on Windows

**Additional context:**

**Comment by harshilsharma63** [comment]
This should be fixed by #1337 .
