### ISSUE TITLE
Webapp Linter Fixes - fix linter warnings for file `markdownEditor.tsx`

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#1352]
The file ...webapp/src/components/markdownEditor.tsx has linter warning for using any object.
	* Run `npx eslint --ext .tsx,.ts .` in the webapp folder to see them

**Comment by anchepiece** [comment]
Hi :wave: @sbishel and mattermost team, thanks for open sourcing this project.
I'd like to attempt adding these types.
