### ISSUE TITLE
Bug: Websocket error banner on shared boards

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1370]
## Steps to reproduce the behavior

1. Deploy plugin v0.9.1 RC2
2. Share a board
3. Open the shared board link in a private browser window
4. Make a change in the original (editable) window
5. A websocket error banner appears in the shared url window

## Expected behavior

No errors

## Screenshots
<img width="1552" alt="Screen Shot 2021-09-29 at 11 15 00 AM" src="https://user-images.githubusercontent.com/46905241/135326079-f6f7d92f-1a64-4696-9dee-7fd16d561a42.png">

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.9.1 RC2
 - Browser and OS: Chrome 93 on macOS

**Comment by chenilim** [comment]
Might be related to #1371

**Comment by mgdelacroix** [comment]
Fixed on https://github.com/mattermost/focalboard/pull/1391
