### ISSUE TITLE
Bug: Dashboard doesn't scroll

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1372]
## Steps to reproduce the behavior

1. Open the dashboard on the v0.9.1 RC2 plugin, on a server where you have many channels
2. Try to scroll vertically, you can't

## Expected behavior

Able to scroll to see all workspaces

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.9.1 RC2
 - Browser and OS: Chrome 93 on macOS

**Comment by hahmadia** [comment]
@ogi-m 

This has been merged into main and release-0.9.0

You can test when you like
