### ISSUE TITLE
Bug: Opening URL to board sometimes opens Dashboard instead

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1373]
## Steps to reproduce the behavior

1. Go to [Focalboard community channel](https://community-daily.mattermost.com/core/channels/focalboard) (on community-daily)
2. Click on "meeting topics" in the channel header
3. Boards dashboard opens

## Expected behavior

The linked board should open

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.9.1 RC2
 - Browser and OS: Chrome 93 on macOS

## Additional context

This might be related to the new routes and dashboard code. It seems that opening a board url in the same tab (e.g. a relative URL) triggers a different code path / navigation.

**Comment by chenilim** [comment]
Assigning to @sbishel to reassign. FYI @harshilsharma63, @hahmadia, @jespino - might be something strange in the routing.

**Comment by harshilsharma63** [comment]
On it.
