### ISSUE TITLE
Bug: Lots of "Unable to clean up the sessions" errors in plugin server log

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1385]
## Steps to reproduce the behavior

1. Run the v0.9.1 RC2 plugin (or recent)
2. Chck the server logs after a day or so
3. See numerous "Unable to clean up the sessions" errors

## Expected behavior

No "Unable to clean up the sessions" errors.

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.9.1 RC2

## Additional context

This is logged by [this line](https://github.com/mattermost/focalboard/blob/80b9abf9dd0e5904e18caac54528940061646e65/server/server/server.go#L260). `CleanupSessions` should not be called in the plugin edition.

**Comment by chenilim** [comment]
@jespino, I think this was already fixed in main. If so, please close the bug. Thanks.

**Comment by jespino** [comment]
Yes, this is fixed on main.
