### ISSUE TITLE
Bug: Sharing Board Link without a view selected creates invalid url

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#1392]
## Steps to reproduce the behavior

1. Turn on Board sharing
Personal server - config.json set "enablepublicsharedboards": true 
Plugin - set in the "Mattermost Boards" configuration in System Console

2. Select a board, not a view but click on the board name.
2. Select  ...
3. Select "Share Board"
4. Turn on sharing and copy the link. 

5. Open link in either incognito or another tab

Receive a page with a message -
"Add or select a board from the sidebar to get started"

## Expected behavior

Should create a valid link.
Other option is to disable "Share Board" unless a view is selected.

## Edition and Platform
- any

## Additional context

I haven't investigated, but my suspicion is it is using the previous "current view id" with the new "current board id" when creating the shared board URL.

**Comment by chenilim** [comment]
@mgdelacroix, assigning to you for now, as this may be a dup or related to https://github.com/mattermost/focalboard/issues/1438 and https://github.com/mattermost/focalboard/issues/1443

**Comment by sbishel** [comment]
Closed by accident...sorry.
