### ISSUE TITLE
Bug: Comment textarea changes height when in focus 

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#1393]
## Expected behavior
It should remain fixed in height in the default state, though we will still allow users to type multiple lines.

## Screenshots
![Oct-01-2021 22-11-03](https://user-images.githubusercontent.com/11034289/135660548-38ca5672-118f-4391-87f8-34f5a291023b.gif)

**Comment by kamre** [comment]
Its the same discrepancy between preview and markdown editor like in #1394

**Comment by sahil9001** [comment]
Can I take this issue?

**Comment by akshat-kumar2109** [comment]
Please assign me this issue. I would like to work on it.

**Comment by asaadmahmood** [comment]
@sahil9001 Sure.
@akshat-kumar2109 Since sahil came first, assigning it to him, but if he does not take it, we can assign it to you.

**Comment by akshat-kumar2109** [comment]
No problem @asaadmahmood

**Comment by sbishel** [comment]
closed as fixed
