### ISSUE TITLE
Feature Idea: Add "show empty" toggle to Dashboard

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1397]
## Summary

Add a toggle switch to show / hide workspaces with 0 boards. Turn on by default. Setting should persist in user settings (localstorage)

## How important this is to me and why

Importance: High

Use cases:
1. The current Dashboard is very cluttered, especially with DM / group message channels
2. This should be on by default to make it easy to populate initial channels

## Additional context/similar features

https://user-images.githubusercontent.com/46905241/135671276-50b039bc-c2ba-4aab-95b2-6c3f61e48369.mp4

**Comment by chenilim** [comment]
Submitting this per the [thread here](https://community-daily.mattermost.com/core/pl/z1qhoag1k7gupd5yyax6t5otqe), with attached PR. What do you all think of taking this for v0.9? I think the risk vs. reward is worth it, but are there any potential issues? cc @sbishel, @ogi-m, @asaadmahmood.

**Comment by sbishel** [comment]
I think it looks pretty safe to cherry-pick.
