### ISSUE TITLE
Feature Request: Changelog entry for every release

### ISSUE THREAD

**Issue by it33** [mattermost/focalboard#141]
**Summary:**

For every release, e.g. v0.6 vs v0.6.1, add an entry to the Changelog

https://github.com/mattermost/focalboard/releases/tag/v0.6.1

**How important this is to me and why:**

Importance: Medium

There's a lot of energy in the early days of a project and reading about the changes in every minor release is a celebration of what's been accomplished--especially when we thank people by their GitHub IDs. 

**Additional context / similar features:**
There's a lot of momentum in this project right now and the Changelog is an opportunity to reflect it!

Also, this shouldn't be hard to do if we ask contributors to update the changelog themselves: https://github.com/mattermost/focalboard/pull/139/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R7

**Comment by chenilim** [comment]
Cleaning up old issues. Changes are now in [CHANGELOG.md](https://github.com/mattermost/focalboard/blob/main/CHANGELOG.md).
