### ISSUE TITLE
Feature Request: Add an "Edit" link to the footer of all pages on the Focalboard.com website that links to the GitHub repo page that can be edited with a pull request.

### ISSUE THREAD

**Issue by it33** [mattermost/focalboard#142]
**Summary:**

Add an "Edit" link to the footer of all pages on the Focalboard.com website that links to the GitHub repo page that can be edited with a pull request.

Use the text: `This page is open source. _Edit_ this page in GitHub`

Example: Link this page on focalboard.com https://www.focalboard.com/download/personal-edition/ubuntu/ to this page in the repo: 
https://github.com/mattermost/focalboard/blob/main/website/site/content/download/personal-edition/ubuntu.md

**How important this is to me and why:**

Importance: Medium

1. Make it more obvious how to edit pages and contribute to documentation. 
2. Avoid misunderstandings like this one: https://github.com/mattermost/focalboard/issues/140

**Additional context / similar features:**
Here is a screenshot and a bad mockup: 
![image](https://user-images.githubusercontent.com/177788/111856052-56cb8980-88e5-11eb-8df3-b6937dfa1f2c.png)

**Comment by rakhi2104** [comment]
Hi @it33 

I've seen a few docs on [developers.mattermost.com](https://developers.mattermost.com/contribute/getting-started/) and is it better to follow the same design pattern? Instead of having the edit link, you can place a link right next to the title. Like this:

![image](https://user-images.githubusercontent.com/17671710/111880271-755a7f00-89d0-11eb-8222-017ab8858406.png)

**Comment by rakhi2104** [comment]
I did a little digging into the code and found, the `page-edit` partial is commented on the title section [here](https://github.com/mattermost/focalboard/blob/b0d8d5a0257eb954e5909efba0dd8aabf21b3814/website/site/layouts/_default/list.html#L18)

**Comment by it33** [comment]
Thanks @rakhi2104 I think either way works. Would you be open to making a pull request to add the change?
