### ISSUE TITLE
Bug: Personal server cannot select board/view

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#1421]
## Steps to reproduce the behavior

1. Latest main; `make all`
2. Log in; using existing sqlite DB 
3. Try to select any view/board
4. Cannot select different view or board
   - when clicking the URL line briefly changes but the browser redirects back to the original URL.

## Expected behavior
Expect to select views

## Screenshots
![cannot_select](https://user-images.githubusercontent.com/5024605/135767034-fd2a4c2d-c1dd-4161-b0bd-9a7e614789cf.gif)

## Edition and Platform

 - Edition: Personal Server
 - Version: main: https://github.com/mattermost/focalboard/commit/f1508df6c177bc7463e6f06ae6685d0f8f01edf7
 - Browser and OS: Firefox 92.0.1 Linux

**Comment by sbishel** [comment]
Investigate in release-0.9.0. branch

**Comment by sbishel** [comment]
Have not been able to duplicate on either release-0.9.0 or main branch. Appears to be isolated to specific machine.

**Comment by sbishel** [comment]
Closing for now.
