### ISSUE TITLE
Feature Idea: Replace button on welcome page to use the Button component instead of the HTML <button>

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#1432]
## Summary
Replace button on welcome page to use the Button component instead of the HTML <button>

## How important this is to me and why

Importance: Low

## Screenshot
<img width="524" alt="Screenshot 2021-10-04 at 2 52 05 PM" src="https://user-images.githubusercontent.com/11034289/135830756-4bbd3bd9-15ba-4e5b-b56e-d8bc16b94b71.png">

**Comment by kamre** [comment]
@asaadmahmood only `welcomePage.tsx` uses `<button>` tag directly. All other places use `<Button>` component.

**Comment by asaadmahmood** [comment]
@kamre Okay cool, then I can update the ticket to replace the button on the welcome page.

**Comment by asaadmahmood** [comment]
@prathamesh3707 Someone has already submitted a fix for this.

**Comment by AbihaFatima** [comment]
Is this issue still open? @asaadmahmood

**Comment by hahmadia** [comment]
This issue is up for grabs again.

**Comment by nishantwrp** [comment]
I'd like to work on this issue.

**Comment by asaadmahmood** [comment]
Go ahead @nishantwrp
