### ISSUE TITLE
UI: Date range highlight should be square, not round, in between dates

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1436]
## Summary

The current date-range property displays circle highlights for ranges:
<img width="310" alt="date range" src="https://user-images.githubusercontent.com/46905241/135889636-f781b43e-3fbf-4365-86f3-83561759bf0c.png">

The highlight for dates in between should be square / filled-in

## How important this is to me and why

Importance: Low

Use cases:
1. This is purely a UI aesthetic issue

**Comment by chenilim** [comment]
@asaadmahmood, I *think* we talked about this briefly, and decided to punt it for now. Are there other visual changes we wanted from the date picker? cc @sbishel.

**Comment by asaadmahmood** [comment]
@chenilim Yup bug.
This is how it should look like.

![image](https://user-images.githubusercontent.com/11034289/135890811-e737298a-399f-4f66-949f-5b83a4e7bed4.png)

**Comment by kamre** [comment]
It looks like this for me on the `main` branch currently:
![image](https://user-images.githubusercontent.com/5587620/135895106-7f690228-2b36-4f94-9c83-92a165fde8d4.png)
Personal server, Windows 10, Chrome 94
