### ISSUE TITLE
Bug: Date range highlight display has wrong end-caps

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1437]
## Steps to reproduce the behavior

1. Open a card with a date property
2. Open the date property
3. Enable "End Date", and specify a range
4. See wrong end-caps of the display

## Expected behavior

The end-caps should curve outwards.

## Screenshots
<img width="310" alt="date range" src="https://user-images.githubusercontent.com/46905241/135889668-262c507a-a163-4f9e-8650-f4c329397466.png">

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.9.1 RC2
 - Browser and OS: Chrome 93 on macOS

## Additional context
The highlight of the dates in between should also be square, which is tracked by #1436.

**Comment by chenilim** [comment]
@asaadmahmood, just want to confirm that this is a bug. cc @sbishel.

**Comment by chenilim** [comment]
Thanks @asaadmahmood! Putting this up for grabs.

**Comment by asaadmahmood** [comment]
This is how it should look like.
Ignore the header, but the dates should look like this for a range:

![image](https://user-images.githubusercontent.com/11034289/135890918-8379958b-4f9c-46be-a91d-0dbb0adc55b6.png)

**Comment by kamre** [comment]
@chenilim @asaadmahmood I have also noticed that the date range spanning between months looks a bit strange (from the video in "Focalboard / Boards October 2021 Roadmap Update"):
![image](https://user-images.githubusercontent.com/5587620/135893810-af964837-2d34-4b46-9b11-dfac989d5d67.png)
First 6 November days are not highlighted though they are in a range. Should this be reported as a separate bug?

**Comment by asaadmahmood** [comment]
@kamre Yes, it can be.

**Comment by kamre** [comment]
Created #1439

**Comment by chenilim** [comment]
This is an issue that has since been fixed. Verified fixed in v0.15, so closing.
