### ISSUE TITLE
Bug: /plugins/focalboard gets added to the URL when loading Boards

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/focalboard#1438]
## Steps to reproduce the behavior

There are two paths that I've seen to reproduce this bug:

1. Use the channel header button to access Boards

On the resulting URL, there is an extra `/plugins/focalboard` at the end. As soon as you select a board, it goes away. The second path starts from a valid board URL and after enabling shared boards:

1. Share a board
2. Copy the URL and check that it's valid and was built as expected
3. Click on the URL, paste the one copied either on an incognito window or a logged in one
4. You'll be redirected either to the boards page with no board selected or to the login page if on an incognito window. The URL will be `base_domain.com/plugins/focalboard/plugins/focalboard/WORKSPACE_ID/shared/...`. Note the two `/plugins/focalboard` that are not only duplicated, but should not be there as the base plugin URL is `/boards`

## Expected behavior

URLs should be correctly formed

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.9.1 and `main`
 - Browser and OS: Firefox 92 on Linux

**Comment by sbishel** [comment]
@mgdelacroix - 

> Note the two /plugins/focalboard that are not only duplicated, but should not be there as the base plugin URL is `/boards`

My understanding is that `/boards` requires an authorized users, which is why this directs to `plugins/focalboard`. Unless that is changing with your work.

**Comment by mgdelacroix** [comment]
@sbishel you're right, in the case of the shared URL it should begin with `/plugins/focalboard` as per the current implementation of Shared Boards, so the issue with that path is only the duplication. The resulting bad URL is causing the router to show the boards page and that confused me.
