### ISSUE TITLE
Bug: Date range doesn't highlight first/last days of the adjacent months

### ISSUE THREAD

**Issue by kamre** [mattermost/focalboard#1439]
## Steps to reproduce the behavior
1. Open a card with date property
2. Select date range: `October 1, 2021` -> `December 15, 2021`
3. Switch to October month in the calendar (not selecting any dates)
4. First days of November are not highlighted but they are in the selected date range.

## Expected behavior
All dates in the selected range should be highlighted.

## Screenshots
![image](https://user-images.githubusercontent.com/5587620/135896443-587432b6-518e-4255-ae3c-89f67a61994d.png)

## Edition and Platform
 - Edition: Personal Server
 - Version: `main` on 2093318
 - Browser and OS: Chrome 94 on Windows 10

**Comment by chenilim** [comment]
Thanks @kamre! Putting this up for grabs.

**Comment by aloks98** [comment]
Hey, I'd like to work on this issue!

**Comment by aloks98** [comment]
Hi, I have fixed this CSS issue but there are some cases where I'd like input from the UI devs.
What if the end date is in next month's dates which show in current view?
![gh1439_1](https://user-images.githubusercontent.com/45600289/136056950-dfe6f255-5f17-4ed7-8845-cf653709b69c.png)

**Comment by asaadmahmood** [comment]
@sbishel Yes I'd be fine with that for now, ideally we want those numbers from the other month to be hidden like what material design does. If that's not possible, we can highlight the date in the same view (and also in the other month).

![image](https://user-images.githubusercontent.com/11034289/136149906-b1044535-3df0-4708-b196-01c917136d0b.png)

**Comment by aloks98** [comment]
@asaadmahmood Let me look into it, if hiding the next month's dates are possible.

**Comment by asaadmahmood** [comment]
@aloks98 Sure, we do style them differently, so I thnk it should be possible.

**Comment by aloks98** [comment]
@asaadmahmood Done with changes
![Screenshot 2021-10-06 at 10 27 16 PM](https://user-images.githubusercontent.com/45600289/136249557-79ff7640-b992-4f58-9e13-b6289ababbcc.png)
![Screenshot 2021-10-06 at 10 27 33 PM](https://user-images.githubusercontent.com/45600289/136249568-2575e8d8-130a-490b-95b4-32a106da6a65.png)
.
