### ISSUE TITLE
Bug: CI tests are currently failing on release-0.9.0 branch

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1442]
## Steps to reproduce the behavior

1. See [release-0.9.0 branch](https://github.com/mattermost/focalboard/tree/release-0.9.0)
2. notice that recent commits have been failing CI tests

## Expected behavior

CI tests all pass

## Edition and Platform

 - Edition: All
 - Version: v0.9.1

## Additional context

See [this CI run](https://github.com/mattermost/focalboard/runs/3793460458) for details on the errors.
CI tests were recently enabled on the release-0.9.0 branch. Some errors are just due to outdated snapshots, but some are not.

**Comment by chenilim** [comment]
@sbishel, filing an issue to track this. I think we just need to update the snapshots, and clean up a couple tests. cc @ogi-m.

**Comment by wiggin77** [comment]
I enabled CI test runs on PRs that target the release branch, so new PRs with failing tests won't slip through going forward.  However, this means no new PRs can be merged with `release-0.9.0` until the existing errors are fixed (or an admin forces a merge).

**Comment by sbishel** [comment]
Perfect. I'm preparing a PR for these fixes now.

**Comment by sbishel** [comment]
Didn't autoclose...closing manually.

**Comment by sbishel** [comment]
Didn't autoclose...closing manually.
