### ISSUE TITLE
Bug: Shared board URL shows login page

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1443]
## Steps to reproduce the behavior

1. Open a board
2. Click on the board menu (...) and select share board
3. Enable sharing
4. Click on copy link
5. Open a private browser window, and paste in link
4. The login screen appears

## Expected behavior

The shared board displays

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.9.1 RC3
 - Browser and OS: Chrome 93 on macOS

## Additional context

You can repro this on my [test server here (invite link)](https://chen-ha.test.mattermost.cloud/signup_user_complete/?id=6ynkaai4mfr13jqjfjio1yx4bc).

**Comment by chenilim** [comment]
This might be a dup / related to https://github.com/mattermost/focalboard/issues/1392 and https://github.com/mattermost/focalboard/issues/1438, but the repro steps here are very direct for me.

**Comment by mgdelacroix** [comment]
Yep, this is a dup of https://github.com/mattermost/focalboard/issues/1438, the modification of the URL causes the router to show the boards, and if you're not logged into the instance you'll see the login instead
