### ISSUE TITLE
Bug: Desktop App: Clicking on the unread filter in Channels sometimes opens the Boards dashboard

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1452]
## Steps to reproduce the behavior

1. Open the Mattermost Desktop App v5.0 (RC2)
2. Click on the unread threads filter button in Channels
3. Sometimes the Boards dashboard opens

## Expected behavior

The Boards view should not open

## Screenshots

![unread thread button](https://user-images.githubusercontent.com/46905241/136068084-2aa5180f-cc23-43a4-b5fe-163927ada81b.gif)

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.9.1 RC2
 - Browser and OS: Desktop App v5 RC2

**Comment by ogi-m** [comment]
Can no longer repro on v0.9 branch
