### ISSUE TITLE
Bug: "Select a template" (on add Board list) looks like a button but it is not

### ISSUE THREAD

**Issue by alauregaillard** [mattermost/focalboard#1469]
## Steps to reproduce the behavior

1. Go to Focalboard
2. Click on "Add Board"
3. Mouse hover the label "Select a template"
The mouse pointer and the background color of the field are like it is a button but clicking is not doing something.

## Expected behavior

The mouse pointer and the background color are not like it is a button.

## Screenshots

![Select a template](https://user-images.githubusercontent.com/86982045/136247155-3a21f602-77d1-4c0b-a70e-ca477800b0ec.png)

## Edition and Platform

 - Edition: Personal Desktop
 - Version: v0.8.0
 - Browser and OS: Windows app, Windows

## Additional context

N/A

**Comment by chenilim** [comment]
Thanks @alauregaillard! I propose fixing by removing the hover highlight from `Menu.Label` elements, unless you prefer a different approach @asaadmahmood? Putting this up for grabs.

**Comment by radiantly** [comment]
Hey, could I take a go at this?
