### ISSUE TITLE
Bug: Columns headers are not align with cards

### ISSUE THREAD

**Issue by alauregaillard** [mattermost/focalboard#1470]
## Steps to reproduce the behavior

1. Open Focalboard
2. Click on "Add Board"
3. Click on "Meeting notes" (View "By type")
4. Add a lot of columns
5. Use the scroll bar (on the bottom)
Columns headers are not align with cards.

## Expected behavior

Columns headers have to be aligned with cards.

## Screenshots

![ColumnsHeaders](https://user-images.githubusercontent.com/86982045/136269384-e56ea595-93d0-415c-8099-ee3627bf4b7a.png)

## Edition and Platform

- Edition: Personal Desktop
- Version: v0.8.0
- Browser and OS: Windows app, Windows

## Additional context

N/A

**Comment by chenilim** [comment]
Thanks @alauregaillard! This was fixed in 0.9. The headers now scroll horizontally with cards. We haven't released 0.9 to the app store yet, but if possible, could you check if this still repros for you on [v0.9.1 RC4](https://github.com/mattermost/focalboard/releases/tag/v0.9.1-rc4)? Thanks!
