### ISSUE TITLE
Bug: shared board link is generated without plugin prefix after refresh on desktop app

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/focalboard#1485]
## Steps to reproduce the behavior

1. On the desktop app, load a board and share it
2. Check the shared url, it should start with `/plugins/focalboard`
3. Refresh with `CTRL+R` or from the top menu
4. Check the shared url, it will not start with `/plugins/focalboard` and will load either the login screen if you try to access it on an incognito window or the "team not found" screen

## Expected behavior

The URL should be the same one that the one generated before the refresh

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.9.1
 - Browser and OS: Desktop v5 on Linux

**Comment by devinbinnie** [comment]
Curious, how come the URL starts with `/plugins/focalboard` and not `/boards`? That might cause some strange Desktop App behaviour.

**Comment by chenilim** [comment]
@devinbinnie (sorry, missed your comment earlier): The shared URLs are off `/plugins/focalboard` because they are meant to be accessed by unauthenticated users, and `/boards/...` would trigger an auth check. In general, the shared URLs are expected to be opened in a browser vs. the desktop app.
