### ISSUE TITLE
Bug: export to CSV fails if the board is showing a multi select property

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/focalboard#1487]
## Steps to reproduce the behavior

1. Create a multi select property
2. Add a couple of values to it
3. Show the property on the board configuration
4. Click on the "export CSV" button. You'll see a "export failed!" message and no prompt to download

## Expected behavior

The export should work properly

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.9.1
 - Browser and OS: Desktop v5 on Linux

**Comment by DeeJayBro** [comment]
I would like to work on this
