### ISSUE TITLE
Allow "show empty" dashboard button to limit drop down.

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#1488]
## Summary

The "show empty" option on dashboard should limit workspace switcher dropdown. (May-be?)

## How important this is to me and why

Low

Use cases:
1. Limits options in drop down allows easier finding of boards.

**Comment by chenilim** [comment]
What do you think @asaadmahmood? Making the toggle apply to the dropdown as well should be easy, but one concern is users may not know to return to the dashboard to change the setting.

**Comment by asaadmahmood** [comment]
Would refrain from it @chenilim Until and unless its explicit in the dropdown, which I don't think is needed.
