### ISSUE TITLE
Bug: "Calculate" menu below the Estimate Property opens underneath and is obscured by the Header row

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#1492]
## Steps to reproduce the behavior

1. In Table view, create a couple of cards and add a property called "Estimate" with the type of number
2. Fill in some test data in the estimate fields of the cards (e.g. 8 and 16)
3. Hover below the "Estimate" field to display the "Calculate ^" option
4. Click on "Calculate ^"
5. Observe: menu opens underneath the header row and is partially obscured by the header row

## Expected behavior
- Menu opens and is not obscured by the header row

## Screenshots

![image](https://user-images.githubusercontent.com/13020833/136450935-e4386891-6145-4ba9-8990-6b7b14b7c388.png)

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.9.1 BETA
 - Browser and OS: Chrome / Win10

## Additional context

I noticed that the "Calculate ^" menu below the "Status" field opens downwards so it seems there's some inconsistency about which way the "Calculate ^" menus open up
![image](https://user-images.githubusercontent.com/13020833/136451496-52a345ac-9e25-4705-a952-f607883cd0f4.png)

**Comment by sbishel** [comment]
@lindy65 - I'm closing this as fixed, reopen if you still see a problem.

**Comment by lindy65** [comment]
Thanks @sbishel - will do!
