### ISSUE TITLE
Bug: Clicking a link in markdown toggles on edit mode

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1498]
## Steps to reproduce the behavior

1. Open a board
2. Add a link to the board description header (e.g. [link](http://www.focalboard.com))
3. Click on the link
4. The link opens in a new tab, but the header enters edit mode
5. Do the same thing with a card description (markdown content)

## Expected behavior

The markdown editor should not enter edit mode when a link is clicked.

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.9.2
 - Browser and OS: Chrome 93 on macOS

**Comment by reyhhan** [comment]
Would appreciate of you can guide me on setting up the dev environment as I'm new to this.
Do I need a macOS to fix this issue or can it be worked on using Windows OS?

**Comment by chenilim** [comment]
Hi @reyhhan, start with the [contributor's guide here](https://www.focalboard.com/contribute/getting-started/) to set up the dev environment. This can be set up on Windows, Linux, or macOS. LMK if you run into any issues. Thanks!

**Comment by kamre** [comment]
@chenilim @reyhhan Looks like this is not reproducible on standalone server for `release-0.9.0` branch. And actually similar bug #1011 was already fixed.

So this might be a Mattermost plugin specific bug.

**Comment by chenilim** [comment]
@prakharporwal, the enableLocalMode setting opens a file socket for the Admin API, mainly for [resetting passwords](https://www.focalboard.com/guide/admin/#resetting-passwords). Unfortunately, it seems that this file isn't always correctly cleaned up, which causes subsequent launches to fail. See #481.
