### ISSUE TITLE
Feature Idea: Convert octo-sidebar-item from <div> to <button>

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#1513]
## Summary
Feature Idea: Convert octo-sidebar-item from <div> to <button>

## How important this is to me and why
Importance: Medium

## Additional context/similar features
This is being used multiple times in the file, so please be sure to replace all instances.
Also, some css changes may be needed to revert the button base styles that are applied, so the UI looks the same as before.

<img width="489" alt="Screenshot 2021-10-11 at 8 16 36 PM" src="https://user-images.githubusercontent.com/11034289/136814813-96dbb628-4963-4b4f-a177-35c53b7b39f4.png">

**Comment by sbishel** [comment]
fixed
