### ISSUE TITLE
Bug: "Create a Board" screen > Low contrast on dark themes

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1519]
## Steps to reproduce the behavior

1. Go to Channels and set a dark theme
2. Go to Boards
3. Click on the "+" button next to the channel switcher
4. Observe the text

## Expected behavior

Text should be easily readable

## Screenshots

![createaboard](https://user-images.githubusercontent.com/15314183/136857456-eb6b0337-d926-4fd0-bc11-1c0684e3e707.jpg)

## Edition and Platform

 - Edition: plugin
 - Version: v0.9.1
 - Browser and OS: Chrome on Windows

**Comment by hahmadia** [comment]
Fixed by https://github.com/mattermost/focalboard/pull/1829
