### ISSUE TITLE
Bug: Mobile web header appears in desktop version of focalboard when window width is small

### ISSUE THREAD

**Issue by tjbortz1s** [mattermost/focalboard#1527]
## Steps to reproduce the behavior

Open focalboard
Shrink the window size until it's "mobile sized"

## Expected behavior

No warning appears or the warning mentions "small width" is unsupported instead?
Focalboard refuses to shrink beyond the size where the mobile header would appear on desktop?

I'm not sure what the expected behavior should be.  It doesn't seem right to get a warning for mobile while not on a mobile platform.

## Screenshots

![image](https://user-images.githubusercontent.com/6193065/136966482-c3c0eed8-3045-4cb7-8471-5290d25f4d4f.png)

## Edition and Platform

 - Windows app 0.9.1

**Comment by sbishel** [comment]
Won't fix.
