### ISSUE TITLE
Bug: Websocket in Plugin behind Traefik not "ready"

### ISSUE THREAD

**Issue by sargreal** [mattermost/focalboard#1531]
## Steps to reproduce the behavior

1. Setup Mattermost behind Traefik with https
2. Go to Boards Plugin
3. Realize that no updates are shown after interactions

## Expected behavior

Interface should be updated after interactions

## Screenshots

![image](https://user-images.githubusercontent.com/19500573/137003181-bfd4b491-344d-4371-915d-03db84aa63a8.png)

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.9.2
 - Mattermost Version: v6.0.0
 - Browser and OS: Firefox on Windows & Mattermost App on Windows

## Additional context

Traefik configuration:
```yaml
        - traefik.http.routers.${STACK_NAME}-app.rule=Host(`${BASE_URL}`)
        - traefik.http.routers.${STACK_NAME}-app.entrypoints=web,websecure
        - traefik.http.routers.${STACK_NAME}-app.service=${STACK_NAME}-app
        - traefik.http.routers.${STACK_NAME}-app.middlewares=redirect-https@file,${STACK_NAME}-sslheader
        - traefik.http.services.${STACK_NAME}-app.loadbalancer.server.port=8065
        - traefik.http.services.${STACK_NAME}-app.loadbalancer.sticky.cookie.secure=true
        - traefik.http.middlewares.${STACK_NAME}-sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
```
partly inspired by https://community.traefik.io/t/how-to-make-websockets-work-with-traefik-2-0-setting-up-rancher/1732

Normal Mattermost websocket works without issues, only in boards it doesn't. I have also read the other websocket issues but they did not help.

~~Another weirdness I discovered but I'm not sure where it comes from yet (but might be related) is the following cookie with the internal ip address:~~
That is only the cookie used for sticky sessions
![image](https://user-images.githubusercontent.com/19500573/137004191-77ae1d57-9832-4c8c-86dd-19bb624fe014.png)

**Comment by nathanaelhoun** [comment]
I had a similar problem, Mattermost v6.0 behing nginx, and setting `ServiceSettings.EnableReliableWebSockets` to `true` fixed that. 
Solution was found [here](https://forum.mattermost.org/t/websocket-issues-with-mattermost-6-0-0-and-boards-mattermost-websocket-client-is-not-ready/12302/4).

**Comment by gabrielctn** [comment]
I have the same issue, the solution to set `ServiceSettings.EnableReliableWebSockets=true` in config.json worked for the browser version but it didn't resolve the problem for Mattermost Desktop v5.0.0. Any idea why ?
I opened #1536  for that matter.
