### ISSUE TITLE
Bug: Title textarea is not focused after creating a new item

### ISSUE THREAD

**Issue by tjbortz1s** [mattermost/focalboard#1532]
## Steps to reproduce the behavior

1. Create a new goal
2. Try to type without clicking anything

## Expected behavior

The title box is focused and typing sets the title.

## Screenshots

![TitleBoxNotFocused](https://user-images.githubusercontent.com/6193065/137011021-731b2220-b188-4083-b7a4-b091d027ac93.gif)

## Edition and Platform

 - Windows app v9.2 

## Additional context

I saw there was an existing issue for this that had been fixed/closed, but it doesn't seem to be working still.  I wasn't sure if commenting on a closed ticket counts for anything or if a new one is necessary.

**Comment by kamre** [comment]
@tjbortz1s @chenilim It seems that corresponding fix from #1120 wasn't cherry picked to release branch.
