### ISSUE TITLE
Feature Idea: Dashboard: allow searching for words rather than only substrings

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#1539]
## Summary

<img width="1361" alt="Screenshot 2021-10-13 at 5 08 29 PM" src="https://user-images.githubusercontent.com/18575143/137125639-b4737f4a-5153-495b-b8c5-21b984160ad1.png">

Currently, when we search for something in the dashboard search box, it searches for a substring.

The search can be improved by searching for the individual words in the input query.

For example, if there is a workspace named - `Foo Bar Baz`, searching for `foo baz` should bring this up.

## How important this is to me and why

Importance: Low

Use cases:

1. Searching for workspaces when you don't remember its full/exact name.

**Comment by De1ain** [comment]
Hi @harshilsharma63, please assign this issue to me.
