### ISSUE TITLE
Table name and property cells should clip

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#154]
**Summary:**
The contents of some table cells overflow.

**Steps to reproduce the behavior:**
1. Open a table view
2. Manually resize the columns smaller than the contents
3. The name and property cells overflow

**Expected behavior:**
All cells should clip.

**Screenshots:**
<img width="801" alt="Table column clipping" src="https://user-images.githubusercontent.com/46905241/111886818-efb5df80-898d-11eb-90a5-c351aa8cd8ad.png">

**Platform:**
 - Chrome 89 on macOS 10.15.7

**Additional context:**
Text, date, and number cells appear to clip correctly.

**Comment by chenilim** [comment]
This appears to be an issue with the CSS.

**Comment by it33** [comment]
@asaadmahmood is this something you could help with?

**Comment by asaadmahmood** [comment]
@it33 Yes I can look at it.

**Comment by Victor239** [comment]
Also when the column title overflows this makes you unable to manually resize the columns again.
![](https://i.imgur.com/dYX4uqg.png)

**Comment by asaadmahmood** [comment]
Thanks, I'll look into that too @Victor239

**Comment by Jeeboot** [comment]
And when the text overflows the cell, you can't resize it manually.

**Comment by asaadmahmood** [comment]
All of those should be fixed by this PR:
https://github.com/mattermost/focalboard/pull/182

**Comment by jespino** [comment]
Close with the PR #182
