### ISSUE TITLE
Limit a card's title length

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#1542]
## Summary

Currently, a card's title has no virtual limit in the database or the UI.

Add a limit of 1000 characters to the card title.

Also, make sure it displays correctly in the UI.

## How important this is to me and why

Importance: Low

**Comment by JenyaFTW** [comment]
Can I take this?

**Comment by asaadmahmood** [comment]
@JenyaFTW Sure

**Comment by sbishel** [comment]
closing https://github.com/mattermost/focalboard/pull/1548
