### ISSUE TITLE
Bug: Switch widget style

### ISSUE THREAD

**Issue by jenyaftw** [mattermost/focalboard#1543]
## Steps to reproduce the behavior

1. Open settings pop up menu in bottom left corner
2. See the switch widget for random icons option item.

## Expected behavior

![image](https://user-images.githubusercontent.com/24240873/137135058-254dad09-59e5-46a0-9130-37a6ff6c692e.png)
![image](https://user-images.githubusercontent.com/24240873/137135104-da92d0e9-10b6-4ebe-a38c-64817ebbd7a9.png)

## Screenshots

![image](https://user-images.githubusercontent.com/24240873/137134882-4b1f0304-661e-4d9f-ad43-b3e536cf4715.png)
![image](https://user-images.githubusercontent.com/24240873/137134920-f98a8497-4102-495c-8fca-10a5d6dbdf58.png)

## Edition and Platform

 - Edition: Personal Desktop
 - Version: Latest
 - Browser and OS: Firefox 93 on Arch Linux

**Comment by kamre** [comment]
@jespino @asaadmahmood rendering of `Switch` component looks better now for personal server but still not the same as in the plugin.

Personal server:
<img width="240" alt="image" src="https://user-images.githubusercontent.com/5587620/149627089-fa58bb71-5d9c-42e3-8f4e-a3ec5e90ff28.png">

Plugin:
<img width="240" alt="image" src="https://user-images.githubusercontent.com/5587620/149627153-4e3c328c-3799-4a4e-bc94-66b366c29df1.png">

The reason for this is that for the plugin and personal server different CSS selectors are used, i.e. for the plugin there is always `.focalboard-body` [added at the beginning](https://github.com/mattermost/focalboard/blob/342c8df39d2c88fb63ca1a544e3babb850102598/mattermost-plugin/webapp/loaders/globalScssClassLoader.js#L16).

This leads to the situation when some [default styles](https://github.com/mattermost/focalboard/blob/342c8df39d2c88fb63ca1a544e3babb850102598/webapp/src/styles/main.scss#L35-L72) from `main.scss` have higher specificity than selectors like `.Switch { .... }` but lower specificity than `.focalboard-body .Switch { ... }`

What is the proper way to fix this situation? We can start adding `.focalboard-body` back in some cases but this will defeat the purpose of #1068
