### ISSUE TITLE
Bug: Person property is not centered vertically

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#1576]
## Steps to reproduce the behavior

1. Go to a card
2. Select  'New Property'
3. Select 'Person'
4. Select a person from the dropdown
5. Value is not centered vertically
## Expected behavior

All other properties appear to be centered vertically

## Screenshots
![Screen Shot 2021-10-15 at 4 01 32 PM](https://user-images.githubusercontent.com/12704875/137558401-092527d4-77ee-4896-ae78-f4b1fc001355.png)

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: [v0.9.0]
 - Browser and OS: [Chrome 94 on macOS]

**Comment by kamre** [comment]
Looks similar to this:
 - #1096

**Comment by sbishel** [comment]
Closing as fixed.
