### ISSUE TITLE
Bug: submenus are always visible

### ISSUE THREAD

**Issue by kamre** [mattermost/focalboard#1581]
1. Click on _Settings_ menu
2. Hover over _Set theme_ to show submenu
3. Move mouse to _Random icons_ menu item
4. Submenu is still visible

## Expected behavior

Submenu should disappear when any other menu item on the same level is hovered.

## Screenshots
![SubmenuAlwaysVisible](https://user-images.githubusercontent.com/5587620/137598923-ed1d2fb1-438c-455a-b40f-1bd71cfd4c84.gif)

## Edition and Platform

 - Edition: Personal Desktop / Personal Server
 - Version: `main` branch
 - Browser and OS: Chrome 94 on Windows 10

## Additional context
Regression was introduced in this pull request:
- #1553

@adithyaakrishna FYI

**Comment by ogi-m** [comment]
Tested and passed on v0.15 RC2 (plugin and personal desktop)
