### ISSUE TITLE
Bug: Gallery view doesn't work

### ISSUE THREAD

**Issue by mpetitdemange57** [mattermost/focalboard#1596]
## Steps to reproduce the behavior

1. Create a card 
2. Add a description (at the bottom of the card)
3. Create a Gallery view
4. Go to the created Gallery view
5. ERROR - The screen is empty nothing is printed

## Expected behavior

The Gallery should print the different cards 

## Screenshots

![image](https://user-images.githubusercontent.com/44063558/137914897-8bbe7e2a-a36f-4eb3-8171-600c42057290.png)
![image](https://user-images.githubusercontent.com/44063558/137915142-6975f5ea-c2fb-43e8-b343-7ee249e92bd3.png)

## Edition and Platform

 - Edition: Personal Server 
 - Version: [e.g. v0.9.0]
 - Browser and OS: [ Chrome / Windows ]
 - Installed with docker

**Comment by kamre** [comment]
Should be fixed in #1556
