### ISSUE TITLE
Feature Request: Option to disable "create an account" and make it invite-only 

### ISSUE THREAD

**Issue by basst85** [mattermost/focalboard#162]
**Summary:**
It would be nice if you can disable the "create account" functionality and enable "invite-only".
The first user becomes the "admin" and can disable the option "everybody can create accounts" and can send invites to new users (team members).

**How important this is to me and why:**
Medium

Use cases:
1. Team leader invites team members

**Additional context / similar features:**
Any examples of good implementations of this capability.

**Comment by chenilim** [comment]
Thanks @basst85 for the input! To clarify the current behavior:
* The first user can [create an account without an invite link](https://www.focalboard.com/guide/server-setup/#registering-the-first-user)
* Subsequent users must be invited by another user (from the Focalboard menu, with a token in the link)
* Any user an invite other users, as well as invalidate (regenerate) the invite link token
* There currently isn't a mechanism to completely disable account creation
* And there currently isn't an "admin" or other roles. All users have the same permissions.

The assumption is that for small team use, all users can be trusted to do the right thing. And this was also to keep complexity down for v1. Would definitely like to hear about other pain points, to help figure out where this capability fits. Maybe there are specific scenarios where a small team isn't fully "trusted"?
