### ISSUE TITLE
Select property text does not stop at the edge of the card.

### ISSUE THREAD

**Issue by MalikuMane** [mattermost/focalboard#1632]
## Steps to reproduce the behavior

1. Using a personal task template, click Properties -> status.
2. Change "To Do" to "A long select property for testing"

## Expected behavior
Test should stop at the right edge of the card.
## Edition and Platform

 - Edition: Personal Server
 - Version: v0.9.2
 - Browser and OS: Firefox 91.2 openSUSE Leap 15.3
![Screenshot_20211022_114724](https://user-images.githubusercontent.com/6107641/138507472-ffd4cd6d-1887-4e37-977c-b14722d601cd.png)

**Comment by sbishel** [comment]
Closing as fixed.
