### ISSUE TITLE
"Add content" should be visible at all times

### ISSUE THREAD

**Issue by kirtilodha** [mattermost/focalboard#1634]
## Summary

To let the user know that they can add more content, the option should be visible at all times.

Use cases: Better interaction

## Additional context/similar features
Screenshots

https://user-images.githubusercontent.com/67586672/138514641-bafec18a-b65d-453f-bfa2-557dfd4590b3.mp4

**Comment by asaadmahmood** [comment]
@chenilim Sounds good.

**Comment by chenilim** [comment]
Closing as "by-design" for now, but feedback noted - we should make our controls more "Fast, Obvious, and Forgiving".
