### ISSUE TITLE
Bug: Default card template on a board template adds a card to the template, not the board

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1690]
## Steps to reproduce the behavior

1. Click on +, and select "+ New Template", name the new template "Board template"
2. Click on the dropdown off the New button
3. Select + New template (new card template)
4. Name the new card template (e.g. "Card template")
5. Click on the dropdown off the New button again
6. Click on the "..." menu for "New card template", and select "Set as default"
7. Now create a new board off this new template:
8. Click on the + button in the sidebar
9. Select "Board template"
10. Click on the New button to add a new card
11. Notice that the card was not created in the board
12. Now click on the + button in the sidebar, then click ... off the "Board template" template
13. Notice that the card was added to the template instead

## Expected behavior

The card should be added to the board, not the template

## Screenshots

https://user-images.githubusercontent.com/46905241/139296695-90e8ef19-a7a4-4127-b94c-2d8d8c5ad8da.mov

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.10.0 RC1
 - Browser and OS: Chrome 93 on macOS

**Comment by sarvani1997** [comment]
I would like to work on this.

**Comment by chenilim** [comment]
Thanks @sarvani1997, but we decided this looks like a P1 issue we should investigate - it might be a problem in the object model workflow. Assigned to @hahmadia.

**Comment by ogi-m** [comment]
Tested and passed on v0.10 - working as expected.
