### ISSUE TITLE
Bug: Adding a card from the + button at the top of a board group / column doesn't open the card

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1694]
## Steps to reproduce the behavior

1. Open a board
2. Click on the + button at the top of a column / group
3. A card is added, but not opened

## Expected behavior

The card should be auto-opened.

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.10.0 RC1
 - Browser and OS: Chrome 93 on macOS

## Additional context

This is to make it consistent with adding a card from other controls: The + button at the bottom of a column, and the New button.

**Comment by ironbyte** [comment]
Hi, please assign this issue to me, thanks!

**Comment by sbishel** [comment]
fixed
