### ISSUE TITLE
Bug: Board calculations menu shows repeated entries

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1696]
## Steps to reproduce the behavior

1. Export the [Focalboard v1 team board](https://community-daily.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/47aa9bb4-6967-4a96-83c7-11bd6b20f1eb/7e38eab4-890a-4fc3-8f48-a1f9bd1ab822) as an archive
2. Import it into a test server running v0.10.0 RC1
3. Open the "By Target release" view
4. Select a column summary calculation
5. Notice that the menu shows many repeated entries (for Sum, Avg, etc.)

## Expected behavior

Only one set of calculation functions at the top level.

## Screenshots

<img width="642" alt="Screen Shot 2021-10-28 at 2 34 15 PM" src="https://user-images.githubusercontent.com/46905241/139339848-9a4a94fd-a1fe-48e8-a547-522316dce703.png">

<img width="406" alt="Screen Shot 2021-10-28 at 2 41 51 PM" src="https://user-images.githubusercontent.com/46905241/139340421-20401ee6-ae49-4fc2-8ffe-b938be3e4d70.png">

<img width="410" alt="Screen Shot 2021-10-28 at 2 42 07 PM" src="https://user-images.githubusercontent.com/46905241/139340446-d9ef4503-af51-4570-a11e-9e68d2e8ded0.png">

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.10.0 RC1
 - Browser and OS: Chrome 93 on macOS

**Comment by harshilsharma63** [comment]
Merged in main and cherrypicked in `release-0.10`.
