### ISSUE TITLE
Bug: Card links don't open the card dialog when opened in the same tab

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1702]
## Steps to reproduce the behavior

1. Post a link to a card in channels
2. Click on the link (not the card preview) - user is taken to boards (in the same tab) and the card dialog opens
3. Return to channels
4. Click on the card link again - user is taken to boards but the card dialog doesn't open

## Expected behavior

The card dialog should open every time the user opens a link to a card

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.10
 - Browser and OS: Chrome 94 on Windows

## Additional context
This happens with card links that open in the same tab. If it opens in a new tab (which is the case when clicking on a card preview), then it opens the card dialog successfully every time.
- Opening a card link in the same tab doesn't open the card
- Opening the card link in a new tab successfully opens the card

**Comment by jespino** [comment]
This is again related to the routes, for some reason is getting the route from the history object of mattermost side instead of getting the route from the history object in the focalboard side. I have to investigate it more.

**Comment by ogi-m** [comment]
Tested and passed on latest v0.10

**Comment by lindy65** [comment]
Hi, I'm reopening this issue as clicking on a card link from a channel on self-hosted servers (Rainforest v6.2 rc2 and mysql.test v6.2.2 rc1) does not open the card - only opens Boards.  

It makes no difference whether you copy the card's link from the 3-dots on the card in Table View or from within the opened card itself - neither link opens the card from Channels.

**Comment by lindy65** [comment]
I see this is fixed in v0.12 of the plugin so I will retest in Rainforest once the servers have been updated to the latest plugin.
