### ISSUE TITLE
Bug: The images in the README are broken

### ISSUE THREAD

**Issue by kitarp29** [mattermost/focalboard#1707]
## Summary

The images in the README are broken.

## Screenshots
![image](https://user-images.githubusercontent.com/56778773/139573245-06f1861d-be1c-4614-b3fb-57b6106e01ad.png)

## Link to the documentation page

If applicable, link to the documentation page and/or section where you feel the improvement could be added. E.g. `https://github.com/mattermost/focalboard/blob/main/README.md'

**Comment by kitarp29** [comment]
Please assign this issue to me @peterk

**Comment by chenilim** [comment]
Thanks @kitarp29! Looks like this has since been fixed by https://github.com/mattermost/focalboard/pull/1808. Please reopen if you still see issues. Thanks!
