### ISSUE TITLE
Feature Request: Multiple export options

### ISSUE THREAD

**Issue by Victor239** [mattermost/focalboard#171]
**Summary:**
Ability to export all data in a choice of several different formats:
- CSV (doesn't maintain relational data well, but is compatible with virtually any tool)
- JSON/XML (structured data means that it's suitable for full backups/archives, but requires being imported into Focalboard to be manipulated)
- SQLite/other database format (maintains relational data well and allows manipulating data in a database editor, but is compatible with fewer tools)

**How important this is to me and why:**

Before investing my time and data into any tool I want to be sure that there's no lock-in. If at any point I decide Focalboard isn't for me I want to be able to easily export my data so I can at the very least access and manipulate it locally. Only then am I most comfortable continuing to use it, because I don't have to worry "but what if it stops updating/they go closed-source/it becomes incompatible with my platform/etc".

Importance: High

Use cases:
1. Full backups
2. Import/export to similar apps
3. Interoperability with other tools

**Additional context / similar features:**
Any examples of good implementations of this capability.

**Comment by chenilim** [comment]
Hi @Victor239, thanks for the input! Yes, data sovereignty is one of the major benefits of a self-hosted system, and Focalboard currently supports several ways to export your data:
* [JSONL Archive](https://www.focalboard.com/guide/user/#archives): The [JSON lines format](https://jsonlines.org/) is used for perf. This is also the import format.
  * Note that data files (images) aren't part of the export. These are stored in the /files folder, and can be copied separately.
* CSV: Individual boards and tables can be exported to CSV from the options menu
* SQLite: Not necessarily a supported method, but if your DB is SQLite (default), the focalboard.db file can simply be copied and queried directly.
* APIs: In addition, you could write export scripts against the [REST API](https://htmlpreview.github.io/?https://github.com/mattermost/focalboard/blob/main/server/swagger/docs/html/index.html)

Please let me know if you run into any issues with any of the above methods.

**Comment by Victor239** [comment]
Awesome! So glad to see that all the options are available. 

After testing now I wasn't initially sure if JSON+CSV exports are working because there's no pop-up that the export was successful, but I can see now they've been saved to `~/Downloads/` directory. For the future a notification that it worked would be handy, but otherwise this feature looks great.

**Comment by chenilim** [comment]
Thanks @Victor239. I've created a new issue #174 to show a confirmation of export. On Chrome it shows a download at the bottom of the screen, but this might differ by browser. If you have a minute, please add any additional notes to the issue, and what browser / OS you are using. Thanks!

**Comment by Nik-Olaas** [comment]
Hi, I do not find a possibility for export a Board. I use Version 0.15.2 (33) -> I got this version via Apple AppStore. 
Anyone has an idea? 

THX Nik.
