### ISSUE TITLE
Bug: impossible to register more than one user

### ISSUE THREAD

**Issue by JamesDAdams** [mattermost/focalboard#1712]
## Steps to reproduce the behavior

Try to register 2 user

## Expected behavior

![image](https://user-images.githubusercontent.com/20860324/139647924-5be2888e-8714-4212-aa76-b62a3eb655ca.png)
## Edition and Platform

![image](https://user-images.githubusercontent.com/20860324/139648261-f7e2875b-04da-4f14-ab4d-09a11e9e03d7.png)

 - Edition: Personal Server  Docker
 - Version: latest
 - Browser and OS: latest

**Comment by JamesDAdams** [comment]
When trying to register a second user there is nothing in Authorization

![image](https://user-images.githubusercontent.com/20860324/139648668-62b6c6d2-bdcc-4654-a142-5c629cd2d26a.png)

**Comment by JamesDAdams** [comment]
Is it only me who has this bug ?

**Comment by JamesDAdams** [comment]
up, it's a critical problem !

**Comment by JamesDAdams** [comment]
It's a abandoned project ?

**Comment by kamre** [comment]
@JamesDAdams hi! Do you use a proper invite link for the second user as described [here in the docs](https://www.focalboard.com/guide/server-setup/)?

**Comment by JamesDAdams** [comment]
> @JamesDAdams hi! Do you use a proper invite link for the second user as described [here in the docs](https://www.focalboard.com/guide/server-setup/)?

Thank you, I had not seen this, it would be an option so that people can register without an invitation link
