### ISSUE TITLE
Bug: Text doesn't in Kanban Board Calculation when too long

### ISSUE THREAD

**Issue by hahmadia** [mattermost/focalboard#1721]
## Steps to reproduce the behavior

Choose Date Range for Date, Notice that the Text show up like the following in the Kanbard Board Calculation
![image](https://user-images.githubusercontent.com/17804942/139858608-930d3ec2-4179-499d-85b8-0689d1ecd78b.png)

## Expected behavior
Shows without wrapping? or maybe a larder header?

## Screenshots

![image](https://user-images.githubusercontent.com/17804942/139858681-279e58cd-29e4-4f9c-b68b-2c6a23da95da.png)

![image](https://user-images.githubusercontent.com/17804942/139858836-1b06082d-451f-472a-8f23-69a47f190c5a.png)

**Comment by chenilim** [comment]
@hahmadia, this is a dup of another bug I filed. Please close one of them as a dup. Thanks.

**Comment by hahmadia** [comment]
Closing this as a duplicate. Thanks Chen
