### ISSUE TITLE
Bug: Dragging column in Table view trades columns, rather than inserting

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#1724]
## Steps to reproduce the behavior

1. Go to a table view
2. Create at least 3 columns (1,2,3)
3. Drag column 3 to column 1
4. Column 1 and 3 switch rather than moving dragged column (3,2,1)

## Expected behavior

Columns should be ordered 3, 1, 2..

## Screenshots

Uploading Nov-02-2021 07-21-11.mp4…

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: [v0.10.0]
 - Browser and OS: Chrome 95 on macOS

**Comment by chenilim** [comment]
Agree, let's fix this for v0.10 unless it's risky.

**Comment by ogi-m** [comment]
Tested and passed on v0.10 - column now gets inserted instead of traded
