### ISSUE TITLE
Bug: Board calculations: Dates are cut off

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1727]
## Steps to reproduce the behavior

1. Go to a board
2. Select a column calculation
3. Select "Latest date" or "Date range"
4. Display is cut off

## Expected behavior

The date should be displayed.

## Screenshots

<img width="280" alt="Screen Shot 2021-11-02 at 9 22 35 AM" src="https://user-images.githubusercontent.com/46905241/139905519-9ebf32a7-6f2e-4557-8518-fc2227b911ad.png">

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.10.0 RC1
 - Browser and OS: Chrome 93 on macOS

## Additional context

In Notion, the value is shown in full. However, their date ranges are shown as momentjs-style summaries (e.g. "a month").

**Comment by chenilim** [comment]
Suggest looking at adding a "nowrap" and "truncate after X width" CSS style. And the tooltip should show the full value. What do you think @asaadmahmood?

**Comment by ogi-m** [comment]
Tested and passed on v0.10 - text is truncated, and tooltip shows the full text
