### ISSUE TITLE
Bug: Search doesn't clear when changing views

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1730]
## Steps to reproduce the behavior

1. Open a board
2. Enter text in the search box and press enter, view is filtered
3. Switch to another view
4. The new view is still filtered by the search box

## Expected behavior

The search filter should clear when switching views

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.10.0 RC1
 - Browser and OS: Chrome 93 on macOS

**Comment by chenilim** [comment]
FYI @asaadmahmood, do you agree with this chane?

**Comment by nishantwrp** [comment]
Hi, I'd like to work on this issue.

**Comment by chenilim** [comment]
Thanks @nishantwrp! You got it!
