### ISSUE TITLE
Bug: Horizontal drag&drop scrolling is difficult

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#1731]
## Steps to reproduce the behavior

1. Create board view with cards in more groups than can fit on screen
2. Position bottom scroll bar to the far right
3. Grab a card and drag it to the left
4. Notice as you reach the edge of screen that it scrolls a bit, but you have to move the cursor back and forth to continue scrolling

## Expected behavior
Nice smooth scrolling experience

## Screenshots

![horz_scroll](https://user-images.githubusercontent.com/5024605/139908371-98388863-ef0a-4fb2-8c6f-cf0561cc2dba.gif)

## Edition and Platform

 - Edition: Mattermost plugin
 - Version:  v0.10.0
 - Browser and OS: Linux + Firefox 93

**Comment by chenilim** [comment]
Putting this up for grabs - it seems that the direct improvement would be to increase the area for which the board scrolls. What do you think @asaadmahmood?
