### ISSUE TITLE
Show confirmation that export is completed

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#174]
**Summary:**
It's not entirely obvious that export completed

**Steps to reproduce the behavior:**
1. Open a board
2. Click on Settings and choose `export archive`
3. File is downloaded, but is not completely obvious (may differ by browser)

**Expected behavior:**
Show a pop-up dialog that export is competed

**Platform:**
 - Chrome 89 on macOS 10.15.7

**Additional context:**
Similar for export CSV

**Comment by Victor239** [comment]
Tested on Kubuntu 20.10 with Linux desktop app, no notification that export was successful.

**Comment by BharatKalluri** [comment]
I can pick this up, looks like this is a small UI change which I should be able to quickly do.

I think there should be "Export complete!" flash message on successfull export or "Export failed!" on a failure.
If this sounds good, I'll make a PR with these changes 😄

**Comment by chenilim** [comment]
Hi @BharatKalluri, yes thanks for offering to contribute a PR! That sounds great. Agree that a temporary message would work best. You can use the [FlashMessages component](https://github.com/mattermost/focalboard/blob/main/webapp/src/components/flashMessages.tsx) to do that. LMK if you run into any issues or have any questions.

**Comment by jespino** [comment]
This is done in the PR #178. Thanks @BharatKalluri!
