### ISSUE TITLE
Feature Idea: Email Notifications

### ISSUE THREAD

**Issue by jwfox5150** [mattermost/focalboard#1750]
## Summary

Email notifications when a person is assigned to a task / task status is changed

## How important this is to me and why

Importance: Medium
This would complete my needs with this software

Use cases:
1. Person is assigned to a task and receives notification via email
2. Task of which someone is assigned has a status change, person who is assigned receives notification via email

**Comment by kitarp29** [comment]
Hey @peterk I can implemnt it using Mailchimp or some other service like SMTP.
Do you would like me to work on this?

**Comment by chenilim** [comment]
Thanks @jwfox5150! Sorry for the delayed response, but this is currently being tracked by the [Change Notifications feature](https://community-daily.mattermost.com/plugins/focalboard/workspace/qgsck6cts3fwpqwyjiupjm5cde/shared/b4ctmm917q3rzdfi451qtuxjzcw/vuswsftt1rb873datosmmbtwkpa/cqbmjyyxgotdydfwt6chjs6op1c?r=k995q65fg14cop75s8wkzxr76cc) ([spec](https://docs.google.com/document/d/1QuLN9OUn7LNC0GttUQv0DYYaxgJ2gV_8VlGryTe5Dt4/edit#heading=h.vii62ytuqz5d)). In short, we will add a "follow card" feature to receive change notifications (ETA is Jan release), and later the ability to assign owners who will also receive notifications.

**Comment by wiggin77** [comment]
@chenilim I think this can be closed as fixed.

**Comment by chenilim** [comment]
Thanks @wiggin77! Closing this issue as the core features have been implemented. For more details, please refer to the [docs here](https://docs.mattermost.com/boards/work-with-cards.html#work-with-cards) for at-mentions and following cards.

Notes:
* Following cards will be released in v0.12.1.
* I don't believe assigning someone a card (setting a Person property to their alias) will notify them yet? We should revisit / track this separately if not. cc @wuwinson, @asaadmahmood.

**Comment by wuwinson** [comment]
@chenilim Assigning someone a card will not notify them yet. Tracking that feature on [this card](https://community-daily.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/b4ctmm917q3rzdfi451qtuxjzcw/vuswsftt1rb873datosmmbtwkpa/chbyyeudxu3f7bg9zfdfe8x1omy).
