### ISSUE TITLE
Bug: Share Boards dialog is too narrow until switch is turned on

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1760]
## Steps to reproduce the behavior

1. Open a board, on a server with Share boards enabled
2. Open the  ... menu and select "Share board"
3. Notice that the dialog is narrow
4. Enable the switch
5. The dialog expands

## Expected behavior

The dialog should be a consistent (or at least minimum) width

## Screenshots

<img width="330" alt="Screen Shot 2021-11-04 at 2 35 16 PM" src="https://user-images.githubusercontent.com/46905241/140423527-946e4480-5a0a-4dec-992a-15d7f020fce8.png">

<img width="455" alt="Screen Shot 2021-11-04 at 2 35 23 PM" src="https://user-images.githubusercontent.com/46905241/140423617-2f75f0da-67b9-470c-a317-a2cab334ca86.png">

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.10.0 RC2
 - Browser and OS: Chrome 93 on macOS

## Additional context

This is a minor issue, likely caused by the new longer text.

**Comment by chenilim** [comment]
@asaadmahmood, what do you think the expected behavior should be here? E.g. should we set a minimum width on the dialog? It's pretty minor, and we can close won't fix if you don't think it's worth it. Thanks.

**Comment by asaadmahmood** [comment]
Closing this as we're moving this into a larger modal.
