### ISSUE TITLE
Boards not respecting Site URL

### ISSUE THREAD

**Issue by fksu** [mattermost/focalboard#1766]
## Steps to reproduce the behavior
1. Setup Mattermost with Focalboard behind a reverse proxy forwarding through a prefix (https://site.com/mattermost).
2. Go to Boards (URL changes to https://site.com/boards/welcome while still working).
3. Refresh the page.
4. See 404.

## Expected behavior
URL stays beyond https://site.com/mattermost (as defined via Site URL).

## Edition and Platform
 - Edition: Mattermost Server / Focalboard
 - Version: v6.0.3-rc1 / v0.9.4
 - Browser and OS: any

**Comment by sbishel** [comment]
Investigate for 0.11

**Comment by ogi-m** [comment]
Confirmed this reproes on v0.10 @harshilsharma63

**Comment by wiggin77** [comment]
> Confirmed this reproes on v0.10 @harshilsharma63

@ogi-m, what proxy did you use to repro?

**Comment by chenilim** [comment]
Moving this to v0.12 after the last discussion - it's an existing issue, and we need more time to sort out the various "baseURL" settings. cc @sbishel, @wuwinson, @ogi-m, @wiggin77.
