### ISSUE TITLE
Bug: v0.10.0 Windows & Mac standalone app - not able to attach an image to a card in Gallery view

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#1767]
I've reproduced locally on the Windows app (don't have a Mac to repro locally on this OS)

## Steps to reproduce the behavior

1. Download the Windows or Mac standalone app from the links below:
    - Windows: https://focalboard-builds.s3.amazonaws.com/latest/focalboard-win.zip
    - Mac: https://focalboard-builds.s3.amazonaws.com/latest/focalboard-mac.zip
2. Create a board
3. Add a Gallery view
4. Add a card 
5. Hover over "Add a description" in the card then click on "Add Content" that appears below
6. Select an image to add to the card

## Observed:
- Image is not added to the card

## Expected:
- Image is added to the card

## Edition and Platform

 - Edition: Personal Desktop
 - Version: v0.10.0
 - Browser and OS: Windows and Mac

**Comment by chenilim** [comment]
Thanks @lindy65! @ogi-m, could you check if this repros on plugin and / or Personal Server?

**Comment by lindy65** [comment]
Apologies, I did not say but this does NOT repro on plugin on v0.10.0 on the Rainforest servers (nor on v0.9.4 plugin running on community servers)

**Comment by chenilim** [comment]
Thanks @lindy65! I also just tested this with the v0.10.0 RC2 Mac App, and it does not repro (able to attach an image to a card), so right now this seems to only affect Windows Personal Desktop (Personal Server and Linux App unknown at this point).

**Comment by chenilim** [comment]
Ok, more info: This bug **does repro** with the Mac build in the link above (not v0.10.0 RC2). Furthermore, I cannot update or add any content to a card, e.g. text, divider, etc. @lindy65 / @ogi-m do you see this too? It appears to be a bug on the main branch, but not release-0.10.0.

**Comment by chenilim** [comment]
I see this issue on a dev build too BTW. After a quick investigation, it appears that this broke after this PR: https://github.com/mattermost/focalboard/commit/fa36e092bb462d1b7d44b3d49a358c9fdfc1b778 (server generated IDs) - I tested the Mac App from the dev build before and after this PR. cc @mgdelacroix.

**Comment by lindy65** [comment]
Hey @chenilim - I do not have a mac so I'm not able to help repro the issues you found.

**Comment by mgdelacroix** [comment]
I don't have any Mac or Windows to try the fix, but I'm reproing on Linux as well, so I'm happy to fix it there and then check if the fix works for other OSs.

**Comment by ogi-m** [comment]
Tested and passed on latest main
