### ISSUE TITLE
Bug: Text layout issue on a board item

### ISSUE THREAD

**Issue by amyblais** [mattermost/focalboard#1784]
Originally reported by Neil: https://mattermost.atlassian.net/browse/MM-39927

## Steps to reproduce the behavior

I added text content in a board item and created paragraphs. I then clicked on another element on the card (i.e. changed focus).

## Observed behavior

Depending on the focus point the text renders differently. When focused (i.e. click to edit) on the content it renders correctly. When I move focus (click elsewhere on the card) the text does not render as expected (i.e. looses the paragraph spacing).

Copying content out to a local text editor (plain text) shows the content saves correctly.

**Comment by kamre** [comment]
Looks very similar to this one:
- #878

**Comment by nab-77** [comment]
I agree that this indeed is very similar, so similar I would call this a dupe. Can be closed.

**Comment by sbishel** [comment]
closed as dup of 
https://github.com/mattermost/focalboard/issues/878
