### ISSUE TITLE
make command fails on Windows

### ISSUE THREAD

**Issue by hantatsang** [mattermost/focalboard#179]
**Summary:**

I'm trying to build the app to run locally following the instructions in `README.md` but `make` task fails due to `win-node-env`. `make webapp` yields the same error.

**Steps to reproduce the behavior:**

1. Run `npm i -g win-node-env`
1. Run `make prebuild`
2. Run `make`
3. This error dialog comes up:
  
  ![2021-03-24 16_33_50-package json - focalboard - Visual Studio Code](https://user-images.githubusercontent.com/11912225/112261058-2f970280-8cbf-11eb-8591-ff949ff8a2d6.png)

**Expected behavior:**

`make` or `make webapp` should succeed.

**Screenshots:**

**Platform:**
 - Browser and version: N/A
 - OS and version: Windows 10
 - Node version: 14.14.0
 - `npm` version: 6.14.8
 - `win-node-env`: 0.4.0

**Additional context:**

Full Node debug log:

```log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'pack'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.14.0
4 verbose run-script [ 'prepack', 'pack', 'postpack' ]
5 info lifecycle focalboard@0.6.1~prepack: focalboard@0.6.1
6 info lifecycle focalboard@0.6.1~pack: focalboard@0.6.1
7 verbose lifecycle focalboard@0.6.1~pack: unsafe-perm in lifecycle true
8 verbose lifecycle focalboard@0.6.1~pack: PATH: ~hidden~
9 verbose lifecycle focalboard@0.6.1~pack: CWD: C:\mattermost\focalboard\webapp
10 silly lifecycle focalboard@0.6.1~pack: Args: [ '/d /s /c', 'NODE_ENV=production webpack --config webpack.js' ]
11 silly lifecycle focalboard@0.6.1~pack: Returned: code: 1  signal: null
12 info lifecycle focalboard@0.6.1~pack: Failed to exec pack script
13 verbose stack Error: focalboard@0.6.1 pack: `NODE_ENV=production webpack --config webpack.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\ProgramData\nvm\v14.14.0\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\ProgramData\nvm\v14.14.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid focalboard@0.6.1
15 verbose cwd C:\mattermost\focalboard\webapp
16 verbose Windows_NT 10.0.19043
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "pack"
18 verbose node v14.14.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error focalboard@0.6.1 pack: `NODE_ENV=production webpack --config webpack.js`
22 error Exit status 1
23 error Failed at the focalboard@0.6.1 pack script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by chenilim** [comment]
Hmmm... it seems that webpack is calling Windows Script Host in that environment ([SO article](https://stackoverflow.com/questions/59605666/windows-script-host-error-800a03ea-on-express-js-code)). Are you running in git bash?

There are some more details in the [dev tips & tricks page](https://www.focalboard.com/contribute/getting-started/dev-tips/) on the setup on Windows.

**Comment by jespino** [comment]
@hantatsang I upgraded all our javascript dependencies, can you try again, I don't know if that is going to solve the problem.

**Comment by hantatsang** [comment]
Thanks, but I'm still having the same issue. I might have to try this on a Linux machine instead.

**Comment by chenilim** [comment]
Just going through old issues. Are you (or anyone else) still running into this @hantatsang? If not, I'll close it for now, but please reopen or file a new issue if anyone can't build on Windows.

**Comment by hantatsang** [comment]
@chenilim I ended up running focalboard in WSL instead. Make doesn't play well for Windows for me.

**Comment by chenilim** [comment]
Found [this SO article](https://stackoverflow.com/questions/37192508/trying-to-execute-a-script-from-package-json-on-windows-throws-a-jscript-error/54869847#54869847), which might be the solution to the original error, in case anyone else sees this.

> Removing .js from PATHEXT helps.
