### ISSUE TITLE
Bug: Card description doesn't get saved

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1792]
## Steps to reproduce the behavior

1. Go to Boards
2. Open a card
3. Click on "Add a description"
4. Enter some text and exit
5. Reopen the card - note the text wasn't saved

## Expected behavior

Text entered in the card description field should be saved

## Screenshots

https://user-images.githubusercontent.com/15314183/141010237-25fb4a7f-40f2-4919-8645-cfc5df996185.mp4

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: main
 - Browser and OS: Chrome 94 on Windows

**Comment by haroldm** [comment]
This bug also happens on latest docker build. It seems to be the same bug as #1767, likely caused by #1667.
Previous description can still be altered and saved.

**Comment by ogi-m** [comment]
Tested and passed on latest main
