### ISSUE TITLE
Bug: added content in card don't appear

### ISSUE THREAD

**Issue by Ghisura** [mattermost/focalboard#1798]
## Steps to reproduce the behavior

1. Go to into a card
2. Select  add content
3. Select anything 
4. nothing appear

## Expected behavior

see what you select / add

## Screenshots

If applicable, add screenshots to elaborate on the problem.

## Edition and Platform

 - Edition: Personal Server (official docker image)
 - Version: v0.10.0
 - Browser and OS: Chrome, firefox, safari on macOS

## Additional context

In fact what I understand, is when you select a content, it don't appear, but it is really created in the database (I use Postgres 13)
- The parent_id is correct
- An id is assigned to the newly entry
- The id which is added in the list of the propriety `contentOrder` (of the parent) don't correspond with the id assigned of the newly entry
- if you modify / add in contentOrder the good id and save it and if you refresh the card, the content is displayed as expected

Edit: Same thing for Card Description (seem to be the same problem)

**Comment by hahmadia** [comment]
Hi! Thanks for report. Several reports regarding this issue have come in. 
Jesus has PR to fix https://github.com/mattermost/focalboard/pull/1799

**Comment by jespino** [comment]
@Ghisura can you confirm if you are using the docker version 0.10 or the `latest`. I think the `latest` is build on `main` branch, so it wouldn't be `0.10` it would be `main`.

**Comment by Ghisura** [comment]
Hello,
@hahmadia , sorry haven't seen the PR
@jespino, sorry v0.10.0 is the version noted on the frontend.
I did not specify tag in docker compose, so is latest

**Comment by ogi-m** [comment]
Tested and passed on latest main.
