### ISSUE TITLE
Bug: Date calculation options multiplied by number of date properties

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1801]
## Steps to reproduce the behavior

1. Go to a board
2. Create three date properties on a card - Date, Last updated time, Created time
3. Open the calculations dropdown
4. Notice there are three sets of date related calculations (Earliest Date, Latest Date, Date Range)

## Expected behavior

The date calculations options shouldn't repeat

## Screenshots

![Screenshot (42)](https://user-images.githubusercontent.com/15314183/141318246-614b46c3-fa67-41fd-8bd0-61eaecba9fdb.png)

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.10

**Comment by chenilim** [comment]
Is this a dup of https://github.com/mattermost/focalboard/issues/1696? Or a subset? At this point in the cycle, I propose fixing this for v0.11. Thoughts @sbishel, @asaadmahmood, @wuwinson?

**Comment by ogi-m** [comment]
@chenilim It appears to be a subset as it only affects the date properties.

**Comment by sbishel** [comment]
Agree, can wait for v0.11.

**Comment by chenilim** [comment]
Thanks! Assigning to you @harshilsharma63 for v0.11.

**Comment by harshilsharma63** [comment]
@ogi-m can you please test this on the latest `main`? It's working fine for me.

<img width="437" alt="Screenshot 2021-11-15 at 1 35 48 PM" src="https://user-images.githubusercontent.com/18575143/141744580-f7922671-4577-4523-978d-ad9d44ad9d52.png">
