### ISSUE TITLE
Feature Idea: Replace unfurl link with card title

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1805]
## Summary

Currently, when pasting a card link in a message, the full URL remains, e.g.:

<img width="467" alt="Screen Shot 2021-11-11 at 2 13 44 PM" src="https://user-images.githubusercontent.com/46905241/141376537-594287df-f1fc-455a-90bc-4f733cd551d1.png">

Instead, the link should be replaced with the card title, as a link.

## How important this is to me and why

Importance: Medium

Use cases:
1. This will clean up the message display
2. Similar to links to channels and GitHub / Jira tickets

**Comment by chenilim** [comment]
@hahmadia, I don't remember where this landed after discussing, but can we do it for v0.11? cc @asaadmahmood, @wuwinson, @ogi-m.

**Comment by hahmadia** [comment]
@chenilim 

We can but my only concern is what if the card title contains private or sensitive information? Although the preview won't show to everyone, the title will and it could possibly leak information.

If we are certain that's okay, I can give it a go for 0.11 but this is the first concern that comes to mind.

**Comment by hahmadia** [comment]
As I mentioned in the DM, I would be in favour of doing it the same way github or mattermost where it shortens it something generic but not the title of the card so that way it's neat and tidy while not exposing any information.

**Comment by chenilim** [comment]
Good point. Maybe something like [Link to card](http://www.mattermost.com). That would have to be localized though. Let's see if other's have a better idea.

**Comment by asaadmahmood** [comment]
@hahmadia @chenilim I think I agree with Hossein, so yeah something generic like "Link to Card" or "Card Link" or "Go to Card" would be fine.

**Comment by wuwinson** [comment]
@asaadmahmood @hahmadia @chenilim The unfurled preview already displays the card title, perhaps we can go with a simple shortened URL so we avoid having to localize the URL text?

**Comment by asaadmahmood** [comment]
@wuwinson Don't mind that.

**Comment by chenilim** [comment]
Thanks! Sounds like we are converging on "Link to card". This would have to be localized.

**Comment by wuwinson** [comment]
@chenilim @asaadmahmood I was thinking something more like: "mattermost.com/shortenedURL", so we don't have to localize, but okay with the generic text you proposed as well.

**Comment by wiggin77** [comment]
I think we should define several card link formats.  For example, mentions and notifications need the card title to provide context, but they are going to private channels so no data leak.  However other card links should have generic text.

**Comment by chenilim** [comment]
@hahmadia, synched up with Scott and Winson. Let's go with `<jump to card>` to be consistent with thread links (won't be localized). Per Doug's note - we should only make this substitution when pasting raw links in channels. i.e. leave the notification code alone for now.

**Comment by hahmadia** [comment]
Hi @ogi-m ,

I've merged this into master. Feel free to test. Thanks
