### ISSUE TITLE
Bug: @mentions don’t trigger when you update content section with new at mentions

### ISSUE THREAD

**Issue by hahmadia** [mattermost/focalboard#1806]
## Steps to reproduce the behavior

Create a new card and mention users in the channel. Save and notice those users get the at mention notification. Go back and update content with new user at mention. New users don't receive notifications. Any at mention done on updated content does not work.

## Expected behavior

New users should receive at mentions

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: Master

**Comment by hahmadia** [comment]
//cc @chenilim Is this a bug or enhancement?

**Comment by chenilim** [comment]
My opinion is this is a bug (not that it matters, I think we should fix this either way). Newly mentioned users should be notified. cc @wiggin77 - is this expected?

**Comment by chenilim** [comment]
Also cc @ogi-m.

**Comment by wiggin77** [comment]
> My opinion is this is a bug (not that it matters, I think we should fix this either way). Newly mentioned users should be notified. cc @wiggin77 - is this expected?

As I recall, when a text block is updated a list of mentions in the old block is compared to a list from the new block, and any new mentions should be notified.  So yes, I expect it to work.  I'll have a look.

**Comment by hahmadia** [comment]
@wiggin77 Sorry, I may have been wrong about this.

I noticed the problem I reported happens if say content is currently set to `Hi @hahmadia` and I go in and delete all the text and set it to `hello @hahmadia`. This won't trigger new notifications.

If I go in and delete the text, go out of focus on the textbox (now content is set to empty), i click back into it and set it to `hello @hahmadia` then I get a new notification warning. 

It does work but only if the user is not mentioned in the previous text you deleted. I just wanted to clarify as I noticed that today.  I'm not sure if that would be classified as a bug but I wanted to clarify. If you feel it's working as intended, feel free to close this issue.

**Comment by wiggin77** [comment]
> if say content is currently set to Hi @hahmadia and I go in and delete all the text and set it to hello @hahmadia. This won't trigger new notifications.

This is as intended. No new mentioned were added.

> If I go in and delete the text, go out of focus on the textbox (now content is set to empty), i click back into it and set it to hello @hahmadia then I get a new notification warning.

Technically these are two separate edits, and the second edit adds a new mention.  I think this is the right behaviour.  Thanks @hahmadia. Please close if you agree.

**Comment by hahmadia** [comment]
Agreed
