### ISSUE TITLE
Write Focalboard E2E with Cypress: "MM-T4275 Set up Board description"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/focalboard#1813]
<article>
<h1>MM-T4275 Set up Board description</h1>
<div>
<div>
<hr><h3>Steps  #1</h3><a href="https://automation-test-cases.vercel.app/test/MM-T4274">Create an empty board</a><h3><h3>Steps  #2</h3>Hover your mouse above the board title, Testing<h3>Expected</h3>"Add icon" and "Show description" options appear<hr><h3>Steps  #3</h3>Click on "Show Description"<h3>Expected</h3>"Show description" options changes to "Hide description" and "Add a description" is shown below the board title<hr><h3>Steps  #4</h3>Click on "Add a description" below the board title and type "for testing purposes only" then hit Enter<h3>Expected</h3>Description is added below the board title<hr><h3>Steps  #5</h3>Hover your mouse above the board title, Testing<h3>Expected</h3>"Hide description" options appear<hr><h3>Steps  #6</h3>Click on "Hide description"<h3>Expected</h3>The description below the board title is now hidden<hr><h3>Steps  #7</h3>Hover your mouse above the board title, Testing<h3>Expected</h3>"Show description" options appear<hr><h3>Steps  #8</h3>Click on "show description"<h3>Expected</h3>Description is added below the board title with the previously saved text: "for testing purposes only"<hr>
</div>
</div>
</article>

**Test code arrangement:**
```
it('MM-T4275 Set up Board description', () => {
    // code
});
```

Note:
1. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Focalboard" community channel](https://community.mattermost.com/core/channels/focalboard).

For new contributors, please see our [guide](https://github.com/mattermost/focalboard#running-and-testing-the-server).

**Comment by saturninoabril** [comment]
Closing this now. Will submit new once at https://github.com/mattermost/mattermost-server/issues.

**Comment by adj2908** [comment]
@saturninoabril  I have created a PR for this issue in the mattermost server repo. Thanks.

**Comment by saturninoabril** [comment]
Thank you @adj2908 for your contribution!
