### ISSUE TITLE
Write Focalboard E2E with Cypress: "MM-T4276 Set up Board emoji"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/focalboard#1814]
<article>
<h1>MM-T4276 Set up Board emoji</h1>
<div>
<div>
<hr><h3>Steps  #1</h3><a href="https://automation-test-cases.vercel.app/test/MM-T4274">Create an empty board</a><h3><h3>Steps  #2</h3>Hover your mouse above the board title, Testing<h3>Expected</h3>"Add icon" and "Show description" options appear<hr><h3>Steps  #3</h3>Click on "Add icon"<h3>Expected</h3>A random emoji is selected and added at the beginning of the board title<hr><h3>Steps  #4</h3>Click on the emoji next to the board title<h3>Expected</h3>Dropdown menu with 3 options appears:<br />- Random<br />- Pick Icon<br />- Remove Icon<hr><h3>Steps  #5</h3>Hover your mouse over the "Pick Icon" option<h3>Expected</h3>Emoji picker opens to the right<hr><h3>Steps  #6</h3>Select an emoji from the picker<h3>Expected</h3>Selected emoji is now displayed next to the board title<hr><h3>Steps  #7</h3>Click on the emoji next to the board title<h3>Expected</h3>Dropdown menu with 3 options appears:<br />- Random<br />- Pick Icon<br />- Remove Icon<hr><h3>Steps  #8</h3>Click "Remove icon"<h3>Expected</h3>Icon next to the board title is removed<hr>
</div>
</div>
</article>

**Test code arrangement:**
```
it('MM-T4276 Set up Board emoji', () => {
    // code
});
```

Note:
1. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Focalboard" community channel](https://community.mattermost.com/core/channels/focalboard).

For new contributors, please see our [guide](https://github.com/mattermost/focalboard#running-and-testing-the-server).

**Comment by saturninoabril** [comment]
Closing this now. Will submit new once at https://github.com/mattermost/mattermost-server/issues.

**Comment by adj2908** [comment]
@saturninoabril Can I also work on this issue? Is possible please assign me this issue. Thanks.

**Comment by adj2908** [comment]
@saturninoabril you may close this issue since the PR has been merged. Thanks.

**Comment by saturninoabril** [comment]
Thanks @adj2908 for your contribution!
