### ISSUE TITLE
Write Focalboard E2E with Cypress: "MM-T4274 Create an Empty Board"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/focalboard#1815]
<article>
<h1>MM-T4274 Create an Empty Board</h1>
<div>
<div>
<h3>Steps  #1</h3>Click on the "+" icon at the top of the sidebar<h3>Expected</h3>"Create a Board" screen opens in the center view with template options<hr><h3>Steps  #2</h3>Click on "Start with an Empty Board"<h3>Expected</h3>Board titled "Untitled Board" is created and opened<hr><h3>Steps  #3</h3>Click on "Untitled Board" and type "Testing" and hit Enter<h3>Expected</h3>Title of the board updates to "Testing"<hr>
</div>
</div>
</article>

**Test code arrangement:**
```
it('MM-T4274 Create an Empty Board', () => {
    // code
});
```

Note:
1. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Focalboard" community channel](https://community.mattermost.com/core/channels/focalboard).

For new contributors, please see our [guide](https://github.com/mattermost/focalboard#running-and-testing-the-server).

**Comment by nishantwrp** [comment]
Hi, I'd like to work on this issue.

**Comment by saturninoabril** [comment]
Sure and thanks @nishantwrp!

**Comment by nishantwrp** [comment]
Hi @saturninoabril, I think the test instructions written in the issue description are written w.r.t. the plugin not standalone server. Can you let me know on how to write e2e tests for focalboard as a plugin. (Don't we need mattermost running for that? 🤔)

**Comment by saturninoabril** [comment]
That's true. However, could you please align the test for standalone server? For plugin test, we're likely to add it in the mattermost-webapp repo where all product suite will be tested.
