### ISSUE TITLE
Write Focalboard E2E with Cypress: "MM-T4290 Duplicating and deleting a board"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/focalboard#1817]
<article>
<h1>MM-T4290 Duplicating and deleting a board</h1>
<div>
<div>
<hr><h3>Steps  #1</h3><a href="https://automation-test-cases.vercel.app/test/MM-T4274">Create an empty board</a><h3><h3>Steps  #2</h3>Click on the "..." menu next to the "Testing" board in the sidebar<h3>Expected</h3>Dropdown menu with three options opens:<ul><li>Delete board</li><li>Duplicate board</li><li>New template from board</li></ul><hr><h3>Steps  #3</h3>Click on "Duplicate board"<h3>Expected</h3>Board title "Testing copy" is created and opened<hr><h3>Steps  #4</h3>Click on the "..." menu next "Testing copy" in the sidebar and click "Delete Board"<h3>Expected</h3>"Testing copy" board is returned and user is returned to the first board on the top<hr>
</div>
</div>
</article>

**Test code arrangement:**
```
it('MM-T4290 Duplicating and deleting a board', () => {
    // code
});
```

Note:
1. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Focalboard" community channel](https://community.mattermost.com/core/channels/focalboard).

For new contributors, please see our [guide](https://github.com/mattermost/focalboard#running-and-testing-the-server).

**Comment by adj2908** [comment]
@saturninoabril I would like to contribute to this issue. Please assign me this issue. Thanks.

**Comment by saturninoabril** [comment]
Sure and thanks @adj2908!

**Comment by adj2908** [comment]
@saturninoabril Looks like few things have changed in the UI after I pulled the latest changes. Actually the ticket says that "..." Dropdown menu should have three options:
- Delete board
- Duplicate board
- New template from board
But I am not able to see these options. Can you please help me with some reference? Attached is the screenshot for your reference. Thanks.

![Screenshot 2023-03-15 at 9 57 15 PM](https://user-images.githubusercontent.com/18600164/225376510-a44a3970-405e-4ee7-a2e4-7530aa5b255e.png)

**Comment by saturninoabril** [comment]
Should be in the screenshot. Unfortunately, this particular ticket was taken by one of our staff - https://github.com/mattermost/mattermost-webapp/pull/12321. With that, I'm closing this now. Sorry about that.

<img width="1370" alt="Screenshot 2023-03-16 at 3 28 15 PM" src="https://user-images.githubusercontent.com/5334504/225545052-a3fc72ed-4597-455c-9cd9-d27f104d6f15.png">

**Comment by saturninoabril** [comment]
Btw, I'll be closing all help-wanted issues here about adding test automation but will submit new ones at https://github.com/mattermost/mattermost-server/issues with new guidelines with Playwright.
