### ISSUE TITLE
Write Focalboard E2E with Cypress: "MM-T4283 Dashboard Search"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/focalboard#1819]
<article>
<h1>MM-T4283 Dashboard Search</h1>
<div>
<div>
<hr><h3>Steps  #1</h3><a href="https://automation-test-cases.vercel.app/test/MM-T4281">Access the dashboard</a><h3><h3>Steps  #2</h3>In the search field, type "Channel"<h3>Expected</h3>"Channel 1" and "Channel 2" are returned in the results (matching titles)<hr><h3>Steps  #3</h3>In the search field, type "2"<h3>Expected</h3>"Channel 2" is returned for the matching title<br />"Channel 1"is returned for the matching board count<hr>
</div>
</div>
</article>

**Test code arrangement:**
```
it('MM-T4283 Dashboard Search', () => {
    // code
});
```

Note:
1. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Focalboard" community channel](https://community.mattermost.com/core/channels/focalboard).

For new contributors, please see our [guide](https://github.com/mattermost/focalboard#running-and-testing-the-server).

**Comment by tejaswini22199** [comment]
Hi @saturninoabril  can you pls assign this issue to me ?

**Comment by saturninoabril** [comment]
Sure and thanks @tejaswini22199!

**Comment by adj2908** [comment]
@saturninoabril. Looks like @tejaswini22199 is not working on this issue. Can you please assign me this issue? Thanks.

**Comment by saturninoabril** [comment]
Sure and thanks @adj2908!

**Comment by saturninoabril** [comment]
I'm closing this now. Will submit new help-wanted issue at https://github.com/mattermost/mattermost-server/issues in the near future.
