### ISSUE TITLE
Write Focalboard E2E with Cypress: "MM-T4287 Hiding/unhiding a group"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/focalboard#1822]
<article>
<h1>MM-T4287 Hiding/unhiding a group</h1>
<div>
<div>
<hr><h3>Steps  #1</h3>Create an empty board and <a href="https://automation-test-cases.vercel.app/test/MM-T4284">add a group</a><h3><h3>Steps  #2</h3>Click on the three dots next to "Group 1"<h3>Expected</h3>Dropdown opens with Hide, Delete and color options <hr><h3>Steps  #3</h3>Click on "Hide" <h3>Expected</h3>"Group 1" is now shown under "Hiden columns" with the card count (3) next to it and the cards hidden<hr><h3>Steps  #4</h3>Click "Group 1", then click "Show" in the dropdown <h3>Expected</h3>Group 1 is restored with all the cards listed below it<hr>
</div>
</div>
</article>

**Test code arrangement:**
```
it('MM-T4287 Hiding/unhiding a group', () => {
    // code
});
```

Note:
1. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Focalboard" community channel](https://community.mattermost.com/core/channels/focalboard).

For new contributors, please see our [guide](https://github.com/mattermost/focalboard#running-and-testing-the-server).

**Comment by djanda97** [comment]
Hi @saturninoabril!
I would like to work on this issue.
This is my first time contributing to Focalboard, so I'll start working on this once I get my local environment setup.

**Comment by saturninoabril** [comment]
@djanda97 Great and thanks!
