### ISSUE TITLE
Write Focalboard E2E with Cypress: "MM-T4286 Card creation and count"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/focalboard#1824]
<article>
<h1>MM-T4286 Card creation and count</h1>
<div>
<div>
<hr><h3>Steps  #1</h3>Create an empty board and <a href="https://automation-test-cases.vercel.app/test/MM-T4284">add a group</a><h3><h3>Steps  #2</h3>Click on "+ New" in "Group 1" column <h3>Expected</h3>A new card titled "Untitled" "is added to the group<hr><h3>Steps  #3</h3>Hover your mouse over the new card and click on the "..." menu<h3>Expected</h3>Dropdown menu opens with "Delete", "Duplicate" and "Copy Link" options<br /><br /><hr><h3>Steps  #4</h3>Click "Duplicate"<h3>Expected</h3>Another card titled "copy" is added to the group<hr><h3>Steps  #5</h3>Observe the card count next to the group name<h3>Expected</h3>Card count shows the expected value - "2"<hr><h3>Steps  #6</h3>Click on the "..." menu on one of the cards and click "Delete"<h3>Expected</h3><ul><li>Card is removed from the group</li><li>Card count is updated to "1"</li></ul><hr>
</div>
</div>
</article>

**Test code arrangement:**
```
it('MM-T4286 Card creation and count', () => {
    // code
});
```

Note:
1. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Focalboard" community channel](https://community.mattermost.com/core/channels/focalboard).

For new contributors, please see our [guide](https://github.com/mattermost/focalboard#running-and-testing-the-server).

**Comment by djanda97** [comment]
Hi @saturninoabril! I would like to work on this issue :smile:

**Comment by saturninoabril** [comment]
Sure and thanks @djanda97!

**Comment by saturninoabril** [comment]
I'm closing this now. Will submit new help-wanted issue at https://github.com/mattermost/mattermost-server/issues in the near future.
