### ISSUE TITLE
Task Card Overflow

### ISSUE THREAD

**Issue by kevr** [mattermost/focalboard#184]
**Summary:**
A task card with too much width in its title causes a visual overflow.

**Steps to reproduce the behavior:**
1. Create a card.
2. Set your window width to something kind of small
3. View your task cards

**Expected behavior:**
Wrapped text.

**Screenshots:**
![overflow](https://user-images.githubusercontent.com/1672189/112339960-5a606700-8c7d-11eb-92bb-9a0fd1f4ada2.png)

**Platform:**
- OS: Ubuntu 20.10
- Browser: Firefox 86.0

**Comment by chenilim** [comment]
Thanks for filing this @kevr! @asaadmahmood, do you think this is a simple css fix?

**Comment by asaadmahmood** [comment]
@chenilim Yup, pretty simple.

**Comment by BharatKalluri** [comment]
Can I take this up?

Is the idea to hide the text overflow? 

![Screenshot 2021-03-26 at 12 12 27 PM](https://user-images.githubusercontent.com/8049414/112592783-89690b00-8e2c-11eb-9ef0-c8f2a8393a43.png)

**Comment by asaadmahmood** [comment]
We can probably have them span multiple lines right @chenilim ?

**Comment by BharatKalluri** [comment]
We can do this too, this is how it would look like. 

<img width="575" alt="Screenshot 2021-03-26 at 1 11 36 PM" src="https://user-images.githubusercontent.com/8049414/112598585-cf29d180-8e34-11eb-8082-d7a251cbc2e6.png">

**Comment by asaadmahmood** [comment]
I'd be fine with that, I think that provides additional value compared to truncating.
