### ISSUE TITLE
Bug: New properties don't get added to table view by default

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1841]
## Steps to reproduce the behavior

1. Open Focalboard Personal Desktop (doesn't repro on plugin)
2. Create an empty board
3. Add table view
4. Add a card in table view
5. Add a text property
6. Close the card - note the new property isn't displayed in table view, it needs to be toggled manually in the Properties dropdown.

## Expected behavior

The new text property should be shown by default in table view

## Screenshots

If applicable, add screenshots to elaborate on the problem.

## Edition and Platform

 - Edition: Personal Desktop
 - Version: main
 - Browser and OS: Windows

**Comment by lindy65** [comment]
Adding that this is an intermittent issue.  At times, new properties are added to table view automatically and, at others, you need to toggle the property to "on" under Properties menu.

**Comment by chenilim** [comment]
Discussed with Scott and Winson - we actually expected the property not be be auto-added to the table. i.e. the user has to manually add it in the properties menu.

**Comment by lindy65** [comment]
I'll keep an eye on final decision as Rainforest tests will need to be refactored if property is not auto-added to the table (as previously properties were auto-added)

**Comment by sbishel** [comment]
This is being caused by the transaction processing when using a sqlite database. 

The functionality to auto add to the table has existed since the beginning, so we should probably think about whether we want to change the functionality.

**Comment by lindy65** [comment]
Thanks Scott,

> The functionality to auto add to the table has existed since the beginning

I'm seeing _intermittent_ failure in Rainforest tests where property is _not_ auto added to the table so Ogi filed this issue.  For now, I've disabled the affected tests from running until a decision is made on whether to change the functionality or not.

**Comment by chenilim** [comment]
I was able to repro this issue on both:
* v0.11 RC2 Personal Desktop Mac with a new DB
* Private build off release-0.11.

macOS 11.16.1 and SQLite 3.32.3.
