### ISSUE TITLE
Bug:  auto refresh of changes fails on board 0.10.0 beta on enterprise 6.1.0

### ISSUE THREAD

**Issue by nimzodisaster** [mattermost/focalboard#1844]
## Steps to reproduce the behavior

1. Go to board
2. Create, edit,or delete a board item
3. See error: Does not update reflecting changes until refresh.

## Expected behavior

Refresh content to be consistent with current state

## Edition and Platform

 - Edition: Board Version: [0.10.0] in Mattermost Enterprise Edition 6.1.0
 - In Mattermost client (5.1) 
 - 
## Additional context

I've tried uninstall then reinstalling the board plugin, but this does not fix the issue.

**Comment by damien-d-gerard** [comment]
Same problem for me.

Need to refresh content to see modification.

**Comment by DummyThatMatters** [comment]
Same behavior for me. With all the versions of Boards (0.9.3 - 0.1.0). Interesting thing - on another instance of Mattermost (same versions: Board: 0.10.0, Mattermost 6.1.0) - it works fine.

**Comment by init098** [comment]
Same problem for us, Mattermost 6.1.0 and Focarlboard v0.10.0 Beta. As additional information, when deactivating and activating the plugin again, it works fine for a few minutes and then crashes again.

**Comment by nimzodisaster** [comment]
I'd love to share the new boards features with some work colleagues, but this bug makes it a no go.

**Comment by badsmoke** [comment]
same error here, server 6.1.0.
For a while it ran, then sporadically, and now not at all, plugin reinstall brings nothing

**Comment by jespino** [comment]
@nimzodisaster can you confirm if you have `EnableReliableWebSockets: true` in your `config.json` of `mattermost-server`? If that is false, can you try to change it to true, restart the server, and see if that fixes the problem?

**Comment by nimzodisaster** [comment]
Changed EnableReliableWebSockets: false to true, and restarted server. **Problem is resolved.**

**Comment by badsmoke** [comment]
works also for us

**Comment by init098** [comment]
> Same problem for us, Mattermost 6.1.0 and Focarlboard v0.10.0 Beta. As additional information, when deactivating and activating the plugin again, it works fine for a few minutes and then crashes again.

EnableReliableWebSockets: true **solved the problem**

**Comment by tareko** [comment]
This fix helped me too. In my case using helm and the official board, this was:

```
  extraEnv:
  - name: MM_ENABLERELIABLEWEBSOCKETS
    value: "true"
```
