### ISSUE TITLE
Property type: User

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#185]
**Summary:**
Pick a user to assign to a property (e.g. "Assigned to").

**How important this is to me and why:**
Importance: High

Use cases:
1. Assign a card to a user
2. Set the reviewer of a card

The current workaround is to use a Select property with the names of users as options. By typing the property to a user (by userID) instead, we can do user-specific filtering, such as "Show tasks assigned to me".

P1: Set a single user, picked from a dropdown
P2: Set multiple users (Related to multiple properties, #110)

**Comment by alerque** [comment]
This issue appears to be implemented already. In my testing on Mattermost there is a 'Person' type now that is typed and restricted to the list of people with access to the board.

Notably missing as far as my own potential use case(s) is there is no multi-person property type, see #2413.

**Comment by chenilim** [comment]
Thanks @alerque! I'll close this (old) issue, as the user property has since been implemented, and https://github.com/mattermost/focalboard/issues/2413 tracks the multi-user property. Please feel free to add any additional use-cases or requests to that or new feature ideas.
