### ISSUE TITLE
Packaged Windows binaries requires WebView2 installation which org blocks

### ISSUE THREAD

**Issue by jakauppila** [mattermost/focalboard#187]
**Summary:**
With signed binaries now being distributed after #99 was closed, I attempted to run it, but encountered that the WebView2 runtime needs to be downloaded and installed, which my org blocks via Group Policy.

**Steps to reproduce the behavior:**
1. Download Windows binaries
2. Run `Focalboard.exe`
3. Click Yes for WebView2 runtime installation

![image](https://user-images.githubusercontent.com/4100127/112370986-0e78e680-8cac-11eb-87b2-30069b0046de.png)

4. Microsoft Edge Update prompt appears
5. Group Policy is preventing installation

![image](https://user-images.githubusercontent.com/4100127/112371062-2e100f00-8cac-11eb-9d82-478d0aded082.png)

**Expected behavior:**
Focalboard to execute

**Platform:**
 - Browser and version: [e.g. Chrome 88, Safari 12]
 - OS and version: Windows 10 1909

**Comment by chenilim** [comment]
Are you able to install the [webview2 runtime](https://developer.microsoft.com/en-us/microsoft-edge/webview2/) directly from Microsoft? Focalboard has a dependency on this for Windows. The expectation is this will eventually be a part of Windows, but the separate install is required for now.

**Comment by jakauppila** [comment]
Nope, I end up at the same prompt.

Is [Fixed Version Distribution Mode](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#fixed-version-distribution-mode) an option? It appears that simply ships the dependencies rather than requiring a separate install?

**Comment by chenilim** [comment]
Thanks for checking @jakauppila. I did some more digging and apparently if you can install a [canary build of Edge](https://www.microsoftedgeinsider.com/en-us/download), it also serves as a webview2 component. Though my guess is you might run into the same group policy restriction.

Would it be possible for your IT to allow this in their policy? Found these [MS docs](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/enterprise). Webview2 has been around for a while now, and more and more apps will have this dependency.

I don't anticipate we will ship the fixed install (avoiding the bloat and dependency management was the main reason we tried this packaging), but it might be possible to add a config setting to [specify the path to the fixed version folder](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#fixed-version-distribution-mode) after installing it manually. Maybe someone wants to take a crack at this?

**Comment by chenilim** [comment]
Oh, looks like Microsoft is already [silently rolling out webview2](https://www.bleepingcomputer.com/news/microsoft/microsoft-is-auto-installing-the-windows-10-webview2-runtime/)! So this problem might just go away in a few weeks.
