### ISSUE TITLE
Bug: Calendar View > '+n more" modal should have a solid background

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1871]
## Steps to reproduce the behavior

1. Go to Calendar View
2. Add enough cards to a date so that the "+n more" button appears
3. Click on "+n more"
4. Note the transparent background on the modal

## Expected behavior

The background should be solid

## Screenshots

![nmore](https://user-images.githubusercontent.com/15314183/143429799-c1e2e2f3-9126-4a4d-b5a8-922a53cc479a.jpg)

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.11
 - Browser and OS: Windows, Chrome

**Comment by ogi-m** [comment]
cc @sbishel @asaadmahmood

**Comment by ogi-m** [comment]
This was on the build from the PR that removes the feature flag. I'll when everything's merged to main.

**Comment by sbishel** [comment]
This was already fixed here - 

https://github.com/mattermost/focalboard/pull/1874/commits/ba59e57745201020e27633e708d8f1bf861debf
![Screen Shot 2021-11-30 at 10 39 51 AM](https://user-images.githubusercontent.com/12704875/144099259-ecdb9f60-22f4-4951-a668-8e825567fcc8.png)
6

**Comment by sbishel** [comment]
@ogi-m Closing...please reopen if you see this again.

**Comment by ogi-m** [comment]
This is now happening on main again

**Comment by sbishel** [comment]
Actually only occurs when the popup is on the current date ie. `today`.
