### ISSUE TITLE
Bug: Icons are black and white

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1872]
## Steps to reproduce the behavior

1. Open Personal Desktop or plugin on Windows/Chrome
2. Observe the icons - they appear in black and white (everywhere except card view and table view)

## Expected behavior

Icons should look normal

## Screenshots

![windows_desktop](https://user-images.githubusercontent.com/15314183/143431101-1d3b9017-ad4c-47ac-ab8a-739cf67354d4.jpg)

## Edition and Platform

 - Edition: Personal Desktop, plugin
 - Version: v0.11
 - Browser and OS: Windows 10, Chrome

**Comment by jespino** [comment]
@ogi-m sorry, it is not happening on the linux app and I don't have windows :( Anybody with windows in the team? maybe @sbishel @harshilsharma63 @wiggin77 or @hahmadia

**Comment by wiggin77** [comment]
Sorry - no Windows.

**Comment by kamre** [comment]
Hi! Looks like there is a duplicate #1697 with some analysis inside about the `font-weight` changes.

**Comment by kamre** [comment]
Regression was introduced in this pull request:
* #908

@asaadmahmood FYI

**Comment by ogi-m** [comment]
This reproes in plugin mode as well now, updated the title and description to reflect that.

**Comment by wiggin77** [comment]
I cannot test this as FocalBoard requires Windows 10 and I only have an older version.
