### ISSUE TITLE
Bug: at-mention autocomplete shows up in the top left after dismissing it and engaging it again

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1877]
## Steps to reproduce the behavior

1. Go to Boards
2. Open a card
3. In the comment box, type "@"
4. Note the autocomplete shows up
5. Click outside of the comment box
6. Click inside the comment box again - note the dropdown shows up in the top left of the screen

## Expected behavior

Autocomplete dropdown should show up below the input field

## Screenshots

![Screenshot (54)](https://user-images.githubusercontent.com/15314183/143491911-5c2dbfc3-9006-40e6-bdcd-315aa546649d.png)

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.11
 - Browser and OS: Chrome & Firefox

**Comment by hahmadia** [comment]
Asaad has volunteered to help me with this problem.

**Comment by ogi-m** [comment]
Tested and passed on v0.11
