### ISSUE TITLE
Font not readable in dark theme

### ISSUE THREAD

**Issue by femto-code** [mattermost/focalboard#188]
In template editor the alert is not readable because of font contrast.

![image](https://user-images.githubusercontent.com/59444046/112372866-9e388800-8ce0-11eb-8a25-84717cd37916.png)

**Comment by chenilim** [comment]
Thanks for reporting this @femto-code! @asaadmahmood, is this something you can help with? We might also consider doing a more general review of the dark theme.

**Comment by asaadmahmood** [comment]
Yup, I can have a look at it @chenilim
