### ISSUE TITLE
Bug: at-mention autocomplete doesn't use theme colors

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1880]
## Steps to reproduce the behavior

1. Set a dark theme
2. Go to boards
3. Open a card and type "@" in the comment field
4. Note the colors are off

## Expected behavior

The autocomplete should match the colors for the selected theme

## Screenshots

![Screenshot (97)](https://user-images.githubusercontent.com/15314183/143493235-3cab06be-bd77-4ff8-9712-df855830695f.png)

## Edition and Platform

 - Edition: Mattermost plugin
-  Version: v0.11
-  Browser and OS: Chrome & Firefox

**Comment by hahmadia** [comment]
Asaad has volunteered to help me with this problem.

**Comment by ogi-m** [comment]
Tested and passed on v0.11, the popup now respects the theme.
