### ISSUE TITLE
Bug: Not being able to select or edit text in v0.11.0-rc1 in Firefox

### ISSUE THREAD

**Issue by pullopen** [mattermost/focalboard#1884]
## Steps to reproduce the behavior

1. Go to any item
2. Try to select text, but failed
3. Try to put the cursor at desired position with mouse, failed.
4. Try to use ↑↓←→ keys to move the cursor, also failed.

## Expected behavior

Put the cursor into desired position and select certain text.

## Edition and Platform

 - Edition: Personal Server
 - Version: v0.11.0-rc1
 - Browser and OS: Firefox 94.0.2

## Additional context

I suppose it only happens after I upgrade. And on Chrome everything works fine.

**Comment by ogi-m** [comment]
Working as expected on latest v0.11
