### ISSUE TITLE
Feature Idea: Add option to turn off auto-random icon

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#190]
**Summary:**
Creating a new card automatically sets a random icon. This is by design, as it makes cards immediately distinguishable. However, sometimes we want to turn that off

**How important this is to me and why:**

Importance: Medium

**Additional context / similar features:**
P1: Add an option to the settings menu to turn this off. Store in localStorage per-client for now.
Bonus points: Create a `userSettings.ts` class to manage other settings like this
P3: (Future) consider how to store this and similar settings per server / instance / board

**Comment by Johennes** [comment]
I'd like to help address this and pushed a proposal for the a global "no random icons" option to #310.
