### ISSUE TITLE
Bug: Flood with "received a message for an unregistered webconn" in logs.

### ISSUE THREAD

**Issue by DummyThatMatters** [mattermost/focalboard#1900]
## Expected behavior
Clean logs

## Screenshots
![изображение](https://user-images.githubusercontent.com/51426114/144245182-5959baee-e0cc-43fe-b8b1-964622a4fb89.png)

## Edition and Platform
 - Edition: Mattermost plugin (Mattermost v6.1.0, postgres 12.1)
 - Version:  v0.10.0

## Additional context
Example of logs:
```
"timestamp":"2021-12-01 13:55:24.441 Z","level":"error","msg":"received a message for an unregistered webconn","caller":"app/plugin_api.go:898","plugin_id":"focalboard","webConnID":"6gbxw54p5pnu3bgn8464kpxnuo","userID":"bh863rbsxpy48xoit9a8rhreqr","action":"user_update_active_status"}
{"timestamp":"2021-12-01 13:55:24.481 Z","level":"error","msg":"received a message for an unregistered webconn","caller":"app/plugin_api.go:898","plugin_id":"focalboard","webConnID":"njipqceq1pd6tynraj9mgxufxe","userID":"bh863rbsxpy48xoit9a8rhreqr","action":"user_update_active_status"}
{"timestamp":"2021-12-01 13:55:25.092 Z","level":"error","msg":"received a message for an unregistered webconn","caller":"app/plugin_api.go:898","plugin_id":"focalboard","webConnID":"ftuduas1ipy4pmwozymg8qztcc","userID":"chmb57caqty55gkm4zpfha6xpy","action":"user_update_active_status"}
{"timestamp":"2021-12-01 13:55:25.113 Z","level":"error","msg":"received a message for an unregistered webconn","caller":"app/plugin_api.go:898","plugin_id":"focalboard","webConnID":"6cgh64t657b9xq3559s9jtbi1a","userID":"p3yggcqi43nn78afj9b7g487we","action":"user_update_active_status"}
{"timestamp":"2021-12-01 13:55:25.115 Z","level":"error","msg":"received a message for an unregistered webconn","caller":"app/plugin_api.go:898","plugin_id":"focalboard","webConnID":"9pmdds9m3pd3dk3g3ed7rb4rbe","userID":"cj3qwesgsir99kkaam7rhz3xrh","action":"user_update_active_status"}
{"timestamp":"2021-12-01 13:55:25.732 Z","level":"error","msg":"received a message for an unregistered webconn","caller":"app/plugin_api.go:898","plugin_id":"focalboard","webConnID":"ixi9egeorbne8qjxgou4oudc8h","userID":"o696b67bsiy3jqbzcedsup6kne","action":"user_update_active_status"}
{"timestamp":"2021-12-01 13:55:26.116 Z","level":"error","msg":"received a message for an unregistered webconn","caller":"app/plugin_api.go:898","plugin_id":"focalboard","webConnID":"5e4mo5t6rfgmzrroykouz3gf9c","userID":"8m6ww3p437dijqdyozrjpjn97r","action":"user_update_active_status"}
{"timestamp":"2021-12-01 13:55:26.150 Z","level":"error","msg":"received a message for an unregistered webconn","caller":"app/plugin_api.go:898","plugin_id":"focalboard","webConnID":"7f1h65tappdi8qtfq48fzrq89y","userID":"8m6ww3p437dijqdyozrjpjn97r","action":"user_update_active_status"}
{"timestamp":"2021-12-01 13:55:26.239 Z","level":"error","msg":"received a message for an unregistered webconn","caller":"app/plugin_api.go:898","plugin_id":"focalboard","webConnID":"bk5cpu4bh3ghjnstmjowt449wc","userID":"dkoed1a7cirg8q4d37ogi46qir","action":"user_typing"}
{"timestamp":"2021-12-01 13:55:26.307 Z","level":"error","msg":"received a message for an unregistered webconn","caller":"app/plugin_api.go:898","plugin_id":"focalboard","webConnID":"3nrn9zpmijfcmeucrnq3c8nk5o","userID":"iwohzddz1tbt5bwuat5eoq7xco","action":"user_update_active_status"}
{"timestamp":"2021-12-01 13:55:26.429 Z","level":"error","msg":"received a message for an unregistered webconn","caller":"app/plugin_api.go:898","plugin_id":"focalboard","webConnID":"uf3x1jmkfig4ff4afnfzidzuoo","userID":"xprj8hqp5b8dimokcuoikx6i4r","action":"user_typing"}
{"timestamp":"2021-12-01 13:55:26.504 Z","level":"error","msg":"received a message for an unregistered webconn","caller":"app/plugin_api.go:898","plugin_id":"focalboard","webConnID":"4o91fxyp8f8mjgcsme7pp5w8cc","userID":"oywnkg6r3pyh9pmju8mini7gww","action":"user_update_active_status"}
{"timestamp":"2021-12-01 13:55:26.508 Z","level":"error","msg":"received a message for an unregistered webconn","caller":"app/plugin_api.go:898","plugin_id":"focalboard","webConnID":"45zufzzc8ig5xk3rtepx5ogjuc","userID":"ebb6a5byubfwzkzp7kmr9r35oh","action":"user_update_active_status"}
{"timestamp":"2021-12-01 13:55:26.508 Z","level":"error","msg":"received a message for an unregistered webconn","caller":"app/plugin_api.go:898","plugin_id":"focalboard","webConnID":"1e79frh9k7g8uj79tqcmzi76bh","userID":"ebb6a5byubfwzkzp7kmr9r35oh","action":"user_update_active_status"}
{"timestamp":"2021-12-01 13:55:26.646 Z","level":"error","msg":"received a message for an unregistered webconn","caller":"app/plugin_api.go:898","plugin_id":"focalboard","webConnID":"8kcgz15byjgjudzmyhojiubbfw","userID":"x7f9itszsi8tjfgfuukm8637hh","action":"user_update_active_status"}
{"timestamp":"2021-12-01 13:55:27.298 Z","level":"error","msg":"received a message for an unregistered webconn","caller":"app/plugin_api.go:898","plugin_id":"focalboard","webConnID":"y6jowhz4ktgbz8cw8cqmqgyeta","userID":"5nekqxs8bbfi9fx918mm49y9gc","action":"user_update_active_status"}
```

Also sometimes when I switch to Boards - it asks me to authorize, although I've already logged in mattermost. Log-out and re-login fixes the issue.

**Comment by chenilim** [comment]
Thanks @DummyThatMatters. Sorry for the delay. This appears to be caused by the plugin crashing (or other error). Does disabling and re-enabling the Boards plugin (in System Console \ Plugin Management) fix the issue? Were there other logs that indicate a crash?

**Comment by DummyThatMatters** [comment]
Hello @chenilim ! There were no real crash actually. The problem is gone for some time for some reason, disabling and re-enabling the Boards plugin made it reappear once again) The plugin works fine, I cant tell that there is some actual crash took place, just issues listed above.
Probably there are some issues with our exact Mattermost insance as we have started to receive `Failed to upgrade websocket connection` error on our mattermost instance lately. I don't know if it is connected somehow. Thanks for support, if you have some clue on what parameters may be the cause of the problem - please let me know.

**Comment by DummyThatMatters** [comment]
@chenilim the problem disappears if I redeploy mattermost instance, but reappears on plugin being turned off/on.

**Comment by danielschubert** [comment]
Same here. After uprade to 
- mattermost 6.3.0 
- mattermost boards 0.12.0

**Comment by chenilim** [comment]
Thanks @DummyThatMatters and @danielschubert! @mgdelacroix / @jespino do you have any ideas about this error? Does it indicate an actual problem, or do we just need to suppress the log?

**Comment by danielschubert** [comment]
I am not sure, but to me there seems to be no actual problem. 
Everything works as expected on my side.

**Comment by DummyThatMatters** [comment]
@chenilim If I try to restart plug-in the issue appears again. And from time to time it behaves like #1903, asking to log in to system once again. I suppose you are leading to the idea of this issue being a duplicate of #1903 ?

**Comment by chenilim** [comment]
Thanks @DummyThatMatters, that's new information - the (incorrect) login page would appear if the plugin crashes, effectively causing each client to timeout on the websocket. It might be related in the sense that a crash would also generate error messages like the above.

I also notice that you're running v0.10 of the plugin. Since v0.12 (Jan release) is now out, you might consider upgrading to it from the Marketplace:
1. Open Marketplace from the main Mattermost menu
2. Search for Mattermost Boards, and upgrade to it

If you do, please let us know if that changes anything. Thanks.

**Comment by DummyThatMatters** [comment]
@chenilim thanks for advice. I've updated focalbord to 12.1. After restarting the server i found a observed errors in log:
`{"timestamp":"2022-01-25 03:39:14.129 Z","level":"error","msg":"webhub.broadcast: cannot send, closing websocket for user","caller":"app/web_hub.go:539","user_id":"s17kwz76qtyzmjoizwtg1yef7a"}
`
and familiar `{"timestamp":"2022-01-25 03:40:27.934 Z","level":"error","msg":"received a message for an unregistered webconn","caller":"app/plugin_api.go:924","plugin_id":"focalboard","webConnID":"ytxwunkcxid7zmjgkntpb58xbr","userID":"yzp8zyfzspyguxq98jhf7hrd7r","action":"user_update_active_status"}
`

After what a whole server stopped to respond with the message `limit exceeded` observed in user GUI after attempt to open desktop app or in web browser.
Currently i using mattermost 6.2.1 and updated to focalbord 0.12.1
![изображение](https://user-images.githubusercontent.com/51426114/150906936-9f2f031b-f98f-469e-9bc9-a30f18167e75.png)

**Comment by DummyThatMatters** [comment]
@chenilim The latter error might be irrelevant to focalbord, as we observed the same server fail behavior after updating mattermost from version 6.1.0 to 6.2.1.

**Comment by mgdelacroix** [comment]
The websocket error messages should not cause any issue. They appear if the plugin is restarted, as the websocket connections for the clients are kept active through Mattermost, but the newly booted Focalboard server doesn't recognize then anymore.

They shouldn't cause any issues, so I'd propose to move them to the `Debug` loglevel.
