### ISSUE TITLE
Bug: Share Board Option not Working

### ISSUE THREAD

**Issue by Genei180** [mattermost/focalboard#1911]
## Steps to reproduce the behavior

1. Go to ... left of "new" Button
2. Select  "Share Board"
3. Turn the switch on which says Publish to web and share this board with anyone.
4. Copy the link
5. Paste it into the Browser

## Expected behavior

After I hit Enter, a Board View Should Appear...

## Screenshots
![image](https://user-images.githubusercontent.com/16257607/144502555-fba4935b-1f4a-4799-a55b-6863beff912e.png)

## Edition and Platform

 - Testet in: Windows / Docker
 - Version: v0.10.0
 - Browser and OS: Chrome on Windows, Edge on Windows

## Additional context

Be Aware that the Share Option is only Available if you Specify: `"enablepublicsharedboards": true` in the config File
Which isn't what [Docs](https://www.focalboard.com/guide/user/#sharing-boards) suggest.
In my Opinion, this should be enabled by Default. 
Other People having Trouble as well see https://github.com/mattermost/focalboard/issues/1419.

Issue https://github.com/mattermost/focalboard/issues/1729 might be Similar and says it has been fixed, might be connected or not. Could be a good Idea to look into it.

**Comment by chenilim** [comment]
Thanks for reporting this @Genei180! Could you check your browser developer console to see if there are any errors in the JS console and / or network tab? The steps you used should (in theory) work. Thanks.

**Comment by Genei180** [comment]
@chenilim there is indeed an Error Message:

````
utils.js:19 Error: [@formatjs/intl Error MISSING_TRANSLATION] Missing message: "Sidebar.default-theme" for locale "de",
using default message as fallback. 

    at new MissingTranslationError (main.js:7179)
    at formatMessage (main.js:7339)
    at formatMessage (main.js:159781)
    at main.js:186694
    at Array.map (<anonymous>)
    at main.js:186694
    at renderWithHooks (main.js:140650)
    at updateFunctionComponent (main.js:143021)
    at updateSimpleMemoComponent (main.js:142880)
    at updateMemoComponent (main.js:142757)
````

The Network Tab apparently shows no errors.

If I am Understanding the Error Above, Correctly, it has something to-do with my German Language Setting.
So there I was Experimenting with the Language Files, and suddenly everything functions as it should.

I couldn't reproduce the Error, and git showed me no apparent Changes. (Even after a full hard reset too Multiple last Versions).
I even had explicitly made sure that a clean Branch from the original Repository produces the same Error on my Setup before initiating that Bug Report (Which it did).

The Old Docker Image still had that Bug going on (So no Browser Setting either), while the newly Compiled Image after that Incident functioned normally.

Again, git showed no Apparent Changes, and the Bug did occur before starting to Fiddle with the Language Settings...
I have no clue what caused it and the sudden Disapearence, maybe a Cache/Dependencie got updated?

If this doesn't appear again, I consider this closed.
Thank you for your time. Have a nice Day :)
