### ISSUE TITLE
Bug: Open the first board in the workspace instead of the "Create a board" screen

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1914]
## Summary

I always open a workspace expecting to land on a board, but instead I'm greeted with the "Create a board" screen.
I find this frustrating, especially for workspaces with a single board, as it requires unnecessary clicks to get to the board, 

## How important this is to me and why

Importance: Medium

**Comment by sbishel** [comment]
Will be handled differently with permission changes on 0.12. We should review then.

**Comment by sbishel** [comment]
Bumping to permissions release (0.16)

**Comment by chenilim** [comment]
Dup of https://github.com/mattermost/focalboard/issues/2516.
