### ISSUE TITLE
BugBash: Selecting text in card description flaky 

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#1915]
## Steps to reproduce the behavior

1. Create a new card
2. Type three lines of text in description.
3. Try to select the three lines by clicking on the first line and drag to the bottom line.
4. Sometimes the text is selected, sometimes nothing happens.

## Expected behavior

Selecting text should work consistently.

## Screenshots
In this screenshot, the mouse left button is clicked each time the cursor pauses at the top-left of the text.

![select_text_bug](https://user-images.githubusercontent.com/5024605/144627115-01e0c8e1-3aa4-4e48-9b5a-192ae1d92345.gif)

## Edition and Platform

 - Edition:  Plugin
 - Version: Mattermost v6.2-rc1, plugin v0.11-rc1
 - Browser and OS: FF 94 on Linux

**Comment by Talismanian** [comment]
Also noticing this on Docker, 0.11.0, FF94 on Linux too. Docker image 88ed2222a948.

**Comment by ogi-m** [comment]
Tested and passed on latest v0.11
