### ISSUE TITLE
BugBash: Cannot position caret within card description

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#1918]
## Steps to reproduce the behavior

1. Create a new card
2. Type three lines of text in description.
3. Position caret at end of third line.
4. Try to position caret on second line via mouse click
5. Notice that nothing happens

## Expected behavior

Should be able to position caret anywhere within existing text

## Screenshots

Screenshot shows clicking on the second line does nothing.

![cannot_position_caret](https://user-images.githubusercontent.com/5024605/144629928-e17a88a4-aef5-4add-bb29-4c5e17a35e1f.gif)

- Edition:  Plugin
 - Version: Mattermost v6.2-rc1, plugin v0.11-rc1
 - Browser and OS: FF 94 on Linux

**Comment by hahmadia** [comment]
WIP https://github.com/mattermost/focalboard/pull/1896 

Requires QA testing and then this will be solved.

**Comment by ogi-m** [comment]
Tested and passed, working as expected now in Firefox
