### ISSUE TITLE
Bug: Drag select card description text closes card if mouse released outside of dialog

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1919]
## Steps to reproduce the behavior

1. Open a card and enter a description
2. Using the mouse, click to start text selection in the description editor
3. Drag and release the mouse outside the dialog
4. The dialog closes, and changes are lost

## Expected behavior

The dialog should not close, and changes should not be lost. Or, at the very least, changes should not be lost.

## Screenshots

https://user-images.githubusercontent.com/46905241/144630208-26b60576-5376-45d9-b167-cf7eb6948d25.mov

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.11.0
 - Browser and OS: Chrome and Safari on macOS

## Additional context

This repros anytime a drag is started in the dialog, and released outside the dialog.

**Comment by kyeongsoosoo** [comment]
@wuwinson Can I take this issue?

**Comment by wuwinson** [comment]
Thanks @kyeongsoosoo! Assigned this ticket to you.
