### ISSUE TITLE
Bug: Creating a template from a card renders the workspace unusable

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/focalboard#1922]
## Steps to reproduce the behavior

1. On a board, create a card with some content
2. Create a template from the card
3. Get an error of "the card doesn't exist" on the card modal
4. Refresh
5. From that point on, accessing the workspace will redirect to an error page with `/boards/error?id=n is null` on the URL.

## Expected behavior

The template is created from the card.

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.11.0 RC
 - Browser and OS: Firefox 94 Linux

**Comment by ogi-m** [comment]
Might be related to https://github.com/mattermost/focalboard/issues/1888
