### ISSUE TITLE
Bug: card description editor doesn't support markdown

### ISSUE THREAD

**Issue by kamre** [mattermost/focalboard#1928]
## Steps to reproduce the behavior

1. Create a new board
2. Create a new card
3. Start adding card description via writing some markdown
4. Editor for card description does not have any support for markdown

## Expected behavior

Editor should support editing markdown as before

## Screenshots

Expected:
![MarkdownEditorBefore](https://user-images.githubusercontent.com/5587620/144723084-df37c4b0-e2d5-48c9-8aac-2896d0812e70.gif)

Regression:
![MarkdownEditorRegression](https://user-images.githubusercontent.com/5587620/144723806-80982f8e-b211-429d-bd53-1bc40318b661.gif)

## Edition and Platform

 - Edition: Personal Server
 - Version: v0.11.0
 - Browser and OS: Chrome on Windows

## Additional context

Regression was introduced by @hahmadia in #1836 

@chenilim is this switching of the editor to `draft-js` was intended and regression in markdown support was expected?

**Comment by chenilim** [comment]
Thanks for filing this @kamre! DraftJS supports plugins, and there are a number of markdown plugins available (e.g. [markdown-draft-js](https://github.com/Rosey/markdown-draft-js) and [draft-js-markdown-plugin](https://github.com/withspectrum/draft-js-markdown-plugin)). This is likely the most direct way to restore the previous Markdown editing functionality.

There are also more advanced editors built on DraftJS like [react-tapable-editor](https://github.com/ryuever/react-tapable-editor).

Longer term, the other consideration is we want Markdown editing to be consistent across Mattermost.

Open to any additional input from anyone - i.e. does anyone have experience or feedback with particular DraftJS plugins? Other approaches to consider?
