### ISSUE TITLE
Feature Idea: Consider switching to ProseMirror away from SimpleMde

### ISSUE THREAD

**Issue by tjbortz1s** [mattermost/focalboard#1941]
## Summary

SimpleMde works great on desktop, but absolutely stumbles and falls over itself once you try to do anything with it on mobile. 
ProseMirror allows similar functionality, but is a lot more robust/reliable/uses newer code.  You will have to use the low level features of it instead of the "drop in" SimpleMDE, but in the long run it might prove to be a lot more solid.

SimpleMDE is also not maintained at all and will probably keep falling behind with time.

## How important this is to me and why

Importance: Low

Use cases:
1.Usable mobile editor

## Additional context/similar features

The guy who made CodeMirror is working on a modernized version that SimpleMde could be converted to, but since ProseMirror is designed for text-editing instead of code, it's probably better to use the text-focused library anyways.

**Comment by kamre** [comment]
Hi @tjbortz1s! It seems that the editor was already switched to [draft.js](https://github.com/facebook/draft-js) and some functionality was [lost](https://github.com/mattermost/focalboard/issues/1928).

**Comment by chenilim** [comment]
Thanks for the suggestion @tjbortz1s! We've started looking at using a plugin to add back Markdown preview to draft.js. See note in #1928, and the [thread here](https://community-daily.mattermost.com/core/pl/6qmtxhsbg7fwxqscjnbiidsida) with a link to the test server - not sure how this performs on mobile. I wasn't aware of ProseMirror before, thanks!

Longer term, we are looking for a an "advanced editor" platform that can support markdown and potentially "block-based" editing. DraftJS seems like a good bet at present, but we are continuing to investigate. Appreciate other input and experiences.
