### ISSUE TITLE
Bug: Text fields don't wrap in shared read-only boards

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1948]
## Steps to reproduce the behavior

1. Open a card
2. Add a text field, paste in a long sentence (e.g. "This is a long sentence. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec suscipit fermentum feugiat. Pellentesque aliquet, quam id auctor vehicula, neque leo malesuada urna, in lobortis massa justo nec mauris. Proin enim mauris, ultrices et quam id, fermentum iaculis nisi. Morbi eget tellus in massa sagittis auctor. Sed ut purus turpis. Nullam ac lobortis diam. Etiam feugiat eros ut erat congue, condimentum pharetra quam mattis. Donec consequat urna ac bibendum lacinia. Aliquam lobortis diam et eros dictum suscipit.")
3. Share the board
4. Open the card in the shared board link
5. The text field wraps and overlaps

## Expected behavior

The text field should be limited to a single line, as it is in the editable card.

## Screenshots

<img width="744" alt="Screen Shot 2021-12-08 at 2 10 50 PM" src="https://user-images.githubusercontent.com/46905241/145292630-d06417ae-ff74-4a43-9a46-d6fe77059c57.png">

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.11 RC2
 - Browser and OS: Chrome 93

## Additional context

Also see repro in the new [acronyms board](https://community.mattermost.com/plugins/focalboard/workspace/orw8z8yajpd9fgxtuijq31eqkh/shared/bemqt6wf847fsdjoeobkor8ucye/v4mxkwwfzw38jicn8a1tsze8mja/c4cxrtdqi3bgkirnonsrj1i9iua?r=kneszyxxkixzc45wq5ebjna15eo).

**Comment by ogi-m** [comment]
Confirmed this is now fixed. Found a related bug - https://github.com/mattermost/focalboard/issues/2100
