### ISSUE TITLE
Bug: Tables don't render correctly in Personal Desktop

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1950]
## Steps to reproduce the behavior

1. Open a card and paste in a table, e.g.:

## Tables:
| Role / Rights | Admin | Editor | Commenter | Viewer |
| --- | --- | --- | --- | --- |
| Modify permissions | X | | | |
| Share board | X | | | |
| Delete board | X | | | |
| Rename board | X | X | | |
| Add, edit, and delete views | X | X | | |
| Add, edit, and delete cards | X | X | | |
| Comment | X | X | X | |
| View | X | X | X | X |

2. Exist the editor
3. The table is rendered with a border around each cell

## Expected behavior

The table should look like the one rendered in the plugin

## Screenshots

Table in Personal Desktop (Mac):
<img width="565" alt="Table - Personal Desktop" src="https://user-images.githubusercontent.com/46905241/145316140-3867f438-cf83-4e5d-a239-f4703ef2f520.png">

Same table in plugin:
<img width="570" alt="Table - plugin" src="https://user-images.githubusercontent.com/46905241/145316163-b0417bf2-724b-4c25-9f96-a55de1f4a9ff.png">

## Edition and Platform

 - Edition: Personal Desktop / Personal Server
 - Version: v0.11 RC2
 - Browser and OS: Chrome on macOS

**Comment by jufab** [comment]
Hi,

May I try?
