### ISSUE TITLE
Bug: "This card doesn't exist or is inaccessible" flashes briefly when creating card template or when creating a card from template

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1953]
## Steps to reproduce the behavior

1. Create a board and create a card
2. In the card dialog, click on `...` in the top right > New template from card
4. "This card doesn't exist or is inaccessible" error flashes briefly
5. Close the card dialog and click on the downward arrow next to "New" button on the board
6. Select the card template created from the card in step 2
7. "This card doesn't exist or is inaccessible" error flashes briefly again

## Expected behavior

No error

## Screenshots

<img width="998" alt="143920159-d921892d-5863-426b-bcbc-109dd018832a" src="https://user-images.githubusercontent.com/15314183/145391742-74c5c7b6-71c9-4510-a8c4-f6bec5e16de6.png">

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.11; v0.12
 - Browser and OS: Chrome on Windows

**Comment by chenilim** [comment]
Any followup @harshilsharma63?

**Comment by harshilsharma63** [comment]
@chenilim we decided that the flashing of that message for a split second is not an important issue for now. We decided to not work on it in the interest of the permissions feature.

**Comment by harshilsharma63** [comment]
I can pick this task next. Shouldn't be more than a day of work.

**Comment by harshilsharma63** [comment]
@ogi-m can you try this again on `main`? I tested and it works fine now.

https://user-images.githubusercontent.com/18575143/162190853-0353ea91-0b5e-4b2b-9814-964c9c19ccb3.mov

**Comment by harshilsharma63** [comment]
This works fine now.
