### ISSUE TITLE
Write Boards plugin developers guide

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1957]
## Summary

The [contributors / developer setup](https://www.focalboard.com/contribute/getting-started/) and [readme](https://github.com/mattermost/focalboard#readme) currently have instructions to develop against Personal Server. We should write a guide to setup a development environment for the Mattermost Boards plugin.

Looking for someone to write the initial draft, to be reviewed by the dev team. This should include best-practices for a developer workflow to build/test the plugin locally.

More and more features are specific to Boards, and require testing the plugin.

**Comment by justinegeffen** [comment]
Thanks, @chenilim! 

The first link provided has now been deprecated in favor of: https://mattermost.github.io/focalboard/ (which looks awesome!) and has this section: https://mattermost.github.io/focalboard/dev-tips.html. Would you say that meets the criteria for a guide?

One thing we can add is a link/sentence about how to edit the content as it's not immediately clear that the user needs to navigate to the repo (as opposed to using the "Edit on GitHub" button).

**Comment by chenilim** [comment]
Thanks @justinegeffen! The current dev tips and tricks refer to developing against Personal Server, which is the easiest way to get started. I realize we need additional details on how to develop against Mattermost Boards. I'll draft a separate page with tips and tricks, and review it with the team.
