### ISSUE TITLE
Bug: Long URLs don't wrap in card comments

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#1961]
## Steps to reproduce the behavior

1. Open any card
2. Copy the card link from the top right corner
3. Paste the copied URL into the comments section in the card

## Expected behavior

URL should wrap to 2nd line after reaching end of comments section on the right.

## Screenshots

https://user-images.githubusercontent.com/93531870/173430453-9cbe2cfd-5bdd-489f-a64f-7bdea666c009.mov

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.11 RC2
 - Browser and OS: Chrome Version 96.0.4664.55 on MacOS

**Comment by sbishel** [comment]
related to/ duplicate ? #2031

**Comment by kamre** [comment]
@sbishel probably not related to #2031 because the last one can be fixed easily via adding `max-width: 100%` to `octo-tooltip` class. And this bug is about the behaviour in the new `draft-js` editor.

**Comment by wuwinson** [comment]
Related to #3204
