### ISSUE TITLE
Feature Idea: Add MySql/MariaDB as alternatives to PostgreSQL

### ISSUE THREAD

**Issue by tcaldon** [mattermost/focalboard#198]
**Summary:**
Add MySql/MariaDB as alternatives to PostgreSQL

**How important this is to me and why:**

Importance: High/Medium

Use cases:
1. For those who have servers and are hosting sites with ISPConfig can't install and manage PostgreSQL i know that is going hot as control panel. So anyone that are using ISPConfig then can't install in production server

**Comment by chenilim** [comment]
Thanks for submitting this @tcaldon! It's good to know that Postgres isn't an option in some environments. We will investigate supporting MySQL if there is enough interest. The main reason we don't initially is to keep the test matrix small.

For anyone else who needs MySQL and can't use Postgres, please upvote this and (even better) add details on what environments don't run Postgres.

**Comment by chenilim** [comment]
@jespino, does your [checkin](https://github.com/mattermost/focalboard/commit/2d261fde59d0190824ae391f9bdee3ea77d21c05) resolve this issue? If so, please add the manual steps needed here (e.g. example config.json setting), and we can use this issue to update the docs. Thanks.

**Comment by jespino** [comment]
Yes, to use mysql you only need to change the config fields `dbtype` to `mysql` and `dbconfig` to something like `user:password@tcp(localhost:3306)/database?multiStatements=true`, `multiStatements=true` is important for the migrations, but can disappear eventually if we change how the migrations are executed (this can change sooner than later).

**Comment by chenilim** [comment]
Thanks @jespino! I'll leave it off the docs for now. We should add a doc when the migrations are cleaned up. Folks can Google and find this issue if they want to try it out sooner than that.
