### ISSUE TITLE
Bug: Calendar picker on-hover highlights are mispositioned

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1980]
## Steps to reproduce the behavior

1. Go to a card
2. Add a date property and open the date picker
3. Hover over a date
4. See that the highlight circle is not centered 

## Expected behavior

The higlights should be positioned correctly

## Screenshots

![Screenshot (160)](https://user-images.githubusercontent.com/15314183/145916567-a1b63ddc-507b-4399-904a-bad08a5ff49b.png)

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.11
 - Browser and OS: Windows, Chrome/Firefox

## Additional context

Doesn't repro on Personal Desktop.

**Comment by wuwinson** [comment]
Repro'ed @ogi-m's steps on Windows.

## Steps
Seeing some issues on Mac as well, but slightly different outcome. See video for details.
1. Open date picker on a card with date property
2. Hover over dates makes the dates blend in with highlight
3. Selecting a new date does not clear the original date

## Screenshots
https://user-images.githubusercontent.com/93531870/145924321-904a3ddd-d101-4176-b7e6-e5ff29b01ae4.mov

## Edition and Platform
Edition: Mattermost plugin
Version: v0.11
Browser and OS: Mac, Chrome

**Comment by ogi-m** [comment]
Tested and passed on v0.11 👍🏻
