### ISSUE TITLE
Bug: Theme and language popouts in the menu are not closed onblur

### ISSUE THREAD

**Issue by gvheertum** [mattermost/focalboard#1984]
## Steps to reproduce the behavior

1. Open the app in a browser or in the application window (seen in both Windows and Mac)
2. Open the settings via the settings button in the left bottom
3. Hover over the language and theme option, this will open both sub menu's
4. See language and theme overlapping each other

## Expected behavior
When "blurring" from the element I would expect it to close, this can be tricky since selecting an items will also cause a "blur". Perhaps when focus is on another element of the settings pane popouts of sub-menu's should be closed. A fix where opening a sub-menu will close all old sub-menu's will also work.

(with blur I mean mouse-out, with focus I mean mouse-over/mouse-in).

## Screenshots

<img width="490" alt="afbeelding" src="https://user-images.githubusercontent.com/7596658/146033489-af2bc847-868d-406f-80e2-0b217ad2ac9b.png">

## Edition and Platform

 - Edition: Personal Desktop (app view and browser view)
 - Version: 0.11.0, but also seen in 0.10.0.
 - Browser and OS: Both Windows and Mac seem to have this issue, so most likely it's caused in the HTML/JS parts

(tried to find a fix myself, but my react skills are a bit rusty ;) )

**Comment by kamre** [comment]
Hi @gvheertum! There was already similar bug #1581 reported and there is a pull request #1586 with possible fix.

**Comment by chenilim** [comment]
Picking up on this. We think this is a dup of #1581. So closing as a dup. cc @ogi-m - when #1581 is fixed, please validate that it fixes this too, otherwise reopen. Thanks.
