### ISSUE TITLE
Feature Idea: support gantt

### ISSUE THREAD

**Issue by 0xC0000000** [mattermost/focalboard#1995]
Hey guys,

Do you have any plan for gantt support ?

**Comment by chenilim** [comment]
Hi @0xC0000000, thanks for filing this. Yup, we have Gantt Charts on the long-term radar - dup of #https://github.com/mattermost/focalboard/issues/662. Right now, this is looking to be farther out (12+ months?). Please feel free to add any additional comments to #662, e.g. on why Gantt charts may be useful for your particular use case.
