### ISSUE TITLE
Bug: Boards App (macOS) Clicking "New" button and "+New" to create a new card shows a blank screen

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#1999]
Repros on macOS (but not Windows 10) Boards app from this link: https://focalboard-builds.s3.amazonaws.com/latest/focalboard-mac.zip

## Steps to reproduce the behavior

1. Download the macOS app from the above link
2. Create a board
3. Within the new board, click on "New" button to create a card and also click on "+New" to create a card
4. FYI, this also reproduces when hovering over an existing card in table view and then clicking "OPEN" 

## Observed
Blank screen from either of the actions in 3)

## Expected behavior

A new card is created and is displayed on the screen

## Screenshots

![image](https://user-images.githubusercontent.com/13020833/146414530-bc3cf5f5-103e-4fac-a5b1-6290bac7ffd3.png)

![image](https://user-images.githubusercontent.com/13020833/146414584-b0b5e37e-aea2-407a-975e-3a674cd27f55.png)

## Edition and Platform

 - Edition: Personal Desktop
 - Version: 0.12.0
 - Browser and OS: macOS

**Comment by kamre** [comment]
@chenilim probably the same as this one:
- #2002

**Comment by chenilim** [comment]
Looks like a dup of #2002. Working on a fix.
