### ISSUE TITLE
Bug: how can focalboard.exe be uesd on windows7？

### ISSUE THREAD

**Issue by Jacob-001** [mattermost/focalboard#2013]
i need use windows7 ,when i run focalboard.exe on win7,it can not run.
![win7 bug](https://user-images.githubusercontent.com/63133877/147108774-50f4e136-ec80-444d-a2d0-6a5dbeeafc01.jpg)

**Comment by chenilim** [comment]
Thanks for filing this @Jacob-001. Focalboard officially requires Windows 10+. To be honest, I'm not sure if it's even possible to update the build to support Windows 7 without significant changes.
