### ISSUE TITLE
Bug: Installation fails on MacOS

### ISSUE THREAD

**Issue by haardikdharma10** [mattermost/focalboard#202]
**Summary:**
When downloading Focalboard from the Mac App Store, the installation fails. The app downloads till it's usual size (15.3 MB in this case) but fails to install. Refer to the screenshot below.

**Steps to reproduce the behavior:**
1. Go to App Store.
2. Search for Focalboard.
3. Download the App.
4. Once the download is completed, the app fails to install.

**Expected behavior:**
The app should download and install successfully.

**Screenshots:**
<img width="1440" alt="Screenshot 2021-03-27 at 4 13 55 PM" src="https://user-images.githubusercontent.com/53044263/112719075-d0cec480-8f1c-11eb-9193-f11bf720b30d.png">

**Platform:**
 - OS and version: macOS BigSur 11.1

**Comment by chenilim** [comment]
Hi @haardikdharma10, hmmm.... that looks like it might be a temporary App Store or network issue. Are you still seeing this? And are you able to download other new apps?

**Comment by haardikdharma10** [comment]
@chenilim The issue still persists after updating to macOS BigSur 11.2.3 (which is the latest version). All other apps are being downloaded and installed successfully.

**Comment by chenilim** [comment]
Thanks @haardikdharma10. What hardware is this running on? Is it an M1 Mac? Are you able to build and run from source via `make mac-app`?

Also, found [this thread](https://talk.macpowerusers.com/t/appstore-updates-fails-to-install/21586/7) from a quick Google search. Try rebooting if you haven't already.

**Comment by haardikdharma10** [comment]
No it is not an M1 Mac. My model is MacBook Air 2018. Building and running `make mac-app` doesn't work as there are some breaking changes on my local branch :( Rebooting was not the solution apparently.

**Comment by chenilim** [comment]
Hmmm... FWIW, I just deleted and re-installed Focalboard from the Mac App Store on Big Sur (11.2.3) on a Macbook 2017.

The thread above also mentioned potential issues with using a VPN with the App Store. Other than that, I'd suggest trying again in a couple days (I've seen App Store download issues before), or we'll investigate further. Thanks.

**Comment by haardikdharma10** [comment]
@chenilim, I have to say that I have tried every solution available on the internet but still the issue is persisting. Do we have a .dmg file for the focalboard app instead?

**Comment by chenilim** [comment]
Thanks for the update @haardikdharma10. Are you able to build and run from source (`make mac-app`)?

At this point, we would like to avoid shipping a separate .dmg to keep things simple, though that may change in the future.

Definitely concerning that the App Store download is failing for you. The app should be available globally. If anyone else is experiencing this, please report too.

**Comment by haardikdharma10** [comment]
The app is now installed successfully. Just to confirm, It is version 0.6.0 right? Many features like the `Share Board` option is not available on the desktop app yet?

**Comment by chenilim** [comment]
Awesome @haardikdharma10! Did you finally get it installed via the App Store? If so, yes, that's 0.6.0.

`Share board` as currently implemented can't be a feature in the desktop app because it relies on a hosted server to share the URLs from. Overall, the goal of Personal Desktop is to be the best tool for an individual user, and Personal Server the best tool for small teams.

**Comment by haardikdharma10** [comment]
> Awesome @haardikdharma10! Did you finally get it installed via the App Store? If so, yes, that's 0.6.0.
> 
Yes, It got installed from the App Store itself :P 
> `Share board` as currently implemented can't be a feature in the desktop app because it relies on a hosted server to share the URLs from. Overall, the goal of Personal Desktop is to be the best tool for an individual user, and Personal Server the best tool for small teams.

Got it! I have added the documentation for share board. Please review the [PR](https://github.com/mattermost/focalboard/pull/270) at your convenience.

**Comment by chenilim** [comment]
Thanks @haardikdharma10! Closing this issue. Thanks also for the PR. Will check it out next.
