### ISSUE TITLE
Bug: It is not possible to create a new card on the focalboard

### ISSUE THREAD

**Issue by Redor** [mattermost/focalboard#2024]
## Steps to reproduce the behavior

1. creating a new board
2. hit the "New" button to create a new card
3. error occurs

## Expected behavior

I should be able to create a new card.

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: mattermost 6.2.1
 - Browser and OS: Chrome 96 on Linux

## Additional context

The client tries to POST to https://xx.xx.de/plugins/focalboard/api/v1/workspaces/ip4oipmidjgq9fqidcendjcfrc/blocks, but gets 500 error.

Payload:
`[{"id":"7ensjq1fw6xdcpreo6bc8cii9pc","schema":1,"workspaceId":"","parentId":"bd7eq9i1cr7nzzbee3j5c7cheoy","rootId":"bd7eq9i1cr7nzzbee3j5c7cheoy","createdBy":"","modifiedBy":"","type":"card","fields":{"icon":"🐚","properties":{},"contentOrder":[],"isTemplate":false},"title":"","createAt":1640695203782,"updateAt":1640695203782,"deleteAt":0}]`

On the server-side in the logs I see:
```
{"timestamp":"2021-12-28 13:06:42.710 Z","level":"error","msg":"API ERROR","caller":"app/plugin_api.go:924","plugin_id":"focalboard","code":"500","error":"\"Error 1366: Incorrect string value: '\\xF0\\x9F\\x90\\x81\",...' for column 'fields' at row 1\"","_msg":"","api":"/api/v1/workspaces/ip4oipmidjgq9fqidcendjcfrc/blocks"}
Waiting for data... (interrupt to abort)
```

Side info: I used focalboard for the first time, after installing mattermost 6.2.1

**Comment by chenilim** [comment]
Duped / fixed with the fix for #1999 in v0.12.

**Comment by chenilim** [comment]
Oops, sorry, this is on a different browser (Chrome Linux) than #1999 (Safari). Reopening.

**Comment by chenilim** [comment]
From a quick search, this appears to be an issue with the collation setting on MySQL (see this [StackOverflow issue](https://stackoverflow.com/questions/10957238/incorrect-string-value-when-trying-to-insert-utf-8-into-mysql-via-jdbc)). @harshilsharma63, I remember we set the collation explicitly in the migrations. Any idea why this might happen?

@Redor, to help us debug, do you remember the steps you used to set up MySQL for this installation? Thanks.

**Comment by chenilim** [comment]
Closing for now. Please reopen with more details if you are still experiencing this issue. Thanks.
