### ISSUE TITLE
Bug: Boards not working (Mattermost 5.39->6.2.1 upgrade) with SiteURL

### ISSUE THREAD

**Issue by LanceBurns** [mattermost/focalboard#2027]
## Edition and Platform

 - Edition: Mattermost plugin
 - Version: Mattermost 6.2.1 (Linux x64, Ubuntu Server 20.04.2)
 - Browser and OS: Mattermost Desktop App - Windows 10 & Ubuntu 21.04

## The Problem

I updated our Mattermost server to 6.2.1 (from 5.39.0), using the basic method suggested by the upgrade guide (which I’ve done many times previously), and boards aren’t working.

I do see the list of channels/boards, but attempting to view a channel’s board(s) results in:

> The team you’re requesting is private or does not exist. Please contact your Administrator for an invitation.

I’m a member of the team, and the administrator. Other (non-admin) team members see the same issues.

The log contains:

```
{"timestamp":"2021-12-30 12:32:49.822 +11:00","level":"error","msg":"API ERROR","caller":"app/plugin_api.go:924","plugin_id":"focalboard","code":"403","error":"\"access denied to workspace\"","_msg":"\"Access denied to workspace\"","api":"/api/v1/workspaces/0/users"}
{"timestamp":"2021-12-30 12:32:49.825 +11:00","level":"error","msg":"API ERROR","caller":"app/plugin_api.go:924","plugin_id":"focalboard","code":"401","error":"","_msg":"\"user does not have workspace access\"","api":"/api/v1/workspaces/0"}
```

Clicking “Back to mattermost” brings me to a page where I can “Log in again”, which gives me a 404 and the following error in the log:

```
{"timestamp":"2021-12-30 12:33:06.241 +11:00","level":"error","msg":"API ERROR","caller":"app/plugin_api.go:924","plugin_id":"focalboard","code":"401","error":"\"unable to delete the session: no update allowed from focalboard, update it using mattermost\"","_msg":"\"incorrect login\"","api":"/api/v1/logout"}
```

I’ve tried resetting the desktop app cache, ensured all server file permissions are set appropriately, restarted the mattermost service and apache proxy multiple times. Tried logging out and back in to renew my session.

I was previously using focalboard as an external client plugin before it was integrated - I removed that copy from `client/plugins` but it didn’t change anything. I tried removing/re-adding/enabling the new integrated plugin but no change.

The rest of Mattermost seems to be working fine…

**Comment by neosparx** [comment]
Another observation on this topic is that, the boards do work on the web browser but give the error on the windows desktop app

**Comment by chenilim** [comment]
Thanks for filing this. @LanceBurns, does Boards work when accessing Mattermost via browser instead of the desktop app (as @neosparx reported)?

What version of the Mattermost Desktop App is running?

Also, to double check, what version of Mattermost Boards is reported in the System Console (under `/admin_console/plugins/plugin_management`)? For Mattermost v6.2 it should be v0.11. If necessary, you can update Boards from the Marketplace:
1. Select top-left menu
2. Select Marketplace
3. Search for "Mattermost Boards"
4. Install or update to v0.11

@neosparx, are you seeing this problem on Mattermost v6.2 / Boards v0.11 as well? What version of the Desktop App is running for you?

cc @ogi-m - do you see a repro of this?

**Comment by LanceBurns** [comment]
It does indeed seem to work fine via browser (Firefox)!

Mattermost Desktop App version is 5.0.2 - tested with both Windows 10 and Ubuntu 21.04. I've done a "Clear Cache and Reload" as that has fixed other issues in the past, but no change here.

Mattermost Boards plugin is listed as 0.11.0 - I uninstalled/reinstalled it with no change in behaviour.

**Comment by chenilim** [comment]
Thanks for the additional info @LanceBurns! One more question: Do you have a SiteURL configured on Mattermost by any chance? There's currently an issue working against SiteURLs (https://github.com/mattermost/focalboard/issues/2032).

**Comment by LanceBurns** [comment]
Right, yep ours is installed off the root under `/mattermost` (using an Apache reverse/HTTPS proxy), so it seems likely that that's what it is. I guess we'll just eagerly await version 0.12. Thanks for following up, @chenilim!

**Comment by neosparx** [comment]
@chenilim Yes we are on the same versions, Mattermost v6.2 / Boards v0.11 / Mattermost Desktop App 5.0.2

**Comment by LanceBurns** [comment]
I have updated to Mattermost 6.3.1 / Boards 0.12.1, and the issue seems resolved via browser (tested with Firefox)... The desktop app, however, refuses to load boards via the Dashboard's "All Channels" list, i.e. going via:
![mm-boards-1](https://user-images.githubusercontent.com/3395466/150620486-47edf1c6-3bbd-4be5-925c-349ca096b837.png)
Selecting a channel via the Dashboard page gives the following as before.
![mm-boards-2](https://user-images.githubusercontent.com/3395466/150620489-e2b7563d-37d4-450c-abf3-1e5a4a96c18a.png)
The "Back to Mattermost" link does at least work now.

Loading boards by visiting a channel and clicking the "Boards" icon seems to work fine in the desktop app. If I trigger the bad state via the Dashboard I have to close the "Boards" tab before it will load a board via a channel though. I've tried "clear cache and reload" and such.

It seems likely that the remaining problem is in the desktop app rather than focalboard? Feel free to close if that's the case.

**Comment by chenilim** [comment]
@devinbinnie, my guess is that the desktop app is looking for "/boards", but with a siteURL, it's "/sireURL/boards", and not being handled correctly. Is this a known issue? cc @sbishel, @wuwinson, @jespino.

**Comment by devinbinnie** [comment]
> @devinbinnie, my guess is that the desktop app is looking for "/boards", but with a siteURL, it's "/sireURL/boards", and not being handled correctly. Is this a known issue? cc @sbishel, @wuwinson, @jespino.

The Desktop App should work correctly with a subpath, so if the URL is http://myserver.com/subpath, then http://myserver.com/subpath/boards should work correctly. Does the URL in the Desktop App match the SiteURL configured in the server?

**Comment by chenilim** [comment]
Thanks @devinbinnie! @LanceBurns, could you check the URL in the Boards tab? I believe you can get it in the dev network tab:
1. View menu \ Developer tools for current tab
2. Open the network tab
3. Refresh (Cmd+R)
4. Select the first item in the network tab
5. What's the request URL?

Does it match your https://server/mattermost/boards site URL path?

**Comment by LanceBurns** [comment]
@chenilim So the base URL of the dashboard appears to be `/mattermost/boards/dashboard` as you'd expect. The problem is when I select a board on that page.

Unfortunately I can't see any way to get the destination URL of the boards listed on the dashboard via the debug tools. Refreshing the dashboard via Ctrl-R takes me to the first board, rather than staying on the dashboard. Selecting "Dashboard" from the boards dropdown triggers the "Team Not Found" error. Doing so doesn't show anything extra on the network capture of the boards tab - the main tab's network capture simply shows the 404 error.

Here's a quick capture of the overall flow, low-res just for privacy but I'm sure anyone familiar with the layout will get the idea (explanation follows though):
https://user-images.githubusercontent.com/3395466/151273996-40d62163-7ebe-4ff7-b89e-cfe6020cb2e6.mp4
I select "Boards" to get the dashboard, then select a board. This takes me to "Team Not Found" on the main tab. I close the boards tab (I didn't need to in retrospect) and go back to the dashboard, and reload (same as Ctrl-R), which takes me to the first board. Selecting "Dashboard" from the channel/board drop-down takes me to the "Team Not Found" on the main tab again.

Happy to try more things in the debugger but I'll need some instructions on what else to do.

**Comment by chenilim** [comment]
Thanks @LanceBurns! Are there any errors in the network or console tabs?
1. Open Boards in the desktop app
2. View menu \ Developer tools for current tab
3. Open the network tab and clear it, and clear the console tab too
4. Now select the workspace to open from the Dashboard
5. Any errors in the network or console tabs?

Really appreciate your help!

**Comment by chenilim** [comment]
Thanks so much @LanceBurns! @ogi-m, I think the next step is to set up a repro of our own - i.e. Mattermost 6.3.1 / Boards 0.12.1 / Desktop App 5.0.2 on a server with a siteURL. If possible, let's use the same "/mattermost" subpath. cc @sbishel, @jespino, @wiggin77, @wuwinson.

**Comment by ogi-m** [comment]
@chenilim Confirmed I can repro this on https://subpath.test.mattermost.com/mattermost (MM v6.3.2 / Boards v0.12.1) using the Desktop App v5.0.2. 
I couldn't repro in Chrome.

**Comment by chenilim** [comment]
Thanks @ogi-m! I could repro it too. The error actually appears in the Channels tab, so to debug, open the Developer tools for that tab. I see a 404 error on the fetch on `https://subpath.test.mattermost.com/mattermost/api/v4/teams/name/mattermost`. @sbishel, can we assign someone to investigate? Though not sure if this issue is in the Boards or desktop app code. cc @devinbinnie.

**Comment by sbishel** [comment]
@jespino Could you take a look? This should have your latest fix as its 0.12.1.  Thanks

**Comment by devinbinnie** [comment]
Okay this is fun...I was able to reproduce your issue the first time I tried to do it. But on subsequent tries everything has worked fine. Tested using `https://subpath.test.mattermost.com/mattermost2` and Desktop App v5.0.3-rc2.

@chenilim @ogi-m If you can repro still can you try the latest RC?

**Comment by LanceBurns** [comment]
I've just been doing some further testing on my end. In the desktop app, attempting to add a new card also causes the same "Team Not Found" error, like so:
https://user-images.githubusercontent.com/3395466/151640780-1f09cc7d-1a12-4e2a-bf4b-b6917ab99868.mp4

However, upon reloading the board, an "Untitled" task has appeared. I cannot view it (triggers "Team Not Found"), but I can successfully delete it without issue.

Under Firefox, boards seem to be working fine. I haven't tested exhaustively, but nothing I've tested which has failed in the desktop app has failed in Firefox.

I also tested with the MM desktop app v5.0.3-rc4 (Windows 10 x64) and the results were unchanged on this end (tried multiple times).

**Comment by devinbinnie** [comment]
> I've just been doing some further testing on my end. In the desktop app, attempting to add a new card also causes the same "Team Not Found" error, like so: https://user-images.githubusercontent.com/3395466/151640780-1f09cc7d-1a12-4e2a-bf4b-b6917ab99868.mp4
> 
> However, upon reloading the board, an "Untitled" task has appeared. I cannot view it (triggers "Team Not Found"), but I can successfully delete it without issue.
> 
> Under Firefox, boards seem to be working fine. I haven't tested exhaustively, but nothing I've tested which has failed in the desktop app has failed in Firefox.
> 
> I also tested with the MM desktop app v5.0.3-rc4 (Windows 10 x64) and the results were unchanged on this end (tried multiple times).

@LanceBurns I can reproduce this as well, thanks for the steps. I'll make a ticket and see what I can do in the Desktop App :)

**Comment by wuwinson** [comment]
Thanks @devinbinnie! Please close this as a duplicate or when resolved.

**Comment by devinbinnie** [comment]
So, I was able to fix an issue with subpath name navigation, however, I think there is still an issue affecting Boards only that cannot be resolved on the Desktop App.

I have a PR with my changes to the Desktop App here with builds you can test with: https://github.com/mattermost/desktop/pull/1993

@chenilim Who would be best to look into this?

**Comment by chenilim** [comment]
Thanks @devinbinnie. @jespino, can you help investigate from our end? cc @sbishel.

**Comment by jespino** [comment]
I missed this, I going to give it a try, subpath + desktop app, right?

**Comment by sadsfae** [comment]
I have the exact same issue on latest `5.0.4` desktop version for Linux 64bit.

I am using the latest community Mattermost `6.4.1`.

**Comment by harshilsharma63** [comment]
@sbishel this will now be part of 7.0, not 0.16.
