### ISSUE TITLE
Feature Idea: We should remove configuration leaks from our code

### ISSUE THREAD

**Issue by Shonke** [mattermost/focalboard#2029]
## Summary

We should remove it to avoid revealing secrets in the log:
https://github.com/mattermost/focalboard/blob/e7c38c88226e7e333f19976182a6b26dae029eca/server/services/store/sqlstore/sqlstore.go#L39

From log:
```
info  [2022-01-01 14:50:57.790 +01:00] info [2022-01-01 14:50:57.785 +01:00] connectDatabase caller="mlog/mlog.go:218" dbType=postgres connStr="postgres://mmuser:YwXLhQ2fbc9CJT@localhost/mattermost_test?sslmode=disable&connect_timeout=10"
 caller="io/io.go:425" plugin_id=focalboard source=plugin_stdout
info  [2022-01-01 14:50:57.821 +01:00] info [2022-01-01 14:50:57.811 +01:00] Server.Start caller="mlog/mlog.go:218"
error [2022-01-01 14:50:57.811 +01:00] server not bind to any port caller="mlog/mlog.go:228"
 caller="io/io.go:425" plugin_id=focalboard source=plugin_stdout
```

## How important this is to me and why

Importance: Medium

Use cases:
1. Removing it should have no consequences

**Comment by sbishel** [comment]
The log file appears to be from an older build. The connection string no longer prints that was update here. https://github.com/mattermost/focalboard/pull/1564
Please reopen if you still see this issue.
