### ISSUE TITLE
Feature Idea: French translation

### ISSUE THREAD

**Issue by IDeAlternative** [mattermost/focalboard#203]
**Summary:**
French Translation.

**How important this is to me and why:**

Importance: High

Use cases:
1. Desktop app and others available apps !

**Additional context / similar features:**
To offer a French translation to Focalboard !

**Comment by micker** [comment]
strange translation is inside githube repo
https://github.com/mattermost/focalboard/blob/main/webapp/i18n/fr.json

**Comment by IDeAlternative** [comment]
No problem ! This translation seems to be good ! 👍🏻

**Comment by jespino** [comment]
Yes, this is already translated to french, the next version is going to include it.
