### ISSUE TITLE
Bug: {SOS} can‘t  work after several hours not edit,And Now I cant find my data back

### ISSUE THREAD

**Issue by HelloToday** [mattermost/focalboard#2053]
## Steps to reproduce the behavior

1. I download the app from Mac App store
2. Create some board of my work
3. after serveral hours not working /editing,it toast that [登陆过期]，and I cant use it any more. What is worse is I cant restore my data!!

## Screenshots

![image](https://user-images.githubusercontent.com/4242585/148347297-32e776ac-6601-406d-a819-19f6396b792b.png)

## Edition and Platform

 - Edition: Personal Desktop
 - Version: v0.11.0
 - MacOs 12
## Additional context

my device is Mac book pro 2015 ,and os is macos 12,

**Comment by sbishel** [comment]
Error is "Login Expired".

**Comment by chenilim** [comment]
Hi @HelloToday, thanks for reporting this. Does quitting and re-opening the Focalboard app work?

If possible, could you capture a screenshot of the error message toast? Is this in the same window, or separate dialog?

For reference, the Personal Server data is stored in a SQLite DB, `focalboard.db` under `~/Library/Containers/Focalboard.focalboard/Data/Library/Application Support/Focalboard/server` (at least on Big Sur, macOS 11.6.2). If you are worried about losing data, you can make a backup copy of that file.

**Comment by wiggin77** [comment]
I think this might be the same as https://github.com/mattermost/focalboard/issues/1903

**Comment by HelloToday** [comment]
> I think this might be the same as #1903
Thanks . I use the docker instead,which I can relog in with username and password,which the Personal Server can not

**Comment by HelloToday** [comment]
> I think this might be the same as #1903

Maybe it sees like. Hope you fix it ASAP~.

**Comment by chenilim** [comment]
Thanks @HelloToday. I'll close this as a dup of #1903 for now. The workaround is to close and repoen the app. Please reopen / file another issue if that doesn't work.

May also be related to https://github.com/mattermost/focalboard/issues/2156.
