### ISSUE TITLE
Bug: Change Notifications > Undoing a change produces a blank notification

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#2059]
## Steps to reproduce the behavior

1. Follow a card as user-1
2. As user-2 make a change to the card
3. Revert the change
4. Wait 2min - user-1 receives a blank notification

## Expected behavior

User-1 shouldn't get a notification if a change was quickly undone

## Screenshots

![blank_notification](https://user-images.githubusercontent.com/15314183/148542157-7fa8ee3c-3647-4e4e-82e1-746b619c9b53.jpg)

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.12

**Comment by ogi-m** [comment]
Probably not a high priority, but I can see this happening with accidental changes that get undone immediately.
cc @wiggin77 @wuwinson

**Comment by wiggin77** [comment]
This was fixed by https://github.com/mattermost/focalboard/pull/2037 which was merged into .12 branch.

A debug log entry is created when a diff is calculated to be empty/no change: 
```
debug [2022-01-07 17:11:59.080 -05:00] notifySubscribers - skip delivery; no chg     caller="app/plugin_api.go:922" plugin_id=focalboard hint="{card cnx3uwx9tqjbxicmyz4n5yntokw 6iaxcbx9i3reu8qamimbafc7ia c3mqsc9izfdj9dift15k7uqs8w Jan  7 17:11:40.727 Jan  7 17:11:59.058}" modified_by_id=c3mqsc9izfdj9dift15k7uqs8w
```

**Comment by ogi-m** [comment]
Thanks Doug, tested on the latest build and it is indeed fixed 👍🏻
