### ISSUE TITLE
Bug: Cannot edit description block if only a space

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#2063]
## Steps to reproduce the behavior

1. Edit card description to have only a space
2. Set focus somewhere else to commit block
3. Try editing same block
4. Cannot edit it

## Expected behavior

Edit the block that only has a space

 - Edition: Mattermost plugin
 - Version: v0.12.0   bug bash
 - Browser and OS: Linux FF 95.0.1

**Comment by wiggin77** [comment]
I suspect the issue is that saving allows a block that only contains whitespace, while editing does a trim space first then sees the block as empty and doesn't allow editing.  The fix would be:
- when saving an edit, check if the block only has whitespace
- if only whitespace, treat it as if all contents of the block were deleted

**Comment by wuwinson** [comment]
@harshilsharma63 Can you do a quick investigation to see if this can be fixed for v0.14. If necessary we can punt to a later release. cc @sbishel @chenilim
