### ISSUE TITLE
Bug: Duplicate boards do not duplicate images in cards

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2067]
## Steps to reproduce the behavior

1. Add an image to a card
2. Duplicate the board
3. The duplicated card doesn't show the image

## Expected behavior

Images should be duplicated.

## Edition and Platform

 - Edition: Personal Desktop and Mattermost plugin
 - Version: v0.12 RC1
 - Browser and OS: Mac Chome, Mac app, Win app

## Additional context

* Duplicating a card (in the same board) duplicates the image ok.
* Other content (text, divider, checkbox) are duplicated in the new board

**Comment by wuwinson** [comment]
Lets handle this with [Permissions](https://community-daily.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/b4ctmm917q3rzdfi451qtuxjzcw/v3ng1gwe7wtfaijukrhp8siwcpy/cr3yryak1tt8czcihebgr8jdwwa).

**Comment by chenilim** [comment]
This appears to be working on v0.15, so closing. @ogi-m, please double-check this on v0.16 as well. Thanks.
