### ISSUE TITLE
Bug: Importing particular archive causes 500 error and plugin crash

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2069]
## Steps to reproduce the behavior

1. Unzip and import the attached archive:
[import - 500 error.focalboard.zip](https://github.com/mattermost/focalboard/files/7829976/import.-.500.error.focalboard.zip)

2. See 500 error in Network tab
3. See errors in Mattermost System Log

## Expected behavior

No errors, and no plugin crash.

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.12 RC1
 - Browser and OS: Mac Chrome and Safari

## Additional context

(Updated) Also repros on Personal Server. Seems to be caused by https://github.com/mattermost/focalboard/pull/2054.

**Comment by wiggin77** [comment]
This is somewhat mitigated by https://github.com/mattermost/focalboard/commit/855ea70a445a8725d5e37325e91635fd1430608d which was cherry picked into the release branch.  It will no longer crash but the import does fail.
