### ISSUE TITLE
Bug: Ellipses sub menu does not collapse

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#2070]
## Steps to reproduce the behavior

1. Go to Card View
2. Add a couple description items
3. Select the ellipses menu item
4. Move up and down the menu items
5. The submenu does not come down when you move off.

## Expected behavior

The submenu should be removed after leaving main menu item

## Screenshots
<img width="707" alt="Screen Shot 2022-01-07 at 9 23 04 AM" src="https://user-images.githubusercontent.com/12704875/148575204-930fccc0-2d56-45d8-9bec-c092d9e2e654.png">

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.12.0
 - Browser and OS: [Chrome 94 on macOS]

**Comment by kamre** [comment]
@sbishel looks similar to these bugs:
- #1984 
- #1581

and there is a pull request with possible fix:
- #1586

**Comment by SpearsR** [comment]
@sbishel Can I pick this up?

**Comment by sbishel** [comment]
@SpearsR - Yes, its all yours. Appears to be an older fix for this. And a couple other bugs that may be fixed by same solution. Thanks.
