### ISSUE TITLE
Bug: Mac App sometimes fails to update after reload

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2077]
## Steps to reproduce the behavior

1. Open the Mac App
2. Refresh with File \ Home or Cmd+Shift+H
3. Try to drag a card to another column
4. The card does not update (this may take a few refreshes)

## Expected behavior

Updates happen

## Screenshots

https://user-images.githubusercontent.com/46905241/148616214-564c0e7d-a421-46ed-bbac-dedac23c8dbf.mov

## Edition and Platform

 - Edition: Personal Desktop
 - Version: v0.11 and v0.12 RC1
 - Browser and OS: macOS Big Sur 16.2.1 and Safari 15.2

## Additional context

Not sure if having Safari 15.2 is a factor, as the WKWebView depends on it.

**Comment by chenilim** [comment]
I've submitted a PR for this, but @ogi-m, can you help check if this repros for you? I saw this on macOS 16.2.1 (Big Sur) and with Safari 15.2 installed, and with the v0.11 and v0.12 RC1 Mac App binaries from GitHub.

**Comment by ogi-m** [comment]
@chenilim I don't have macOS, but I couldn't repro on Windows
