### ISSUE TITLE
Bug: Undo delete board doesn't always restore view and cards

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2079]
## Steps to reproduce the behavior

1. Delete a board (and confirm)
2. Press Cmd+Z (Ctrl+Z on Win) to undo
3. The board re-appears, but not the views or cards

## Expected behavior

Undo delete board should restore its views and cards as well.

## Screenshots

https://user-images.githubusercontent.com/46905241/148794862-55ece06f-8e95-4986-af2e-f1da41eaa016.mov

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.12 RC1
 - Browser and OS: macOS Chrome

**Comment by chenilim** [comment]
Same as #2080 - can this be supported in the new system?

**Comment by ogi-m** [comment]
This test has failed this morning in Rainforest test run.

Reproes on plugin and personal desktop.

cc @lindy65

**Comment by chenilim** [comment]
Thanks @ogi-m. Since there was a recent fix (#2222), I think we should investigate why it failed now - was this caused by another change? Are there other effects? If it turns out to be a larger issue, we can postpone, but I'll mark it for v0.15 for now. cc @jespino, @sbishel.

**Comment by jespino** [comment]
I'll take a look

**Comment by jespino** [comment]
@chenilim it is not failing for me in the personal server edition in the main branch. I'll try it in the plugin mode too.

**Comment by lindy65** [comment]
Thanks for the update @jespino - I ran the tests in Rainforest and it's no longer reproducing there.  Board, views and cards are restored after pressing CMD/CTRL+Z

I think we're fine to close this issue off again?

cc @ogi-m @chenilim

**Comment by chenilim** [comment]
Thanks @lindy65 and @jespino. If it's working now, agree we can close the bug. Do we have any idea why it failed for @ogi-m 3 days ago?

**Comment by lindy65** [comment]
I'm reopening this issue as it's regressed in v0.16.0

![image](https://user-images.githubusercontent.com/13020833/161037270-b9f1df8b-bbf7-4395-9e31-2546b1f858a4.png)

**Comment by sbishel** [comment]
Closing - reopened as new issue - https://github.com/mattermost/focalboard/issues/2696
