### ISSUE TITLE
Bug: Ubuntu 20.04 docker-compose error

### ISSUE THREAD

**Issue by BHanq** [mattermost/focalboard#2089]
## Steps to reproduce the behavior
Using version 0.11.0, pulled the zipped version at https://github.com/mattermost/focalboard/archive/refs/tags/v0.11.0.zip
1. Go to focalboard docker folder and run docker-compose up

## Error
Warning of npm needing version 8.3 but it is only a warning (and even while upgrading version it doesn't fix the error)

The command '/bin/sh -c npm install --no-optional &&     npm run pack' returned a non-zero code: 1
ERROR: Service 'app' failed to build : Build failed

## Screenshots
![focalboardError](https://user-images.githubusercontent.com/47426643/148995316-bcb56861-ed22-489e-b3bb-9206054b6ae6.png)

## Edition and Platform

 - Edition: Digital Ocean server (but also on my personal computer)
 - Version: Ubuntu 20.04

**Comment by chenilim** [comment]
Thanks @BHanq! Were there details below (after the screenshot cuts off)?
Try running the build separately, i.e.:
```
make prebuild
make webapp
make server
```
Please copy / paste the error text if there is one to help debug. Thanks!

**Comment by wuwinson** [comment]
Closing for now, please re-open or file a new ticket if anyone else if facing this issue. Thanks!
