### ISSUE TITLE
Bug: [Change Notifications] Date, Person, and Multi-select properties not displaying properly in the notification

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2094]
## Steps to reproduce the behavior

1. Have someone else or use a secondary account to make changes to the date, person, and multi-select properties on a card you're following:
2. Wait 2 minutes to receive the change notification from Boards Bot.
3. See the error in Boards Bot notification

## Expected behavior

The properties display the same as the card.

## Screenshots
![Change Notifications Bug](https://user-images.githubusercontent.com/93531870/149017549-aa2d159b-6b39-4980-9e63-404dc7785c59.png)

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.12 RC1
 - Browser and OS: Chrome Version 96.0.4664.55 on macOS

**Comment by wiggin77** [comment]
Fixed `Multiselect` and `Date` property types.  `Person` type remains to be fixed.
