### ISSUE TITLE
Bug: Users can be subscribed to card when feature flag is disabled

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#2095]
## Steps to reproduce the behavior

1. instantiate server with `subscriptions` feature flag disabled
2. create new board and populate with a card
3. with a different user, open the card
3. notice the `Follow` button is greyed
4. click the `Follow` button; the button does not change but the subscription is added to the database
     - to verify this you can enable the feature flag, restart server, and view card with the users from step 3

## Expected behavior

Users should not be able to create subscriptions when feature flag is disabled

## Edition and Platform

 - Edition: Mattermost plugin
 - Version:  v0.129.0 RC1
 - Browser and OS: Linux FF 91

**Comment by chenilim** [comment]
@wiggin77, is this still an issue now that we have removed the feature flag? cc @wuwinson, @sbishel.

**Comment by wiggin77** [comment]
If subscriptions cannot be disabled then I do not think it's an issue any longer and can be closed.

**Comment by chenilim** [comment]
Thanks.
