### ISSUE TITLE
Bug: Card following not working

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2107]
## Steps to reproduce the behavior

**Manual Follow**
1. Go to a card
2. Click on the "Follow" button on top right
3. See error: Button does not change to "Following"

**Auto-Follow**
4. Create a new card
5. See error: Button does not change to "Following"

**Add Followers**
6. @mention your secondary account on the card description or comment
7. Login to your secondary account and open the card
8. See error: User is not following the card they were mentioned on

## Expected behavior

Button should turn to "Following" in all 3 use cases

## Screenshots

https://user-images.githubusercontent.com/93531870/149179204-8f03929b-5580-4599-acd6-3e9ba69be9b2.mov

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.12 RC1.1?
 - Browser and OS: Chrome Version 96.0.4664.55 on macOS

**Comment by wiggin77** [comment]
No longer reproducible for latest build.  The root cause and how it was fixed are still unknown.

**Comment by wuwinson** [comment]
Cannot repro anymore, closing out.
