### ISSUE TITLE
Doc: Add documentation for exporting / importing archives

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2111]
## Summary

Not sure if I missed it, but we should cover how to:
1. Export a single board's archive
2. Export all board archives for a workspace / channel
3. Import an archive

## Link to documentation page

Should be added to the Boards documentation: https://docs.mattermost.com/guides/boards.html. [Here's the existing doc in the Focalboard User's Guide](https://www.focalboard.com/guide/user/#archives) for reference.

## (Optional) Additional context and/or screenshot

Exporting / importing are a useful workaround for copying and moving boards.
This can also be used to copy custom templates to other workspaces.

**Comment by marpit19** [comment]
Is this issue resolved or I can help with this

**Comment by justinegeffen** [comment]
This is not yet resolved, @marpit19 - we'd really appreciate your help if you're still able to. :)

**Comment by marpit19** [comment]
Sure I'll look into it @justinegeffen

**Comment by TylerStilson** [comment]
Has this issue been completed? Or would I be able to help with it?

**Comment by justinegeffen** [comment]
Thanks, @TylerStilson! We currently have [this section](https://docs.mattermost.com/boards/sharing-boards.html#import-and-export-a-board) in the docs but it's absolutely open to any improvements. #1972

**Comment by justinegeffen** [comment]
Completed and available in https://docs.mattermost.com/boards/migrate-to-boards.html
