### ISSUE TITLE
Bug: Issue upgrading from 6.2.1 to 6.3.0

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#2119]
Initially reported here -
https://community.mattermost.com/core/pl/c9krqnf8m3bmdd3xapgxms7pqw

(MySQL 5.7)
```
error [2022-01-14 15:24:29.010 +01:00] Table creation / migration failed             caller="app/plugin_api.go:928" plugin_id=focalboard error=""migration failed in line 0:

UPDATE focalboard_blocks_history AS bh SET bh.parent_id='' WHERE bh.parent_id IS NULL;
UPDATE focalboard_blocks_history AS bh SET bh.schema='' WHERE bh.schema IS NULL;
UPDATE focalboard_blocks_history AS bh SET bh.type='' WHERE bh.type IS NULL;
UPDATE focalboard_blocks_history AS bh SET bh.title='' WHERE bh.title IS NULL;
UPDATE focalboard_blocks_history AS bh SET bh.fields='' WHERE bh.fields IS NULL;
UPDATE focalboard_blocks_history AS bh SET bh.create_at=0 WHERE bh.create_at IS NULL;
UPDATE focalboard_blocks_history AS bh SET bh.root_id='' WHERE bh.root_id IS NULL;
UPDATE focalboard_blocks_history AS bh SET bh.created_by='system' WHERE bh.created_by IS NULL;


 (details: Error 1366: Incorrect integer value: '' for column 'schema' at row 4)""
```

## Screenshots
	
Jan-Peter Rusch
7:36 AM
Log is filling fast with:

![Bild eingefügt am 2022-1-14 15-36 (1)](https://user-images.githubusercontent.com/12704875/149538211-d03e91f4-85d1-4ca5-9da1-90164a2aaa9f.png)
![Bild eingefügt am 2022-1-14 15-36](https://user-images.githubusercontent.com/12704875/149538215-c40c8e1c-9b71-47c2-96fd-455553fa3798.png)

## Edition and Platform

 - Edition: 
 - Version: v0.12.0
 - Browser and OS:

## Additional context
	
Jan-Peter Rusch
7:30 AM
schema is BIGINT
	
Jan-Peter Rusch
7:40 AM
I reran the UPDATES with bh.schema = 1 & cleared the dirty flag in focalbaord_schema_migrations. Boards are running now.
	
Jan-Peter Rusch
7:48 AM
Still coming after after some time, had to switch off logging.

**Comment by jprusch** [comment]
I'm not sure, if the error on the schema upgrade is correlated to the webhub.broadcast errors. The webhub errors are logged in 100s.

**Comment by flyersa** [comment]
I have the same issue. Upgraded from 6.0.x to 6.3.0 same error in server log

**Comment by wget** [comment]
I have been able to fix the problem to our prod versions at @arawa thanks to the solution given by @jprusch on the Mattermost community chat server.

For those finding this bug and wanting to get strait to copy-pasting :arrow_heading_down: 

```
$ mysql -u root -p
[...]
MariaDB [(none)]> use mattermostdb;
MariaDB [mattermostdb]> UPDATE focalboard_blocks_history AS bh SET bh.schema=1 WHERE bh.schema IS NULL;
Query OK, 29 rows affected (0.007 sec)
Rows matched: 29  Changed: 29  Warnings: 0
MariaDB [mattermostdb]> select * from focalboard_schema_migrations;
+---------+-------+
| version | dirty |
+---------+-------+
|      15 |     1 |
+---------+-------+
1 row in set (0.001 sec)

MariaDB [mattermostdb]> update focalboard_schema_migrations set dirty = 0;
Query OK, 1 row affected (0.005 sec)
Rows matched: 1  Changed: 1  Warnings: 0

MariaDB [mattermostdb]> select * from focalboard_schema_migrations;
+---------+-------+
| version | dirty |
+---------+-------+
|      15 |     0 |
+---------+-------+
1 row in set (0.000 sec)

MariaDB [mattermostdb]> quit
```

**Comment by mgdelacroix** [comment]
Thanks @jprusch and @wget!

The solution can also be applied stopping only the plugin, and we need to set back the schema version as well so the faulty migration runs correctly the next time that we start the server.

These would be the steps with the changes described above:

1. In the System Console, go to the plugins section and disable the Boards plugin.
2. Log into the database and run the following queries:
```sql
UPDATE focalboard_blocks_history AS bh SET bh.schema=1 WHERE bh.schema IS NULL;
UPDATE focalboard_schema_migrations SET version = 14;
UPDATE focalboard_schema_migrations SET dirty = 0;
```
3. From the System Console, enable the plugin again. This time it should start correctly.
4. The migrations can be checked running the following query:
```sql
SELECT * FROM focalboard_schema_migrations;
```
The result of the query should show the version field set to `16` and the dirty flag set to `0`.

**Comment by fzakfeld** [comment]
For our installation we have the same issue, but this is how the migration table looks like:

```
mattermost=> select * from focalboard_schema_migrations;
 version |                      name
---------+------------------------------------------------
       1 | init
       2 | system_settings_table
       3 | blocks_rootid
       4 | auth_table
       5 | blocks_modifiedby
       6 | sharing_table
       7 | workspaces_table
       8 | teams
       9 | blocks_history
      10 | blocks_created_by
      11 | match_collation
      12 | match_column_collation
      13 | millisecond_timestamps
      14 | add_not_null_constraint
      15 | blocks_history_no_nulls
      16 | subscriptions_table
      17 | add_file_info
      18 | add_teams_and_boards
      19 | populate_categories
      20 | populate_category_blocks
      21 | create_boards_members_history
      22 | create_default_board_role
      23 | persist_category_collapsed_state
      24 | mark_existsing_categories_collapsed
      25 | indexes_update
      26 | create_preferences_table
      27 | migrate_user_props_to_preferences
      28 | remove_template_channel_link
      29 | add_category_type_field
      30 | add_category_sort_order
      31 | add_category_boards_sort_order
      32 | move_boards_category_to_end
      33 | remove_deleted_category_boards
      34 | category_boards_remove_unused_delete_at_column
      35 | add_hidden_board_column
      36 | category_board_add_unique_constraint
      37 | hidden_boards_from_preferences
      38 | delete_hiddenBoardIDs_from_preferences
      39 | add_path_to_file_info
(39 rows)
```

The board plugin on the admin page complains that "dirty" does not exist, which is obviously because the migrations schema is different.
![image](https://github.com/mattermost/focalboard/assets/43890789/2ea37579-8c48-4acb-bb7f-407776d578c7)

Mattermost 6.3.0, Focalboard 7.1.0
