### ISSUE TITLE
Bug: Database update error from Mattermost 6.2.1 to 6.3.0

### ISSUE THREAD

**Issue by luk4sk** [mattermost/focalboard#2121]
After updating the Mattermost from 6.2.1 to 6.3.0 and the focalboard from 0.11.0 to 0.12.0 boards do not work anymore.
An error with database update appears in the logs: 

`
{"timestamp":"2022-01-14 21:03:45.526 +01:00","level":"error","msg":"RPC call OnWebSocketDisconnect to plugin failed.","caller":"plugin/client_rpc_generated.go:620","plugin_id":"focalboard","error":"unexpected EOF"}
{"timestamp":"2022-01-14 21:03:45.526 +01:00","level":"error","msg":"RPC call OnWebSocketDisconnect to plugin failed.","caller":"plugin/client_rpc_generated.go:620","plugin_id":"focalboard","error":"unexpected EOF"}
{"timestamp":"2022-01-14 21:03:45.526 +01:00","level":"error","msg":"RPC call OnWebSocketDisconnect to plugin failed.","caller":"plugin/client_rpc_generated.go:620","plugin_id":"focalboard","error":"unexpected EOF"}
{"timestamp":"2022-01-14 21:03:45.564 +01:00","level":"error","msg":"RPC call OnDeactivate to plugin failed.","caller":"plugin/client_rpc_generated.go:33","plugin_id":"focalboard","error":"connection is shut down"}
{"timestamp":"2022-01-14 21:04:02.608 +01:00","level":"error","msg":"Table creation / migration failed","caller":"app/plugin_api.go:928","plugin_id":"focalboard","error":"\"migration failed in line 0: \n\nUPDATE focalboard_blocks_history AS bh SET bh.parent_id='' WHERE bh.parent_id IS NULL;\nUPDATE focalboard_blocks_history AS bh SET bh.schema='' WHERE bh.schema IS NULL;\nUPDATE focalboard_blocks_history AS bh SET bh.type='' WHERE bh.type IS NULL;\nUPDATE focalboard_blocks_history AS bh SET bh.title='' WHERE bh.title IS NULL;\nUPDATE focalboard_blocks_history AS bh SET bh.fields='' WHERE bh.fields IS NULL;\nUPDATE focalboard_blocks_history AS bh SET bh.create_at=0 WHERE bh.create_at IS NULL;\nUPDATE focalboard_blocks_history AS bh SET bh.root_id='' WHERE bh.root_id IS NULL;\nUPDATE focalboard_blocks_history AS bh SET bh.created_by='system' WHERE bh.created_by IS NULL;\n\n\n (details: Error 1366: Incorrect integer value: '' for column `mattermost`.`focalboard_blocks_history`.`schema` at row 19)\""}
{"timestamp":"2022-01-14 21:04:02.619 +01:00","level":"error","msg":"Failed to install prepackaged plugin","caller":"app/plugin.go:891","path":"/opt/mattermost/prepackaged_plugins/focalboard-v0.12.0-linux-amd64.tar.gz","error":"Failed to install extracted prepackaged plugin /opt/mattermost/prepackaged_plugins/focalboard-v0.12.0-linux-amd64.tar.gz: installExtractedPlugin: Unable to restart plugin on upgrade., error initializing the DB: migration failed in line 0: \n\nUPDATE focalboard_blocks_history AS bh SET bh.parent_id='' WHERE bh.parent_id IS NULL;\nUPDATE focalboard_blocks_history AS bh SET bh.schema='' WHERE bh.schema IS NULL;\nUPDATE focalboard_blocks_history AS bh SET bh.type='' WHERE bh.type IS NULL;\nUPDATE focalboard_blocks_history AS bh SET bh.title='' WHERE bh.title IS NULL;\nUPDATE focalboard_blocks_history AS bh SET bh.fields='' WHERE bh.fields IS NULL;\nUPDATE focalboard_blocks_history AS bh SET bh.create_at=0 WHERE bh.create_at IS NULL;\nUPDATE focalboard_blocks_history AS bh SET bh.root_id='' WHERE bh.root_id IS NULL;\nUPDATE focalboard_blocks_history AS bh SET bh.created_by='system' WHERE bh.created_by IS NULL;\n\n\n (details: Error 1366: Incorrect integer value: '' for column `mattermost`.`focalboard_blocks_history`.`schema` at row 19)"}
{"timestamp":"2022-01-14 21:04:02.725 +01:00","level":"error","msg":"Unable to activate plugin","caller":"app/plugin.go:142","plugin_id":"focalboard","error":"error initializing the DB: Dirty database version 15. Fix and force version."}
{"timestamp":"2022-01-14 21:04:13.352 +01:00","level":"error","msg":"Access to route for non-existent plugin","caller":"app/plugin_requests.go:37","missing_plugin_id":"focalboard","url":"/plugins/focalboard/api/v1/workspaces/9kfhcocwibycxrjxnuzi3yihha","error":"plugin not found: focalboard"}
{"timestamp":"2022-01-14 21:04:13.358 +01:00","level":"error","msg":"Access to route for non-existent plugin","caller":"app/plugin_requests.go:37","missing_plugin_id":"focalboard","url":"/plugins/focalboard/api/v1/workspaces/9kfhcocwibycxrjxnuzi3yihha/users","error":"plugin not found: focalboard"}
{"timestamp":"2022-01-14 21:04:13.358 +01:00","level":"error","msg":"Access to route for non-existent plugin","caller":"app/plugin_requests.go:37","missing_plugin_id":"focalboard","url":"/plugins/focalboard/api/v1/workspaces/9kfhcocwibycxrjxnuzi3yihha/blocks?all=true","error":"plugin not found: focalboard"}
{"timestamp":"2022-01-14 21:04:13.362 +01:00","level":"error","msg":"Access to route for non-existent plugin","caller":"app/plugin_requests.go:37","missing_plugin_id":"focalboard","url":"/plugins/focalboard/api/v1/workspaces","error":"plugin not found: focalboard"}
`

## Edition and Platform
 - Server OS: Debian 11.2
 - Mattermost Server: 6.2.1

**Comment by mgdelacroix** [comment]
Thanks for the report @luk4sk! Closing the issue as a duplicated of https://github.com/mattermost/focalboard/issues/2119, please check the comments of that ticket for the fix.
