### ISSUE TITLE
Bug: Mention Notification not delivered

### ISSUE THREAD

**Issue by Techsigns** [mattermost/focalboard#2123]
## Steps to reproduce the behavior

1. Add board
2. Create card
3. Add mention for user, who is member of the channel, team and board

## Expected behavior

Notification for card update on board should be received by user

## Error message from log
`
{"timestamp":"2022-01-15 21:45:54.958 Z","level":"error","msg":"Error delivering notification","caller":"app/plugin_api.go:928","plugin_id":"focalboard","backend":"notifyMentions","action":"add","block_id":"abk6wj6kuib85fdnkbski97jf7a","error":"\"MError:\ncannot deliver notification for @jens.schaerer: cannot get direct channel: createDirectChannel: A direct channel cannot be created between these users because they do not share a team in common., \n1 errors total.\n\""}
`

**Comment by chenilim** [comment]
Thanks for filing this @Techsigns! Looks like this is a followup to your [thread here](https://community-daily.mattermost.com/core/pl/r5475ep4tfrgz8gbn3tj3y7e1c). Any ideas @wiggin77?

From the description above, this should work as the user is a "member of the channel, team and board".

**Comment by wiggin77** [comment]
This is a Channels API call.  I'll check Channels code and see if there are other conditionals that can trigger this error.

**Comment by wiggin77** [comment]
@chenilim  I investigated this further.  The only way to get that specific error is to have two users without any teams in common.  No database errors will output that.  The error means the SQL query was successful but did not find any records.  It is searching for teams that contain both user ids and the none of the users or team can be deleted.

@Techsigns, are you sure neither user has been deleted or removed from the team they may have once had in common?  When doing an @mention, punctuation such trailing period, spaces are ignored.  Did the user mentioned show up in the auto-complete?

**Comment by Techsigns** [comment]
@wiggin77 the users are all members of the team, especially when I try to "notify" myself I get the same error. See some screenshots for investigation (some data obfuscated):
![image](https://user-images.githubusercontent.com/1929590/150939359-10ab60e9-96c5-4898-9da2-7be3b54fbf34.png)

This is the channel with the board and the members of the board:
![image](https://user-images.githubusercontent.com/1929590/150939608-a2b6c90e-5a31-4f32-8edb-51fc06b910ac.png)

autocompletion works:
![image](https://user-images.githubusercontent.com/1929590/150940125-a508c9fe-8917-41e7-b412-0568e2a36420.png)

at-mention on a card of the board:
![image](https://user-images.githubusercontent.com/1929590/150940125-a508c9fe-8917-41e7-b412-0568e2a36420.png)

Error from log:
`{"timestamp":"2022-01-25 08:27:59.288 Z","level":"error","msg":"Error delivering notification","caller":"app/plugin_api.go:928","plugin_id":"focalboard","backend":"notifyMentions","action":"add","block_id":"agj4snaetyjrsikoq7mutyz3drc","error":"\"MError:\ncannot deliver notification for @patrick.schreiber: cannot get direct channel: createDirectChannel: A direct channel cannot be created between these users because they do not share a team in common., \n1 errors total.\n\""}`

Hope this helps :)

**Comment by wiggin77** [comment]
Thanks for that info @Techsigns.  Can you confirm the `Boards` bot account is a member of the team.  It should be automatically created unless a setting is preventing that. Also can you let me know the state of these settings in system console:

`Integrations | Bot Accounts | Enable Bot Creation`.  There is a hyperlink in the description... you can click on it to see the Boards bot account.

`Site Configuration | Users and Teams | Enable users to open Direct Message channels with`

**Comment by Techsigns** [comment]
@wiggin77 thanks for the hint to the Bot accounts! They were disabled and Boards bot wasn't a member of the team. I've added it and the notifications work now!

**Comment by wiggin77** [comment]
That's great @Techsigns.  We'll look into how to better document this so others don't trip over it.  cc @chenilim

**Comment by chenilim** [comment]
Following up on documenting the workaround steps, @wiggin77 please review these steps:

If `@mention` notifications aren't being sent, perform the following steps as a System Admin:
1. Open the System Console to Bot Accounts, and set `Enable Bot Account Creation` to `true`
2. Add the Boards Bot account to each team:
  * Open the team in Mattermost, select the team dropdown, and select "Invite People"
  * Type "boards" and select the Boards Bot account

Is anything else required? cc @wuwinson.

**Comment by wiggin77** [comment]
After enabling bot accounts the plugin must be restarted to actually create the bot.

**Comment by wiggin77** [comment]
> Would disabling and re-enabling the plugin do that?

Yes, I believe so.

**Comment by chenilim** [comment]
Thanks! Posted the steps in a discussion here: https://github.com/mattermost/focalboard/discussions/2415.
