### ISSUE TITLE
Bug: Can't move card to another list after changing the css style

### ISSUE THREAD

**Issue by JadeVane** [mattermost/focalboard#2125]
## Steps to reproduce the behavior

I am going to move card to another list, but it returned to the original list unexpectedly.

## Expected behavior

Move card to another list

## Screenshots

![move-card-test](https://user-images.githubusercontent.com/34258753/149718078-db71eebc-6aff-4447-aeb5-5846e4aaa2e1.gif)

## Edition and Platform

 - Edition: Personal Server
 - Version: 0.12.0
 - Browser and OS: Brave 1.34.80 (based on Chromium: 97) on ubuntu 21.04

## Additional context

It happen after changing the css style. I'm not sure if this should be reported as a bug, so just feel free to close it if not

**Comment by chenilim** [comment]
Hi @JadeVane, thanks for filing this! Are there any errors in the browser console (Cmd+Shift+I on Chrome) or network tab? This issue may indicates a problem with the websocket update.

**Comment by moschlar** [comment]
We are seeing this too (Plugin 0.12.1 in Mattermost Server 5.2.1), regardless of any CSS change.

Browser Console *and* Server Log correctly show that a card movement occured, but the view of the browser where this occured does not update (refreshing the page shows the change then).

**Comment by chenilim** [comment]
@moschlar, could you try updating Mattermost Server to 6.3? There was an issue resolved there, and a workaround for earlier versions (to set the `EnableReliableWebsockets` flag. See [this note](https://github.com/mattermost/focalboard/discussions/1971) for more details. Thanks!

**Comment by moschlar** [comment]
@chenilim Thanks for your response - I can't easily update the Server since we're using the bundled version in GitLab Omnibus - but I activated that flag in the config and that seems to have worked for now! 

For anyone else experiencing this under the same circumstances, add this to `/etc/gitlab/gitlab.rb`:
```ruby
mattermost['env'] = {
    'MM_SERVICESETTINGS_ENABLERELIABLEWEBSOCKETS' => true,
}
```

**Comment by chenilim** [comment]
Thanks @moschlar!
