### ISSUE TITLE
Bug: Boards missing since Mattermost 6.3.0 Update (Teams)

### ISSUE THREAD

**Issue by terehov** [mattermost/focalboard#2128]
#### Summary
After upgrading to Mattermost version 6.3.0 the Boards plugin is missing in the menu bar.

#### Version

Mattermost Team Edition
Mattermost Version: 6.3.0
Database Schema Version: 6.3.0
Database: mysql

<img width="316" alt="Screenshot 2022-01-17 at 12 12 48" src="https://user-images.githubusercontent.com/490885/149793999-2846e4d4-aafe-4fb2-acd0-9f60d4125eea.png">

Corresponding issue: https://github.com/mattermost/mattermost-server/issues/19342

**Comment by terehov** [comment]
This is what I found in my logs: 

> Jan 18 11:25:23 {"timestamp":"2022-01-18 10:25:23.926 Z","level":"error","msg":"Not activating plugin because diagnostics are disabled","caller":"app/plugin_api.go:928","plugin_id":"com.mattermost.nps"}

So I enabled diagnostics. However this was the result (not sure if its related to this update): 

> Jan 18 11:28:35 {"timestamp":"2022-01-18 10:28:35.229 Z","level":"error","msg":"Unable to activate plugin","caller":"app/plugin.go:142","plugin_id":"focalboard","error":"error initializing the DB: Dirty database version 15. Fix and force version."}

**Comment by luk4sk** [comment]
Hi,
please check at:  https://github.com/mattermost/focalboard/issues/2119#issuecomment-1013751739

**Comment by terehov** [comment]
@luk4sk Thank you, it helped.

**Comment by viewpointsa** [comment]
For me, I did not have Board in menu, and plugin not listed in plugin. I did not kwow if all my actions must be done. My error:

`mattermost    | {"timestamp":"2023-12-20 13:31:15.941 Z","level":"error","msg":"Failed to install prepackaged plugin","caller":"app/plugin.go:945","path":"/mattermost/prepackaged_plugins/focalboard-v7.11.2-linux-amd64.tar.gz","error":"Failed to install extracted prepackaged plugin /mattermost/prepackaged_plugins/focalboard-v7.11.2-linux-amd64.tar.gz: installExtractedPlugin: Unable to move plugin from temporary directory to final destination. Another plugin may be using the same directory name., destination already exists"}`


# psql
```
mattermost=# select * from focalboard_schema_migrations;
 version | dirty
---------+-------
      14 | f
mattermost=# UPDATE focalboard_blocks_history SET schema=1 WHERE schema IS NULL;
UPDATE 10
```
# files
```
mattermost@3dd005d1ae62:~$ chown -R mattermost: .
mattermost@3dd005d1ae62:~$ cd plugins/
mattermost@3dd005d1ae62:~/plugins$ ls -l
total 20
drwxr--r-- 4 mattermost mattermost 4096 Dec 20 13:31 com.mattermost.apps
drwxr--r-- 6 mattermost mattermost 4096 Dec 20 13:31 com.mattermost.calls
drwxr--r-- 3 mattermost mattermost 4096 Mar 22  2021 com.mattermost.nps
drwxr--r-- 4 mattermost mattermost 4096 Feb  1  2022 focalboard
drwxr--r-- 5 mattermost mattermost 4096 Dec 20 13:31 playbooks
mattermost@3dd005d1ae62:~/plugins$ mv focalboard/ focalboard.bak
```
# Restart
Mattermost Version: 8.1.1
Database Schema Version: 109
Database: postgres
In Docker container
