### ISSUE TITLE
Bug: "Could not connect: Connection refused" error message in Firefox 87.0 on Manjaro 5.9.16 (Gnome)

### ISSUE THREAD

**Issue by sakr101** [mattermost/focalboard#214]
**Summary:**
linux version of the app doesn't work even building it from source, the result is similar.
**Steps to reproduce the behavior:**
1. go to terminal
2. cd app directory
3. run the binary
4. the app UI doesn't load

**Expected behavior:**
the app should run or even load the UI

**Screenshots:**
![Screenshot from 2021-03-30 07-25-08](https://user-images.githubusercontent.com/62211979/112939024-0ea13800-912b-11eb-8eb9-8d7ac4aad8ef.png)

**Platform:**
 - Browser and version: [Firefox 87.0]
 - OS and version: [Manjaro 5.9.16 (Gnome)]

**Additional context:**
- tried to build the application from source (v0.6.0 & v0.6.1) 
- tried first to initiate the server then use browser client.
- the UI is loaded  (on v0.6.0) but can't log-in to the application.
- after registration and trying to login, it returns to log-in again :  
- server log for **first registration**:
```
2021/03/30 07:28:38 Focalboard Server
2021/03/30 07:28:38 Version: 0.6.0
2021/03/30 07:28:38 Edition: linux
2021/03/30 07:28:38 Build Number: 644234983
2021/03/30 07:28:38 Build Date: Thu Mar 11 21:47:39 UTC 2021
2021/03/30 07:28:38 Build Hash: b9667151fce025228a82d3ab73c5c3ecca9be3f0
2021/03/30 07:28:38 readConfigFile
2021/03/30 07:28:38 {ServerRoot:http://localhost:8088 Port:8088 DBType:sqlite3 DBConfigString:./focalboard.db UseSSL:false WebPath:./pack FilesPath:./files Telemetry:true WebhookUpdate:[] Secret: SessionExpireTime:0 SessionRefreshTime:0 LocalOnly:true EnableLocalMode:false LocalModeSocketLocation:/var/tmp/focalboard_local.socket}
2021/03/30 07:28:38 connectDatabase
{"level":"info","ts":1617082118.8096724,"caller":"server/server.go:168","msg":"Server.Start"}
2021/03/30 07:28:38 http server started on :8088
2021/03/30 07:29:01 Single User: false
2021/03/30 07:29:01 API ERROR 401, err: unable to get the session for the token: sql: no rows in result set
2021/03/30 07:29:01 Single User: false
2021/03/30 07:29:01 API ERROR 401, err: unable to get the session for the token: sql: no rows in result set
2021/03/30 07:29:19 Single User: false
2021/03/30 07:29:19 API ERROR 401, err: unable to get the session for the token: sql: no rows in result set
2021/03/30 07:29:21 Single User: false
2021/03/30 07:29:21 API ERROR 401, err: unable to get the session for the token: sql: no rows in result set
2021/03/30 07:29:22 API ERROR 401, err: invalid username or password: sql: no rows in result set
2021/03/30 07:29:23 API ERROR 401, err: invalid username or password: sql: no rows in result set
2021/03/30 07:29:24 Single User: false
2021/03/30 07:29:24 API ERROR 401, err: unable to get the session for the token: sql: no rows in result set
2021/03/30 07:29:45 Single User: false
2021/03/30 07:29:45 API ERROR 401, err: unable to get the session for the token: sql: no rows in result set
2021/03/30 07:29:45 Single User: false
```
- when trying to register another user it shows : 
```
2021/03/30 08:00:03 API ERROR 401, err: <nil>
2021/03/30 08:00:04 API ERROR 401, err: <nil>
2021/03/30 08:00:04 API ERROR 401, err: <nil>
2021/03/30 08:00:04 API ERROR 401, err: <nil>
```

**Comment by mahesh-maan** [comment]
The same thing happened to me when I tried to run the desktop app, but when I used `sudo` privileges, the app started normally.

**Comment by Surendrajat** [comment]
Happened to me too because I was running it from home dir `$ ./focalboard-app/focalboard-app`.
But it worked fine when I started it from inside the extracted `focalboard-app` dir directly.

I guess this is an issue when the `focalboard-server` can't start if you run `focalboard-app` from outside that dir.

**Comment by gmarchault** [comment]
same issue for me. the desktop app is working fine, but when i'm using the server, the web client is working but i can't create a user. the server errors are the same as sakr101

**Comment by chenilim** [comment]
Thanks for filing this issue @sakr101! The error messages indicate the login failed. A few things:
* [Registering the first user doesn't require a token](https://www.focalboard.com/guide/server-setup/#registering-the-first-user), but subsequent registrations require an invite link.
* If this is a new test server, it's easiest to move or delete `focalboard.db` to start over, and register a new first user
    * Or you can use `sqlite3` to delete all rows from the `users` table if you want to preserve data
    * Then register a new user
* Delete the `sessionId` item in the browser's localStorage (shouldn't be necessary, but worth a try)

Hope this helps.

**Comment by chenilim** [comment]
@sakr101, just realized you were running the app binary using the [app config](https://github.com/mattermost/focalboard/blob/main/app-config.json), which uses single-user desktop mode meant only for the app. It's the same binary, but to run in multi-user mode with a browser, you need to use the server [config.json](https://github.com/mattermost/focalboard/blob/main/server-config.json) file.

I recommend:
* Copying to a separate folder, then
* Copy [server-config.json](https://github.com/mattermost/focalboard/blob/main/server-config.json) as config.json, and
* Edit it if necessary to change the port or paths

This is fine for a local test, but to set up Personal Server, follow the [download and setup guide here](https://www.focalboard.com/download/personal-edition/ubuntu/).

**Comment by jespino** [comment]
I improved the port opening to use a random one. This fix is in the main branch already.

**Comment by jespino** [comment]
I think I need to review it in more detail before closing it, sorry for the noise.

**Comment by jespino** [comment]
Ok, looks like this is already fixed.

**Comment by AB1908** [comment]
I have the same error but using the tar.gz package on Arch. Should I open a separate issue?
