### ISSUE TITLE
Feature Idea: URL property improvement

### ISSUE THREAD

**Issue by kamre** [mattermost/focalboard#2147]
## Summary

Currently URL property is represented as an `input` element (sometimes readonly) and an additional `button` that appears on hover and allows to follow the link:
<img width="568px" src="https://user-images.githubusercontent.com/5587620/150192149-70a3f0ff-3691-4cd5-8567-78f5b0100ac0.gif" >

But how often do you need to _edit_ the link vs _follow_ the link? Probably following the link or even just copying the link are the actions that are used more often than editing.

Proposed changes:
* make the whole URL text as a clickable link via `a` element
* on hover show two buttons for editing and copying in the card dialog
* show only copy button for the cards on kanban/gallery/calendar views
* in the table cell two buttons take too much space so only show the button for editing

This is how URL property will look in the card dialog:
<img width="592px" src="https://user-images.githubusercontent.com/5587620/150197430-aaf5d3df-b568-468d-b77a-0d73a52fcd69.gif">

Also we can support markdown syntax for the links so that displayed text can be entered by the user:
<img width="754px" src="https://user-images.githubusercontent.com/5587620/150198216-1735a368-75d5-42c0-a331-6bdeb2b4fa92.gif">

## How important this is to me and why

Importance: Medium, nice to have feature

## Additional context/similar features

Notion URL property works like this and it is rather convenient.

@chenilim @wuwinson @asaadmahmood what do you think about such improvement for URL property?

**Comment by jprusch** [comment]
URLs can get quite long & are a pain to display. Wouldn't it be great to have a small Edit icon and otherwise a "Jump/Goto" button hiding the URL. I know nobody, who "reads" are URL & knows where it is pointing to. That's why we can hide the URL in MM discussions & have an autolink feature. (I wish that one for comments & description in cards...)

**Comment by wuwinson** [comment]
@kamre Thanks for submitting this idea! Great suggestions, and greed that this would be an improvement to the UX. I've documented some requirements below for additional clarity. Let's hold off on the markdown syntax for now. We may want to consider using some kind of "Display Text" field which is a more common experience and would also address @jprusch's feedback.

## Requirements
1. If the field on a URL property has a link, make the whole URL text as a clickable link
2. To edit the URL, user must click on the Edit button when hovering over the field
  a. Display "Edit" hover text
3. To copy the URL, the user can click on the Copy button when hovering over the field
  a. Display "Copy" hover text
4. When hovering over the URL field, display the following:
  a. On the card dialog: Show buttons for Editing and Copying
  b. On board/gallery/calendar views: Show only the Copy button on the cards if the URL property is enabled
  c. On table view: Show the Edit button on the cards if the URL property is enabled
5. If the URL property is empty on the card dialog, leave the field as editable and do not display any hover over buttons

**Comment by kamre** [comment]
@wuwinson ok, lets hold off for the markdown editing because there can be better solutions like popups with two fields in JIRA for example. So far I have finished the implementation for documented requirements and created pull request.

Regarding the feedback from @jprusch I suppose he is talking more about the links in the card _description/comments_ instead of a card _link property_. And in particular about this server-side [Mattermost plugin](https://github.com/mattermost/mattermost-plugin-autolink#readme) so that it can be used for processing of the card comments/description content in the boards server plugin.

**Comment by jprusch** [comment]
Actually, I don't like a url link property displaying the "raw" url. The plain url is in many case not relevant for a user & hiding it behind a generic "Jump / Goto" button is from a user & UI perspective better than just printing it out. Each URL / Link property field has a descriptive name. Either display the field name & a button right next to it, or use the field name as button text.

**Comment by kamre** [comment]
@jprusch do you mean a popup like this one from Confluence:
<img width=426px src=https://user-images.githubusercontent.com/5587620/151040410-8c3fa1b3-0805-49e8-944f-ecb6c715479f.png>
?
@wuwinson is there an example of such popup in the [mattermost-webapp](https://github.com/mattermost/mattermost-webapp)?

**Comment by wuwinson** [comment]
Thanks @kamre! I'm not aware of such a pop-up within the webapp, but adding @chenilim and @asaadmahmood to chime in since they're more familiar with the product.

**Comment by jprusch** [comment]
Hi @kamre 
assume I've got a card like this:

<img width="337" alt="image" src="https://user-images.githubusercontent.com/9337414/151123804-001d55a1-cce6-4c82-817e-d77074f0a1c1.png">

I want this card displayed on a board or a table not to display the raw URL like here

<img width="211" alt="image" src="https://user-images.githubusercontent.com/9337414/151123523-44f02fa5-f6ef-4fb8-8ecd-a2bc16ed67b8.png">

but something like

![image](https://user-images.githubusercontent.com/9337414/151124620-05608b7a-29ec-45ba-b4df-d3415d15c941.png)

Take the field description as text for the button & link the URL for the field to the button click.

I haven't made my mind up about the editing of a URL property field. Maybe something like:

![image](https://user-images.githubusercontent.com/9337414/151125215-d986b32e-e260-4bc5-8d15-ed4f4dad9579.png)

Just my thoughts...

JP

**Comment by asaadmahmood** [comment]
@kamre @wuwinson I think this a great idea.
I also like @jprusch idea on how the link can be displayed as well, if I had to pick one, I would not mind going with the link with the edit and copy options like presented, as that's more consistent with what we have right now, and then decide if we want to move with the button feature later.
