### ISSUE TITLE
Bug: Focalboard 0.12.1 on Mattermost does not have the menu which allows to export and import archives.

### ISSUE THREAD

**Issue by hamidhamzeiy** [mattermost/focalboard#2148]
## Steps to reproduce the behavior

1. Go to Boards on Mattermost
2. Click on the gear (settings) on the upper right hand corner of the screen
3. The previously available menu as described at the end of the documentation (in this link: https://www.focalboard.com/guide/user/), does not exist. 

## Expected behavior

I expect to be able to import my archives from a previous installation of Mattermost and Boards

**Comment by chenilim** [comment]
Hi @hamidhamzeiy, which build is this? Confirmed this is working as of v0.12.

**Comment by hamidhamzeiy** [comment]
It's v0.12.1 on Mattermost 6

**Comment by chenilim** [comment]
Hmmm... here's what the settings menu looks like on my server:
<img width="309" alt="settings menu" src="https://user-images.githubusercontent.com/46905241/151255077-1b3c23cf-83e7-452c-8a62-ef72b45c691a.png">

To double check, make sure you have opened Boards first (i.e. this is not the Channels settings). Could you share a screenshot of your menu? Thanks.

**Comment by hamidhamzeiy** [comment]
Well that's not how it looks on our installation. We simple get the Mattermost menu and it doesn't matter whether we are on the channels page or the boards page
![Screenshot from 2022-01-28 16-27-21](https://user-images.githubusercontent.com/763329/151574114-685c9701-dfc6-48b2-9f54-8efc6d671e4d.png)
.

**Comment by chenilim** [comment]
Cleaning up old issues. @hamidhamzeiy, since this was on an old version, would you mind checking on a newer (e.g. 7.1) release, and open a new issue if still repros?

Selecting the settings icon while in Boards should open the Boards settings menu, so if it opens the main (Channels) settings dialog, that's a bug. Thanks.

**Comment by hamidhamzeiy** [comment]
The issue ix fixed in the new version. Thank you
