### ISSUE TITLE
Doc: Unreadable text on landing page (in mobile)

### ISSUE THREAD

**Issue by bnainar** [mattermost/focalboard#2149]
## Summary
Parts of a paragraph have white foreground and background making them unreadable

## Link to documentation page
https://www.focalboard.com/

## (Optional) Additional context and/or screenshot

![Screenshot_20220120_174037](https://user-images.githubusercontent.com/94557605/150336698-63fdf131-004b-4d92-8b16-3ee08525d956.png)

**Comment by justinegeffen** [comment]
Thanks, @bnainar! I've let the team know about this. :)

**Comment by chenilim** [comment]
Thanks! I ran into this before and will submit a fix - it's the min-height of the background.
