### ISSUE TITLE
Feature Idea: Add French to server application

### ISSUE THREAD

**Issue by frague59** [mattermost/focalboard#215]
**Summary:**
Just add "French" to "Settings" > "Set language" 

**How important this is to me and why:**
I'ld like to deploy a local server for my organization, and most on peoples does not speak english (or spannish)

Importance: High

**Additional context / similar features:**
We are searching for an alternative to Trello, which we cannot use as local public service in France.

**Comment by jespino** [comment]
French is already added, it is going to be included in the next release :)
