### ISSUE TITLE
Bug: Some template icons show ? 

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2153]
## Steps to reproduce the behavior

1. Log into https://master.test.mattermost.com/boards/
2. Create a board
3. Notice that some template icons show ?
4. Create a board from the "Project tasks" template
5. It's icon is ?

## Expected behavior

The correct icons appear.

## Screenshots

<img width="1408" alt="Screen Shot 2022-01-20 at 9 56 26 AM" src="https://user-images.githubusercontent.com/46905241/150395324-eee72168-dacd-4476-9258-dfce5c66d701.png">

<img width="441" alt="Screen Shot 2022-01-20 at 9 56 56 AM" src="https://user-images.githubusercontent.com/46905241/150395330-58dda629-f4b7-4313-9d92-20eca05452e2.png">

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.12 (main build on Jan 19/20)
 - Browser and OS: Chrome 96 on Mac

## Additional context

This may be related to #2119 and encoding settings in MySQL.

**Comment by chenilim** [comment]
@ogi-m, try updating from 0.12 to 0.14, and close if no repro.

**Comment by ogi-m** [comment]
Couldn't repro this with a fresh install. Closing.
