### ISSUE TITLE
Doc: Report a bug

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2155]
## Summary

Focalboard.com is being sunsetted, and the [feedback link](https://www.focalboard.com/feedback/) will redirect to [Mattermost bug reporting](https://handbook.mattermost.com/contributors/contributors/ways-to-contribute#report-a-bug) which isn't relevant to Board users. We should add a bug reporting section within the Boards handbook with more relevant guidelines.

### Report a Bug
Have you encountered an issue while deploying or using Mattermost Boards that you’d like to report?
1. Search our [Github issues](https://github.com/mattermost/focalboard/issues) to see if anyone else has already reported the issue. If so, show your support by commenting on the issue, and share any additional information you might have.
2. If the issue is a security vulnerability, please review our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/) to ensure our users stay safe.
3. If the first two steps don’t apply, you can [create a new issue](https://github.com/mattermost/focalboard/issues/new/choose) on the Boards Server GitHub repository. Please fill out all sections in the Issue template.

## Link to documentation page
https://docs.google.com/spreadsheets/d/1vu0vFMH8PxMFPvCBEVx6BsJpKJmZz_30XTuJZZYM4rU/edit#gid=1388870109

**Comment by justinegeffen** [comment]
Thanks, @wuwinson! I can definitely add this to the Handbook in a "Boards" section. LMK if that works for you.

**Comment by wuwinson** [comment]
Sounds great, thanks @justinegeffen!

**Comment by justinegeffen** [comment]
Content has been added: https://handbook.mattermost.com/contributors/contributors/ways-to-contribute#report-a-boards-bug. Closing. :)
