### ISSUE TITLE
Bug: make mac-app not compatible with m1 chip

### ISSUE THREAD

**Issue by jpaldeano** [mattermost/focalboard#2160]
## Steps to reproduce the behavior

Run the the command `make mac-app` using a MacBook Pro - Apple M1 Chip . 

Got errors: 

```
% make mac-app
mkdir -p bin/mac
cd server; env GOOS=darwin GOARCH=amd64 go build -ldflags '-X "github.com/mattermost/focalboard/server/model.BuildNumber=dev" -X "github.com/mattermost/focalboard/server/model.BuildDate=n/a" -X "github.com/mattermost/focalboard/server/model.BuildHash=92eb78357fbed987ef412d49667f5ea8f2ae7c47" -X "github.com/mattermost/focalboard/server/model.Edition=mac"' -o ../bin/mac/focalboard-server ./main
package github.com/mattermost/focalboard/server/main: build constraints exclude all Go files in /Users/joaoaldeano/personal/focalboard/server/main
make: *** [server-mac] Error 1
```

## Expected behavior

Looking to ReadMe this command should create an application: `Focalboard.app`.

## Edition and Platform

 - Edition: MacBook Pro (13-inch, M1, 2020) 16 GB
 - Chip: Apple M1 

## Additional context

Looking to the error it seems that Makefile line 36 defines:
`cd server; env GOOS=darwin GOARCH=amd64 go build -ldflags '$(LDFLAGS)' -o ../bin/mac/focalboard-server ./main`

But the systems arch on m1 chip is arm64.

**Comment by chenilim** [comment]
Thanks for filing this @jpaldeano! We'd be happy to take a PR to support M1. Looks like `uname -m` returns `x86_64` on my 2014 iMac, so we may need to translate that to `amd64` for GOARCH.

**Comment by jpaldeano** [comment]
Thanks @chenilim , I noticed that after the ci have ran the tests. It seems to be green now.
