### ISSUE TITLE
Websocket Error Docker container behind Nginx ProxyManager 

### ISSUE THREAD

**Issue by frauseo** [mattermost/focalboard#2183]
## Problem
My Focalboard sits behind a nginx reverse proxy ([NPM](https://nginxproxymanager.com/)). On the LAN there is no errors and Websockets work fine as i can see in the running docker container. When i access the Focalboard from the internet, there are these Websocket errors. As described in the [Docs/Personal Server](https://www.focalboard.com/guide/websocket-errors/), there are a solution only for a locally installed environment.

## Docker Setup
Running the Container:
```yml
version: "3"

services:
  focalboard:
    image: mattermost/focalboard:0.12.1
    container_name: focalboard
    ports:
      - 4024:8000
    volumes:
      - "/volume/docker/focalboard:/data"
      - "./server_config.json:/opt/focalboard/config.json"
    restart: unless-stopped
```
Note that i have a MariaDB-Container running on port 4002.

### Config
I picked the server_config.json and made changes to my needs
```json
{  
  "serverRoot": "http://localhost:8000",
  "port": 8000,
  "dbtype": "mysql",
  "dbconfig": "user:password@tcp(192.168.1.11:4002)/focalboard",
  "useSSL": false,
  "webpath": "./pack",
  "filespath": "/data/files",
  "telemetry": true,
  "session_expire_time": 2592000,
  "session_refresh_time": 18000,
  "localOnly": false,
  "enableLocalMode": true,
  "localModeSocketLocation": "/var/tmp/focalboard_local.socket"
}
```

## Nginx Proxy Manager Config
Since Focalboard is sitting behind my NPM-Container, i came up with this config:
```
# ------------------------------------------------------------
# focalboard.domain.tld
# ------------------------------------------------------------

server {
  set $forward_scheme http;
  set $server         "192.168.1.11";
  set $port           4024;

  listen 80;
  listen [::]:80;

  listen 443 ssl http2;
  listen [::]:443 ssl http2;

  server_name focalboard.domain.tld;

  # Let's Encrypt SSL
  include conf.d/include/letsencrypt-acme-challenge.conf;
  include conf.d/include/ssl-ciphers.conf;
  ssl_certificate /etc/letsencrypt/live/npm-26/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npm-26/privkey.pem;

  access_log /data/logs/proxy-host-27_access.log proxy;
  error_log /data/logs/proxy-host-27_error.log warn;

  location ~ /ws/* {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Real-IP		$remote_addr;
    proxy_pass       http://192.168.1.11:4024;

    # Inherited
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_http_version 1.1;
    
    # Custom location
    client_max_body_size 50M;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Frame-Options SAMEORIGIN;
    proxy_buffers 256 16k;
    proxy_buffer_size 16k;
    client_body_timeout 60;
    send_timeout 300;
    lingering_timeout 5;
    proxy_connect_timeout 1d;
    proxy_send_timeout 1d;
    proxy_read_timeout 1d;
  }

  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Real-IP		$remote_addr;
    proxy_pass       http://192.168.1.11:4024;
    
    proxy_set_header Upgrade $http_upgrade;
    proxy_http_version 1.1;
    
    # Added by custom location
    client_max_body_size 50M;
    proxy_set_header Connection "";
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Frame-Options SAMEORIGIN;
    proxy_buffers 256 16k;
    proxy_buffer_size 16k;
    proxy_read_timeout 600s;
    proxy_cache_revalidate on;
    proxy_cache_min_uses 2;
    proxy_cache_use_stale timeout;
    proxy_cache_lock on;
  }

  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}
```

## Summary
Is there a way to get the websocket to work with nginx proxy manager docker container? In the [Docs](https://www.focalboard.com/download/personal-edition/ubuntu/#configure-nginx) is this nginx config... i tried to adjust as close as possible to this one, but had no success.
I'm wondering how to forward the incoming traffic to the `localhost:8000` described in the documentation since the Focalboard-Container is running on host `192.168.1.11` and port `4024`.

I'm willing to collaborate and test If there are needs for that.

Thanks for your attention and help.
Stay save!

**Comment by wuwinson** [comment]
cc @jespino @wiggin77 Any ideas on how to configure nginx for this?

**Comment by wiggin77** [comment]
> When i access the Focalboard from the internet, there are these Websocket errors. 

@frauseo can you provide the error logs. Also

**Comment by zhzy0077** [comment]
It works for me by simply checking the box "Websocket support":
![image](https://user-images.githubusercontent.com/8717471/172091503-57bd222b-ab59-42d2-901c-56315a66be1d.png)

Nginx Proxy Manager version: v2.9.16

**Comment by creightonfrance** [comment]
I just ran into the same issue: didn't have `Websockets Support` enabled in NGINX Proxy Manager and ran into odd behavior. I think this can be closed.
