### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by vbardelli** [mattermost/focalboard#2197]
## Steps to reproduce the behavior

1. Go to boards tab
2. Select to create a new card
3. Scroll down to ...
4. See error "no refresh in order to see the new card"

## Expected behavior

to see my new card in the board 

## Screenshots

If applicable, add screenshots to elaborate on the problem.

## Edition and Platform

 - Edition: Personal Desktop / Personal Server / Mattermost plugin
 - Version: [e.g. v0.9.0]
 - Browser and OS: [e.g. Chrome 91 on macOS, Edge 93 on Windows]

**Comment by chenilim** [comment]
Thanks @vbardelli, could you provide a screenshot or more info? i.e. is there an error message, or did you mean the new card does not appear until after a refresh?

Please also specify the version and edition being used. Thanks.

**Comment by vbardelli** [comment]
Sorry for the late on my answer.

See the two attached screenshots:

- before the view>reload

- after view>reload

I use mattermost in gitlab omnibus:

- you can see version of focalboard in the screenshots (0.11.0 BETA);

- client for linux (lxle) version 5.0.2;

- mattermost version 6.2.1;

Regards, Valerio

**Comment by RillonDodgers** [comment]
How did you get focalboard to work with gitlab omnibus @vbardelli? I cant get a board to show up after clicking on the icon next to the playbook buttons.

**Comment by wuwinson** [comment]
@vbardelli Sorry we can't see the screenshots. Do you mind re-attaching them? Thanks!

@RillonDodgers Can you add more details and screenshots of your issue? May need to file a separate ticket for yours. Thanks!

**Comment by vbardelli** [comment]
Chose a channel, click on the button with "target", at the right of the 
header, then I click on the "+" in the left panel, just at the side of 
the channel name, then I reach board templates.

Valerio

**Comment by vbardelli** [comment]
before


after

**Comment by chenilim** [comment]
From the description, our best guess is this is a repro of the [refresh bug in v6.2 and older](https://github.com/mattermost/focalboard/discussions/1971). Please upgrade to Mattermost 6.3+ or try the workaround steps in the linked discussion, and reopen if those don't work. Thanks!
