### ISSUE TITLE
Bug: Focalboard give feedback link turns purple after being clicked

### ISSUE THREAD

**Issue by tjbortz1s** [mattermost/focalboard#2212]
## Steps to reproduce the behavior

1. Click the Give Feedback link
2. on return to the focalboard screen the link appears purple.

## Expected behavior

The link remains the same color

## Screenshots

![image](https://user-images.githubusercontent.com/6193065/152045427-c0451359-c423-4f9d-b990-99b8c350d710.png)

## Edition and Platform

 - Edition: Windows 0.12.1

**Comment by wuwinson** [comment]
@asaadmahmood What color should this be after the link is clicked?

**Comment by ogi-m** [comment]
Tested and passed on v0.15 RC2
