### ISSUE TITLE
Bug: Focalboard drag-drop-hold-scroll only kicks in when cursor is at the top of the group names and not the group list

### ISSUE THREAD

**Issue by tjbortz1s** [mattermost/focalboard#2214]
## Steps to reproduce the behavior

1. Start dragging a card
2. Move the car up near the top of the region cards can be dropped in.
3. When the cursor is below the group header titles the list of tasks does not scroll up.
4.  When the cursor approaches the top of the group header titles the list of tasks does scroll up.

## Expected behavior

The scrolling area starts to scroll when the mouse is at the top of the visible scrolling area.

## Screenshots

![image](https://user-images.githubusercontent.com/6193065/152058738-a642be91-412a-41ed-b4f2-6a5f061b3349.png)
Scrolls at the check, does not scroll at the X

## Edition and Platform

 - Edition: Windows 0.12.1

**Comment by wuwinson** [comment]
Retested in our Feb bugbash server v0.14RC1 and it appears fixed.
