### ISSUE TITLE
Bug: X Window error: 'BadValue (integer parameter out of range for operation)'

### ISSUE THREAD

**Issue by tennox** [mattermost/focalboard#2215]
## Steps to reproduce the behavior

1. Download linux build
2. Create a board from e.g. personal tasks template
3. open a board item / card
4. app hangs / screen goes blank

## Screenshots
![focalboard crash](https://user-images.githubusercontent.com/2084639/152067679-00f087cd-abdc-4a20-be35-81d0e5ace98d.gif)

## Edition and Platform

 - Edition: Personal Desktop
 - Version: v0.12.1
 - Browser and OS: elementary OS 5.1.7 Hera (Ubuntu)

## Additional context

Also set the Severity using the labels as best you can:
* Sev/1: Issue affects critical functionality without a workaround

**Comment by chenilim** [comment]
@ogi-m, does this repro for you (v0.12 and v0.14)? cc @jespino - appears to be a blocking issue on the Linux app.

**Comment by tennox** [comment]
Hm :thinking: I can't reproduce it anymore. Sorry, no idea what I changed (did a lot of OS changes the last days).

Unless I or someone else encounteres this again I'd proclaim:
/close

**Comment by Moilleadoir** [comment]
I have this same issue.  Was using v. 0.6 a while back and tried 0.12.1 yesterday.  Crashes/freezes as soon as you try to look at a card.

Just tried 0.14.0 with same result.

Manjaro Linux
Cinnamon Desktop
