### ISSUE TITLE
Bug: Template selector > Elements in the preview highlight on hover

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#2236]
## Steps to reproduce the behavior

1. Open the template selector
2. Select "Welcome to Boards"
3. Move the mouse over the bottom half of the table in the preview
4. Note the cards highlight

## Expected behavior

Elements in the preview shouldn't interact on mouse-over

## Screenshots

https://user-images.githubusercontent.com/15314183/152343735-5a9c671d-facb-4147-8c54-e5f3535048a7.mp4

## Edition and Platform

 - Version: v0.14 RC1
 - Browser and OS: Chrome on Windows

**Comment by chenilim** [comment]
The calendar view cells also highlight on hover (e.g. Roadmap template), and it appears you can click on the '+' button (though nothing happens). This only seems to affect the bottom half of the preview, as if there's an invisible div that only covers the top half.
