### ISSUE TITLE
Bug: Template selector > Buttons overlap with the template preview

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#2237]
## Steps to reproduce the behavior

1. Open the template selector
2. Select "Welcome to Boards" or "Roadmap" template
3. Note the button overlap with the preview

## Expected behavior

The buttons should not overlap

## Screenshots

![SharedScreenshot](https://user-images.githubusercontent.com/15314183/152344259-524abba8-fa93-4b86-b0de-ae0abec75ff7.jpg)

## Edition and Platform

 - Version: v0.14 RC1
 - Browser and OS: Chrome on Windows

**Comment by asaadmahmood** [comment]
This is as expected, not a bug.
