### ISSUE TITLE
Bug: Template picker sidebar width changes when hovering over certain templates

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2240]
## Steps to reproduce the behavior

1. Open the template picker (add new board)
2. Hover over custom templates with long titles
3. Width of sidebar changes

## Expected behavior

Width should not change - propose that title is truncated and icons appear on the right.

## Screenshots

https://user-images.githubusercontent.com/46905241/152403385-71aafb0b-6551-482f-90e7-0899b9b827fc.mov

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.14.0 RC1
 - Browser and OS: Chrome on macOS

**Comment by chenilim** [comment]
@asaadmahmood - what should the behavior be here? Propose that title is truncated and icons appear on the right. cc @wuwinson.

**Comment by asaadmahmood** [comment]
@chenilim Yup, I Think I actually did that, but maybe for some reason it didn't work.

**Comment by ogi-m** [comment]
Dupe of https://github.com/mattermost/focalboard/issues/2240
