### ISSUE TITLE
Bug: Confirmation modal to delete a template is not centered 

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2243]
## Steps to reproduce the behavior

1. Go to new template picker and delete a custom template
2. See error

## Expected behavior
Confirmation modal is centered to the page

## Screenshots

![Confirmation Msg Not Centered](https://user-images.githubusercontent.com/93531870/152406502-e750ef3d-2b1c-44c3-b0c7-7e3b39e90e7f.png)

## Edition and Platform

- Edition: Mattermost plugin
- Version: v0.14.0 RC1
- Browser and OS: Chrome on macOS

**Comment by chenilim** [comment]
Please fix if easy, but not a priority for 0.14.
