### ISSUE TITLE
Bug: Images not appearing for cards created from default template

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#2244]
## Steps to reproduce the behavior

1. Create channel & click FB icon
2. Select  a default template containing an image e.g. `Welcome to Boards`
3. Open card that should have an image e.g. `@mention teammates`

## Expected behavior

Image should appear in card.

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.14 RC
 - Browser and OS: FF 93 Linux

## Additional context

This error is appearing in log:
```json
{
"timestamp": "2022-02-03 18:26:29.939 Z",
"level": "error",
"msg": "API ERROR",
"caller": "app/plugin_api.go:931",
"plugin_id": "focalboard",
"code": "500",
"error": "\"unable to copy file from 4k47wuad37rjprarhxwxdk4jbh/hq5sn6ru5bbuzertkmb74j76ey/b1dgqnsx8pj8q7n5frewmzifiiw/7ek6wbpp19jfoujs1goh6kttbby.gif to 4k47wuad37rjprarhxwxdk4jbh/hq5sn6ru5bbuzertkmb74j76ey/bnyck66mk5jngdea5iyzoaeaoyr/7ek6wbpp19jfoujs1goh6kttbby.gif: The specified key does not exist.\"",
"_msg": "",
"api": "/api/v1/workspaces/hq5sn6ru5bbuzertkmb74j76ey/blocks"
} 
```

**Comment by chenilim** [comment]
Doug confirmed that the images are in the default template. Please investigate.
