### ISSUE TITLE
Bug: Unable to delete or edit custom templates in Personal Desktop

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2245]
## Steps to reproduce the behavior

1. Create a new Board template in Personal Desktop (Mac)
2. Try to delete it from the template picker (new board UI)
3. Delete and edit buttons don't appear on hover

## Expected behavior

Able to delete and edit custom templates

## Screenshots

<img width="277" alt="Screen Shot 2022-02-03 at 10 43 14 AM" src="https://user-images.githubusercontent.com/46905241/152408365-ac7e922f-132f-4b7c-afee-cd65fe553ac3.png">

## Edition and Platform

 - Edition: Personal Desktop
 - Version: v0.14.0
 - Browser and OS: macOS

**Comment by ogi-m** [comment]
This is fixed by https://github.com/mattermost/focalboard/pull/2221#pullrequestreview-875320189, but I'm now seeing a new issue on Personal Desktop:

https://github.com/mattermost/focalboard/issues/2282
