### ISSUE TITLE
Bug: "Create Empty Board" button has a transparent background

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2249]
## Steps to reproduce the behavior

1. Select "+ Add Board"
2. Select the Roadmap template
3. The background appears on the "Create empty board" button

## Expected behavior

The button background should be opaque.

## Screenshots

<img width="956" alt="Screen Shot 2022-02-03 at 12 42 13 PM" src="https://user-images.githubusercontent.com/46905241/152425578-a5192f9e-1572-4c9d-b452-224be2727908.png">

## Edition and Platform

 - Edition: Personal Desktop and Mattermost plugin
 - Version: v0.14.0 RC1
 - Browser and OS: Safari Mac and Mac + Win Personal Desktop

## Additional context

This may cause the button to be hard to read.

**Comment by chenilim** [comment]
@asaadmahmood / @jespino / @ogi-m, not sure if this is already tracked, but I think we should fix it if easy.

**Comment by asaadmahmood** [comment]
It's easy @chenilim

**Comment by chenilim** [comment]
Thanks @asaadmahmood. Assigning to you to fix. Please reassign if needed. Thanks. cc @wuwinson, @sbishel.

**Comment by chenilim** [comment]
Are you on track to fix this for v0.14 @asaadmahmood? Thanks.

**Comment by asaadmahmood** [comment]
@chenilim PR submitted:
https://github.com/mattermost/focalboard/pull/2279
