### ISSUE TITLE
Bug: Should not be able to follow a card template

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2250]
## Steps to reproduce the behavior

1. Open a card
2. Select "New template from card" from the ... menu
3. There's a follow button in the template editor

## Expected behavior

Should not show a follow button in the template editor

## Screenshots

<img width="1005" alt="Screen Shot 2022-02-03 at 12 50 26 PM" src="https://user-images.githubusercontent.com/46905241/152426675-8ee151de-aa00-4075-b4df-f865cffb7d52.png">

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.14.0 RC1
 - Browser and OS: Safari on Mac

## Additional context

Not sure what "following" a template will do. But expect not to be able to follow a template, nor to ever receive notifications on template changes.

**Comment by chenilim** [comment]
@wuwinson and @asaadmahmood - do you agree we should not show the Follow button for templates? cc @wiggin77.

**Comment by wiggin77** [comment]
> @wuwinson and @asaadmahmood - do you agree we should not show the Follow button for templates? cc @wiggin77.

I agree.

**Comment by asaadmahmood** [comment]
@wiggin77 Agreed.

**Comment by wuwinson** [comment]
Agree as well.
