### ISSUE TITLE
Bug: AWS Desktop App - Not able to create a board

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#2270]
## Steps to reproduce the behavior

Reproduces in Rainforest on macOS and Win10 and locally in Win10 (I don't have a mac)

1. Download the desktop app from either of these links, install and add the community server:
    - macOS : https://mattermost-desktop-daily-builds.s3.amazonaws.com/macos/mattermost-desktop-daily-develop-mac-universal.dmg
    - Win10 : https://mattermost-desktop-daily-builds.s3.amazonaws.com/win/mattermost-desktop-setup-daily-develop-win.exe 
2. Click on the grid icon, select Boards then click on the Explore button (or click on the Boards tab in the top tabs bar)
3. Click on one of the channels or click on the Dashboard drop-down and select a channel
4. Observed:  Nothing happens

## Expected behavior

Boards template screen is displayed (or a list of boards options to select from).  

## Screenshots

![image](https://user-images.githubusercontent.com/13020833/152745206-8a7120e3-f6a2-4d47-8598-178589238ea5.png)

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: plugin v0.12.1
 - Browser and OS: Mattermost Desktop AWS build macOS/Catalina Win10/Chrome

## Additional context

I'm not sure whether this is a Boards or Desktop App issue

Severity:
* Sev/2: Issue affects major functionality with a difficult or non-obvious workaround
  - Clicking on the Boards icon from within a channel does open the Boards template selection screen.

**Comment by wuwinson** [comment]
@devinbinnie Can you take a look into this? Looks like it might be related to the desktop build. Thanks! cc @sbishel @chenilim

**Comment by harshilsharma63** [comment]
I can confirm that this works fine on the latest official Mac desktop app available at https://mattermost.com/download/

**Comment by devinbinnie** [comment]
@wuwinson Submitted a fix for the above issue. Please note that the original issue that caused this will still need some works from the Boards team to accommodate the changes.

**Comment by wuwinson** [comment]
Thanks @devinbinnie!
