### ISSUE TITLE
Bug: Clean up log files after a plugin crashes.

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#2277]
## Steps to reproduce the behavior

1. Go to local Focalboard plugin and login.
2. Disable mattermost plugin. 
3. Client will be redirected to Error Page.

## Expected behavior

When a plugin crashes, there are "false-positive" error logs - we should clean these up

See https://github.com/mattermost/focalboard/issues/1903 for more details.

**Comment by wiggin77** [comment]
The logs referenced in the linked issue are generated by the MM server's plugin layer.  The server cannot communicate with the plugin, because it crashed, and is reporting those errors.  Removing those log entries would remove them for crashes and communication errors for all plugins.
