### ISSUE TITLE
Bug: Unable to add/view a description for boards

### ISSUE THREAD

**Issue by amyblais** [mattermost/focalboard#2281]
For example, in the Product Management channel, there is a board for PM meeting agenda. https://community-daily.mattermost.com/boards/workspace/xu5h1df38bf35jtmskz6z53qno/caff565e-3172-467f-89fd-6670cfdd454c/e678f17f-bb3e-443e-8a08-17b76ae13390.
<img width="605" alt="Screenshot at Feb 07 15-27-54" src="https://user-images.githubusercontent.com/29708087/152866581-8d0bdd7a-ee44-4ef2-9f93-af66ecdf04ee.png">

I'm no longer able to add or see the description of the board on community-daily (the description included key upcoming release dates and a few other items). This issue happens on other boards too.

**Comment by chenilim** [comment]
Thanks @amyblais! I was able to show the description by hovering above the title and selecting "Show description". Does this work for you?

<img width="441" alt="Screen Shot 2022-02-07 at 3 00 07 PM" src="https://user-images.githubusercontent.com/46905241/152886662-2af8b2f6-d9ec-4034-af5d-ee140f399f0b.png">

**Comment by amyblais** [comment]
Thanks! I didn't see that button until I hovered above the title.
