### ISSUE TITLE
Feature Idea: default using specfic template to create new item when click new button

### ISSUE THREAD

**Issue by grsky360** [mattermost/focalboard#229]
**Summary:**
I think a default setting in template edit page will be useful
User can create new note and fill some default properties without manually fill it every time, and don't need click select button every time

For development:
using default setting, `addCard` and `addCardTemplate` can be merged and while no default template, will using the internal empty one as a template card. Then I think it will simplify the code in somewhere and has a consistent abstraction.

Development implementation plan:
In `ViewHeader`, it can use default template directly.
In `BoardTree`, it can use default template, and replace specific property or not.
If using the `Filter`, it can use above solutions, then replace specific properties by filter configuration.

If necessary, I can also help to develop it.

**How important this is to me and why:**

Importance: Medium

**Additional context / similar features:**
![image](https://user-images.githubusercontent.com/13222125/113496526-1bf46300-952d-11eb-8a91-6d9863182701.png)

**Comment by chenilim** [comment]
Thanks @grsky360! Just catching up on issues. I think this could be implemented with a "default card template" setting on the board.
* Add a "is default template" indicator to the card template dropdown
* Add a "set as default" action on templates, including "Empty card", which is current default

Clicking New would create a card using the default template, or an empty card if there is none.

Putting this up for grabs if you are still interested in taking a crack at it.

**Comment by grsky360** [comment]
@chenilim I'd like to help for this. But maybe need many times because I'm a little busy

**Comment by chenilim** [comment]
Thanks @grsky360! You got it. Here's a "spec" for how I think this could work:
* Add a default template property to the View object (stores the block ID of the template as a string)
* Show the default template in the template dropdown (New button dropdown)
  * Use a checkmark icon for now (we can refine the icon later)
* Add a "Set as default" option to the template options ("...") sub-menu item
  * Also add this to the "Empty card" option - which will remove the default template property value
* Clicking New will use the default template, if one is set, and an empty card if not

LMK if you have any questions or would like more details. Thanks!

**Comment by grsky360** [comment]
@chenilim Just submit a first version PR, I didn't apply some code style for now.
This version is only a first version that is working for using, you could review it and give some suggestions to improve the code and meet your specs

**Comment by grsky360** [comment]
Thanks everyone, this PR has been merged.!
