### ISSUE TITLE
Bug: Template selector > Edit & Delete button icon alignment is off

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#2305]
## Steps to reproduce the behavior

1. Go to the template selector
2. Hover over a custom template
3. Note the icon alignment for Edit and Delete buttons is off

## Expected behavior

Icons should be aligned

## Screenshots

![Screenshot (169)](https://user-images.githubusercontent.com/15314183/153270071-646a3a30-5b91-40bb-a765-3efea08e2142.png)

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.14.0-rc1
 - Browser and OS: Chrome on Windows

**Comment by asaadmahmood** [comment]
This should be fixed on main.
