### ISSUE TITLE
Bug: Errors in browser console when using certain board templates

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2307]
## Steps to reproduce the behavior

1. Open the browser console (Cmd+Opt+I in Chrome)
2. Create a board from the "Welcome to Boards" template
3. See errors:
```
groupCardsByOptions: Missing option with id: aqb5x3pt87dcc9stbk4ofodrpoy
groupCardsByOptions: Missing option with id: a1mtm777bkagq3iuu7xo9b13qfr
groupCardsByOptions: Missing option with id: auxbwzptiqzkii5r61uz3ndsy1r
groupCardsByOptions: Missing option with id: aj9386k1bx8qwmepeuxg3b7z4pw
```

Similar errors for other templates (Content Calendar, Meeting Agenda, and maybe others).

## Expected behavior

No errors in the console.

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.14 RC3
 - Browser and OS: Chrome on Mac

## Additional context

The errors may also show when just selecting the template in the preview

**Comment by chenilim** [comment]
@wiggin77, this might indicate an issue with some of the template archives. I don't think it's a priority for 0.14, but might be worth a quick look to make sure there are no unintended impacts. cc @wuwinson.

**Comment by wiggin77** [comment]
I'm not seeing these errors in my console.  Is this still happening for anyone else?  @chenilim @wuwinson

**Comment by wuwinson** [comment]
Thanks for checking @wiggin77! Still seeing the errors on my console - Chrome on Mac on the latest bug bash server.

https://user-images.githubusercontent.com/93531870/184698491-7cb769c0-51dd-47e5-a87c-38db7ebdbdf3.mov

**Comment by wiggin77** [comment]
@wuwinson since we have decided to not clean-up orphaned blocks or properties on community I would like to close this as `won't fix`.

**Comment by wuwinson** [comment]
Sounds good! Closing out as `Won't fix`.
