### ISSUE TITLE
Bug: Template Selector > Edit and Delete buttons not visible on Personal Server

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#2308]
## Steps to reproduce the behavior

1. Go to the template selector
2. Select "+New Template"
3. Create a custom template
4. Return to template selector
5. Move the cursor over the template title - Edit and Delete buttons don't show up

## Expected behavior

Edit and Delete buttons should be visible

## Screenshots

![SharedScreenshot](https://user-images.githubusercontent.com/15314183/153306998-93794bd9-b0dc-4665-9259-ca4c3de652c6.jpg)

## Edition and Platform

 - Edition: Personal Server
 - Version: v0.15
 - Browser and OS: Chrome on Windows

**Comment by chenilim** [comment]
Is this on 0.14 RC3? Does this also repro on Personal Desktop? If so, it might be a dup of https://github.com/mattermost/focalboard/issues/2245, which was marked fixed.

**Comment by chenilim** [comment]
Just tried this, and it doesn't repro on Personal Desktop Mac with 0.14 RC3. So, this might be Personal Server only - which is unusual. cc @jespino.

**Comment by ogi-m** [comment]
Can't repro anymore.
