### ISSUE TITLE
Feature Idea: Improve the docker file to specify the DB connection at container creation

### ISSUE THREAD

**Issue by romu70** [mattermost/focalboard#231]
**Summary:**
The idea is to modify/improve the Docker file to be able to specify the DB settings without having to tweak the container at runtime.

**How important this is to me and why:**
It's important for people like me who run a server with a centralized DB to host all of their data. Being able to do this simplifies the server setup and keeps the server resources as lean as possible.

Importance: High

Use cases:
1. Already described.

**Additional context / similar features:**
A lot of open source projects allow to pass the DB settings at container creation.

This could be something like:
docker run --name focalboard -d -e DATABASE='postgres://boardsuser:boardsuser-password@focalboard-db/boards?sslmode=disable&connect_timeout=10' -p 80:8080 --restart always focalboard

**Comment by zacheryph** [comment]
#227 should take care of this.

**Comment by romu70** [comment]
#That is... when a new image is created that contains it.

The most simple solution would be to get this out the image itself and being able to set the DB connection at "docker run...". Like a lot of other containerized software.

**Comment by romu70** [comment]
> That is... when a new image is created that contains it.

Thanks. But the most simple solution would be to get this out the image itself and being able to set the DB connection at "docker run...". Like a lot of other containerized software.

**Comment by zacheryph** [comment]
correct... that PR lets you define the configuration (including the database url) using environment variables. Thus letting you use something along the lines of `docker run ... -e FOCALBOARD_DATABASE=...`. Is that not what you are asking for?

**Comment by romu70** [comment]
It is 100% what I'm waiting for. So let's wait for a new image. Thanks, I close this ticket.
