### ISSUE TITLE
Bug: Card sort on selected board differs from the template

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2311]
## Steps to reproduce the behavior

1. Go to template picker
2. Click on the Welcome board  
3. See the sort order of the cards in the preview
4. Click on "Use this template" button
5. View the sort order of the cards in the Welcome board
6. Occurs on other standard templates as well.

## Expected behavior

Cards should display in the same order as the template preview, but are displaying in alphabetical order instead.

#### Compare the card sort order from the template vs the board that was loaded.
![Welcome Template](https://user-images.githubusercontent.com/93531870/153439464-443c31af-8d35-4969-870e-88d8f75a6449.png)
![Welcome Board](https://user-images.githubusercontent.com/93531870/153439479-1e616bc5-5b8b-41a6-afdd-700573b2b46f.png)

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.14 RC3
 - Browser and OS: Chrome on macOS

## Additional context
* Sev/3: Issue affects minor, non-critical functionality

**Comment by chenilim** [comment]
Should be fixed by #2345.
