### ISSUE TITLE
Mentioning in Boards Plugin doesn´t work properly

### ISSUE THREAD

**Issue by Chr1st14n-LL** [mattermost/focalboard#2316]
Summary

If i try to mention a user with "@user" on a card the notification doesn´t arrive.

Steps to reproduce

OnPremise Server Debian 9, Mattermost Server 6.3.2 , Client 5.0.2 + 5.0.3

Mentioning in the Channel is working. But not in Boards. Users are both in one Team and the same Channel.

Observed behavior (that appears unintentional)

{"timestamp":"2022-02-10 15:57:50.332 +01:00","level":"error","msg":"Error delivering notification","caller":"app/plugin_api.go:928","plugin_id":"focalboard","backend":"notifyMentions","action":"add","block_id":"ab3tbq8ymd78ndxwpxkp8qfyk8h","error":""MError:\ncannot deliver notification for @testuser: cannot get direct channel: createDirectChannel: A direct channel cannot be created between these users because they do not share a team in common., \n1 errors total.\n""}

**Comment by chenilim** [comment]
Thanks @Chr1st14n-LL! This looks like a dup of https://github.com/mattermost/focalboard/issues/2123. Do the suggested steps there work for you? i.e.:
> Can you confirm the Boards bot account is a member of the team. It should be automatically created unless a setting is preventing that.

cc @wiggin77 - should we / can we make code changes on our end to prevent more users encountering this? Also, what specifically should we document in the meantime? Thanks. cc @wuwinson.

**Comment by wiggin77** [comment]
> cc @wiggin77 - should we / can we make code changes on our end to prevent more users encountering this? Also, what specifically should we document in the meantime? Thanks. cc @wuwinson.

We do programmatically create the bot account.  That's why it works for our test environments without having to manually create the account.  However, people who have reported this seem to have Bots disabled.  When the bot creation fails it does put an error in the logs.  We may need to highlight that bots must be enabled in docs/release notes.  We could also have a error message displayed in webapp, but that will appear for everybody and would become annoying if they really want bots disabled.

**Comment by Chr1st14n-LL** [comment]
Hey guys, sorry for not finding #2123 ...the solution worked for me either. Thanks. 

FYI... my Bot Accounts where already enabled but the Bot was not a Member of the Team. Maybe it helps you to know that sometimes a notification came with 3-5 min. delay. Maybe 1 of 10 attempts. Also it looked a bit different as now:

yesterday....Bot enabled but not Member of the Team....3-5 min. delay
![grafik](https://user-images.githubusercontent.com/99415300/153637882-ae4c2c85-a82c-4ae1-859d-56f53842b1c2.png)

Now....Bot enabled and Member of the Team.....delivered in realtime
![grafik](https://user-images.githubusercontent.com/99415300/153638191-de6acd26-84c5-46f3-91e7-210b17fedfdf.png)

Thanks again.

**Comment by chenilim** [comment]
I've posted the workaround steps as a discussion here: https://github.com/mattermost/focalboard/discussions/2415. Please LMK if those steps need to be adjusted.

Closing this issue for now, but please re-open, create a new issue, or chime in the discussion if anyone is still running into this. The workaround steps *should* not be required, and we still need to figure out why notifications aren't working out-of-the-box for everyone. cc @wuwinson, @sbishel.

**Comment by wiggin77** [comment]
Based on the conversation here https://community.mattermost.com/core/pl/cwppbn1kufrnpqbcuba1cric8e it looks like a code fix is indeed required.  I am assigning to myself.

**Comment by wiggin77** [comment]
Fixed via https://github.com/mattermost/mattermost-server/pull/19713
