### ISSUE TITLE
Doc: Assign to person - no option

### ISSUE THREAD

**Issue by asad-awadia** [mattermost/focalboard#2327]
## Summary

How do I add a person property to a card?

There is no way to type anything or add anything here

<img width="477" alt="focalboard" src="https://user-images.githubusercontent.com/6923282/153774059-991b9565-d5f1-42dd-8350-2914a0274798.png">

**Comment by asad-awadia** [comment]
@chenilim

**Comment by wuwinson** [comment]
@asad-awadia Person property is only available with Personal Server and Plugin Boards. @justinegeffen Can we please update the docs to reflect this?

https://www.focalboard.com/guide/user/#editing-cards

**Comment by asad-awadia** [comment]
@wuwinson wdym personal server? Like self hosted?

**Comment by justinegeffen** [comment]
Thanks, @wuwinson, I've added a note to the docs for this. @asad-awadia, the personal server version is a single-user, standalone, app. The Focalboard [landing page](https://www.focalboard.com/) has a good explanation of what @wuwinson has mentioned.

**Comment by wuwinson** [comment]
Thanks @justinegeffen! Just to clarify @asad-awadia, the [Personal Desktop edition](https://www.focalboard.com/download/personal-edition/desktop/) only supports a single user, so no users appear on the person property.

Our [Personal Server](https://www.focalboard.com/download/personal-edition/ubuntu/) and [Mattermost Boards Plugin](https://www.focalboard.com/download/mattermost/latest-plugin/) both support multiple users, where you'll be able to properly user the `PERSON` property.

**Comment by asad-awadia** [comment]
@wuwinson Ok I get it

I just tried running via docker and can add assignee - which is great!

But why can I only filter by status and priority?

**Comment by asad-awadia** [comment]
Reports is not a feature yet right?

**Comment by wuwinson** [comment]
@asad-awadia Thanks again for your feedback! We've updated the docs to clarify the `PERSON` property in Personal Desktop. The changes will be published to [this section](https://docs.mattermost.com/boards/work-with-cards.html#work-with-property-types) in our Help Docs soon. We're also discussing options on making this experience clearer via some kind of messaging within the Focalboard app.

Our groups and filters currently only support the `SELECT` property type. Our goal is to eventually support grouping and filtering by all property types, including the `PERSON` property. See https://github.com/mattermost/focalboard/issues/1732 for more details.

Reports is not a feature yet, but [Calculations](https://docs.mattermost.com/boards/work-with-cards.html#calculations) can be used in the meantime to address some basic metric questions.

Closing out this ticket, but please feel free to file a new ticket or message us on our [Mattermost Community Channel](https://community.mattermost.com/core/channels/focalboard) if you have any questions!
