### ISSUE TITLE
Bug: Modal window doesn't have background color

### ISSUE THREAD

**Issue by mgoldchild** [mattermost/focalboard#2328]
## Steps to reproduce the behavior

1. Go to Calendar View (month mode)
2. Create multiple items at the same day
3. Click more button
4. See the error following

## Expected behavior

Background is not transparent. 

## Screenshots

![Screenshot_20220214_163830](https://user-images.githubusercontent.com/8959761/153821411-36533a9a-764b-4fae-9a2c-38f0c52fda78.png)

## Edition and Platform

 - Edition: Personal Desktop / Mattermost plugin
 - Version: v0.12.1
 - Browser and OS: Manjaro Linux KDE

**Comment by sbishel** [comment]
I could not duplicate with v0.14.0, nor the main branch. @mgoldchild, please reopen if you see it once v0.14 is released this week.
