### ISSUE TITLE
Bug: Double vertical scroll bar, and no horizontal scroll bar

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2329]
## Steps to reproduce the behavior

1. Open a large board (e.g. our team features by release)
2. Notice double vertical scroll bars, and no horizontal scroll bar

## Expected behavior

Should be one vertical and one horizontal scroll bar (if needed).

## Screenshots

<img width="1514" alt="double scroll" src="https://user-images.githubusercontent.com/46905241/153910052-61ad4ae9-a6dd-43d5-a4ef-485ea2b6131a.png">

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.14.0
 - Browser and OS: Chrome on Mac

## Additional context

Horizontal scrolling is painfully difficult without a scrollbar.

**Comment by wuwinson** [comment]
Looks fixed on community-daily. Closing out.
