### ISSUE TITLE
Bug: Crash with the Docker container

### ISSUE THREAD

**Issue by romu70** [mattermost/focalboard#233]
**Summary:**
My Focalboard container stops as soon as I reach the first screen.

I've been able to create my account and I can check my user account data have been created as expected in my Postgres 13 container.

The last message in the log this one:

> 2021/04/05 12:54:39 websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header

**Steps to reproduce the behavior:**
1. Open your focalboard session

**Expected behavior:**
It should work.

**Screenshots:**
This is all I get, and then, my container is gone.

<img width="1429" alt="Screenshot 2021-04-05 at 15 07 28" src="https://user-images.githubusercontent.com/1898319/113576924-b5e90800-9620-11eb-945d-d64bf9ab7ce4.png">

**Platform:**
- Server: A Docker container hosted on a Synology nas
- Data: Hosted on a Postgres 13 separated container. 
 - Firefox 87
 - macOS 11.2.3

**Additional context:**

**Comment by rajudev** [comment]
I am enquiring the similar bug. 
After deploying focalboard using docker-compose, create account, login. 
The moment I click on `Invite Users` the container exits. 

Here are container logs
 
![2021-04-19_07-59](https://user-images.githubusercontent.com/2010120/115173590-3f9ada00-a0e5-11eb-88cd-901fe784134e.png)

**Comment by chenilim** [comment]
Thanks @romu70 and @rajudev! Which Dockerfile did you use? I just ran the following against our [Dockerhub image](https://hub.docker.com/r/mattermost/focalboard) and it should work: `docker run -it -p 80:8000 mattermost/focalboard`, then open http://localhost. LMK if it doesn't for you.

The error message indicates that the upgrade header was not passed to the server correctly (triggering issue #112).

**Comment by romu70** [comment]
Here is what I did.

First, I tweaked the docker/config.json file to set my Postgres connection.

```
{
    "serverRoot": "http://localhost:8000",
    "port": 8000,
    "dbtype": "postgres",
    "dbconfig": "postgres://focalboard:blablabla@psql-ip:port/focalboard?sslmode=disable",
    "postgres_dbconfig": "dbname=boards sslmode=disable",
    "useSSL": false,
    "webpath": "./pack",
    "filespath": "./files",
    "telemetry": true,
    "session_expire_time": 2592000,
    "session_refresh_time": 18000,
    "localOnly": false,
    "enableLocalMode": true,
    "localModeSocketLocation": "/var/tmp/focalboard_local.socket"
}
```

Then, I tweaked a bit the docker-compose.yml:

```
version: "3"
services:
  app:
    build:
      context: ./
    container_name: focalboard
    ports: 
      - 4300:8000
    environment:
      - VIRTUAL_HOST=focalboard.local
      - VIRTUAL_PORT=8000
    volumes:
      - "./config.json:/opt/focalboard/config.json"
```
Personaly, I absolutely need Focalboard to use my Postgres instance.

**Comment by rajudev** [comment]
The config.json was already capable of using the configured postgres. Without any tweaking. 
If you change the password or db name, then you have to do it at config.json as well as the compose file. 

I am not sure of what you changed. I see that you explicitly mounted the config file, I am not sure, if that would have stopped the crash.

**Comment by romu70** [comment]
The only tweak I did in the config.json is to specify my connection string indeed, nothing more.

And I added the volume in the docker-compose.yml because it was not crystal clear to me how things are working together. So you say I can safely remove this line, right?

Ideally, I just want a dockerfile which supports to pass the DB connection string at container runtime.

**Comment by romu70** [comment]
I pulled all the repository, removed all my changes except my DB connection string in the config.json file, and no change. Focalboard constantly crashes.

**Comment by jespino** [comment]
I'll try to investigate this tomorrow (maybe not, but I'll try)

**Comment by jespino** [comment]
The server was crashing because there was a `log.Fatal` when somebody tried to connect to the websocket without websocket headers. It should be fixed now.

**Comment by romu70** [comment]
Great, thanks a lot, I can't wait for the next release.

But, could you please clarify what it means from a user point of view not having the websocket headers? Does this means that Docker Focalboard users miss some Focalboard features, for example?

Thanks.
