### ISSUE TITLE
Bug: Template preview buttons cropped on narrow windows

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2330]
## Steps to reproduce the behavior

1. Select "Add board" (+) button
2. Resize the window to be narrow
3. Buttons are cropped

## Expected behavior

Buttons should always be visible (re-arrange / layout if needed)

## Screenshots

<img width="763" alt="Narrow preview" src="https://user-images.githubusercontent.com/46905241/153910493-f6ff7768-4325-460e-9a7f-bce027ef6439.png">

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.14.0
 - Browser and OS: Chrome on Mac

## Additional context

Note: Buttons are also cropped in mobile (narrow) view.

**Comment by wuwinson** [comment]
@asaadmahmood Any thoughts on how to address this? Thanks!

**Comment by asaadmahmood** [comment]
@wuwinson We can stack the buttons vertically.
