### ISSUE TITLE
Bug: Board and view remain selected in sidebar when adding board

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2331]
## Steps to reproduce the behavior

1. Open a view in a board
2. Select "add board" (+) button
3. The view is still selected in the sidebar
4. Selecting the (selected) view does not return to it

## Expected behavior

Board and view is unselected when adding a board. Or, at a minimum, clicking on the selected view should return to it.

## Screenshots

<img width="689" alt="board selection" src="https://user-images.githubusercontent.com/46905241/153911288-698db870-e872-4290-b55e-e6f9e76f8fae.png">

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.14.0
 - Browser and OS: Chrome on Mac

## Additional context

Workaround is to select another view, then select the original view to return to it.

**Comment by chenilim** [comment]
Actually, clicking on the X at the top right will close the template selector, returning to the view. Maybe pressing Esc should close it too?

**Comment by wuwinson** [comment]
Clicking on the view or board should dismiss the dialog.

**Comment by sridhar02** [comment]
@wuwinson can I work on this ?

**Comment by chenilim** [comment]
You got it @sridhar02. Thanks!
