### ISSUE TITLE
Feature Idea: provide helm chart for kubernetes deploy

### ISSUE THREAD

**Issue by Hokwang** [mattermost/focalboard#234]
Hi,

**Summary:**
Users who can use docker container and want to use this production level may want helm chart for kubernetes cluster.

**How important this is to me and why:**
IMO, very important things are 
- config as code and user can handle by configmap
- HA setting using multiple replicas.
- easy install & easy twick using helm chart

I will try to use focalboard after this.

**Comment by JohannesKlauss** [comment]
+1 for a k8s helm chart.

**Comment by chenilim** [comment]
Thanks @Hokwang! Opening this up to any takers. My own experience with Helm charts is pretty limited, so even links to good examples of this would be helpful. Thanks!

**Comment by JohannesKlauss** [comment]
I'll give it a try.

**Comment by stafot** [comment]
I could grab this if no one else is already up to this.

**Comment by chenilim** [comment]
You got it @stafot. Thanks!

**Comment by Hokwang** [comment]
@stafot do you have any progress?

**Comment by stafot** [comment]
@Hokwang Yes, I achieved to raise a draft PR today, will review it myself and add some documentation and then we will go to our review cycles. I hope soon enough to be available for you. If you want to give it a try with the current draft you are also able to.

**Comment by Hokwang** [comment]
@stafot thanks! I will test!
