### ISSUE TITLE
Bug:  Drag and drop in Safari Mobile doesn‘t work

### ISSUE THREAD

**Issue by Giancrafter** [mattermost/focalboard#236]
**Summary:**
When you want to move something in your board on iOS in Safari, it simply won't let you

**Steps to reproduce the behavior:**
1. Try to drag an element

**Expected behavior:**
Element is draggable like on desktop

**Screenshots:**

**Platform:**
 - iOS 14.5, Safari

**Additional context:**

**Comment by jespino** [comment]
This should be fixed in the main branch thanks to the react-dnd-touch-backend :tada:
