### ISSUE TITLE
Bug: Docker Pull to Pi not working as expected

### ISSUE THREAD

**Issue by bryceprutsos** [mattermost/focalboard#2362]
## Steps to reproduce the behavior

When I pull the container it complains about the platform

sudo docker run -it -p 80:8000 mattermost/focalboard
Unable to find image 'mattermost/focalboard:latest' locally
latest: Pulling from mattermost/focalboard
ab2f6dae3b54: Pull complete
9411f38bb959: Pull complete
eb9742ac9792: Pull complete
6a7303af5bba: Pull complete
a7e665517a56: Pull complete
2fd5af10a00b: Pull complete
dbd56ebf8fda: Pull complete
847ba836d3eb: Pull complete
Digest: sha256:607467c70b717b86c5f6a0ff389768e91b1192de83cf14f32bb3852e38a48c31
Status: Downloaded newer image for mattermost/focalboard:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

## Expected behavior

Pull and run a docker container 

See above

If applicable, add screenshots to elaborate on the problem.

## Edition and Platform

 - Edition:  Personal Server 0.14.0
 - Version: V0.14.0
 - Browser and OS: N/A

## Additional context

Also set the Severity using the *Sev/1*, *Sev/2* or *Sev/3* labels as best you can:

*Sev/2* Issue affects major functionality with a difficult or non-obvious workaround

**Comment by chenilim** [comment]
Someone posted a link to a functional docker image for Raspberry Pi (ARM64) [here]https://github.com/mattermost/focalboard/issues/124#issuecomment-1020328897). Dup of https://github.com/mattermost/focalboard/issues/124
