### ISSUE TITLE
Permissions Branch - Users have access to custom templates that were previously created in private channels

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#2370]
## Steps to reproduce the behavior

After updating, custom templates that were created in workspaces tied to private channels become accessible to any user that's part of that same team to which that private channel/workspace belonged to. 

Is this expected?

## Edition and Platform

- permissions-feature-branch

**Comment by chenilim** [comment]
@wuwinson, please link to the updated spec when ready. Thanks.

**Comment by wuwinson** [comment]
@ogi-m @sbishel @chenilim I updated the [spec](https://docs.google.com/document/d/1HOnoB87WZojqplpB6XGbtKsLuqjG8h-8CbJpmWsRfM4/edit#bookmark=id.xx2zqweio32l) with details on how custom templates should behave. This ticket would be considered a bug. We'll need some additional designs to address custom templates. Can review together in our next weekly team meeting. cc @asaadmahmood

**Comment by harshilsharma63** [comment]
I'm working on this now.
