### ISSUE TITLE
Permissions branch: Share button is not final UI

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2376]
## Steps to reproduce the behavior

1. Open a board
2. There's a button labeled "Show Share Modal"

## Expected behavior

The button should be labeled "Share" and positioned at the right, per the [spec here](https://docs.google.com/document/d/1HOnoB87WZojqplpB6XGbtKsLuqjG8h-8CbJpmWsRfM4/edit#bookmark=id.655mvflwidvj).

## Screenshots

<img width="398" alt="Screen Shot 2022-02-22 at 3 50 15 PM" src="https://user-images.githubusercontent.com/46905241/155239367-783f182b-2339-4ac3-aa2b-60782aea2dbc.png">

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: permissions-feature-branch
 - Browser and OS: Chrome on Mac

**Comment by sbishel** [comment]
Fixed via https://github.com/mattermost/focalboard/pull/2536
