### ISSUE TITLE
Permissions branch: Unable to join / view board that is team accessible

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2380]
## Steps to reproduce the behavior

Set up two user accounts.

1. As user 1: Create a new board
2. Open the Share dialog and grant "Everyone at ___ Team" Editor access
3. Now log in as user 2
4. Select the "Find Boards" input in the sidebar
5. Type in the name of the board, and select it
6. Nothing happens

## Expected behavior

The board is added to the sidebar and opens

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: permissions-feature-branch
 - Browser and OS: Chrome on Mac

**Comment by chenilim** [comment]
Might be related / dup of #2371.

**Comment by chenilim** [comment]
Might be covered by #2371.

**Comment by jespino** [comment]
It should be fixed
