### ISSUE TITLE
Permissions branch: white space shown to left of sidebar

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2381]
## Steps to reproduce the behavior

1. Open Boards
2. There is a white gap to the left of the sidebar

## Expected behavior

No gap

## Screenshots

<img width="316" alt="Screen Shot 2022-02-22 at 4 08 32 PM" src="https://user-images.githubusercontent.com/46905241/155241113-687e217c-8c90-4c88-8a6d-fb8bcc0c6e4b.png">

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: permissions-feature-branch
 - Browser and OS: Chrome on Mac

## Additional context

This is probably where the team selector goes. But the team selector should not appear if there is only one team, and there should be no gap.

**Comment by wuwinson** [comment]
Repros on https://boards-permissions1.test.mattermost.cloud/ with 1 team.

**Comment by harshilsharma63** [comment]
Fixed by https://github.com/mattermost/mattermost-webapp/pull/9827 in mattermost webapp. Changes are already merged in and it works fine latest master of mattermost webapp.
