### ISSUE TITLE
Build: Generate separate plugin packages per platform

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2384]
## Summary

Per the [discussion at our dev meeting](https://community-daily.mattermost.com/boards/workspace/b1ni7nprjpfwpb566k1gk8z9nw/886d2280-e88e-4065-8c85-1b62578f192e/f30dcb19-a0e8-45d2-8768-a9489f6e7fe8/chyhtjswcoinuffs1d9tf8ht7zy), let's produce separate binaries for each platform, i.e.:

* plugin-linux-amd64
* plugin-linux-arm64
* plugin-darwin-amd64
* plugin-darwin-arm64
* plugin-windows-amd64.exe

This should be added to [prod-release](https://github.com/mattermost/focalboard/blob/main/.github/workflows/prod-release.yml) and [dev-release](https://github.com/mattermost/focalboard/blob/main/.github/workflows/dev-release.yml) as a separate parallel workflow.

## How important this is to me and why

Importance: High

The 100MB plugin size exceeds the server limit and blocks test deployments.

## Additional context/similar features

This is related to https://github.com/mattermost/focalboard/pull/2301, which is to update the makefile for local builds to generate single-OS packages.

**Comment by harshilsharma63** [comment]
This is no longer needed as we're running as a product now.
