### ISSUE TITLE
Bug: Comment link colors are not highlighted

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2387]
## Steps to reproduce the behavior

1. Open a card
2. Send a comment with a link, e.g. `This is [a link](https://github.com/mattermost/focalboard), and auto link: https://github.com/mattermost/focalboard`
3. The links are the same color as the text (but are highlighted on hover)

## Expected behavior

The links should appear in the "link color" (blue with the default theme) even without hover.

## Screenshots

https://user-images.githubusercontent.com/46905241/155393101-3d1ea94d-8751-4dc1-84a9-7ddce669411a.mov

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.14.0
 - Browser and OS: Chrome on Mac

## Notes:
Strangely, if you enter a comment, but press ESC instead of Send, the links appear correctly in that preview. But links in sent comments don't appear with the right color.

**Comment by kamre** [comment]
@chenilim @asaadmahmood looks like the reason is that css variable `--link-color-rgb` is [not set for the plugin](https://github.com/mattermost/focalboard/blob/1d5583ac7a9a1a63f52e87f3c7250d4833226eeb/webapp/src/theme.ts#L134).

**Comment by kamre** [comment]
Another thing that I have noticed from
> if you enter a comment, but press ESC instead of Send, the links appear correctly in that preview

is that for preview (when the message is not yet sent) the color of the link is set like `rgba(var(--link-color-rgb), 1)` and not just `var(--link-color-rgb)` like for the link in sent comment.

So changing the [expression for the color in main.scss](https://github.com/mattermost/focalboard/blob/1d5583ac7a9a1a63f52e87f3c7250d4833226eeb/webapp/src/styles/main.scss#L58) also fixes this issue.

**Comment by ogi-m** [comment]
Tested and passed on v0.15 RC2
