### ISSUE TITLE
Bug: Type label overflows out of column

### ISSUE THREAD

**Issue by coreyhulen** [mattermost/focalboard#239]
**Summary:**

**Steps to reproduce the behavior:**
1. create a type `ONE-ON-ONE`
2. View in table mode

**Expected behavior:**
Should not overflow the table cell

**Screenshots:**
![Screen Shot 2021-04-08 at 9 25 48 AM](https://user-images.githubusercontent.com/1431746/114053931-a0582600-984c-11eb-80de-188b7e4ffb13.png)

**Platform:**
 - Browser and version: Chrome
 - OS and version: Mac

**Comment by jespino** [comment]
I fixed it in my new drag and drop rewrite branch. Probably I'll merge it tomorrow morning because it looks working pretty well, and simplifies a lot adding new sortable things.

**Comment by jespino** [comment]
Merged into main branch
