### ISSUE TITLE
UX: Menus should not close when toggling switches

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2394]
## Steps to reproduce the behavior

1. Open a board view
2. Select the properties menu
3. Toggle a property
4. The menu closes

## Expected behavior

The menu should not close when toggling a switch in a menu.

## Screenshots

https://user-images.githubusercontent.com/46905241/155596475-50b3507b-5464-4c84-ba8f-6246f3000bc9.mov

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.14
 - Browser and OS: Chrome for Mac

**Comment by kamre** [comment]
Is this the same as #606?

**Comment by chenilim** [comment]
Thanks @kamre! I looked, but missed it. Yup, closing this as a dup of #606, which has more details.

Also putting #606 up for grabs. cc @wuwinson, @sbishel, @asaadmahmood.
