### ISSUE TITLE
Permissions branch: Existsing Boards Are Not Migrated Correctly

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#2398]
## Steps to reproduce the behavior

1. Install Boards 0.14 from the Github release page.
2. Create some boards and cards in a channel corresponding to DMs.
3. Upgrade to the build from `permissions-feature-branch`.
4. Open boards. Notice the boards corresponding to DMs don't show up.
6. Open the database and query the `team_id` column in the `focalboard_boards` table. Notice how it's all empty for boards belonging to DMs.

## Expected behavior

Existing boards should be associated with a team and show up in UI after the upgrade.

## Edition and Platform

 - Edition:  Mattermost plugin
 - Version: `permissions-feature-branch` on commit `17931a5311e05ba9181bfab54454c4a4bff89e52`.
 - Browser and OS: Firefox.

## Additional context

 - Mattermost version: latest `master`
 - Database: MySQL 8

**Comment by jespino** [comment]
@harshilsharma63 if I remember correctly, you are taking care of this, right?

**Comment by harshilsharma63** [comment]
> @harshilsharma63 if I remember correctly, you are taking care of this, right?

Yes, now that I'm done with supporting upgrades from old versions, I'm starting on this today.

**Comment by harshilsharma63** [comment]
@chenilim in response to https://github.com/mattermost/focalboard/issues/2469#issuecomment-1067322678

1. For boards belonging to DMs, we'll migrate those boards to the first team where both members of the DM are part. If no such team exists, we'll migrate the boards to the first team of the DM creator. In the latter case, the other person will lose access to the board.

2. For direct group messages, we'll migrate the boards to the team where most members of the group message are a member. If multiple such teams exist, we'll pick the first one. Some users may lose access to the board.

The new APIs absolutely need everything to be scoped to a team, so adding support of team-less boards was not an option.

I was thinking of some ways to notify the users of losing access to what happened. @chenilim @wuwinson @sbishel any thoughts on this?
