### ISSUE TITLE
Bug: Long board name causes overflow issue

### ISSUE THREAD

**Issue by coreyhulen** [mattermost/focalboard#240]
**Summary:**
When you have a long board name and you mouse over the LHS it causes the LHS border to shift.

**Steps to reproduce the behavior:**
1. Create a board with the name `FY22 H1 Goal Definitions`
2. From LHS menu float over with the mouse

**Expected behavior:**
LHS border shouldn't change size

**Screenshots:**
https://user-images.githubusercontent.com/1431746/114054478-22e0e580-984d-11eb-9762-5f2077510b20.mov

**Platform:**
 - Browser and version: Chrome
 - OS and version: Mac

**Comment by jespino** [comment]
It should be fixed now on main branch
