### ISSUE TITLE
Permissions branch: Menus are cut off in sidebar

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2402]
## Steps to reproduce the behavior

1. Select the ... menu of a board in the sidebar
2. Select "Move to..."
3. The sub-menu is cut off and unreadable

## Expected behavior

The sub-menu is visible

## Screenshots

<img width="256" alt="Screen Shot 2022-02-25 at 11 37 43 AM" src="https://user-images.githubusercontent.com/46905241/155784106-e8d065c4-6595-4871-9035-1f24a6e165f2.png">

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: permissions-feature-branch
 - Browser and OS: Chrome on Mac

**Comment by chenilim** [comment]
May be related to [this card](https://community-daily.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/b4ctmm917q3rzdfi451qtuxjzcw/v3ng1gwe7wtfaijukrhp8siwcpy/c9ztr8fwjwbbnxgydagfuby381r). cc @harshilsharma63.

**Comment by chenilim** [comment]
The category menu is also truncated, likely the same issue:
<img width="277" alt="Screen Shot 2022-02-25 at 11 43 26 AM" src="https://user-images.githubusercontent.com/46905241/155784855-0dc17a59-70c9-4ff5-b449-61c2e4b24ac4.png">

**Comment by chenilim** [comment]
Might be a dup / already be fixed by https://github.com/mattermost/focalboard/pull/2399.

**Comment by harshilsharma63** [comment]
> Might be a dup / already be fixed by #2399.

@chenilim yes, it's already fixed. Closing this one.
