### ISSUE TITLE
UX: Profile picture and Send button are vertically centered for comments

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2405]
## Steps to reproduce the behavior

1. Open a card
2. Enter a long comment (e.g. 3 paragraphs of lorem ipsum)
3. The profile picture and Send button are vertically centered

## Expected behavior

The profile picture should be aligned to the top, and the Send button to the bottom (I think?).

## Screenshots

<img width="775" alt="Screen Shot 2022-02-25 at 2 04 30 PM" src="https://user-images.githubusercontent.com/46905241/155809776-2b04b744-af2c-40b6-8934-edc39efd8670.png">

## Edition and Platform

 - Edition: Personal Desktop / Personal Server / Mattermost plugin
 - Version: v0.14.0
 - Browser and OS: Chrome on Mac

**Comment by chenilim** [comment]
@asaadmahmood, please weigh in on what the layout should be. We should fix it if an easy change, or we can put it up for grabs. Thanks.

**Comment by chenilim** [comment]
Agree that the card comments should conform with the message post, but be aware that Enter does not send the comment today - it inserts a newline. While, Alt+Enter in channels inserts a newline, and Enter submits the post.

**Comment by asaadmahmood** [comment]
@chenilim Yup, we should unify it, so we're not inconsistent here.
