### ISSUE TITLE
Doc: Export / import boards doc has an out of place "Share a template" heading

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2412]
## Summary

The [import / export docs](https://docs.mattermost.com/boards/sharing-boards.html#import-and-export-a-board) show:

<img width="1036" alt="Screen Shot 2022-02-28 at 9 14 16 AM" src="https://user-images.githubusercontent.com/46905241/156027658-d544fd7b-41cb-458e-b4ca-638fad0295b0.png">

The "Share a template" heading appears out of place / not needed. Maybe work in progress?

## Link to documentation page

[If applicable, link to the documentation page and/or section where you feel the improvement could be added. E.g. `https://docs.mattermost.com/boards/accessing-boards.html`
](https://docs.mattermost.com/boards/sharing-boards.html#import-and-export-a-board)

**Comment by justinegeffen** [comment]
Thanks for catching this! It's been fixed. :)
