### ISSUE TITLE
Bug: Personal Desktop opens to a blank screen

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#2420]
## Steps to reproduce the behavior

1. Get the latest Personal Desktop build from main
2. Launch it
3. App stuck on blank screen

## Expected behavior

Boards view should load

## Screenshots

![SharedScreenshot](https://user-images.githubusercontent.com/15314183/156155603-221b883d-6d27-4046-a6f5-787602f30930.jpg)

## Edition and Platform

 - Edition: Personal Desktop
 - Version: latest main
 - Browser and OS: Windows

**Comment by chenilim** [comment]
This should be fixed now / dup of #2430.
