### ISSUE TITLE
Bug: Personal Server > Users should not be prompted to take a tour

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#2422]
## Steps to reproduce the behavior

1. Open Personal Server
2. On the Welcome screen, click on "Take a tour"
3. User is taken to the welcome board, but there's no tour

## Expected behavior

Welcome screen shouldn't prompt the user to take a tour

## Edition and Platform

 - Edition: Personal Server
 - Version: main
 - Browser and OS: Chrome on Windows

**Comment by wuwinson** [comment]
@harshilsharma63 Is it easier to make the onboarding tour work for v0.15 or is it easier to remove the link altogether similar to Personal Desktop? Let's do whatever is easier for v0.15. cc @sbishel @chenilim

**Comment by harshilsharma63** [comment]
@wuwinson we display the welcome page only on plugins now. So can this be closed now?

**Comment by wuwinson** [comment]
Thanks @harshilsharma63, closing this out!
