### ISSUE TITLE
Permissions branch: View=0 in card links does not show card

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#2426]
## Steps to reproduce the behaviour

1. Create a link to a card that uses default view (0 for view id in link).  e.g. An @mention will create this kind of link.
2. Click the link or paste into browser
3. The card does not display 
4. Logs indicate the view was not found

## Expected behaviour

Card links work with or without a view id

## Edition and Platform

 - Edition:  Mattermost plugin
 - Version:  Permissions branch
 - Browser and OS: FF 93 Linux

**Comment by jespino** [comment]
This should be fixed in #2473
