### ISSUE TITLE
Bug: Permissions Feature Branch: Cannot open boards from app-switcher after upgrade

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#2433]
## Steps to reproduce the behavior

1. Install any previously released version of Boards. Open boards and create some boards.
2. Now upgrade to the build from the permissions feature branch.
3. Open boards from Mattermost app switcher.
4. Notice the boards don't open up and the URL is incorrect.

## Expected behavior

Boards should work perfectly fine on upgrading from a previous version.

## Screenshots

NA

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: permissions feature branch
 - Browser and OS: Firefox and Chrome

## Additional context

I think it is unable to pick the team ID on opening from the app switcher.

**Comment by jespino** [comment]
@harshilsharma63 can you confirm if this is still happening?

**Comment by harshilsharma63** [comment]
@jespino it works fine now. We can close this.
