### ISSUE TITLE
Bug: Changing the port to something else

### ISSUE THREAD

**Issue by JulienGenoud** [mattermost/focalboard#244]
I can't use focalboard with flipper because it's using the same port (8088)
making flipper not working.

https://fbflipper.com

**Comment by chenilim** [comment]
Thanks for filing this @JulienGenoud! Are you seeing this in the Mac app? If so, this should be fixed in the next release (dup of #109). If you can build from source (`make mac-app`), please let me know if you still see the issue there. Thanks!

**Comment by JulienGenoud** [comment]
@chenilim works now with the new port ;)
