### ISSUE TITLE
Bug: Card properties escape card boundary

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#2447]
## Steps to reproduce the behavior

1. Set a really long value in a select property.
2. Select that property to show up in the board view.
3. Notice the value displayed in the cards.

## Expected behavior

The long value shouldn't overflow.

## Screenshots
<img width="1883" alt="Screenshot 2022-03-03 at 3 00 26 PM" src="https://user-images.githubusercontent.com/18575143/156536496-229e81f5-2b49-42e7-bfd4-4dd199b5b41b.png">

## Edition and Platform

 - Edition: 
 - Version: 0.15-RC1
 - Browser and OS: Firefox

**Comment by ogi-m** [comment]
Verified this is fixed on v0.15 RC2
