### ISSUE TITLE
Bug: Dismiss first tour point if a user opens a card 

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#2450]
## Steps to reproduce the behavior
1. Start tour
2. Click outside to dismiss first tour point
3. Open the card
4. No tour points start in the card

## Expected behavior
For 4th point, the card tour points should start as soon as the user opens a card for the first time.
Also, add a cursor pointer on the pulsing dot indicator.

## Screenshots
https://user-images.githubusercontent.com/11034289/156541304-e2f72b12-e4be-4722-9ab4-85eb29c8def9.mov

## Edition and Platform
Edition: Personal Server and Mattermost plugin
Version: 0.15-RC1
Browser and OS: [e.g. Chrome 91 on macOS, Edge 93 on Windows]

**Comment by wuwinson** [comment]
Wasn't able to repro myself. @harshilsharma63 @ogi-m can you confirm?

**Comment by wuwinson** [comment]
@asaadmahmood Are you still able to repro this? Feel free to close out if not. Thanks!

**Comment by asaadmahmood** [comment]
@wuwinson Yup, Harshil is already working on this, he's trying to fix this issue.

**Comment by ogi-m** [comment]
Verified this is fixed on v0.15 RC2
