### ISSUE TITLE
Bug: Duplicating Welcome to Boards board from sidebar doesn't work

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#2451]
## Steps to reproduce the behavior

1. Once done with the product tour, try duplicating the board from the left sidebar.
2. Notice the board doesn't duplicate.

## Expected behavior

User should be able to duplicate the welcome board.

## Edition and Platform

 - Edition: Personal Mattermost plugin
 - Version: 0.15-RC1
 - Browser and OS: Firefox

## Additional context

It only occurs on the welcome board created automatically for the tour.

**Comment by harshilsharma63** [comment]
The code issue here was that the images in the welcome board were not being copied over when creating a copy for the onboarding tour. Sof without this fix, if you see any card in the onboarding tour board, you won't find images.

**Comment by chenilim** [comment]
I also hit an issue where the Onboarding board does not have images (500 errors in the console). Sounds like a dup of this issue.

**Comment by harshilsharma63** [comment]
> I also hit an issue where the Onboarding board does not have images (500 errors in the console). Sounds like a dup of this issue.

@chenilim lack of images was the underlying cause of this. So the linked PR fixes both.

**Comment by ogi-m** [comment]
Tested and passed on v0.15 RC2
