### ISSUE TITLE
Bug: Read-only view screen when access revoked

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#2457]
## Steps to reproduce the behavior

1. Go to Share 
2. Publish External Link
3. Using Incognito, go to external link.
4. Should open find.
5. Disable External Link 
- either turn off sharing
- or regenerate token
6. Refresh incognito window

## Expected behavior
Unsure...but I think just a blank page, with top banner.

You cannot create a board from here, but shouldn't display.

## Screenshots

![Screen Shot 2022-03-03 at 11 13 32 AM](https://user-images.githubusercontent.com/12704875/156627455-de15085d-409b-4c10-985f-0a9f91dd7897.png)

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: 0.15-RC1
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment]
Should send user to error page with message: "Board may be deleted or access revoked"
