### ISSUE TITLE
Bug: Console errors when viewing and using board templates

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2463]
## Steps to reproduce the behavior

1. Open the browser console
2. Go to the board template selector (add board)
3. Select each template
4. See errors in the console
5. Create a board from the templates that show errors
6. Same errors when viewing specific views in those board (e.g. Project Tasks \ Project Priorities)

## Expected behavior

No errors.

## Screenshots

<img width="1021" alt="Screen Shot 2022-03-03 at 10 37 32 AM" src="https://user-images.githubusercontent.com/46905241/156630212-3db85110-4272-4b55-942b-43cb39e96f9d.png">

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.15 RC1
 - Browser and OS: Safari on Mac

**Comment by ogi-m** [comment]
@chenilim @wuwinson I see this on a newly created server as well.

**Comment by chenilim** [comment]
@sbishel, @wuwinson we may have missed triaging this yesterday. It's a sev 3, but I think it's worth doing a cleanup pass through the built-in templates.

**Comment by chenilim** [comment]
I took a closer look at this. The issue is caused by the [groupByProperty](https://github.com/mattermost/focalboard/blob/main/webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.tsx#L51) and [visibleGroups](https://github.com/mattermost/focalboard/blob/main/webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.tsx#L55) variables changing at different times. i.e. when switching templates:
1. First the `activeTemplate` is updated to the new one (while activeView is still the previously selected template's view)
  * This renders with the console errors
3. Then the `activeView` is updated
  * This then renders correctly, without errors

There is a similar flow, and console errors, in [CenterPanel.render](https://github.com/mattermost/focalboard/blob/main/webapp/src/components/centerPanel.tsx#L180).

So, the issue is not related to the template data per-se, and this does appear to not have any direct side effects. I'm not sure what the correct fix is, but I think it'll need your input @jespino. I'll push it back to triage for now. cc @sbishel, @wuwinson.

**Comment by sbishel** [comment]
This was fixed, https://github.com/mattermost/focalboard/commit/41a722049f784835f8e2f21310593d798f24ccc5
