### ISSUE TITLE
Bug: Language settings menu overlaps Import menu

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2476]
## Steps to reproduce the behavior

1. Go to settings menu and click on Import
2. With the settings menu still open, click on Set language
3. See error
4. Click on Import again
5. See error

## Expected behavior

Opening a submenu should dismiss other submenus. Clicking on Set language should close out the Import menu and vice versa.

## Screenshots
![Screen Shot 2022-03-04 at 6 46 27 PM](https://user-images.githubusercontent.com/93531870/156857628-84810fc3-6b3d-409c-8131-ca56c3cdf262.png)

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.15 RC1
 - Browser and OS: Chrome Version 96.0.4664.55 on macOS

## Additional context
Workaround is to close the Settings menu and re-open.

**Comment by chenilim** [comment]
Might be related / dup of https://github.com/mattermost/focalboard/issues/2070.

**Comment by chenilim** [comment]
Dup of https://github.com/mattermost/focalboard/issues/1581.

**Comment by wuwinson** [comment]
Dupe of #1581

**Comment by sbishel** [comment]
Fixed via https://github.com/mattermost/focalboard/pull/2509
