### ISSUE TITLE
Bug: Export not working in Personal Desktop app on Linux

### ISSUE THREAD

**Issue by ZevSwe** [mattermost/focalboard#248]
**Summary:**
Export does not seem to work in the personal server.

**Steps to reproduce the behavior:**
1. Install focalboard according to the instructions
2. start with ./focalboard-app
3. Do any change
4. Click export under settings at bottom left.
5. Nothing happens, no logging, no nothing

**Expected behavior:**
The server version asks where you would like the file to be saved, I would expect the same from the Personal one.

**Platform:**
 - MANJARO 21.0.1

**Comment by codingthat** [comment]
I'm seeing this behaviour too on Linux Mint 19.3.  Import works fine, but export does not seem to have any effect.

**Comment by chenilim** [comment]
Thanks @ZevSwe and @codingthat! Updated title to reflect this is on the Linux app. Have to investigate more, but there was a similar issue in the Mac app, where we had to add special handling for file downloads. Export CSV would likely have the same problem.

**Comment by ZevSwe** [comment]
If you point me to where I can export CSV I could test that for you. I found that the user guide button is also non-responsive on the desktop app.

**Comment by chenilim** [comment]
Thanks @ZevSwe! Under the board menu, select `Export to CSV`
<img width="236" alt="Export CSV" src="https://user-images.githubusercontent.com/46905241/114617133-91161580-9c5c-11eb-84c1-538314be74c0.png">

**Comment by ZevSwe** [comment]
Thanks. I can confirm that is the case. Works on server version but not in app. Version 0.6.0 om both.

**Comment by chenilim** [comment]
Thanks for the updates. Opening this up to anyone who wants to take a crack at it. My guess is it requires implementing some hooks in the webview control on Linux.

**Comment by jespino** [comment]
I wrote a workaround because webview doesn't open externa links or download links.

**Comment by prisae** [comment]
I am on version v0.12.1, and I just tried to export on the Linux app without luck, nothing happens at all. How does your workaround look like @jespino ?
