### ISSUE TITLE
Bug: Duplicating a card, does not duplicate anymore the contents inside the card

### ISSUE THREAD

**Issue by marcungeschikts** [mattermost/focalboard#2489]
## Steps to reproduce the behavior

1. Go to a Board View
2. Click on the 3 point of a card that has content inside(text, or images,....)
3. Select Duplicate
4. The card is duplicated, but it does not contain any content

## Expected behavior

Back to the previous behaviour, where the Duplicate action copy also the content inside the card 

## Screenshots

![Card with content](https://user-images.githubusercontent.com/74183327/157194237-726eb5a6-c81e-4a51-87d3-d8445e14ec5d.png)
![Card duplicated with no content](https://user-images.githubusercontent.com/74183327/157194270-f6ae1b5f-6663-4764-9b8d-8472a4ab6454.png)

## Edition and Platform

 - Edition: Mattermost plugin 
 - Version: e.g. v0.11.0
 - Browser and OS:  Chrome Version 98.0.4758.102 (Build officiel) (64 bits) on Windows 11

**Comment by marcungeschikts** [comment]
👆🏻 I want also to mention that there is the same issue when creating a template from a card, the contents of the card are not copied to the template.

**Comment by marcungeschikts** [comment]
Sorry, I was mistaken. I am using Focalboard mattermost plugin installed on a server.

**Comment by jespino** [comment]
It is working for me in the main branch

**Comment by wuwinson** [comment]
Should be working in v0.14, closing out, but please feel free to open if you're still running into this issue in the latest release. Thanks!

**Comment by marcungeschikts** [comment]
I confirm it works in Feb 2022 version
![image](https://user-images.githubusercontent.com/74183327/157634615-d81c4861-3d61-4291-952c-46a80e3d18d3.png)

**Comment by wuwinson** [comment]
Thanks @marcungeschikts!
