### ISSUE TITLE
Bug: "Go to the dashboard" link on error page should only show in plugin

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#2491]
## Steps to reproduce the behavior

1. Trigger the error page on personal server
2. Click on "Go to dashboard"
3. User is taken to the dashboard

## Expected behavior

Button to go to the dashboard should not be shown on Personal Server and Personal Desktop, only plugin

## Screenshots

If applicable, add screenshots to elaborate on the problem.

## Edition and Platform

 - Edition: Personal Server
 - Version: v0.15
 - 
![SharedScreenshot](https://user-images.githubusercontent.com/15314183/157240541-9d62e247-9b8d-4e4a-820d-52ab6eb9bce7.jpg)

**Comment by chenilim** [comment]
On Personal Server / Desktop, we can navigate to home (/) if the user lands on any page that doesn't apply to that edition (Dashboard, etc.).

**Comment by wuwinson** [comment]
@wiggin77 Related issue for the error pages.

**Comment by chenilim** [comment]
Is this closed now with your last PR @wiggin77? https://github.com/mattermost/focalboard/pull/2518

**Comment by wiggin77** [comment]
> Is this closed now with your last PR @wiggin77? #2518

There are no longer any error page links to dashboard for any SKU.
