### ISSUE TITLE
Bug: Focalboard cards are not displayed anymore on mattermost when writing a card link

### ISSUE THREAD

**Issue by marcungeschikts** [mattermost/focalboard#2493]
## Steps to reproduce the behavior

1. Go to Mattermost
2. On a new message, copy the link of a focalboard card
3. Send the message(enter)
4. You will see the url of the focalboard card, and not the image of the card, like inthe previous version

## Expected behavior

Display the card smal image on Mattermost when writing the link of a focalboard card

## Screenshots

![Focabord ard link](https://user-images.githubusercontent.com/74183327/157281032-8e81a56e-7ed1-40c5-8b9e-d8b34705001d.png)

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: e.g. v0.11.0
 - Browser and OS:  Chrome Version 98.0.4758.102 (Build officiel) (64 bits) on Windows 11

**Comment by chenilim** [comment]
Thanks @marcungeschikts! The link preview feature should only work on Mattermost, and not Personal Desktop. Could you help check the following:
* The link is to a card on the same Mattermost server
* You are able to open and view that card via that link
* Are there any errors in the System Console or browser console at the time of creating the post?

From the steps and screenshot, it appears that the Boards plugin is not detecting and updating the link correctly at the time of the post - it should replace it with a "<Link to card>" link with the preview. cc @sbishel, @wuwinson.

**Comment by marcungeschikts** [comment]
Sorry, I was mistaken. I am using Focalboard mattermost plugin installed on a server

**Comment by marcungeschikts** [comment]
- The link is to a card on the same Mattermost server: **Yes**
- You are able to open and view that card via that link: **Yes**
- Are there any errors in the System Console or browser console at the time of creating the post?: **Yes** :
![Focalboard link](https://user-images.githubusercontent.com/74183327/157401448-13df2896-40c6-4bdd-8e10-7dd51f249884.png)

**Comment by wuwinson** [comment]
@marcungeschikts Can you upgrade to [v0.14](https://github.com/mattermost/focalboard/releases/tag/v0.14.0) and try again? Thanks!

**Comment by marcungeschikts** [comment]
On it.
I'll get back to you within the week.

**Comment by marcungeschikts** [comment]
I confirm it works with the last version of the plugin
![image](https://user-images.githubusercontent.com/74183327/157635194-1f5b1987-9c28-4e80-9ebc-dfc409d489c4.png)

You can close this ticket.
Thanks a lot.
