### ISSUE TITLE
Bug: Board title is truncated, even when there is a lot more space

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2496]
## Steps to reproduce the behavior

1. Open a board with a long title
2. The title is truncated, even through there is a lot of room

## Expected behavior

The full title should show if there is room

## Screenshots

<img width="651" alt="Screen Shot 2022-03-08 at 10 17 20 AM" src="https://user-images.githubusercontent.com/46905241/157300691-55718a39-f381-4d6c-8457-745919c2755b.png">

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.15 RC1
 - Browser and OS: Chrome on Mac

## Additional context

This does not repro on 0.14.

**Comment by chenilim** [comment]
@asaadmahmood, just saw this regression on community. Could you take a quick look? Appears to be caused by a CSS change? cc @sbishel, @wuwinson.

**Comment by chenilim** [comment]
Thanks @asaadmahmood! Recommend taking this for v0.15. Fix looks pretty straight forward. Anyone see any issues? cc @sbishel, @wuwinson, @ogi-m.

**Comment by wuwinson** [comment]
Agreed we should take this for v0.15.

**Comment by ogi-m** [comment]
Tested and passed on v0.15 RC2
