### ISSUE TITLE
Feature Idea: Save when closing card

### ISSUE THREAD

**Issue by ZevSwe** [mattermost/focalboard#251]
**Summary:**
When editing and then pressing outside of the card it closes without saving any progress. It would be nice if it did so that one did not loose anything if one miss clicked. One way could be some auto save feature maybe? Would also save a user who closed the browser for whatever reason.

**How important this is to me and why:**

Importance: Medium
I guess I'm not the only one who has done this one or two times and has had to re-write a card. It would improve the experience if that did not happen.

Use cases:
1. If a user miss clicks the info is still saved.
2. Saves progress if browser or computer crashes

**Comment by chenilim** [comment]
Cleaning up some old issues. This one is actually a bug, not a feature. All fields should save when clicking "away" or out of a card. See issues: #292, #303, and #269. I'm  closing this feature request, but please open new bugs if the existing ones don't cover any current issues you are seeing. Thanks!
