### ISSUE TITLE
Bug: Board switcher defaults to template picker instead of first view from first board

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2516]
## Steps to reproduce the behavior

1. Go to board switcher
2. Select a board different from your current board
3. See error - view defaults to template picker instead of first view of first board

## Expected behavior

It should only go to the new board screen if no boards exist in that workspace, otherwise it should go to the first board and first view.

## Screenshots

https://user-images.githubusercontent.com/93531870/157690674-29953dbc-af69-4c07-a70e-42899dba8140.mov

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.15 RC1
 - Browser and OS: Chrome 96 on macOS

**Comment by wuwinson** [comment]
@sbishel @harshilsharma63 Would this be a quick fix for v0.15? cc @asaadmahmood

**Comment by sbishel** [comment]
@harshilsharma63 - only if quick and safe as final build is tomorrow.

**Comment by harshilsharma63** [comment]
@sbishel not quick and easy and anyways already works in the permissions branch.

**Comment by harshilsharma63** [comment]
This is working fine on `main`.
