### ISSUE TITLE
Bug: Ctrl+X and Ctrl+Z don't work in comments

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2520]
## Steps to reproduce the behavior

1. Open a card
2. Enter a comment
3. Select some text
4. Press Ctrl+X (or Cmd+X on Mac)
5. Nothing happens

## Expected behavior

The text should be cut.

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.15 RC1
 - Browser and OS: Chrome on Mac

## Additional context

Similarly, Cmd+Z / Cmd+Shift+Z to undo / redo typed text in comments doesn't work.

**Comment by chenilim** [comment]
Note: The issue is probably that the card keyboard handler is intercepting undo / redo keys even when the comment is being edited.

**Comment by kyeongsoosoo** [comment]
@chenilim  Can I take this issue? 
I took a look and it seems that it's a bug from `markdownEditorInput`.
Maybe it's related to #2814, too.

**Comment by sbishel** [comment]
Thanks @kyeongsoosoo - all yours.
