### ISSUE TITLE
UX: Long board description pushes content down

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2521]
## Steps to reproduce the behavior

1. Open a board
2. Enter a long description for the board
3. The cards are pushed down, and the description cannot be scrolled away or collapsed

This makes this board unusable, particularly on smaller screens.

## Expected behavior

The description should scroll away when content is scrolled down. i.e. the whole main content area should scroll.

## Screenshots

<img width="1367" alt="Screen Shot 2022-03-10 at 12 07 20 PM" src="https://user-images.githubusercontent.com/46905241/157746531-58405ce0-a687-4694-9d34-39756053b167.png">

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.15 RC1
 - Browser and OS: Chrome on Mac

**Comment by chenilim** [comment]
@asaadmahmood, what do you think the expected behavior should be? Scrolling the entire main area seems to be the most natural thing, but are there better alternatives? One possible addition is that the board header (Properties, Group by, etc.) should ideally "stick" to the top of the screen when scrolled.

(I thought we had this issue filed somewhere, but I couldn't find it, so filed a new issue). cc @wuwinson.

**Comment by wuwinson** [comment]
What if we truncated the text after several lines with a "view more" button or an option to expand/collapse the description? The **Meeting Agenda** template has a 4 line description and that seems to be an okay limit without taking up too much real estate.

**Comment by chenilim** [comment]
Please weigh in @asaadmahmood. Do you another alternative?

**Comment by asaadmahmood** [comment]
@wuwinson @chenilim I think we can have it scroll, set a max height on the description content of lets say 3-4 lines.
I think people adding that much description would probably not be that common.

**Comment by chenilim** [comment]
I'm bumping up the priority on this - to do by v0.17 / June. @asaadmahmood, agree with your proposal above. Would there be a button to expand / collapse the header past 4 lines? Or show on hover like the Channel header? Let's sync up at our next meeting. Thanks.
