### ISSUE TITLE
Permissions Branch Bug: personal server should navigate to login page instead of error page when not logged in

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#2534]
## Steps to reproduce the behavior

1. Run personal server.
2. Open it up in a browser where you're not already logged into your personal server.
3. Notice you end up on the URL `http://localhost:8000/error?id=not-logged-in`.

## Expected behavior

When not logged in, the user should be sent to the login page instead.

## Edition and Platform

 - Edition: Personal Server
 - Version: permissions branch
 - Browser and OS: [e.g. Chrome 91 on macOS, Edge 93 on Windows]

**Comment by chenilim** [comment]
Propose removing the "Sorry, something went wrong" header from this error page.
* E.g. if someone shares a link to a board, and you're not logged in, opening the link should prompt you to login, but this is not "something wrong". This applies to plugin as well.

@asaadmahmood, please weigh in, or if there's a better way to handle this. E.g. a more elaborate welcome process for Personal Server.

cc @wuwinson.

**Comment by asaadmahmood** [comment]
@chenilim @wuwinson For both plugin and personal server, I think we should take the user to the login page.
Here are some screens from what competitors do when you access a link you don't have access to.
https://www.figma.com/file/pHTXvGBkZtMgWyidN1O987/Error-Pages?node-id=2%3A3922

**Comment by chenilim** [comment]
Thanks @asaadmahmood. Setting triage to discuss when Winson's back. One follow-up issue is that the Mattermost login page will open Channels after login, which will be jarring to the user who may struggle to find the board. At least on Personal Server, the list of boards will be shown after login. Also cc @wiggin77.

**Comment by asaadmahmood** [comment]
@chenilim Even if we show an error page, and add a login button in there, that problem would still be there, as that would take the user to Mattermost's login page on click.

So taking the user to the error page may not be the fix, it would still make the user run into the same problem, so we have to figure out redirects from the login page.

**Comment by chenilim** [comment]
Yup @asaadmahmood, I agree. The ideal flow is the user is auto-redirected back to the specific URL (board, card, view, etc.) after login. That can be tracked as a separate issue. Sounds like we agree that it's an improvement to redirect straight to the login page (and eliminate this page entirely) when the user is not logged in. I don't know / remember if there was a reason we didn't do that instead of the current implementation. Anyone see any issues with the proposed change?

**Comment by wuwinson** [comment]
Removing the error page and redirect to login page makes sense to me. For plugin, we need to redirect to MM login page, while for others, we can redirect to Focalboard login. Any concerns with this @wiggin77? cc @chenilim @sbishel
