### ISSUE TITLE
Feature Idea: Mindmap support

### ISSUE THREAD

**Issue by ZevSwe** [mattermost/focalboard#254]
**Summary:**
Mind maps are incredible strong. Would be good in both knowledge bases and meeting notes. Today I use the nextcloud mind map app, but it would be nice having it integrated in focalboard.

**How important this is to me and why:**

Importance: Low
This is a powerful nice-to-have feature.

Use cases:
1. Brainstorm in meetings
2. Explain complex networks of information
3. Plan projects

**Comment by ZevSwe** [comment]
This could be merged with  #237. Sorry for dup.

**Comment by it33** [comment]
Thanks @ZevSwe, no worries, closing as duplicate.
