### ISSUE TITLE
Permissions Branch: Remove commenter from list 

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2570]
## Steps to reproduce the behavior

1. Open the board's share UI
2. Select a role
3. Commenter is shown, but does not work as expected

## Expected behavior

Remove the commenter role from the list for now (v6.6)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: permissions-feature-branch
 - Browser and OS: Chrome on Mac

**Comment by jespino** [comment]
This is already done in the permissions branch
