### ISSUE TITLE
Bug: focus on title input field when adding card

### ISSUE THREAD

**Issue by sambody** [mattermost/focalboard#2575]
I would like the focus (cursor) automatically be in the card title input field. So that I can start adding the title right away, without having to click on it.

## How important this is to me and why

Importance: High

Having the focus automatically on the title would save a bit of time (one less click), especially when adding multiple cards in a row.

## Additional context/similar features

A good implementation of this is Trello: when adding a new card, the focus is directly on the input field. What's more is that when adding the title and hitting enter, the card is saved, a new card is presented, again with the focus in the input field. This makes adding multiple cards very fast, all with the keyboard. As if writing a list of items in a text document. I'm not sure that speed is possible in Focalboard, since, unlike trello, adding a new card pops up a lightbox window. But having the focus on the title would be one step forward to faster card creation.

Thanks.

**Comment by kamre** [comment]
Hi @sambody, this was working before exactly like you have described. So some regression was introduced.

@chenilim FYI

**Comment by chenilim** [comment]
Thanks @sambody and @kamre! I checked, and this is indeed a regression... from 0.11. So, it's been broken for a while, but agree that the behavior should be to auto-select the title field when opening a card with no title (such as a new card). cc @wuwinson, @asaadmahmood.

**Comment by chenilim** [comment]
Also, as a note: Would be worth adding a (Cypress) unit test for this when fixed.

**Comment by kamre** [comment]
Here is a possible fix:
```diff
Index: webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
===================================================================
diff --git a/webapp/src/components/markdownEditorInput/markdownEditorInput.tsx b/webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
--- a/webapp/src/components/markdownEditorInput/markdownEditorInput.tsx	(revision aa9ebc237fc162c1c98a9ff02cff4389bc539c83)
+++ b/webapp/src/components/markdownEditorInput/markdownEditorInput.tsx	(date 1648580066731)
@@ -125,10 +125,13 @@
     }, [editorState, onBlur])
 
     const onEditorStateChange = useCallback((newEditorState: EditorState) => {
+        const text = editorState.getCurrentContent().getPlainText()
         const newText = newEditorState.getCurrentContent().getPlainText()
-        onChange && onChange(newText)
-        setEditorState(newEditorState)
-    }, [onChange])
+        if (text !== newText) {
+            onChange && onChange(newText)
+            setEditorState(newEditorState)
+        }
+    }, [onChange, editorState])
 
     const onMentionPopoverOpenChange = useCallback((open: boolean) => {
         setIsMentionPopoverOpen(open)
```

**Comment by kyeongsoosoo** [comment]
@chenilim Can I take this issue?

**Comment by wuwinson** [comment]
Go for it @kyeongsoosoo! Can you also include unit tests? Thanks!
