### ISSUE TITLE
Bug: Card should not show "Following" on first open without edits being made

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#2583]
## Steps to reproduce the behavior

1. Open boards (either from in-channel icon or via Grid icon > Boards)
2. Select the Project Tasks template
3. Click on Project budget approval card
4. Observe that sometimes "Follow" already shows "Following" 

## Expected behavior

"Follow" should only change to "Following" if an edit has been made or you have clicked on "Follow"

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/13020833/159553577-66f139d8-70f9-4ff3-b30d-d4ffb29a0d94.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: [e.g. v0.15.0]
 - Browser and OS: [e.g. Win10/Chrome & macOS Safari]

## Additional context (optional)
I reproduced this on the Rainforest servers, v6.5 while writing a test for [this issue](https://github.com/mattermost/focalboard/issues/2460)

**Comment by wuwinson** [comment]
@lindy65 When you create a board from a template, you are automatically the creator of the default cards on the board, which also makes you a follower of the card. In this screenshot, the creator was "rainforest-admin", so if you're logged in as that account, then you should be following the card. Closing out this ticket "as-designed".

**Comment by lindy65** [comment]
Thanks @wuwinson - Understood that creator of the card should automatically show "following".

However, in step 4 above, I mentioned "sometimes" - so it seems there _may_ be a bug here because it's random whether the card shows "Follow" or "Following"

**Comment by wuwinson** [comment]
@lindy65 Thanks for clarifying. We shipped change notifications in Jan 2022, so you will only be set as "following" on any new cards created after that point. We didn't run any migrations for older cards, so you wouldn't be automatically following cards created prior to that time. Feel free to re-open this ticket or file a new one if you notice that you're not following any new cards created after Jan 2022. Thanks!
