### ISSUE TITLE
Feature Idea: Interactive rendered Markdown

### ISSUE THREAD

**Issue by codingthat** [mattermost/focalboard#259]
**Summary:**
Markdown in descriptions handles URLs and checklist items (`- [ ]`)...but those would be more useful if they could be interacted with in standard ways:

1. Clicking a URL doesn't seem to do anything.  Neither does right-clicking and choosing "open" or "open in new tab".  So the very common action of clicking a hyperlink currently needs this workaround: 1) right-click 2) click "copy URL" 3) switch to your browser 4) open a new tab 5) paste the link 6) hit Enter.
2. Clicking a Markdown checkbox could do the edit (toggling the checkbox) quickly for you like it does in GitHub.  Instead, you have to 1) click the description 2) click precisely within the `[ ]` or `[x]` you want to toggle 3) edit it 4) click back outside the description (but not too far outside: #251 ).

**How important this is to me and why:**

Importance: Medium

Use cases:
1. Everyday usage of URLs in descriptions.
2. Everyday usage of checklists in descriptions.

**Additional context / similar features:**
Trello (and just about everything else, even my terminal) does 1. out of the box.  It doesn't do 2. per se, but does one better in supporting bona fide checklists (with templating), which do allow for one-click toggling.

**Comment by chenilim** [comment]
Thanks for submitting this @codingthat! Number 1 should work currently after saving:
* Add a link to the card description / contents, e.g. `This is a [link](http://www.focalboard.com).`
* Press Esc to save
* Should be able to click on the link to open it

Does that work for you? If not, which version are you seeing this on (e.g. Mac app store app, or current build)?

We recently added a [checkbox content type](https://github.com/mattermost/focalboard/pull/146), which is rolling out in 0.6.5. Plan is to add more types to make the content more interactive.

**Comment by codingthat** [comment]
Clicking the link does not seem to do anything (nor right-clicking it and choosing the first two options, as mentioned above.)  That's already after saving a Markdown link as you describe (otherwise it would not recognize it as a URL in the context menu and give choices like "open in new tab," right?)

Great to hear about the checkbox content type though!  That would put it on the same level as Trello ✔

**Comment by chenilim** [comment]
Thanks @codingthat. Hmmm... what version / platform / browser is this on? I just smoke tested this on the v0.6.0 Mac app, Windows app, and Chrome 89.

BTW, the same thing should work in the board description too.

**Comment by codingthat** [comment]
v0.6.1 personal edition (not sure what browser it uses internally)... I must've just missed 0.6.5RC1.  Linux Mint 19.3 64-bit.  Thanks!

**Comment by chenilim** [comment]
Thanks @codingthat! I installed Linux Mint (20.1 Cinnamon), and confirmed that this is indeed an issue with the Desktop App.
To avoid confusion with the checkbox feature idea, I've opened a new issue, #284 to track it. Please feel free to add additional details or comments there, or open additional feature ideas for markdown or other things.
