### ISSUE TITLE
Feature Idea: Duplicate board with templates and cards

### ISSUE THREAD

**Issue by ZevSwe** [mattermost/focalboard#260]
**Summary:**
Say you would run a company that did the same thing over and over. Each customer delivery contains the same basic parts. Then it would be really strong if one could duplicate a template board that already has the basic cards in it and that has templates for the most common add-ons. Today when duplicating a board it does not include templates (strange) and not cards (this should probably be a choice).

**How important this is to me and why:**

Importance: High

As I will use this for customer deliveries and they will be for the most part identical this would be a great way of keeping track of that.

Use cases:
1. Project templates for whole boards. When launching new project just create a new copy of the board and fill in the blanks.
2. Customer delivery, one customer delivery is one board, just use the template board and add whatever addons you need via the template cards.

**Comment by chenilim** [comment]
Hi @ZevSwe, thanks for filing all these ideas! They are very helpful.

This particular one sounds like a bug: Duplicating a board should duplicate all cards and card-templates in that board. Could you add which version you are seeing this issue on? i.e. Personal Desktop from the Mac / Windows app store? Or built-from-source?

**Comment by ZevSwe** [comment]
Hmm, you are correct. I re-tested and it worked fine. I suspect error from my side. But then it begs the question, what if I want to duplicate a board but not all cards? Any good way of selecting all and deleting on the new board?

I guess we can close this for now and I can open a new ticket for batch editing :)

**Comment by chenilim** [comment]
Awesome! Thanks for confirming @ZevSwe. I'll close this for now, but please reactivate or file a new issue if you see bugs.

As for duplicating just the board: Have to think more about it, but I can see a scenario of duplicating just the **board + card templates**. One way perhaps is to offer a dialog to let users choose what things to duplicate.

For now, duplicating then deleting all cards would work, but please feel free to open a new issue if you can think of other "advanced duplication options".
