### ISSUE TITLE
Bug: Guest User can access user via API

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#2606]
## Steps to reproduce the behavior

1. Login as a Guest User to the Mattermost with Focalboard Plugin enabled. 
2. Ensure that the Guest User has access to only one channel and one another user, say User1. 
3. Now if the Guest User tries to access the Mattermost API endpoint to fetch the user details of User2, i.e

/api/v4/users/<user_id>

The user will get an error indicating that the user does not has enough permissions. 
<img width="1567" alt="Screenshot 2021-12-08 at 11 26 31 AM" src="https://user-images.githubusercontent.com/12704875/159770983-1893f81f-0570-4837-9a0c-6edf5ba0ba83.png">

4. However if the same user calls the Focalboard plugin API to fetch the user details of User2, i.e. 

/plugins/focalboard/api/v1/users/ppijfug66iy83frijk1hz44r6o 

The user gets the information about the user along with the user's custom status. 

## Expected behavior

Guest user should only be allowed to fetch user information for which the guest user has access to. If the user does not has permission, then it should throw an error. 

<img width="1567" alt="Screenshot 2021-12-08 at 11 26 41 AM" src="https://user-images.githubusercontent.com/12704875/159770989-005a3709-4265-49ad-b4eb-978b7779a935.png">

**Comment by sbishel** [comment]
Moved from Jira - https://mattermost.atlassian.net/browse/MM-40538

**Comment by wuwinson** [comment]
Guest accounts won't have any access to Boards in v0.16.

**Comment by wuwinson** [comment]
Guests cannot be set as admins on Channels.
