### ISSUE TITLE
Feature Idea: Export/import board

### ISSUE THREAD

**Issue by ZevSwe** [mattermost/focalboard#261]
**Summary:**
It would be nice if one could export just one board. Say I designed a killer board for tracking software projects that I would like to share as a template for the community and someone else wanted to import and test that. One would want to do that without effecting any other boards one has.

**How important this is to me and why:**

Importance: Low
This is a nice to have feature. It's not really that important right now. 

Use cases:
1. Share a template with the community
2. Import someone else's template

**Comment by chenilim** [comment]
Just going through issues. Yes, this is a feature we want. What we need is:
* A new API to export all blocks from a rootID (i.e. all the contents of a board)
* UI to export a board into the .focalboard archive format

**Comment by hahmadia** [comment]
Hey guys,

I'll be taking a look at this.

**Comment by chenilim** [comment]
Thanks for picking this up @hahmadia!
