### ISSUE TITLE
Bug: Unauthorized user is able to retrieve blocks for private board template

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2633]
## Steps to reproduce the behavior

1. Call getBlocks for a private board template as an unauthorized user
2. Call succeeds

## Expected behavior

Call should fail with 403.

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.16 (main)

## Additional context (optional)

See PR https://github.com/mattermost/focalboard/pull/2632 for the failing test.

The expected behavior is:
* All users (in the system) can view any built-in template
* Only Viewers (and above) of a board can view it, including custom templates

**Comment by wuwinson** [comment]
@harshilsharma63 Does #2636 address this bug?

**Comment by harshilsharma63** [comment]
@wuwinson yes, this is fixed with #2636. I've verified this on `main`.
