### ISSUE TITLE
Bug: Import scripts are broken

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2638]
## Steps to reproduce the behavior

1. Follow the steps to import, e.g. [from Asana](https://docs.mattermost.com/boards/data-and-archives.html#import-from-asana)
2. Error (see [thread](https://community-daily.mattermost.com/core/pl/qu3rprxx8pyidefpwptwsged7c)

## Expected behavior

Import succeeds

## Screenshots (optional)

Compile errors:
```
TSError: ⨯ Unable to compile TypeScript:
importAsana.ts:106:11 - error TS2339: Property 'rootId' does not exist on type 'Board'.

106     board.rootId = board.id
              ~~~~~~
importAsana.ts:133:17 - error TS2345: Argument of type 'Board' is not assignable to parameter of type 'Block'.
  Type 'Board' is missing the following properties from type 'Block': boardId, parentId, schema, fields

133     blocks.push(board)
                    ~~~~~
importAsana.ts:139:10 - error TS2339: Property 'rootId' does not exist on type 'BoardView'.

139     view.rootId = board.id
             ~~~~~~
importAsana.ts:149:17 - error TS2339: Property 'rootId' does not exist on type 'Card'.

149         outCard.rootId = board.id
                    ~~~~~~
importAsana.ts:171:18 - error TS2339: Property 'rootId' does not exist on type 'TextBlock'.

171             text.rootId = board.id
                     ~~~~~~
```

## Edition and Platform

 - Edition: Personal Desktop / Personal Server / Mattermost Boards (plugin)
 - Version: v0.16 (main)

## Additional context (optional)

Broken by model changes.

**Comment by wiggin77** [comment]
@chenilim   This should be fixed as part of https://github.com/mattermost/focalboard/pull/2577.  I am blocked testing this as main is not loading boards at all for me.

**Comment by chenilim** [comment]
Thanks @wiggin77! Also, as a note to anyone else running into this: main currently contains work-in-progress code for the upcoming release. In order to import successfully into v6.5 (March 2022 release) and earlier, run the [import scripts](https://docs.mattermost.com/boards/data-and-archives.html) from the `release-0.15` branch, i.e. from a clone of your fork:
```
git fetch upstream
git checkout release-0.15
```
