### ISSUE TITLE
Bug: Clean up API permissions-check inconsistencies

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2639]
## Steps to reproduce the behavior

See [this thread](https://community-daily.mattermost.com/core/pl/tydo1w1x97fmidzzexnosjwnzo) for more details.

Currently, some APIs (handleGetBoard, handleDuplicateBoard, handleGetBlocks, handleGetTemplates, maybe others) allow users to retrieve public board data without being a member of the board. This is both a consistency and potential audit issue.

We should refactor the APIs to require users become explicit members (via handleUpdateMember) before being able to retrieve public board data.

The client kinda tries to do 2 in [BoardPage here](https://github.com/mattermost/focalboard/blob/main/webapp/src/pages/boardPage/boardPage.tsx#L90), but the APIs do not all enforce this.

We should draw the line at board vs. block data. i.e.

* A team member can retrieve board data for public boards (or maybe just a subset, i.e. ID, Title, Author, Created date, Updated date?)
* Only board members can retrieve the blocks for a board, including public boards

So, APIs like handleSearchBoards will continue to work, but handleDuplicateBoard will require HasPermissionToBoard to succeed (on all paths).

This leaves templates. The client requires all the blocks to show the preview. We either have to treat public templates specially, or explicitly call addMember on each template a user clicks on. I'm not sure which is better or worse, but if we have special treatment, then I propose adding APIs specifically for templates, so we can isolate the exception.

## Expected behavior

This may require a few iterations, but the first pass is to ensure that only explicit members of a board can retrieve blocks for that board

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.16 (main)

**Comment by jespino** [comment]
This is already solved.
