### ISSUE TITLE
Feature Idea: Vertically align comment icon & button 

### ISSUE THREAD

**Issue by it33** [mattermost/focalboard#264]
**Summary:**
Propose adjusting vertical alignment of comment icon and "Send" button in cards

**How important this is to me and why:**

Importance: Medium

Use cases:
1. Viewing "Add Comment" 
2. Clicking "Send" after typing comment and having the button in a location that is expected

**Additional context / similar features:**

Center grey icon to align with "Add Comment" 
![image](https://user-images.githubusercontent.com/177788/114566024-b7b95980-9c26-11eb-8d99-5472adf06219.png)

Maybe Bottom align grey icon and "Send" button. Center alignment is difficult to use because as the text grows the button moves
![image](https://user-images.githubusercontent.com/177788/114566149-d9b2dc00-9c26-11eb-9f9f-2cf3476a74ac.png)

**Comment by it33** [comment]
@asaadmahmood wondering your thoughts here?

**Comment by asaadmahmood** [comment]
@it33 Something like this would make sense.

![image](https://user-images.githubusercontent.com/11034289/114569525-7fe5fc80-9c8e-11eb-9c53-75b31adbeb67.png)

**Comment by asaadmahmood** [comment]
Should be fixed.
