### ISSUE TITLE
Permission Branch: Missing options to duplicate board and create new template from board

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2640]
## Steps to reproduce the behavior

1. Create a new board
2. Click on the "..." menu next to the board name on the sidebar
3. See error

## Expected behavior

Menu should have options for:
- Duplicate board
- New template from board

## Screenshots (optional)

| Permissions Branch  | Community |
|--|--|
| ![Screen Shot 2022-03-25 at 12 59 32 PM](https://user-images.githubusercontent.com/93531870/160167725-9fc98184-d9d9-4c98-a4f9-eaf66f068c85.png) | ![Screen Shot 2022-03-25 at 1 02 13 PM](https://user-images.githubusercontent.com/93531870/160167740-fbe708ce-d257-4a5f-9a34-ed3bd7730c95.png) |

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: permissions-feature-branch
 - Browser and OS: Chrome on Mac

**Comment by harshilsharma63** [comment]
On it.
