### ISSUE TITLE
Bug: Sidebar menus fixed to width of sidebar

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2641]
## Steps to reproduce the behavior

1. Go to any board on Community
2. Click the "..." menu next to a board name on the sidebar
3. See error

## Expected behavior

Menu should pop-out to the right of the sidebar

## Screenshots (optional)

![Screen Shot 2022-03-25 at 1 02 13 PM](https://user-images.githubusercontent.com/93531870/160168858-7fee1658-129c-4920-bf2d-0abb6ff31a6b.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.15.0
 - Browser and OS: Chrome on Mac

**Comment by jespino** [comment]
This is not happening for me. But I'm experiencing a different behavior. I get the menu in the right place where there are no teams, but when there are teams I get the menu shifted to the left.

**Comment by jespino** [comment]
I added a PR fixing that behavior here #2654

**Comment by wuwinson** [comment]
Unable to repro on main - closing out.
