### ISSUE TITLE
Feature Idea: Updated Docker Images?

### ISSUE THREAD

**Issue by zacheryph** [mattermost/focalboard#265]
**Summary:**
The docker image continues to get built (at least daily) but its not actually being updated. Its still a commit from March 11th.

**How important this is to me and why:**
I and I think most people prefer to use _official_ docker images over one offs, or making their own if its not required. If an official image exists it should stay up to date.

Use cases:
1. Docker
2. Docker

**Additional context / similar features:**
_N/A_

**Comment by NoLooseEnds** [comment]
I came to write this exact request. Also, it would be nice to have the release candidate and beta builds there.

**Comment by chmac** [comment]
Maybe this can be closed by now? There is a `mattermost/focalboard` docker container.
