### ISSUE TITLE
Bug: Search text does not search in card and does not reset

### ISSUE THREAD

**Issue by ZevSwe** [mattermost/focalboard#266]
**Summary:**
It seems the search function does not search for anything inside the cards, only on their names. Not sure if this is a feature or a bug.

**Steps to reproduce the behavior:**
1. Create a card with text inside, also add a property with free text and add some tags
2. click on search text in top left and search for anything in the text or any of the free text tags.
3. No card will show
4. As a bonus, nothing will show when you remove your search, to get cards back just resort them on name.

**Expected behavior:**
Searching should happen both on name and content. Name should probably have a higher weight. If I'm done with my search and remove the text the board should return to previous state automatically.

**Platform:**
 - Fire fox for Manjaro Linux 87.0 (64-bit)

**Comment by chenilim** [comment]
Thanks @ZevSwe! The first part (comprehensive search) is a dup of #128.

However, number 4 sounds like a separate bug. Could you list the exact steps you took to "remove your search"? i.e. the following works for me in FireFox 84.0.2 (on macOS 10.15.7):
1. Click on search box
2. Type in text, e.g. "data", press enter
3. Cards are filtered to title
4. Click on search box again, press Esc
5. All cards are shown

Also:
4. Click on search box again, press backspace to delete all text, then press enter
5. All cards are shown

Do those steps work for you? Or did you clear the search another way? Thanks.

**Comment by ZevSwe** [comment]
I've since I've reported this upgraded to the new version and now it seems to work as you describe it, I'll close this thanks!
