### ISSUE TITLE
Bug: Fix Cypress CI tests

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2670]
## Steps to reproduce the behavior

1. Run CI (`make ci`)
2. Fails on Cypress

## Expected behavior

Cypress tests pass

## Screenshots (optional)

<img width="713" alt="Screen Shot 2022-03-29 at 9 54 11 AM" src="https://user-images.githubusercontent.com/46905241/160664996-a3b5d710-d47f-4f0c-8c9b-d0c2c8944673.png">

## Edition and Platform

 - Edition: Personal Desktop / Personal Server / Mattermost Boards (plugin)
 - Version: v0.16 (main)

**Comment by kamre** [comment]
Hi, posted possible fix [here](https://github.com/mattermost/focalboard/pull/2676#issuecomment-1082226961)
