### ISSUE TITLE
Feature Idea: Should we remove subscriptions on remove member?

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2674]
## Summary

When removing a member of a board, should we also remove their subscriptions?

The benefit of this is it will clean up the database, and reduce the potential attack surface.
The con is that when re-joining, the user will have to resubscribe (re-follow) cards.

What is the expectation, based on similar features (channels and threads) in Channels and elsewhere?

## How important this is to me and why

Importance: Medium

**Comment by sbishel** [comment]
> What is the expectation, based on similar features (channels and threads) in Channels and elsewhere?

@wuwinson Assigning to you to answer the question -

**Comment by wuwinson** [comment]
Below are the current behaviours when removing a member from a channel or when a member leaves a channel:

- **Collapsed Threads**
  - Public Channel: User still follows the thread but does not get notifications. Thread history is still accessible, unread indicator is visible for new messages, but user cannot view new messages and cannot post and new messages. 
  - Private Channel: User still follows the thread, but does not get notifications. Can still select the thread on the "Followed Threads" list, but entire thread history is hidden/empty, with no option to send new messages either.
- **Playbook Runs**
  - User still follows the run and gets bot notifications. Can still see the run details in Playbooks.

For consistency with Channels and Playbooks, when we remove members from a Board, we should not remove subscriptions, but we should stop notifications until they rejoin the board.

cc @chenilim @sbishel @asaadmahmood @wiggin77 @jespino

**Comment by chenilim** [comment]
Thanks @wuwinson! Sounds good. As long as we fix https://github.com/mattermost/focalboard/issues/2666, this won't be an issue for now.

The one thing I will call out for the future is: This means that a user follows a card if they are both a member of the board, and a subscriber to the card. E.g. if we later show a list of card followers in the UI, we should restrict that list to members of the board.

The other potential issue @sbishel brought up is we may need to consider cleaning the database if there are many of these "orphaned" subscribers.

In any case, since there is nothing we need to change right now, closing this issue.
