### ISSUE TITLE
Doc: Update focalboard.com header to point to new contributor's guide

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2677]
## Summary

Update the Contribute link on focalboard.com to point to https://developers.mattermost.com/contribute/focalboard/

## Link to documentation page

https://developers.mattermost.com/contribute/focalboard/

## (Optional) Additional context and/or screenshot

See [discussion here](https://community-daily.mattermost.com/core/pl/ab9tphuxnfght8kbkq8ipnd5me) for more context.

**Comment by chenilim** [comment]
@emdecr, not sure if this should go to you or @justinegeffen. In any case, this should be updated on the focalboard.com redesign as well. What's the current ETA? Thanks.

**Comment by BenLloydPearson** [comment]
Thanks @emdecr I tagged you in a request to add this link to our new design.

**Comment by emdecr** [comment]
@chenilim Just to circle back on this – Ben has synced with JuliAnn to add the Contribute link to the designs. We should have the changes developed and ready to review by next EOD Tuesday, Apr 5th. Can we fold this change/PR into the larger redesign branch, or is it pressing to get this edit out?

Also would it be okay to put some time on your calendar to walk me through the existing way to update the site via the AWS console? Just want to make sure I don't crash the site when we're all ready with the dist files 😁

**Comment by chenilim** [comment]
Thanks @emdecr! I think it makes sense to make this change along with the design overhaul. Unless you think this is more pressing @BenLloydPearson?

The process to update the website is [documented here](https://docs.google.com/document/d/11uLGhYYNnsulL1oUAlfFyNcT3wgAiDJmCSvnNkuAbpA/edit#bookmark=id.4ll9apxeg6sr), but happy to walk through it with you. Feel free to grab some time. Ping Daniel Sischy to get access if you haven't already.

Also, separately, it looks like the content under https://github.com/mattermost/focalboard/tree/main/docs has been migrated to https://github.com/mattermost/mattermost-developer-documentation/tree/master/site/content/contribute/focalboard. Once the links have all been switched over (I assume this is the last one), we should delete the `/docs` folder. Was that the plan @azigler?

**Comment by azigler** [comment]
@chenilim Right! None of the files in the `/docs` folder will be used after the design overhaul because everything lives in the shared developer documentation now, as you've mentioned. When the new design goes live, I think we should get rid of `/docs` to reduce clutter and ensure no one gets confused by older documents in the repository.

**Comment by emdecr** [comment]
@chenilim Circling back to close this since the website is live. Thanks!
