### ISSUE TITLE
UX: Gallery view should have top border

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2681]
## Summary

The top row of the Gallery view currently is right next to the header line:

<img width="1274" alt="Screen Shot 2022-03-29 at 1 26 35 PM" src="https://user-images.githubusercontent.com/46905241/160701128-e12d2e2b-a7bc-41a6-abdf-f9d9197f23c4.png">

There should be a space to be consistent with the board view:

<img width="1387" alt="Screen Shot 2022-03-29 at 1 27 48 PM" src="https://user-images.githubusercontent.com/46905241/160701165-8928122f-98db-4d28-bd25-97100be758d4.png">

## How important this is to me and why

Importance: Low, UX fit and finish

Note:
This repos on v0.15, and may have been this way for a while.

**Comment by TylerStilson** [comment]
I would love to help with this issue?

**Comment by chenilim** [comment]
You got it! Thanks.

**Comment by TylerStilson** [comment]
#2725
