### ISSUE TITLE
Bug: 配置后再重启，配置又恢复原样。

### ISSUE THREAD

**Issue by ms8great** [mattermost/focalboard#2693]
比作，设置成中文后，重启又恢复英文界面。

**Comment by wuwinson** [comment]
**Translation:**

After the configuration is restarted, the configuration is restored to its original state.

For example, after setting it to Chinese, restart and restore the English interface

**Comment by ogi-m** [comment]
@wuwinson Duplicate of https://github.com/mattermost/focalboard/issues/2001

**Comment by wuwinson** [comment]
Thanks @ogi-m! Closing out this ticket.
