### ISSUE TITLE
Bug: Undo delete board doesn't always restore view and cards

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#2696]
ReOpen of - 
https://github.com/mattermost/focalboard/pull/2079

## Steps to reproduce the behavior

1. Delete a board (and confirm)
2. Press Cmd+Z (Ctrl+Z on Win) to undo
3. The board re-appears, but not the views or cards

## Expected behavior

Undo delete board should restore its views and cards as well.

## Screenshots

https://user-images.githubusercontent.com/46905241/148794862-55ece06f-8e95-4986-af2e-f1da41eaa016.mov

I'm reopening this issue as it's regressed in v0.16.0

![image](https://user-images.githubusercontent.com/13020833/161037270-b9f1df8b-bbf7-4395-9e31-2546b1f858a4.png)

**Comment by wuwinson** [comment]
Need to retest on bugbash server

**Comment by jespino** [comment]
@wuwinson any news about this, has you re-tested it?

**Comment by wuwinson** [comment]
@jespino Re-tested and unable to repro. Closing out.
