### ISSUE TITLE
Permissions Branch: New sidebar categories get added for everyone

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2707]
## Steps to reproduce the behavior

1. Go to any category in the new sidebar
2. Select the  "..." menu
3. Click on "Create New Category"
4. Name the category
5. Log into to a different account
6. See the new category in users sidebar
7. Switching to Channels then back to Boards fixes this and only displays the categories the user should be seeing.

## Expected behavior

Categories should only be visible to the user who created them, and should not get added to another user's sidebar.

## Screenshots (optional)
| User A  | User B |
|--|--|
| ![Screen Shot 2022-04-01 at 12 29 37 PM](https://user-images.githubusercontent.com/93531870/161305357-2cf91a67-6bc2-44e1-b933-9b256a897180.png) | ![Screen Shot 2022-04-01 at 12 29 24 PM](https://user-images.githubusercontent.com/93531870/161305377-544a218c-5618-40ed-be2d-12afed76fab8.png) |

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: permissions-feature-branch
 - Browser and OS: Chrome on Mac

**Comment by harshilsharma63** [comment]
@wuwinson created a PR for this. The issue was only with displaying of the categories.
