### ISSUE TITLE
Permissions Branch: Description text overlaps property menu on hover over

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2708]
## Steps to reproduce the behavior

1. Open a card
2. Add description text the card if none exists
3. Select or create a new multi-select property with many options (10+) so that it expands into the description section
4. Scroll down to the description section while the multi-select menu is still open
5. Hover over the description without clicking on it
6. See error

## Expected behavior

Property menu should remain above the description section

## Screenshots (optional)
![Screen Shot 2022-04-01 at 1 11 14 PM](https://user-images.githubusercontent.com/93531870/161311180-60befc37-65f4-4786-bb3f-69dc3d3f60cd.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: permissions-feature-branch
 - Browser and OS: Chrome on Mac

**Comment by chenilim** [comment]
@asaadmahmood, please investigate. Is this a regression?
