### ISSUE TITLE
Permissions Branch: Missing channel intro link to Boards

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2709]
## Steps to reproduce the behavior

1. Create a new channel or DM
2. See error

## Expected behavior

"Create a board" link should be on the channel intro

## Screenshots (optional)
![Screen Shot 2022-04-01 at 1 30 57 PM](https://user-images.githubusercontent.com/93531870/161313593-ee4f216b-93a3-4c93-8fe5-16d5155701db.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: permissions-feature-branch
 - Browser and OS: Chrome on Mac

**Comment by chenilim** [comment]
Looks like we just need to update the server version.

**Comment by sbishel** [comment]
Investigated, when the app bar feature flag is on this doesn't work. Updating in mattermost-webapp.

Also the link still goes to "workspace", updating to "team"
