### ISSUE TITLE
Permissions Branch: Users should not be allowed to create multiple categories with the same name

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2711]
## Summary

Currently there are no restrictions on creating duplicate category names in the new sidebar, but when there are multiple categories with the same name, it becomes difficult to navigate moving boards.

## How important this is to me and why

Importance: Low

Use cases:
1. Users moving boards from one category to another

![Screen Shot 2022-04-01 at 1 43 49 PM](https://user-images.githubusercontent.com/93531870/161316005-bf2c2173-3121-4ac3-8ea3-a86a9fc01e55.png)

**Comment by chenilim** [comment]
Decided to won't fix for now - because the categories are created by the user.
