### ISSUE TITLE
Bug: White space in place of the team sidebar if there's only one team

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#2713]
## Steps to reproduce the behavior

1. Create a server with a single team
2. Open boards
3. Note the white space on the left

## Expected behavior

There should be no space to the left of the sidebar

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/15314183/161321844-853d5c81-25b2-49ba-9a15-9f6804c01144.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.16.0]
 - Browser and OS: Chrome on Windows

**Comment by wuwinson** [comment]
@ogi-m Can you verify if this is fixed and close out this ticket? Thanks!

**Comment by ogi-m** [comment]
Verified this is fixed.
