### ISSUE TITLE
Permissions Branch: Modal menus are cutoff

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2714]
## Steps to reproduce the behavior

Share board modal
1. Go to share board modal
2. Add a few users to the board
3. Find a user towards the bottom of the share board modal that was recently added to the board
4. Select the role dropdown to change their role
5. See error - menu is cut toff

Card view modal
1. Open a card
2. Create a multi-select property and add 10+ values
3. Click on the multi-select field to assign a value
4. See error - menu is cut off

## Expected behavior
Modal should auto scroll down so user can see the full height of the menu.

## Screenshots (optional)
![Screen Shot 2022-04-01 at 2 01 52 PM](https://user-images.githubusercontent.com/93531870/161321186-9faa08d1-f344-40e2-844f-4c81bf98fa6c.png)
![Screen Shot 2022-04-01 at 2 29 09 PM](https://user-images.githubusercontent.com/93531870/161322016-d12d9e39-8636-41c8-bbf9-66be5dc526d5.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: permissions-feature-branch
 - Browser and OS: Chrome on Mac

**Comment by chenilim** [comment]
@asaadmahmood please investigate. Thanks.
