### ISSUE TITLE
Bug: CreateCategories fails on Postgres and MySQL

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2717]
## Steps to reproduce the behavior

1. Call the createCategories API on a Postgres DB
2. Error, e.g.:
```
error  [2022-04-01 21:43:40.341 Z]  Error creating category  category name="Test category" error="pq: invalid input syntax for integer: "7nwnj6c3jotn7jm4d1hnbk9ztac""
```
## Expected behavior

API works

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.16 (main)

## Additional context (optional)

The [table schema](https://github.com/mattermost/focalboard/blob/main/server/services/store/sqlstore/migrations/000018_populate_categories.up.sql#L3) is varchar for SQLite (which works), but Serial for Postgres and INT for MySQL.

**Comment by jespino** [comment]
This should be a VARCHAR for all or an AUTO_INCREMENT for all, @harshilsharma63 what do you think? Should we follow the existing patterns of passing our own generated IDs?
