### ISSUE TITLE
Bug: latest main crashing on startup

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#2728]
## Steps to reproduce the behavior

1. Fetch latest main
2. Deploy as plugin
3. See migration error

## Edition and Platform

 - Edition: plugin
 - Version: latest main
 - Browser and OS: [e.g. Chrome on Mac, Edge on Windows]

## Additional context (optional)
https://github.com/mattermost/focalboard/pull/2697 introduced an error in data migration. 

```
Failed: failed to upload plugin bundle: : Unable to restart plugin on upgrade., error initializing the DB: driver: postgres, message: failed to execute migration, command: executing_query, originalError: pq: column "channel_id" of relation "focalboard_categories" does not exist, query: 

ALTER TABLE focalboard_categories ALTER COLUMN id TYPE VARCHAR(36);
ALTER TABLE focalboard_categories ALTER COLUMN id SET NOT NULL;
ALTER TABLE focalboard_category_blocks ALTER COLUMN id TYPE VARCHAR(36);
ALTER TABLE focalboard_category_blocks ALTER COLUMN id SET NOT NULL;
ALTER TABLE focalboard_categories ALTER COLUMN channel_id TYPE VARCHAR(36);
ALTER TABLE focalboard_categories ALTER COLUMN channel_id DROP NOT NULL;
```
 The column is dropped in migration 000017:
https://github.com/mattermost/focalboard/blob/d8d942519096c72575d71a8c77f2ee6fc10a7660/server/services/store/sqlstore/migrations/000019_populate_category_blocks.up.sql#L31

But also added back in 00021 but only for sqlite.

**Comment by chenilim** [comment]
More details in the [thread here](https://community-daily.mattermost.com/core/pl/cfdmb7awj7ytmbjbsuxhxwpc4c).

**Comment by wiggin77** [comment]
Fixed via https://github.com/mattermost/focalboard/pull/2739
