### ISSUE TITLE
Bug: Boards channel shortcut opens new window in Safari

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2730]
## Steps to reproduce the behavior

1. From the Safari browser, go to any channel (i.e. [https://community.mattermost.com/core/channels/focalboard](https://community.mattermost.com/core/channels/focalboard))
2. Click on the Boards icon in the channel header
3. See error - Board opens up in a new window

## Expected behavior

The corresponding board for that channel should load in a new tab

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.15.0
 - Browser and OS: Safari on Mac

**Comment by ogi-m** [comment]
@wuwinson dupe of https://github.com/mattermost/focalboard/issues/1716 ?
