### ISSUE TITLE
Bug: Mac App updates don't appear until refreshed

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2731]
## Steps to reproduce the behavior

1. Open the Mac App
2. Open a board, and make a change (e.g. move a card to another column)
3. The UI doesn't update
4. Select "Home" from the File menu (which does a refresh) - the UI updates

## Expected behavior

The UI should update on change

## Edition and Platform

 - Edition: Personal Desktop
 - Version: v0.16 (main)
 - Browser and OS: Mac

## Additional context (optional)

This also repros if you run the server in single-user mode. The issue appears to be that [BroadcastBlockChange](https://github.com/mattermost/focalboard/blob/main/server/ws/server.go#L532) does not work for single-user mode. This likely affect other actions (add, delete, etc.) as well.

**Comment by lindy65** [comment]
I'm seeing the same issue where updates/changes aren't displayed until after a refresh and/or changing views and going back to the previous view.  Examples are adding a status and adding a property.
