### ISSUE TITLE
Code debt - improve CI run times

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2745]
## Summary

CI tests currently take around 30m in GitHub.

One area we can improve is the template init - which takes around 8 seconds on GitHub, multiplied by 130+ times (for a total of 17 minutes). From the last dev meeting, the proposal is to reduce or skip this for most tests (except the ones that test the templates).

## How important this is to me and why

Importance: Medium

**Comment by chenilim** [comment]
cc @wiggin77 - followup from the dev meeting. Go ahead and grab it if you wanted to start working on it. Thanks.

**Comment by wiggin77** [comment]
@chenilim https://github.com/mattermost/focalboard/pull/2748 has brought the CI job down to 14 minutes.
