### ISSUE TITLE
Code debt: refactor `z-index`s into SCSS map

### ISSUE THREAD

**Issue by Pinjasaur** [mattermost/focalboard#2746]
## Summary

Refactor CSS `z-index` properties into a single SCSS `map`.

When reviewing #2727 I suggested it as a future refactor / code debt item. The benefit is it consolidates all the `z-index` occurrences into a single place to help manage them as ultimately they're effectively context-less arbitrary integers otherwise.

## How important this is to me and why

Importance: Low

## Additional context/similar features

1. Create a new file (or re-use an existing centrally `@import`-ed one) e.g. `_z-index.scss` which contains a map e.g.

	  ```scss
	  // Keep in descending order to aid in visual grepping
	  //
	  // Usage:
	  // map-get($z-index, <key>)
	  
	  $z-index: (
	    // key: value
	  );
	  ```

2. Refactor `z-index` occurrences to the new `map-get($z-index, key)` pattern

Links:
- https://jonsuh.com/blog/organizing-z-index-with-sass/
- https://css-tricks.com/handling-z-index/

**Comment by wuwinson** [comment]
Let's take this post v0.16.
