### ISSUE TITLE
[Tech Debt]: Review log level at server side.

### ISSUE THREAD

**Issue by jespino** [mattermost/focalboard#2750]
We are logging a lot of stuff in the server side at Error, Info, Warn and Debug level.

We should have a clear vision of what is each level for and avoid any message that is not directly useful for the administrator (useful means he can do something or can to send that data to US to do something).

Any log that is not useful for the administrator (based on the previous definition) should be in the `Debug` level.

**Comment by jespino** [comment]
@wiggin77 I assigned it to you because I'm out the whole week next week, feel free to reassign it or give it back to me if you want, but I'll do it, in the best scenario, after the next week.

**Comment by wiggin77** [comment]
Also `BroadcastingXXXChange` are output at `INFO` level and should be `DEBUG.`
```
{"timestamp":"2022-04-14 17:33:47.130 Z","level":"info","msg":"BroadcastingBoardChange","caller":"app/plugin_api.go:937","plugin_id":"focalboard","teamID":"giyjmbra97nnfrxz71hoaoboco","boardID":"b35szx6f5o7n1iyn1mr5oz8xheo"}
{"timestamp":"2022-04-14 17:33:47.281 Z","level":"info","msg":"BroadcastingMemberChange","caller":"app/plugin_api.go:937","plugin_id":"focalboard","teamID":"giyjmbra97nnfrxz71hoaoboco","boardID":"b35szx6f5o7n1iyn1mr5oz8xheo","userID":"zc3jz8a393ghiret31ehrdfe8a"}
```
