### ISSUE TITLE
Bug: esLint rules have been disabled.

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#2769]
## Steps to reproduce the behavior

A number of eslint rules are no longer being enforced. It looks like we removed the default mattermost in this PR:
https://github.com/mattermost/focalboard/pull/2642

## Expected behavior

Default eslint rules should be enabled and enforced.

## Additional context (optional)

The custom rule that's in our ESLint plugin was causing problems with the new version of ESLint, so that's probably related to why it was removed. I thought we were going to remove that rule from the plugin so that we could keep using the shared config though.

**Comment by chenilim** [comment]
Link to [thread with Harrison](https://community-daily.mattermost.com/core/pl/tnbb7if4mbbg7po9r3qp6qy4pr).
