### ISSUE TITLE
Bug: Content drag grip should not appear on shared read-only boards

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#277]
Importance: P3

**Steps to reproduce the behavior:**
1. Open or create a card
2. Add 2 or more content blocks
2. Share the board
3. Open an incognito window and open the readonly shared board link
4. Open the card
5. Hovering over the content shows the rearrange grip

**Expected behavior:**
Users should not see the drag grip if a board is read-only.

**Platform:**
 - Chrome 89 on macOS 10.15.7

**Additional context:**
Dragging and dropping the content doesn't actually rearrange it if readonly, but the user should not see the grips.

**Comment by Johennes** [comment]
I'd like to help fix this and have submitted #294.
