### ISSUE TITLE
Bug: Template screen is not properly visible on Windows 10 Standalone Boards App

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#2775]
This issue has appeared in Rainforest since https://github.com/mattermost/focalboard/issues/2593 was fixed. 

This does NOT reproduce locally for me on my Win10 laptop (could it be because I had a previous version of Boards installed?). I have asked Rainforest support to look into the issue on their VMs.

## Steps to reproduce the behavior

1. Download and install the AWS Windows 10 standalone app (https://focalboard-builds.s3.amazonaws.com/latest/focalboard-win.zip)
2. Once the app is open, maximise the screen
3. Observed: Template screen is not fully visible and it's not possible to scroll up to view it (see screenshot below)
4. **NOTE**: I'm also seeing text at the top of the screen `Members of "" will have access to Boards created here`. Is this text relevant to the standalone app?

## Expected behavior

Template screen is fully visible

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/13020833/163123708-7a72d6fb-7239-4ce6-9556-5a0ee050532e.png)

## Edition and Platform

 - Edition: Personal Desktop
 - Version: v0.16.0 AWS
 - Browser and OS: Windows 10 / Chrome

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround

**Comment by chenilim** [comment]
Dup of https://github.com/mattermost/focalboard/issues/2770, which was just fixed.

**Comment by lindy65** [comment]
Thanks @chenilim - sorry, missed that there was already an issue for this bug.

**Comment by chenilim** [comment]
Not a problem @lindy65! I noticed this after the last fix, and fixed it too. Meant to ping you, but after this is in, the Windows and Mac App builds should be working now - let's see if there are any other tests are failing after that. Thanks.

**Comment by lindy65** [comment]
Thanks Chen, will let you know :)
