### ISSUE TITLE
Bug: Should not be able to drag items in shared read-only gallery view

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#278]
Importance: P3

**Steps to reproduce the behavior:**
1. Open or create a gallery view with multiple cards
2. Share the board
3. Open an incognito window and open the readonly shared board link
4. Try to drag a card in the gallery view
5. Able to drag, but dropping has no effect

**Expected behavior:**
Should not be able to start the drag on a readonly view

**Platform:**
 - Chrome 89 on macOS 10.15.7

**Additional context:**
There are likely other related UI issues on readonly shared boards.

**Comment by Johennes** [comment]
I took a stab at this and submitted a fix in #293.
