### ISSUE TITLE
Bug: Unable to create new boards (tested on psql)

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#2786]
## Steps to reproduce the behavior

On today's `main`, unable to create new boards . 

Error from postgres -

```
pq: null value in column "insert_at" violates not-null constraint
```

**Comment by ogi-m** [comment]
Probably related to https://github.com/mattermost/focalboard/issues/2791

**Comment by wiggin77** [comment]
Strange.  All the `insert_at` fields should now have defaults defined for the column.  The only way I can see this happening is if some data generated with older code (before yesterday's migration PR merge) had null there.

**Comment by sbishel** [comment]
Retested. Issue was with unsupported migration.
