### ISSUE TITLE
Bug: The screen gets stuck after clicking on the Use this template button on create a board screen

### ISSUE THREAD

**Issue by Rajat-Dabade** [mattermost/focalboard#2787]
## Steps to reproduce the behaviour

1. Create a new board
2. Select the Welcome to Board option
3. Click on use this template
![Screenshot 2022-04-14 at 2 54 23 PM](https://user-images.githubusercontent.com/26198062/163356123-f7065d5f-eec0-44e0-a092-22fa6f08d6c0.png)

## Expected behaviour
A new board should be created with the product tour.

## Screenshots (optional)

If applicable, add screenshots or a screen recording to elaborate on the problem.

## Edition and Platform

 - Edition:  Mattermost Boards (plugin)
 - Version: [e.g. v0.16.0]
 - Browser and OS: Chrome on Mac

**Comment by Pinjasaur** [comment]
@Rajat-Dabade I tried to reproduce this today using both FF & Chrome on Mac and am unable. Tried 2 different users on the bugbash server to see if there was something state related and didn't have any luck. The 'Welcome to Boards!' onboarding flow seems to work fine with my testing. Could you attach a short video?

**Comment by Rajat-Dabade** [comment]
@Pinjasaur @harshilsharma63 @sbishel  Today, I tried to reproduce this issue with the new deployment on the BugBash-board2 test server but was not getting the same error was working fine. I think this issue is no more, probably we can close this issue.

**Comment by sbishel** [comment]
Closing as cannot repo
