### ISSUE TITLE
Bug: Unable to open publically shared boards

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#2789]
## Steps to reproduce the behavior

1. Share a board publically.
2. Copy the URL and try opening it up in incognito.

Notice that board doesn't load up and the following errors - 
<img width="735" alt="Screenshot 2022-04-14 at 3 17 41 PM" src="https://user-images.githubusercontent.com/18575143/163360051-6bc805a1-02c4-4577-9842-d1fa05577ddd.png">

**Comment by sbishel** [comment]
Retested, appears to still be an issue.

**Comment by sbishel** [comment]
Caused by this change (https://github.com/mattermost/focalboard/commit/89cc947a21e0d7eee9080e5b887885e55f2f6e78#diff-66710a42b385d093492613702b1b7ac5957299970761bbf6717012e01d1fabadL212)
