### ISSUE TITLE
Bug: lost  "Simplified Chinese"/简体中文 option

### ISSUE THREAD

**Issue by MrBear2018** [mattermost/focalboard#279]
**Summary:**
when I set the language as Chinese , the language is traditional Chinese,but lost the option of simplified chinese.

**Steps to reproduce the behavior:**
1. Go to  Settings
2. Click on Set language
3. Scroll down to "Chinese"
4. the language of software changed into traditional chinese

**Expected behavior:**
there should be two chinese language options, "Traditional Chinese"/"繁体中文", "Simplified Chinese"/"简体中文", the target json file is :
"Traditional Chinese"/"繁体中文" <---> zh_Hant.json
"Simplified Chinese"/"简体中文"  <---> zh_Hans.json
----
Expected behavior in Chinese: / 中文描述：
语言设置项缺失简体中文选项卡

**Screenshots:**
![image](https://user-images.githubusercontent.com/45927673/114960104-f7877780-9e98-11eb-9704-2fb8bb8ab273.png)

**Platform:**
 - Ubuntu 18.04

**Additional context:**

**Comment by chenilim** [comment]
Thanks @MrBear2018! @jespino, do you know if this was a regression, or is this language just not added yet? Thanks.

**Comment by jespino** [comment]
Done!
