### ISSUE TITLE
Bug: Error when copying a default template card - "This card doesn't exist or is inaccessible"

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#2790]
## Steps to reproduce the behavior

1. Create a board from a defaulttemplate
2. Click on `...` on a pre-made card
3. Click "Duplicate card"
4. A few redirects happen and the user lands on a card with the "This card doesn't exist or is inaccessible" error

## Expected behavior

Card gets copied without redirects or errors

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/15314183/163360284-63837c62-d754-4b75-89b4-5a4bd42ff497.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.16
 - Browser and OS: Chrome on Windows

**Comment by sbishel** [comment]
Retested, unsupported migration issue.
