### ISSUE TITLE
Bug: Error when trying to move a board to a different category

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#2791]
## Steps to reproduce the behavior

1. Create a category in the sidebar
2. Click `...` next to a Board title and click Move To
3. Select the category created in step 1
4. Board isn't moved and error 500 is thrown

## Expected behavior

Board is successfully moved to the selected category

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/15314183/163363955-32fb7950-4abb-4dc2-a909-3c08d0285e4d.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.16.0
 - Browser and OS: Chrome on Windows

**Comment by ogi-m** [comment]
500 is also thrown when trying to duplicate a board or create a new template from a board

**Comment by sbishel** [comment]
Retested, unsupported migration issue.
