### ISSUE TITLE
Bug: Permissions - adding a user results in 500 error most of the time

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#2792]
## Steps to reproduce the behavior

1. Open aboard, try adding a user into it from the share board modal and notice API errors-

https://user-images.githubusercontent.com/18575143/163382699-fa40499a-5345-4d05-ab6b-59c4e4c96b00.mp4

**Comment by sbishel** [comment]
Retested, unsupported migration issue.
