### ISSUE TITLE
Bug: Permissions - User can still continue viewing the board even after being removed from it

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#2794]
## Steps to reproduce the behavior

1. Create a private board and add a user to it.
2. Open this board from the other user's account in a separate browser or somewhere.
3. Remove the second user's access to the board.
4. Notice that the user can still see the board in the other window. They can't perform any updates though and performing a refresh removes the board.

## Expected behavior

A user should immediately be kicked out of the board as soon as they are removed from it, even if they are currently viewing that board,

**Comment by sbishel** [comment]
Retested, unsupported migration issue.
