### ISSUE TITLE
Bug: Unexpected "Team 2" Board in sidebar for new users

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2796]
## Steps to reproduce the behavior

1. Register a new Mattermost user
2. Login and open Boards for the first time
3. Skip the welcome tour (optional)
4. See a "Team 2" Board in the sidebar

## Expected behavior

Sidebar should be empty until I add or open a board.

## Screenshots (optional)

<img width="249" alt="Screen Shot 2022-04-14 at 7 55 26 AM" src="https://user-images.githubusercontent.com/46905241/163417903-6337deee-d9c7-46e7-99a6-d7a2179cf794.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.16 (bugbash)
 - Browser and OS: Chrome on Mac

## Additional context (optional)

The sharing panel shows that everyone on the team is an Editor, and my account (chen2 in this case) is also an explicit editor:

<img width="619" alt="Screen Shot 2022-04-14 at 8 00 46 AM" src="https://user-images.githubusercontent.com/46905241/163418096-d9541694-d1e3-4c91-83bf-9bfcfc101efe.png">

**Comment by wuwinson** [comment]
Looks like new users are auto-added as board members on public boards. Signed up with a new user and saw all the following boards on the sidebar when going to Boards for the first time. When checking the permissions, the user "mattmoss" is an explicit member with the "Editor" role on all boards. User should not be an explicit member on all public boards unless the user joins it themselves or is added by another user.

![Screen Shot 2022-04-14 at 1 07 38 PM](https://user-images.githubusercontent.com/93531870/163438978-54faa98a-d7a0-4994-98cf-0b1b6cc3db0e.png)

**Comment by chenilim** [comment]
Update: As other users set boards to public, they appear in my sidebar. Hypothesis: The GetBoards API is likely returning all public boards. Need to revisit that.

**Comment by wuwinson** [comment]
Noticed this occurs when I go from Boards > Channels > Boards. My sidebar adds all new public boards.
