### ISSUE TITLE
Bug: Follow button is not right-aligned in card dialog

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2797]
## Steps to reproduce the behavior

1. Open a card
2. Follow button appears in the top center

## Expected behavior

Follow button should be right-aligned, to the left of the ... menu

## Screenshots (optional)

<img width="820" alt="Screen Shot 2022-04-14 at 7 37 23 AM" src="https://user-images.githubusercontent.com/46905241/163418432-cf9624e4-de49-4ede-b887-0f69581077c1.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.16 (bugbash)
 - Browser and OS: Chrome on Mac

**Comment by Pinjasaur** [comment]
Manually diffing this against community looks like there might have been a regression with a `class` and/or some CSS. Regardless, looks like previously it was 16px spacing.

![image](https://user-images.githubusercontent.com/6335792/164026331-b9f59861-0e61-4f05-a630-0326ed4c6c02.png)
