### ISSUE TITLE
Bug: Team sidebar shows notifications from channels

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#2802]
## Steps to reproduce the behavior

1. As user-1 make sure you're a member of 2 (or more) teams
2. As user-1 open Boards
3. Log in in another browser as user-2 and at-mention user-1 in a channel
4. As user-1 observe the team sidebar - there's a notification icon for the at-mention on the appropriate team

## Expected behavior

Channel message notifications should probably not show up on the team sidebar in Boards as it can't be viewed or cleared?

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/15314183/163439920-ef115370-dfed-4b56-a45e-6b8111210da7.png)

## Edition and Platform

 - Edition:  Mattermost Boards (plugin)
 - Version: v0.16.0
 - Browser and OS: Chrome on Windows

**Comment by chenilim** [comment]
My initial impression is we should **not** indicate unread messages in the team picker in Boards. In the Mattermost Desktop app, there are separate tabs per vertical. Longer-term, we need to decide how to handle notifications in general (board-specific ones vs. channels, etc.). cc @asaadmahmood, @wuwinson.

One more addition: I reproed this, and if you clear the unread count in Channels, the indicator doesn't go away in Boards until a refresh.

**Comment by harshilsharma63** [comment]
Created PR in mattermost webapp - https://github.com/mattermost/mattermost-webapp/pull/10203

**Comment by harshilsharma63** [comment]
Webapp PR merged.
