### ISSUE TITLE
Bug: Random icon's icon is too large, and the same as the "Pick icon" icon

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2805]
## Steps to reproduce the behavior

1. Select the icon on a Board
2. Notice that the icon for "Random icon" is larger than the other one
3. It is also the same icon

## Expected behavior

Icons should be a consistent size, and (probably) different.

## Screenshots (optional)

<img width="266" alt="Screen Shot 2022-04-14 at 10 33 54 AM" src="https://user-images.githubusercontent.com/46905241/163442989-b493d626-a413-435c-a010-f948f84e65c3.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.16 (bugbash)
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment]
@asaadmahmood Can you decide on the icon and set the appropriate size? Thanks!
