### ISSUE TITLE
UX Bug: FireFox shows a black rectangle for Empty Card templates

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2807]
## Steps to reproduce the behavior

1. Open a board
2. Select the dropdown next to the New button
3. Notice a black rectangle for the "Empty Card" template, which is off-center

## Expected behavior

A centered icon, and consistent across browsers.

## Screenshots (optional)

<img width="269" alt="Screen Shot 2022-04-14 at 10 43 17 AM" src="https://user-images.githubusercontent.com/46905241/163445858-d7b8a1fe-474c-4618-987b-d8acc8f1017b.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.16 (bugbash)
 - Browser and OS: FireFox on Mac

## Additional context (optional)

Note that there is no icon on other browsers.

**Comment by Rajat-Dabade** [comment]
Fixed. https://github.com/mattermost/focalboard/pull/2849

**Comment by sbishel** [comment]
Closing issue, already fixed.
