### ISSUE TITLE
Bug: Unexpected error in log every time an editor opens the Share dialog

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#2808]
## Steps to reproduce the behavior

1. Be an editor on a board (not board creator/admin)
2. Click the `Share` button
3. Dialog displays fine, but an error is always generated in log:

```
{"timestamp":"2022-04-14 17:44:33.763 Z","level":"error","msg":"API ERROR","caller":"app/plugin_api.go:940","plugin_id":"focalboard","code":"403","error":"\"access denied to sharing the board\"","_msg":"","api":"/api/v2/boards/bq495ankeu7gr5jjagaa1h73rme/sharing"}
```

## Expected behavior

No error in log

## Edition and Platform

 - Edition: plugin
 - Version: v0.16 bug bash
 - Browser and OS: Linux FF 93

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by sbishel** [comment]
Possibly related to https://github.com/mattermost/focalboard/pull/2719 (v0.15)
