### ISSUE TITLE
Bug: 500 error when clicking Follow button

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#2811]
## Steps to reproduce the behavior

1. Click on another user's open board
2. Notice you become editor
3. Open a card
4. Click `Follow`
5.  Error appears in logs
6. Clicking `Following` to unfollow does nothing
```
{"timestamp":"2022-04-14 17:48:45.153 Z","level":"error","msg":"API ERROR","caller":"app/plugin_api.go:940","plugin_id":"focalboard","code":"500","error":"\"{cz7agu4hahfgr8xkeukbasqq1br,6sa5t9dwbfgdxj89w9qrxt7m1y} not found\"","_msg":"","api":"/api/v2/subscriptions/cz7agu4hahfgr8xkeukbasqq1br/6sa5t9dwbfgdxj89w9qrxt7m1y"}
```

## Expected behavior

No error

## Screenshots (optional)

If applicable, add screenshots or a screen recording to elaborate on the problem.

## Edition and Platform

 - Edition: Personal Desktop / Personal Server / Mattermost Boards (plugin)
 - Version: [e.g. v0.15.0]
 - Browser and OS: [e.g. Chrome on Mac, Edge on Windows]

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by sbishel** [comment]
I can not duplicate on the Main branch. It may have been fixed by another PR.
@wiggin77 Can you try to duplicate on the Main branch.

**Comment by wiggin77** [comment]
I try to reproduce when the bug bash test server is updated with latest code.

**Comment by wiggin77** [comment]
I did not reproduce this in latest bug bash.  Closing.
