### ISSUE TITLE
Bug: Template viewers should not see edit icon in template picker

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2812]
## Steps to reproduce the behavior

1. Create a board template
2. Select Share
3. Set team permissions to none (make it private)
4. Set another user (e.g. user2) as a viewer
5. Log in as user2
6. Select + to create a new board
7. See the delete and edit icons in the template picker

## Expected behavior

Should not see the edit button if not an editor.
Should not see the delete button if not an admin.

## Screenshots (optional)

<img width="251" alt="Screen Shot 2022-04-14 at 10 53 42 AM" src="https://user-images.githubusercontent.com/46905241/163448978-494e2416-b7fc-4fd5-b8ee-47b37c5ffece.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.16 (bugbash)
 - Browser and OS: Chrome on Mac

## Additional context (optional)

If you try to edit the template, it opens it in a read-only view.

Related to #2803.

**Comment by wuwinson** [comment]
Related to #2803
