### ISSUE TITLE
Bug: `<Editable>` has an `undefined` class if `className` isn't defined

### ISSUE THREAD

**Issue by Pinjasaur** [mattermost/focalboard#2813]
## Steps to reproduce the behavior

1. Go to a table view
2. Inspect one of the `<Editable>` components e.g. `<input class="Editable">` in the DOM
3. Note the addition of a literal `undefined` to the class e.g. `<input class="Editable undefined">`

## Expected behavior

Don't have a literal `undefined` end up in the class.

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/6335792/163449246-b1045b9f-8013-4f5d-93cc-a3d4c4d88e08.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.16.0 (bugbash)
 - Browser and OS: Firefox 100 on MacOS 12.3.1 (M1)

## Additional context (optional)

Sev 3: low importance.

Likely can be resolved with the addition of a check for the `className` prop in the `editable.tsx` component, similar to existing `readonly` prop. https://github.com/mattermost/focalboard/blob/923437cc573ca515e17c67b56b09436ae9014e0c/webapp/src/widgets/editable.tsx#L90

**Comment by Rajat-Dabade** [comment]
Fixed
![Screenshot 2022-04-20 at 7 32 45 PM](https://user-images.githubusercontent.com/26198062/164251651-49456a61-bb58-4a17-add7-d9f326c25716.png)
