### ISSUE TITLE
How can I filter and see tasks "Assigned to me "

### ISSUE THREAD

**Issue by LimitlessDonald** [mattermost/focalboard#2825]
Hi guys, thanks for your work on this software . 

I can't seem to figure out  a way to filter tasks "Assigned to me"

I know there is a way to add a "person" property , but there is no way to filter based on that property 

I would also like to kindly mention that when a person is added to a task using the "person" property an alert is not sent to the person/user

**Comment by LimitlessDonald** [comment]
Hello, anyone please?

**Comment by wuwinson** [comment]
@LimitlessDonald Thanks for reaching out! It's currently not possible to filter by a person property, but something we plan to address in the future. We're tracking this issue via #1732. As a temporary workaround, "Select" properties are filterable, so you can create a "Select" property and populate it with the names of the people on you wanted to include as "assignees".

We're also planning to address "person" property notifications in the near future. Please see [this card](https://community.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/b4ctmm917q3rzdfi451qtuxjzcw/vuswsftt1rb873datosmmbtwkpa/cgasaqrb9ffg8p867yrefs1t8fc) for reference. In the meantime, you can manually @mention your assignees on the card to [trigger a notification and set them as followers on the card](https://docs.mattermost.com/boards/work-with-cards.html#receive-updates).

Closing out this ticket, but please feel free to reach out to us on [~Focalboard](https://community.mattermost.com/core/channels/focalboard) if you have any other questions!
