### ISSUE TITLE
Bug: Remove "Viewer" roles from Permissions UI

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2836]
#### Boards permissions modal
1. Go to Permissions modal on any board
2. Select a board member
3. Open the role drop down
5. See error - "Viewer" role should be hidden

#### Custom template permission modal
1. Go to Permissions modal on the custom template editor
2. Select a template board member
3. Open the role drop down
5. See error - "Viewer" role should be hidden

## Expected behavior

Viewer role should be hidden from the UI in v0.16 until we add support for [minimum roles on public boards](https://docs.google.com/document/d/1hQAjl-4FFaEVCVYtU2BtyGxA97hcnNxCBDSnpnDT_cw/edit#bookmark=id.6x62zwca7fce). No changes needed for our API - we will add a note in our docs to warn users not to use the "Viewer" role in the short term.

## Screenshots (optional)

![Screen Shot 2022-04-18 at 5 45 28 PM](https://user-images.githubusercontent.com/93531870/163882806-ad85d082-5e49-4ba7-9c18-f10e7134fb60.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.16
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment]
cc @chenilim @sbishel

**Comment by sbishel** [comment]
@jespino - You can now submit this fix directly to `release-0.16`

**Comment by jespino** [comment]
It is not confirmed that we want to remove that yet, it depends a bit on the minimal role/default role discussion that is still ongoing.

**Comment by jespino** [comment]
@wuwinson Ok, then lets keep this rolling. I can fix this quickly.

**Comment by wuwinson** [comment]
Thanks @jespino!

**Comment by jespino** [comment]
@wuwinson submitted

**Comment by wuwinson** [comment]
Awesome, thanks @jespino!
