### ISSUE TITLE
Bug: Links don't open on Linux Desktop App

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#284]
**Steps to reproduce the behavior:**
1. Open Linux Personal Desktop
2. Create a card
3. Add a link to markdown, e.g. `This is a [link](http://www.focalboard.com).`
4. Save (press Esc)
5. Click on the link
6. Nothing happens

**Expected behavior:**
The URL should open in the default browser.

**Platform:**
 - Personal Desktop 0.6.5 RC3 on Linux Mint 20.1 Cinnamon

**Additional context:**
Same problem happens with links in the board header.
Right-clicking on the link and selecting "open link" also doesn't do anything.

The desktop app is likely not intercepting and handling link-clicks correctly.
This issues doesn't repro on the Mac and Windows desktop apps.

**Comment by chenilim** [comment]
Clicking on other links (e.g. the help link or "About Focalboard" from the menu) in the Desktop App also doesn't open them in the default browser. This is likely due to the same issue.

**Comment by jespino** [comment]
This a restriction from the webview library, I have to investigate how to fix that.

**Comment by jespino** [comment]
I wrote a workaround for this.
