### ISSUE TITLE
Bug: cannot create new board from template

### ISSUE THREAD

**Issue by fanszoro** [mattermost/focalboard#2851]
## Steps to reproduce the behavior

I cannot create any new board after I pulled the new docker images, and the docker logs says ,

```
error [2022-04-20 18:45:20.817 +08:00] API ERROR                                caller="api/api.go:4125" code=500 error="pq: null value in column "insert_at" of relation "board_members_history" violates not-null constraint" msg="pq: null value in column "insert_at" of relation "board_members_history" violates not-null constraint" api=/api/v2/boards/bshsty8d95bg1ujgyzcebbiu98c/duplicate
```

## Expected behavior

Any behavior should be consistent across versions，but there seems to be some problems .

## Edition and Platform

 - Edition: Personal Server 
 - Version: latest
 - Browser and OS:  Chrome on Windows

**Comment by chenilim** [comment]
The docker build installs from main, which may be unstable. Fix is to change docker to install the latest release, dup of https://github.com/mattermost/focalboard/issues/2592.
