### ISSUE TITLE
Doc: Add Help Doc note to inform users “Enable Publicly-Shared Boards” will be on by default for Cloud

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2857]
## Summary

Add note in Help Docs that the System Console option to “Enable Publicly-Shared Boards” will be on by default for Cloud.

## (Optional) Additional context and/or screenshot
https://docs.google.com/document/d/1VxIcDnI5jc68mQSNKSICv-0npkN8nGl2cnkWIMQUiEk/edit?disco=AAAAXtYBIkI

**Comment by justinegeffen** [comment]
@wuwinson, is this still required? :)

**Comment by wuwinson** [comment]
@justinegeffen Added it as a note [here](https://docs.google.com/document/d/13f_6mMWtvagOpfu_O77NR1_JQXMkhxIrBGsfub5nXlk/edit#bookmark=id.6gu43vxfevna). Closing this out.
