### ISSUE TITLE
Bug: Incorrect input field styling on create category modal

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#2864]
## Steps to reproduce the behavior
1. Open the create category modal

## Expected behavior
Styling should match the designs or the input fields we have, and also have a focus state.

## Screenshots (optional)
<img width="656" alt="Screenshot 2022-04-21 at 1 23 17 PM" src="https://user-images.githubusercontent.com/11034289/164413228-9143ca43-b0ae-4f38-beb9-105ed5fe4c47.png">

## Edition and Platform
 - Edition: Mattermost Boards (plugin)
 - Version: v0.16.0
 - Browser and OS: Chrome on Mac

## Additional context (optional)

Sev 3

**Comment by wuwinson** [comment]
@asaadmahmood Can you link to the designs or provide design specs on this? Thanks!

**Comment by asaadmahmood** [comment]
@wuwinson Example with various states can be seen here:
https://www.figma.com/file/FBMH5jZgvE1I0gSu5dazzW/Components---Text-Inputs?node-id=1047%3A80

Or here:
https://zeroheight.com/29be2c109/p/937efe-text-inputs

**Comment by wuwinson** [comment]
Thanks @asaadmahmood!
