### ISSUE TITLE
Bug: Create a board from Welcome board template should show tour points

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#2865]
## Steps to reproduce the behavior

1. Create a user and open Boards
2. Decline the tour 
3. Go to template picker
4. Select  welcome board template 
5. Create a board from welcome board (or select Product Tour from settings)
6. It does not show the tour poins

## Expected behavior
Create a board from the welcome board templates should show the tour points

## Screenshots (optional)
<img width="1332" alt="Screenshot 2022-04-21 at 1 28 57 PM" src="https://user-images.githubusercontent.com/11034289/164413839-e5d27fda-7995-4327-8449-72b32769bba2.png">

## Edition and Platform
 - Edition: Mattermost Boards (plugin)
 - Version: v0.16.0
 - Browser and OS: Chrome on Mac

## Additional context (optional)

Sev 3

**Comment by sbishel** [comment]
Appears if you "cancel" the tour via the first screen, you can't restart it ever. If you start and end it, it works correctly.

**Comment by wuwinson** [comment]
Should be able to restart tour from the Setting menu and template even if user cancels initial tour from Welcome page.
