### ISSUE TITLE
Bug: select property options stop working

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/focalboard#2867]
## Steps to reproduce the behavior

1. Create a card with a select property
2. Create a couple of options, `A` and `B`
3. Change between the options a couple of times

## Expected behavior

Every time you click on an option to change to it, it should be set, but at some point it stops working and the selected option doesn't change.

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.16.0 bugbash
 - Browser and OS: Firefox 99.0.1 on Linux

**Comment by Rajat-Dabade** [comment]
To more describe this issue, it was not allowing us to select the value which was already there in the select property when we entire the card view. This issue was because of the useCallback hook without any dependencies, the inner value of the function was not getting updated.

Fixed
