### ISSUE TITLE
Bug: Clicking on the edges of a category to move does not work

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#2869]
## Steps to reproduce the behavior
1. Clicking on the edges of the category to move a board to does not move it

## Expected behavior
Clicking anywhere on the menu option should move the board

## Screenshots (optional)
<img width="406" alt="Screenshot 2022-04-21 at 1 36 29 PM" src="https://user-images.githubusercontent.com/11034289/164415305-1de5ba09-c742-4f61-aa09-0eb722f2fbaf.png">

## Edition and Platform
 - Edition: Mattermost Boards (plugin)
 - Version: v0.16.0
 - Browser and OS: Chrome on Mac

## Additional context (optional)

Sev 2

**Comment by wuwinson** [comment]
Potentially related to #2879

**Comment by asaadmahmood** [comment]
Don't think its related @wuwinson

**Comment by jespino** [comment]
It is working for me locally, Can you try to reproduce it now @asaadmahmood?

**Comment by asaadmahmood** [comment]
@jespino Tried it locally, works for me too.
