### ISSUE TITLE
Bug: Last update by and created by fields have different representation in the board cards

### ISSUE THREAD

**Issue by jespino** [mattermost/focalboard#2874]
## Steps to reproduce the behavior

In the board cards and gallery cards the representation of the created by and last modified by has different representaiton. One shows the user with the avatar, the other don't. It should be consistent

## Expected behavior

Consistent user representation in the cards

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/290303/164416835-7d02507d-ccab-4295-bc17-a7ba9d828b8f.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.17.0
 - Browser and OS: Firefox/Linux

**Comment by jespino** [comment]
@asaadmahmood can you confirm what do you want for the correct behavior? My guess is the user representation with the avatar.

**Comment by asaadmahmood** [comment]
You are right @jespino We should have the avatar.
