### ISSUE TITLE
Bug: Autocomplete not styled in the share modal

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#2877]
## Steps to reproduce the behavior
1. Open share modal on a template ore a board
2. Click to add user
3. Notice that the autocomplete list not styled

## Expected behavior
Styling should match the designs

## Screenshots (optional)
<img width="697" alt="Screenshot 2022-04-21 at 1 51 54 PM" src="https://user-images.githubusercontent.com/11034289/164418567-444fbb63-a3ba-46b1-b530-0b28f10f2967.png">

https://www.figma.com/file/bu8YbzRGfO1AEw9pmQyUSR/Focalboard-Permissions?node-id=34%3A9382

## Edition and Platform
 - Edition: Mattermost Boards (plugin)
 - Version: v0.16.0
 - Browser and OS: Chrome on Mac

## Additional context (optional)

Sev 3

**Comment by asaadmahmood** [comment]
@wuwinson I think this should be given to someone else. I just need the images and full name in the UI, and then I can style it.

**Comment by wuwinson** [comment]
Sure np @asaadmahmood. @sbishel any suggestions?
