### ISSUE TITLE
Bug: moving a board to a new category doesn't show on the interface until refresh

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/focalboard#2879]
## Steps to reproduce the behavior

1. Create a new category
2. Move a board to that new category
3. The interface doesn't react and you need to refresh the page to see the changes

## Expected behavior

The interface should react to the board move.

## Edition and Platform

 - Edition: Personal Desktop
 - Version: v0.16.0
 - Browser and OS: Firefox 99.0.1 on Linux

## More context

Looks like the websocket message is arriving correctly, but the interface is not processing it.

**Comment by chenilim** [comment]
This repros for me (intermittently) on the plugin bugbash server as well. Seems fairly consistent with a board created from the welcome board template.

**Comment by chenilim** [comment]
A few more observations:
* There appears to be a general case where auto-updates stop working after certain actions.
* E.g. with two different users logged in (in two different browsers), I would switch between views for user1, while adding and removing user1 to a private board as user2 (which makes it appear in user1's sidebar)
* After a few (3-4) view changes, user1's sidebar updates would stop working automatically (until refresh).
* I can see the websocket event come over to user1's browser, but the interface does not auto-update

A hypothesis is a silent error / exception is happening which breaks the UI auto-update.

**Comment by jespino** [comment]
It is working for me, can you try to reproduce it again @mgdelacroix or @chenilim ?

**Comment by sbishel** [comment]
This is fixed for me as well on RC1. Closing...
