### ISSUE TITLE
Bug: Auto-complete only lists board members instead of all team members on public boards

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2885]
## Steps to reproduce the behavior

1. Go to public board
2. Open a card and go to the Comments section
3. @mention a non-board member
4. See error: User does not appear on auto-complete list. Manually @mentioning a non-board member will still add them as a board member even though they don't initially appear on the auto-complete list.

## Expected behavior

When @mentioning users on public boards:
1. Auto-complete lists all users on the current team
2. If @mentioned user is not a board member, auto-add user at mention time prior to sending notification to @mentioned user
3. @mentioned user gets added as the default role on the board

See [spec](https://docs.google.com/document/d/1HOnoB87WZojqplpB6XGbtKsLuqjG8h-8CbJpmWsRfM4/edit#bookmark=kix.p1mww7cnoiz4) for details.

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/164525871-0a18691d-461c-419a-af43-ab20f4e8eb55.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.16 Bugbash-2
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment]
Related to #2886

**Comment by harshilsharma63** [comment]
> If @mentioned user is not a board member, auto-add user at mention time prior to sending notification to @mentioned user

@wuwinson this is inconsistent with Channels. In channels, you always need to confirm adding a user to the channel, even if it's a public channel. Can you please confirm that we want this here? If we want to add the confirmation part as well, I'd propose doing this issue as part of 0.17 instead as it's not a blocker IMO.

**Comment by harshilsharma63** [comment]
Ah okay! Got it @wuwinson !
