### ISSUE TITLE
Bug: Personal Server > Don't show user avatar circle

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#2889]
## Steps to reproduce the behavior

1. Open Personal Server
2. Click on "Share"
3. Observe avatars - all users have grey avatars

## Expected behavior

Hide user avatars ? (since these can't be set on personal server)

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/15314183/164536434-7e2bde61-83ab-4a44-a6cb-0147d3a0c8ed.png)

## Edition and Platform

 - Edition: Personal Server 
 - Version: v0.16.0
 - Browser and OS: Chrome on Windows

## Additional context (optional)

This issue also affects card comments

**Comment by wuwinson** [comment]
@asaadmahmood Padding might be a bigger issue than the gray avatar - can you take a pass at fixing this?

**Comment by chenilim** [comment]
@asaadmahmood, go ahead and make the call on whether leaving the gray circle or removing it (or something else) is preferable here.

**Comment by asaadmahmood** [comment]
@chenilim @wuwinson What's the purpose of the share modal on the personal server. Just trying to understand it. Can a user have other team members on the personal server? Or have the everyone at the team dropdown?

**Comment by wuwinson** [comment]
@asaadmahmood Clarifying the differences here from the discussion in our team meeting:

1. Plugin - Multiple teams and users
2. Personal Server - Single team with multiple users
3. Personal Desktop - Single user
