### ISSUE TITLE
Bug: Welcome board has no images

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2890]
## Steps to reproduce the behavior

1. Register a new account and login
2. Select "Take the tour" on the initial welcome page
3. The Welcome board opens
4. Open the first card
5. There is not image attached to the card (nor on any of the other cards)

## Expected behavior

The welcome board's cards should have images

## Screenshots (optional)

<img width="823" alt="Screen Shot 2022-04-21 at 12 17 48 PM" src="https://user-images.githubusercontent.com/46905241/164536997-f11bf6dc-4e4c-44b8-8e85-9867e93f183e.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.16 (bugbash2)
 - Browser and OS: Safari and Chrome on Mac

## Additional context (optional)

If you create a board from the welcome board template, there are no images either.

**Comment by wuwinson** [comment]
Try to repro on Personal Server first to confirm if its a connectivity issue.

**Comment by wiggin77** [comment]
This may be more than a S3 connectivity issue... while testing a PR I noticed these in my local logs after creating a board from template:
```
error [2022-04-22 11:56:33.209 -04:00] API ERROR                                     caller="app/plugin_api.go:940" plugin_id=focalboard code=500 error=""unable to open file wnnbqiiw13d7xnh3omhoqrdw3r/bn9oykhxmdb8b7eeip4cm1t7dto/77pe9r4ckbin438ph3f18bpatua.png: open data/wnnbqiiw13d7xnh3omhoqrdw3r/bn9oykhxmdb8b7eeip4cm1t7dto/77pe9r4ckbin438ph3f18bpatua.png: no such file or directory"" msg= api=/api/v2/files/teams/wnnbqiiw13d7xnh3omhoqrdw3r/bn9oykhxmdb8b7eeip4cm1t7dto/77pe9r4ckbin438ph3f18bpatua.png
debug [2022-04-22 11:56:33.307 -04:00] attachSession                                 caller="app/plugin_api.go:934" plugin_id=focalboard single_user=false
error [2022-04-22 11:56:33.311 -04:00] API ERROR                                     caller="app/plugin_api.go:940" plugin_id=focalboard code=500 error=""unable to open file wnnbqiiw13d7xnh3omhoqrdw3r/bn9oykhxmdb8b7eeip4cm1t7dto/77pe9r4ckbin438ph3f18bpatua.png: open data/wnnbqiiw13d7xnh3omhoqrdw3r/bn9oykhxmdb8b7eeip4cm1t7dto/77pe9r4ckbin438ph3f18bpatua.png: no such file or directory"" msg= api=/api/v2/files/teams/wnnbqiiw13d7xnh3omhoqrdw3r/bn9oykhxmdb8b7eeip4cm1t7dto/77pe9r4ckbin438ph3f18bpatua.png
```

They appear in logs every time I access a card in the duplicated board.

**Comment by wiggin77** [comment]
I can reproduce this consistently as a local plugin.

**Comment by wiggin77** [comment]
None of the copy files code made it to the `DuplicateBoard` refactor.  Strange that this is just now noticed.  Any board with cards containing images will lose the images on duplication.
