### ISSUE TITLE
Bug: Table's "Count not empty" calculation is wrong for person properties

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2892]
## Steps to reproduce the behavior

1. Create a new board from the welcome template
2. Open the table view
3. Set the assignee column calculation to "count not empty"
4. It shows an incorrect count

## Expected behavior

Should show the correct count

## Screenshots (optional)

<img width="822" alt="Screen Shot 2022-04-21 at 12 22 28 PM" src="https://user-images.githubusercontent.com/46905241/164537729-ce65136c-33ec-4d7d-a77c-c0b0bf1a4950.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.16 (bugbash2)
 - Browser and OS: Chrome on Mac

## Additional context (optional)

Selecting some cells and pressing delete makes the count change, even though the cell still shows "empty".

**Comment by sbishel** [comment]
This is an issue with the actual templates.
