### ISSUE TITLE
Feature Idea: duplicating a board maintains the category

### ISSUE THREAD

**Issue by Pinjasaur** [mattermost/focalboard#2897]
## Summary

When duplicating a board that is in a non-default category (`Boards` being the default) it will be duplicated into the default (`Boards`) category.

## How important this is to me and why

Importance: Low

Use cases:
1. As a user, I would expect 'duplicate' to equate to a familiar 'copy + paste' workflow e.g. retain the category.
2. As a user, if I have many boards / categories and I duplicate a board I could visually lose it.
3.

## Additional context/similar features

Any examples of good implementations of this capability.

**Comment by wuwinson** [comment]
cc @asaadmahmood Thoughts?

**Comment by wuwinson** [comment]
@harshilsharma63 only fix if this is quick and easy otherwise we'll fix in the next release.

**Comment by harshilsharma63** [comment]
@wuwinson sure, I'll take a look.

**Comment by harshilsharma63** [comment]
@wuwinson this is not a quick one. Can we move it to 0.17?
