### ISSUE TITLE
Bug: Table View Is Very Slow

### ISSUE THREAD

**Issue by LimitlessDonald** [mattermost/focalboard#2907]
When using the table view of focalboard in mattermost, it gets incredibly slow when trying to do just about anything when I have more than 70+ tasks on the list.
This issue persists whether I am creating a new task with the "in-table" option or creating a new task with the pop-up

This issue is not present when I am trying to add new tasks using the board view, or calendar view

My browser literally hangs for about 4-5 seconds when I try to resize a column or create a new task in table view 

My work-around to fix this, is to search for some random string that is not a keyword in any of my tasks e.g "hdhgdhshdsahdsh" in table view so no task shows on the list of tasks, then I can easily add new tasks or resize columns very quickly.

## Steps to reproduce the behavior

1. Go to your boards page of a preferred channel in mattermost
2.  Create a table view 
3.  Add as many as 70+  tasks 
4. Try to add new tasks
5. Try to resize a column width

## Expected behavior

Resizing column width or adding new tasks in table view should be easy and quick no matter the number of tasks I have 

## Edition and Platform

 - Edition: Team edition in browser and even desktop app 
 - Version: focal board v0.15.0 . I also tested on mattermost 6.5 and 6.6 
 - Browser and OS: Tested on Linux mint(But I doubt this is a Linux issue, I may be wrong), Tested on Opera browser, Firefox browser, Chrome browser, and the desktop app

**Comment by sbishel** [comment]
Fixed in v7.2 (main) branch. Will not backport.
