### ISSUE TITLE
Filter Cards by Assignee

### ISSUE THREAD

**Issue by samuraii78** [mattermost/focalboard#2918]
Is there a way to filter cards in a board by Assignee? The only two options currently available are Status and Priority. Can additional filters be created / added?

**Comment by wuwinson** [comment]
@samuraii78 Boards currently only supports filtering by the `SELECT` property type. We plan to add filtering by other property types in the future. Please feel free to add any additional feedback to https://github.com/mattermost/focalboard/issues/1732. Thanks!
