### ISSUE TITLE
Bug: Database Ping failed

### ISSUE THREAD

**Issue by morganzero** [mattermost/focalboard#2920]
## Steps to reproduce the behavior

1. bind volume path in your docker-compose
2. deploy your docker-compose
3. docker logs focalboard -tf and see error

Not able to access app. Container crashes.

## Expected behavior
To be able to bind volume path and get app working.

## Edition and Platform

 - Edition: Personal Ubuntu Server running focalboard docker container
 - Version: mattermost/focalboard:latest

**Comment by wuwinson** [comment]
@Pinjasaur Queueing this one up for v7.1. cc @sbishel

**Comment by wuwinson** [comment]
@morganzero Are you still able to reproduce this issue? If so, can you please provide any logs? Thanks!

**Comment by wuwinson** [comment]
Feel free to re-open if you're still having issues. Thanks!
