### ISSUE TITLE
Bug: Able to add cards on a "read-only" calendar view

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2931]
## Steps to reproduce the behavior

1. Go to board with a calendar view
2. Generate a public read-only view
3. Load the public link on a browser
4. Hover over any date and click on the "+" button
5. See error - User is able to create a new card, but not add any content to the card

## Expected behavior

"+" button does not appear when mouse is hovered over a date

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/165396884-7203e7e3-123f-46f5-82d2-c0525d7e6d4b.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.15.0
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment]
Doesn't seem to occur in the v0.16 permissions bugbash servers, so maybe a non-issue.

**Comment by sbishel** [comment]
Yep. I just double checked the code (and tested). It was an issue in v0.15, fixed in v.016. Because it doesn't allow cards to be added, I would not fix.

**Comment by wuwinson** [comment]
Cool, closing out. Thanks @sbishel!
