### ISSUE TITLE
Feature Idea: Disable view dropdown selector on public "read-only" views

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2932]
## Summary
The view dropdown selector should be disabled on public "read-only" views so users can't switch views.

## How important this is to me and why

Importance: Medium

Use cases:
Some users would like to share not only a board but also a specific view. Think about an internal & public roadmap. There are some tasks that a user may not want to show up on the public roadmap (like internal tools) etc. that can be filtered out on another view, but if the user shares the board, the public can switch between both views and also see the internal tasks.

**Comment by wuwinson** [comment]
See #2938 for reference.

**Comment by wuwinson** [comment]
Additional improvements to view-only public boards: Option to prevent viewers from opening cards.

See this [thread](https://community.mattermost.com/core/pl/n9siwxekm3dimnmgorqr1yufra) for reference.

**Comment by redhoyasa** [comment]
I have some questions:
1. Since the permission is attached to the board (not the view), any user that has the URL for other views can still open the other views using the URL directly right?
2. What if the board owner wants to share all the views with "read-only"? In this case, do you expect the dropdown selector still be disabled?

**Comment by wuwinson** [comment]
@redhoyasa Thanks for your questions! Answers below:

1. Correct!
2. The common use case for sharing public read-only boards is to communicate specific information to an external audience, and not all the information from the board, thus the reason for wanting to restrict access to a single view. If the board owner wants to share all views publicly, I'd expect the dropdown to still be disabled and to have all views shared as individual links. In the case where a board owner wants to share all the views to internal collaborators with "read-only" access, they can add the user to the board and assign them the "Viewer" role.

Hope that clears things up, but let us know if you have any other questions!

**Comment by redhoyasa** [comment]
@wuwinson thanks for the answer!

To summarize:
1. in the public "read-only" view, the dropdown is disabled (or hidden? which one do you prefer?)
2. if the user is directly assigned the "Viewer" role, the dropdown is available for that user

Is that correct?

**Comment by wuwinson** [comment]
@redhoyasa Yep, that's right!

1. Dropdown should be disabled but not hidden, so the viewers can still see the name of the view
2. Dropdown is still available for users assigned the "Viewer" role (no changes from current behavior)

LMK if you'd like to pick up this ticket, and I'll assign to you. Thanks!

**Comment by redhoyasa** [comment]
Yes I would like to pick this one.

**Comment by wuwinson** [comment]
Awesome, thanks @redhoyasa!

**Comment by redhoyasa** [comment]
@wuwinson I forgot to ask this. Do you want the views' name to become disabled (as in the below screenshot)? Or do you want the whole dropdown disabled so we cannot click and show the dropdown list?

<img width="937" alt="Screenshot 2022-10-31 at 11 49 11 AM" src="https://user-images.githubusercontent.com/1910192/198933461-1645769e-680c-4d26-b9da-4851b0b493e7.png">

**Comment by redhoyasa** [comment]
> Option to prevent viewers from opening cards.
From my understanding, the board owners can decide whether they want the viewers to be able to open the card or not, is that correct?

**Comment by wuwinson** [comment]
> @wuwinson I forgot to ask this. Do you want the views' name to become disabled (as in the below screenshot)? Or do you want the whole dropdown disabled so we cannot click and show the dropdown list?

@redhoyasa The whole dropdown should be disabled so you cannot click and show the dropdown list


> > Option to prevent viewers from opening cards.
> 
> From my understanding, the board owners can decide whether they want the viewers to be able to open the card or not, is that correct?

We can leave this out of scope for now as we don't currently have a mechanism for board owners to determine if cards can be opened or not.

Thanks!
