### ISSUE TITLE
Bug: drag and drop animation gets halted in Firefox

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/focalboard#2948]
## Steps to reproduce the behavior

1. On a board view, start dragging a card from one column to the next
2. See how the card stops following the mouse a bit after starting the drag, but the drop point is correctly identified and the card moves to the right place when dropped

## Expected behavior

The card should follow the mouse during the drag&drop animation.

## Screenshots (optional)

If applicable, add screenshots or a screen recording to elaborate on the problem.

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.16.0
 - Browser and OS: Firefox 99.0.1 on Linux

**Comment by sbishel** [comment]
@mgdelacroix - Could you retest on https://boards-bugbash.test.mattermost.cloud.
I cannot duplicate but I'm Firefox/Chrome on Mac.

**Comment by mgdelacroix** [comment]
@sbishel couldn't repro on Firefox 102.0 it might have been an issue with the specific Firefox on Linux version. Closing and will reopen if found again
