### ISSUE TITLE
Bug: User list sits inside of the share modal for templates

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#2950]
## Steps to reproduce the behavior

1. Create a new custom template
2. Go to share
3. Open the invite modal and have a lot of members
4. See the user list inside of the container

## Expected behavior
The user list should be outside.

## Screenshots (optional)
<img width="689" alt="Screenshot 2022-04-28 at 1 16 23 PM" src="https://user-images.githubusercontent.com/11034289/165709143-7afe2df0-7c5f-41a4-9c4a-ccfe363d23c1.png">

## Edition and Platform
 - Edition: Mattermost Boards (plugin)
 - Version: v0.16.0
 - Browser and OS: Chrome on Mac

## Additional context (optional)
SEV 3

**Comment by chenilim** [comment]
Note that this is not an issue for boards as there is enough vertical space for the user picker, but templates don't have the additional Share tabs. In any case, agree that the user picker pop-up should overflow above the share dialog.
