### ISSUE TITLE
UI: Messed up alignment on the template picker list

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#2952]
## Steps to reproduce the behavior

1. Go to template picker
2. Create template with no icon
3. Compare horizontal alignment of list items
4. Misaligned list items

## Expected behavior
All text should start from the same position even if there is an icon or not, and same goes for the New template item.

## Screenshots (optional)
<img width="689" alt="Screenshot 2022-04-28 at 1 16 23 PM" src="https://user-images.githubusercontent.com/11034289/165710213-12e6fc6f-f674-44ba-b4e4-9667c70b9578.png">

## Edition and Platform
 - Edition: Mattermost Boards (plugin)
 - Version: v0.16.0
 - Browser and OS: Chrome on Mac

## Additional context (optional)
Sev3

**Comment by chenilim** [comment]
Looks like the wrong screenshot above, but I'm able to repro it:
<img width="262" alt="Screen Shot 2022-04-29 at 12 13 40 PM" src="https://user-images.githubusercontent.com/46905241/166026503-1d7c0ad4-3106-4dfe-90ba-763e4d2a30a7.png">

**Comment by wuwinson** [comment]
This happens on v0.15 as well. Is there some kind of placeholder icon we can use? Even if we align the text, the empty space still looks weird.

**Comment by asaadmahmood** [comment]
@wuwinson We should use the boards icon for it. We can assign this to a dev if not urgent.

Figma link:
https://www.figma.com/file/hOfP5n9Ij0ym0CvdU2t3HS/Boards-Template-Picker?node-id=1%3A16016

![image](https://user-images.githubusercontent.com/11034289/181497434-57c8cd52-3dea-45f7-a778-13f36a649d63.png)

**Comment by wuwinson** [comment]
Related to #3461.

**Comment by chenilim** [comment]
@wuwinson should this still be prioritized for 7.2? cc @sbishel.

**Comment by asaadmahmood** [comment]
@wuwinson Yes I can fix this (hopefully).
