### ISSUE TITLE
UI: Align board text in the LHS and use a default icon as placeholder

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#2958]
## Steps to reproduce the behavior

1. Add multiple boards on the LHS
2. Some with icon, some with not
3. The starting point of the text is not aligned

## Expected behavior
- The starting point of the text should be vertically aligned
- And we can add a placeholder icon (boards) icon on the LHS instead of the custom one if it has no icon.

## Screenshots (optional)
<img width="238" alt="Screenshot 2022-04-28 at 1 31 57 PM" src="https://user-images.githubusercontent.com/11034289/165712211-5732d46f-858f-4c89-b4c1-400f091ccc3f.png">

## Edition and Platform
 - Edition: Mattermost Boards (plugin)
 - Version: v0.16.0
 - Browser and OS: Chrome on Mac

## Additional context (optional)
SEV3

**Comment by Pinjasaur** [comment]
@asaadmahmood is this for boards _and_ views? is the default icon the same for both if they don't have a custom icon set?

**Comment by asaadmahmood** [comment]
@Pinjasaur Views always have an icon set. So its only for boards.
