### ISSUE TITLE
UI: Close icon and search icon not aligned in CMD+K modal

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#2959]
## Steps to reproduce the behavior

1. Press CMD/CTRL K
2. See boards switcher
3. Close icon and search icon not aligned.

## Expected behavior
Close icon and search icon should be aligned

## Screenshots (optional)
<img width="639" alt="Screenshot 2022-04-28 at 1 39 42 PM" src="https://user-images.githubusercontent.com/11034289/165713284-d33ab85d-c76f-4371-8126-3f71c8031b01.png">

## Edition and Platform
 - Edition: Mattermost Boards (plugin)
 - Version: v0.16.0
 - Browser and OS: Chrome on Mac

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
Sev3

**Comment by chenilim** [comment]
Here's the channel feature for reference:
<img width="646" alt="Channel switcher" src="https://user-images.githubusercontent.com/46905241/166320285-e59f861f-b266-416e-9285-826724b70342.png">

**Comment by wuwinson** [comment]
@asaadmahmood Where should the X be aligned? The Channels switcher doesn't look to be aligned either.
