### ISSUE TITLE
Bug: Cannot set emoji on board once it's been deleted

### ISSUE THREAD

**Issue by Johennes** [mattermost/focalboard#296]
**Summary:**

Boards created from the default templates have an emoji applied. Once the emoji is removed, there seems to be no way to bring it back though.

**Steps to reproduce the behavior:**

1. Create a new board from the "Meeting Notes" template
2. Click the 🗒 icon next to the board title
3. Click "Remove icon"
4. The icon disappears but if I now decide that I want to set an emoji again, there seems to be no way in the UI to do that.

**Expected behavior:**

There should be an option somewhere to reapply an emoji to the board.

**Screenshots:**

![Screenshot 2021-04-19 at 15 03 36](https://user-images.githubusercontent.com/1137962/115242931-a68ab400-a122-11eb-8a0f-d644ff2b5ff2.png)
![Screenshot 2021-04-19 at 15 03 49](https://user-images.githubusercontent.com/1137962/115242937-a7234a80-a122-11eb-94bb-daa8a81acacf.png)

**Platform:**

macOS 11.2.1
Focalboard v0.6.0

**Comment by chenilim** [comment]
Hi @Johennes, thanks for filing this! When there is no emoji icon, you should be able to hover above the title to see an "Add icon" button. Clicking that should set a random icon that can be then changed.

<img width="336" alt="Add icon hover button" src="https://user-images.githubusercontent.com/46905241/115267506-1a5e9980-a0ee-11eb-8944-d60d1ee02984.png">

Please let me know if this doesn't work on your setup. In any case, it seems that this is not as discoverable as it should be, so we may need to rethink this design.

**Comment by Johennes** [comment]
Ohh, you're right. It shows when hovering the area above the title. I tried hovering the area left to the title, where the emoji was, but not above. Sorry for missing that. 🤦‍♂️

We can close this then as it's not a bug.

UX-wise maybe it'd be helpful if the buttons above the title would also show when hovering the title itself? Hm, or maybe that'd be annoying. 🤔
