### ISSUE TITLE
Bug: When I import a exported board it doesn't get reflected in the sidebar until refresh

### ISSUE THREAD

**Issue by jespino** [mattermost/focalboard#2961]
## Steps to reproduce the behavior

1. Export a board
2. Import it again
3. The new board doesn't show up in the sidebar

## Expected behavior

The new board shows up in the sidebar (and maybe you get redirected to it).

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.16.0
 - Browser and OS: Firefox on Linux

## Additional context (optional)

* Sev 3: Affects minor, non-critical functionality

**Comment by sbishel** [comment]
Retest on 7.2 to make sure its still an issue.

**Comment by sbishel** [comment]
Closing as appears fixed in latest main. 

https://user-images.githubusercontent.com/12704875/186711888-061e1e82-418f-4737-9163-1ed7e202b480.mov
