### ISSUE TITLE
Feature Idea: Dont close board property selector menu on selecting a property

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#2965]
## Summary

Problem 1-
Currently, when you wanna select multiple properties to be displayed in board view, you need to open the "Properties" menu again and again for each property as it closes as soon as you select a property.

Proposed solution-
Don't close the properties menu on selecting a property, and close if the user clicks on the "Properties" menu again or clicks anywhere outside.

It would also be nice if we showed which properties in that menu are already displayed. Such as by showing a checkmark with those already displayed.

## How important this is to me and why

Importance: Medium

**Comment by chenilim** [comment]
Related to https://github.com/mattermost/focalboard/issues/2989

**Comment by chenilim** [comment]
Amy recently ran into this issue when working on the FY23 Goals board.

Also filed https://github.com/mattermost/focalboard/issues/3361 to track a similar issue for the filter menu.

**Comment by kamre** [comment]
Hi @chenilim, I have started looking into this issue as well as #3361 

My idea is to add a new flag to props of Menu Switch Item that will avoid closing the menu when Switch Item is toggled. And use this flag for Switch Items in menus for board properties and filter values.
