### ISSUE TITLE
UI: Disable hover state on card properties if I'm a viewer on the board

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#2966]
## Steps to reproduce the behavior
https://www.loom.com/share/417c103d7d82484c913fe7d8a2cdd6c7

## Expected behavior
No hover state should be there on the card properties

## Edition and Platform
 - Edition: Mattermost Boards (plugin)
 - Version: v0.16.0
 - Browser and OS: Chrome on Mac

## Additional context (optional)
SEV3

**Comment by wuwinson** [comment]
@wuwinson To define and put it up for grabs.
