### ISSUE TITLE
Bug: `serverRoot` with subpath doesn't work locally

### ISSUE THREAD

**Issue by Pinjasaur** [mattermost/focalboard#2972]
## Steps to reproduce the behavior

1. Go to `config.json` and modify the `serverRoot` to contain a subpath e.g. `http://localhost:8000/localboard`
2. Start up Focalboard (personal server) locally
3. Go to the `serverRoot` you configured
4. Note the boilerplate React HTML document loads, but none of the assets e.g. JS load

## Expected behavior

Subpathing to work locally for testing e.g. to verify URLs are being build correctly.

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/6335792/165789034-85746500-18cf-4579-8731-65aa67124333.png)

![image](https://user-images.githubusercontent.com/6335792/165789107-af116d2d-85b6-47f3-b561-3d4290ef0923.png)

## Edition and Platform

 - Edition: Personal Server (locally)
 - Version: `main`
 - Browser and OS: FF100 on Mac

## Additional context (optional)

Sev 2 as the workaround (as I understand it) is to also run Nginx (or similar) locally to reverse-proxy and test that way.

- Board: https://community.mattermost.com/boards/workspace/b1ni7nprjpfwpb566k1gk8z9nw/886d2280-e88e-4065-8c85-1b62578f192e/f30dcb19-a0e8-45d2-8768-a9489f6e7fe8/c79q3sin15jfsupuwm85595epdc
- @harshilsharma63's `nginx.conf`: https://community-daily.mattermost.com/core/pl/uju4oqetmbftifqqgajmosjfjh

**Comment by Pinjasaur** [comment]
@jespino could you tag me in the PR when it's out? I'm curious to see how it's done

**Comment by jespino** [comment]
@Pinjasaur there is the PR, take a look, it is a very simple solution.
