### ISSUE TITLE
UI: Min-width of header should match min-width of view header

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2975]
## Steps to reproduce the behavior

1. Open a board view
2. Resize the window narrower
3. The Share button moves to the left of the view header (i.e. New button)

## Expected behavior

The Share button should stop so that the right-edge lines up with the New button. i.e. the header's min-width should match the min-width of the viewHeader. This should apply to all editions.

## Screenshots (optional)
<img width="1105" alt="min-width" src="https://user-images.githubusercontent.com/46905241/165800824-453fab39-402a-41db-bf46-31ebd598bdcd.png">

## Edition and Platform

 - Edition: Personal Desktop / Personal Server / Mattermost Boards (plugin)
 - Version: v0.16 (bugbash2)
 - Browser and OS: Chrome on Mac

**Comment by chenilim** [comment]
@asaadmahmood, do you agree with this, or have a different preferences?

**Comment by asaadmahmood** [comment]
This should be fixed with the new condensed header. @chenilim
