### ISSUE TITLE
UI: Share button is not right-aligned with New button

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2976]
## Steps to reproduce the behavior

1. Open a board view
2. The share button is not right-aligned with the New button

## Expected behavior

The buttons should be right-aligned.

## Screenshots (optional)

<img width="410" alt="align buttons" src="https://user-images.githubusercontent.com/46905241/165801786-6f5379d0-2b88-45a2-b5b9-416d8e8e4373.png">

## Edition and Platform

 - Edition: Personal Desktop / Personal Server / Mattermost Boards (plugin)
 - Version: v0.16
 - Browser and OS: Chrome on Mac

**Comment by chenilim** [comment]
@asaadmahmood, do you agree with this, or do you have a different preference?

**Comment by wuwinson** [comment]
Nice! Closing this out. Fixed by https://github.com/mattermost/focalboard/pull/2930
