### ISSUE TITLE
Set boardsdataretention to True

### ISSUE THREAD

**Issue by amyblais** [mattermost/focalboard#2977]
Unsure if needed, but if Boards data retention is shipping with v6.7, the feature flag https://github.com/mattermost/mattermost-server/blob/master/model/feature_flags.go#L87 should be either removed or set to "true" in server code.

**Comment by sbishel** [comment]
Thanks Amy...

**Comment by sbishel** [comment]
@amyblais - we are not going to remove FF for v6.7 - thank you.

**Comment by sbishel** [comment]
no longer valid...closin
