### ISSUE TITLE
Bug: Select option menu is truncated by the dropdown

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2981]
## Steps to reproduce the behavior

1. Open a card with a select property
2. Select the property, and click ... next to a value
3. The value menu is truncated by the dropdown

## Expected behavior

The value menu appears above the dropdown

## Screenshots (optional)

v0.16:
<img width="442" alt="Screen Shot 2022-04-28 at 10 27 57 AM" src="https://user-images.githubusercontent.com/46905241/165812695-3de02f90-8d10-4a56-9f73-8c1c28bfc5c2.png">

v0.15 (expected):
<img width="468" alt="Screen Shot 2022-04-28 at 10 31 08 AM" src="https://user-images.githubusercontent.com/46905241/165812919-558e9b1c-7ea2-436e-bb59-355d6848000b.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.16
 - Browser and OS: Chrome and Safari on Mac

**Comment by Pinjasaur** [comment]
Closed by #3171.
