### ISSUE TITLE
UI: "Add icon" icon is too large

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2982]
## Steps to reproduce the behavior

1. Open a board and create a new card
2. Hover above the title area
3. The "Add icon" icon appears to be too large

## Expected behavior

The icon is balanced with the text.

## Screenshots (optional)

Card view:
<img width="233" alt="Screen Shot 2022-04-28 at 10 41 02 AM" src="https://user-images.githubusercontent.com/46905241/165814785-26d5614c-3d8e-4e3e-b00d-372fb58f38b2.png">

Board view (looks correct):
<img width="282" alt="Screen Shot 2022-04-28 at 10 42 25 AM" src="https://user-images.githubusercontent.com/46905241/165814808-019b200d-c7cf-470e-bc4a-a5beaf0a6eb0.png">

## Edition and Platform

 - Edition: Personal Desktop / Personal Server / Mattermost Boards (plugin)
 - Version: v0.16
 - Browser and OS: Chrome on Mac

## Additional context (optional)

Repros on v0.15, and on Personal Server as well.

**Comment by wuwinson** [comment]
@Rajat-Dabade For post v0.16. Thanks!

**Comment by Rajat-Dabade** [comment]
Merge to `main`, closing this issue.
