### ISSUE TITLE
Bug: Mysql driver, syntax error

### ISSUE THREAD

**Issue by ariitano** [mattermost/focalboard#2999]
## Steps to reproduce the behavior

1. change the original config file to use a mysql database
2. build and start the container
3. get logs

error [2022-04-29 12:14:12.087 +02:00] Table creation / migration failed        caller="sqlstore/sqlstore.go:65" error="driver: mysql, message: failed when applying migration, command: apply_migration, originalError: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json)) WHERE fields->'$.columnCalculations' = cast('[]' as json);

## Expected behavior
The required tables will be created into the mysql database

## Edition and Platform
 - Docker latest

Seems to be a problem here:
https://github.com/mattermost/focalboard/blob/ae97d5c314039c7c529ee66b0a92beb7d8fa05a5/server/services/store/sqlstore/migrations/000017_add_teams_and_boards.up.sql#L16

**Comment by wuwinson** [comment]
@ariitano Sorry, but we do not officially support MariaDB. Please see [here](https://docs.mattermost.com/install/software-hardware-requirements.html?#database-software) for more details. Thanks!

**Comment by ariitano** [comment]
Then, If mysql/mariadb is not supported, please remove the examples from the documentation and the partial (and not working) routines from the code. 
The actual situation is misleading.

Thank you
