### ISSUE TITLE
Doc: Migrating permissions for customers with larger DBs

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3019]
## Summary

Permission migrations are failing for large DBs. Document permissions migration steps for larger DB's in v6.7 release (Boards v0.16) notes and potentially in Boards Help Docs.

- What threshold is considered "large"?
- What steps do our customers have to do differently to migrate their DB when upgrading to the v6.7 release (Boards v0.16)?

## Link to documentation page

TBD - waiting on updates from @mgdelacroix and @chenilim

**Comment by justinegeffen** [comment]
@wuwinson, where would you like this to be documented?

**Comment by wuwinson** [comment]
@mgdelacroix Will this still be an issue for v7.2? @justinegeffen No docs needed on this before then.

**Comment by wuwinson** [comment]
Deferring this for now, may not be needed for v7.2 since we've had more time to address this.

**Comment by mgdelacroix** [comment]
@wuwinson @justinegeffen I prepared [this document](https://docs.google.com/document/d/1hKQV6QfXSJ6LznvKxoENvU1Z21ulaZ09b-h8N1caS64/edit#) following the Server Team's guidelines for migration changes. We should add it to the Release Notes for admins to check before migrating.

Please let me know if any editing or clarification is required.

**Comment by wuwinson** [comment]
Thanks @mgdelacroix! @justinegeffen In addition to wherever you think this should go, can we also create a subpage under our [What's New](https://docs.mattermost.com/welcome/whats-new-in-v72.html) page and link to it in the following areas?

- Release Notes
- Under the [Automatic Migration](https://docs.mattermost.com/welcome/whats-new-in-v72.html#automatic-migration) section
- Another under [this FAQ](https://docs.mattermost.com/welcome/whats-new-in-v72.html#will-i-need-to-backup-and-restore-any-data)

**Comment by justinegeffen** [comment]
That looks good to me, I like those suggestions @wuwinson. I'll sort it out this weekend.

**Comment by justinegeffen** [comment]
@mgdelacroix, would you be open to adding an entry in the Cloud changelog [here](https://github.com/mattermost/docs/pull/5828/files) regarding the issue with a link to the doc?

**Comment by justinegeffen** [comment]
PR for What's New doc updates is here: https://github.com/mattermost/docs/pull/5840.
