### ISSUE TITLE
Bug: Text cursor is hard to see in dark theme

### ISSUE THREAD

**Issue by Johennes** [mattermost/focalboard#302]
**Summary:**

In the dark theme, when editing a text block on a card, the cursor is using a light shade of gray that makes it rather hard to see against the white background.

In the light theme, the contrast is a lot stronger and the cursor is easy to spot.

This is usually not a problem when appending text. However, when moving through existing text it can sometimes get tricky to spot the cursor.

**Steps to reproduce the behavior:**

1. Open a card
2. Click into a text block to enter editing
3. Notice that the cursor is hard to see

**Expected behavior:**

The cursor should be easy to see. This could be achieved by simply giving it a darker color. Alternatively, maybe the background could be changed. The board title field, for instance, uses a light cursor on a dark background when editing.

**Screenshots:**

![Screenshot 2021-04-20 at 12 37 35](https://user-images.githubusercontent.com/1137962/115382826-69cbc500-a1d5-11eb-921a-19d253ea74cd.png)

![Screenshot 2021-04-20 at 12 38 08](https://user-images.githubusercontent.com/1137962/115382829-6a645b80-a1d5-11eb-8184-95218eea0937.png)

![Screenshot 2021-04-20 at 12 46 19](https://user-images.githubusercontent.com/1137962/115383686-7270cb00-a1d6-11eb-8fb8-631256e17269.png)

**Platform:**

macOS 11.2.1
Focalboard v0.6.0

**Additional context:**

I wasn't sure about the best way to file this. It's more of an accessibility rather than a functional bug but it didn't seem to fit the feature / enhancement category.

**Comment by asaadmahmood** [comment]
@Johennes This look fine to me. Please refer to the screenshots.
And if the issue still exists, please post a screenshot of a place where it still looks bad.

<img width="284" alt="Screenshot 2021-04-26 at 5 01 11 PM" src="https://user-images.githubusercontent.com/11034289/116079302-11069b80-a6b1-11eb-8930-94a6a21b4f6f.png">


<img width="460" alt="Screenshot 2021-04-26 at 4 59 36 PM" src="https://user-images.githubusercontent.com/11034289/116079038-cbe26980-a6b0-11eb-8fdc-4fd027c3fbf4.png">

**Comment by Johennes** [comment]
This looks good for me in 0.6.5 now (original noticed this in 0.6.0). Thanks a lot @asaadmahmood!
