### ISSUE TITLE
Bug: Selecting "Create a board" from the channel intro doesn't open the template picker

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#3021]
## Steps to reproduce the behavior

1. Select "Create a board" from the channel intro (scrolling to the very beginning of a channel)
2. The last opened board opens

## Expected behavior

The template picker should open

## Screenshots (optional)

<img width="504" alt="Screen Shot 2022-05-03 at 10 27 21 AM" src="https://user-images.githubusercontent.com/46905241/166507810-b8d8a223-70e6-40e0-bf16-5aa6454515bb.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.16
 - Browser and OS: Chrome on Mac

## Additional context (optional)

This is a regression from v0.15.

**Comment by sbishel** [comment]
@chenilim - Could you retest? This seems to work as you describe on -
https://boards-bugbash.test.mattermost.cloud/

**Comment by chenilim** [comment]
Thanks @sbishel. Yup, retested again on https://boards-bugbash.test.mattermost.cloud/ and it didn't repro for me, so closing.
