### ISSUE TITLE
Impossible delete templates when created by 'New template from board'

### ISSUE THREAD

**Issue by ricfio** [mattermost/focalboard#3038]
### Discussed in https://github.com/mattermost/focalboard/discussions/2291

<div type='discussions-op-text'>

<sup>Originally posted by **kafeiweimei** February  8, 2022</sup>
![image](https://user-images.githubusercontent.com/18021399/153003860-45d72257-962f-4b3e-b556-040d5490e312.png)
</div>

In my experience, it seems there is no way to delete the board template created by "New template from board".

So I can delete "Untitled Template" (see image below): 
![image](https://user-images.githubusercontent.com/69871782/167166191-3cb828b0-0fc6-4a4e-98ca-bf68513b211a.png)

while it's impossible delete "New board template" and "New2-temp", beacuse created from "New template from board"
![image](https://user-images.githubusercontent.com/69871782/167166739-b50caddb-30b7-421a-9e31-595f64c11c37.png)

![image](https://user-images.githubusercontent.com/69871782/167165801-9de8f355-7b0e-4839-b45c-75be1c44ae57.png)
![image](https://user-images.githubusercontent.com/69871782/167165919-87a6f939-f597-4105-99fa-f3bfaab80ac3.png)

**Comment by wuwinson** [comment]
@ricfio Thanks for filing this issue. To help us triage the issue, can you provide more details on your edition and platform?

 - **Edition:** Personal Desktop / Personal Server / Mattermost Boards (plugin)
 - **Version:** [e.g. v0.15.0]
 - **Browser and OS:** [e.g. Chrome on Mac, Edge on Windows]

**Comment by ricfio** [comment]
Hi, here my two client, both affetcted by the bug. Thank you.

Web client:
- **Edition**: Mattermost Boards (plugin) for Web browsers
- **Version**: [v5.0.4](https://www.focalboard.com/fwlink/doc-boards.html?v=0.15.0)
- **Browser and OS**: Chrome 101.0.4951.54 on Windows 10

Windows client:
- **Edition**: Personal Desktop for Windows
- **Version**: v5.0.4
- **OS**: Windows 10
