### ISSUE TITLE
Feature Idea: 

### ISSUE THREAD

**Issue by Trincazul** [mattermost/focalboard#3044]
## Summary

I use the desktop program daily, and every time I restart the process it comes back without the settings I configured.
it returns the random icons and light mode

## How important this is to me and why

Importance: Low

Use cases:
1. save configuration state

## Additional context/similar features
would there be any method to make it return with the settings saved in desktop?

**Comment by Trincazul** [comment]
I forgot to mention that I use it on a Linux Mint

**Comment by wuwinson** [comment]
Thanks @Trincazul, looks like a dupe of https://github.com/mattermost/focalboard/issues/2198. Will reference this ticket there. Closing this one out.
