### ISSUE TITLE
Bug: Cannot add/change assignee

### ISSUE THREAD

**Issue by fubo73** [mattermost/focalboard#3057]
Hi,

I cannot add/change assignee using focalboard desktop for windows.

## Steps to reproduce the behavior

1. Just extract .zip locally
2. Execute focalboard and select Project Tracker template
3. Open a task and try to edit assignee

## Expected behavior

I expect to be able to add/change assignee

## Edition and Platform

 - Edition: Personal Desktop
 - Version: v0.15.0
 - Browser and OS: Windows 10 x64

**Comment by wuwinson** [comment]
@fubo73 Thanks for your feedback! Personal Desktop is a single user app, so the only user available on the `PERSON` property would be yourself. I've filed https://github.com/mattermost/focalboard/issues/3077 as an enhancement idea. Please try our [Personal Server](https://www.focalboard.com/download/personal-edition/ubuntu/) or [Mattermost Boards plugin](https://www.focalboard.com/download/mattermost/latest-plugin/) editions, which support multiple users. Thanks!
