### ISSUE TITLE
Bug: Custom templates created from global templates are not editable/deletable after creation

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3061]
## Steps to reproduce the behavior

1. Go to a board created from any of the global templates
2. Click on the "..." sidebar menu on a board name
3. Select  "New template from board" option
4. Name the custom template
5. Go to template picker
6. Mouse over the new custom template
7. Try to edit or delete template
8. See error - no buttons to edit or delete

Note: Issue does not occur for custom templates created from scratch directly from the template picker, or when using the sidebar "New template from board" option on a template created from scratch. Only applies to creating a custom template from a global template.

## Expected behavior

Custom templates created from a global template should display the edit and delete buttons when mousing over the template name. 

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/168148346-cd11341b-44ee-48b4-bb58-f1fe8544d059.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.0
 - Browser and OS: Chrome on Mac

Related to #3038

**Comment by Pinjasaur** [comment]
closed by #3125 (not sure why it didn't auto-close, I used the `fixes` keyword)
