### ISSUE TITLE
Bug: Desktop App redirects to Error Page

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#3068]
## Steps to reproduce the behavior

I noticed something odd when playing with the Desktop App. It seems as though new accounts on community (tested with my own test account) when they go to Boards for the first time get the attached image. And anytime I try to use the Global Header to go to Boards, or even on refresh they get stuck on that page.

It seems to go away once I explicitly open a Board and then from there I can go to the Dashboard and everything is fine. Is this a known issue or has anyone else seen this? It was reported during our MAS review.

## Screenshots (optional)
![Image Pasted at 2022-5-13 11-45](https://user-images.githubusercontent.com/12704875/168335467-a7b89266-f4e4-4a64-9fef-b593eeeef272.png)

## Edition and Platform

 - Edition: Mattermost Boards
 - Version: v0.15.0
 - Browser and OS: Desktop App

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by wuwinson** [comment]
@ogi-m Can you try to get a consistent repro steps on this bug? Thanks!

**Comment by chenilim** [comment]
I added my repro steps to https://github.com/mattermost/mattermost-server/issues/20251, and was eventually able to get to the Dashboard by:
1. Clicking on "Return to home" (Channels tab appears)
2. Selecting the Boards tab
3. Refreshing with Cmd+Shift+R (error reappears)
4. Selecting Boards from the App Switcher menu

The problem repros if I delete the App, then re-download it from the App Store and re-login.

**Comment by chenilim** [comment]
Bumping this up to Sev/1 as this will apparently affect all new users of the Desktop App, and the workaround is not at all obvious.

**Comment by devinbinnie** [comment]
I remember doing a little debugging with this on the Desktop App.
It looks like Boards by default is redirecting to `/workspace/0/null/null`, which I assume would normally be the last used workspace. But since new users wouldn't have one of those, that's probably why the above is happening.

You can reproduce and see the issue in the Desktop App by turning on DEBUG logging.

**Comment by chenilim** [comment]
Thanks @devinbinnie! Sorry if it's an FAQ, but how do we turn on DEBUG logging?

I'm also able to restart the repro using the dev console (instead of reinstalling):
1. Open the dev console (View \ Developer Tools for Current Server)
2. Open the Application tab, and select Local Storage
3. Clear the local storage for the server
4. Refresh (Cmd+R)

**Comment by devinbinnie** [comment]
@chenilim It's in the Settings window, near the bottom you can change the logging level to 'Debug'

**Comment by chenilim** [comment]
Thanks for the help @devinbinnie! For reference, after updating the log level in Preferences, you can find the logs (`main.log`) under `~/Library/Containers/Mattermost/Data/Library/Logs/Mattermost` (or `~/Library/Containers/Mattermost Desktop/Data/Library/Logs/Mattermost`).

For me, this contained the entry:
```
[2022-05-19 10:29:58.647] [debug] webContentEvents.did-start-navigation {
  webContentsId: 5,
  url: 'https://community-daily.mattermost.com/boards/workspace/0/null/null'
}
```
which is what Devin also saw.

@harshilsharma63, does this look familiar to the previous issues around the initial routing?

**Comment by harshilsharma63** [comment]
Looking into this now.

**Comment by harshilsharma63** [comment]
@chenilim @sbishel works fine on the latest release of Desktop app and latest release-7.0 branch. @ogi-m can you please verify this and close if it works fine?

**Comment by harshilsharma63** [comment]
@chenilim verified on on Mattermost desktop app installed from the Apple App Store as well. All works fine.

**Comment by harshilsharma63** [comment]
@chenilim just FYI I'm testing on latest Mattermost with release-7.0 version of focalboard locally. As that contains a fix for navigation issue in desktop app.

**Comment by chenilim** [comment]
Just tried this again and it repros against https://boards-bugbash-7rc4.test.mattermost.cloud (using the Mac App Store version of Mattermost desktop, Version 5.1.0 (19937)). Same steps as above.

**Comment by chenilim** [comment]
@harshilsharma63, here's a video of the behavior I see, which also repros for Winson:

https://user-images.githubusercontent.com/46905241/172237396-d10d8a17-a55d-4b33-a15f-fb8991ff4ed9.mov
