### ISSUE TITLE
Bug: Clickable area for views in left panel is too small

### ISSUE THREAD

**Issue by Johennes** [mattermost/focalboard#307]
**Summary:**

Not a functional but rather an accessibility bug: When hovering views in the left panel, they highlight. The area that is clickable and where the cursor turns into a pointer is a lot smaller than the highlighted area though. Occasionally this results in having to double click to activate the view because the first click landed outside the clickable area.

**Steps to reproduce the behavior:**

1. Hover over a view name in the left panel
2. Try to click it at the edges
3. Notice how it's only possible to click close to the label

**Expected behavior:**

I think ideally the whole highlighted area should react to clicks.

**Screenshots:**

![Screenshot 2021-04-21 at 07 53 25](https://user-images.githubusercontent.com/1137962/115504110-b071fb80-a277-11eb-9a20-6728dde9d2ff.png)

(Approximate) clickable area marked in red.

**Platform:**

macOS 11.2.1
Focalboard v0.6.0

**Comment by chenilim** [comment]
Thanks @Johennes! Agree that the entire row should be clickable. This might require more than just a CSS change. The fix might involve refactoring the sidebar items layout. Opening it up to any takers.

**Comment by Johennes** [comment]
Luckily it didn't require much more than moving the click-handler up from the title element to the row itself. I opened #344. 🙂
