### ISSUE TITLE
Doc: How to Generate PAT for Personal Server API

### ISSUE THREAD

**Issue by carlos-sarmiento** [mattermost/focalboard#3072]
## Summary

I'm trying to use the API docs here () to get some data out of my boards and into Home assistant. On the documentation there is a login function but there doesn't seem to be a way to create a Personal Access Token. From reading the mattermost V4 API it seems there is a way. Is it missing documentation or is the feature missing from Focalboard?

## Link to documentation page
https://htmlpreview.github.io/?https://github.com/mattermost/focalboard/blob/main/server/swagger/docs/html/index.html#api-Default-login

**Comment by chenilim** [comment]
Thanks for asking @carlos-sarmiento! To auth against Personal Server, first call login with your credentials to get a token, e.g.
```
curl -X POST \
 -H "Accept: application/json" \
 -H "X-Requested-With: XMLHttpRequest" \
 -H "Content-Type: application/json" \
 "http://localhost:8000/api/v1/login" \
 -d '{
  "type" : "normal",
  "username" : "testuser",
  "password" : "testpass"
}'
```

This should return a token in the form:
```
{"token":"abcdefghijklmnopqrstuvwxyz1"}
```

Pass this as the bearer auth to subsequent calls, e.g.
```
curl -X GET \
 -H "Accept: application/json" \
 -H "Authorization: Bearer abcdefghijklmnopqrstuvwxyz1" \
 -H "X-Requested-With: XMLHttpRequest" \
 -H "Content-Type: application/json" \
 "http://localhost:8000/api/v1/workspaces/0/blocks"
```

See the API documentation for getting the token for Mattermost Boards, and for additional details.

Please LMK if the steps above don't work for you.

**Comment by shlyapp** [comment]
Привет!

А какие еще бывают типы токенов? Если использовать "нормальный", то я не могу редактировать таблицу. Не совсем понимаю вашу документацию по API :(

**Comment by shlyapp** [comment]
Hi!

What other types of tokens are there? If I use the "normal" one, I can't edit the table. I don't quite understand your API documentation :(
