### ISSUE TITLE
Bug: Link to Cards Does Not Load Card on Firefox

### ISSUE THREAD

**Issue by projectsSD** [mattermost/focalboard#3078]
##Summary

Link to board card does not load the card on Firefox

## Edition and Platform

 - Edition: MM Team Edition on Linode Server running in Docker 
 - Version: 6.3.8
 - Browser and OS: Firefox on Linux

##Steps to reproduce

1. Copy link to a card
2. Post link to the card in a channel
3. Click on the link
4. The link will bring you to the board, but the card itself will not load
5. After this, going to other boards or trying to open other cards will not work
6. Refresh the page and cards will load okay (until the link is clicked again...)

Tested in Chrome and everything works okay.

##Expected behavior

Click on the link and the board page will open with the card opened too

## Observed behavior (that appears unintentional)

The board loads, but the card does not open, and then other cards cannot be opened too.

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 3: Affects minor, non-critical functionality

**Comment by wuwinson** [comment]
@projectsSD This should be fixed in Boards v0.15 (Mar 2022) - can you upgrade to the latest version and see if you're still running into this issue? Please feel free to re-open if so, thanks!
