### ISSUE TITLE
Bug: Boards plugin does not load in browser after reinstalling Mattermost

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3095]
## Steps to reproduce the behavior

1. open "boards" in browser
2. delete mattermost
3. do clean reinstall
4. restore a database backup
5. install plugins again
6. open "boards" in browser again — it indefinitely reloads the page or shows an error related to the "wrong workspace" or something.

It worked in the desktop app so I tried to clear the website data, and it helped. See [thread](https://community.mattermost.com/core/pl/696roptyopnbbccbnqi935e8qc) for reference.

## Expected behavior

Boards should load properly after reinstalling.

## Screenshots (optional)

If applicable, add screenshots or a screen recording to elaborate on the problem.

## Edition and Platform

 - Edition: Personal Desktop / Personal Server / Mattermost Boards (plugin)
 - Version: [e.g. v0.15.0]
 - Browser and OS: [e.g. Chrome on Mac, Edge on Windows]

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by chenilim** [comment]
@wuwinson, please add more detailed steps, particularly around what "delete mattermost" means? E.g. re-install the server? May be related to https://github.com/mattermost/focalboard/issues/3068.

**Comment by wuwinson** [comment]
@chenilim Filed this from a community member post - still waiting on more clarity, but we can close if we don't hear back by next week.
