### ISSUE TITLE
Bug: Horizontal/vertical scroll reset

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3097]
## Steps to reproduce the behavior

1. Go to a board that requires horizontal scrolling like the [Focalboard v1 - Target Release](https://community.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/b4ctmm917q3rzdfi451qtuxjzcw/vuswsftt1rb873datosmmbtwkpa) board
2. Scroll all the way to the right
3. Open a card
4. Close the card
5. See error - Horizontal scroll resets
6. For boards with many cards on a column, try scrolling down to repro same issue with vertical scrolling.

## Expected behavior

Board remains in the same position after opening and closing a card. Please note this occurs on v0.15, but not on the new [bugbash2 server](https://bugbash-boards2.test.mattermost.cloud/boards/team/ogyyzbwg9pr65pcwnec9gi9aqw/btccoz8srqtfpjddpp9a8h514se/v3mhqswfdnjnsjy55ue6b9fsdqa).

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/169611691-1ea3373f-155c-4b93-bda0-81068bc8abb8.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.15.0
 - Browser and OS: Chrome on Mac

**Comment by chenilim** [comment]
If this doesn't repro on main, it should be fixed in 7.2, and since it is a sev-3, won't backport to previous versions.
