### ISSUE TITLE
Fix server lint issues

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#31]
Run `make server-lint` to see the list of Go lint issues. We should incrementally fix them.

**Comment by Snehal1112** [comment]
@chenilim I would like to work  on this issue

**Comment by chenilim** [comment]
Thanks @Snehal1112! I recommend tackling this incrementally.  `make server-lint` will show the list of lint errors, but some of them might be false positives. Start with the ones you feel most comfortable with, and we can make multiple PRs. Thank you for contributing to Focalboard!

**Comment by Snehal1112** [comment]
@chenilim @jespino Quick question!! In code, I found there is some code which never used anywhere e.g. https://github.com/mattermost/focalboard/blob/main/server/app/blocks.go#L37 
It intentionally did that or someone forgot to remove it.

**Comment by chenilim** [comment]
Hi @Snehal1112, thanks for catching that! Yup, I forgot to remove them when refactoring. :) Please go ahead and remove `blockIDsToNotify` and `uniqueBlockIDs` from InsertBlocks and DeleteBlock. They aren't used. Thanks!

**Comment by Snehal1112** [comment]
@chenilim thanks will do. I am going to create multiple PR for linter issues so each PR contains a fix for individual modules.
feel free to suggest any other better way.

**Comment by harshilsharma63** [comment]
I'm picking this up due to the inactivity.
