### ISSUE TITLE
Bug: Cannot access all views from view switcher a slist goes beyong viewport

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#3106]
If you have too many views, it's impossible to access them via the view switcher on boards. See screenshot-

<img width="709" alt="Screenshot 2022-05-24 at 11 55 36 AM" src="https://user-images.githubusercontent.com/18575143/169963095-b209adaf-3ba1-4978-8633-7a36028d95db.png">

**Comment by chenilim** [comment]
Also consider that if the window height is too short, the full menu may not fit.

**Comment by Rajat-Dabade** [comment]
@chenilim @harshilsharma63 @sbishel 
This is what I can best think of for this bug. 

https://user-images.githubusercontent.com/26198062/174447519-e9ae0877-d827-4837-8af0-0b42c024c499.mov

**Comment by sbishel** [comment]
I'm good with the fix. @chenilim @asaadmahmood @wuwinson ?

**Comment by chenilim** [comment]
Looks good to me @Rajat-Dabade!

**Comment by asaadmahmood** [comment]
Looks good.

**Comment by harshilsharma63** [comment]
Looks good!

**Comment by Rajat-Dabade** [comment]
PR merged and all the changes are ported to main, so closing the issue.

**Comment by kamre** [comment]
@Rajat-Dabade it seems that **always showing the scroll** for the list of views doesn't look good (single Table view on this screenshot):
<img width="259" alt="image" src="https://user-images.githubusercontent.com/5587620/175789536-f5c662ce-a284-4863-8987-8ac4a28347f6.png">
@asaadmahmood what do you think?

**Comment by asaadmahmood** [comment]
@kamre It shouldn't show the scroll always, only when there is something to scroll, more like overflow: auto, rather than overflow: scroll.
