### ISSUE TITLE
Bug: Cannot create the first user after fresh install

### ISSUE THREAD

**Issue by isven42** [mattermost/focalboard#3108]
## Steps to reproduce the behavior

1. Install focalboard and postgres like in this guide: https://docs.mattermost.com/boards/focalboard/installing-boards.html#personal-server 
2. Configure nginx 
3. Configure systemd 
4. Start server

## Expected behavior

On the Loginpage i click on register. Expected: New User is going to be created.

## Screenshots (optional)

![grafik](https://user-images.githubusercontent.com/103841208/170033084-bc1fe8eb-d4cf-4ba2-91c1-d9b30ef0faca.png)

## Edition and Platform

 - Edition: Personal Server Ubuntu 20.04
 - Version: [e.g. v0.15.0]
 - Browser and OS: firefox

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* SystemdJob works
* Redirect of nginx works
* nginx focalboard.<domain>.com:

upstream focalboard {
   server localhost:8000;
   keepalive 32;
}

server {

   server_name <domain>;
          <basic-auth>

   location ~ /ws/* {
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
       client_max_body_size 50M;
       proxy_set_header Host $http_host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Frame-Options SAMEORIGIN;
       proxy_buffers 256 16k;
       proxy_buffer_size 16k;
       client_body_timeout 60;
       send_timeout 300;
       lingering_timeout 5;
       proxy_connect_timeout 1d;
       proxy_send_timeout 1d;
       proxy_read_timeout 1d;
       proxy_pass http://focalboard;
   }

   location / {
       client_max_body_size 50M;
       proxy_set_header Connection "";
       proxy_set_header Host $http_host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Frame-Options SAMEORIGIN;
       proxy_buffers 256 16k;
       proxy_buffer_size 16k;
       proxy_read_timeout 600s;
       proxy_cache_revalidate on;
       proxy_cache_min_uses 2;
       proxy_cache_use_stale timeout;
       proxy_cache_lock on;
       proxy_http_version 1.1;
       proxy_pass http://focalboard;
   }

    listen 443 ssl; 
    <ssl-conf>

}

server {
    if ($host =<domain>) {
        return 301 https://$host$request_uri;
    } 

   listen 80 default_server;

   server_name <domain>;
    return 404; 

}

**Comment by wuwinson** [comment]
@isven42 Thanks for sharing. Can you try the following next steps:

1. Delete the database and restart the server
2. If that doesn't work, query the database and check that the Users table is empty

Thanks! cc @chenilim @sbishel

**Comment by isven42** [comment]
> 

i already did that. Doesnt fix the problem. But i was able to get it working. The steps i did:
1. moved to root of subdomain -> doesnt fix it neither
2. removed basic auth -> fixed it. Is there a possibility to get focalboard work with an already set auth-header?

**Comment by isven42** [comment]
> For more context, the [first user can be added without the token](https://www.focalboard.com/guide/server-setup/#registering-the-first-user).

I wasnt able to add the first user, i ran into an error shown above
