### ISSUE TITLE
Bug: Header buttons misaligned to the right

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3114]
## Steps to reproduce the behavior

1. Go to any board
2. See the `Share` and `New` buttons on the right
4. See error - minimal padding on the right

## Expected behavior

More padding on the right of the board header buttons

## Screenshots (optional)

![Screen Shot 2022-05-24 at 5 51 51 PM](https://user-images.githubusercontent.com/93531870/170139060-26113da2-ebee-4485-b0e5-82406bf68284.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.0-RC1
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment]
cc @asaadmahmood

**Comment by wuwinson** [comment]
Can't repro, closing out.

**Comment by Pinjasaur** [comment]
https://user-images.githubusercontent.com/6335792/172917040-a345da5f-ac5c-4c31-9607-c00898067888.mov

**Comment by Rajat-Dabade** [comment]
This issue is been fixed as a part of PR: https://github.com/mattermost/focalboard/pull/3261, so closing this issue. 
cc: @wuwinson @sbishel @Pinjasaur
