### ISSUE TITLE
Bug: Limit dialog is not shown on duplicate view

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#3117]
## Steps to reproduce the behavior

1. On a Free Cloud server, Create a board with 5 views
2. Select "Duplicate view" from the view dropdown
3. Nothing happens

## Expected behavior

The view limit dialog should be shown.

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.0.0
 - Browser and OS: Chrome on Mac

**Comment by sbishel** [comment]
duplicate of - https://github.com/mattermost/focalboard/issues/3116
