### ISSUE TITLE
Bug: Boards functionality not available w/ MM 6.2

### ISSUE THREAD

**Issue by aagha** [mattermost/focalboard#3118]
## Steps to reproduce the behavior

N/A

## Expected behavior
Expect to see Boards in the Plugin Management list

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/5522103/170154385-92010a8c-75d4-4218-a7b2-ae968499ee77.png)

## Edition and Platform

 - Edition: Personal Desktop / Personal Server / Mattermost Boards (plugin)
 - MM version: 6.6.1
 - Browser and OS: Chrome on Windows
 - Client: 5.1.0

![image](https://user-images.githubusercontent.com/5522103/170154498-e0db3421-f4a9-48f0-be92-4c6e34fd77fd.png)

![image](https://user-images.githubusercontent.com/5522103/170154503-2594cc33-ab48-4ad6-802d-cd0a4a9f5fbd.png)

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
Sev 1 issue where enabling Boards is not possible.

Trying to enable following the directions here, but can't enable:

https://docs.mattermost.com/boards/getting-started.html

**Comment by wuwinson** [comment]
@aagha Thanks for sharing! Can you confirm if the Boards plugin is enabled on the system console via the Plugin tab? See below for details:
![Screen Shot 2022-05-25 at 2 52 07 PM](https://user-images.githubusercontent.com/93531870/170346440-db29f2e4-34d3-4a19-ac3e-711e78d0bf55.png)

**Comment by aagha** [comment]
Hi @wuwinson 

I scrolled through the list and it doesn't even exist there:

![image](https://user-images.githubusercontent.com/5522103/170385119-07481f70-f4a1-4b53-8be0-8ad30dd06fb8.png)

**Comment by wuwinson** [comment]
Closing out. @aagha Feel free to re-open if you have any more details. Thanks!
