### ISSUE TITLE
Bug: Cloud Limits not setting hidden cards

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#3121]
## Steps to reproduce the behavior

1. Go to a server with Cloud Limits Set
2. Enter several (10+) cards
3. Select  Import Archive and import file with 490 cards
4. Add another card.
5. The card limits message is displayed, but no cards are hidden.

Here is archive with 490 cards. 
https://community.mattermost.com/core/pl/44p86yby9j8xxe8qcmkdg6nrow

## Expected behavior

The older cards should be hidden. 

Appears that the "card_limit_timestamp" is not getting set. 
This is the return from our call to `limits`

https://sbishel-test.test.mattermost.cloud/plugins/focalboard/api/v1/limits
{"cards":500,"used_cards":518,"card_limit_timestamp":0,"views":5}

## Screenshots (optional)

If applicable, add screenshots or a screen recording to elaborate on the problem.
<img width="442" alt="Screen Shot 2022-05-25 at 8 30 30 AM" src="https://user-images.githubusercontent.com/12704875/170287998-e7bdfdb3-98a2-4c02-82af-67c6a91515e0.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.0.0-rc2
 - Browser and OS: Chrome on Mac

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by mgdelacroix** [comment]
https://github.com/mattermost/focalboard/pull/3149 should trigger limit calculation after running an import. I couldn't repro the `cardLimitTimestamp = 0` state, could you please @sbishel try to reproduce it with the patch applied, in case there is something I'm missing?

**Comment by sbishel** [comment]
I can still duplicate this, but I don't think it is an issue with the limits code. After reloading the database, the first thing that needs to happen is updating the license to a cloud license (for testing). The limits get loaded in `OnActivate`, but if the license isn't a cloud license there are no limits. 

The real bug is that we are not listening for Licensing changes, which for this feature won't matter. License will be cloud, but when we have features based on license, this will be a problem. 

I will create a ticket to track.
