### ISSUE TITLE
Bug: Publish a template shouldn't be allowed

### ISSUE THREAD

**Issue by jespino** [mattermost/focalboard#3136]
## Steps to reproduce the behavior

1. Go to a custom template
2. Click on Share
3. You should be able to see publish there

## Expected behavior

I would expect that no publish option exists for templates

## Screenshots (optional)

![imagen](https://user-images.githubusercontent.com/290303/170453928-7ca4da48-ed0e-4b73-94c2-4bdd2c017234.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.0-rc2
 - Browser and OS: Firefox

**Comment by wuwinson** [comment]
This portion of the share modal is removed for v7.2. Okay with this for v7.0 since it's low impact. Closing out.
