### ISSUE TITLE
Bug: Create empty board makes all boards dissapear

### ISSUE THREAD

**Issue by jespino** [mattermost/focalboard#3137]
## Steps to reproduce the behavior

1. Go to add board
2. Select  create empty board
3. The list of boards gets empty.
4. If you do any action that refresh that, you get the list again.
5. It happens randomly time to time due a 500 error from the server (calling `/plugins/focalboard/api/v1/workspaces/7qrxz3s4w78t9d34psfqcok89a/blocks?all=true`)

## Expected behavior

I would expect to not clear the list of boards never and not receive a 500 error from the server

## Screenshots (optional)

![imagen](https://user-images.githubusercontent.com/290303/170454957-2c77c850-d1d5-4887-ae9b-ff678a10de83.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.0-rc2
 - Browser and OS: Firefox

**Comment by mgdelacroix** [comment]
Most probably related to https://github.com/mattermost/focalboard/issues/3134

**Comment by sbishel** [comment]
Appears to be fixed in RC3 - https://boards-bugbash-7rc3.test.mattermost.cloud/

**Comment by wuwinson** [comment]
Can't repro on RC3, closing out.
