### ISSUE TITLE
Bug: Can not start a new line when the Type/Property is of "Text" 

### ISSUE THREAD

**Issue by tropicaljungle** [mattermost/focalboard#3138]
## Steps to reproduce the behavior

1. Go to "add a new property"
2. Select  "Text" on Type
3. Input some text and press ENTER key,
4. Can not start a new line in this input box

## Expected behavior

By pressing Enter key a newline should be started

## Edition and Platform

 - Edition: Personal Server 
 - Version: v0.15.0
 - Browser and OS: Edge on Windows

**Comment by wuwinson** [comment]
@tropicaljungle Thanks for reporting! This is actually the current expected behavior, but I filed #3147 as an enhancement idea with this bug linked to the ticket. Please feel free to add any additional feedback to that ticket. Thanks!

**Comment by tropicaljungle** [comment]
Great! Thank you! [thumb up]
