### ISSUE TITLE
Bug: View title cut off when using emoji

### ISSUE THREAD

**Issue by Johennes** [mattermost/focalboard#316]
**Summary:**

When using the 🧑‍💻 emoji in the title of a view, the title is offset towards the bottom and cut off. This seems to happen with other emojis as well.

**Steps to reproduce the behavior:**

1. Go to a view in a board
2. Change its title to "🧑‍💻 Reports"
3. Notice how the title is clipped at the bottom
4. Remove the 🧑‍💻 emoji
5. Notice how the title is not clipped anymore

**Expected behavior:**

The title should not clip regardless of whether it contains emojis.

**Screenshots:**

![gif](https://user-images.githubusercontent.com/1137962/115692429-43399580-a35f-11eb-9c07-f6369d67e459.gif)

**Platform:**

macOS 11.2.1
Focalboard v0.6.5

**Comment by chenilim** [comment]
Thanks @Johennes! Took a quick look, and this repros on Safari in addition to the Mac App. Looks like Safari has different default css for input elements. @asaadmahmood, is this something you'd like to take a look at? Also opening this up to any other takers.

**Comment by asaadmahmood** [comment]
Yup I can take it @chenilim
