### ISSUE TITLE
Bug: Card limit notification CTA not working for admins

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3176]
## Steps to reproduce the behavior

1. Login as an admin on https://boards-bugbash-7rc4.test.mattermost.cloud/boards/
2. Ensure that the server is over the 500 card limit in app switcher
3. Create a new card
4. See the card limit notification on the bottom right
5. Click on the CTA "Upgrade to a paid plan"
6. See error - nothing happens

## Expected behavior

Clicking on the CTA opens the pricing modal

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/171710912-1ebb9b86-ce34-46a0-91b6-9660ad7e68b0.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.0 RC4 (https://boards-bugbash-7rc4.test.mattermost.cloud/boards/)
 - Browser and OS: Chrome on Mac

**Comment by sbishel** [comment]
@jespino - I think this was fixed by [this PR](https://github.com/mattermost/focalboard/pull/3169)

**Comment by wuwinson** [comment]
Looks fixed in v7.0.
