### ISSUE TITLE
Bug: Clicking on "Cards Hidden" button does nothing

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3178]
## Steps to reproduce the behavior

1. Go to https://boards-bugbash-7rc4.test.mattermost.cloud/boards/workspace/e8my97k5w7ytfqxozpddy619bo/bcxcgyucwktfj9b6iq7t1cmrrac/v6ujoqc4hdif8bphnwdrwgtzftr
3. Click on `Cards Hidden` button on the right of the board
4. See error - nothing happens

## Expected behavior

Clicking on `Cards Hidden` should open the pop-up.

## Screenshots (optional)
Actual:

https://user-images.githubusercontent.com/93531870/171742424-29e5cd1b-5262-4fcb-bc5e-17f89124f16b.mov

Expected:
![Image Pasted at 2022-6-2 17-31](https://user-images.githubusercontent.com/93531870/171741962-eb8ef62c-86ea-47a8-9f89-6ce29ceb3160.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.0 RC4
 - Browser and OS: Chrome on Mac

**Comment by sbishel** [comment]
@wuwinson This is why I asked for all this information from Figma to be transferred to the spec. It is too easy to get lost in the Figma. 
@Rajat-Dabade - Please see what it will take to implement this. If easy go ahead and do it.

**Comment by Rajat-Dabade** [comment]
@sbishel @wuwinson, I will take this as a priority today and will work on it.

**Comment by wuwinson** [comment]
> @wuwinson This is why I asked for all this information from Figma to be transferred to the spec. It is too easy to get lost in the Figma. @Rajat-Dabade - Please see what it will take to implement this. If easy go ahead and do it.

@sbishel This information was on the spec: https://docs.google.com/document/d/1VxIcDnI5jc68mQSNKSICv-0npkN8nGl2cnkWIMQUiEk/edit#bookmark=id.d37yj5dcrn3o
