### ISSUE TITLE
Bug: Card title overlap three dot menu.

### ISSUE THREAD

**Issue by madrix01** [mattermost/focalboard#3185]
## Steps to reproduce the behavior

1. Hover on a card with long title.

## Expected behavior

It should not overlap

## Screenshots
If applicable, add screenshots or a screen recording to elaborate on the problem.

![image](https://user-images.githubusercontent.com/51414879/172003104-80a2e663-d068-4081-97ca-44c22452e104.png)

**Comment by wuwinson** [comment]
@asaadmahmood Thoughts on this? Leaning more towards expected behavior.
