### ISSUE TITLE
Feature Idea: Localize built-in templates

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#319]
**Summary:**
The built-in board and card templates are stored in `templates.json` and initialized on the server side at first run. While they are technically data, we ultimately have to implement a way to localize them.

**How important this is to me and why:**

Importance: High

Use cases:
1. Install a new server, pick a non-English language, click + Add Board, notice that the template items are all in English

**Additional context / similar features:**
We'll need to come up with a way to localize the built-in templates, and plug into the existing localization / translation system.

**Comment by wuwinson** [comment]
Dupe of https://github.com/mattermost/focalboard/issues/4046
