### ISSUE TITLE
Bug: Boards template picker momentarily appears collapsed on load

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#3203]
## Steps to reproduce the behavior

1. Navigate to Boards (e.g. from the App Switcher), or refresh the template picker
2. The template picker momentarily appears as collapsed for a split second (longer on first load), and the buttons are cut off

## Expected behavior

The template picker preview has a minimum height, so that the buttons are visible

## Screenshots (optional)

(Screenshot taken while paused, so it appears dimmed):
<img width="1421" alt="Screen Shot 2022-06-09 at 11 35 28 AM" src="https://user-images.githubusercontent.com/46905241/172920434-95c7326a-4596-452a-9a37-c52afa7039f0.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.0.1
 - Browser and OS: Chrome on Mac

**Comment by chenilim** [comment]
Not sure if this is a dup or was fixed on main already.

**Comment by asaadmahmood** [comment]
@harshilsharma63 Can you confirm? I think we talked about this previously too. I can repro this on main local.
