### ISSUE TITLE
Bug: filtered out rows are visible on the first render of the table

### ISSUE THREAD

**Issue by kamre** [mattermost/focalboard#3211]
## Steps to reproduce the behavior

1. Use `Project Tasks` template to create new board
2. Switch to `Task Overview` table view
3. Add **new filter** (for example **include only** tasks which have `Status` value `In Progress`)
4. Switch between views in the sidebar (from `Task Overview` and back)
5. When switching back to the table view with filter there is a flicker because initial rendering shows all the rows and only later some rows are removed

## Expected behavior
No flickering and first rendering of the table view shows only rows according to the filter

## Screenshots (optional)
<img src="https://user-images.githubusercontent.com/5587620/173202917-6f8926e3-d918-41c0-80f0-45e4f382996c.gif" width=1122>

## Edition and Platform

 - Edition: Personal Desktop
 - Version: `main` branch
 - Browser and OS: Chrome on Mac

## Additional context (optional)
Can use CPU throttling in Crome Dev Tools to notice the flicker

* Sev 3: Affects minor, non-critical functionality

**Comment by wuwinson** [comment]
Thanks @kamre!
