### ISSUE TITLE
Bug: Update issue from 7.1 to 7.2 

### ISSUE THREAD

**Issue by beastarman74** [mattermost/focalboard#3214]
## Steps to reproduce the behavior

1. Update Focalboard Docker (mattermost/focalboard:edge) from 7.1 to 7.2. 
2. Restart the Container
3. Focalboard fails to start with the below critical error. 

## Expected behavior

Upgrades are successful from 0.16 to 7.0 and upwards and then from 7.1 to 7.2.0 (edge)
This issue has been occuring since moving from [https://github.com/mattermost/focalboard/releases/tag/v0.16.0]

## Screenshots (optional)

Error message:
```
2022/06/13` 12:59:48 {ServerRoot:https://localhost:8000 Port:8000 DBType:postgres DBConfigString:postgres://postgres:Password@192.168.1.XX:5432/focalboard?sslmode=disable&connect_timeout=15 DBTablePrefix: UseSSL:false SecureCookie:false WebPath:./pack FilesDriver:local FilesS3Config:{AccessKeyID: SecretAccessKey: Bucket: PathPrefix: Region: Endpoint: SSL:false SignV2:false SSE:false Trace:false} FilesPath:/data/files MaxFileSize:0 Telemetry:true TelemetryID: PrometheusAddress: WebhookUpdate:[] Secret: SessionExpireTime:2592000 SessionRefreshTime:18000 LocalOnly:false EnableLocalMode:true LocalModeSocketLocation:/var/tmp/focalboard_local.socket EnablePublicSharedBoards:false FeatureFlags:map[] EnableDataRetention:false DataRetentionDays:0 AuthMode:native LoggingCfgFile: LoggingCfgJSON: AuditCfgFile: AuditCfgJSON: NotifyFreqCardSeconds:0 NotifyFreqBoardSeconds:0}
info  [2022-06-13 12:59:48.238 +01:00] FocalBoard Server                        caller="main/main.go:57" version=7.2.0 edition=linux build_number=dev build_date=n/a build_hash=f3faf39eaaa76392c95e7499fe4801d04b920ab7
info  [2022-06-13 12:59:48.264 +01:00] connectDatabase                          caller="sqlstore/sqlstore.go:42" dbType=postgres
2022/06/13 12:59:48 ==  add_file_info: migrating  ======================================================================
error [2022-06-13 12:59:48.392 +01:00] Table creation / migration failed        caller="sqlstore/sqlstore.go:65" error="driver: postgres, message: failed to execute migration, command: executing_query, originalError: pq: relation "file_info" already exists, query: 

CREATE TABLE file_info (
    id varchar(26) NOT NULL,
    create_at BIGINT NOT NULL,
    delete_at BIGINT,
    name TEXT NOT NULL,
    extension VARCHAR(50) NOT NULL,
    size BIGINT NOT NULL,
    archived BOOLEAN
) ;

"
fatal [2022-06-13 12:59:48.394 +01:00] server.NewStore ERROR                    caller="main/main.go:146" error="driver: postgres, message: failed to execute migration, command: executing_query, originalError: pq: relation "file_info" already exists, query: 

CREATE TABLE file_info (
    id varchar(26) NOT NULL,
    create_at BIGINT NOT NULL,
    delete_at BIGINT,
    name TEXT NOT NULL,
    extension VARCHAR(50) NOT NULL,
    size BIGINT NOT NULL,
    archived BOOLEAN
) ;

"
  main.main
      /go/src/focalboard/server/main/main.go:146
  runtime.main
      /usr/local/go/src/runtime/proc.go:250
  runtime.goexit
      /usr/local/go/src/runtime/asm_amd64.s:1571
```

## Edition and Platform

 - Edition: Personal Desktop
 - Version: 7.1 upgrade to 7.2
 - Browser and OS: Chrome Dev on  Windows 11

## Additional context (optional)
Add any other context about the problem here, and any notes about the severity:

* Sev 2: Affects major functionality with a difficult or non-obvious workaround

I have experienced issues with upgrades from 0.1.6 to 7.0 and 7.0 to 7.1 cuasing failures to restart. As there was no other reports of issues on Github I assumed it was an issue with my own installation/configuation or board archive.  So did not have the confidence to report the issue here until I saw [https://github.com/mattermost/focalboard/issues/3210](url) and [https://github.com/mattermost/focalboard/issues/3208](url) both of which I have experienced with the last few updates. 
Rolling back to the previous version has not been successful with other critical errors being displayed for example :

```
2022/06/13 13:35:32 readConfigFile
2022/06/13 13:35:32 {ServerRoot:https://localhost:8000 Port:8000 DBType:postgres DBConfigString:postgres://postgres:Password@192.168.1.XX:5432/focalboard?sslmode=disable&connect_timeout=15 DBTablePrefix: UseSSL:false SecureCookie:false WebPath:./pack FilesDriver:local FilesS3Config:{AccessKeyID: SecretAccessKey: Bucket: PathPrefix: Region: Endpoint: SSL:false SignV2:false SSE:false Trace:false} FilesPath:/data/files Telemetry:true TelemetryID: PrometheusAddress: WebhookUpdate:[] Secret: SessionExpireTime:2592000 SessionRefreshTime:18000 LocalOnly:false EnableLocalMode:true LocalModeSocketLocation:/var/tmp/focalboard_local.socket EnablePublicSharedBoards:false FeatureFlags:map[] AuthMode:native LoggingCfgFile: LoggingCfgJSON: AuditCfgFile: AuditCfgJSON: NotifyFreqCardSeconds:0 NotifyFreqBoardSeconds:0}
info  [2022-06-13 13:35:32.099 +01:00] FocalBoard Server                        caller="main/main.go:56" version=7.0.1 edition=linux build_number=dev build_date=n/a build_hash=7b293e153f56cf77c463156813818400f37441ad
info  [2022-06-13 13:35:32.128 +01:00] connectDatabase                          caller="sqlstore/sqlstore.go:41" dbType=postgres
error [2022-06-13 13:35:32.186 +01:00] Table creation / migration failed        caller="sqlstore/sqlstore.go:55" error="pq: column "dirty" does not exist in line 0: SELECT version, dirty FROM "public"."schema_migrations" LIMIT 1"
fatal [2022-06-13 13:35:32.186 +01:00] server.NewStore ERROR                    caller="main/main.go:145" error="pq: column "dirty" does not exist in line 0: SELECT version, dirty FROM "public"."schema_migrations" LIMIT 1"
  main.main
      /go/src/focalboard/server/main/main.go:145
  runtime.main
      /usr/local/go/src/runtime/proc.go:225
  runtime.goexit
      /usr/local/go/src/runtime/asm_amd64.s:1371
```
I have been able to get back to a working system by dropping the the contents of the database, allowing a fresh setup of the database, create a new account and then import my board archive.  This didn't work for 7.0.0 (as per [https://github.com/mattermost/focalboard/issues/3208](url). Which is why I ended up running the Edge release as this allowed the import of the archive.

**Comment by wuwinson** [comment]
@beastarman74 Apologies for this. `v0.16 RC1` was an interim release that we ended up not shipping. For anyone on v0.15, please upgrade to [v7.0.1 (June release)](https://github.com/mattermost/focalboard/releases/tag/v7.0.1).

**Comment by beastarman74** [comment]
Hi, thanks for responding. I am not sure this addresses the most recent issue I had which was the upgrade from 7.1 to 7.2 on the Edge release.

I have had issues upgrading from 7.0.0 onwards including 7.0.1 to 7.1 and now 7.1 to 7.2.

**Comment by wuwinson** [comment]
@beastarman74 Can you clarify upgrading from 7.1 to 7.2? Our latest release is [v7.0.1](https://github.com/mattermost/focalboard/releases/tag/v7.0.1). We don't have any releases beyond that yet. Thanks!

**Comment by wuwinson** [comment]
Thanks for clarifying @beastarman74 and thanks for your input on #3188! Commented with more details on https://github.com/mattermost/focalboard/discussions/3225, so hopefully that clears things up!
