### ISSUE TITLE
Bug: Starting the stand-alone desktop app as per linux dev setup opens a blank window with console error

### ISSUE THREAD

**Issue by imasdekar** [mattermost/focalboard#3236]
## Steps to reproduce the behavior

1. Follow the [dev-setup guide](https://developers.mattermost.com/contribute/focalboard/personal-server-setup-guide/#building-and-running-standalone-desktop-apps) for Linux,
2. As the last step in the setup guide run `focalboard-app` from the directory you have chosen and a new window opens which is a blank window with the following error in the background
``` shell

http://localhost:45441/static/main.js?36f45b9dc1ad715cf84d:336:82523: CONSOLE ERROR TypeError: null is not an object (evaluating 'f.featureFlags.disableTour')
http://localhost:45441/static/main.js?36f45b9dc1ad715cf84d:432:574453: CONSOLE LOG [1655357887.66] WSClient webSocket opened.
http://localhost:45441/static/main.js?36f45b9dc1ad715cf84d:43:41673: CONSOLE JS ERROR Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'f.featureFlags.disableTour')
 
```

## Expected behavior

Running the standalone desktop app in Linux should launch the app with the welcome page.

## Screenshots (optional)
![Screenshot_20220616_110928](https://user-images.githubusercontent.com/29521808/174001657-a5c5dde7-96b5-4205-b5e0-767bdc7b2396.png)

If applicable, add screenshots or a screen recording to elaborate on the problem.

## Edition and Platform

 - Edition: Personal Desktop
 - Version: latest commit from the main branch
 - Browser and OS: ArcoLinux

**Comment by imasdekar** [comment]
@wiggin77 should this issue be closed as the merge request related to this is merged.

**Comment by wiggin77** [comment]
fixed via https://github.com/mattermost/focalboard/pull/3237

**Comment by wiggin77** [comment]
Thanks @imasdekar
