### ISSUE TITLE
Bug: Viewer and Commenter roles appearing on Share modal

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3243]
## Steps to reproduce the behavior

1. Go to a board and open the Share modal
2. Select role dropdown on any board member
3. See error - `Viewer` role is visible on the dropdown
4. Select dropdown on team role
5. See error - `Admin`, `Commenter`, and `Viewer` roles are visible on the dropdown

## Expected behavior

`Viewer` role should not be visible on the board member dropdown. `Admin`, `Commenter`, and `Viewer` roles should not appear on the team role dropdown. 

## Screenshots (optional)

**Board member role dropdown:**
![Screen Shot 2022-06-16 at 3 21 55 PM](https://user-images.githubusercontent.com/93531870/174149175-ee430a10-6014-4601-9976-971f0b27b3ce.png)

**Team role dropdown:**
![Screen Shot 2022-06-16 at 2 32 17 PM](https://user-images.githubusercontent.com/93531870/174149186-a3bfbd61-15e2-41d5-8e8e-cd36a3b65300.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2 (https://boards-seventwo2.test.mattermost.cloud/)
 - Browser and OS: Chrome on Mac

**Comment by jespino** [comment]
Fixed only in 7.2, this doesn't need to be merged into main, because 7.3 probably is going to have that roles exposed.

**Comment by wuwinson** [comment]
@jespino We still need to make sure `admin` does not appear on the team drop-down for v7.3+, should only be able to assign `admin` to explicit board members and not the entire team.

**Comment by jespino** [comment]
@wuwinson reopening to tackle this for 7.3
