### ISSUE TITLE
Bug: Boards plugin not working in 7.0

### ISSUE THREAD

**Issue by LimitlessDonald** [mattermost/focalboard#3247]
## Steps to reproduce the behavior

1. Use docker-compose provided in the documentation 
2. Upgrade the docker image from 6.6 to 7.0

## Expected behavior

Boards should work fine 

## Edition and Platform

 - Edition: Team Edition
 - Version: 7.0
 - Browser and OS: All browsers

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
All attempts to enable the boards plugin is not working 
I upgrade from 6.5 to 6.6 using the method described to reproduce this error without issues 
I also tried following some steps here https://github.com/mattermost/focalboard/issues/2119#issuecomment-1013751739

The plugin got activated but, in the logs, I see the error below. And I can't see any of my boards or cards, everything is empty 

`{"timestamp":"2022-06-17 22:09:05.133 Z","level":"debug","msg":"starting plugin","caller":"plugin/hclog_adapter.go:52","plugin_id":"focalboard","wrapped_extras":"pathplugins/focalboard/server/dist/plugin-linux-amd64args[plugins/focalboard/server/dist/plugin-linux-amd64]"}
{"timestamp":"2022-06-17 22:09:05.133 Z","level":"debug","msg":"plugin started","caller":"plugin/hclog_adapter.go:52","plugin_id":"focalboard","wrapped_extras":"pathplugins/focalboard/server/dist/plugin-linux-amd64pid823"}
{"timestamp":"2022-06-17 22:09:05.133 Z","level":"debug","msg":"waiting for RPC address","caller":"plugin/hclog_adapter.go:52","plugin_id":"focalboard","wrapped_extras":"pathplugins/focalboard/server/dist/plugin-linux-amd64"}
{"timestamp":"2022-06-17 22:09:05.156 Z","level":"debug","msg":"using plugin","caller":"plugin/hclog_adapter.go:52","plugin_id":"focalboard","wrapped_extras":"version1"}
{"timestamp":"2022-06-17 22:09:05.156 Z","level":"debug","msg":"plugin address","caller":"plugin/hclog_adapter.go:52","plugin_id":"focalboard","wrapped_extras":"address/tmp/plugin032124899networkunixtimestamp2022-06-17T22:09:05.156Z"}
{"timestamp":"2022-06-17 22:09:05.164 Z","level":"info","msg":"connectDatabase","caller":"app/plugin_api.go:937","plugin_id":"focalboard","dbType":"postgres"}
{"timestamp":"2022-06-17 22:09:05.182 Z","level":"debug","msg":"Acquiring cluster lock for Unique IDs migration","caller":"app/plugin_api.go:934","plugin_id":"focalboard"}
{"timestamp":"2022-06-17 22:09:05.186 Z","level":"debug","msg":"Releasing cluster lock for Unique IDs migration","caller":"app/plugin_api.go:934","plugin_id":"focalboard"}
{"timestamp":"2022-06-17 22:09:05.188 Z","level":"error","msg":"Table creation / migration failed","caller":"app/plugin_api.go:940","plugin_id":"focalboard","error":"\"Dirty database version 18. Fix and force version.\""}
{"timestamp":"2022-06-17 22:09:05.192 Z","level":"info","msg":"plugin process exited","caller":"plugin/hclog_adapter.go:61","plugin_id":"focalboard","wrapped_extras":"pathplugins/focalboard/server/dist/plugin-linux-amd64pid823"}
{"timestamp":"2022-06-17 22:09:05.192 Z","level":"debug","msg":"plugin exited","caller":"plugin/hclog_adapter.go:54","plugin_id":"focalboard"}
{"timestamp":"2022-06-17 22:09:05.192 Z","level":"error","msg":"Unable to activate plugin","caller":"app/plugin.go:139","plugin_id":"focalboard","error":"error initializing the DB: Dirty database version 18. Fix and force version."}
{"timestamp":"2022-06-17 22:09:05.211 Z","level":"debug","msg":"Received HTTP request","caller":"web/handlers.go:156","method":"POST","url":"/api/v4/plugins/focalboard/enable","request_id":"juh1sqfhyfy1urhpc9jedop5ye","status_code":"200"}
{"timestamp":"2022-06-17 22:09:26.586 Z","level":"debug","msg":"Not auto installing/upgrade because plugin was disabled","caller":"app/plugin.go:967","plugin_id":"focalboard","version":""}
{"timestamp":"2022-06-17 22:09:26.612 Z","level":"debug","msg":"Received HTTP request","caller":"web/handlers.go:156","method":"POST","url":"/api/v4/plugins/focalboard/disable","request_id":"8e3gbzy5mbrr9yxdk5ry39e57a","status_code":"200"}
{"timestamp":"2022-06-17 22:10:23.948 Z","level":"debug","msg":"starting plugin","caller":"plugin/hclog_adapter.go:52","plugin_id":"focalboard","wrapped_extras":"pathplugins/focalboard/server/dist/plugin-linux-amd64args[plugins/focalboard/server/dist/plugin-linux-amd64]"}
{"timestamp":"2022-06-17 22:10:23.948 Z","level":"debug","msg":"plugin started","caller":"plugin/hclog_adapter.go:52","plugin_id":"focalboard","wrapped_extras":"pathplugins/focalboard/server/dist/plugin-linux-amd64pid856"}
{"timestamp":"2022-06-17 22:10:23.948 Z","level":"debug","msg":"waiting for RPC address","caller":"plugin/hclog_adapter.go:52","plugin_id":"focalboard","wrapped_extras":"pathplugins/focalboard/server/dist/plugin-linux-amd64"}
{"timestamp":"2022-06-17 22:10:23.970 Z","level":"debug","msg":"plugin address","caller":"plugin/hclog_adapter.go:52","plugin_id":"focalboard","wrapped_extras":"address/tmp/plugin186521137networkunixtimestamp2022-06-17T22:10:23.970Z"}
{"timestamp":"2022-06-17 22:10:23.971 Z","level":"debug","msg":"using plugin","caller":"plugin/hclog_adapter.go:52","plugin_id":"focalboard","wrapped_extras":"version1"}
{"timestamp":"2022-06-17 22:10:23.980 Z","level":"info","msg":"connectDatabase","caller":"app/plugin_api.go:937","plugin_id":"focalboard","dbType":"postgres"}
{"timestamp":"2022-06-17 22:10:23.999 Z","level":"debug","msg":"Acquiring cluster lock for Unique IDs migration","caller":"app/plugin_api.go:934","plugin_id":"focalboard"}
{"timestamp":"2022-06-17 22:10:24.005 Z","level":"debug","msg":"Releasing cluster lock for Unique IDs migration","caller":"app/plugin_api.go:934","plugin_id":"focalboard"}
{"timestamp":"2022-06-17 22:10:24.012 Z","level":"debug","msg":"Mention listener added.","caller":"app/plugin_api.go:934","plugin_id":"focalboard","listener_count":"1"}
{"timestamp":"2022-06-17 22:10:24.013 Z","level":"info","msg":"Initialized notification backend","caller":"app/plugin_api.go:937","plugin_id":"focalboard","name":"notifyMentions"}
{"timestamp":"2022-06-17 22:10:24.014 Z","level":"debug","msg":"Starting subscriptions backend","caller":"app/plugin_api.go:934","plugin_id":"focalboard","freq_card":"120","freq_board":"86400"}
{"timestamp":"2022-06-17 22:10:24.015 Z","level":"info","msg":"Initialized notification backend","caller":"app/plugin_api.go:937","plugin_id":"focalboard","name":"notifySubscriptions"}
{"timestamp":"2022-06-17 22:10:24.015 Z","level":"info","msg":"Initialized notification backend","caller":"app/plugin_api.go:937","plugin_id":"focalboard","name":"notifyLogger"}
{"timestamp":"2022-06-17 22:10:24.016 Z","level":"error","msg":"isInitializationNeeded ERROR","caller":"app/plugin_api.go:940","plugin_id":"focalboard","error":"\"pq: column \"workspace_id\" does not exist\""}
{"timestamp":"2022-06-17 22:10:24.016 Z","level":"error","msg":"InitializeTemplates failed","caller":"app/plugin_api.go:940","plugin_id":"focalboard","error":"\"cannot initialize templates: pq: column \"workspace_id\" does not exist\""}
{"timestamp":"2022-06-17 22:10:24.017 Z","level":"debug","msg":"notify loop - no hints in queue","caller":"app/plugin_api.go:934","plugin_id":"focalboard","next_check":"\"2022-06-17 23:10:24.017 Z\""}
{"timestamp":"2022-06-17 22:10:24.017 Z","level":"debug","msg":"subscription notifier loop","caller":"app/plugin_api.go:934","plugin_id":"focalboard","next_notify":"\"2022-06-17 23:10:24.017 Z\""}
{"timestamp":"2022-06-17 22:10:24.018 Z","level":"info","msg":"Server.Start","caller":"app/plugin_api.go:937","plugin_id":"focalboard"}
{"timestamp":"2022-06-17 22:10:24.019 Z","level":"debug","msg":"server not bind to any port","caller":"app/plugin_api.go:934","plugin_id":"focalboard"}
{"timestamp":"2022-06-17 22:10:24.028 Z","level":"error","msg":"ERROR GetWorkspaceCount","caller":"app/plugin_api.go:940","plugin_id":"focalboard","error":"\"pq: relation \"focalboard_workspaces\" does not exist\""}
{"timestamp":"2022-06-17 22:10:24.029 Z","level":"error","msg":"Error fetching telemetry data","caller":"app/plugin_api.go:940","plugin_id":"focalboard","name":"workspaces","error":"\"pq: relation \"focalboard_workspaces\" does not exist\""}
{"timestamp":"2022-06-17 22:10:24.061 Z","level":"debug","msg":"Received HTTP request","caller":"web/handlers.go:156","method":"POST","url":"/api/v4/plugins/focalboard/enable","request_id":"e1fiziugiidmxrrynr81bd1pze","status_code":"200"}`

**Comment by harshilsharma63** [comment]
@LimitlessDonald looks like DB migration failed to complete. Can you find the original error in mattermost server logs? The first time you tried installing the new version is when you'd have the original error in logs.

Apologies for the late response.
