### ISSUE TITLE
Bug: Text of sidebar menu partially hidden

### ISSUE THREAD

**Issue by kaakaa** [mattermost/focalboard#3276]
## Steps to reproduce the behavior

1. Set language to 日本語 (Japanese)
2. Open a context menu of a board in sidebar

## Expected behavior

All text and icons in the sidebar menu are visible.

## Screenshots (optional)

Text in sidebar menu is partially hidden.

<img width="267" alt="スクリーンショット 2022-06-24 15 00 54" src="https://user-images.githubusercontent.com/1453749/175472749-67cd347d-9433-4c91-b71c-591cf0738fa2.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: ? (On community server)
 - Browser and OS: Chrome

## Additional context (optional)

With some other language, this issue is happened.

* Español
<img width="322" alt="スクリーンショット 2022-06-24 15 00 18" src="https://user-images.githubusercontent.com/1453749/175473270-54a27720-c406-4ab7-a717-8a5c8b2ccd13.png">

* French
<img width="287" alt="スクリーンショット 2022-06-24 15 08 19" src="https://user-images.githubusercontent.com/1453749/175473385-fb9e57b3-1b00-4b6e-8bfd-4f13e32ff2a4.png">

**Comment by sbishel** [comment]
Should not be clipped by the parent (sidebar) nor go off the screen. Menus should hover over the sidebar and alway be visible.
