### ISSUE TITLE
Bug: Focalboard App displays blank page

### ISSUE THREAD

**Issue by 59degreesnorth** [mattermost/focalboard#3277]
Opening focalboard gives a blank application interface only (only a white background, nothing else).
This began after the most recent update (0.15.1).

The expected behaviour is to load the focalboard home screen.

<img width="897" alt="Screenshot 2022-06-27 at 11 56 34" src="https://user-images.githubusercontent.com/61550559/175926229-a60994cb-9a5b-4e7b-a431-df604df479db.png">

 - Edition: Personal Desktop
 - Version: [e.g. v0.15.1 (32)]
 - macOS Monterey v12.4

Clearly the app is unusable for me in the current form.

**Comment by chenilim** [comment]
Hi @59degreesnorth, thanks for reporting this. It appears that Focalboard crashed during the render. Could you try the following:

First try quitting and re-opening the app. Then try selecting Home from the File Menu (which will refresh the window).

Failing that, try to backup then reinstall the app:

1. Open Finder to `~/Library/Containers/com.mattermost.focalboard/Data/Library/Application Support/Focalboard/server`
2. Backup `focalboard.db` to another folder. This contains all your data.
3. Delete the `~/Library/Containers/com.mattermost.focalboard/Data/Library/Application Support/Focalboard` folder
4. Uninstall Focalboard: Open LaunchPad (Cmd+Space, "Launchpad"), click and hold on "Focalboard", then click X
5. Reinstall Focalboard from the [App Store](https://apps.apple.com/us/app/focalboard/id1556908618?mt=12).

Does the interface render now?

Copy `focalboard.db` back to `~/Library/Containers/com.mattermost.focalboard/Data/Library/Application Support/Focalboard/server`, and re-launch Focalboard. Does that work?

**Comment by 59degreesnorth** [comment]
Hi @chenilim, thanks for the support.
I have followed all the instructions above.
Neither quitting and restarting the app, restarting the device multiple times, nor selecting home from the File Menu had any effect.
I have followed all the instructions to backup and reinstall the app, however this also did not work. I am still presented with a blank page only.
Do you have any further suggestions? How can I send an error report to you?
Just to highlight, Focalboard _was_ working on my device until a few days ago, and the only change that I can see was the most recent update to Focalboard.

**Comment by chenilim** [comment]
Thanks @59degreesnorth. I've investigated further and determined this was a build issue - I built this on an M1 Mac, which generated the server binary for arm64 (Apple Silicon), causing it to fail on x86. To confirm, you were running this on an x86 Mac right?

A fix has been submitted to the App Store, and this will be resolved in v0.15.2. Sorry for the inconvenience!

**Comment by 59degreesnorth** [comment]
Thanks @chenilim, yes I am using a mid-2019 MacBook Pro with a 2.6 GHz 6 core Intel i7. Fingers crossed the update resolves the issue!

**Comment by chenilim** [comment]
Hi @59degreesnorth, Focalboard 0.15.2 is now available in the App Store, please [download it here](https://apps.apple.com/us/app/focalboard/id1556908618?mt=12), and LMK if you are still seeing issues. Thanks!

**Comment by 59degreesnorth** [comment]
@chenilim This has resolved this issue! Thanks!
