### ISSUE TITLE
Bug: Build issue

### ISSUE THREAD

**Issue by prakharporwal** [mattermost/focalboard#3288]
## Steps to reproduce the behavior

1. Go to webapp folder in the repo 
3. run `make prebuild`
4. run `make`
5. See error

## Expected behavior

website of focalboard should start on localhost
## Screenshots (optional)
![image](https://user-images.githubusercontent.com/49529937/176516956-c16de01c-b38b-41cd-afa5-e14a3cb86be3.png)

![image](https://user-images.githubusercontent.com/49529937/176516842-a37e2f8c-381a-4370-9aca-93da50570708.png)

Above error show up . I think they are related to webpack config.

## Edition and Platform
- GNU Make 4.2.1 Built for x86_64-pc-linux-gnu
 - Browser Ubuntu 20.04

**Comment by prakharporwal** [comment]
@wuwinson  I have submitted the steps above. Its weird if it is happening in my machine only.

**Comment by chenilim** [comment]
@prakharporwal, note that `make prebuild` needs to be run from the root folder, not `webapp`. Does that help?

**Comment by wuwinson** [comment]
Closing out. Please feel free to re-open if you're still having issues. Thanks!

**Comment by prakharporwal** [comment]
![image](https://user-images.githubusercontent.com/49529937/181197807-6188d650-53c6-4616-8a56-04ebf93252f2.png)
Fails to login to github to get eslint-plugin.git

**Comment by prakharporwal** [comment]
@wuwinson

**Comment by chenilim** [comment]
@prakharporwal please try cloning the repo via https (https://github.com/mattermost/focalboard.git), or double check your ssh credentials. Thanks.

**Comment by wuwinson** [comment]
@prakharporwal Closing out. Please feel free to re-open if you're still having issues. Thanks!
