### ISSUE TITLE
Bug: Users are not removed from person property type after getting removed from the board

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/focalboard#3293]
## Steps to reproduce the behavior

1. Create a board
2. Add a user to the board
3. On a person property, check that the added user appears as an option 
4. Remove the user membership from the board
5. Check that on the person property, the user still appears as an option
6. Refresh and check again. The user will not appear this time

## Expected behavior

The options on the selector should be consistent with the current state of the board.

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2
 - Browser and OS: Firefox 101.0.1 on Linux

**Comment by wuwinson** [comment]
cc @asaadmahmood Thoughts on expected behaviour?
