### ISSUE TITLE
Bug: New membership not reflected live

### ISSUE THREAD

**Issue by jespino** [mattermost/focalboard#3294]
When I add a user I expect that to be reflected in the interface on the fly, but I need to switch board to get the new board.

## Steps to reproduce the behavior

1. Create one board
2. With other user, open Boards
3. Add this other user to the board
4. The board is not shown in the added user interface.

## Expected behavior

The sidebar of the new added user should show the board on the fly.

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.2
 - Browser and OS: Firefox/Linux

**Comment by harshilsharma63** [comment]
Working on this now.
