### ISSUE TITLE
Bug: Duplicating a card with an image won't show the image until after changing views / refreshing

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/focalboard#3298]
## Steps to reproduce the behavior

1. On a board with a gallery view, create a card with an image
2. Duplicate the card
3. The image will not be shown
4. Refresh or change to another view and back
5. The image will be shown

## Expected behavior

The image should be shown right after the duplication.

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2
 - Browser and OS: Firefox 101.0.1 on Linux

**Comment by sbishel** [comment]
Retested on Community (v7.2.1) and it does not reproduce. Closing, reopen if you see it again.
