### ISSUE TITLE
Bug: After deleting the category, the deleted category is not removed from the board.

### ISSUE THREAD

**Issue by Rajat-Dabade** [mattermost/focalboard#3299]
## Steps to reproduce the behaviour

1. Create a new Category on the boards
2. Delete the category 
3. Category still remain on the page

## Expected behaviour

After deleting the category, the deleted category should be removed from the board

## Screenshot

https://user-images.githubusercontent.com/26198062/176632172-237c0a0d-ef5f-48cc-9df1-565c96a5200d.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2.0
 - Browser and OS: Chrome on Mac

**Comment by chenilim** [comment]
@Rajat-Dabade, please retest on this week's bugbash server. It did not repro on Scott's local setup. Thanks.

**Comment by sbishel** [comment]
Retested on community...appears to be fixed, closing
