### ISSUE TITLE
Internationalize hardcoded strings

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#33]
There are hardcoded strings sprinkled throughout the app. These should be replaced with intl.FormatMessage calls to pull them from the translation tables.

* Easiest way to find hardcoded strings is to change the UI language to Spanish from the Settings menu, then look for strings that haven't changed.
* Remember to run `cd webapp; npm run i18n-extract` to extract newly added translations to the language tables.

**Comment by BharatKalluri** [comment]
I'll be picking this up since no one is currently assigned to this issue 😃 

I've made a PR fixing a bunch of hardcoded strings over at https://github.com/mattermost/focalboard/pull/221

**Comment by mickmister** [comment]
Should this be closed, or is this something that needs further work?

**Comment by chenilim** [comment]
Thanks for checking @mickmister! Yes, this does require further work. There are still hardcoded strings sprinkled throughout. One example is the Undo messages:
* Switch to another language (e.g. Chinese) to make this easier to see
* E.g. drag a card and then press Cmd+Z
* The flash message says "Undo drag card"

These strings are in `mutator.ts` and the callers to it (I know because I created most of these bugs :)). This particular class of bugs requires some refactoring of how the undo action strings are passed in.

Another example are the names of the built-in template boards and cards. I just filed #319 to track that.

If anyone finds particular strings that need to be localized, please feel free to file additional bugs. Thanks!
