### ISSUE TITLE
Bug: Channels -> Boards Navigation Review

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#3305]
## Steps to reproduce the behavior

Not a bug, necessarily, but want to make sure it's right. 

From the Global Nav, you should be taken to last viewed board for that team.
From either the App Bar or the Channel Intro. You are taken to the "Create Board".

## Expected behavior
Unsure, which is why I want to discuss.

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: main
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment]
This will change once we merge the Boards-Channels Associations feature.
