### ISSUE TITLE
Bug: Unable to see icons on gentoo

### ISSUE THREAD

**Issue by priv4cy** [mattermost/focalboard#3312]
I didn't see any icon when firstly launch focalboard on gentoo but when I install font awesome, some icon was be seen.

## Edition and Platform

 - Edition: Personal Desktop 
 - Version: 7.0.0.1
 - Appimage
 - gentoo

Gentoo need icon dependencies i think but in spite of I search the all internet about that but didn't find any information.
- If i wrong with grammer sorry for that.

**Comment by priv4cy** [comment]
I don't think there's a need to be familiar with Gentoo because I've learned that Gentoo doesn't have special dependencies. If you tell me what you use for icon dependencies on Linux. I can try to figure it out.

 If you are using Microsoft or any close source dependency, I can't use it (I think this is not possible with the open source application?) and we also need to find your dependencies in the portage repository. (Gentoo can handle this with the source code, but I'm not an expert on Gentoo.)

**Comment by priv4cy** [comment]
@wuwinson I am newbie on github and i wrongly closed issue. I am tryed font awesome and some blade, sword black icons seened but other colorful icon did not seen.

**Comment by wuwinson** [comment]
No worries @priv4cy! Reopening this ticket.

**Comment by octoman90** [comment]
I think are looking for the `media-fonts/noto-emoji` package.

**Comment by priv4cy** [comment]
> I think you are looking for the `media-fonts/noto-emoji` package.

I saw the same error in arch linux and installing noto-emoji solved my problem. I think Gentoo could be the same.
