### ISSUE TITLE
Bug: Cypress test failing for main.

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#3318]
`webapp/cypress/integration/cardURLProperty.ts` is failing consistently in CI.  PR https://github.com/mattermost/focalboard/pull/3316 has temporarily disabled the problematic part of the test.  The test should be fixed and re-enabled.

**Comment by kamre** [comment]
Hi @wiggin77 , after disabling problematic part this Cypress test [still can fail](https://github.com/kamre/focalboard/runs/7228283687?check_suite_focus=true)

So may be disabling the whole test will be required temporarily.

It looks like there is some additional redundant rerendering when new view is added to the board:
- Cypress finds the element on the first rendering of the new view
- location is changed for the new view
- rerendering happens with remounting of the found element
- so Cypress has a detached element that can't be used for user actions

The question is why the new view of the board is rendered twice, this looks like a bug to me. It should not render before the location is changed and router renders the new view.

**Comment by kamre** [comment]
@harshilsharma63 its great to hear that this is a high priority issue.

Tests are ok in my understanding and the webapp itself should be fixed avoiding redundant rerenderings with remounting react components. So that if Cypress has found the component it will not be detached immediately.
