### ISSUE TITLE
Bug: menu -> view -> tabbar should be disabled

### ISSUE THREAD

**Issue by Willyfrog** [mattermost/focalboard#332]
**Summary:**
clicking on menu -> view -> tabbar shows a single tabbar below the title which looks weird. if tabs are not supported it should be disabled

**Steps to reproduce the behavior:**

1. clicking on menu -> view -> tabbar 

**Expected behavior:**
either the menu is not visible or there should be some sort of help on how to use tabs

**Screenshots:**
<img width="996" alt="Screen Shot 2021-04-26 at 01 16 57" src="https://user-images.githubusercontent.com/1515906/116012802-1a4e2480-a62d-11eb-921d-01d83eb17eb4.png">

**Platform:**
 - OS and version: macOS Big Sur, built from master

**Comment by chenilim** [comment]
In general, the menu items in macOS needs to be cleaned up. Individually, these are fairly easy fixes in the storyboard. Opening it up if someone wants to grab it before I can get to it. :)

**Comment by chenilim** [comment]
@haardikdharma10, to clarify, we should remove that first section of the view menu from the storyboard:
* Show Tab Bar
* Show All Tabs
* The divider

<img width="493" alt="Focalboard mac menu" src="https://user-images.githubusercontent.com/46905241/116725324-a302f280-a996-11eb-838a-1b979432d838.png">
