### ISSUE TITLE
Bug: When typing in Korean, the input cursor moves to the front in about 5-10 seconds.

### ISSUE THREAD

**Issue by mjxaone** [mattermost/focalboard#3342]
## Expected behavior

When typing in Korean, the input cursor moves to the front in about 5-10 seconds.

## Screenshots (optional)

Video
https://user-images.githubusercontent.com/7800723/178091006-90601410-7086-41e6-a9b3-b22112ee85dc.mp4

## Edition and Platform

 - Edition: Personal Server 
 - Version: v7.0.1
 - Browser and OS: Ubuntu 20.08(Server) / Chrome(Browser)

## Additional context (optional)
* Sev 1: Affects critical functionality without a workaround

## ps.
This issue disables the "Comment" function.
Please have mercy on Korean speakers too.
thank you

**Comment by wuwinson** [comment]
@ogi-m Can you repro and test other input fields as well? ie. Card description, property fields, search box, etc. Thanks! cc @chenilim

**Comment by mjxaone** [comment]
ok.
Other input fields are fine.
The problem only occurs when entering comment.

**Comment by wuwinson** [comment]
@ogi-m Any updates on this? Thanks!

**Comment by chenilim** [comment]
Ping @ogi-m.

**Comment by ogi-m** [comment]
@wuwinson @chenilim I was able to reproduce this as decrbed on plugin v7.2. It only happens in the comments section when hitting the spacebar while typing.

**Comment by harshilsharma63** [comment]
@mjxaone can you tell me your Focalboard plugin version? And can you also confirm that this occurs only in the new comment section and everywhere else (Card title, description) work fine? If yes, it's most likely fixed by #4039 and the fix would be in 7.5.

**Comment by sbishel** [comment]
Fixed by https://github.com/mattermost/focalboard/pull/4039
