### ISSUE TITLE
Bug: Link/unlinking boards does not appear on RHS until browser refresh

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3351]
## Steps to reproduce the behavior

1. Go to Boards apps bar in Channels
2. Select some boards to link and unlink
3. Confirm the boards to link
4. Close the "Link boards" modal
5. See error - the RHS does not automatically update with the linked/unlinked boards.

## Expected behavior
The RHS should automatically update with the linked/unlinked boards without needing to refresh the browser.

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/178305321-67847848-71d0-4535-b1d0-25afe3ebe151.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2 (bug bash)
 - Browser and OS: Chrome on Mac

**Comment by mgdelacroix** [comment]
This requires the websocket lifecycle refactor to work: https://github.com/mattermost/focalboard/pull/3315

**Comment by chenilim** [comment]
Does this require any additional chances @mgdelacroix?

**Comment by sbishel** [comment]
Tested on bug-bash, no longer an issue...closing
