### ISSUE TITLE
Feature Idea: Filter selection menu should not close on select

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#3361]
## Summary

If you want to set a filter to multiple values, you need to re-open the filter value menu each time. E.g. see video:

https://user-images.githubusercontent.com/46905241/178857962-4cd36d80-b07a-47aa-90ef-9bd8fe46b418.mov

Instead, the menu should not close until dismissed (e.g. clicked outside). This may apply elsewhere as well.

## How important this is to me and why

Importance: Medium

Use cases:
1. Filtering for multiple values

**Comment by sbishel** [comment]
closing as fixed
