### ISSUE TITLE
Bug: Boards RHS doesn't handle text for DM and GM

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#3365]
## Steps to reproduce the behavior

1. Open a DM or a GM.
2. Open boards RHS. Notice the text in there and on the button. It includes channel name when in a channel but says nothing in DM and GM

## Screenshots (optional)

<img width="523" alt="Screenshot 2022-07-14 at 1 46 13 PM" src="https://user-images.githubusercontent.com/18575143/178935660-a1d860da-fc27-4fa3-8b56-d7c5a92303cb.png">

**Comment by wuwinson** [comment]
@asaadmahmood @justinegeffen Thoughts on using a generic label for DMs and GMs such as "Link boards to this channel"?

**Comment by harshilsharma63** [comment]
FIxed by #3368

**Comment by harshilsharma63** [comment]
@wuwinson @justinegeffen its already fixed now. This is how it looks-


<img width="466" alt="Screenshot 2022-07-19 at 11 08 52 AM" src="https://user-images.githubusercontent.com/18575143/179673400-80b353ac-fcb8-4ce9-88f8-8f4666aec924.png">

<img width="475" alt="Screenshot 2022-07-19 at 11 09 05 AM" src="https://user-images.githubusercontent.com/18575143/179673436-4e3b99e1-0e92-46fd-af01-f0cd8d064104.png">

**Comment by justinegeffen** [comment]
Thanks, @harshilsharma63! Would it be possible for me to refine that copy in a new PR?
