### ISSUE TITLE
Bug: Cannot add explicit board members when a channel is linked to a board

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3369]
## Steps to reproduce the behavior

1. Go to a board thats linked to a channel
2. Open Share modal
3. Add a team member to the board
4. See error - user is not added
5. Remove channel as a member of the board
6. Add the same team member from Step 3 - member can now be added

## Expected behavior

Users can be added to a board regardless if a channel is linked to the board or not.

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/179058094-dc834cfa-e106-480b-9c51-c4ad94e5bf48.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2 Bug Bash
 - Browser and OS: Chrome on Mac

**Comment by harshilsharma63** [comment]
I'm taking a look at this.

**Comment by harshilsharma63** [comment]
This happens when the user you're trying to add already exists in one of the channels the board is linked to.

**Comment by wuwinson** [comment]
Thanks @harshilsharma63! We should allow adding explicit board members even if they're already a member of a channel based on @mgdelacroix's [hybrid approach](https://docs.google.com/document/d/1gV3EsDIieyK9KmyAjQqZ0AVG_KG_XE-1OrN3G5daZ3o/edit#bookmark=id.2awt1oyd0t9l). I updated @jespino's [Boards-Channels Associations spec](https://docs.google.com/document/d/1DFteQ7qb3xYY5c4cS1N1LppDffDaJX-MCJZwcMfUSF4/edit?usp=sharing) with a [narrowed down v7.2 version of the matrix](https://docs.google.com/document/d/1DFteQ7qb3xYY5c4cS1N1LppDffDaJX-MCJZwcMfUSF4/edit#bookmark=kix.g33gglonpo62).

**Comment by harshilsharma63** [comment]
Picking this one now.
