### ISSUE TITLE
Bug: "Link boards to channel" button does not have enough padding for long channel names

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3370]
## Steps to reproduce the behavior

1. Create a new channel with a longer name
2. Click on the Boards Apps Bar button
3. See error

## Expected behavior

The button should have proper padding around it.

## Screenshots (optional)

![Screen Shot 2022-07-14 at 2 41 37 PM](https://user-images.githubusercontent.com/93531870/179059227-f43a5fea-4ee5-4c14-8ac9-99ab0de6cd55.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2 Bug Bash
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment]
cc @asaadmahmood for input.

**Comment by asaadmahmood** [comment]
@wuwinson Already covered in
