### ISSUE TITLE
Bug: Able to link a board / channels across teams

### ISSUE THREAD

**Issue by Pinjasaur** [mattermost/focalboard#3371]
## Steps to reproduce the behavior

1. Go to a channel in Team A
2. Select the Boards RHS button & open the "Link a board" modal
3. Search for a board in Team B and notice it shows up
4. Link the board

## Expected behavior

I would expect that linking of boards & channels is restricted to the same team/workspace.

## Screenshots (optional)

If applicable, add screenshots or a screen recording to elaborate on the problem.

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.2 bug bash
 - Browser and OS: FF103 Mac

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by jespino** [comment]
I'm not able to reproduce it, probably is already fixed by other changes. @Pinjasaur we can re-test this in the next bug squashing.

**Comment by wuwinson** [comment]
@Pinjasaur Can you try retesting this off the tip of `release-7.2`? Thanks! cc @sbishel

**Comment by Pinjasaur** [comment]
Tested locally with `release-7.2` and it appears to be resolved by a PR since I reported it. Closing. 👍🏻
