### ISSUE TITLE
Bug: Linked boards right-hand sidebar doesn't scroll

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#3372]
## Steps to reproduce the behavior

1. Go to a channel
2. Click FocalBoard target button (right hand side) to open `Linked boards` sidebar
3. Link more boards than will fit vertically in the sidebar
4. Observe there are no scrollbars or ability to scroll to clipped boards.

## Expected behavior

Scrollbars appear when sidebar overflows

## Screenshots (optional)

If applicable, add screenshots or a screen recording to elaborate on the problem.

## Edition and Platform

 - Edition: Plugin
 - Version: v7.2 
 - Browser and OS: FF 102.0.1 Linux

**Comment by Pinjasaur** [comment]
Closing, appears to have been fixed in #3368.

<img width="450" alt="image" src="https://user-images.githubusercontent.com/6335792/180070604-e4d1271a-5598-4d7a-af1e-f170db2abc65.png">
