### ISSUE TITLE
Feature Idea: Add calendar view

### ISSUE THREAD

**Issue by mblennegard** [mattermost/focalboard#338]
**Summary:**
Add calendar view.

**How important this is to me and why:**
Medium

**Use cases:**
To visualize tasks/items in a time focused way.

**Additional context / similar features:**
This feature would require having **date** as a field type, as requested by issue #257.

**Comment by chenilim** [comment]
Thanks @mblennegard! This is something we want to add. Opening it up to you and/or others to add any other thoughts, preferences, or ideas. To kick things off, the basic calendar I can visualize will show:
* You pick the date property to display, and cards are shown in a daily calendar view
* P2: Pick an optional **end date** property (or pick a **date range** property) to show the span

Are there any other particular features anyone finds indispensable in a calendar view?

**Comment by mblennegard** [comment]
Just adding this thought as well.
I think you should be able to display any property on the cards in the calendar view, similar to how the board view works already.
With any property on the cards you could at a glance have a different color to each card depending on select properties.

To expand on the above and make color coding even more useful, it would be nice to being able to define so that the entire card background gets the color of a specified select property.

**Comment by justasojourner** [comment]
_Thanks for building this tool, it’s looking promising!_

Re: the calendar specifically, and the system generally, can you please keep internationalisation in mind. For example, for the majority of countries, Monday, not Sunday, is the first day of the week.

Also date display formatting is not just a matter of order (and again most countries use dd + mm + yy) but separators — ` ‘/‘, ‘.’, ‘-‘ `.

Date formatting can be set on system level (but that causes issues for multinational users), manually by user logon, or by taking from OS international settings (perhaps the safest).

**Comment by chenilim** [comment]
Closing this issue now that Calendar View has shipped in v0.11. 🎉
Please file additional issues or enhancement requests for any additions you'd like to see. Thanks.

**Comment by loviuz** [comment]
Calendar View is great! I suggest to add also a "Dayly" view in addition to Weekly and Monthly.
