### ISSUE TITLE
Bug: Unlinking a channel from Board's share modal doesn't ask for confirmation

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#3391]
## Steps to reproduce the behavior

1. Create a board.
2. Link it to a channel.
3. Open the board's share modal.
4. Unlink the channel from the modal. Notice there was no confirmation for this action.

## Expected behavior

A confirmation should be asked before unlinking the board.

## Screenshots

https://user-images.githubusercontent.com/18575143/179970866-354936a6-f1d0-42d7-90a8-ccfd14ac1ee7.mp4

**Comment by wuwinson** [comment]
@asaadmahmood Thoughts on this? Thanks!

**Comment by asaadmahmood** [comment]
@wuwinson I feel like we should show a message like this.
![test](https://user-images.githubusercontent.com/11034289/180858715-ec86dcea-d76b-49ab-adb9-b30de9fa014c.jpg)

**Comment by wuwinson** [comment]
Thanks @asaadmahmood!
