### ISSUE TITLE
Bug: Unable to invite users on Personal Server (w/ SQLite)

### ISSUE THREAD

**Issue by Pinjasaur** [mattermost/focalboard#3394]
## Steps to reproduce the behavior

1. Go to your Personal Server e.g. http://localhost:8000/ 
2. Open the "invite users" dialog from the top left
3. Copy the invite URL and create a new user from it
4. Notice the users are not on the same team i.e. boards are not shared

## Expected behavior

Would expect users to be able to invite each other & create a team on Personal Server.

## Edition and Platform

 - Edition: Personal Server w/ SQLite
 - Version: `main` (2022-07-20)
 - Browser and OS: FF103 Mac

**Comment by Pinjasaur** [comment]
Again, note that this is locally w/ SQLite—have not tested with a different db.

**Comment by wuwinson** [comment]
Just to clarify - Personal Server should only have 1 team. Only Plugin supports multiple teams.

**Comment by sbishel** [comment]
@Pinjasaur - Can you update with some debug information? What errors are you seeing in server, webapp? You shouldn't really even see "teams" on personal server. Although the underlying code should be using a default team. Similar to how personal server previously had a default workspace.

**Comment by Pinjasaur** [comment]
steps:

1. check out `release-7.2`
2. `make prebuild && make`
3. `rm focalboard.db`
4. `make watch`
5. create an account
6. boards & categories do not appear to be shared i.e. users don't behave like they're on the same (default) team

I'm not seeing any blatant errors in the devtools or server logs—I'll dig into the db and see if there's anything that looks off

note: the (default) team is an empty string

<img width="723" alt="image" src="https://user-images.githubusercontent.com/6335792/180884041-9c3a2578-3f81-4681-82c7-704758a1a380.png">

**Comment by Pinjasaur** [comment]
did testing with `release-7.1` and it worked as expected. migrated the 7.1 db to 7.2 and manually diffed a 7.2-created board and noticed the new board type is set to `P` instead of `O`

when trying to use the Share modal to add my 2nd user to the board, the webapp errors:

<img width="491" alt="image" src="https://user-images.githubusercontent.com/6335792/181126275-b652004e-5bac-4af6-90e4-74509abfe0d7.png">

**Comment by Pinjasaur** [comment]
the above error is #3389

**Comment by Pinjasaur** [comment]
need to investigate how the migration is handling board types & determine what the correct behavior is, particularly for Personal Server

**Comment by Pinjasaur** [comment]
correct behavior is default to `P` == `private`, there is currently no way to create a board that is public upon creation—the share modal would be needed to be used post-creation

**Comment by Pinjasaur** [comment]
determined it's all functioning as expected: https://community.mattermost.com/core/pl/rqctbdmzo7ffjx1ggmapa13zuc

closing out, making copy changes in #3464
