### ISSUE TITLE
Bug: templates cannot be removed

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/focalboard#3399]
## Steps to reproduce the behavior

1. Create a template
2. Try to delete it

## Expected behavior

There is a way to delete a template.

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2

## Additional context (optional)

The only way to delete a board / template now is through the LHS and we don't show templates there

**Comment by Pinjasaur** [comment]
@mgdelacroix I might be misunderstanding, but can't you still delete from the "Create a board" page? 


![image](https://user-images.githubusercontent.com/6335792/180286924-d072e598-dbb2-437c-9dd2-46f37a487e41.png)

**Comment by wuwinson** [comment]
@mgdelacroix I was able to delete the template via @Pinjasaur's screenshot. Can you confirm if this is still an issue. Closing out for now. Please re-open if still an issue. Thanks!

**Comment by mgdelacroix** [comment]
Thanks @Pinjasaur and @wuwinson, looks like it was a permissions issue for me
