### ISSUE TITLE
Bug: templates with empty name are show as empty on the template list

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/focalboard#3400]
![image](https://user-images.githubusercontent.com/223323/180216373-ba255238-ec27-433f-b601-3f2671197db5.png)

## Expected behavior

Empty templates should shown some text like `Untitled`

**Comment by wuwinson** [comment]
@mgdelacroix Are the empty templates at least starting out with "Untitled Template"? If not, we should make sure that they still get populated.

@asaadmahmood Can we do a warning here if the user deletes the default template name and leaves it blank? Thoughts?

**Comment by asaadmahmood** [comment]
@wuwinson @mgdelacroix Is right, it should just say `Untitled` if the user leaves it empty.

**Comment by wuwinson** [comment]
Sounds good, thanks @asaadmahmood!
