### ISSUE TITLE
Feature Idea: Healthcheck w/ build metadata

### ISSUE THREAD

**Issue by Pinjasaur** [mattermost/focalboard#3410]
## Summary

We currently have `/hello` which acts as a basic HTTP 200 healthcheck. Would like to create a new endpoint similar to `mattermost-server`s `/api/v4/system/ping` that adds additional build metadata e.g. commit hash, version, etc.

For acceptance criteria:

- Create a new HTTP GET endpoint e.g. `ping`
- Response with a JSON body containing metadata keys and values e.g.

	```json
	{
		"version": "7.2",
		"commit": "abcd123",
		"build_number": "dev",
		"build_date": "n/a",
		"db_type": "sqlite",
		"db_version": "SQLite 3.37.0",
		"os_type": "darwin",
		"os_arch": "arm64",
		"sku": "personal_desktop"
	}
	```

- The values would be populated from environment variables e.g. Makefile, GitHub Actions CI and data from the Golang binary
	- `version` from hardcoded values
	- `commit` derived from `BUILD_HASH`
	- `build_date` and `build_number` derived from `BUILD_DATE` and `BUILD_NUMBER` environment variables
	- `os_type` & `os_arch` perhaps from `OSTYPE` or `uname` command
	- `db_type` & `db_version` from config.json & database driver, respectively
	- `sku` by checking `FOCALBOARDSERVER_ARGS=--single-user`
- Add simple test(s) to verify endpoint

## How important this is to me and why

Importance: Medium

Use cases:
1. more robust debugging & observability when deploying releases 

## Additional context/similar features

`mattermost-server`s `ping` endpoint: https://api.mattermost.com/#tag/system/operation/GetPing

**Comment by wuwinson** [comment]
@Pinjasaur Do you have any proposals for this? Thanks! cc @sbishel

**Comment by Pinjasaur** [comment]
For anyone interested in working on this (for Hacktoberfest or not) we're happy to take a more iterative approach i.e. start with the more core metadata (version, commit, build info) and add more later.

**Comment by wuwinson** [comment]
Thanks @mastersb! I've assigned this ticket to you.
