### ISSUE TITLE
Bug: Card Property is not deleted after confirming delete and seeing the "Success" message

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#3424]
QA community contributors have been taking part in a weekly bug bash on `https://boards-bugbash.test.mattermost.cloud/`. One of the contributors (`@krmh04`) found that deleting a property on a card does not delete the property, even after "success" message is shown.

## Steps to reproduce the behavior

1. Add a property to a card
2. Delete the property (i.e. click Delete in the Confirm Property Delete modal)
3. Observed:  Success message is displayed but property remains on the card

## Expected behavior

After deleting a property on a card and seeing the "success" message, the property is deleted and no longer visible on the card

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/13020833/180965713-009026d4-b30d-4a2b-b8a2-40b667fb380b.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2.0
 - Browser and OS: Windows 10 / Chrome

**Comment by chenilim** [comment]
This may already be fixed in main. Please check @sbishel. Thanks.

**Comment by sbishel** [comment]
Retested on latest  https://boards-bugbash.test.mattermost.cloud/
This has been fixed along the way. Closing....
Reopen if you still see this issue.
