### ISSUE TITLE
Bug: Calendar View - "More Options" modal displays behind tasks

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#3425]
Found by `@krmh04` QA community contributor bug bashing on `https://boards-bugbash.test.mattermost.cloud/` server

## Steps to reproduce the behavior

1. Switch to calendar view
2. Add tasks on a date
3. Click on the more options (three dots) button
4. Observed: "More options" modal displays behind tasks

## Expected behavior

Not sure - perhaps display the "More options" modal a little to the right of the tasks?

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/13020833/180973569-b854e99b-3a8b-4998-abfc-5e3cec1da199.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2.0
 - Browser and OS: Windows 10 / Chrome

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround

**Comment by sbishel** [comment]
@Pinjasaur - I spoke to @chenilim about this. If this can't be fixed easily (and quickly). Let's "fix" it by removing the functionality from Calendar, its new functionality and the we can implement correctly (using single instance) when we have more time.
