### ISSUE TITLE
Bug: Find Boards > Icons on dark themes have low contrast

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#3442]
## Steps to reproduce the behavior

1. Set a dark theme
2. Open Boards
3. Click "Find Boards" and start typing a board name
4. Note the icons are barely visible

## Expected behavior

Icon color should be lighter so it's more easily visible against a dark background

## Screenshots (optional)

Boards:
![image](https://user-images.githubusercontent.com/15314183/181460839-0dabab5c-d723-4cc9-92d1-c9716855d6ba.png)

Channels (expected):
![image](https://user-images.githubusercontent.com/15314183/181460899-268b3a43-77cf-4eb2-b7b2-6f0e7e3a26a9.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2
 - Browser and OS: Chrome on Windows

**Comment by wuwinson** [comment]
@asaadmahmood Ideas?

**Comment by asaadmahmood** [comment]
@wuwinson Submitted a fix for this here:
https://github.com/mattermost/focalboard/pull/3445

**Comment by wuwinson** [comment]
Nice, thanks @asaadmahmood!
