### ISSUE TITLE
Bug: Users don't have admin permissions on boards they created

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#3443]
## Steps to reproduce the behavior

1. As a member, create a board in a channel on Boards v7.1
2. Upgrade to v7.2
3. Open Boards and find that board
4. Open the Share modal
5. Note that you're not an admin

## Expected behavior

Users should be admins on boards they created

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/15314183/181464656-519c7f63-648c-416a-ac89-71aadfb47169.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2
 - Browser and OS: Chrome on Windows

**Comment by jespino** [comment]
The server side part is already merged, lets wait until rajat do his changes and we can test it again in a fresh community database migration.

**Comment by ogi-m** [comment]
I can no longer repro this on the community clone
