### ISSUE TITLE
Bug: Text containing single backticks causes data loss

### ISSUE THREAD

**Issue by neflyte** [mattermost/focalboard#3446]
## Steps to reproduce the behavior

1. Create or open a card
2. Add a comment or add a description containing text enclosed in single backticks (e.g. for monospaced text)
3. Save the comment or description
4. Notice it disappears with no warning or error

## Expected behavior

My data is saved and can be retrieved.

## Edition and Platform

 - Edition: Community server
 - Version: v7.1.0
 - Browser and OS: Ubuntu 20.04, MM Desktop App v5.1.1

## Additional context (optional)

This should be considered a Sev1 issue as there is data loss with no indication that any error occurred.
Text enclosed in triple backticks (e.g. for unformatted blocks of text) does not trigger the issue.

**Comment by chenilim** [comment]
@neflyte, thanks for filing this! I could not repro using Chrome or Desktop App on Mac. Would you be able to attach a video? i.e. do you think it's specifically about the backticks? Does text without backticks save correctly?

**Comment by neflyte** [comment]
I can't reproduce this with v7.2; I'll assume it got fixed somewhere. :smile:
