### ISSUE TITLE
Bug: Cannot remove/hide boards from LHS

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#3447]
## Steps to reproduce the behavior

1. With User A, add User B to a board. Notice the board shows up in LHS for User B.
2. With User B, try to remove that board from the LHS. YOu can neither leave the board from anywhere nor remove the board from the sidebar.

## Expected behavior

User should either be allowed to leave a board or at least hide it from the LHS. Channels' behavior is to leave a channel to remove it from LHS and for DMs, one can "close conversation" which keeps the messages but removes the DM from LHS.

Lack of this feature would be an issue after v7.2 is deployed on the community and everyone ends up with dozens of boards on LHS>

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.2

**Comment by wuwinson** [comment]
Need an option to hide the board from the LHS similar to Channels. @wuwinson to provide a spec.

**Comment by chenilim** [comment]
Link to spec: https://docs.google.com/document/d/1pcNMzUETYp-T8WpBRzK68vDq-itzYsjz6PH554mhBrc/edit
