### ISSUE TITLE
Bug: LHS category collapsed/expanded state resets on switching teams

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#3448]
## Steps to reproduce the behavior

1. Be part of more than one team.
2. Open team 1, create a category in Boards LHS and collapse it.
3. Switch to team 2, then back to team 1.
4. Notice the collapsed category is now expanded.

## Expected behavior

The collapsed/expanded state of a category should not reset on switching teams. Ideally, it should even persist refreshes and be part of user's preferences.

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.2

**Comment by chenilim** [comment]
The expand/collapse state is also lost on a simple page refresh.
