### ISSUE TITLE
Bug: Text in Card (in Board View) overlaps with "..." menu

### ISSUE THREAD

**Issue by Pinjasaur** [mattermost/focalboard#3457]
## Steps to reproduce the behavior

1. Go to a card in a board view with text
2. Hover w/ cursor and notice the text overlaps the "..."  menu

## Expected behavior

Not overlap, either via z-index or more appropriate padding or linebreaking of the text.

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/6335792/181613539-f3da27b0-f936-4ca8-a107-2c8a6a56eb13.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.2 community clone bug bash
 - Browser and OS: FF103 Mac

**Comment by wuwinson** [comment]
@asaadmahmood Thoughts on making the options button with a solid background rather than transparent?

**Comment by asaadmahmood** [comment]
@wuwinson I've already fixed this in a PR.
https://github.com/mattermost/focalboard/pull/3445

**Comment by wuwinson** [comment]
Awesome, thanks @asaadmahmood!
