### ISSUE TITLE
Bug: when accessing Boards through a link, the team is not highlighted

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/focalboard#3458]
## Steps to reproduce the behavior

1. Go to a board on a multi-team instance
2. Reload

## Expected behavior

The team that my board is in should be highlighted

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2
 - Browser and OS: Firefox 102.0.1 on Linux

**Comment by wuwinson** [comment]
Refreshing on the Contributors team causes issues and ends up on the Staff team with an error on the URL.

**Comment by sbishel** [comment]
This was fixed again with https://github.com/mattermost/focalboard/pull/3602
