### ISSUE TITLE
Bug: template selector text needs updating

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/focalboard#3464]
## Steps to reproduce the behavior

1. Press the "+" icon to create a new board

another way to reproduce this is the following:

1. Go to channels
2. Press the boards icon
3. Try to link a new board and press the "Create Board" icon to create a new one

## Expected behavior

First case: The text says "Members of Contributors will have access to boards created here" but that's not true anymore, as new boards will be private by default and only manually added members will have access to them.

Second case: The error in the text is the same one, but the fixed text could make a reference to the channel that the new board will be linked to.

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/223323/181615218-63e5faba-09e1-43be-9725-1d2c7099fe7f.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2
 - Browser and OS: Firefox 102.0.1

**Comment by Pinjasaur** [comment]
https://community.mattermost.com/core/pl/k36xq7bqd7dyujhwhao11x1kww

**Comment by wuwinson** [comment]
Let's remove the 2nd sentence for v7.2.
