### ISSUE TITLE
Bug: Categories should be collapsed by default

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3465]
## Steps to reproduce the behavior

1. Go to the [Community Clone server](https://community-dr.staging.cloud.mattermost.com/)
2. On Channels, go to the `R&D Meeting` channel
3. Click on the Boards Apps Bar button to load the new RHS
4. Click on the `ice-breakers` board
5. See error - Board loads, but the board is not visible on the LHS until you scroll down because so many categories are open after the migration

## Expected behavior

A better UX might be to collapse all categories by default after migration and then possible do #3449 in a future release.

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2 Bug Bash
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment]
cc @asaadmahmood 

@mgdelacroix mentioned this is consistent with the current behavior in Channels.

**Comment by chenilim** [comment]
Propose bumping up the priority of this, as it will help with the initial impression. Also equally important that the category collapsed state is persisted - not sure if that's already tracked.

**Comment by chenilim** [comment]
Related to https://github.com/mattermost/focalboard/issues/3448

**Comment by harshilsharma63** [comment]
@chenilim @wuwinson to be clear, we want all newly created categories to be "collapsed" by default, right? As part of #3448, we'll persist a category's expanded/collapsed state anways.

**Comment by chenilim** [comment]
I'll defer to Winson, but my understanding is the categories should be collapsed **after migration**. IMHO, categories created by the user should be uncollapsed. cc @asaadmahmood.

**Comment by harshilsharma63** [comment]
Makes sense @chenilim .

**Comment by wuwinson** [comment]
Yep agreed, this applies to **migrated** custom categories only. Any new categories created by the user should be uncollapsed.
