### ISSUE TITLE
Bug: Cannot see opened board when its category is collapsed

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#3467]
## Steps to reproduce the behavior

1. (On 7.2 bugbash server), open a board
2. Collapse its category
3. It's impossible to see which category contains the selected board

## Expected behavior
Even if the category is collapsed, the board should be shown in the LHS selected.

## Screenshots (optional)

https://user-images.githubusercontent.com/46905241/181635236-52d0d2c4-7304-46f9-afba-8a5580e66f5c.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.2 (bugbash)
 - Browser and OS: Chrome on Mac

## Additional context (optional)

This will be particularly challenging when opening a board from a channel that is in a collapsed category.

**Comment by chenilim** [comment]
@asaadmahmood, do you have an opinion on how this should work? cc @wuwinson.

**Comment by chenilim** [comment]
@asaadmahmood, please define behavior and reassign to triage for v7.3. Thanks. cc @wuwinson.

**Comment by asaadmahmood** [comment]
@chenilim Added it.

**Comment by sbishel** [comment]
I believe this has been fixed.  https://github.com/mattermost/focalboard/pull/3556
