### ISSUE TITLE
Bug: Migrated board has no admin

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#3471]
## Steps to reproduce the behavior

1. (7.2 bugbash) open a migrated board, e.g. Announcements \ Content calendar, or R&D Meeting \ demos
2. Select Share
3. There's no admin

## Expected behavior

Every board should have at least one admin

## Screenshots (optional)

<img width="630" alt="Screen Shot 2022-07-28 at 2 09 31 PM" src="https://user-images.githubusercontent.com/46905241/181637954-0291bcba-573a-4bc1-97a9-feeadada2da7.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2 bugbash
 - Browser and OS: Chrome on Mac

**Comment by chenilim** [comment]
cc @wuwinson, @asaadmahmood. I think there might be at least two issues here:
1. The migration didn't set the admin correctly
2. There can be a case where the admin of a board is no longer available (e.g. left the company). What is the solution to reset the admin then? i.e. can a team admin do that?

**Comment by wuwinson** [comment]
Think this is the related to https://github.com/mattermost/focalboard/issues/3443.

A board requires at least one admin, so the last admin can never be removed. If that admin is no longer at the company, the system admin would have to reset the pw for the user and login as them to reset the admin.

We can also move [this feature](https://docs.google.com/document/d/1BwXeEDeTXJzecFE1D8mjcKyL5nC3IK81sKziz3257uA/edit#bookmark=id.d89ryclpwaoe) up to v7.3 to mitigate this issue.

**Comment by chenilim** [comment]
cc @ogi-m - please retest on the latest bugbash this week. There was an issue of slow user-data refreshes, which was fixed in the latest release branch.

**Comment by ogi-m** [comment]
I can no longer repro this on the community clone
