### ISSUE TITLE
Bug: backport the websocket fixes to webapp 7.1.X and update the Boards 7.2 minimum version accordingly

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/focalboard#3484]
We need to make this change in preparation for the Boards 7.2 release, so it can correctly run on Mattermost ESR

**Comment by wuwinson** [comment]
Let's set the min server version to 7.2, and recommend customers on ESR to upgrade to the next ESR for stability. cc @sbishel @chenilim
