### ISSUE TITLE
Bug: Pressing Enter two or more times results in multiple categories

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#3511]
## Steps to reproduce the behavior

1. Select ... next to a category in the sidebar
2.Select add new cateogory
3. Type in a name
4. Press enter multiple times rapidly
5. Multiple categories with the same name are created

## Expected behavior

Only one category is created

## Screenshots (optional)
https://user-images.githubusercontent.com/46905241/182256678-999aeef0-3d9c-49c6-ad54-878f7f5e588c.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2 bugbash
 - Browser and OS: Chrome one Mac

## Additional context (optional)

The first time this happened, the server was slow, and I ended up creating 4 copies of the same category.

**Comment by wuwinson** [comment]
@ogi-m Can you confirm if this is happening on other dialogs? Thanks!

**Comment by wuwinson** [comment]
Retested on latest bug bash and appears fixed. Reopen if necessary. Thanks!
