### ISSUE TITLE
Bug: Lack of margin between text and button in link dialog

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#3512]
## Steps to reproduce the behavior

1. Select Boards icon from channel header and select + Add
2. Notice that long descriptions go up to the button

## Expected behavior

There should be a margin between text and the button

## Screenshots (optional)

<img width="623" alt="Screen Shot 2022-08-01 at 3 09 24 PM" src="https://user-images.githubusercontent.com/46905241/182257761-f5da399a-e6ee-4d95-9172-6dbf8aa468d1.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.2 bugbash
 - Browser and OS: Chrome on Mac

**Comment by chenilim** [comment]
@asaadmahmood, is a margin specified in the design? cc @wuwinson.

**Comment by wuwinson** [comment]
@asaadmahmood Can you tackle this one? Thanks!

**Comment by asaadmahmood** [comment]
@wuwinson Sure.
