### ISSUE TITLE
Bug: Card updates after a long delay

### ISSUE THREAD

**Issue by cdlangen** [mattermost/focalboard#3519]
## Steps to reproduce the behavior

Once when I altered a card in the webapp (tried to add comments / alter the description), the changes didn't appear in the card and no error message was shown. After a few minutes the comments and changes did eventually appear. I have no idea why this occurred, so I don't know how to reproduce it.

## Expected behavior

The card updates with changes. If the card cannot update, then show an error message indicating the cause.

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: [e.g. v7.1.0]
 - Browser and OS: [e.g. Chrome on Ubuntu]

**Comment by wuwinson** [comment]
@cdlangen Thanks for reporting this. If anyone else notices this, please chime in and add any repro steps if possible. Thanks!

**Comment by sbishel** [comment]
closing as cannot repo.
