### ISSUE TITLE
Bug: Boards with no icon don't have the official boards icon displayed

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#3520]
## Steps to reproduce the behavior
1. Create a board with no icon
2. Open modal on channels to link a board.
3. See that if the board has no icon, no icon is shown.

## Expected behavior
Official Boards icon should show on boards that don't have an icon.

## Screenshots (optional)
<img width="649" alt="Screenshot 2022-08-02 at 6 00 20 PM" src="https://user-images.githubusercontent.com/11034289/182381004-00498e65-8c0c-48cf-a21a-23fb7368016b.png">

## Edition and Platform
 - Mattermost Boards (plugin)
 - Version: 7.3.0
 - Browser and OS: Chrome Mac

**Comment by wuwinson** [comment]
@asaadmahmood Can you attach/link the icon to this ticket? Feel free to tackle this one if you have capacity as well. Thanks!

**Comment by asaadmahmood** [comment]
@wuwinson It's the same icon we have in the LHS for boards with no icons.

**Comment by sbishel** [comment]
Closing as fixed. 
<img width="616" alt="Screen Shot 2022-08-11 at 6 02 41 PM" src="https://user-images.githubusercontent.com/12704875/184261884-b1982ee7-c4df-4c58-bcbb-48079f856d31.png">
