### ISSUE TITLE
Bug: Not obvious you can search for a channel in the Share dialog

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#3523]
## Steps to reproduce the behavior

1. Open the Share dialog for a board
2. Not obvious how to link to a channel

## Expected behavior

Recommend changing the search box placeholder text to "Search for people or channels"

## Screenshots (optional)

<img width="632" alt="Screen Shot 2022-08-02 at 2 56 50 PM" src="https://user-images.githubusercontent.com/46905241/182480604-acc05d55-d7a4-4dcc-b964-3ac696063385.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2 bugbash
 - Browser and OS: Chrome on Mac

**Comment by chenilim** [comment]
cc @asaadmahmood - I actually forgot about this feature, and couldn't figure it out until I read @wuwinson's help doc. :) Do you think this is enough, or could we improve the discoverability more?

**Comment by asaadmahmood** [comment]
@wuwinson Yup, I'll fix it right now.
