### ISSUE TITLE
Feature Idea: Allow boards from any team to be searched for

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#3524]
## Summary

(Based on 7.2 bugbash): Allow boards from all teams the user is a member of to be found in the search (Cmd+K). Automatically switch to the appropriate team when selected

## How important this is to me and why

Importance: Medium

Use cases:
1. The problem today is you need to be on the "correct" team to find a board, which is ambiguous in the case of migrated DM / GM channel boards
2. It is also consistent with Channels to allow cross-team search

**Comment by chenilim** [comment]
cc @asaadmahmood, @wuwinson - I don't remember if we discussed this before, but in light of the 7.2 changes doc, this will avoid some user confusion.

**Comment by sbishel** [comment]
@chenilim - We do search across teams. Can this be closed?

**Comment by chenilim** [comment]
Yup, cross team search is working now, so closing.
