### ISSUE TITLE
Bug: Boards autocomplete acts weird while searching for boards

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#3532]
## Steps to reproduce the behavior
See video below.
https://user-images.githubusercontent.com/11034289/182692535-6bd6f75b-e9d8-4921-915c-c99e00ea4b35.mov

## Expected behavior
Matches matching the search text most relevantly should appear above.

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2 Bug Bash
 - Browser and OS: Chrome on Mac

**Comment by sbishel** [comment]
Should be fixed by the following two PRs. Open a new issue if still seeing issues.
https://github.com/mattermost/focalboard/pull/3623
https://github.com/mattermost/focalboard/pull/3622
