### ISSUE TITLE
Bug: Custom templates shared with the team are misleading with the role assignment

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3543]
## Steps to reproduce the behavior

1. Open the template picker
2. Create new template
3. Share the template with the team by setting the team role as "Editor"
4. Log-in as another team member
5. Open the template picker and hover over the template created in step 2
6. See error - User from step 4 is not able to edit the template even though they are "Editors" of the template

## Expected behavior

The team role should display something less misleading, so it's clear to the template admin that sharing with the team only gives the team "viewer" access and not edit access.

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/182745971-5b8fc448-13bd-4974-8047-bdb1fbb2a4cc.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment]
Maybe related to #3531 

cc @sbishel @chenilim

**Comment by jespino** [comment]
After investigating it, it can be possible, you are seeing all the "public" templates, that are the ones that "allows you to join by default", but for templates the meaning is different, is "anyone can use it, but not necessarily join". So... you don't have edit or delete permissions until you get explicitly invited or you find the way to join it (the interface doesn't allow you to do that).

You are seeing there the builtin templates, the templates that you are member of, and the public templates that third category looks like the ones that you can't manage. Do you think that is wrong @wuwinson ?

**Comment by wuwinson** [comment]
@jespino I did a little investigating as well, and confirmed that they are most likely due to setting the team role on the templates as "Editor". Personally I think this is preferable to not allow team members to edit the template unless they are explicitly added by the admin, but the role "Editor" is misleading then. We should rename the role dropdown specifically for the template editor to something more accurate. Either renaming it "Viewer" or something along the lines of "Access / no access". @justinegeffen @asaadmahmood Thoughts on this?

![Screen Shot 2022-08-04 at 10 54 49 PM](https://user-images.githubusercontent.com/93531870/182991812-cc8c6e82-4cd7-4d8a-bb6c-5fdc0e7b1197.png)

Additionally, I also tried linking a channel to the template, and nothing happens. Regardless if the 2nd user was a member of that channel or not. We should either hide channels in the template share modal or fix it so that only members of those channels can see the template. Whichever is easier for v7.2. @sbishel @chenilim Thoughts?

See recording using 2 users:

https://user-images.githubusercontent.com/93531870/182990861-fcce71a8-70c8-420d-8b7b-7138a33598f6.mov

**Comment by wuwinson** [comment]
@jespino Updated this ticket and separated https://github.com/mattermost/focalboard/issues/3625 into its own ticket.

**Comment by jespino** [comment]
@asaadmahmood do you mind to make a specific UX proposal for this change? I don't need a full UX, It would be just enough with a textual description with the exact texts used.

**Comment by asaadmahmood** [comment]
@jespino I am more inclined to change it as "Viewer".
I can also think of separate ways to differentiate the share template modal from the share board modal, which we can do later.
