### ISSUE TITLE
Bug: Sidebar scrollbar almost invisible

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#3544]
## Steps to reproduce the behavior

1. (7.2 RC1) Open Boards
2. Try to scroll the sidebar
3. The scrollbar is almost invisible

## Expected behavior

More visible scrollbar.

## Screenshots (optional)

https://user-images.githubusercontent.com/46905241/182758482-7ec3d67b-097f-442d-90e1-9e2b9bb3f1ed.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.2 RC1
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment]
@asaadmahmood Can you help with this one? Thanks!
