### ISSUE TITLE
Feature Idea: Select opened board in sidebar

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#3548]
## Summary

When opening a board from board switcher, the board opens up but if the board isn't brought into viewport in the LHS and a lot of times you need to manually find it.

Additionally, if that board is in a category and the category was collapsed, do we open that category?

## How important this is to me and why

Importance: Medium

**Comment by harshilsharma63** [comment]
cc @asaadmahmood @wuwinson

**Comment by wuwinson** [comment]
Dupe of #3466 - Would be awesome to get this in for v7.3 if it's simple, otherwise we can leave it up for grabs and prioritize it for a later time if it doesn't get picked up.
