### ISSUE TITLE
Bug: Send button doesn't appear when writing comments

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#356]
**Steps to reproduce the behavior:**
1. Create card and open it
2. Click on the comments box
3. The send button doesn't appear, and I can't send the comment

**Expected behavior:**
The send button should appear when I start writing a comment.

**Platform:**
 - App on macOS 10.15.7
 - Also Chrome 89

**Additional context:**
Pressing Cmd+Enter makes the send button appear, and I can then click on it, but it's not obvious.
This used to work, so was likely a regression in 0.6.5.

**Comment by jespino** [comment]
Fixed here: d09d6e0e4080b257e3d0a898cb1cab4d2640efb7 . Not the most elegant solution, but it works.
