### ISSUE TITLE
Bug: Searching boards does not return relevant items

### ISSUE THREAD

**Issue by nab-77** [mattermost/focalboard#3564]
## Steps to reproduce the behavior

1. Use the search box Find Boards or the search box on the Link boards dialog
2. Type in your board name
3. Review list
4. Note the board you are searching for is missing

## Expected behavior

1. Based on your search input the list would be complete, including the board you are searching for.
2. When searching for multiple words, board switcher search results should display results for an "AND" query and not an "OR" query. For example, when searching for "Meeting Agenda", results should include both the terms "Meeting" AND "Agenda".
3. Results should be sorted alphabetically

## Edition and Platform

 - Edition: community.mattermost.com
 - Version: Boards v7.2.0
 - Browser and OS: Chrome on macOS & Desktop App on macOS.

**Comment by wuwinson** [comment]
@nab-77 Is this happening for single word searches or when you start using multiple words in your search term? cc @sbishel @chenilim

**Comment by wuwinson** [comment]
I'm encountering this pretty frequently whenever I enter a 2nd word into my search term from both the Link Board modal and the Share modal.

https://user-images.githubusercontent.com/93531870/183123385-e5527440-385d-4805-8b06-da6c09dcd244.mov


https://user-images.githubusercontent.com/93531870/183123429-48269715-5a02-472a-918d-1527b5c1d510.mov

**Comment by nab-77** [comment]
Its on a single word for me. I am looking for `Product Journey Team` board.
<img width="653" alt="Screenshot 2022-08-04 at 15 13 27" src="https://user-images.githubusercontent.com/93996140/183157918-2ed3804d-a5dd-40bb-9196-7d385ee5be0a.png">

**Comment by harshilsharma63** [comment]
@wuwinson what you are showing in the demo video is because when you search for multiple words, we don't look for them occurring together, but rather anything that matches either word. For example, if you search for "hello world", you'd get everything containing just "hello", and just "world" rather than things containing "hello world" together. From your video I can see this isn't the ideal experience but so it always searching for the two terms together.

I remember implementing this way thinking if you wanna open the Focalboard OKR board and search for "Focalboard OKR", and the board is named "Focalboard Q4 OKR", you won't get any results. I can see from the video that either approach isn't ideal.

**Comment by harshilsharma63** [comment]
@nab-77 can you tell which channel was that board in and which team?

**Comment by wuwinson** [comment]
Need to file separate bugs for these 3 search bugs.

**Comment by nab-77** [comment]
> @nab-77 can you tell which channel was that board in and which team?

I was searching for Product Journey Team Meeting Agenda board, in the Product Journey Team channel (it does show as a linked board in the RHS).

**Comment by wuwinson** [comment]
> 

@nab-77 The board switcher only searches for the board name, not the channel name. Is your board titled "Product Journey Team Meeting Agenda" or is it titled "Meeting Agenda" on the Product Journey Team channel? If it's the latter, then you'd need to search for the term "Meeting Agenda".

**Comment by nab-77** [comment]
Board name is Meeting Agenda. So using those search terms I get multiple boards in the results and I am unable to see which is the one I am looking for.

I did used to enter "Product" in the search box and see the item.

**Comment by nab-77** [comment]
As a follow up I renamed the board to "Product Journey Team Meeting Agenda" and when entering I still get no results.

**Comment by wuwinson** [comment]
Thanks for following up Neil! We're looking to address this bug in the following ways:

1. Switch the search with multiple words from an "OR" to an "AND" search, which would narrow down the results and be consistent with how the channel switcher works.
2. Display your custom categories in the search results, so it's easier to find your board that uses the same name as other boards.

When you renamed the board to "Product Journey Team Meeting Agenda" the search results should be displaying boards the have ANY of those 5 words. Are you getting no results or too many? If it's no results, then that might be another issue we'll have to investigate. cc @sbishel

**Comment by nab-77** [comment]
I get results just not the board I am searching for.

"Product"  > results do not contain what i am looking for
"Product Journey"  > results do not contain what i am looking and does not expand the list of results
"Product Journey Team"  > results do not contain what i am looking for but does expand the list of results
"Product Journey Team Meeting"  > results do not contain what i am looking for but does expand the list of results further 
"Product Journey Team Meeting Agenda"  > results do not contain what i am looking for but expands the list of results even further

Seems like we are currently doing an `OR` search as with the last search "Meeting Agenda" board in the list of results.

Sadly I never see the board I am searching for.
