### ISSUE TITLE
Bug: Link board to channel button should be blue

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3568]
## Steps to reproduce the behavior

1. Go to a board without a channel already linked to it
2. Open the Share modal on the board
3. Search for a channel to link to the board
4. See error - the `Yes, link here` button is red

5. Go to any channel and open the Boards Apps Bar
6. Open the Link Boards modal and search for a board that isn't already linked to a channel
7. Click on the "Link" button for that board
8. See error - the `Yes, link board` button is red

## Expected behavior

Both buttons in these use cases should be blue. The only time it should appear red is when a link is replacing an existing link.

## Screenshots (optional)

![Screen Shot 2022-08-04 at 2 30 07 PM](https://user-images.githubusercontent.com/93531870/182928810-9a5354e2-0d59-44bd-a15c-7ee7616fbf18.png)

![Screen Shot 2022-08-04 at 2 31 33 PM](https://user-images.githubusercontent.com/93531870/182928821-76ea1f00-f1bf-425b-bf47-57941bb56f19.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2 RC1
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment]
cc @asaadmahmood in case you have capacity to tackle this for v7.2, otherwise we'll hold off until v7.3.

**Comment by asaadmahmood** [comment]
@wuwinson This is already fixed on 7.2 (not on community), but probably for rc2.

**Comment by wuwinson** [comment]
Nice!
