### ISSUE TITLE
Bug: Portrait pictures are distorted

### ISSUE THREAD

**Issue by Ghisura** [mattermost/focalboard#357]
**Summary:**
when add picture in card, portrait pictures are distorted 
**Steps to reproduce the behavior:**
1. open/create card
2. Click on add picture 

**Expected behavior:**
portrait picture keep the right proportions

**Screenshots:**
picture source :
![food-5981232_1280](https://user-images.githubusercontent.com/30210989/116402886-36201900-a82d-11eb-99d3-050b1ea8670a.jpg)

in card:
<img width="1071" alt="Untitled (2)" src="https://user-images.githubusercontent.com/30210989/116403085-6ff11f80-a82d-11eb-8060-5bf96f4c5cb9.png">

**Platform:**
 - Browser Chrome , vivaldi, firefox
 - OS  macOS, self-hosted

**Comment by jespino** [comment]
Fixed in main branch :)
