### ISSUE TITLE
Bug: Ability to un-hide a board

### ISSUE THREAD

**Issue by Pinjasaur** [mattermost/focalboard#3575]
## Steps to reproduce the behavior

1. Hide a board
2. It's now hidden from being rendered, what if I want to see it again?

## Expected behavior

Ability to unhide a board besides the very-technical workaround of manually sending a PUT request with the updated `hiddenBoardIDs` key & values.

## Screenshots (optional)

If applicable, add screenshots or a screen recording to elaborate on the problem.

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.2 rc2
 - Browser and OS: FF104 Mac

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by Pinjasaur** [comment]
I now see `handleUnhideBoard` which seems to be work if you have a direct link to a board? It would be nice to have an alternative method so I can't lock myself out of a board, so to speak.

**Comment by wuwinson** [comment]
@Pinjasaur This is the same behavior as Channels - you can also still search for the board from the board switcher, which would unhide it if you "join" again. Closing out.
