### ISSUE TITLE
Bug: LHS team not selected upon reload

### ISSUE THREAD

**Issue by Pinjasaur** [mattermost/focalboard#3576]
## Steps to reproduce the behavior

1. Go to any team/board/card URL
2. Reload the page
3. Notice the team on the LHS isn't automatically selected

## Expected behavior

The team to be auto selected/persisted upon a fresh page load.

## Screenshots (optional)

<img width="708" alt="image" src="https://user-images.githubusercontent.com/6335792/182972285-fdc8a82f-9104-438b-af56-8f75b4daa52f.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.2 rc2
 - Browser and OS: FF104 Mac

## Additional context (optional)

Happens on bugbash & community servers.

**Comment by sbishel** [comment]
duplicat of https://github.com/mattermost/focalboard/issues/3458?

**Comment by Pinjasaur** [comment]
I'll close this in favor of #3458 as it's a dupe.
