### ISSUE TITLE
Bug: Unable to link board to DM

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3584]
## Steps to reproduce the behavior

1. Go to a DM
2. Open Link Boards modal
3. Search for a board already linked to another channel
4. Click on the blue Link button
5. Click on the red Link button after confirmation modal appears
6. See error - board doesn't link to the DM and no indication of failed linkage

## Expected behavior

Board is linked to the DM and unlinked from previous channel

## Screenshots (optional)

https://www.loom.com/share/f343bd91d6ca4680964503e01a0a3197

<img width="1552" alt="Screen Shot 2022-08-05 at 10 43 24 AM" src="https://user-images.githubusercontent.com/93531870/183120605-fc0d8719-cd82-4b24-b484-402c9d593930.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2 RC2
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment]
See [thread](https://community.mattermost.com/private-core/pl/on5r7rkj8ifpuykkpa1x8ui85o) for details.

**Comment by sbishel** [comment]
Duplicate of https://github.com/mattermost/focalboard/issues/3509?

**Comment by wuwinson** [comment]
Looks like it, closing out.
