### ISSUE TITLE
Bug: Lost board when new permissions rolled out 

### ISSUE THREAD

**Issue by wiersgallak** [mattermost/focalboard#3588]
## Steps to reproduce the behavior

After permissions and the new LHS was added, I am no longer able to find the board I had in my DM with myself. (I believe the board name was ```katie.wiersgalla,katie.wiersglla```  - that is how I found it when searching for it from the prior Boards UI. The view I believe was named "Personal Tasks", but I am not completely certain. 

I have a bookmark to it on Chrome, and when I select the bookmark, I get a white page.  Here's the URL: https://community.mattermost.com/boards/workspace/furnzjswi3rf7cg65ix9iuhfrw/074aca72-00c3-4708-852c-a6289f096f54/e40b0d8f-a66a-434a-806e-572c94ed8c6f.  

I am unable to find the board listed under any other new category in the Boards LHS including the generic "Boards" category. I also seem to be missing a shared board in a DM I have with Corey Hulen for managing 1:1s. 

## Screenshots (optional)

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/39744472/183206658-fa8bc8f6-ac7e-4347-ad50-5c9a33b97661.png">

## Edition and Platform

 - Edition: Community.mattermost.com / Mattermost Boards (I believe 7.2)
 - Browser and OS: Chrome on Mac

**Comment by wiersgallak** [comment]
Providing a bigger image of the console in case its useful: 
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/39744472/183208863-a872ed32-7044-4e27-bb0b-fdc07c2e892d.png">

**Comment by sbishel** [comment]
Adding conversation https://community.mattermost.com/core/pl/zyj34acjobycm87qc53nobyxwh

Query's to determine current member settings. Any other queries to request from SRE?

SELECT * FROM focalboard_board_members WHERE board_id = '074aca72-00c3-4708-852c-a6289f096f54'
SELECT * FROM focalboard_board_members_history WHERE board_id = '074aca72-00c3-4708-852c-a6289f096f54'
SELECT channel_id, created_by from focalboard_boards WHERE id = '074aca72-00c3-4708-852c-a6289f096f54'

**Comment by wiggin77** [comment]
I'm seeing requests for the board link in community logs.  First request is the old style URL:
```
/boards/workspace/furnzjswi3rf7cg65ix9iuhfrw/074aca72-00c3-4708-852c-a6289f096f54/e40b0d8f-a66a-434a-806e-572c94ed8c6f
```
which gets redirected to:
```
/api/v2/boards/074aca72-00c3-4708-852c-a6289f096f54
```
That second request returns an `access denied to board` 403 in all cases after 7.2 was deployed.

**Comment by mgdelacroix** [comment]
Reading through the `migrateTeamLessBoards` data migration, turns out we're not checking that the teams we're assigning the boards to are not archived, so chances are that both Katie and Corey were members of a team that is not available anymore and that's the one that the board got assigned to.

Will try to repro this first thing tomorrow and work on a fix

**Comment by mgdelacroix** [comment]
Reopening the issue as we need to fix it in Community, where the faulty migration has already run
