### ISSUE TITLE
Doc: How do I build this without having mattermost/enterprise

### ISSUE THREAD

**Issue by clmnin** [mattermost/focalboard#3591]
## Summary

I tried building the app using the following commands
```shell
make prebuild
make
```

But it fails when it can't find the `mattermost/enterprise` repo - which is not open source. And so I tried building a stand alone linux app using `make linux-app` but this fails with the same error.

## Link to documentation page

Link to the doc I followed - [link](https://developers.mattermost.com/contribute/focalboard/personal-server-setup-guide/#building-via-the-terminal)

**Comment by noxer** [comment]
Hi @clmnin, thanks for reporting this. It's a bug in our Makefile.

For now you can mitigate it by running `make setup-go-work`, opening the `go.work` file in the root folder of the repository, and removing the line `use ../mattermost-server`.

**Comment by clmnin** [comment]
Thank you
