### ISSUE TITLE
Bug: Local mode password reset results in a "404 page not found" message

### ISSUE THREAD

**Issue by evoactivity** [mattermost/focalboard#3595]
## Steps to reproduce the behavior

1. Enable local mode and restart focalboard service
2. attempt to use password-reset.sh
3. see `404 page not found` message

## Expected behavior

Password is reset for user

## Edition and Platform

 - Edition: Personal Server
 - Version: v0.15.0
 - Browser and OS: curl 7.68.0, Ubuntu 20.04.3 LTS

## Additional context (optional)
This is just installed on a digital ocean droplet without docker following https://www.focalboard.com/download/personal-edition/ubuntu/. It installed and worked fine when I was using it in April. I haven't used it for months though, and I have lost my password. I attempted to use the reset-password script offered here https://www.focalboard.com/guide/admin/#resetting-passwords but I always get the above error when trying to use it.

The /var/tmp/focalboard_local.socket does exist.

This is my config

```json
{
    "serverRoot": "https://myboard.notreal",
    "port": 8000,
    "dbtype": "postgres",
    "dbconfig": "myPostgresUrl",
    "postgres_dbconfig": "dbname=focalboard sslmode=disable",
    "useSSL": false,
    "webpath": "./pack",
    "filespath": "./files",
    "telemetry": true,
    "prometheus_address": null,
    "session_expire_time": 2592000,
    "session_refresh_time": 18000,
    "localOnly": true,
    "enableLocalMode": true,
    "localModeSocketLocation": "/var/tmp/focalboard_local.socket"
}
```
This is the verbose output of the curl command
```
root@FocalBoard-ubuntu-s-1vcpu-2gb-ams3-01:/opt/focalboard# ./reset-password.sh myuser password
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying /var/tmp/focalboard_local.socket:0...
* Connected to localhost (/var/tmp/focalboard_local.socket) port 80 (#0)
> POST /api/v2/admin/users/myuser/password HTTP/1.1
> Host: localhost
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 26
>
* upload completely sent off: 26 out of 26 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Mon, 08 Aug 2022 11:59:56 GMT
< Content-Length: 19
<
404 page not found
* Connection #0 to host localhost left intact
```

**Comment by wuwinson** [comment]
@evoactivity You'll need to replace v2 with v1 in this line:
`curl --unix-socket /var/tmp/focalboard_local.socket http://localhost/api/v1/admin/users/$1/password -X POST -H 'Content-Type: application/json' -d '{ "password": "'$2'" }'`

@justinegeffen Can we update the [doc](https://www.focalboard.com/guide/admin/#resetting-passwords) to indicate that if prior to v7.2, then use v1 of the API, otherwise use v2.

cc @sbishel
