### ISSUE TITLE
Bug: Can't create new board cards on MM community

### ISSUE THREAD

**Issue by johndavidlugtu** [mattermost/focalboard#3597]
## Steps to reproduce the behavior

1. Go to Mattermost community
2. Try creating a new board card
3. Nothing happens

## Expected behavior

Clicking on "New" opens up a new card, or at least tells me why it's not responding.

## Screenshots (optional)

https://www.loom.com/share/aed98bc249b6495e8993c0e30e4fd58f

## Edition and Platform

 - Edition: Personal Desktop / Personal Server / Mattermost Boards (plugin)
 - Version: [e.g. v0.15.0]
 - Browser and OS: [e.g. Chrome on Mac, Edge on Windows]

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by sbishel** [comment]
@Rajat-Dabade - appears related to these -
https://github.com/mattermost/focalboard/pull/3444
https://github.com/mattermost/focalboard/pull/3335

@johndavidlugtu - As a work-around, you can create boards using the drop-down on the `New` button.

**Comment by wuwinson** [comment]
Only appears to occur on board view, but not other views. Clicking on the blue `New` button doesn't work either unless you use the drop down.

Might be some kind of delay with card creation, as some cards appeared on the board later on.
