### ISSUE TITLE
Bug: Non-board admin should not be able to unlink board from channel RHS

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3600]
## Steps to reproduce the behavior

1. Go to a channel with linked boards where you are not an admin of the board
2. Click on the options "..." menu for the board
3. See error - I am able to click on the "Unlink board" button even though I am not an admin of the board (although nothing happens from clicking on the button)

## Expected behavior

The "Unlink board" option should be disabled for non-board admins, and a subtitle should be displayed underneath the "Unlink board" option: "You are not an admin of the board"

Related to https://github.com/mattermost/focalboard/issues/3403

## Screenshots (optional)

![Screen Shot 2022-08-08 at 10 54 47 AM](https://user-images.githubusercontent.com/93531870/183449506-7f81e5b6-56cb-4031-9750-3e4b6ad71260.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2 RC2
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment]
cc @asaadmahmood On where to display the subtitle.

**Comment by asaadmahmood** [comment]
@wuwinson Added it, we can ignore the other options for now.
![image](https://user-images.githubusercontent.com/11034289/183450849-c2631697-f2c4-46a4-90bd-ddaaf43084b6.png)
