### ISSUE TITLE
Bug: Board admin cannot see linked channel if they're not a member of the channel

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3605]
## Steps to reproduce the behavior

1. Login as User 1 and create `Private Channel A`
2. Add User 2 to the private channel
3. Login as User 2 and create a `Private Board Z`
4. As User 2, open share modal and link `Private Channel A` to `Private Board Z`
5. Go back to User 1 and remove User 2 from the `Private Channel A`
6. Go back to User 2 and open Share modal on `Private Board Z`
7. See error - User 2 cannot see that `Private Channel A` is still linked to `Private Board Z`, and therefore no one is able to unlink the channel, since User 2 is the only admin of the board. User 1 is still able to access the board, but is not able to unlink the board.

## Expected behavior

Since User 2 is the board admin, they should still see that `Private Channel A` is linked to their board, even though they are no longer a member of the channel.

## Screenshots (optional)

![Screen Shot 2022-08-08 at 12 07 11 PM](https://user-images.githubusercontent.com/93531870/183464281-816376de-71c0-4eea-94d5-b97238cc548c.png)

![Screen Shot 2022-08-08 at 12 06 53 PM](https://user-images.githubusercontent.com/93531870/183464297-c93fb971-6bd2-489b-94e4-822c2a1f9c9a.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2 RC2
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment]
Edge case Sev/2, but can probably wait until v7.3.

**Comment by jespino** [comment]
I agree, this can wait until 7.3, but we have to think how to do it. If you are not a member of the channel, you can't even know the name of the channel, so... I would show something like "Private Channel (you don't have access to this channel)" and the unlink button. @asaadmahmood what do you think?
