### ISSUE TITLE
Bug: Private boards where I am an Editor are shown in link boards dialog

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3608]
## Steps to reproduce the behavior

1. Find a private board where you are an Editor
2. Go to a channel and open the link boards modal
3. Search for the private board from step 1
4. See error - board appears in the search results even though user is not an admin of the board
5. Clicking on the "Link board" button does nothing

Related to #3509 

## Expected behavior

Technically, if you are not a board admin, you should not see the board in the search results. However, in this case, the user is an explicit member of the board, and may be confused as to why they cannot find a board they have access to. For the short term, we should simply hide the board from the search results. In the long term, we should display some kind of messaging to help the user understand why they can't link the board. cc @asaadmahmood 

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/183475287-9c7fc272-4a18-4be1-86d5-6eab9997f09e.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2 RC2
 - Browser and OS: Chrome on Mac

**Comment by jespino** [comment]
I think this was fixed in the PR #3553 merged 4 days ago. I guess we can test after @sbishel uploads the rc3 to the server.

**Comment by wuwinson** [comment]
@jespino I think I tested after PR #3553 was merged, and it fixed public boards showing up in the results. Now this issue only happens when the user is an explicit board member, but not the admin.

**Comment by jespino** [comment]
@wuwinson I'll take a look.

**Comment by wuwinson** [comment]
Fixed in v7.2 RC3. Closing out. cc @sbishel
