### ISSUE TITLE
Feature Idea: Automatically open new card for editing

### ISSUE THREAD

**Issue by Johennes** [mattermost/focalboard#364]
**Summary:**

When clicking the _+ New_ button at the end of a column, a new card with empty content is appended to the row. It would be nice if the newly created card would be automatically opened so that I can edit title, description and other things.

![Screenshot 2021-04-30 at 11 15 07](https://user-images.githubusercontent.com/1137962/116675087-bbc6d480-a9a5-11eb-92fe-a1569d330c71.png)
![Screenshot 2021-04-30 at 11 15 13](https://user-images.githubusercontent.com/1137962/116675094-bcf80180-a9a5-11eb-847a-c7c878b48a61.png)

**How important this is to me and why:**

Importance: Medium

Medium importance for me. It's not a huge annoyance but I also run into it very often.

Use cases:

1. I want to add a new card with title / description to a board

**Comment by Johennes** [comment]
Oh, inline title editing would be even more convenient, agreed. 👍

**Comment by mblennegard** [comment]
@chenilim I would suggest that we instead add a setting for the preferred way, so the user can choose between opening the card automatically and have the inline editing (and maybe keep the current way as a third option).
This setting would then be good to have on a per board basis, so some boards might always open the cards whereas another board have the inline editing.

**Comment by rohit1101** [comment]
I am interested in this idea.
Can you assign me this issue @Johennes  ?

**Comment by Johennes** [comment]
@rohit1101 I don't have that superpower. I'm just a contributor as well. 🙂 

I think it's ok to just mention your interest here (which you did), then go work on it and submit a PR when done.

**Comment by chenilim** [comment]
Thanks @rohit1101! You got it! @Johennes thanks for all you do! You're right - if an issue is marked up for grabs, and no one else had grabbed it, generally you're good to go.

For this particular issue, I think we can fix @Johennes's original issue directly, i.e. when clicking on the + New on the board columns, open the card by default. This is consistent with clicking on the New button.
* And also do the same when clicking on +New in Gallery view

I consider the inline editing a separate feature. LMK if you intended to tackle that, and we can create a separate issue to track it - I'd tackle them as two separate PRs.

@mblennegard, are there particular scenarios where you'd find it useful to **not** open a card after edit (or activate inline editing)? Maybe bulk-inserting? Ultimately, that's something that should be easier to do in the table view.

**Comment by rohit1101** [comment]
Thank you assigning me this task I have cloned the repo and started working the task.
 I will try my best to get this done.

**Comment by rohit1101** [comment]
@chenilim I have raised a [PR link](https://github.com/mattermost/focalboard/pull/571).

And I also found a small bug in the sidebar of focalboard it is a minor CSS fix.

Can I fix the css bug and raise another PR ?

**Comment by rohit1101** [comment]
![Screenshot 2021-06-13 at 12 41 03 PM](https://user-images.githubusercontent.com/37110560/121798588-d8ad2380-cc44-11eb-92c5-8ebf2d31a4b9.jpg)

@chenilim I am going to fix this bug and raise a PR.

**Comment by rohit1101** [comment]
@chenilim Raised a PR for horizontal scrollbar fix 
https://github.com/mattermost/focalboard/pull/572

**Comment by chenilim** [comment]
Looks like #571 fixes this issue, so closing this. Thank you @rohit1101!
