### ISSUE TITLE
Bug: FindBoards - Boards in other teams display "Boards" as category

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#3641]
## Steps to reproduce the behavior

1. Go to "Find Boards"
2. Enter a letter to bring up multiple boards
3. Notice categories other than in current team are all Boards, not the actual category name.

## Expected behavior

Category from any team should be displayed.

## Screenshots (optional)

![Screen Shot 2022-08-10 at 4 28 05 PM](https://user-images.githubusercontent.com/12704875/184031592-6df3c012-b27d-456e-a130-31a18c0c7336.png)
![Screen Shot 2022-08-10 at 4 28 34 PM](https://user-images.githubusercontent.com/12704875/184031591-5d82a22c-d5ca-4e9c-8041-102d26bfe93f.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.2.0-rc3
 - Browser and OS: Chrome on Mac

## Additional context (optional)

We currently only retrieve categories for one team at a time (the current team). We would need to retrieve and store categories for all teams. I'm worried about the size of this fix.

**Comment by sbishel** [comment]
If we can't retrieve ALL categories...easily and quickly, we will revert the feature.

**Comment by harshilsharma63** [comment]
@sbishel I started it but it's getting a bit lengthy. I think it's best to revert the feature and skip this to 7.3.

**Comment by sbishel** [comment]
Reverted from v7.2 - https://github.com/mattermost/focalboard/pull/3650.

**Comment by wuwinson** [comment]
cc @asaadmahmood for v7.3

**Comment by harshilsharma63** [comment]
Closing this one as we decided not to display category name in search results.
