### ISSUE TITLE
Bug: Find Boards UX does not match spec

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#3642]
## Steps to reproduce the behavior

1. Go to "Find Boards"
2. Enter a letter to bring up multiple boards
3. Notice the Team is cut off and category should be left justified next to board name.

## Expected behavior
Team name displays, category displays next to board name

## Screenshots (optional)

![Screen Shot 2022-08-10 at 4 28 34 PM](https://user-images.githubusercontent.com/12704875/184031591-5d82a22c-d5ca-4e9c-8041-102d26bfe93f.png)

![image](https://user-images.githubusercontent.com/12704875/184032114-d9c3c7a1-7d11-4202-a67a-fa037e27a732.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.2.0-rc3
 - Browser and OS: Chrome on Mac

**Comment by sbishel** [comment]
If https://github.com/mattermost/focalboard/issues/3641 can't be fixed, this one doesn't matter as we will revert the feature.

**Comment by harshilsharma63** [comment]
Closing this one as we decided not to display category name in search results.
