### ISSUE TITLE
Bug: Switching between teams in boards goes to Template Picker

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#3654]
## Steps to reproduce the behavior

1. Go to TeamA, select a Board
2. Go to TeamB - note on Template picker, select a board
3. Go to TeamA - back to template picker.
4. Go to TeamB - back to template picker.

## Expected behavior
You should be able to switch between team and keep last used board.

## Edition and Platform

 - Edition:Mattermost Boards (plugin)
 - Version: 7.2.0-rc3
 - Browser and OS:  Chrome on Mac

**Comment by wuwinson** [comment]
cc @jespino Any insights to help Paul here?

**Comment by Pinjasaur** [comment]
I think this might be related to the adjacent code to #3651. Potentially just querying for `lastBoardId` and if it exists update the URL with it along with `teamId`. Might be totally wrong, though.
