### ISSUE TITLE
Bug: RHS boards list does not update for other users when board created

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#3655]
## Steps to reproduce the behavior

1. Go to any channel that has no Boards linked using two accounts and two browsers
2. Select  `Boards` icon on RHS in both browsers
3. Select `Link boards` on first browser
4. Select `Create Board` & create a board on first browser
5. Newly created board does not appear in RHS for second browser

## Expected behavior

Newly created boards appear in RHS for all users

## Edition and Platform

 - Edition: BugBash Server (plugin)
 - Version: 7.2 RC3
 - Browser and OS: Linux FF & Chrome

## Additional context (optional)

See related bug (fixed):    https://github.com/mattermost/focalboard/issues/3573

**Comment by jespino** [comment]
I think this should be fix in main, can you confirm that?

**Comment by wiggin77** [comment]
@jespino Yes this made it to the Bugbash server.  It seems to only fail if the RHS was empty for both browsers.

**Comment by wiggin77** [comment]
Hmmm.  Now I cannot reproduce.

**Comment by wiggin77** [comment]
Possibly cached client code?

**Comment by wiggin77** [comment]
Cannot reproduce after browser refresh.  May have been cached client code.

**Comment by wiggin77** [comment]
I have reproduced this again on https://boards-bugbash73.test.mattermost.cloud

**Comment by sbishel** [comment]
This appears fixed on latest - https://boards-bugbash73.test.mattermost.cloud/
(or need to somehow get in the right state to duplicate.

Tested when testing - 
https://github.com/mattermost/focalboard/issues/3824

**Comment by wiggin77** [comment]
I cannot reproduce on latest bug bash server.
