### ISSUE TITLE
Bug: Bots show up in Share Board Search

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#3656]
## Steps to reproduce the behavior

1. Go to Share on a board you are an admin
2. Type 'B'
3. Notice the user "Boards", which is a bot is available

## Expected behavior

Bots should not be displayed as users for board access.

## Screenshots (optional)
<img width="612" alt="Screen Shot 2022-08-11 at 12 17 30 PM" src="https://user-images.githubusercontent.com/12704875/184210846-7db51fd2-95d8-4607-8700-9a3f9400929c.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2.0-rc3
 - Browser and OS: Chrome on Mac,

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by wuwinson** [comment]
Check person property and @mentions - related to #3144

**Comment by Pinjasaur** [comment]
Just like in #3144, needed to `@mention` a user before able to see the `boards` bot appear. Not seeing it in the Person property or `@mention`s list.
