### ISSUE TITLE
Feature Idea: improve the RHS App Bar Boards tooltip text

### ISSUE THREAD

**Issue by Pinjasaur** [mattermost/focalboard#3659]
## Summary

Improve the RHS App Bar Boards tooltip text:

![image](https://user-images.githubusercontent.com/6335792/184213551-c8fe134f-4931-43e6-ae9b-0652225ecf79.png)

cc @justinegeffen perhaps `Toggle Linked Boards`?

## How important this is to me and why

Importance: High/Medium/Low

Use cases:
1.
2.
3.

## Additional context/similar features

I'm partial to Playbooks' usage of `Toggle`.

**Comment by wuwinson** [comment]
cc @asaadmahmood

**Comment by asaadmahmood** [comment]
Show linked boards, Hide linked boards sounds good to me too.
But we can have toggle as well.

**Comment by wuwinson** [comment]
Let's stick with `Toggle Linked Boards` for simplicity and consistency.
