### ISSUE TITLE
Bug: v7.2 tour points not matching spec/improvements

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3664]
## Steps to reproduce the behavior

1. Initiate and finish Welcome tour
2. v7.2 tour points should start right afterwards
3. Go through through the tour points
4. See expected behavior for each tour point below

#### First tour point
![Screen Shot 2022-08-11 at 4 08 25 PM](https://user-images.githubusercontent.com/93531870/184241543-57325fa1-6ac5-4fa1-992d-f4e88e63577b.png)

1. Header should display as "Sidebar categories" with a lowercase c
2. Can we cut down the copy to: "All your boards are now organized under your new sidebar. No more switching between workspaces. One-time custom categories based on your prior workspaces may have automatically been created for you as part of your v7.2 upgrade. These can be removed or edited to your preference."
3. Add "Learn more" link at the end of the copy, with link to: https://docs.mattermost.com/welcome/whats-new-in-v72.html

#### Second tour point
![Screen Shot 2022-08-11 at 4 12 10 PM](https://user-images.githubusercontent.com/93531870/184242200-bc993f03-e32a-416e-8829-e9eddec01a1e.png)
1. Header should display as "Manage categories" with a lowercase c

#### Third tour point
![Screen Shot 2022-08-11 at 4 13 01 PM](https://user-images.githubusercontent.com/93531870/184242654-b5a5caf6-5414-41b2-8e63-028e0eb0ad37.png)
1. Header should display as "Manage boards" with a lowercase b
2. Missing a period at the end

#### Final tour point
![Screen Shot 2022-08-11 at 4 50 52 PM](https://user-images.githubusercontent.com/93531870/184243531-8df54119-98fd-4192-a273-c5a589079e59.png)
1. Header should display as "Search for boards" with a lowercase "f" and "b"
2. Tour point should appear over the "Find boards" box and not on the dialog.

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2 RC3
 - Browser and OS: Chrome on Mac

**Comment by Rajat-Dabade** [comment]
Thanks for the feedback @wuwinson, I will make the suggested changes today itself. I got really confused by the `Search For Boards` tour point because now also the spec 
![Screenshot 2022-08-12 at 12 02 58 PM](https://user-images.githubusercontent.com/26198062/184297599-30f66229-4a79-4bac-92cf-b1e3fa60e35c.png)
says, `Pop over on the board switcher`, but now it's clear. Will make the changes and push them today itself.
