### ISSUE TITLE
Bug: Second character does not appear in comment 

### ISSUE THREAD

**Issue by paulpremont** [mattermost/focalboard#3667]
## Steps to reproduce the behavior

1. Open a new task
2. Add a comment or description
3. Enter "12"

## Expected behavior

"12" should appear but only "1" is appearing

## Edition and Platform

 - Edition: Personal Desktop
 - Version: 7.1.0
 - OS: Ubuntu 22.04

**Comment by wuwinson** [comment]
@paulpremont I'm not able to repro this on the latest [Personal Desktop build for Mac](https://focalboard-builds.s3.amazonaws.com/latest/focalboard-mac.zip).

Would recommend downloading our v7.3 release from our [release page](https://github.com/mattermost/focalboard/releases) when available. If you'd like an early preview you can test the [latest build for Linux](https://github.com/mattermost/focalboard/suites/8145479201/artifacts/353289665), but please note there may be stability issues. Feel free to re-open this ticket if you're still having issues. Thanks!
