### ISSUE TITLE
Bug: Link board modal does not dismiss after linking a board

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3679]
## Steps to reproduce the behavior

1. Go to link board modal from channel RHS
2. Search a board to link
3. Click on the link button
4. See error - modal is still visible after linking the board

## Expected behavior

1. The link board modal should auto-dismiss and the confirmation modal should appear as soon as user clicks on the Link button
2. If user confirms, close confirmation modal and display the recently linked board should on the RHS.
3. If user cancels, display the link board modal

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/184584720-9c8e0008-5aaf-4f8b-a8b0-afd9dc9a549c.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2 RC3
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment]
cc @asaadmahmood This currently works better for linking multiple boards, but not so much for single boards. However, I think the more common use case will be single board linking. Thoughts?

**Comment by asaadmahmood** [comment]
@wuwinson I agree I think for this as soon as the user clicks the link, we close the modal and open the confirmation dialog, and then when they confirm, we take them to the RHS.
If they cancel, we can take them back to the link boards list modal.

**Comment by wuwinson** [comment]
Thanks @asaadmahmood! Updated the expected behavior.
