### ISSUE TITLE
Bug: Duplicating a card not created by you on the ONBOARDING board throws an error but does duplicate the card

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#3680]
Found by `varghesejose2020` on `https://boards-bugbash.test.mattermost.cloud/` server. Lindy can also reproduce.

## Steps to reproduce the behavior

1. Go to `https://boards-bugbash.test.mattermost.cloud/` server > Onboarding board
2. Hover over the "Create your own board" card below the "To Do" column, click on the 3-dots and select "Duplicate"
3. Observed: Error reading "This card doesn't exist or is inaccessible" (see screenshot). Note that a duplicate card **is** created. (see 2nd screenshot for js.console error)
4. Create a new card under the "To Do" column and close the card
5. Hover over the card you just created, click on the 3-dots and select "Duplicate"
6. Observed: the card is duplicated without any error

## Expected behavior

Not sure as the cards were pre-existing on the "Welcome to Boards" board but I would expect to be able to duplicate the cards without any errors.

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/13020833/184590155-028653a5-b007-4193-9ea3-7d48e1fda6c8.png)

![image](https://user-images.githubusercontent.com/13020833/184591393-0a9bd1bb-9e2e-4880-a301-ec4f5bd8c8b0.png)

## Edition and Platform

 - Edition: Personal Mattermost Boards (plugin)
 - Version: v7.2.0
 - Browser and OS: Chrome / Windows 8.1 and 10

**Comment by wuwinson** [comment]
@lindy65 Can you repro this with any other boards? We think this might be related to bad data on @harshilsharma63's [Welcome board](https://boards-bugbash.test.mattermost.cloud/boards/team/uzkj4t1tdpfat8xywo5w8fcy9y/b6wqy1pfqkjredn6o1curber79a/vei8dum5f1ffjznz99oiacxmc9r). Does not occur on any other board - new or existing. cc @sbishel

**Comment by harshilsharma63** [comment]
Works fine for me for new boards, even for a new user. @lindy65 can you share the URL of welcome board you're referring to? There are tons of welcome board in there and duplicate board is working for me in all those boards that I have access to.

**Comment by lindy65** [comment]
Thanks @wuwinson and @harshilsharma63 - I could repro this only on the Welcome Board on the `https://boards-bugbash.test.mattermost.cloud/` server

Try duplicating [this card](https://boards-bugbash.test.mattermost.cloud/boards/team/uzkj4t1tdpfat8xywo5w8fcy9y/b6wqy1pfqkjredn6o1curber79a/vei8dum5f1ffjznz99oiacxmc9r/c4i4g453kmtyd8kcy9zzs39pd4e) Harshil.  I get the error every time.

**Comment by lindy65** [comment]
Not sure whether this makes a difference @harshilsharma63 but you're an admin on the board

![image](https://user-images.githubusercontent.com/13020833/184815336-6f1188f3-5dee-4a3d-9d90-74b28add62ea.png)

**Comment by lindy65** [comment]
Thanks @wuwinson - I'm not able to repro on other boards at present but will keep an eye open and re-open if necessary.
