### ISSUE TITLE
Bug: macOS Boards App using AWS build shows a blank screen

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#3683]
Using the AWS macOS URL to install the Boards app gives a blank screen - either on trying to open the app or after selecting a template.  (URL: https://focalboard-builds.s3.amazonaws.com/latest/focalboard-mac.zip)

See [this convo](https://community.mattermost.com/core/pl/w51u7twjgpgktntyyhr76qbiia) for more context

## Steps to reproduce the behavior

1. Download the macOS using the AWS URL: https://focalboard-builds.s3.amazonaws.com/latest/focalboard-mac.zip
2. Install and run the app
3. Observed: Lind and Paul saw a blank screen after selecting a template to use. Winson got a blank screen just trying to open the app

## Expected behavior

No error on trying to open the app or after selecting a template to use

## Edition and Platform

 - Edition: Personal Desktop
 - Version: v7.3.0 (main/master)
 - Browser and OS: macOS/Safari

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround

**Comment by wuwinson** [comment]
@Pinjasaur Can you also check if this is happening on v7.2? Thanks! cc @sbishel

**Comment by Pinjasaur** [comment]
Tested locally off of `release-7.2` in `single-user` mode and am able to reproduce the behavior I was setting from the AWS build zip. I'll need to dig in more, but I think it has to do with the teamId and how the default `0` is used.
