### ISSUE TITLE
Bug: unable to edit/delete a template in personal server/desktop

### ISSUE THREAD

**Issue by Pinjasaur** [mattermost/focalboard#3695]
## Steps to reproduce the behavior

1. Go to the template selector in personal server or desktop
2. Create a new custom template
3. Go back to the template selector and notice you cannot edit/delete your custom template

## Expected behavior

Be able to edit/delete a custom template.

## Screenshots (optional)

Personal Server:

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/6335792/184999250-bbefc330-a691-43de-95f6-5aa278b67f36.png">

Personal Desktop:

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/6335792/184999925-3c8935c9-9f6c-4a8d-a3be-3639f4dfeead.png">

## Edition and Platform

 - Edition: Personal Desktop / Personal Server
 - Version: main
 - Browser and OS: FF104 Mac

## Additional context (optional)

Looking at the code, we're doing a conditional to see if the template belongs to the `globalTeamId` of `0` which we use for the builtin templates, but it's also the team used on personal server & desktop.

https://github.com/mattermost/focalboard/blob/393b961a6b6bce0d8e60f74f7beae14b407dfdbb/webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.tsx#L46-L47

**Comment by Pinjasaur** [comment]
@wuwinson can you confirm that this in a bug? if it's not and I'm simply mistaken, please close. thanks!

**Comment by Pinjasaur** [comment]
> @Pinjasaur Definitely a bug and very similar to what we saw on plugin a few releases ago on #3061

Aha, that's why it felt so familiar...

**Comment by wuwinson** [comment]
cc @sbishel
