### ISSUE TITLE
Feature Idea: enlarge images on click

### ISSUE THREAD

**Issue by AuspeXeu** [mattermost/focalboard#3699]
## Summary

Since images might be difficult to read, it would be great to enlarge them when clicking on them.

## How important this is to me and why

Importance: Medium

**Comment by wuwinson** [comment]
Thanks for the feedback @AuspeXeu! We have this enhancement tracked on line item #1 on https://github.com/mattermost/focalboard/issues/2467. Closing out this ticket as a dupe.
