### ISSUE TITLE
Feature Idea: Add button to clear a select property

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#370]
**Summary:**
It's not clear how to clear a select property, and set its value to "Empty"

**Steps to reproduce the behavior:**
1. Click on a select property (in a card view or table view, etc.)
2. What do you click on to clear it?

**Expected behavior:**
There's a button to clear the value

**Screenshots:**
<img width="217" alt="Select picker" src="https://user-images.githubusercontent.com/46905241/116787628-ef633680-aa59-11eb-81f2-1118ea507983.png">

**Platform:**
 - Chrome 89 on macOS 10.15.17

**Additional context:**
You can press Delete to clear the select, but this is not discoverable.

**Comment by chenilim** [comment]
There might be a simple option for this in the standard control we use.

**Comment by Johennes** [comment]
react-select provides a clear button but the indicator container is currently [hidden](https://github.com/mattermost/focalboard/blob/main/webapp/src/widgets/valueSelector.tsx#L95). If the default look is acceptable, we'd just have to tweak the CSS a little to make it show next to the label like in this quick hack:

![Screenshot 2021-05-02 at 20 47 42](https://user-images.githubusercontent.com/1137962/116823926-a6110500-ab87-11eb-9740-b76341e85d1c.png)
