### ISSUE TITLE
Bug:  White page and DOMException

### ISSUE THREAD

**Issue by b-m-f** [mattermost/focalboard#3712]
## Steps to reproduce the behavior

Directly after Login

## Expected behavior
Get to overveiw

## Screenshots 
![Screenshot from 2022-08-19 18-04-57](https://user-images.githubusercontent.com/2843450/185679025-2a3cf671-2d59-44b8-a404-d1d1c5a6e9a8.png)

## Edition and Platform

 - Edition: Personal Server
 - Version: Dockerfile 7.2.0
 - Browser and OS: Chromium & Firefox on Linux

## Additional context (optional)

Works fine when downgrading back to 7.1.0

**Comment by wuwinson** [comment]
@Rajat-Dabade Can you please investigate? Thanks! cc @sbishel

**Comment by Rajat-Dabade** [comment]
@b-m-f, I have tried to reproduce this issue but it seems that is it working completely fine for me.

https://user-images.githubusercontent.com/26198062/186087038-a2b0903b-e22f-48d0-980e-de90fd1bcc01.mov

Can you please provide some more details regarding this if the issue still exists? Thanks.

**Comment by b-m-f** [comment]
Hey @Rajat-Dabade ,

first of all thank you for the super fast response.

I have dug deeper and found a misconfiguration in the reverse proxy setup.

`Upgrade: websocket`

was missing as a header.

For some reason **7.1** was able to still reach the dashboard whereas in **7.2** the above error occurs.

Now that the proxy setup is fixed everthing runs smooth. Thank you for the support!
