### ISSUE TITLE
Bug: Fail to import Jira to board (500 error)

### ISSUE THREAD

**Issue by MingSwivel** [mattermost/focalboard#3728]
## Steps to reproduce the behavior

1. Followed https://docs.mattermost.com/boards/data-and-archives.html#import-from-jira
2. Failed import (500) 

## Expected behavior
Import successfully.

## Screenshots (optional)
<img width="247" alt="CleanShot 2022-08-24 at 00 27 03@2x" src="https://user-images.githubusercontent.com/88298938/186211610-4edb10c7-17cd-4822-bcb4-8b2b8b234af2.png">

## Edition and Platform
7.2.0

**Comment by MingSwivel** [comment]
Is it `.focalboard` or `.boardarchive` ?

**Comment by MingSwivel** [comment]
Hi @sbishel,

I just imported the Jira (`archive.boardarchive`) again. I can see this error via browser console.
![CleanShot 2022-08-31 at 10 18 54@2x](https://user-images.githubusercontent.com/88298938/187578326-1f035621-efeb-4168-92eb-35a4f7b2c687.png)

@mioatswivel Can you share the backend error log in docker?

Thanks.

**Comment by MingSwivel** [comment]
<img width="571" alt="CleanShot 2022-08-31 at 10 23 06@2x" src="https://user-images.githubuserconte
<img width="573" alt="CleanShot 2022-08-31 at 10 23 57@2x" src="https://user-images.githubusercontent.com/88298938/187578873-2eb973c1-33cc-4662-98be-0d8a3d87b6ec.png">
nt.com/88298938/187578736-e3b207f0-46d0-43de-a752-1dc2fc06e096.png">

FYI.

**Comment by wuwinson** [comment]
Thanks @MingSwivel. Can you share the server error log as well? Thanks! cc @sbishel

**Comment by MingSwivel** [comment]
`{"timestamp":"2022-09-07 10:08:04.132 +08:00","level":"error","msg":"API ERROR","caller":"app/plugin_api.go:975","plugin_id":"focalboard","code":"500","error":"\"unsupported archive line type; got board, line 2\"","_msg":"","api":"/api/v1/workspaces/xxxxxxxxxxxxxxxxxxxxx/archive/import"}`
@wuwinson

**Comment by MingSwivel** [comment]
Did anyone try to export and import Jira into Boards? The content format seems wrong.

**Comment by hoellmet** [comment]
Seems like my error with asana import:
https://github.com/mattermost/focalboard/discussions/3784

**Comment by MingSwivel** [comment]
Is it JSONL?
I found the Jira export is sth cannot be opened. Sadly.
Hope someone fixes it soon.

**Comment by wiggin77** [comment]
@MingSwivel I am unable to reproduce this error following the instructions in the link you posted, I exported a XML from Jira, converted to a `.boardarchive file` using `npx ts-node importJira.ts -i ./my_jira_export.xml -o archive.boardarchive`, and then I imported to a new Board.  All the tickets were imported.

The error reported `unsupported archive line type; got board, line 2` is something that was fixed a last spring via https://github.com/mattermost/focalboard/pull/2578 and https://github.com/mattermost/focalboard/pull/2700 and https://github.com/mattermost/focalboard/pull/2704 .   Specially the error states that a JSONL record containing `"type"="board"` has an invalid type. The first two lines of the archive I just imported are:
```
{"version":1,"date":1666114620447}
{"type":"board","data": ...
```
This suggests you used an older `/import/jira` script which didn't support the "board" record type.  Can you try again with the latest main?  The key is to run `npx ts-node importJira.ts -i ./my_jira_export.xml -o archive.boardarchive` with the latest version of `/import/jira`

**Comment by MingSwivel** [comment]
Yes. I can import now. Thank you.
