### ISSUE TITLE
UI Regression: dialog/modal styling 

### ISSUE THREAD

**Issue by Pinjasaur** [mattermost/focalboard#3744]
@asaadmahmood it appears there's some CSS regression from #3713, specifically the top/toolbar part of dialogs/modals

![image](https://user-images.githubusercontent.com/6335792/186738356-1e3bfe44-ffe3-4da3-bffb-83356b47373c.png)

![image](https://user-images.githubusercontent.com/6335792/186738383-79c85dce-a5c7-43b0-a9a5-6862c565a769.png)

**Comment by sbishel** [comment]
Appears to have been fixed by https://github.com/mattermost/focalboard/pull/3835 - tested on latest https://boards-bugbash73.test.mattermost.cloud
