### ISSUE TITLE
Bug: `@mention` not filtering in private boards

### ISSUE THREAD

**Issue by Pinjasaur** [mattermost/focalboard#3746]
## Steps to reproduce the behavior

1. Go to a private board and start typing e.g. comment to mention someone
2. Notice it doesn't filter as you type

## Expected behavior

Users to filter as typing.

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/6335792/186743889-c8f06d55-0966-46b0-929a-dc51c480880b.png)

## Edition and Platform

 - Edition: Personal Desktop / Personal Server / Mattermost Boards (plugin)
 - Version: [e.g. v0.15.0]
 - Browser and OS: [e.g. Chrome on Mac, Edge on Windows]

## Additional context (optional)

Might be related to `synthetic` members through associated channels.

**Comment by Pinjasaur** [comment]
@sbishel lmk your findings, #2604 has some related work I need to do for Guest users, so there may be overlap

**Comment by wuwinson** [comment]
Might potentially be resolved with the [@mention autocomplete](https://docs.google.com/document/d/1IiIgtXI_lYtTSpm6XfqPvSe_jD0E0rajqerWSRLC6OQ/edit?usp=sharing) feature @jespino worked on. Can verify after it's been merged.

**Comment by wuwinson** [comment]
Waiting on #3724 before testing.

**Comment by wuwinson** [comment]
Confirmed this is fixed on v7.3 Bug Bash server. Users are filtered as you type on both private and public boards, and we also indicate which users are not explicit board members. Closing out.
