### ISSUE TITLE
Bug?: No page is shown only in Chrome

### ISSUE THREAD

**Issue by mzch** [mattermost/focalboard#3749]
## Steps to reproduce the behavior

1. Update focalboard using `focalboard-server-linux-amd64.tar.gz`.
2. Start Focalboard.
3. Visit Focalboard page via Google Chrome.
4. See no page.

## Expected behavior

See Login page.

## Screenshots (optional)

<img width="1513" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/186823197-81c56735-ced4-40fb-8d77-9b158e9c5784.png">

## Edition and Platform

 - Edition: Personal Server
 - Version: v7.2.1
 - Browser and OS: Chrome 104.0.5112.101 on macOS 12.5.1

## Additional context (optional)

I can see the login page by using Safari `15.6.1`, Firefox `104.0`, Brave `1.42.97 Chromium: 104.0.5112.102` and Vivaldi `5.4.2753.40`

**Comment by kamre** [comment]
Looks similar to this one that was recently fixed:
 - #3589

**Comment by wuwinson** [comment]
Fixed with #3718. Can you try it out with the latest main? If it's still an issue, feel free to re-open. Thanks!
