### ISSUE TITLE
Bug: Cannot start installation of Focalboard Personal on MacBookPro

### ISSUE THREAD

**Issue by Natedi** [mattermost/focalboard#3752]
## Steps to reproduce the behavior

1. Go to App Store
2. Select Install
3. Click "Open"
4. See nothing happens

## Expected behavior:
Typical installation should happen

Blank window opens and that it

## Edition and Platform

 - Edition: Personal Desktop
 - Version: Current - from Apple App Store (0.15.2)
 - My Mac configuration:

 Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,1
  Chip:	Apple M1 Pro
  Total Number of Cores:	10 (8 performance and 2 efficiency)
  Memory:	16 GB
  System Firmware Version:	7459.141.1
  OS Loader Version:	7459.141.1

**Comment by wuwinson** [comment]
@Natedi I'm on an M1 MacBook Pro and wasn't able to repro this issue and haven't received any reports from the App Store. Have you tried uninstalling and reinstalling? @ogi-m Any issues on your end?

If it's still not working, have you considered using our [Cloud Starter plan](https://mattermost.com/pricing/) which is also free?

cc @sbishel

**Comment by ogi-m** [comment]
@wuwinson I don't have macOS but I've asked @jgilliam17 to try and she's able to install without issue

**Comment by Natedi** [comment]
@wuwinson 
I did try to uninstall and install it before, but repeated it again today and got the same problem.
Here is everything in details and some screenshots.
1. Went to Apple Store clicked on a little cloud with arrow -> see a little circle with progressing download indication.
2. A possible issue (?) -> I do not see the file in my "Downloads" folder and if I search for it, I find it in "Applications" folder.
3. Attached screenshots are file info, package content (just a couple more files at the bottom didn't fit into screenshot) and that empty window which I get when clicking on the file.
<img width="396" alt="FileInfo" src="https://user-images.githubusercontent.com/77253394/187576603-48f6ef5f-d54f-49f8-93cf-30b13cd4b862.png">
<img width="831" alt="Nothing" src="https://user-images.githubusercontent.com/77253394/187576610-5297055d-3575-4f5c-97bb-0e0fc9db3b0f.png">
<img width="883" alt="PackageContent" src="https://user-images.githubusercontent.com/77253394/187576624-fe7e72a6-8dfb-4679-87b0-23dbb8c07a1a.png">

**Comment by Natedi** [comment]
@wuwinson Yes, I'll check the "cloud starter", thanks

**Comment by Natedi** [comment]
Just to note,
I use a brand new Mac - literally a few days from physical local Apple Store (not resellers of any sorts) and if I look at the screen shot of file info, in the "sharing and permissions" section, I see this "Wheel" thing. First of all, I don't know why it says "you have custom access", because I don't believe I've changed any default system settings and secondly, I have no idea what that "wheel" user is. The "wheel" is NOT the admin user name I have created during the setup. Is that an OS thing, or what...

Another thing, and this is probably/possibly on a separate note - I can't download anything into "Downloads" folder for some reason right now (not even a photo attached to email), while I did recently (...installed browsers and other apps)...

...I am beginning to have a feeling that I am unintentionally wasting your precious time, deal developers, and I should just do a "hard reset" of my notebook.

Yay or Nay?
:o(

**Comment by wuwinson** [comment]
@Natedi Thanks for the details, we're not too sure what's going on here, but would recommend sticking with the Cloud Starter version until we release a new mac version in the future. Going to close out this issue, but feel free to re-open if you have other issues. Thanks!
