### ISSUE TITLE
Bug: Board view dropdown menu fly out of the window

### ISSUE THREAD

**Issue by MioAtSwivel** [mattermost/focalboard#3753]
## Steps to reproduce the behavior

1. Create or access a board
2. Click on the dropdown menu to change / add view
3. Half of the menu flew out of window

## Expected behavior

The dropdown menu should drop *down* instead of flying up and away form the visible view

## Screenshots (optional)

![CleanShot 2022-08-29 at 12 25 20](https://user-images.githubusercontent.com/102662641/187122845-c4f0be81-5cab-4ab3-be00-deea70c56710.png)

## Edition and Platform

 - Edition: Mattermost Teams, both web version and native client / Mattermost Boards (plugin)
 - Version: Board v7.1.0 on mattermost 7.1.3
 - Browser and OS: [e.g. Chrome on Mac, Edge on Windows]

## Additional context (optional)

There seems to have no workaround on getting the menu back without going into F12 and inject my own css, while more than half of the functins inside the menu is inaccessible due to this issue

**Comment by sbishel** [comment]
fixed via https://github.com/mattermost/focalboard/pull/3251
