### ISSUE TITLE
Bug: Search icon misaligned

### ISSUE THREAD

**Issue by jespino** [mattermost/focalboard#3768]
## Steps to reproduce the behavior

1. Go to any board
2. The search input icon is misaligned

## Expected behavior

The search icon is properly aligned

## Screenshots (optional)

![imagen](https://user-images.githubusercontent.com/290303/187874941-2ffe2db0-833a-47ea-86fd-065b918706ef.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.3
 - Browser and OS: Firefox

**Comment by ankit-tiple** [comment]
Can I work on this issue? @jespino
