### ISSUE TITLE
Bug: Guests can access boards linked to a channel

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3771]
## Steps to reproduce the behavior

1. Invite a guest to a channel
2. Link boards to the same channel
3. Login as the guest
4. Go to the channel and click on the boards linked on the channel
5. See error - guest is able to access those boards even though they're not an explicit member

## Expected behavior

Guests should not have access any board unless they were added as an explicit member. See [this thread](https://community.mattermost.com/private-core/pl/dpw8uj3dbpdsijdobueacp7kyc) for reference.

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/188013397-d4bc393e-b5ca-40e7-9d2c-bae016aa9b68.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.3
 - Browser and OS: Chrome on Mac

**Comment by Pinjasaur** [comment]
@wuwinson should the Linked Channels RHS in Channels be rendered for a Guest user at all then?

**Comment by wuwinson** [comment]
@Pinjasaur Only for the boards where they are an explicit member. Other boards should be hidden.

**Comment by Pinjasaur** [comment]
While testing this locally I realized that this should probably apply to the Search Boards modal, too. Currently a guest can search for a board they are an implicit member of via a channel association. Is that correct @wuwinson?

**Comment by wuwinson** [comment]
Good catch! Yep, guests should not be able to search for any boards they're not an explicit member of.

**Comment by Pinjasaur** [comment]
> Good catch! Yep, guests should not be able to search for any boards they're not an explicit member of.

cc @sbishel
