### ISSUE TITLE
Latest main - unable to create board from template with images

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#3773]
Getting following error when trying to create board with template with images in it -

```
{"timestamp":"2022-09-02 05:14:39.677 Z","level":"error","msg":"InitializeTemplates failed","caller":"app/plugin_api.go:975","plugin_id":"focalboard","error":"\"cannot initialize global templates for team 0: cannot import file 76fwrj36hptg6dywka4k5mt3sph.png for board bbn1888mprfrm5fjw9f1je9x3xo: unable write the data in the file g3kcuwxxat8sjgw57cpseq6rpe/0/b8orpp4yz3jg588655khfydhjba/76fwrj36hptg6dywka4k5mt3sph.png: context deadline exceeded\""}
```

Server URL - https://harshil-mysql-test-6.test.mattermost.cloud/team-a/channels/off-topic

Server invite link in Focalboard internal channel

**Comment by sbishel** [comment]
Seems to work fine on 7.3 but can't get it to work with main, even going back prior to 7.3. release date. Can't duplicate locally, not sure if it is due to code or not.

**Comment by sbishel** [comment]
Also receive the error "Unable to upload image. FileSize limit reached."
