### ISSUE TITLE
Feature Idea: export board archive in the side bar context menu

### ISSUE THREAD

**Issue by kamre** [mattermost/focalboard#3776]
## Summary

Currently it is possible to export board archive via board view options menu:
<img width="396" alt="image" src="https://user-images.githubusercontent.com/5587620/188308194-4e3fa01e-4a0a-4ee3-9a29-b9c1242c12b0.png">

This action can also be added to the side bar context menu:
<img width="241" alt="image" src="https://user-images.githubusercontent.com/5587620/188308249-f39e404a-2a52-4986-adaa-b5508338a413.png">

## How important this is to me and why

Importance: Low (nice to have, logically this export is for the board and not just board view)

@asaadmahmood what do you think?

**Comment by asaadmahmood** [comment]
Makes sense @kamre

**Comment by sbishel** [comment]
@wuwinson?  We can open for Hacktoberfest?

**Comment by wuwinson** [comment]
Thanks @kamre @sbishel! Let's add the "Export board archive" option below the "New template from board" option for the ... menu next to each board on the sidebar. Button should behave exactly the same as from the boards view. Asaad is out for a few weeks, but please see my hacked together mockup for reference:

![Screen Shot 2022-09-29 at 5 16 08 PM](https://user-images.githubusercontent.com/93531870/193148681-496fa73a-869c-47d8-9ec0-ab10715251de.png)

Icon attached - will need to be recolored to match the other icons on the menu:
<img width="38" alt="icon-export-variant" src="https://user-images.githubusercontent.com/93531870/193148826-67e63409-39c2-4f3a-b3f7-ea096e4a994c.png">

**Comment by cannalee90** [comment]
Could you assign this issue for me?

**Comment by kamre** [comment]
@wuwinson there is a corresponding Compass icon that can be used like this:
```ts
export default function ExportIcon(): JSX.Element {
    return (
        <CompassIcon
            icon='export-variant'
            className='ExportIcon export-variant'
        />
    )
}
```
Will look like this:
![Screenshot 2022-10-03 at 09 58 31](https://user-images.githubusercontent.com/5587620/193494023-f4713df8-7815-4b5f-ab8c-3ff6298ca045.png)

**Comment by wuwinson** [comment]
Perfect, thanks @kamre! @cannalee90 you got it!
