### ISSUE TITLE
Feature Idea: Update confirmation message to account for Guest Accounts when linking boards to a channel

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3785]
## Summary

When linking a board to a channel, Guest accounts from the channel are not automatically granted access to the board. The board admin should be informed of this so they know who will be getting access to their board.

The copy on the 4 confirmation messages below need to be updated to:

>When you link a channel to a board, all members of the channel (existing and new) will be able to edit it. This excludes members who are guests

See [thread](https://community.mattermost.com/private-core/pl/dpw8uj3dbpdsijdobueacp7kyc) for reference.

## How important this is to me and why

Importance: Medium

Use cases:
#### Boards share dialog
1. Linking a channel to the board
![Screen Shot 2022-09-06 at 5 03 44 PM](https://user-images.githubusercontent.com/93531870/188738282-df41b216-f5d0-4f2d-8c8a-9b12c100f1e5.png)

2. Linking another channel to the same board
![Screen Shot 2022-09-06 at 5 03 25 PM](https://user-images.githubusercontent.com/93531870/188738673-a65c15f9-e3c1-4d6d-826c-af75d4cd5407.png)

#### Channel RHS Link Boards dialog
1. Linking a board to the channel
![Screen Shot 2022-09-06 at 5 04 31 PM](https://user-images.githubusercontent.com/93531870/188738938-a73d8413-f5d7-4554-ba3e-3da9be20ddcf.png)

2. Linking a board that is already linked to another channel
![Screen Shot 2022-09-06 at 5 04 50 PM](https://user-images.githubusercontent.com/93531870/188738961-443e57ca-ddf2-4563-9660-928165897743.png)

**Comment by wuwinson** [comment]
cc @justinegeffen @asaadmahmood @Pinjasaur for input.

**Comment by Pinjasaur** [comment]
If we're able to keep it identical for all 4 modals that'll simplify the i18n/translation aspect of it.

Perhaps:

> all members of the channel (existing and new) _**except guests**_

0/5 otherwise

**Comment by wuwinson** [comment]
@justinegeffen Any updates on the copy for this? Thanks!

**Comment by wuwinson** [comment]
Thanks @justinegeffen! @sbishel @Pinjasaur The text has been finalized.

**Comment by Pinjasaur** [comment]
I'll plan on getting it in for #3786.
