### ISSUE TITLE
Bug: boards not loading

### ISSUE THREAD

**Issue by AuspeXeu** [mattermost/focalboard#3788]
## Steps to reproduce the behavior

![image](https://user-images.githubusercontent.com/2115696/188803537-9276658d-b403-4d56-934d-add62373b154.png)
![image](https://user-images.githubusercontent.com/2115696/188824459-1f9c5a1e-4b11-488a-9f81-290033218f1b.png)

## Edition and Platform

 - Edition: Personal Server (docker)
 - Version: v7.2.0
 - Browser and OS: Firefox, Chrome, Edge - Windows 10

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround

**Comment by mgdelacroix** [comment]
Hi @AuspeXeu! Can you please post the URL that you're trying to access when the error happens and the sequence of requests on the Network tab to see what is happening at a request level?

It would be ideal if you could attach one sequence from a successful load and another one from a failing one.

**Comment by AuspeXeu** [comment]
The url is just the base url like `https://boards.example.com` which then gets changed to `https://boards.example.com/b1qicbkfdz3ge8k7rs7kywhydxr` in my particular case.

First the sequence of call of a failing load:
![image](https://user-images.githubusercontent.com/2115696/189898419-976b19a3-b9b6-4086-9d8f-884f00e74eb6.png)

And a successful load:
![image](https://user-images.githubusercontent.com/2115696/189898767-a8d56967-f274-426b-affb-b50643fd1f9f.png)

Hope this helps. Let me know if you need more information.

**Comment by mgdelacroix** [comment]
Nothing seems to be failing on those request chains. The error happens in all boards and views or is it one specifically that fails? If that is the case, what's the type of view that causes the error? (as in Kanban view, Table view, etc) Is there anything that triggered these errors initially? Any action, update or change?

**Comment by AuspeXeu** [comment]
It fails on the initial page load of the focalboard server instance. Not any particular board. I cannot even get to any view since the screen just remains blank.

**Comment by mgdelacroix** [comment]
Thanks for all the information :) Is it a fresh instance? How does it behave from an incognito window?

**Comment by AuspeXeu** [comment]
Same issue for an incognito window unfortunately. I'll try with a fresh instance as well, I would assume that I should import my existing database to simulate a real-world case?

**Comment by mgdelacroix** [comment]
I see. You could try with a new instance and import your DB, but I don't think it would help. You were using the tool before then, when did it start to fail? did you update the server or do any action while using it that you could think of as the starting point of the failures?

**Comment by AuspeXeu** [comment]
Oh, it was definitely not present prior to version `7.1.2`. After that upgrade it started failing.

**Comment by mgdelacroix** [comment]
Could you please reach me on https://community.mattermost.com to talk synchronously? My username is `miguel.delacruz` there

**Comment by AuspeXeu** [comment]
It seems like our nginx reverse proxy in front of the docker image is causing the issue since directly exposing port 8000 of the docker image works without problems. We're actually using the nginx configuration of the official documentation: https://www.focalboard.com/download/personal-edition/ubuntu/

**Comment by mgdelacroix** [comment]
An interface flick behind the proxy was causing the websocket to send a command in between component mount and unmounts, after the client was closed, and the resulting error was making the interface crash.

https://github.com/mattermost/focalboard/pull/3858 catches websocket errors, logging them and preventing the crash.

Thanks a ton @AuspeXeu for your time and your help debugging this tricky situation!
