### ISSUE TITLE
Bug: Multiperson property failed in kanban view.

### ISSUE THREAD

**Issue by Rajat-Dabade** [mattermost/focalboard#3789]
## Steps to reproduce the behaviour

1. Create a board.
2. Create at least 2 cards.
3. Open a card and add the multiperson property and add a value to the multiperson property only to one of these cards.
5. Close the card and in the header - properties - check the multiperson property. 
6. See an error

## Expected behaviour

The multiperson should show in the close kanban card.

## Screenshots (optional)

https://user-images.githubusercontent.com/26198062/188825482-557d353c-0c8c-46ee-ac45-732ed1fcb94b.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.3
 - Browser and OS: [e.g. Chrome on Mac, Edge on Windows]

**Comment by harshilsharma63** [comment]
@Rajat-Dabade the board crash is fixed but the UI looks funny when adding too many users in the property-

![Uploading Screenshot 2022-09-12 at 11.29.40 AM.png…]()

ccing @asaadmahmood  for thoughts
