### ISSUE TITLE
Property type: Date

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#38]
Add a date property type
P2: Add date picker UI

**Comment by harshilsharma63** [comment]
@Johennes we can use [React Day Picker](https://react-day-picker.js.org) which is what we already use in Mattermost.

**Comment by Johennes** [comment]
Ah nice. I'll give that a try.

**Comment by Johennes** [comment]
I pushed up a first attempt in #391.

**Comment by harshilsharma63** [comment]
@Johennes that's awesome 👍 Just did a high-level review and it looks pretty good. Will do a deeper code review on it.

**Comment by alerque** [comment]
This issue appears to be stale, my Focalboard has had a date property for the last 2 versions at least.
