### ISSUE TITLE
Bug: Language changed unexpectedly, now EN not available. 

### ISSUE THREAD

**Issue by mawanthad** [mattermost/focalboard#3802]
My language automatically change to another language suddenly. But now when I am trying to change the language ENGLISh is not there in the list. Can you please check this.

**Comment by wuwinson** [comment]
@mawanthad We're not able to reproduce this issue on Community, can you provide more details on how you ran into this issue along with information on your OS version and edition, MM Boards edition, and screenshots/recordings. Thanks!

**Comment by mawanthad** [comment]
It is windows 10 64 bit and it suddenly appears.

**Comment by wuwinson** [comment]
Thanks @mawanthad! In that case, we'll close out this ticket. Please feel free to re-open if it's still an issue. Thanks!
