### ISSUE TITLE
Bug: Unable to find boards to link to a channel

### ISSUE THREAD

**Issue by hmhealey** [mattermost/focalboard#3805]
## Steps to reproduce the behaviour

1. In Channels, click on the Boards icon in the App Bar
2. Click on the "+ Add" button if the channel already has boards or "Link boards to ~" if the channel doesn't
3. In the modal that pops up, enter the name or partial name of another channel

## Expected behaviour

The channel is displayed

## Screenshots (optional)

In this example, there's a Web Platform OKR Planning board I wanted to link to this channel. No matter what board name I entered, I wasn't able to get any results.

![Screen Shot 2022-09-08 at 10 48 41 AM](https://user-images.githubusercontent.com/3277310/189164566-05d2591c-6734-4b62-b8b1-4317f7147388.png)

There were no errors in the JS console either.

## Edition and Platform

 - Edition: Mattermost Boards plugin on community.mattermost.com
 - Version: v7.2.1

**Comment by hmhealey** [comment]
That's not the case for the board that I wanted to link, but I also wasn't able to see boards that I'd previously created. myself. The other one I was looking for was on another team though if that's relevant.

More specifically, I was in the Web Platform channel on the private team on community, and I was trying to link a board that Pantelis created a couple weeks ago. I wasn't able to see a board that I created earlier this year on the public team either though.

**Comment by wuwinson** [comment]
@hmhealey The board needs to be in the same team as the channel, and you'd need to be a board admin to see the board in your search results when linking boards. Can you confirm if that's the case? Happy to chat about this in Mattercon as well.

**Comment by hmhealey** [comment]
Oh, I see. I didn't realize those were requirements. In retrospect, the team thing makes sense with Boards now having the team sidebar, but I didn't know there was such a thing as a board admin.

I can close this then unless me not understanding how that's supposed to work is something you'd want to track.

**Comment by wuwinson** [comment]
Thanks for confirming @hmhealey! We also updated our [Help Docs](https://docs.mattermost.com/boards/navigate-boards.html#navigate-boards) to cover the latest changes. Going to close out this ticket, but please feel free to reach out on the [Focalboard Community](https://community.mattermost.com/core/channels/focalboard) channel and/or file an [enhancement idea](https://github.com/mattermost/focalboard/issues/new?assignees=&labels=Enhancement&template=enhancement.md&title=Feature+Idea%3A+) if you have any feedback. Thanks!
