### ISSUE TITLE
Bug: Multi-Person member doesn't display if removed.

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#3809]
I"m not sure if this is bug or the proper functionality, but currently doesn't feel right.

## Steps to reproduce the behavior

1. Create a Multiple Person property
2. Add multiple members to the property
3. Remove one of the members from the board
3a - Either unlink a channel
3b - Or delete explicit membership
4. Member is no longer displayed in multi person property.

5. Add member back to board, either explicit or implicit.
6. Member is once again displayed in the multi-person property.

## Expected behavior

I'm not sure, but having a property appear to change when changing access doesn't seem right.

## Edition and Platform

 - Edition:  Mattermost Boards (plugin)
 - Version: [7.3.0-rc1]
 - Browser and OS: [Chrome on Mac]

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by wuwinson** [comment]
Related to https://community.mattermost.com/boards/team/qghzt68dq7bopgqamcnziq69ao/b4ctmm917q3rzdfi451qtuxjzcw/vuswsftt1rb873datosmmbtwkpa/cuqoz5pbr17rzjjk8o88axgiscc

**Comment by sbishel** [comment]
Closing, as won't fix
