### ISSUE TITLE
Bug: Shard Board role selector has misplaced check mark.

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#3810]
## Steps to reproduce the behavior

1. Go to Share Board modal
2. Click on role selector
3. Observe check mark misaligned

## Expected behavior

Check mark in correct position

## Screenshots (optional)

![check-mark-wrong](https://user-images.githubusercontent.com/5024605/189200516-05fa9b2b-5a45-44fa-b31c-d8e93c457bbe.png)

## Edition and Platform

 - Edition: Bugbash 7.3 
 - Version: 7.3
 - Browser and OS: Linux, Firefox 104.0.2

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by wuwinson** [comment]
Re-opening - Still occurring on both the team role dropdown and explicit member dropdown, although slightly differently.

![Screen Shot 2022-09-15 at 7 06 03 PM](https://user-images.githubusercontent.com/93531870/190523763-9848fe9c-1251-430d-b248-7e6e8898d5f4.png)
![Screen Shot 2022-09-15 at 7 06 10 PM](https://user-images.githubusercontent.com/93531870/190523766-39d44b50-e30f-48a2-8965-1c0b7266cd84.png)

**Comment by asaadmahmood** [comment]
@wuwinson I don't think there has been a realse for this yet. Did you check this on master?

**Comment by wuwinson** [comment]
Thanks @asaadmahmood! Not sure what was happening yesterday... but looks good now!
