### ISSUE TITLE
Bug: User with Commenter role gets error accessing card

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#3811]
## Steps to reproduce the behavior

1. Set team members to be "commenter" on a board
2. Search and select the board as a member of that team.
3. Attempt to open a card.

## Expected behavior

User should be able to access the card as a commenter
## Screenshots (optional)
<img width="833" alt="Screen Shot 2022-09-08 at 12 45 29 PM" src="https://user-images.githubusercontent.com/12704875/189201792-54656c13-fb6a-4833-8138-b48af5b9db97.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: [7.3.0-rc1]
 - Browser and OS: [e.g. Chrome on Mac]

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by jespino** [comment]
I'm not able to reproduce this locally, can we check it again?

**Comment by sbishel** [comment]
I can't duplicate even on the bug bash server which is where I produced it before. I was switching between several roles, so I'm not sure exactly how to duplicate. Closing for now.
