### ISSUE TITLE
Bug: infinite error redirect loop

### ISSUE THREAD

**Issue by Pinjasaur** [mattermost/focalboard#3812]
## Steps to reproduce the behavior

1. Go to a board with a view that causes an error `Boards: Sprints` in https://boards-bugbash73.test.mattermost.cloud/boards/team/emkcjitr1jfs5nzhntbj6dzztr/bcic7hnpf1bnf8x9b6hnxqhqmpc/v51b4fn1f7brfxkfk49cwzzndnr
2. Attempt to select the same error view again
3. Observe error redirect loop (1+ minute) 

## Expected behavior

Not stuck in error redirect loop.

## Screenshots (optional)

https://user-images.githubusercontent.com/6335792/189202768-6db8d989-cb59-4a87-a141-59698e4dd547.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: bugbash 7.3
 - Browser and OS: FF105 Mac

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by wiggin77** [comment]
May be happening on community as well:  https://community.mattermost.com/private-core/pl/humyg56q87g7brrx9uboqtj8dh

**Comment by harshilsharma63** [comment]
@wuwinson @Pinjasaur this was fixed by #3793 I've uploaded lagtest 7.3 with the patch on bugbashs server. Please give it a go.

**Comment by Pinjasaur** [comment]
Just did some testing and it appears resolved. My concern is still that our error handling was allowing the recursive `/boards` appending. That doesn't have to be fixed for this ticket, but if it's not we should create another ticket to track fixing that.

**Comment by wuwinson** [comment]
> 



> Just did some testing and it appears resolved. My concern is still that our error handling was allowing the recursive `/boards` appending. That doesn't have to be fixed for this ticket, but if it's not we should create another ticket to track fixing that.

Thanks @Pinjasaur, can you create a new ticket for that issue? Closing this one out.

**Comment by harshilsharma63** [comment]
@sbishel is also fixing something around this.

**Comment by Pinjasaur** [comment]
@sbishel need a ticket or issue created?

**Comment by sbishel** [comment]
@Pinjasaur My fix https://github.com/mattermost/focalboard/pull/3880, also fixed the issue before the error loop. So we probably need a ticket to investigate the error looping, but need a way to duplicate since these now won't occur.

**Comment by Pinjasaur** [comment]
#3937
