### ISSUE TITLE
Bug: Mention @ autocomplete doesn't filter on typing

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#3821]
## Steps to reproduce the behavior

1. Open a card
2. Enter a comment
3. Type `@` then the start of a user's name
4. The list doesn't filter

## Expected behavior

The list should filter to users with those characters in their name

## Screenshots (optional)

<img width="385" alt="Screen Shot 2022-09-09 at 9 16 57 AM" src="https://user-images.githubusercontent.com/46905241/189396168-f6fd6ff2-d97e-4722-9c7a-7df6f3ba626c.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2 (Community)
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment]
@chenilim Are you still running into this issue? Not able to repro on Community. Tried Chrome and MM Desktop app. Also tested on v7.3 and can't repro there either. cc @ogi-m

**Comment by chenilim** [comment]
Yup, it repros on [this card](https://community.mattermost.com/boards/team/qghzt68dq7bopgqamcnziq69ao/2510923b-40de-4a48-871f-cb8f85517a0b/effcc895-53a6-4af5-8320-9aabac657178/c14gbsocagprkup7nkjm8c6hr1r), but not in a card from the Internal Focalboard channel (Weekly Focalboard meeting agenda). Maybe it's board specific?

**Comment by wuwinson** [comment]
Thanks @chenilim! Ran a few tests and this looks like it only occurs on a private board when the user has synthetic membership. Does not occur any public boards or boards where users have explicit membership. Tested in v7.3 Bug Bash and not able to repro there, so might already be resolved. @ogi-m Can you confirm? Our [Boards Team Meetup Location](https://community.mattermost.com/boards/team/qghzt68dq7bopgqamcnziq69ao/batertig1mpbfidbz5pampdzfdw/vxtnq78frujrkikc8anpyp8ampy) board would be an example where we have synthetic membership on Community.

**Comment by Pinjasaur** [comment]
Yeah this should have been fixed in #3761.

**Comment by sbishel** [comment]
Can we confirm on https://boards-bugbash73.test.mattermost.cloud/ and close?

**Comment by wuwinson** [comment]
Can't repro on https://boards-bugbash73.test.mattermost.cloud/, closing out.
