### ISSUE TITLE
Bug: Cannot create board from `Link to Channel` model in DM channel

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#3824]
## Steps to reproduce the behavior

1. Have some boards created
2. From a DM channel, open Boards RHS
3. Select  `Link boards to DM`
4. Select `Create a board`
5. Template selector briefly appears then disappears, showing last open board.

## Expected behavior

Template selector should stay up, allowing user to create a board

## Screenshots (optional)

![create-board-bug](https://user-images.githubusercontent.com/5024605/189465047-2ff35c94-1f79-41a0-872f-b766aeabf702.gif)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.3 (main)
 - Browser and OS: FF Linux

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by sbishel** [comment]
@wiggin77 - I retested this on latest https://boards-bugbash73.test.mattermost.cloud/ and could no longer duplicate. Could you double check and close if fixed.

**Comment by wiggin77** [comment]
Agreed @sbishel - I can no longer reproduce.
