### ISSUE TITLE
Bug: Person property cells overflow in table view

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#3830]
## Steps to reproduce the behavior

1. Open a table view with person property columns
2. The person names overflow the cell

## Expected behavior

Should not overflow

## Screenshots (optional)

<img width="362" alt="Screen Shot 2022-09-12 at 8 27 54 AM" src="https://user-images.githubusercontent.com/46905241/189694337-4f6b72ad-18ff-4550-b364-d5c6354ca62a.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2 (Community)
 - Browser and OS: Chrome one Mac

**Comment by wuwinson** [comment]
Reproducible in v7.3 Bug Bash server as well.

If we want to stay consistent with current table view behavior, the names should get clipped when it reaches the width of the cell.

However, it might be a better experience for the cell to auto-expand to a max width then start wrapping the text up to certain number of lines before requiring the user to manually expand the cell. Would be helpful for `multi-person` and `text` properties. Something to consider as an improvement separate from this bug. Thoughts @asaadmahmood?
