### ISSUE TITLE
asana import fails

### ISSUE THREAD

**Issue by hoellmet** [mattermost/focalboard#3834]
### Discussed in https://github.com/mattermost/focalboard/discussions/3784

# Steps to reproduce the behavior

I tried to import a asana.json board archive.
I do all the steps in the import/asana/README.md and https://docs.mattermost.com/boards/data-and-archives.html document, 
but if i try to import in mattermost no cards are imported and no error message is shown

1. From the Asana Board Menu (dropdown next to board title), select Export / Print, and JSON
2. Save it locally, e.g. to asana.json
3. Run npm install from within focalboard/webapp
4. Run npm install from within focalboard/import/asana
5. Run npx ts-node importAsana.ts -i <asana.json> -o archive.focalboard
6. In Focalboard, click Settings, then Import archive and select archive.focalboard

## Expected behavior
It should display all imported boards or error should be displayed.

Point 5. worked like expected:

`npx ts-node importAsana.ts -i ./tasks_hosting.json -o hosting_archive.boardarchive`

```
.....
Card: Hosting & Haftung
Card: AGB anpassen (Hosting)

Found 43 card(s).
Exported to hosting_archive.boardarchive
```

Content Line 1+2 of  hosting_archive.boardarchive:

```
{"version":1,"date":1662493797984}
{"type":"board","data":{"id":"bhco6knmhxrn64ys54cu9jmzp5a","teamId":"","channelId":"","createdBy":"","modifiedBy":"","type":"P","minimumRole":"","title":"Webhosting","description":"","icon":"","showDescription":false,"isTemplate":false,"templateVersion":0,"properties":{},"cardProperties":[{"id":"b886bec3-4f51-49f3-86a7-0baf748523e4","name":"Section","type":"select","options":[{"id":"54ee3ec7-6b70-4073-8d70-bc22793c4aaa","value":"Account-Pflege","color":"propColorGray"},{"id":"a13f883c-c18f-4795-8c1b-c0ccc6ff4477","value":"Fertig","color":"propColorBrown"},{"id":"9b6d7f50-b80b-4c1a-8fd5-d1da2d330b0e","value":"Abgelehnt","color":"propColorOrange"},{"id":"ca8794af-ca44-4620-82f6-f4805f4e8407","value":"Später","color":"propColorYellow"}]}],"createAt":1662493797978,"updateAt":1662493797978,"deleteAt":0}}
...
```

## Error-Log / Screenshots
Here is the output of server log mattermost.log after import:
`
{"timestamp":"2022-09-06 21:56:25.797 +02:00","level":"error","msg":"API ERROR","caller":"app/plugin_api.go:975","plugin_id":"focalboard","code":"500","error":"\"unsupported archive line type; got board, line 2\"","_msg":"","api":"/api/v1/workspaces/7qi6a78hxffnfe5rd8kmxxk3gr/archive/import"}
`
In Chrome Version 104.0.5112.102 Windows i found this messages:

![Screenshot 2022-09-07 151617](https://user-images.githubusercontent.com/112982447/189872988-e6a36367-25c4-46b7-a1fb-14effffd5f16.png)

## Edition and Platform

 - Edition: mattermost server on premise with Debian Linux 9.0
 - Version: 7.2 0
 - Browser and OS: Chrome on Windows and Windows Desktop App 5.1.1

**Comment by wuwinson** [comment]
@Pinjasaur can you please test and fix all imports since v7.2? Thanks! cc @sbishel

**Comment by Pinjasaur** [comment]
Related to #3728.

**Comment by hoellmet** [comment]
@Pinjasaur Sorry i comment here: #3784

**Comment by hoellmet** [comment]
@Pinjasaur I upload files and comment in discussion: https://github.com/mattermost/focalboard/discussions/3784

**Comment by Pinjasaur** [comment]
Closing, see #3784.
