### ISSUE TITLE
Bug: Theme preference resets on app restart

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#384]
**Summary:**
Selected theme preference doesn't persist after app restart, instead it reverts to system default.

**Steps to reproduce the behavior:**

1. Launch Focalboard on Windows (the store app)
2. Click on _Settings_ > _Set theme_
3. Select any theme other than _System theme_
4. Quit the app and start it again
5. Observe the theme

**Expected behavior:**
The theme selected in step 3 is displayed

**Observed behavior:**
App seems to have defaulted back to _System theme_

**Platform:**
 - Windows 10
 - Focalboard desktop app

**Comment by chenilim** [comment]
Dup of #314. This should already be fixed as part of a checkin for #314. Should be able to verify this in the latest build from source, or in the next release.
