### ISSUE TITLE
Bug: Multiple console errors when on the first tour point

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#3846]
## Steps to reproduce the behavior

1. Create a new user
2. Go take a tour
3. Notice bunch of console errors when the board loads with the first tour point

## Expected behavior
No console errors

## Screenshots (optional)
<img width="1045" alt="Screenshot 2022-09-15 at 1 27 06 PM" src="https://user-images.githubusercontent.com/11034289/190355232-b38ea233-264c-427a-b9d5-011aa0fd5bfe.png">

## Edition and Platform
 - Edition: Mattermost Boards (plugin)
 - Version: 7.3
 - Browser and OS: Chrome

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 3: Affects minor, non-critical functionality

**Comment by sbishel** [comment]
This should get fixed when we update templates.
