### ISSUE TITLE
Bug: Unable to convert between certain property types

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#3847]
## Steps to reproduce the behavior

1. Create a multi select property.
2. Try converting it to a text type.
3. There is no user error message about type incompatibility or anything. It just doesn't work.

Also, converting number property to text removes its values, but it shouldn't as text can contain number

**Comment by wuwinson** [comment]
Related to #3916

**Comment by sbishel** [comment]
https://github.com/mattermost/focalboard/pull/3920 fixes the first part of this.

**Comment by sbishel** [comment]
Closing this as #3920 fixes the first part. Regarding changing values, we only delete values when going to from select properties. So we shouldn't be removing values. Please write a separate ticket where and how you see values being changed.
