### ISSUE TITLE
Bug: Clicking next or previous on tour points at the first time does not work

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#3848]
## Steps to reproduce the behavior

1. Create a new user
2. Take a tour
3. Open a card, and go to tour points on the card

## Expected behavior
Clicking next or previous on tour points should work

## Screenshots (optional)
https://www.loom.com/share/0aba577eaf134f88b248ceec2821b253

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.3
 - Browser and OS: Chrome on Mac

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 2: Affects major functionality with a difficult or non-obvious workaround

**Comment by sbishel** [comment]
Retested on latest - https://boards-bugbash73.test.mattermost.cloud/ 
Appears to have been fixed.

**Comment by mgdelacroix** [comment]
Can't reproduce neither on `main` nor on `v7.3`
