### ISSUE TITLE
Feature Idea: Show a visual indicator next to the selected language & theme options

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#385]
**Summary:**
There's currently no way to tell which theme or language is selected when looking at the list. It would be great to show a visual indicator, like a checkmark, next to the selected option.

Note in the screenshot that there's nothing to indicate which theme is currently selected

![focalbard_theme](https://user-images.githubusercontent.com/15314183/117199422-74e43f00-adea-11eb-96d4-58950ff80dd7.jpg)

**Comment by chenilim** [comment]
Thanks @ogi-m! Agree we should have a standard way to show the active setting in a menu (e.g. a checkbox). Thoughts @michaelgamble?

**Comment by michaelgamble** [comment]
My instinct is that settings like this likely should be consolidated and more of a settings modal rather then a dropdown (gives them a home that we can expand on). For the sake of not holding anything up, in the short-term we can add a blue check icon to the left of the selected item. If this is using the menu component from MM it may already have an accommodation for including icons in the line items. [icon reference here](file:///Volumes/GoogleDrive/Shared%20drives/Product%20Design/Compass%20Design%20System/Compass%20Icons/demo.html) - i suggest the "icon-check" character (this is our customizable icon font library that MM uses)

@chenilim I would like to que up exploring a settings modal for the mid / long term approach.

**Comment by chenilim** [comment]
Thanks! Queueing this up for triage. We might want to add the basic Mattermost icons to Focalboard, so we can start using them elsewhere.

**Comment by harshilsharma63** [comment]
iI'm in the process of adding the Mattermost Compass Icons to Focalboard. I'll update here when the changes are merged and then we can proceed with this one.

**Comment by harshilsharma63** [comment]
@ogi-m I've merged the PR which adds the icon library in Focalboard. You can use this PR as a reference for how we're using the icons - https://github.com/mattermost/focalboard/pull/393 .
