### ISSUE TITLE
Bug: Missing notifications for board events and mentions

### ISSUE THREAD

**Issue by johan-d-x** [mattermost/focalboard#3852]
We're having trouble using Boards in our team due to notification trouble. 

We've applied this manual fix: https://github.com/mattermost/focalboard/discussions/2415

Notifications are still inconsistent:
- The `@boards` bot isn't available/functioning for all boards (between 2 users for instance and even for some public boards)

- It is unclear what event the `@boards` is supposed to track and follow-up when following a card

- Notification are something lacking of context with no other information than "you've been mentioned somewhere" (see screen)

## Steps to reproduce the behavior

1. Go to a public board where `@boards` is not member or to a private message
2. Select the board of your channel / private message
3. `@mention` someone from your team
4. User isn't notified of mentions and isn't notified of any event related to card he follows

Notifications only works if `@boards` bot is member of the chan.

`Enable users to open Direct Message channels with` is set as `Any user on the Mattermost Server`.

## Expected behavior

We would have expected a more consistent and reliable behavior from the notification system:

- Being notified every time we're mentioned on any board of the team (except board from a private channel we're not member of)

- Being notified every time an event occurs on a card we're following

- Boards bot being able to track events on every boards of our team

![image](https://user-images.githubusercontent.com/17347288/190418574-6237448c-c397-44a1-898e-9e5e3bb36cd0.png)

## Edition and Platform

 - Edition: Mattermost Team Edition (self-hosted) + Mattermost Boards (plugin)
- Mattermost Version: 7.1.2
 - Browser and OS: Chrome on Windows, Mac, Linux

**Comment by wiggin77** [comment]
@johan-d-x can you confirm which version of Mattermost server you are on?  Do you happen to upgrade the plugin but have an older server?

**Comment by johan-d-x** [comment]
> @johan-d-x can you confirm which version of Mattermost server you are on? Do you happen to upgrade the plugin but have an older server?

@wiggin77 We are running `Mattermost Version 7.2.0` via Omnibus Gitlab.
Regarding the plugin version: `Mattermost Boards (focalboard - 7.1.0)`

We're running the latest plugin version available on the Marketplace.

**Comment by wiggin77** [comment]
Ok, thank you @johan-d-x.  To answer a few questions from the original description:

> It is unclear what event the @boards is supposed to track and follow-up when following a card

When following a card, a user should be notified of any changes to the content of the card, or the card being deleted.  That includes any changes to property values, comments added, and any changes (add/modify/delete) to text in the description.  However the user will not be notified of changes they themselves have authored.

> Notification are something lacking of context with no other information than "you've been mentioned somewhere" (see screen)

The notification appearing in the `boards` bot channel should include context regarding the change. This includes before and after text, before and after property values.  However there was an issue preventing email notifications from containing this context that will be fixed via https://github.com/mattermost/mattermost-server/pull/20946

Note, whether email notifications are sent for these events is controlled via a user settings.  For any users not receiving notifications, check the settings here:
 
![Screenshot from 2022-10-19 09-01-02](https://user-images.githubusercontent.com/5024605/196698280-6008f217-6900-4204-8951-3190102a1f08.png)

**Comment by wiggin77** [comment]
One other thing, there should be no need to ever mention the @board bot.  Mentioning the bot has no effect.  The only way to subscribe to card changes is to be the author of the card, get mentioned in the card, or click the `Follow` button.

**Comment by wiggin77** [comment]
@johan-d-x is this still an issue for you?  Were you able to upgrade to the latest version (which includes the fix mentioned earlier).

**Comment by johan-d-x** [comment]
@wiggin77 Thanks for the follow-up, the bug has been fixed an is no longer visible on our running version (7.4.0).
