### ISSUE TITLE
Bug: "New template from card" text wrapped on menu

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3853]
## Steps to reproduce the behavior

1. Open a card
2. Select  options menu (...)
3. See error - "New template from card" text is wrapped

## Expected behavior

Width of menu should span the width of the "New template from card" text so it doesn't wrap.

![Screen Shot 2022-09-15 at 2 50 26 PM](https://user-images.githubusercontent.com/93531870/190485654-fa3f59b8-0e82-4509-8749-9e39aa71177d.png)

## Screenshots (optional)

![Screen Shot 2022-09-15 at 2 46 46 PM](https://user-images.githubusercontent.com/93531870/190485217-8598d0ce-a9a6-4119-8bba-6adb66b912bc.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.3
 - Browser and OS: Chrome on Mac

**Comment by asaadmahmood** [comment]
Can't reproduce neither on master or on https://boards-bugbash73.test.mattermost.cloud/boards/team/emkcjitr1jfs5nzhntbj6dzztr/bqoq5yf17wffg7e34pfg4pgtt4e/vzor5wijsdbnbfc5cxkn89i85ae/c5k7ru5iro7ynicd1axmtzmwexr

@wuwinson Can you have a look.

**Comment by wuwinson** [comment]
Can't repro anymore, closing out. Thanks @asaadmahmood!
