### ISSUE TITLE
Bug: "Viewer" role not aligned on drop down for explicit board members

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3865]
## Steps to reproduce the behavior

1. Open Share modal on a board
2. Add an explicit board member
3. Click on their role dropdown
4. See error - "Viewer" role is not aligned, but lines up once you select the "Viewer" role. Does not occur on team dropdown, only for explicit membership. Occurs when editing custom templates too.

## Expected behavior

"Viewer" role is aligned with other roles on role drop down.

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/190805384-b0a46069-aca6-4117-be0a-0c7cfd68f44a.mov

![Screen Shot 2022-09-16 at 5 54 47 PM](https://user-images.githubusercontent.com/93531870/190805432-685dadb1-c0fe-47d0-b3be-3c7df3c046f4.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.3 Bug Bash
 - Browser and OS: Chrome on Mac

**Comment by vivekkj123** [comment]
Hi,
I think I can solve this issue. Please assign to me :)

**Comment by wuwinson** [comment]
Awesome, thanks @vivekkj123!
