### ISSUE TITLE
Bug: Comment box doesn't clear after sending

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#387]
**Steps to reproduce the behavior:**
1. Open a card
2. Enter text in the comment box (e.g. "test")
3. Click send (comment is posted)
4. Click on the comment box again
5. The text ("test") appears in the comment box

**Expected behavior:**
The comment box should be cleared after sending

**Platform:**
 - Chrome 89 on macOS 10.15.7

**Comment by prakharporwal** [comment]
newbie to opensource . Like to pick this issue.

**Comment by chenilim** [comment]
You got it @prakharporwal! Thanks!

**Comment by prakharporwal** [comment]
@chenilim  not able to make a pull request on this repo ?? says access denied!!

**Comment by prakharporwal** [comment]
@chenilim Made a pull request after forking the repo . please review . # 547

**Comment by jespino** [comment]
This was already solved by @prakharporwal.
