### ISSUE TITLE
Can't remove created templates

### ISSUE THREAD

**Issue by DiederikR** [mattermost/focalboard#3878]
Hi all,

I just created a template by accident and there seems to be no way of removing it.
I noticed there should be a bin icon when you hover but there is none in version v.7.2.1 running in a Docker container.

Perhaps this is a bug or am I missing something here?

Thanks!

**Comment by wuwinson** [comment]
@DiederikR Can you provide more details on your server edition and screen recordings if available? Thanks! cc @sbishel

**Comment by wuwinson** [comment]
Potentially related to https://github.com/mattermost/focalboard/issues/3695

**Comment by sbishel** [comment]
I tested this yesterday and it seems to work fine on latest. #3695 was part of v7.3.
