### ISSUE TITLE
Bug: Updating to 7.2 replaced all images into 4 empty text block

### ISSUE THREAD

**Issue by MioAtSwivel** [mattermost/focalboard#3879]
## Steps to reproduce the behavior

1. Create a board and card in pre-7.2 versions
2. Add add an image to the card
3. Update to 7.2 through updating mattermost
4. Images get replaced into 4 empty text block

## Expected behavior

The images stay there as how it was before updating

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/102662641/192417152-af630ffe-9d51-42d1-9653-7c79cc9a041d.png)
The red box is where the image should be

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.2.1
 - Browser and OS: Tested on, but not limited to Chrome on Mac, Mattermost Desktop app (windows/mac)

## Additional context (optional)

* Sev 1: Affects all past cards with images, while backing up does not help restoring easily
* Sev 2: Not updating is the only workaround for now

**Comment by harshilsharma63** [comment]
I'm able to reproduce this locally by upgrading from v7.0 to tip of `main`. Looking into this now.

**Comment by kamre** [comment]
I have the same problem after updating to `main` branch. My first impression was that I have some files/directories permission problems because of my own updating script. But it might be that the problem is more generic.

So I am also waiting for possible solution and will look into this on my personal server.

**Comment by harshilsharma63** [comment]
@kamre I've found the issue. Expect a PR pretty soon :)
