### ISSUE TITLE
Feature Idea: ability to install with Apache

### ISSUE THREAD

**Issue by biva** [mattermost/focalboard#388]
**Summary:**
I understand that Focalboard can be installed only with Nginx. Is it also possible on Apache? (in this case, would it be possible to add the documentation like on https://docs.mattermost.com/install/config-apache2.html?)

If it's not available on Apache, do you plan to consider it in the future?

**How important this is to me and why:**

Importance: High (our server uses Apache and not Nginx)

**Additional context / similar features:**
Mattermost can be installed on Apache with this documentation: https://docs.mattermost.com/install/config-apache2.html

**Comment by biva** [comment]
I just tested it and the documentation for Mattermost / Apache2 also works with Focalboard :)

Should I close the issue?

**Comment by gabrielctn** [comment]
> I just tested it and the documentation for Mattermost / Apache2 also works with Focalboard :)
> 
> Should I close the issue?

I am also looking for an apache configuration for my docker instance of Focalboard (in reverse proxy).
Could you please give more details on what you changed to make it work please ?
Thanks

**Comment by biva** [comment]
Same as https://docs.mattermost.com/install/config-apache2.html
