### ISSUE TITLE
Bug: Person property edit cursor behind avatar

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#3881]
## Steps to reproduce the behavior

1. Create card with a `Person` property.  
2. Select a person to populate it
3. Edit the Person property by clicking on it
4. See the cursor appearing behind the avatar of the person selected in step 2

## Expected behavior

The fact that people who are not members of the board do not appear in the auto-complete drop-down is confusing IMO.  With the cursor hidden there is no way for a user to know how to add a team member who is not a member of the board.

## Screenshots (optional)
![person-prop-bugs](https://user-images.githubusercontent.com/5024605/193115733-246a251c-6de8-4f05-a4b0-a9fda4b14397.gif)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.3 bugbash 
 - Browser and OS: Linux FF

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by Pinjasaur** [comment]
Repros on Mac FF too.

![image](https://user-images.githubusercontent.com/6335792/193120103-538d7bcd-b3de-4e8d-8b61-5db37ad5a2bf.png)

**Comment by sbishel** [comment]
@wiggin77 - Could you retest on Linux and see if still an issue. I tried on https://boards-bugbash74.test.mattermost.cloud/ and could no longer duplicate either on MAC (chrome nor FF).

**Comment by wiggin77** [comment]
> @wiggin77 - Could you retest on Linux and see if still an issue. I tried on https://boards-bugbash74.test.mattermost.cloud/ and could no longer duplicate either on MAC (chrome nor FF).

Still happening for me on bugbash74.  FF 106.0.1 Linux

![caret-bug](https://user-images.githubusercontent.com/5024605/197208203-986243d0-d1e3-4550-a9f0-45f527bde4ba.gif)

**Comment by sbishel** [comment]
Thanks.  Also occurs on the normal "Select" property.
