### ISSUE TITLE
Bug: Multi-Person property does not allow selecting non-board members

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#3884]
## Steps to reproduce the behavior

1. Create a card with a multi-person property
2. Select the property to edit it
3. Type the first letter of a team member username that is not a board member
4. There is no way to select that user

## Expected behavior

Multi-person property should behave as Person property does with respect to who can be added/selected.

## Screenshots (optional)

![person-prop-bugs](https://user-images.githubusercontent.com/5024605/193116535-5162f5c0-addd-4ae7-855d-fb600c3117d2.gif)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.3  bug bash
 - Browser and OS: Linux FF

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by Pinjasaur** [comment]
@wiggin77 I'm seeing that behavior you described by leaving a tab idle for a few minutes while doing something else:

Person:

![image](https://user-images.githubusercontent.com/6335792/193121526-14c94b9f-ac0c-439b-a215-b610d422da74.png)

Multi-Person:

![image](https://user-images.githubusercontent.com/6335792/193121561-ee3639a4-915c-4605-ba19-c2c060ae1efb.png)

**Comment by Pinjasaur** [comment]
Looks like Multi-Person is showing bots in that scenario too (#3762)
