### ISSUE TITLE
Popup is not aligned

### ISSUE THREAD

**Issue by varghesejose2020** [mattermost/focalboard#3898]
## Summary
Found on `https://boards-bugbash73.test.mattermost.cloud/`server >Private Board
In this section we click on three dots and select `Copy Link` Option Copied popup is not alligned
![feature1](https://user-images.githubusercontent.com/71702982/193397195-b6ef6bec-b380-46a6-87ae-25ceb93fb01f.png)

**Comment by vivekkj123** [comment]
Hi, I would like to work on this. Please assign it to me
