### ISSUE TITLE
Change Indication icon for Random and Pick Icon

### ISSUE THREAD

**Issue by varghesejose2020** [mattermost/focalboard#3899]
## Summary
Found on `https://boards-bugbash73.test.mattermost.cloud/`server >On Boarding
Indication Icon of Random and Pick Icon is same. It should be better to change
![image](https://user-images.githubusercontent.com/71702982/193397757-173e8aea-28cd-4d81-a2fe-6402a66e3841.png)

**Comment by vivekkj123** [comment]
Hi, I can work on this. Please assign to me
