### ISSUE TITLE
Bug: Person auto-complete doesn't work in tables

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#3903]
## Steps to reproduce the behavior

1. Open a table view with a person column
2. Type in the person column
3. No auto complete

## Expected behavior

There should be auto-complete like typing in the card.

## Screenshots (optional)

<img width="731" alt="Screen Shot 2022-10-01 at 8 38 27 AM" src="https://user-images.githubusercontent.com/46905241/193417075-b2b3ac21-9c89-4704-a23e-38fd8fe44aaa.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2.1 (community)
 - Browser and OS: Chrome on Mac

**Comment by chirag-ghosh** [comment]
Can i work on this ?

**Comment by wuwinson** [comment]
@sbishel Looks like we have a regression on this bug as of v7.8.

**Comment by sbishel** [comment]
@wuwinson Not a regression, but the same issue with multiPerson.
