### ISSUE TITLE
Bug: Rows in table view shift left on hover over

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3915]
## Steps to reproduce the behavior

1. For boards where you're a Viewer or Commenter only
2. Go to table view
3. Hover over each row
4. See error - row shifts to the left

## Expected behavior

Row is highlighted but remains fixed in it's position

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/193656559-fcf83932-bdde-4c44-ae8c-7d2673795e42.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.3 Bug Bash
 - Browser and OS: Chrome on Mac

**Comment by idChef** [comment]
Hi, let me take this issue

**Comment by wuwinson** [comment]
Great, thanks @idChef!
