### ISSUE TITLE
Bug: Color on Person cell with dark theme is invisible

### ISSUE THREAD

**Issue by jufab** [mattermost/focalboard#3918]
## Steps to reproduce the behavior

1. Set dark theme
2. Open a table view with person property columns

## Expected behavior

View a selected person or Empty text

## Screenshots (optional)
<img width="600" alt="image" src="https://user-images.githubusercontent.com/25395032/193692502-a13f212f-a6c6-49a9-852f-725a1dd487f5.png">
<img width="600" alt="image" src="https://user-images.githubusercontent.com/25395032/193693066-1f13d9a5-294c-4a08-9345-1eafcdb6aa4d.png">

## Edition and Platform

 - Edition: Personal Desktop
 - Version: v7.5.0
 - Browser and OS: Chrome on Mac

## Additional context (optional)

No problem in Light theme

**Comment by jufab** [comment]
Can I be assigned on it? I think I know how to fix it.

**Comment by sbishel** [comment]
@jufab - absolutely...
