### ISSUE TITLE
Bug: Card badges are missing

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3919]
## Steps to reproduce the behavior

1. Go to any board
2. Open the "Properties" menu from the board header
3. See error - the toggle to enable "Comments and descriptions" are missing

## Expected behavior

"Comments and descriptions" toggle should be visible as the last option on the menu. See https://github.com/mattermost/focalboard/pull/2025 and our [Help Docs](https://github.com/mattermost/focalboard/pull/2025) for details.

#### Current
![Screen Shot 2022-10-03 at 5 57 36 PM](https://user-images.githubusercontent.com/93531870/193694050-474c1660-6be6-4c44-a267-bf75684b2576.png)

#### Expected

![Screen Shot 2022-10-03 at 6 03 15 PM](https://user-images.githubusercontent.com/93531870/193694111-f2e8914a-6e5d-44ef-9fd6-a754a51beab6.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.3 Bug Bash
 - Browser and OS: Chrome on Mac

**Comment by sbishel** [comment]
@wuwinson - I cannot duplicate on any board. Only on table views which is by design.

**Comment by wuwinson** [comment]
@sbishel User error... my fault. :grimacing:  Closing out.
