### ISSUE TITLE
Bug: Creating a board from a custom template adds the board to the same category as the origin board

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3938]
## Steps to reproduce the behavior

1. Go to a board under a custom category
2. From the sidebar, open the board's option menu and select `New template from board`
3. Go to the template picker and select the template
4. See error - the board gets created in the same category as the origin board. Only applies to the board creator. The board will get created correctly in the default Boards category for other users.

## Expected behavior

The board is added to the default "Boards" category.

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/194176503-9cffefe0-62ec-42c6-bdc0-d466ea64c25f.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.3 Bug Bash
 - Browser and OS: Chrome on Mac

**Comment by shadybotros** [comment]
@wuwinson I can work on that if no one is already working on it (would be my first contribution)

**Comment by wuwinson** [comment]
Awesome, thanks @shadybotros! I've assigned the bug to you!
