### ISSUE TITLE
Bug: `Guest` tag overlaps with timestamp in card comments

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3939]
## Steps to reproduce the behavior

1. Login as a guest account
2. Open a card and add a comment
3. See error - `Guest` tag overlaps with the timestamp

## Expected behavior

Guest tag does not overlap with timestamp

## Screenshots (optional)

![Screen Shot 2022-10-05 at 6 42 15 PM](https://user-images.githubusercontent.com/93531870/194177426-a9886853-839e-4767-8eb4-138ef8e0ecf0.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.3 Bug Bash
 - Browser and OS: Chrome on Mac

**Comment by adithyaakrishna** [comment]
Can I take this up?

**Comment by wuwinson** [comment]
Thanks @adithyaakrishna, assigned to you!
