### ISSUE TITLE
Bug: Grammatical error on confirmation modal to add member from autocomplete list

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3940]
## Steps to reproduce the behavior

1. Go to a board where you're an admin
2. Open a card and @mention a non-board member
3. Select the non-member from the autocomplete list
4. See error - grammatical error with the word "received" on confirmation modal

## Expected behavior
"Receive" should be in present tense:

{User name} is not a member of the board, and will not **receive** any notifications about it.

## Screenshots (optional)

![Screen Shot 2022-10-05 at 6 44 32 PM](https://user-images.githubusercontent.com/93531870/194177956-df6f7fe0-eccc-4314-81a8-23ef9d373e5a.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.3 Bug Bash
 - Browser and OS: Chrome on Mac

**Comment by shikhar13012001** [comment]
I would like to work on this issue, Can you please assign me this? @wuwinson

**Comment by shikhar13012001** [comment]
@wuwinson I have create the PR please review and let me know if you need any changes, 
Thanks again for assigning this issue to me, it was great! 😄
