### ISSUE TITLE
Bug: Unlink board message displays the word "Hello" for boards you do not have permissions to unlink

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3942]
## Steps to reproduce the behavior

1. Go to Boards Apps Bar in a channel
2. Open the options menu for a board you cannot unlink
3. See error - the word "Hello" appears in the message

## Expected behavior

The message should not include the word "Hello" and the header should only display "Unlink board"

## Screenshots (optional)

![Screen Shot 2022-10-05 at 7 02 40 PM](https://user-images.githubusercontent.com/93531870/194179511-de887b32-4834-44c5-b176-4a81b57d4f41.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.3 Bug Bash
 - Browser and OS: Chrome on Mac

**Comment by alfredoalpizar** [comment]
can I be assigned this one?

**Comment by sbishel** [comment]
Fixed in this PR. https://github.com/mattermost/focalboard/pull/3759
