### ISSUE TITLE
Bug: Product tour for share button is not in the right place

### ISSUE THREAD

**Issue by Rajat-Dabade** [mattermost/focalboard#3946]
## Steps to reproduce the behaviour

1. Start the product tour.
2. Click the next button till the share button tour appears.
3. See the error, the share button tour is on the new button.

## Expected behaviour
The share button tour should be on the share button.

## Screenshots (optional)
![Screenshot 2022-10-06 at 2 08 40 PM](https://user-images.githubusercontent.com/26198062/194266695-8c05b124-69d7-4df5-a98b-bc244625e132.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.3
 - Browser and OS: Chrome on Mac

**Comment by vivekkj123** [comment]
Can i Work on this ?

**Comment by sbishel** [comment]
@vivekkj123 - sure.

**Comment by vivekkj123** [comment]
Hey, Are there any tricks to test product tour?

**Comment by Rajat-Dabade** [comment]
@vivekkj123, yes there is, from the top nav bar inside the setting menu there is an option to start a product tour (the last option).
![Screenshot 2022-10-10 at 11 01 32 AM](https://user-images.githubusercontent.com/26198062/194803750-fcf8101e-f67f-483a-a134-0b407058cfc1.png)
