### ISSUE TITLE
Feature Idea: confirmation dialog when deleting a card in calendar/galley view

### ISSUE THREAD

**Issue by kamre** [mattermost/focalboard#3947]
## Summary

Cards in **calendar**/**gallery** views have action menus like this:
![image](https://user-images.githubusercontent.com/5587620/194337434-e8904e8b-0119-4693-9ca7-f7aa7fb813dd.png)

If `Delete` action is selected there is no confirmation dialog like for `Delete` menu action for cards on **kanban** view:
![image](https://user-images.githubusercontent.com/5587620/194338929-2f848167-f96f-4f05-bca5-e04f1fd1a9c8.png)

Propose to add confirmation dialog when deleting cards via actions menu from **calendar**/**gallery** views.

Not sure how it works for table views because it is impossible to show actions menu for table row on `main` branch currently.

## How important this is to me and why

Importance: Medium, better have some consistent behaviour for all views.

**Comment by wuwinson** [comment]
Good catch, thanks @kamre!

**Comment by varunKT001** [comment]
@wuwinson I would like to work on this issue. Please assign it to me.

**Comment by varunKT001** [comment]
@wuwinson Please assign this issue to me.

**Comment by varunKT001** [comment]
@wuwinson 
Can you help me in setting up the project? 
I have no experience with GO, so is it possible that I can only start a dev-server for the web app?

**Comment by varunKT001** [comment]
@kamre I'll go through it, thanks!

**Comment by kamre** [comment]
@Rajat-Dabade @varunKT001 When deleting the card in Calendar view I see the confirmation dialog. After that I click `Delete` button and the card is deleted but the dialog is not closed.

Can you check this please?

**Comment by Rajat-Dabade** [comment]
@kamre, I can also see this issue, I will create another ticket for it. Nice catch. Thanks.

**Comment by varunKT001** [comment]
@kamre @Rajat-Dabade It's a minor fix. Shall I work on this?

**Comment by Rajat-Dabade** [comment]
Sure, @varunKT001, will reopen this issue.

**Comment by varunKT001** [comment]
@Rajat-Dabade I'll make a PR soon, thanks!

**Comment by varunKT001** [comment]
@kamre Even though I have 2 PRs merged, I can't see my name in the contributors' list shown by GitHub 😕
