### ISSUE TITLE
Bug:  CONSOLE ERROR SyntaxError: Invalid regular expression

### ISSUE THREAD

**Issue by BaltazarBazar** [mattermost/focalboard#3980]
When I try to start the app for the first time:

x@deb:~/Desktop/focalboard-app$ ./focalboard-app 
http://localhost:38375/static/main.js?23c98825b3a4d0d6c41d:350: CONSOLE ERROR SyntaxError: Invalid regular expression: invalid escaped character for unicode pattern

^C
x@deb:~/Desktop/focalboard-app$ 

The app opens but the window is blank. That's all that happens

**Comment by sbishel** [comment]
@BaltazarBazar - Can you provide version information

**Comment by BaltazarBazar** [comment]
I used the latest version

**Comment by wuwinson** [comment]
@jespino @wiggin77 Can you see if you can duplicate this issue? Thanks!

**Comment by jespino** [comment]
I don't know if this is a duplicated issue, the bugs looks related to some kind of encoding problem. @BaltazarBazar can you try to execute this with `LANG=C ./focalboard-app` and see if that still happens?

**Comment by BaltazarBazar** [comment]
Same thing. It all looks good (a bunch of green lines) in the terminal window up until the final line:

2022/10/18 14:06:40 ==  migrate_user_props_to_preferences: migrated (0.0063s)  =========================================
2022/10/18 14:06:40 ==  remove_template_channel_link: migrating  =======================================================
2022/10/18 14:06:40 ==  remove_template_channel_link: migrated (0.0056s)  ==============================================
http://localhost:38121/static/main.js?23c98825b3a4d0d6c41d:350: CONSOLE ERROR SyntaxError: Invalid regular expression: invalid escaped character for unicode pattern

The GUI is blank as before

**Comment by wiggin77** [comment]
I'm installing Debian to try and repro this.

**Comment by wiggin77** [comment]
I was not able to reproduce this with latest Focalboard app and stable Debian.

![Debian 11-2022-11-07-15-18-41](https://user-images.githubusercontent.com/5024605/200407089-3466d4cc-2770-44b4-96d5-6905cc4bc5bb.png)

**Comment by wiggin77** [comment]
@BaltazarBazar I'm wondering if the issue is that you have a very old Debian?

**Comment by sbishel** [comment]
@BaltazarBazar - Closing please reopen if still and issue.
