### ISSUE TITLE
Bug: Welcome screen appears sporadically even after previously skipping the tour

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#4007]
## Steps to reproduce the behavior

1. Go to bookmarked board from your browser on Community
2. Select the bookmark several times to reload the page
3. See error - Welcome screen appears sporadically when it shouldn't. Clicking on the "Take a tour" button also doesn't work and might be related to https://github.com/mattermost/focalboard/issues/3995
4. Going to /boards on the other hand takes you to Boards, but the Welcome page appears for a brief moment each time

## Expected behavior

Boards loads without the Welcome screen

### Going to a [specific bookmarked board](https://community.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/b4ctmm917q3rzdfi451qtuxjzcw/vuswsftt1rb873datosmmbtwkpa)

https://user-images.githubusercontent.com/93531870/195433553-2418aec0-9eb3-4805-872a-feddeec28923.mov

### Going directly to [/boards](https://community.mattermost.com/boards/) from a bookmark

https://user-images.githubusercontent.com/93531870/195434883-a85580fc-0dfa-4287-b5de-76d82f454069.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.4.2 Community
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment]
cc @sbishel

**Comment by sbishel** [comment]
This occurs when using the old "workspace" path. And it actually stops on the Welcome Board. It does "flash" even when hitting the new "team" path.

**Comment by sbishel** [comment]
This occurs when using the old "workspace" path. And it actually stops on the Welcome Board. It does "flash" even when hitting the new "team" path.
