### ISSUE TITLE
Bug: Long category names overlap other categories on the "Move To..." sidebar submenu

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#4008]
## Steps to reproduce the behavior

1. Go to sidebar on Community
2. Select a board and open the options menu (...) from the sidebar
3. Select "Move To..."
4. See error - categories with long names overlap other categories and are not legible on the submenu

## Expected behavior

Category names that wrap multiple lines have an expanded height on the submenu. cc @asaadmahmood for confirmation.

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/195437981-a958551c-0b73-481f-9232-ccc27c062933.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.4.2 Community
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment]
cc @asaadmahmood Should we wrap or truncate or something else?

**Comment by asaadmahmood** [comment]
@wuwinson I'll fix this. Ideally we can allow the menu to expand a bit more, and then truncate the categories, with possibly a basic html tooltip on hover.
