### ISSUE TITLE
Bug: Changes to template permissions and icons don't update

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#4013]
## Steps to reproduce the behavior

1. Open a custom template to edit
2. Open the Share dialog and change permissions for the team
3. See error - nothing happens
4. Change the icon for the template
5. See error - nothing happens
6. Go back to the template editor
7. Notice the icon is updated on the preview, but going back to the same template to edit does not display the changes
8. Open another template to edit
9. Go back to template editor
10. Open the same custom template from Step 1 to edit
11. Changes are now visible on the template

## Expected behavior

Changes to the template are seen immediately

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/195680068-802da90f-53d7-42f7-a3e6-971af89fc094.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.5 Bug Bash
 - Browser and OS: Chrome on Mac

**Comment by sbishel** [comment]
Fixed - https://github.com/mattermost/focalboard/pull/4145
