### ISSUE TITLE
Bug: Email notification displays comments but not change notifications

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#4014]
## Steps to reproduce the behavior

1. Follow a card
2. Have another user make changes to the card and comment you
3. Wait for Boards bot notification
4. Then wait for email notification
5. See error - Email notification is missing content for change notifications

## Expected behavior

Email notification display similar to Boards bot notification in Channels.

### Boards bot in Channels:
![Screen Shot 2022-10-13 at 2 48 02 PM](https://user-images.githubusercontent.com/93531870/195681362-0d86a6d1-8c6a-4c95-bbbb-1e09ed3e0680.png)

### Email notification:
![Screen Shot 2022-10-13 at 2 48 49 PM](https://user-images.githubusercontent.com/93531870/195681349-f9a0f9da-9098-4ab9-b6c0-8222d511a5eb.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.5 Bug Bash
 - Browser and OS: Chrome on Mac

**Comment by harshilsharma63** [comment]
@wuwinson its already being completed as part of https://github.com/mattermost/mattermost-server/pull/20946

The em,ail notifications will now contains everything but the red box highlighted below.

![195681362-0d86a6d1-8c6a-4c95-bbbb-1e09ed3e0680](https://user-images.githubusercontent.com/18575143/196369228-7484bc38-fd0f-472f-9e6d-fda0495c389c.png)

Also, this is not a bug, but rather a new feature in the sense that it was never implemented.

**Comment by harshilsharma63** [comment]
Can we close this one as a dupe of the ticket being tracked in the above specified PR?

**Comment by wuwinson** [comment]
Ah ok thanks @harshilsharma63! We were testing all the stuff from `main` as part of our post-v7.4 bug bash and thought the email stuff was merged in. Closing this out.
