### ISSUE TITLE
Doc: role permissions

### ISSUE THREAD

**Issue by AuspeXeu** [mattermost/focalboard#4028]
## Summary

It would be great to have a resource that details what rights come with a specific role. (Viewer, Commenter, Admin, etc.)

**Comment by wuwinson** [comment]
@AuspeXeu Thanks for your feedback! We may need to link to the Help Docs somewhere on the Share dialog to make it more obvious, but the docs are located [here](https://docs.mattermost.com/boards/share-and-collaborate.html#roles). Feel free to reach out if you have any other questions. cc @justinegeffen @asaadmahmood
