### ISSUE TITLE
Bug: Text cursor always moves to the end of input text after any text editing action.

### ISSUE THREAD

**Issue by andrewwutw** [mattermost/focalboard#4038]
## Steps to reproduce the behavior

In focalboard text input mode, if I do any text editing action, the text cursor will move to the end of input text automatically.

See screenshots :

1. I create a new empty board item.

![1](https://user-images.githubusercontent.com/4443713/196635831-b1245f8b-32d7-4edd-b540-df51968fdfea.png)

2. I type "1234" in the comment field. It is no problem.

![2](https://user-images.githubusercontent.com/4443713/196635871-09b6ff06-1e20-4da8-a223-023921708d85.png)

3. By pressing left arrow key 2 times, I moved the text cursor to the middle of input text field, now the text cursor is between "12" and "34".

![3](https://user-images.githubusercontent.com/4443713/196635907-7d51ba12-9bc4-4fad-9a1f-bd9774a512aa.png)

4. I type "5", this character is inserted between "12" and "34", so the input text field is "12534", but the text cursor moved to the end of input text. It is not a correct behavior.

![4](https://user-images.githubusercontent.com/4443713/196635964-2dd4fa8e-7931-47d8-9fef-81f43dfdc159.png)

5. I type "6", this character is appended to the end of input text.

![5](https://user-images.githubusercontent.com/4443713/196636000-0ebf58c1-af4b-4905-86d0-75b37faccea4.png)

## Expected behavior

In this case, the text cursor should not move to the end of input text.

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.5.0
 - Browser and OS: Chrome on Mac

This incorrect behavior doesn't exist in v7.2.1, but exists since v7.4.0. So I guess there is something wrong between v7.2.1 and v7.4.0

I tested on main branch (commit 6f0c34ddd1ae275986ab491a05ee4ba9c30ad0b1)

**Comment by wuwinson** [comment]
Thanks for reporting @andrewwutw! This was reported on https://github.com/mattermost/focalboard/issues/4005 and the fix should be available in one of the upcoming weekly cloud releases.
