### ISSUE TITLE
Bug: Fail to upgrade from v7.4.2 to v7.4.3 on focalboard server w/ MySQL

### ISSUE THREAD

**Issue by zhzy0077** [mattermost/focalboard#4067]
## Steps to reproduce the behavior

1. A working focalboard server on v7.4.2 with MySQL data store via Docker.
2. docker run v7.4.3 version of focalboard server

## Expected behavior
The server is able to start.

## Screenshots (optional)
```
error [2022-10-23 05:05:44.632 Z] Table creation / migration failed        caller="sqlstore/sqlstore.go:66" error="error running fix collations and charsets migration: error fetching collation: sql: no rows in result set"
fatal [2022-10-23 05:05:44.632 Z] server.NewStore ERROR                    caller="main/main.go:136" error="error running fix collations and charsets migration: error fetching collation: sql: no rows in result set"
  main.main
      /go/src/focalboard/server/main/main.go:136
  runtime.main
      /usr/local/go/src/runtime/proc.go:250
  runtime.goexit
      /usr/local/go/src/runtime/asm_amd64.s:1571
```
## Edition and Platform

 - Edition: Personal Server
 - Version: v7.4.3
 - Browser and OS: Docker on Linux

## Additional context (optional)

The failure seems coming from this PR https://github.com/mattermost/focalboard/pull/4002. By looking at the code, it checks `channel` table in MySQL database by
```
select table_collation from information_schema.tables
where table_name = 'Channels'
and table_schema=(SELECT DATABASE())
```
However I don't have `Channels` table in my MySQL database at all. Not sure if it's from mattermost servers.

cc @wiggin77

**Comment by wiggin77** [comment]
TBH I didn't know personal server could use MySQL.  I thought it was Sqlite only.  I'll fix today.
