### ISSUE TITLE
Bug: Cannot paste nor select in description's Card

### ISSUE THREAD

**Issue by backit** [mattermost/focalboard#407]
**Summary:**
In Task Card > description, cannot paste nor select anything

**Steps to reproduce the behavior:**
1. open a task card
2. click on description field
3. try to paste / select anything

**Expected behavior:**
Insert pasted text / select text

**Platform:**
 - FocalBoard Personal Desktop 0.6.7
 - OS: Linux Ubuntu 18.04

**Comment by harshilsharma63** [comment]
I'm also to reproduce this on Safari.

**Comment by coltoneshaw** [comment]
Same behavior happens with the MacOS app. However, I'm also seeing that you cannot paste into comments and you cannot copy the unsent comment text.

**Comment by harshilsharma63** [comment]
I'm working on this.
