### ISSUE TITLE
Doc: NGINX Proxy Manager Issues

### ISSUE THREAD

**Issue by pairofcrocs** [mattermost/focalboard#4072]
## Summary

Seemingly all people are having issues getting focalboard working inside of NGINX Proxy Manager (NPM)

## Link to documentation page

(https://www.focalboard.com/download/personal-edition/ubuntu/#configure-nginx)

## (Optional) Additional context and/or screenshot

I keep getting the `Websocket connection closed, connection interrupted. If this persists, check your server or web proxy configuration.` error that everyone else has been getting. Everything seemingly works, except when changes are made in the UI, it doesn't update. A manual refresh is required.

Any help with this issue would be greatly appreciated, I can make a PR to the documentation when it's solved to help everyone else.

Thanks :)

**Comment by zhzy0077** [comment]
The error sounds like a websocket issue. Have you checked 'Websockets support' in NGINX Proxy Manager?
This is my config:
![image](https://user-images.githubusercontent.com/8717471/197458242-c21cb9c3-05d2-4357-a337-693ccebe6da8.png)

**Comment by pairofcrocs** [comment]
Nope, I was an complete idiot.

After HOURS of trouble shooting I finally figured out that uBlockOrigin was blocking the websockets requests....
