### ISSUE TITLE
Bug: "SUM" is not adding up the total of column rows (remains zero)

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#4073]
Reproduced in Rainforest v7.4.3 Boards Plugin Windows 10/Chrome

## Steps to reproduce the behavior

1. Use the "Personal Tasks" template
2. Add "7" to the Number column to the right of "Buy groceries"
3. Add "2" to the Number column to the right of "Feed Fluffy"
4. Hover over "COUNT" at the bottom of the table
5. Click on "Calculate^" below the Number column
6. Observed:  "SUM" remains zero (see screenshot)

## Expected behavior

"SUM" should show 9

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/13020833/197473868-565e138a-3131-45b0-987f-21607d58bc24.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.4.3
 - Browser and OS: Windows 10 / Chrome

**Comment by lindalumitchell** [comment]
Also reproduced in Rainforest on v7.4.3 Boards Plugin MacOS / Safari.

**Comment by Pinjasaur** [comment]
While reviewing #4081 I looked into the behavior for this bug a bit closer.

I'll paste a snippet of what I [wrote there](https://github.com/mattermost/focalboard/pull/4089#pullrequestreview-1157118876):

> Seems to be related to editing property values in the table view (vs opening the table row into the card modal) not PATCHing.

**Comment by harshilsharma63** [comment]
I've tested and can confirm that #4089 fixes this.

**Comment by harshilsharma63** [comment]
Closing as the PR is already merged in main.
