### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Alderaaan** [mattermost/focalboard#4074]
Hi,

Since I downloaded and deployed the v7.4.2 focalboard, I noted when an issue with the txt block.

# Steps to reproduce the behaviour

1- Go to boards
2 - Select any board and navigate to table view
3 - Create a project with an txt column
4 - Write a comment
5 - Navigate to the board view
6- Navigate to the table view

# Expected behaviour

The txt comment disapear.

# IMG
<img width="129" alt="2022-10-24 11_49_12-Suivi IT _ Avancements" src="https://user-images.githubusercontent.com/21173299/197499344-d30aefb0-e651-4029-890c-99df34a3f7f7.png">
<img width="379" alt="2022-10-24 11_48_51-Suivi IT _ Suivi" src="https://user-images.githubusercontent.com/21173299/197499354-4ccadc0b-eb8a-4b52-9fef-aabdf06c46f7.png">

# Edition and Platform

    Edition: Personal Server and docker
    Version: [v7.4.2]
    Browser and OS: [Windows and Firefox/Edge]

Tks for your help.
Thibaut

**Comment by wuwinson** [comment]
@Alderaaan Can you provide a screen recording of your issue? We're having trouble reproducing it. Thanks!

**Comment by Alderaaan** [comment]
Yes. Attachment.
Tks
[screen-recording.webm](https://user-images.githubusercontent.com/21173299/197863780-c8bfa3dd-b5c3-47b6-b0e4-32655ee3aafb.webm)
