### ISSUE TITLE
Bug: Attempting to view board from Mattermost Windows client gets "Redirecting to error page", works from web browser

### ISSUE THREAD

**Issue by MikeSchlag** [mattermost/focalboard#4075]
## Steps to reproduce the behavior

1. Using Mattermost Windows client v5.1.1, attempt to select `Boards` view from any project tab.
2. Client displays 'Redirecting to error page' and never goes anywhere else.
3. Using Mattermost Windows client v5.1.1, use `View/Clear and reload cache` command
4. Attempt to select `Boards` view from any project; error is displayed again
5. Using web browser, use same Mattermost link and attempt to select `Boards` view from any project tab
6. Board shows successfully and is able to be interacted with

Behavior happened before and after upgrade to MM Server 7.4.0

## Expected behavior

Boards are viewable in both Mattermost client and through web browser

## Screenshots (optional)
Client view:
![image](https://user-images.githubusercontent.com/107645861/197550526-4f2ca8f6-d6cc-4d24-aa6f-ebf7815d6b20.png)

Web browser:
![image](https://user-images.githubusercontent.com/107645861/197550727-0f9c87b4-4f86-42d2-8802-49759a713551.png)

## Edition and Platform

 - Edition: Personal Desktop / On-premises Server / Mattermost Boards (plugin)
 - Mattermost Windows Client Version: v5.1.1 & v5.2.0 & 5.2.1
 - Mattermost Server Version: v7.4.0
 - Boards Version: v7.4.2
 - Browser and OS: Chrome 106.0.5249.119

## Additional context (optional)

I have not yet tried uninstalling and reinstalling the client yet, as I wanted to preserve any settings that are potentially interfering with this working properly to be able to aid in root cause discovery.

I was made an editor on the one board that is working for me via the web browser, but I'm unsure if that made any difference, as I tried the web browser method after being made an explicit editor for that board.

Attaching sanitized log (server address and server nickname) to this report.

Add any other context about the problem here, and any notes about the severity:
* Sev 3: Affects minor, non-critical functionality

Log file
[main.log.bugreport2.txt](https://github.com/mattermost/focalboard/files/9852514/main.log.bugreport2.txt)

**Comment by MikeSchlag** [comment]
Additionally, I am able to see the board in the `Linked Boards` side pane accessed from the bullseye icon.

![image](https://user-images.githubusercontent.com/107645861/197587706-d1899a3b-60ea-4b86-baf6-cdbef242b8da.png)

However, clicking on the board in this view still results in the "Redirecting to error page" message.

**Comment by ogi-m** [comment]
@wuwinson I'm unable to repro on Windows.

**Comment by FOustOri** [comment]
Had exactly the same problem when upgrading from version 7.4.0 to 7.4.2. Copying the client folder with a clean mattermost helped.

**Comment by MikeSchlag** [comment]
I’m happy to try any specific clearing of files or comparison against a clean install; assuming in that case I’d just rename my Mattermost folders and install the client again)?

**Comment by MikeSchlag** [comment]
Small update: got notification that Windows 5.2.0 client is available, did the upgrade, no change to the initial submission. Note that I have not tried a clean install, pending any requests for things to go about diff'ing between a clean install and my current install.

**Comment by wuwinson** [comment]
Thanks for the additional details @MikeSchlag!

@sbishel I just tried a fresh install of Mattermost Windows Desktop client v5.2.0, and logged into Community which is running Mattermost Server Version: v7.4.0 and Boards Version: v7.4.3, and unfortunately I was not able to repro the issue. Chrome on Windows was also working as expected.

@MikeSchlag Are you able to create a new board from the "Linked Boards" section by clicking + Add > Create a board? That should redirect you to the template picker within boards.

**Comment by MikeSchlag** [comment]
@wuwinson Using the 'bullseye' icon in the upper right of the channel view, I pick a channel that I know doesn't have any boards (or any for that entire project), click on the 'Link boards to <channel>' button that pops up in the sidebar window; a new window pops up for 'Link Boards' (none are displayed, since there are no boards), and I click 'Create a board', I immediately get the "Redirecting to error page" view from the original post.

At least within the client, I don't see any 'Add' buttons, since on the 'Boards' tab, all I get is the "Redirecting" error.

**Comment by wuwinson** [comment]
@MikeSchlag Apologies for all the back and forth. Can you share any error messages from the console? Thanks! cc @wiggin77

**Comment by MikeSchlag** [comment]
@wuwinson Which console would that be?

**Comment by MikeSchlag** [comment]
Did a fresh load of MM (full exit of client, restarted), and here's what was in there after about 2 minutes. I accessed by going to the linked channel from one of my first posts to get to the page with the error message.

![image](https://user-images.githubusercontent.com/107645861/200459186-222e4494-e627-4f84-bc09-8d1dbc65fd1d.png)

**Comment by MikeSchlag** [comment]
>  FWIW, I am unable to reproduce this issue with 5.2 client and 7.4 server.
Everything works fine for my co-workers as well, I seem to be the only one. However, I'm also the only one who came over to this team *after* they had set up boards, and I'd already been established on multiple other projects on the server. I'm just the odd one out here. :)

**Comment by MikeSchlag** [comment]
@wiggin77 Any other info that still needs captured for this? Would it be helpful for me to do a clean install (backing up the current directory) and diff any specific files?

Incidentally, still happening with upgraded  Windows client 5.2.1. Will update the original report to include that info.

**Comment by wiggin77** [comment]
@MikeSchlag can you try this with [v5.2.2](https://releases.mattermost.com/desktop/5.2.2/mattermost-desktop-setup-5.2.2-win.exe?src=dl)

**Comment by MikeSchlag** [comment]
@wiggin77 I got the 5.2.2 update last week I think, and it’s still no good.

I will ask a coworker tomorrow to try logging in on my computer to see if there’s any difference. Also just about at the point of renaming my MM directory and installing clean, so I can diff the files and see what’s different.

**Comment by MikeSchlag** [comment]
@wiggin77 Sorry for the delay, finally got back onto my computer after break, and here's what I've tried/found.

1. I tried renaming my `mattermost-desktop` directory to `mattermost-desktop-backup` and running the installer. Mattermost came back up with no differences as seen by BeyondCompare doing a directory compare. Boards still do not work.

2. I ran `UninstallMattermost.exe`, redownloaded the installer completely fresh, and installed again. Same as #1, no directory differences, and boards do not work.

I noticed that after uninstalling, I did not have to enter my server info or anything, so I found the Mattermost data in the `Roaming` folder, and renamed that, uninstalled MM, and re-installed. Once I set everything back up, boards are now working within the client.

I ran another BeyondCompare on the directories, and the results are summarized in the picture. Anything in particular you'd like me to dig into for specific diffs? Left side is fresh install, right side is previous/backed up data.

![image](https://user-images.githubusercontent.com/107645861/210637309-785e1655-8a06-4b12-bcbb-287e6b211b8f.png)

**Comment by wiggin77** [comment]
> Once I set everything back up, boards are now working within the client.

Thanks @MikeSchlag.  Is the above to mean that a truly fresh install of desktop client is working for you?

**Comment by MikeSchlag** [comment]
Yes, a fully cleared (manually cleared roaming folder plus uninstalled then reinstalled client) works just fine now.

**Comment by wiggin77** [comment]
Thanks @MikeSchlag.  I'm interpreting your last comment to mean that you have resolved the issue.  I'll close this.  Please re-open if needed.  Thanks.
