### ISSUE TITLE
Bug: The value in Number Field disappear when we change a board view

### ISSUE THREAD

**Issue by KakEgorka** [mattermost/focalboard#4081]
## Steps to reproduce the behavior

1. Enter the Mattermost Boards and create issue 
2. Edit issue in boards view and fill the number type field
3. Close the edit screen and change a view to "table"

## Expected behavior

The number field must be filled after we change the board view 

## Screenshots (optional)

https://user-images.githubusercontent.com/109951790/197762365-441909dd-e1c2-44f0-ae3b-40f3a6ab2489.mp4

## Edition and Platform

 - Edition:Mattermost Boards (plugin)
 - Version: v7.4.3
 - Browser and OS: [Mac, Windows]

**Comment by Pinjasaur** [comment]
Will need to investigate further, potentially related to #4073.

**Comment by Pinjasaur** [comment]
Similar to #4074.

**Comment by Pinjasaur** [comment]
OK, I'm able to reproduce the behavior across a `Text` and `Number` property (which confirms #4074). I didn't try every property type but it seems limited to Text and Number, at least in basic testing.

Steps:

1. Go to a Board View
2. Edit the property of a card
3. Switch to a non-Board View e.g. Table, Calendar, Gallery
4. Notice the property briefly shows the updated value and reverts back to pre-edit

This behavior doesn't happen if you reload the page _after_ step 2 and _before_ step 3. Something funky is happening client side where the property is getting `PATCH`-ed back to the initial value which results in this data loss.

**Comment by Pinjasaur** [comment]
@harshilsharma63 this might be related to your #4073—seems possible due to similar circumstances of property values not "sticking" like they should. I haven't spent much time looking into that specific behavior. If you're able to look into #4073 and find anything let me know and we can sync tomorrow. Otherwise I'll continue the investigation tomorrow. cc @sbishel
