### ISSUE TITLE
Bug:  Cannot run the Windows standalone app

### ISSUE THREAD

**Issue by eiminola** [mattermost/focalboard#4082]
windows personal( standalone) version.

In windows, when I download and install Focalboard from Microsoft Store everything works perfect, but the problem with Microsoft Store is this: the Focalboard version which is there is old, it is for 5 months ago.  
When I want to use the last version of  Focalboard which in the release part of GitHub repo, after downloading the zip file( Focalboard-win) and extracting it and double clicking on Focalboard.exe nothing happens. 
I uninstalled the version from Microsoft Store and restart my laptop, also used Windows 10 compatibility troubleshooting and default graphics change, but the app didnt work, just nothing happens.
webview2 in installed on my windows 10, I have MS Edge.
thanks in advance.

**Comment by alevinetx** [comment]
@eiminola  Did you check the security on the exe?  I didn't have any problems, other than Windows telling me it couldn't verify the publisher and gave me an option to continue running.

![image](https://user-images.githubusercontent.com/5067356/198734482-2f41ef31-76e6-4a00-a7f7-9f0612c352ad.png)

**Comment by eiminola** [comment]
@alevinetx thank you for your contributions.
I used to do direct zip extract, but after seeing your comment I did copying from zip archive and then pasting into a folder, but nothing has changed, Windows has no reaction.

As you see there is no security section in the properties of exe file.
![image](https://user-images.githubusercontent.com/51320663/198822335-078be24f-02a2-4923-80d8-3e3a1a023d22.png)

**Comment by wiggin77** [comment]
@eiminola , I tried reproducing this problem using Windows 11 and the latest release [focalboard-win.zip](https://github.com/mattermost/focalboard/releases/download/v7.4.3/focalboard-win.zip)   I did have to unblock the executable as alevinetx indicated above.  

Are there any errors in Event Viewer?

**Comment by eiminola** [comment]
@wiggin77, thanks for your reply, I checked Event Viewer but didn't see any error there or maybe don't know where it is, but I made another local Windows account on my pc and logged in it, Focalboard.exe worked properly there, I don't know which installed program in my main Windows account is preventing Focalboard.exe being launched.

**Comment by wiggin77** [comment]
> I made another local Windows account on my pc and logged in it, Focalboard.exe worked properly there, I don't know which installed program in my main Windows account is preventing Focalboard.exe being launched.

@eiminola just want to check if you are still having this issue.  If so, could you try unblocking the file using the utility here:  https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/unblock-file?view=powershell-7.3

**Comment by wiggin77** [comment]
@eiminola I'm going to close this due to inactivity.  If you are still having issues please re-open.

**Comment by nkz-soft** [comment]
I have the same problem on the [latest release](https://github.com/mattermost/focalboard/releases/tag/v7.9.3). I tried using Unblock-File, but without success.

**Comment by eiminola** [comment]
@nkz-soft I removed the folder containing database which is located in "Documents" folder of Windows and the problem was solved. 
It seems the database file remained from previous versions conflicts with the new one. Each time you download a new version of Focalboard you should delete the Focalboard database folder of previous version from Windows' "Documents". To transfer your data you may make an export in the previous Focalboard and an import in the new one. @wiggin77
