### ISSUE TITLE
Bug: Offline Mattemost instance - Icon emoji preview not loaded due to unpkg.com reference on boards

### ISSUE THREAD

**Issue by TheMasterFX** [mattermost/focalboard#4084]
## Steps to reproduce the behavior

1. Install a Mattermost instance in an offline environment (no connection to internet)
2. Go to Boards => Create New Board (from any Template you like)
3. Open a Task
4. Click on the Symbol => Pick icon => Preview is empty

## Expected behavior
Preview of icon is visible

## Observed behavior (that appears unintentional)
No Icon preview visible due to reference to (hardcoded?) background-image: url("https://unpkg.com/emoji-datasource-apple@5.0.1/img/apple/sheets-256/64.png");

## Possible fixes
Make sheets-256/64.png offline available

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/12451336/197854459-28b29847-024b-42e4-91e4-b45f216a8e4f.png)

## Edition and Platform

 - Edition: Personal Server with Mattermost Boards (plugin)
 - Version: 7.4.0
 - Browser and OS: Chrome + Firefox + Desktop App on Windows

**Comment by wuwinson** [comment]
@harshilsharma63 Is this something that we can change on our end? Thanks! cc @sbishel

**Comment by harshilsharma63** [comment]
@TheMasterFX thanks for creating this issue 🙌

@wuwinson this definitely seems fixable. I'll look into this.
