### ISSUE TITLE
Doc: Personal server setup guide out of date

### ISSUE THREAD

**Issue by michkrej** [mattermost/focalboard#4086]
## Summary

Currently the instructions on how to setup focalboard locally aren't correct. You have to clone mattermost-server and add an environment variable to the focalboard repo before running *make* for everything to work correctly. 

## Link to documentation page

[README](https://github.com/mattermost/focalboard/blob/main/README.md)
[Personal server setup guide](https://developers.mattermost.com/contribute/more-info/focalboard/personal-server-setup-guide/#build-via-the-terminal)

## Additional context and/or screenshot

Made a quick edit of how the text could be formulated in the readme to better explain the setup. 

<img width="502" alt="image" src="https://user-images.githubusercontent.com/25232126/197987433-2b505872-4a70-41d6-8a4e-4624ef055cdb.png">

I'll gladly submit a pull request for these changes if you guys thing this is something that should be updated! :)

On another note I also saw that the .gitignore file isn't ignoring .env files, is that on purpose?

**Comment by michkrej** [comment]
I'll gladly submit a pull request for these changes if you guys thing this is something that should be updated! :) 

On another note I also saw that  the focalboard repo isn't ignoring .env files, is that on purpose?

**Comment by wuwinson** [comment]
@michkrej Yes a PR would be awesome, thank you so much! cc @justinegeffen

**Comment by michkrej** [comment]
@justinegeffen the pull request can be found above when you have time to look at it!

**Comment by justinegeffen** [comment]
Thank you, @michkrej! :)
