### ISSUE TITLE
Bug: Title cell in read-only table view should not appear to be editable

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#410]
**Steps to reproduce the behavior:**
1. Share a board with a table view
2. Click on the title of a row in the read-only table view
3. It appears to be editable (but is not)

**Expected behavior:**
It should not appear to be editable. Perhaps removing the white border around the input field would be sufficient?

**Screenshots:**
<img width="427" alt="table-view readonly editable" src="https://user-images.githubusercontent.com/46905241/118052938-7ce73600-b338-11eb-9e29-f4c3e7b6b60b.png">

**Platform:**
 - Chrome 89 on macOS 10.15.7

**Comment by Johennes** [comment]
We could maybe make the background transparent when the field is in read-only mode. That's rather easy to implement and would work regardless of the background of the field's parent element. I opened #452 to demonstrate this proposal.
