### ISSUE TITLE
Bug: Can't connect to Boards from Channels

### ISSUE THREAD

**Issue by mdiehlenator** [mattermost/focalboard#4108]
## Steps to reproduce the behavior

Using MM Desktop v. 5.1.1 or the web client using Firefox, I am unable to go from using a Channel to using the Boards plugin.  When I try, I am asked to log in again.  Providing the correct credentials doesn't result in access to my Boards.

## Expected behavior

I should be able to login into MM and use the Channels and Boards.

## Screenshots (optional)

None

## Additional context (optional)

I am running MM Teams Edition 6.3 under Docker and using NGNX Proxy Manager to manage TLS.  I understand that this is an older version, so if "upgrade to the latest version" is the solution to this issue, I'll accept that.  However, I'm submitting this ticket as requested at https://community.mattermost.com/core/pl/bsn8u8xpepyn5ecu3zribtptia

## Add any other context about the problem here, and any notes about the severity:

I'm about to restart the docker container to see if this fixes the problem.  I'll update the ticket.

I've attached a current log file.

[_mattermost_1_logs.txt](https://github.com/mattermost/focalboard/files/9902226/_mattermost_1_logs.txt)

**Comment by mgdelacroix** [comment]
Closing for now, please feel free to reopen if needed
