### ISSUE TITLE
Bug: Cursor flew to the end of line after any input in comment field

### ISSUE THREAD

**Issue by MioAtSwivel** [mattermost/focalboard#4113]
## Steps to reproduce the behavior

1. Go to any item created in a board
2. Open it
3. Input something to "add the comment..." field
4. Try insert characters at the middle of your typed words
5. Cursor flew to the end of line after any input

## Expected behavior

Cursor should continue to stay at the spot (just how usually you would expect from using any text editor)

## Screenshots (optional)

![CleanShot 2022-11-01 at 14 31 09](https://user-images.githubusercontent.com/102662641/199173085-8ea12692-0617-467d-afb4-376ab578d83e.gif)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: Mattermost version 7.4.1-rc1
 - Browser and OS: Desktop Application on MacOS, Chrome on MacOS (possibly any browser exhibit same issue)

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:

* Sev 2: Affects minor to moderate functionality, depending on team reliance on commenting

**Comment by wuwinson** [comment]
Thanks for reporting @MioAtSwivel! This is fixed as of `v7.4.2` - please download the [latest release](https://github.com/mattermost/focalboard/releases) for the fix. Thanks!
