### ISSUE TITLE
Bug: MySQL migrations search for collation and charset on nonexistent Channels table

### ISSUE THREAD

**Issue by LINKIWI** [mattermost/focalboard#4123]
## Steps to reproduce the behavior

1. Configure MySQL storage.
2. Start the focalboard-server binary.
3. See an error that migrations failed.

## Expected behavior

The binary starts and starts serving over HTTP.

## Edition and Platform

 - Edition: Personal Server
 - Version: 7.4.3
 - Browser and OS: Ubuntu Server 16.04, MySQL 5.7, Go 1.18.7 (server compiled from source)

## Symptom

Focalboard server startup fails to apply migrations, yielding the following error:

```
fatal [2022-11-02 00:24:24.930 -07:00] server.NewStore ERROR caller="main/main.go:136" error="error running fix collations and charsets migration: error fetching collation: sql: no rows in result set"
```

## Root cause

The migration code path attempts to check for collation details from a table called "Channels" which does not exist in the database.

https://github.com/mattermost/focalboard/blob/v7.4.3/server/services/store/sqlstore/data_migrations.go#L742

The actual database schema:

```
mysql> show tables;
+-----------------------+
| Tables_in_focalboard  |
+-----------------------+
| blocks                |
| blocks_history        |
| board_members         |
| board_members_history |
| boards                |
| boards_history        |
| categories            |
| category_boards       |
| db_lock               |
| file_info             |
| notification_hints    |
| preferences           |
| schema_migrations     |
| sessions              |
| sharing               |
| subscriptions         |
| system_settings       |
| teams                 |
| users                 |
+-----------------------+
19 rows in set (0.00 sec)
```

I fixed this issue by removing the post-migration collation check, given that I know in advance the collation is configured correctly already. I don't have context on the "Channels" table but I suspect this is just a bug and we should be checking against a known table instead.

**Comment by zhzy0077** [comment]
Sounds like a dup of https://github.com/mattermost/focalboard/issues/4067

**Comment by wuwinson** [comment]
@LINKIWI [Release v7.4.4](https://github.com/mattermost/focalboard/releases/tag/v7.4.4) is now out and has a fix for this issue. Please feel free to re-open this ticket if you're still having issues. Thanks!
