### ISSUE TITLE
Bug: Update issue from 7.2 to 7.2.1

### ISSUE THREAD

**Issue by VardanAb** [mattermost/focalboard#4143]
## Steps to reproduce the behavior

1. Download mattermost-plugin-focalboard.tar.gz for 7.2.1 version from https://github.com/mattermost/focalboard/releases
2. In mattermost go **System Console** -> **PLUGINS** -> **Plugin Management** and upload plugin
3. Focalboard fails to start with the below critical error.

## Expected behavior

It can not run some sql queres

## Screenshots (optional)

`This plugin failed to start. error initializing the DB: driver: postgres, message: failed to execute migration, command: executing_query, originalError: pq: constraint "focalboard_blocks_pkey1" of relation "focalboard_blocks" does not exist, query: ALTER TABLE focalboard_blocks DROP CONSTRAINT focalboard_blocks_pkey1; ALTER TABLE focalboard_blocks ADD PRIMARY KEY (id); CREATE INDEX idx_blocks_board_id_parent_id ON focalboard_blocks (board_id, parent_id);CREATE INDEX idx_subscriptions_subscriber_id ON focalboard_subscriptions (subscriber_id);`
I![image](https://user-images.githubusercontent.com/88328485/199822723-4cc72c98-4def-429b-beda-d1e077c5267e.png)

## Edition and Platform

 - Edition: Mattermost 7.4
 - Version: 7.2 upgrade to 7.2.1

**Comment by VardanAb** [comment]
> Hi @VardanAb! Could you please post the list of tables prefixed with `focalboard_` that you currently have on the database and the contents of the `focalboard_schema_migrations` table?

![image](https://user-images.githubusercontent.com/88328485/205655109-101eb4ff-e8eb-4b05-9f15-ee59b4bd1def.png)

**Comment by mgdelacroix** [comment]
Thanks for the information! Could you please share the output of running `\d focalboard_blocks` inside the database?

**Comment by VardanAb** [comment]
> Thanks for the information! Could you please share the output of running `\d focalboard_blocks` inside the database?

@mgdelacroix Output of running \d focalboard_blocks

![image](https://user-images.githubusercontent.com/88328485/206173439-be85fc83-646d-465b-b438-71e6edd80ede.png)

**Comment by mgdelacroix** [comment]
Thanks @VardanAb, it seems that the name of the index is not the one the migration is expecting, please try running:

```sql
ALTER INDEX focalboard_blocks_pkey RENAME TO focalboard_blocks_pkey1;
```

and try to run the migrations again restarting the plugin.

**Comment by VardanAb** [comment]
> \d focalboard_blocks

**Comment by VardanAb** [comment]
ALTER INDEX focalboard_blocks_pkey RENAME TO focalboard_blocks_pkey1;

It's work, 
Thank you
