### ISSUE TITLE
Search failed with a new item

### ISSUE THREAD

**Issue by Alderaaan** [mattermost/focalboard#4150]
### Discussed in https://github.com/mattermost/focalboard/discussions/4149

<div type='discussions-op-text'>

<sup>Originally posted by **Alderaaan** November  5, 2022</sup>
Hi,
I created a new table, and when I search some words, the page appear to be white.
When I use a default template, It's work.

What I missed ?
Tks

Focalboard on docker.
**Docker install :** mattermost/focalboard:edge

[screen-recording(1).webm](https://user-images.githubusercontent.com/21173299/200119841-358ecd87-3bd5-4939-b282-3dd39b889336.webm)
</div>

**Comment by wuwinson** [comment]
@Alderaaan You may be facing a similar issue as https://github.com/mattermost/focalboard/issues/4092. Can you provide more details on the error from the console? Thanks! cc @sbishel

**Comment by Alderaaan** [comment]
@wuwinson , ok I didn't see it.
You pushed on the edge also ? I can try to reproduce it.

Witch command do you tape for this logs ?

**Comment by Alderaaan** [comment]
@wuwinson , I tried with the edge and main (7.4.4) release and the issue is still present.
I can't connect tothe container to see the logs. 

[screen-recording(2).webm](https://user-images.githubusercontent.com/21173299/201685745-c621b1f6-57c0-4194-beaf-86be5077cf68.webm)

**Comment by Pinjasaur** [comment]
@Alderaaan if you can help us debug this locally by providing a few additional details that would be much appreciated:

1. can you export that board you're using (remove any sensitive data please) to a `.boardarchive` and share it here?
2. can you share what search term(s) are causing the error? 
3. can you share any relevant console errors?

thanks!
