### ISSUE TITLE
Bug: Missing standard templates

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#4170]
## Steps to reproduce the behavior

1. Go to template editor
2. See error

## Expected behavior

All old and new standard templates are available.

## Screenshots (optional)

![Screen Shot 2022-11-08 at 12 18 46 PM](https://user-images.githubusercontent.com/93531870/200632904-16612af7-b91e-4b25-9bd3-1f191daba43b.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.5 Bug Bash
 - Browser and OS: Chrome on Mac

**Comment by sbishel** [comment]
Here is the error from the server. 
```
{"timestamp":"2022-11-08 17:09:21.361 Z","level":"error","msg":"InitializeTemplates failed","caller":"app/plugin_api.go:976","plugin_id":"focalboard","error":"\"cannot initialize global templates for team 0: cannot import board b7wnw9awd4pnefryhq51apbzb4c: cannot add member to board: createBoardsCategory error fetching user's team's boards: GetUser: Unable to find the user.\""}
```
