### ISSUE TITLE
Bug: Linked boards do not automatically appear on your sidebar

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#4179]
## Steps to reproduce the behavior

1. Go to a linked board where you are not an explicit member
2. Check your sidebar
3. See error - board does not appear on your sidebar even after you open the board

## Expected behavior

Board appears on your sidebar as long as you're a member of the linked channel

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/200690691-3656bb18-cfed-4b18-8cff-6566191bef6b.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.5 Bug Bash
 - Browser and OS: Chrome on Mac

**Comment by harshilsharma63** [comment]
@wuwinson works for me both on `boards-bugbash75` and locally. I've linked a private board 'Harshil Test` in Town Square in Focalboard team. Try opening that up and see if you see that one in LHS or not.

**Comment by harshilsharma63** [comment]
@wuwinson this was fixed by #4200 about a day or two after you created this issue. Can you please try it on latest `main`? LMK if you want me to upload the latest build somewhere.

**Comment by wuwinson** [comment]
Thanks @harshilsharma63! I'll verify during our bug bash later this week and get back to you.

**Comment by harshilsharma63** [comment]
@wuwinson can you verify this? I've tested this locally as well on a HA cloud server. IT works fine everywhere.

**Comment by wuwinson** [comment]
Yep working now, thanks @harshilsharma63! Closing out.
