### ISSUE TITLE
Bug: Dates with empty values don't update when moving cards on calendar view

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#4181]
## Steps to reproduce the behavior

1. Create a card with an empty date property
2. Go to calendar view
3. Display by the date property
4. Move the card from step 1 to another date
5. See error - date on the property is not updated

## Expected behavior

Cards should not appear on the calendar if they do not have a date on the date property. Date property is updated based on the date selected. Works find on cards with existing dates on the date property.

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/200697467-69207976-a0b8-4da5-8431-3c35a89cf400.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.5 Bug Bash
 - Browser and OS: Chrome on Mac

**Comment by sbishel** [comment]
Actually, these cards should not show up if they don't have a date property. Appears they are displaying on "today" if date property is empty.

**Comment by wuwinson** [comment]
Updated, thanks!
