### ISSUE TITLE
Bug: Undeleting a board does not restore original memberships and permissions

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#4195]
## Steps to reproduce the behavior

1. Create a board
2. Add members to the board, with various permissions
3. Add at least one person property and set to added user
4. Delete the board
5. Undelete the board (ctrl-z)
6. Notice the board members added in step 2 are gone
7. Notice any person property values that contained the missing people are empty

## Expected behavior

Membership and permissions are restored when undeleting a board

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.5 (bug bash)
 - Browser and OS: FF & Linux

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by mgdelacroix** [comment]
Can't reproduce neither on `main` nor `release-7.5` (`v7.5.4` by now). Found that the channel link is not restored with the rest of the board, but managing this as something different on https://github.com/mattermost/focalboard/issues/4360 as it can be intentional
