### ISSUE TITLE
Bug: Emoji selection is severely limited after update

### ISSUE THREAD

**Issue by justinegeffen** [mattermost/focalboard#4205]
## Steps to reproduce the behavior

I updated my Mattermost desktop app and noticed that the emoji selection was very different to the usual. The random emojis aren't listed in the selection and very few of the ones I currently use are.

1. Open a card.
2. Select the emoji and select "Select icon".
3. Scroll through the list to see the limitations.

## Expected behavior

I expected the full selection of emojis to be available that match my currently used ones.

## Screenshots (optional)
![Screen Shot 2022-11-14 at 20 05 20](https://user-images.githubusercontent.com/4223530/201734240-314983fc-8d77-459c-b029-977d13e3a365.png)

![Screen Shot 2022-11-14 at 20 05 27](https://user-images.githubusercontent.com/4223530/201734275-920413e4-79e1-4dc8-823e-af147865c2a8.png)

## Edition and Platform

 - Edition: Mattermost Boards on desktop 
 - Version: v7.5
 - Browser and OS: Firefox on Mac

## Additional context (optional)

* Sev 3: Affects minor, non-critical functionality

**Comment by justinegeffen** [comment]
The random emoji isn't available in the selection provided.
![Screen Shot 2022-11-14 at 20 10 23](https://user-images.githubusercontent.com/4223530/201734599-0a52f087-16af-482f-ac9d-d1e636be7c6b.png)

**Comment by harshilsharma63** [comment]
On it.
