### ISSUE TITLE
Bug: label not removeable

### ISSUE THREAD

**Issue by MarkusBeer** [mattermost/focalboard#4214]
## Steps to reproduce the behavior

1. Go to any car
2. Add a label
3. Try to remove label by clear button
4. See error - nothing happens

## Expected behavior

The label should get removed

## Screenshots (optional)

![grafik](https://user-images.githubusercontent.com/94354455/202118101-9d8ce780-4dca-49ee-a5c4-d93026c0a208.png)

## Edition and Platform

 - Edition: Personal Server 
 - Version: 7.4.4
 - Browser and OS: Firefox/Edge on Windows

**Comment by wuwinson** [comment]
@ogi-m Can you try to repro this with a multi-select property on Firefox/Edge on Windows? We're not seeing a `Clear` button on our side. Thanks!

**Comment by wuwinson** [comment]
Thanks for clarifying @MarkusBeer! @ogi-m Can you try to repro? I just tested on Firefox and Windows on our test Personal Server and I'm still not seeing a `Clear` button.

![image](https://user-images.githubusercontent.com/93531870/204344101-22d55ec9-7f0b-4e00-baae-9724c2d5a269.png)

**Comment by wuwinson** [comment]
@MarkusBeer We're able to see the `Clear` button now, but it's working fine for us. Can you provide us with a console log to help us investigate? Thanks!

**Comment by MarkusBeer** [comment]
Hello. OnClick i dont get any console log in browser. OnLoad of card i get missing option error:
![grafik](https://user-images.githubusercontent.com/94354455/204988524-d0591d48-d1b0-4fc1-930c-5fda581de844.png)

**Comment by wuwinson** [comment]
@MarkusBeer Are you able to clear individual tags with the `x` button? Can you also share any log messages from the server?

**Comment by wuwinson** [comment]
Sorry @MarkusBeer we are unable to reproduce this issue. Please feel free to re-open if you're still having this issue. Thanks!
