### ISSUE TITLE
Bug: Focalboard personal server unconditionally binds to any-address instead of localhost

### ISSUE THREAD

**Issue by qlyoung** [mattermost/focalboard#4224]
## Steps to reproduce the behavior

1. Install focalboard personal server
2. Run focalboard personal server
3. Observe that the server binds to `:::8000` and `:::9092` instead of ports on a loopback address
4. Observe in the docs that there is [no configuration open to change this](https://docs.mattermost.com/boards/focalboard/installing-boards.html#personal-server-configuration)

## Expected behavior

I expected the listen address to be configurable in addition to the port. This is table stakes for server software, so it's possible I'm mission the option somewhere - if so, would appreciate being shown where it is!

## Screenshots (optional)

If applicable, add screenshots or a screen recording to elaborate on the problem.
```
root@host /h/qlyoung# netstat -tlnp | grep focal
tcp6       0      0 :::8000                 :::*                    LISTEN      1285679/focalboard-
tcp6       0      0 :::9092                 :::*                    LISTEN      1285679/focalboard-
```

## Edition and Platform

 - Edition: Personal Server
 - Version: 7.1.0
 - Browser and OS: Firefox on Linux

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 2: This is a security risk

**Comment by olaysco** [comment]
> 4. Observe in the docs that there is [no configuration open to change this](https://docs.mattermost.com/boards/focalboard/installing-boards.html#personal-server-configuration)

I don't think this statement is true anymore, there's an option named `localOnly` in the [configuration](https://docs.mattermost.com/boards/focalboard/installing-boards.html#personal-server-configuration) that allows limiting the listening address to localhost.

This is the code section that checks for the value of this option:
https://github.com/mattermost/focalboard/blob/f1a190d4d6bb1ababd55b3ea2628501fc859fa65/server/web/webserver.go#L48-L50

@qlyoung @wuwinson

**Comment by qlyoung** [comment]
Hm, looks like the option has been there for a long time, but perhaps was not documented until recently, or I missed it (equally likely). Thanks for pointing this out.
