### ISSUE TITLE
Bug: Disappearing content in Boards desktop app

### ISSUE THREAD

**Issue by johndavidlugtu** [mattermost/focalboard#4231]
## Steps to reproduce the behavior

1. Go to Boards
2. Create a new card
3. Add title and content
4. Close card
5. See if content is lost

## Expected behavior

Content is not lost

## Screenshot

Loom video: https://www.loom.com/share/bf69b52c20cf4814b7e26a118aa815e1

**Comment by wuwinson** [comment]
@johndavidlugtu Can you provide more details on your version and edition?

## Edition and Platform

 - Edition: Personal Desktop / Personal Server / Mattermost Boards (plugin)
 - Version: [e.g. v0.15.0]
 - Browser and OS: [e.g. Chrome on Mac, Edge on Windows]

**Comment by johndavidlugtu** [comment]
Edition and Platform
Edition: Mattermost Boards (plugin)
Version: 
<img width="219" alt="Screen Shot 2022-11-23 at 12 11 45 AM" src="https://user-images.githubusercontent.com/101303489/203364442-d19e4754-3f9e-4b6f-80f7-1b8e61c24f0f.png">

Browser and OS: Desktop app, macOS Monterey 12.6

@wuwinson you should also now have access to the Loom video. Let me know if that's not the case!

**Comment by wuwinson** [comment]
Fixed in https://github.com/mattermost/mattermost-server/pull/21737
