### ISSUE TITLE
Server Unit Tests - ./app/sharing.go

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#424]
Write Unit Tests for ./server/app/sharing.go.

use mock for store layer
see ./server/app/auth_test.go and ./server/app/blocks_test.go for samples.

**Comment by matheusmosca** [comment]
Hi @sbishel. Can I take this one :smile:?

**Comment by sbishel** [comment]
@matheusmosca, Thank you. I will review this evening.
