### ISSUE TITLE
Bug: File Attachments > `...` button is transparent

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#4240]
## Steps to reproduce the behavior

1. Go to a card
2. Add an attachment
3. Hover over the `...` button
4. Note it is transparent and overlaps the file name

## Expected behavior

File name shouldn't be visible through the button

## Screenshots (optional)

<img width="633" alt="image" src="https://user-images.githubusercontent.com/15314183/203612296-bf062f56-e964-4556-a263-541db0761ef7.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.6
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment]
File name doesn't overlap with the Option button on Channels:
![Screen Shot 2022-11-28 at 3 14 42 PM](https://user-images.githubusercontent.com/93531870/204372144-d98cdbc9-ee89-47b1-b93f-cd45f3107165.png)
