### ISSUE TITLE
Bug: Many channels are not marked and the red badge do not show on Dock icon to indicate unread messages

### ISSUE THREAD

**Issue by apieceoy** [mattermost/focalboard#4248]
## Steps to reproduce the behavior

1. In recent days, many channels are not marked and the red badge do not shown on Dock icon to indicate unread messages.
2. It usually happens on private channels, but the mentions and direct messages work correctly.
3. I do not mute the channels, and others also have this problem.
4. Upgrade to 7.5.1 from 5.37.10 can't solve. (self-hosted)

## Expected behavior

Correctly show red badge on Dock icon and mark channels to indicate unread messages

## Edition and Platform

 - Edition: Personal Desktop, Personal iPhone
 - Version: 5.2.1 (Desktop)
 - Browser and OS: Chrome on Mac, Desktop on Mac, Mattermost APP on iPhone

**Comment by amyblais** [comment]
@apieceoy Would you be open to re-opening this issue at https://github.com/mattermost/mattermost-server/issues? Do you see any errors in the Mattermost server logs?

**Comment by apieceoy** [comment]
Okey, I have reopened at https://github.com/mattermost/mattermost-server/issues/21763
I don't see any special errors in server logs.
