### ISSUE TITLE
Bug: docker build returns non-zero code: 2 on EC2

### ISSUE THREAD

**Issue by arditobryan** [mattermost/focalboard#4249]
I have cloned the repo on an EC2 linux and installed docker, then executed the following command as per instructions:
My EC2 has 4GB memory, 70GB space

`docker build -f docker/Dockerfile -t focalboard .`

This is the output I am getting:
```
# github.com/mattermost/focalboard/server/api
api/insights.go:116:31: undefined: model.GetStartOfDayForTimeRange
api/insights.go:234:31: undefined: model.GetStartOfDayForTimeRange
# github.com/mattermost/mattermost-server/v6/store/sqlstore
/go/pkg/mod/github.com/mattermost/mattermost-server/v6@v6.0.0-20220802151854-f07c31c5d933/store/sqlstore/store.go:1022:41: undefined: mysql.Config
/go/pkg/mod/github.com/mattermost/mattermost-server/v6@v6.0.0-20220802151854-f07c31c5d933/store/sqlstore/store.go:1029:60: undefined: postgres.Config
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function 'sqlite3SelectNew':
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
       |          ^~~~~~~
make: *** [Makefile:71: server-docker] Error 2
The command '/bin/sh -c EXCLUDE_PLUGIN=true EXCLUDE_SERVER=true EXCLUDE_ENTERPRISE=true make server-docker os=${TARGETOS} arch=${TARGETARCH}' returned a non-zero code: 2
```

**Comment by sbishel** [comment]
@wiggin77 - Could this be a MPA issue where docker is using the wrong mm-server?

**Comment by wiggin77** [comment]
Yes, this the symptom when using a older mattermost-server repo.

**Comment by wiggin77** [comment]
@arditobryan have you also cloned the [mattermost-server](https://github.com/mattermost/mattermost-server) in a sibling directory to focalboard?

**Comment by arditobryan** [comment]
Hi @wiggin77 thank you for following the issue. 
No, I haven't. I followed the instructions in this repo and:
- Cloned the repo
- Executed this command: docker build -f docker/Dockerfile .

**Comment by wiggin77** [comment]
Thanks @arditobryan.  Please clone [mattermost-server](https://github.com/mattermost/mattermost-server) and then delete any `go.work` file found in the focalboard repo root.  Then run your docker command again.

**Comment by wiggin77** [comment]
> I followed the instructions in this repo and:

Do you mean the [instructions here](https://github.com/mattermost/focalboard#getting-started)?

**Comment by bwskin** [comment]
I also have this problem. Last commit I've been able to build is `b582e5920c54f353b99625e1326b24b401a27b90` (found using git bisect)

**Comment by wiggin77** [comment]
@bwskin are you getting the same error as reported above?  That error indicates building with an outdated [mattermost-server](https://github.com/mattermost/mattermost-server).  It may be necessary to delete the go.work files.

**Comment by wiggin77** [comment]
@arditobryan and @bwskin I was able to reproduce this locally.  I'll figure out a fix.  Thanks.

**Comment by wiggin77** [comment]
This will be fixed via https://github.com/mattermost/focalboard/pull/4271   You can wait for the merge, or you can run `go get github.com/mattermost/mattermost-server/v6@master` in your focalboard/server directory.
