### ISSUE TITLE
Server Unit Tests - ./app/workspaces.go

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#425]
Write Unit Tests for ./server/app/workspaces.go

use mock for store layer
see ./server/app/auth_test.go and ./server/app/blocks_test.go for samples.

**Comment by majidsajadi** [comment]
im working on this

**Comment by chenilim** [comment]
Thanks @majidsajadi!

**Comment by Prassud** [comment]
Hi @cpanato, started working on this issue, will raise with in this week.
