### ISSUE TITLE
Bug: Android Boards not working in mattermost app

### ISSUE THREAD

**Issue by bcfdadmin** [mattermost/focalboard#4256]
## Steps to reproduce the behavior

Just downloaded the newest mattermost app off google play, logged in as a admin, clicked on the line @admin linked the board XXXXX with this channel. Once the link is clicked it opens up focalboard in the top right corner, displays a white screen, and doesn't load anything

## Expected behavior

Expected it to open the board that was linked

## Screenshots (optional)

If applicable, add screenshots or a screen recording to elaborate on the problem.

**Comment by wuwinson** [comment]
@bcfdadmin Can you provide any screenshots or video to help us investigate? Thanks! cc @ogi-m @sbishel

**Comment by bcfdadmin** [comment]
This is what it hangs on just a white screen with focal board in the top 
left corner


Steven Berg
Bonneville County Fire District
Chief Technology Officer

**Comment by wuwinson** [comment]
@bcfdadmin Thanks for your response, but we still don't see any attachment. Can you reattach again? Thanks!

**Comment by bcfdadmin** [comment]
I do show that the attachment is there, it's a white screen but if you look
at the top you can see what it was taken from the cell phone at 1:51. In
the top left it ways focalboard, top right displays battery is 66%. It is a
PNG file.

I can upload it again if you are not seeing what I am seeing.

[image: image.png]

**Comment by wuwinson** [comment]
Hi @bcfdadmin, thanks for your response! This is what we're seeing on our end:

![Screen Shot 2022-12-12 at 3 25 29 PM](https://user-images.githubusercontent.com/93531870/207147314-80971e0e-e5cc-48d6-a533-fe79903b2e58.png)

It sounds like you're trying to access Boards from the Mattermost mobile app and getting to a blank screen. Boards is currently not natively supported in the MM app yet. What you should be seeing instead, is a screen where it asks you to "View in App" or "View in Browser". From there, you'll be asked to login, where you'll get access to Boards in a mobile web-view.

Can you provide more details on whether the blank screen is in-app or opening a browser? Can you provide more details on your phone, your Mattermost mobile app version, and the Mattermost server version? Thanks!

**Comment by bcfdadmin** [comment]
That is correct, trying to access it through the mobile application. it
does not state view in app or view in browser, just hangs out with that
white screen.

Tried 2 different phones, one is a samsung galaxy note 20 ultra, the other
is a google pixel 6. the mobile app is 1.55.1 and the server version is
self hosted team edition

**Comment by wuwinson** [comment]
@harshilsharma63 Can you repro this issue? Thanks! cc @sbishel

**Comment by harshilsharma63** [comment]
@bcfdadmin just to confirm, are you in the "Mattermost" app or the "Mattermost Beta" app? I can reproduce the issue on "Mattermost" app but on "Mattermost Beta" it opens the link in the browser.

**Comment by bcfdadmin** [comment]
It is on the matter most app downloaded directly off play store


Steven Berg
Bonneville County Fire District
Chief Technology Officer

**Comment by harshilsharma63** [comment]
Okay, so we're developing a brand new mobile app, which you can try out from https://play.google.com/store/apps/details?id=com.mattermost.rnbeta&hl=en&gl=US . ITs in beta right now and it resolves this issue as I tested it on my phone.

**Comment by wuwinson** [comment]
Thanks @harshilsharma63! @bcfdadmin Closing out this ticket, but please feel free to reach out if you're still having issues. Thanks!
