### ISSUE TITLE
Feature Idea: Move card properties

### ISSUE THREAD

**Issue by m-primo** [mattermost/focalboard#4257]
## Summary

A feature to move the card properties.

Let's say we have these properties:
- Status
- Priority
- Description

And I would like to move "Description" to above "Status" I can't do that, I'd have to delete every property and then add them again, and so on!

## How important this is to me and why

Importance: High

As I said above, I can't move properties, I'd have to delete and then add again which is very bad for productivity.

## Additional context/similar features

Notion has this feature and it's pretty helpful!

Good luck with it.

**Comment by wuwinson** [comment]
Thanks for the feedback @m-primo! Agreed that this is important, and we're already tracking this idea on https://github.com/mattermost/focalboard/issues/2190. Feel free to add any additional feedback there. Thanks!
