### ISSUE TITLE
Bug: Clicking on the permalink when linking a board gives a 404

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#4269]
## Steps to reproduce the behavior

1. Link a board to a channel
2. See system message posted by boards bot
3. Click on linked board
4. See 404 error page

## Expected behavior
The board should be accurately linked

## Edition and Platform
 - Edition: Mattermost Boards (product mode)
 - Version: 7.6.0
 - Browser and OS: Chrome mac

**Comment by wuwinson** [comment]
@asaadmahmood Can you confirm if those boards still exist? cc @ogi-m @sbishel

**Comment by wuwinson** [comment]
Any updates @asaadmahmood? Thanks!
