### ISSUE TITLE
Bug: Export/Import - Memberships not retained

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#4275]
## Steps to reproduce the behavior

1. Go to Board, add members to that board.
2. Select  Export to Board Archive
3. Select Import Archive
4. Once imported, open share dialog.
5. Note no memberships are retained.

If that person is set in a person property, the property will appear blank, so also affects card data (display, data is still there.)

## Expected behavior
Memberships should be retained

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: [7.6.0-rc1]
 - Browser and OS: [Chrome on Mac]

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by wuwinson** [comment]
When importing to a different team, and a member is not on the team, display an "unknown" user or their userID instead of not importing anyone to the board.
