### ISSUE TITLE
Bug: Large file attachments (100mb+) get stuck at 100%

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#4277]
## Steps to reproduce the behavior

1. Go to a card and upload one of our plugin .tar files
2. Wait for the upload to reach 100%
3. See error - progress bar remains visible even though it indicates 100% and the file cannot be deleted nor opened.

## Expected behavior

File is uploaded and can be downloaded or deleted.

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/205143707-1c3288fe-e39d-4828-bfa4-d17bc1bc6127.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.6 Bug Bash
 - Browser and OS: Chrome on Mac

**Comment by Rajat-Dabade** [comment]
@wuwinson, I can't this bug in community, we can close this issue.
