### ISSUE TITLE
Bug: Tooltip for card menu says "menuBtn"

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#4280]
## Steps to reproduce the behavior

1. Open a board in list view
2. However over card menu button
3. Observe tooltip with `menuBtn` text

## Expected behavior

No tooltip there, or better text

## Screenshots (optional)

![menu-tooltip-bug](https://user-images.githubusercontent.com/5024605/205147302-902f169d-fd5a-4d31-a6af-6b3eec5e6357.gif)

## Edition and Platform

 - Edition: Mattermost Boards bug bash
 - Version: 7.6
 - Browser and OS: Linux & FF

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by wuwinson** [comment]
@justinegeffen @asaadmahmood Any thoughts on what to put on the tooltip?
