### ISSUE TITLE
Bug: Unable to undo in comment box

### ISSUE THREAD

**Issue by hmhealey** [mattermost/focalboard#4288]
## Steps to reproduce the behaviour

1. Go to a card
2. Start typing some text in the comment input, paste some text, or delete a chunk of text
3. Hit ctrl/cmd+z

## Expected behaviour

The previous action is undone

## Edition and Platform

 - Edition: Mattermost Boards plugin
 - Version: v.7.4.2 (whatever's on community)
 - Browser and OS: MM Desktop App on Mac

**Comment by wuwinson** [comment]
This is no longer occurring on the latest version of Boards. We'll test on Community again once it gets updated to the latest version and verify.
