### ISSUE TITLE
Bug: In the comment input on a card, pressing a key always moves the cursor to the end

### ISSUE THREAD

**Issue by hmhealey** [mattermost/focalboard#4289]
## Steps to reproduce the behaviour

1. Open a card
2. Type some text in the comment input
3. Move the cursor away from the end of the text
4. Start typing

## Expected behaviour

The cursor doesn't move suddenly after the first key press

## Screenshots

https://user-images.githubusercontent.com/3277310/205357956-8913554e-56e5-4d43-9225-78c1830a14b0.mov

## Edition and Platform

 - Edition: Mattermost Boards plugin
 - Version: v.7.4.2 (whatever's on community)
 - Browser and OS: MM Desktop App on Mac

**Comment by wuwinson** [comment]
@hmhealey This was fixed in 7.4.3, but Boards was reverted to an older version on Community.
