### ISSUE TITLE
Bug: Updating from 7.3 to 7.4 or higher will cause connection refused on (any) client!?

### ISSUE THREAD

**Issue by PepeLopez** [mattermost/focalboard#4311]
## Problem

Can't update from v7.3 to any higher versioon (not 7.4 nor 7.5.1) - it results in no connection by web/app/mobile - but service IS running.

## Error in debug log

```
{"timestamp":"2022-12-07 14:27:51.586 +01:00","level":"debug","msg":"GET subscriptions","caller":"app/plugin_api.go:970","plugin_id":"focalboard","subscriberID":"i91knmiqrb8tirab54ffik1g5o","count":"78"}
{"timestamp":"2022-12-07 14:27:51.599 +01:00","level":"debug","msg":"attachSession","caller":"app/plugin_api.go:970","plugin_id":"focalboard","single_user":"false"}
{"timestamp":"2022-12-07 14:27:51.632 +01:00","level":"debug","msg":"Command not implemented in plugin mode","caller":"app/plugin_api.go:970","plugin_id":"focalboard","command":"SUBSCRIBE_TEAM","webConnID":"7u3nzu4s6br6mpxsebm486hdrc","userID":"i91knmiqrb8tirab54ffik1g5o","teamID":"56frpszzcjb87y115futkedcur"}
{"timestamp":"2022-12-07 14:27:51.699 +01:00","level":"debug","msg":"attachSession","caller":"app/plugin_api.go:970","plugin_id":"focalboard","single_user":"false"}
{"timestamp":"2022-12-07 14:27:51.713 +01:00","level":"debug","msg":"GetMembersForBoard","caller":"app/plugin_api.go:970","plugin_id":"focalboard","boardID":"2b307d18-0d07-48cf-85b1-ddd805d76444","membersCount":"7"}
{"timestamp":"2022-12-07 14:27:51.785 +01:00","level":"debug","msg":"**CSRF Check failed for request - Please migrate your plugin to either send a CSRF Header or Form Field, XMLHttpRequest is deprecated**","caller":"app/plugin_requests.go:196","path":"/plugins/focalboard/api/v2/users","ip":"127.0.0.1:43802","session_id":"sourqat88jryjkneiwh3xke6ww","user_id":"i91knmiqrb8tirab54ffik1g5o"}
```

## Edition and Platform

 - Edition: Personal Server (local hosted)
 - Version: 7.3
 - Browser and OS: Server on Debian10 (fully patched), any Client

## Additional context (optional)

MySQL schema is updated to 95 (that should be fine).
However, the service itself is running, but it's not possible to connect when updated to 7.4++
When reverting back to 7.3 I can connect again.

**Comment by PepeLopez** [comment]
Further Info:
Mattermost server is running behind Cloudflare.
By disabling Cloudflare (aka "Proxy bypass") it seems working somewhat (via browser it works, via app not).
However, up to v7.3 it was no problem, since v7.4 it seems that "something" changed, not sure what.
Changelog is not giving proper info about that.

**Comment by mgdelacroix** [comment]
Hi @PepeLopez, apologies for the delay on the response. Is this still an issue you're facing with the newer versions of Focalboard?

**Comment by mgdelacroix** [comment]
Closing for now, please feel free to reopen if needed
