### ISSUE TITLE
Bug: Boards keeps refreshing on MM Desktop app v5.2

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#4318]
## Steps to reproduce the behavior

1. Go to MM Desktop app
2. Open Boards from the app switcher
3. See error - Boards keeps refreshing

## Expected behavior

Boards loads properly

## Screenshots (optional)

![2022-12-09 13 41 23](https://user-images.githubusercontent.com/93531870/206779540-aceb6360-a238-4e33-9112-78fdc8f111f5.gif)

![image](https://user-images.githubusercontent.com/93531870/206779187-82cbd0e0-00ee-4570-8e87-81d8be843faf.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.5.3
 - Browser and OS: MM Desktop app on Mac

**Comment by michaelgamble** [comment]
<img width="396" alt="image" src="https://user-images.githubusercontent.com/31866506/206779937-243d6e06-b858-49b6-b2b6-6cd3e35da8d3.png">

**Comment by michaelgamble** [comment]
Boards currently works in my chrome browser

**Comment by michaelgamble** [comment]
Ohh interesting

So I had been navigating to the board by clicking the tab in the global header... and purely out of curiosity I was wondering what would happen if i clicked a card preview from channels

So if i click a card preview from channels, it will stop the loop and load up the appropriate board / card and boards seems to work just fine from that point forward

HOWEVER if i refresh or quit / reload the app, its back to the loop

seems like maybe something to do with the template picker area as a landing point?

**Comment by michaelgamble** [comment]
Further looking at it, if i try to switch to the contributors team from the staff team in the team sidebar following the card preview into boards - then the loop starts again

so maybe not related to the template picker

**Comment by wuwinson** [comment]
@michaelgamble Is this still happening? Can you make this happen on demand? cc @sbishel

**Comment by michaelgamble** [comment]
yes this is still happening every time for me

**Comment by michaelgamble** [comment]
Oh wait... looks like it might be fixed (just saw a banner saying I had a newer version available)

**Comment by michaelgamble** [comment]
I can no longer recreate the bug... it seems clicking the banner and refreshing into the newer version has eliminated the problem

**Comment by sbishel** [comment]
I'm closing this for now. ReOpen or resubmit if you see it again. Thanks.
