### ISSUE TITLE
Server Unit Tests - ./services/telemetry/telemetry.go

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#432]
Write Unit Tests for ./server/services/telemetry/telemetry.go

**Comment by Aashimalik** [comment]
Hi @sbishel ,
I would love to work on this.

**Comment by yedamao** [comment]
@Aashimalik hi, are u still working on this

**Comment by Aashimalik** [comment]
@yedamao 
Someone else is working on this .
