### ISSUE TITLE
Bug: Able to see private boards through board switcher

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#4333]
## Steps to reproduce the behavior

1. Login with user A
2. Create a private board for user A
3. Login with user B
4. Go to board switcher
5. Search for board created in step 2
6. See error - board appears in search results
7. Clicking on the board leads to an error page

## Expected behavior

Board should not appear in results. User should only see results for boards they have access to.

## Screenshots (optional)

![Screen Shot 2022-12-13 at 4 48 19 PM](https://user-images.githubusercontent.com/93531870/207451682-7569b04c-f3da-4b95-93dd-acf93f4c2f6b.png)

![Screen Shot 2022-12-13 at 4 48 27 PM](https://user-images.githubusercontent.com/93531870/207451444-48d24ac5-0cbf-48fd-8cd6-d1252e240965.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.5.4
 - Browser and OS: Chrome on Mac
 - [mattermost-server master with MySQL](https://sbishel-master.test.mattermost.cloud/boards/team/5sc6ey6j7f8n8dozkcaq8j9q3h/bhf3sdcjmsjn3ifkythozc4hoxr/vk5guubgrqjnkidphcqg3ypwknr)

**Comment by wuwinson** [comment]
Also occurring on https://sbishel-75.test.mattermost.cloud/

**Comment by sbishel** [comment]
Yep...We have a fix for it...
