### ISSUE TITLE
Bug: Boards from a deleted category do not return to the default "Boards" category

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#4334]
## Steps to reproduce the behavior

1. Create a custom category
2. Move boards to the category
3. Delete the category
4. See error - boards disappear from the sidebar instead of returning to the default "Boards" category. Can only view the board by searching and opening from the board switcher, but still does not return the board to the sidebar

## Expected behavior

Boards from a deleted category appear under the default "Boards" category.

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/207452439-e2773863-d4be-4076-8d86-921b57d8d983.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.5.4
 - Browser and OS: Chrome on Mac
 - [mattermost-server master with MySQL](https://sbishel-master.test.mattermost.cloud/boards/team/5sc6ey6j7f8n8dozkcaq8j9q3h/bhf3sdcjmsjn3ifkythozc4hoxr/vk5guubgrqjnkidphcqg3ypwknr)

**Comment by sbishel** [comment]
This is the same functionality as community. Moving to 7.7 milestone.

**Comment by harshilsharma63** [comment]
@wuwinson its's working fine on `main` now that we have DND merged back. I'll still wait for today's bugbash to end before closing this. Please LMK if you still face this.

**Comment by wuwinson** [comment]
Not facing this anymore, but occasionally see https://github.com/mattermost/focalboard/issues/4344 when deleting a category. Closing out.
