### ISSUE TITLE
Bug: Delete card notification has an empty box

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#4336]
<img width="546" alt="Screenshot 2022-12-14 at 7 46 28 AM" src="https://user-images.githubusercontent.com/18575143/207488885-f116e200-2085-4e7e-9d74-a3564e2e760a.png">

Boards bot notification for deleting a card shows an empty box. It shouldn;t be displaying that box.

**Comment by wuwinson** [comment]
We should hide the preview for change notifications when it's for deletions. Thoughts @asaadmahmood?

**Comment by asaadmahmood** [comment]
I agree @wuwinson
