### ISSUE TITLE
Server Unit Tests - ./web/webserver.go

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#434]
Write Unit Tests for /web/webserver.go

**Comment by prakharporwal** [comment]
@sbishel I thought I won't be able to do this. So unassigned. But I think I should give one more try. But need a little guidance on how to go approaching the test.  I am new to unit tests.

#### Their can be multiple ways :
- For NewServer func :
1. On NewServer should I check if the function returns a webserver object.

is this enough!
- For Start( ):
1. Should I actually try pinging the server on Start( ) .
 
Need guidance for this one.
