### ISSUE TITLE
Bug: New sidebar categories do not display tooltip on DND, and deleted categories persist on sidebar

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#4344]
## Steps to reproduce the behavior

1. Login as a new user
2. Create a new category on the sidebar
3. See error - no tooltip displays to indicate DND
4. Delete the category
5. See error - category does not disappear and now displays tooltip for DND
6. Seems to only happen for newly logged in users. After refreshing a few times, the issue no longer occurs

## Expected behavior

New categories display the `New` label and a tooltip for DND. Deleted categories are removed from the sidebar.

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/207675675-9e544a9d-9830-43b4-bb75-bcfdf2f8e699.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.7
 - Browser and OS: Chrome on Mac

**Comment by harshilsharma63** [comment]
Checking this now.

**Comment by harshilsharma63** [comment]
I'm able to reproduce this locally. Debugging this.
