### ISSUE TITLE
Bug: Board can become detached from any categories

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#4345]
## Steps to reproduce the behavior

Unfortunately I don't know exactly how it got to this state.  Things I was testing:
- multiple categories with same name
- deleting categories
- renaming categories

1. Create a category
2. Create three boards
3. Drag all three into category
4. Unfortunately I don't know exactly how it got to this state.  Things I was testing:
- multiple categories with same name
- deleting categories
- renaming categories
5. Notice a board is now longer in a category

## Expected behavior

Boards should always be in a category

## Screenshots (optional)

![board-category-lone-wolf](https://user-images.githubusercontent.com/5024605/207678774-86b1cccd-f24f-479e-921f-1dac9b984104.gif)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.7.7
 - Browser and OS: FF Linux

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by sbishel** [comment]
Not sure if you can do anything until we duplicate again. But wanted you to be aware of the issue.

**Comment by harshilsharma63** [comment]
@wiggin77 we do not hide the active board on collapsing its category. I suppose you're just seeing that? If you notice, when you collapsed the "Boards" category, all boards were hidden as none of them were active. But for the "Lorem" category, you have one active board, which kee continue to display even after collapsing the category.

Was this the confusion maybe?

**Comment by wiggin77** [comment]
> we do not hide the active board on collapsing its category.

That looks like the issue. No bug.
