### ISSUE TITLE
Feature Idea: Allow user to copy a Image in card.

### ISSUE THREAD

**Issue by themaharshpatel** [mattermost/focalboard#4354]
## Summary

Currently, the images added in the description of the card are fixed and a user cannot copy it by simply right-clicking on it.

## How important is this to me and why
By this if there is some image with a user has added on the card and now wants to copy for using it in another application it cannot do that unless it takes a snip of that. and on that, sometimes quality gets lost.

Importance: Low

Use cases:
1. For teams where one sends some reference to the designer and the designer can copy that and use it in the editing software.

**Comment by wuwinson** [comment]
Thanks @themaharshpatel! We'll be shipping file attachments in v7.7 where you'll be able to download the original files, and this would be a good future enhancement.
