### ISSUE TITLE
Bug: Duplicated attachments from templates with pre-attached files

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#4380]
## Steps to reproduce the behavior

1. Open a card and attach files
2. On the sidebar options menu from the current board, select "New template from board"
3. Go to template picker and create a board from the new template
4. Open the card with attached files in Step 1
5. See error - File is duplicated on the card

## Expected behavior

Card should only display attachments if there are any, and attachment should not be duplicated.

## Screenshots (optional)

![Screen Shot 2022-12-20 at 1 41 34 PM](https://user-images.githubusercontent.com/93531870/208742542-400a0bad-6855-4ee0-9b50-fcf89f1fb80c.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.7 Bug Bash
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment]
@harshilsharma63 I logged this bug already.

**Comment by harshilsharma63** [comment]
@wuwinson BTW do we want to fix duplicate file bug or disallow attachment in board templates?

**Comment by wuwinson** [comment]
@harshilsharma63 We should fix the duplicate file bug here, but there may be some use cases where file attachments would make sense in a template, such as onboarding new hires and having them fill out docs. Would allow attachments in the templates unless we hear otherwise.
