### ISSUE TITLE
Bug: Dirty column error

### ISSUE THREAD

**Issue by amyblais** [mattermost/focalboard#4389]
See: https://community.mattermost.com/core/pl/6a7sgzmentn1db7ekjho3ncnmw

After upgrade from 7.5.0 to 7.5.2 I get:

```
error [2022-12-21 19:19:20.363 +01:00] Failed to sync plugin from file store         caller="app/plugin.go:370" bundle=plugins/focalboard.tar.gz error="installExtractedPlugin: Unable to restart plugin on upgrade., error initializing the DB: Error 1054: Unknown column 'dirty' in 'field list' in line 0: SELECT version, dirty FROM `focalboard_schema_migrations` LIMIT 1"
```

Boards is on 7.5.4 & working.

The dirty column doesn't exist in focalboard_schema_migration.

Last entry is:
![image](https://user-images.githubusercontent.com/29708087/208977761-bcf5edf7-abc2-4175-b6d9-90e49b85c646.png)

**Comment by harshilsharma63** [comment]
Closing this one now but feel free to re-open.
