### ISSUE TITLE
Feature idea : make possible to search all the cards across all the boards

### ISSUE THREAD

**Issue by abunet** [mattermost/focalboard#4413]
I'd like to be able to add a virtual board made of all the cards of all the boards (by selecting wich board to include, or selecting all the boards where I am a member). 
At this point I could add multiple views to the aggregated board like any other board.

I think this is a very important Feature

Thanks

**Comment by wuwinson** [comment]
Thanks @abunet! Looks like a dupe of https://github.com/mattermost/focalboard/issues/247 and https://github.com/mattermost/focalboard/issues/360. Feel free to add any additional comments there!
