### ISSUE TITLE
Bug: When you create a new template for a card and delete properties then these properties are deleted for all cards on the board

### ISSUE THREAD

**Issue by cindy565656** [mattermost/focalboard#4425]
## Steps to reproduce the behavior

1. Create a new template for a card by going to the arrow next to new and click New Template
![image](https://user-images.githubusercontent.com/122022426/210773463-81ed5d69-f867-4f3d-982c-a147b782f067.png)
2. All your old properties are shown in the new template
![image](https://user-images.githubusercontent.com/122022426/210773491-694c6e4b-26ae-4d81-aca3-83c52108bc50.png)
3. If you want to delete some of the old properties or add new ones, all the cards on your board will be affected, also those made with other templates
![image](https://user-images.githubusercontent.com/122022426/210773517-15aa8a70-a95b-429b-91c0-5ec2d311fd80.png)
![image](https://user-images.githubusercontent.com/122022426/210773539-4b0f2e93-2083-4ddc-a2fe-858533d162e9.png)

## Expected behavior
If I create a new template, I expect the old cards that used other templates won't be affected 

## Edition and Platform

 - Edition: Personal Server
 - Version: v7.5.1
 - Browser and OS: Both on firefox and on Mattermost Desktop that connect to personal server

## Additional context (optional)
* Sev 3: Affects minor, non-critical functionality
It's just kind of annoying when you want to rearrange the properties in the card and have to delete all your info for them before you can add them again. A new template that doesn't affect the old cards would solve this issue.

**Comment by wuwinson** [comment]
@cindy565656 Thanks for the feedback! Properties apply to all cards on the board, even on templates. Check out our Help Docs on [card properties](https://docs.mattermost.com/boards/work-with-cards.html#card-properties) for more details. To help address your use case, we're tracking the ability to hide properties on https://github.com/mattermost/focalboard/issues/3319. I've linked this ticket there, but please feel free to add any additional comments. Thanks!
