### ISSUE TITLE
Bug: App fails to open on dock icon click

### ISSUE THREAD

**Issue by jgilliam17** [mattermost/focalboard#443]
**Summary:**
When the app is closed using x, it can't be brought back to forefront by clicking on the dock icon

**Steps to reproduce the behavior:**
1. Open the app, dismiss welcome window if present 
2. Close the app by click on the X
3. Click on the dock icon to open again

**Expected behavior:**
App can be brought to forefront by clicking on the dock icon, as the dot indicates that it is still open

**Screenshots:**
<img width="662" alt="Screen Shot 2021-05-18 at 9 11 56 AM" src="https://user-images.githubusercontent.com/52937121/118702156-8feb8180-b7e2-11eb-9440-f550e02d9d09.png">

**Platform:**
 - Focalboard Version 0.6.7 (12)
 - OS and version: macOS 10.15.7 Catalina and macOS 11.3.1 Big Sur

**Additional context:**
App is not installed, opening from unzipped downloaded file. 
Reproduces on App Store installed version 0.6.5
Work-around: File>New opens the app back up, although "new" is misleading as it's opening existing boards

**Comment by haardikdharma10** [comment]
Able to reproduce 👍

**Comment by chenilim** [comment]
Thanks for reporting this @jgilliam17! Setting it as up for grabs. Desired behavior when clicking the dock icon is:
* Bring the first open window to the top, if there is one, or
* Open a new window
