### ISSUE TITLE
UI/UX issue: `x` icon is not aligned with text in "Create New Category" modal text input box

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#4434]
Found by QA community contributor @krmh04 on `https://boards-bugbash-76.test.mattermost.cloud/` server, Boards v7.7.0

## Steps to reproduce the behavior

1. Click on the "+" to the right of "Find Boards"
2. Select "Create New Category"
3. Type a name for the category
4. Observed: "x" that appears on the right-hand-side of the category input box is not aligned with category name text

## Expected behavior

"x" that appears on the right-hand-side of the category input box is aligned with category name text

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/13020833/211078511-e3af50c9-68ad-405a-81f9-1d6e8b74100a.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.7.0
 - Browser and OS: Windows / Chrome

**Comment by wuwinson** [comment]
@asaadmahmood Can you help with this one? Thanks!
