### ISSUE TITLE
Bug: "Delete" attachment box "jumps" and moves if you move your mouse off it

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#4436]
Found by QA community contributor @varghesejose2020 on `https://boards-bugbash-76.test.mattermost.cloud/` server, Boards v7.7.0

## Steps to reproduce the behavior

1. Add an attachment to a card
2. Once attachment has uploaded, hover over it and click the 3-dots then select "Delete"
3. Don't click "Delete" and move your mouse off the "Delete" box
4. Observed: "Delete" box jumps / moves (see video attached)

## Expected behavior

"Delete" box stays in the same place and does not jump/move

## Screenshots (optional)

https://user-images.githubusercontent.com/13020833/211084336-a8ac616a-8575-4b32-86a7-6df4839821cd.mp4

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.7.0
 - Browser and OS: Windows / Chrome

**Comment by wuwinson** [comment]
@Rajat-Dabade @ogi-m Can you confirm if #4297 fixes this issue? Thanks!

**Comment by ogi-m** [comment]
This was fixed by https://github.com/mattermost/focalboard/pull/4297.

Closing.
