### ISSUE TITLE
Bug: When you duplicate a board the comments on the cards are not copied

### ISSUE THREAD

**Issue by cindy565656** [mattermost/focalboard#4443]
I looked in the docs and it only said the following about duplicating boards:
Duplicate board: Creates a copy of the board and all the cards on the board. The duplicated board will appear under the same category as the original board. Board members from the original board aren’t migrated to the new board.

So in case this isn't a bug, I'd like to change it to a 'Documentation Request' or 'Feature Request'.

Thanks in advance.

## Steps to reproduce the behavior

1. Duplicate board by clicking on the 3 dots next to your board name and click duplicate board
2. Go to a card that used to have comments
3. The comments are now missing

## Expected behavior

I expect the comments to be still there, since the cards get duplicated

## Screenshots (optional)

Original card:
![image](https://user-images.githubusercontent.com/122022426/211486135-b7fc3ba1-d424-49bb-94d6-8e98a5815bfd.png)
Duplicated board card:
![image](https://user-images.githubusercontent.com/122022426/211486212-a2d5fbec-b5f5-4777-b574-f3af8e66abb9.png)

## Edition and Platform

 - Edition:  Personal Server 
 - Version: 7.5.1
 - Browser and OS: Desktop

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 3: Affects minor, non-critical functionality

**Comment by wuwinson** [comment]
Thanks @cindy565656! Board members and comments don't get duplicated. I've submitted https://github.com/mattermost/docs/pull/6142 to update the docs. If you'd like to copy comments over as well, please try our [export/import feature](https://docs.mattermost.com/boards/migrate-to-boards.html#import-and-export-a-board-archive). Thanks! cc @justinegeffen
