### ISSUE TITLE
Bug: Switching teams takes the user to channels

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#4448]
## Steps to reproduce the behavior

1. Be a member of at least two teams
2. Open Boards
3. Select a different team in the team sidebar
4. User is taken to channels

## Expected behavior

User should remain in boards and see the boards from the selected team

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.7
 - Browser and OS: Chrome on Mac

**Comment by harshilsharma63** [comment]
Fixed by https://github.com/mattermost/mattermost-webapp/pull/11967

**Comment by harshilsharma63** [comment]
This is fixed now. Closing the issue.
