### ISSUE TITLE
Bug: Publicly shared board links not working

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#4450]
## Steps to reproduce the behavior

1. Open the Share dialog on a board as an admin
2. On the bottom of the dialog, click on the "Publish" tab
3. Toggle on the "Publish to the web" button
4. Copy and paste link into a browser
5. See error - issue only occurs Community, but not on our bug bash server.

## Expected behavior
Link directs user to publicly shared board with read-only access.

#### Community:
https://community.mattermost.com/team/qghzt68dq7bopgqamcnziq69ao/shared/b4ctmm917q3rzdfi451qtuxjzcw/vsyng4ghehbgsmp7gxfxk81bxxa?r=kfsmtwmhwtpug6xnou7swweo1dw

#### [Bug bash v76](https://boards-bugbash76.test.mattermost.cloud/boards/team/7qgkkun8kjb4jbjqo435gd63nh/bf6gc56y8wig9tnp6ocescsj59h/vf9cn41xbj3bf7d8wnsoeybhsxh):
https://boards-bugbash76.test.mattermost.cloud/plugins/focalboard/team/7qgkkun8kjb4jbjqo435gd63nh/shared/bf6gc56y8wig9tnp6ocescsj59h/vf9cn41xbj3bf7d8wnsoeybhsxh?r=ko33u7s8nq33syn6e7trq7f9dhh

![Screen Shot 2023-01-10 at 11 50 55 AM](https://user-images.githubusercontent.com/93531870/211613098-f9ac770f-b88a-4e5c-a62b-076c2f524217.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.7
 - Browser and OS: Chrome on Mac

**Comment by ogi-m** [comment]
@wuwinson This also reproduces on cloud test servers now that they're running in product mode.

cc @sbishel

**Comment by wiggin77** [comment]
During the bug bash this issue was reported as also involving old/existing share URLs having the `plugins/boards` prefix.  I don't think our share links ever had that prefix (unless I'm missing something).  While the link generator needs to be fixed, do we really need the server to convert/redirect any old URLs due to MPA?

**Comment by lindy65** [comment]
Tested on [this PR](https://github.com/mattermost/mattermost-server/pull/22710) and this issue is fixed 👍
