### ISSUE TITLE
Bug: Board Templates Not Showing Up

### ISSUE THREAD

**Issue by wihodges** [mattermost/focalboard#4460]
## Steps to reproduce the behavior

1. Create a Board

## Expected behavior

There are currently only two pre-configured Board templates available. The website very clearly shows multiple types of templates to choose from. I understand you can create a template. What is not clear and could use some enhancement is better path to save a template globally across organizations. 

## Screenshots (optional)

![Screenshot 2023-01-12 at 11 28 16 AM](https://user-images.githubusercontent.com/286956/212137376-b8c2f844-4424-4d41-9356-1dea374c1599.png)

## Edition and Platform

 - Edition: Personal Desktop / Personal Server / Mattermost Boards (plugin)
 - Version: 7.5.2
 - Browser and OS: N/A

**Comment by wuwinson** [comment]
@wihodges Thanks for reporting the issue. Can you provide more details such as your edition and browser/OS version? Did this happen as a result of an upgrade or a fresh install?

**Comment by wuwinson** [comment]
Closing out. @wihodges Feel free to reach out if this is still happening. Thanks!
