### ISSUE TITLE
Bug: Clicking on Boards bot message of linked board results in 404 error

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#4462]
## Steps to reproduce the behavior

1. Link a board to a channel
2. Go to the channel and see the boards bot message of the linked board
3. Click on the link to the board
4. See error - 404 page not found

## Expected behavior

The linked board is loaded on a new tab

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/93531870/212161316-3ce09848-4193-4fe1-ab4a-d43ac886af7d.png)

https://user-images.githubusercontent.com/93531870/212161333-01b10318-5eb7-4f49-84d7-09a7f94feea3.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.7 Community
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment]
Related [thread](https://community.mattermost.com/core/pl/nmzq4b9jhpyg8c8e63rmcr1kxe).

**Comment by sbishel** [comment]
dupllicate of - https://github.com/mattermost/focalboard/issues/4441
