### ISSUE TITLE
Enable channel notifications for Boards

### ISSUE THREAD

**Issue by jnny** [mattermost/focalboard#4464]
A few UX notes on Mattermost Boards, which we've just started exploring and are great, thank you!

1. It would be nice to be able to configure channel notifications when a board is updated.

2. I like that there is a quick link to Boards in the channel (top right icon, see next point below on that], and feel this should be standardized with quick one-hop icon links back to the Channel from a linked Board (at current, have to find it in the way top left dropdown menu which is unintuitive].

3. The Boards icon is not intuitive (looks like a dartboard...?, consider changing to something more resembling a kanban board?

**Comment by devinbinnie** [comment]
Moved to focalboard repo

**Comment by wuwinson** [comment]
Thanks for the feedback @jnny! We're tracking "Follow boards" on https://github.com/mattermost/focalboard/issues/2421. We're also exploring new options to navigate between boards and channels for later this year, which should make it easier for users to switch from a channel to a linked board and vice versa.
