### ISSUE TITLE
Bug: Personal Server's frontend make error on MacOS

### ISSUE THREAD

**Issue by cokeBeer** [mattermost/focalboard#4468]
## Steps to reproduce the behavior

1. clone the project
2. run make prebuild
3. run make

## Expected behavior

build successfully

## Screenshots (optional)

<img width="850" alt="image" src="https://user-images.githubusercontent.com/70683161/212287513-f3d58c30-14c8-4846-9392-4ca2fbd9cfcc.png">

## Edition and Platform

 - Edition:  Personal Server
 - Version: v7.5.2
 - Browser and OS: Chrome on Mac

**Comment by sbishel** [comment]
@cokeBeer - Is this still an issue? Did you run `make prebuild`?
