### ISSUE TITLE
Bug: Global header icons in the middle ui bug

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#4478]
## Screenshots (optional)
<img width="537" alt="Screenshot 2023-01-17 at 10 09 52 PM" src="https://user-images.githubusercontent.com/11034289/212966124-ec2f183e-7138-43e3-abce-85dfdc12b2d1.png">

## Edition and Platform
 - Edition: Mattermost Boards (plugin)
 - Version: 7.8
 - Browser and OS: Chrome Mac

**Comment by wuwinson** [comment]
@asaadmahmood Can you help clarify the issue? Is this something you can work on?

**Comment by wuwinson** [comment]
@asaadmahmood Are you referring to https://github.com/mattermost/focalboard/issues/4384 or something else?
