### ISSUE TITLE
Bug: Language Translations should not also translate the language selector options

### ISSUE THREAD

**Issue by coltoneshaw** [mattermost/focalboard#448]
**Summary:**
The language selector will also translate the language selector options. This makes it difficult to get back to your original language.

**Steps to reproduce the behavior:**
1. Click Settings
2. Set Language
3. Pick any language

**Expected behavior:**
The language options will be translated to the language they belong to. Similar to how Mattermost currently operates.

**Screenshots:**
![Screen Shot 2021-05-20 at 9 43 02 AM](https://user-images.githubusercontent.com/46071821/118990951-51280980-b951-11eb-98dc-ce18df4659b8.png)

**Platform:**
 - Browser and version: v0.6.5
 - OS and version:MacOS Big Sur

**Comment by chenilim** [comment]
Thanks @coltoneshaw! Agree with making this change, to be consistent with Mattermost. Should be fairly straight forward, to always use the "native" language for each language name. Opening it up to any takers.

**Comment by coltoneshaw** [comment]
@chenilim - I can take a swing at it. Just needs to have the `"Sidebar.english": "Englisch",` updated in the i18n files for each translation to the native language, right?

**Comment by chenilim** [comment]
Thanks @coltoneshaw! tbh, I'm not sure what the best way to implement it is - do you know how Mattermost does it? If it's done in the translation file, then we should do that too. The other approach would be to set the language in code, but that might be more complicated.

@jespino might know more, but he's out until next week. @sbishel do you know, or know who might know?

**Comment by coltoneshaw** [comment]
I can definitely do it in the translation file, in the code I might have step aside! I'll start playing around with it though.

**Comment by sbishel** [comment]
I just took a look at Messaging. There we pull the "available languages" which includes the "code" and the name in its native language. I think we can simply update the menu text in sidebarSettingsMenu.tsx to NOT call format message, but simple display the name in the native language.
