### ISSUE TITLE
Enhancement: "Add Content" Button is hidden unless you hover over where it should be.

### ISSUE THREAD

**Issue by coltoneshaw** [mattermost/focalboard#449]
**Summary:**
When editing a card the Add Content button is hidden unless you hover over exactly where it should be. This could lead people to not even know it exists.

**Steps to reproduce the behavior:**
1. Go to edit a card
2. Hover below the `Add a description

**Expected behavior:**
I would expect this to be visible when editing a card to know it exists.

**Screenshots:**

![Screen Shot 2021-05-20 at 9 58 29 AM](https://user-images.githubusercontent.com/46071821/118991678-ee833d80-b951-11eb-93e3-42f2a01cde29.png)
![Screen Shot 2021-05-20 at 9 58 36 AM](https://user-images.githubusercontent.com/46071821/118991695-f2af5b00-b951-11eb-8e04-b5099077f071.png)

**Platform:**
 - Browser and version: v0.4.6
 - OS and version: Big Sur

**Comment by jespino** [comment]
@chenilim @asaadmahmood any opinion on this? This is the designed behavior I think so I going to convert this to enhancement.

**Comment by asaadmahmood** [comment]
@jespino This is different from notion, but I like the add content button. I would not mind having the `add content` button appear at all times when the user is description field is active.

Though again, just like any other issues, see how many users actually think this is a problem before we implement a fix.

**Comment by jespino** [comment]
@asaadmahmood the fix would be very easy to do. I don't mind to keep it always visible, visible on certain circustances or invisible until hover. I don't think is super important, but because it is cheap, I think we can use our gut feeling about what is the best option, change it to that, and then wait for feedback.

**Comment by asaadmahmood** [comment]
@jespino Then we can make that change and see what users think.

**Comment by jespino** [comment]
@asaadmahmood ok, what change? always visible?

**Comment by asaadmahmood** [comment]
@jespino Always visible when the description field is focused.
