### ISSUE TITLE
Bug: Person Column Headers text is light.

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#4493]
## Steps to reproduce the behavior

1. Go to Kanban View of Board, add cards with Person property
2. Select  Group by Person property.
3. Notice Person names in the header is very light text

## Expected behavior

Darker text?

## Screenshots (optional)

![Screen Shot 2023-01-19 at 10 00 22 AM](https://user-images.githubusercontent.com/12704875/213510869-8ba5c6dc-b2d1-4e25-9865-df8d2679b47f.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: [main]
 - Browser and OS: [e.g. Chrome on Mac]

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by wuwinson** [comment]
@asaadmahmood Can you help look into this one?
