### ISSUE TITLE
Bug: Find boards modal misalignment in header

### ISSUE THREAD

**Issue by matthewbirtch** [mattermost/focalboard#4500]
## Steps to reproduce the behavior

1. Hit Command-K shortcut to open "find boards" modal
2. Notice text in the header is misaligned and too close to the left edge

## Expected behavior

There should be appropriate padding on the left, similar to the 'Find channels' modal.

## Screenshots (optional)

<img width="689" alt="image" src="https://user-images.githubusercontent.com/2040554/213818557-4c3c9b1d-b80e-4549-b606-1e2ccc812752.png">

## Edition and Platform

 - Edition: Mattermost Boards
<img width="614" alt="image" src="https://user-images.githubusercontent.com/2040554/213818634-2bda00a9-77ca-40cb-8755-af5d62e8a5bd.png">

**Comment by wuwinson** [comment]
@asaadmahmood might be caused by https://github.com/mattermost/focalboard/pull/4458 - can you help look into this?
