### ISSUE TITLE
Bug: Dialog titles misaligned

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#4509]
## Steps to reproduce the behavior

1. Open the "share Board" modal or the create/.rename category modal and notice the title is misaligned, all the way towards the left side,

## Expected behavior

Title should not be misaligned

## Screenshots (optional)
<img width="693" alt="Screenshot 2023-01-24 at 3 14 00 PM" src="https://user-images.githubusercontent.com/18575143/214259325-3008407f-666f-4b27-868e-401a09273e41.png">

<img width="737" alt="Screenshot 2023-01-24 at 3 14 11 PM" src="https://user-images.githubusercontent.com/18575143/214259362-ebc313ab-1b9e-49cb-a711-0d9f430cfe3a.png">
<img width="733" alt="Screenshot 2023-01-24 at 3 14 23 PM" src="https://user-images.githubusercontent.com/18575143/214259399-091a88b8-cbe4-4a9d-809d-25d3c6851d16.png">

## Edition and Platform

 - Edition:  Mattermost Boards (plugin)
 - Version: latest `main`
 - Browser and OS: Firefox

**Comment by harshilsharma63** [comment]
Additionally, the card dialog's height is also 100%, but it was smaller previously, so maybe that got messed up as well.

**Comment by wuwinson** [comment]
Also occurring on the "Find boards" modal: https://github.com/mattermost/focalboard/issues/4500.
