### ISSUE TITLE
Bug: invalid license/authorization to use insights API

### ISSUE THREAD

**Issue by lonesomewalker** [mattermost/focalboard#4511]
## Steps to reproduce the behavior

Look in Admin section logfile:
```
{"timestamp":"2023-01-24 12:38:51.681 +01:00","level":"error","msg":"API ERROR","caller":"app/plugin_api.go:976","plugin_id":"focalboard","code":"500","error":"\"invalid license/authorization to use insights API\"","api":"/api/v2/teams/fmtn7u8t138j7m86iwjbog4tzc/boards/insights"}
```

## Expected behavior
Clean install/upgrade :-)

## Edition and Platform

 - Edition: Personal Server
 - Version: 7.latest
 - Browser and OS: independent

## Additional context (optional)

Upgraded from 7.1 through all the versions to the current one.

**Comment by sbishel** [comment]
@lonesomewalker - Personal server does not support insights. Insights are supported when running Boards as part of the Mattermost Channels. I'm not sure what else would be calling that endpoint.  Are you sure you are running Personal Server?

**Comment by lonesomewalker** [comment]
Sure as the sun will rise tomorrow...
