### ISSUE TITLE
Bug: Boards bot notifications link redirects to template picker

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#4514]
## Steps to reproduce the behavior

1. On a board where you have synthetic membership (not explicit) - have someone @mention you on a card in the comments section to make you a follower
2. Ask them to make changes to the card so you will receive change notifications
3. Wait 2 mins to receive boards bot notification in Channels
4. Click on card link from boards bot message
5. See error - user is redirected to Boards tab, but sees template picker instead of the card.

## Expected behavior

User is redirected to Boards tab with the respective card dialog open. (Have not confirmed if this applies to all members or only synthetic members.)

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/93531870/214443773-264976b4-113a-4ddd-a949-9ae5f1a62363.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.8
 - Browser and OS: MM desktop app

**Comment by wuwinson** [comment]
See [thread](https://community.mattermost.com/core/pl/hdz8uyi9djf87d5ummwzq9icha) for details. cc @hmhealey

**Comment by wiggin77** [comment]
This is because when generating a link for notifications it uses a `0` for the viewID.  This is a regression as it used to treat `0` as the first view.
