### ISSUE TITLE
Bug: Import Notion

### ISSUE THREAD

**Issue by atah** [mattermost/focalboard#4524]
Hi, 

I use : 

1. From a Notion Board, open the ... menu at the top right
2. Select `Export`, pick `Markdown & CSV` as the export format, select true to include subpages.
3. Save it locally, and unzip the folder e.g. to `notion-export`
4. Run `npm install` from within `focalboard/webapp`
5. Run `npm install` from within `focalboard/import/notion`
6. Run `npx ts-node importNotion.ts -i <path to the notion-export folder> -o archive.boardarchive`
7. In Focalboard, click `Settings`, then `Import archive` and select `archive.boardarchive`

But I have a error : 

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:737:3)
    at tryReadSync (node:fs:432:20)
    at Object.readFileSync (node:fs:478:19)
    at getMarkdown (/Users/axelpichon/Downloads/focalboard-main/import/notion/importNotion.ts:105:29)
    at /Users/axelpichon/Downloads/focalboard-main/import/notion/importNotion.ts:200:26
    at Array.forEach (<anonymous>)
    at convert (/Users/axelpichon/Downloads/focalboard-main/import/notion/importNotion.ts:155:11)
    at main (/Users/axelpichon/Downloads/focalboard-main/import/notion/importNotion.ts:74:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Can you help me please ?

**Comment by wuwinson** [comment]
@ogi-m Can you try to reproduce this issue? Thanks! cc @sbishel

**Comment by sbishel** [comment]
So, I just tried it myself and it took me a couple tries to get it right. 
The command expects the `-i` path to be to a directory containing the csv file. 

`npx ts-node importNotion.ts -i ~/Downloads/notion -o archive2.boardarchive`

<img width="652" alt="Screen Shot 2023-02-01 at 1 29 07 PM" src="https://user-images.githubusercontent.com/12704875/216156251-0102b36c-e9f7-420c-b294-7efea49736e6.png">

**Comment by wuwinson** [comment]
@atah Can you confirm if this is still happening after trying @sbishel suggestions? Thanks!

**Comment by sbishel** [comment]
@atah - closing, please reopen if still an issue.
