### ISSUE TITLE
Bug: Can not change language to English after changing to another lanuage

### ISSUE THREAD

**Issue by xiezhenye** [mattermost/focalboard#4525]
English is not in the language setting list. After changing to another lanuage, there is no way to change the language setting back to English.

## Steps to reproduce the behavior

1. Go to Configration
2. Select  language setting
3. Select  some language, like 中文（简体）
4. Select 设定，设定语言
5. See error

## Expected behavior

There is an English option in language list

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/2225688/215379592-d5abacd8-e2be-4e66-b854-743093c76730.png)

## Edition and Platform

 - Edition: Personal Desktop
 - Version: v0.15.2
 - Browser and OS: Mac

**Comment by anonymous-baaka** [comment]
i would like to work on this issue. Please do assign if no one else is working on it right now.
