### ISSUE TITLE
Doc: API Docs' Usage and SDK Samples language does not change

### ISSUE THREAD

**Issue by lokeswaran-aj** [mattermost/focalboard#4552]
## Summary

I was looking at the [API Docs](https://htmlpreview.github.io/?https://github.com/mattermost/focalboard/blob/main/server/swagger/docs/html/index.html) and I was not able to switch language.

## (Optional) Additional context and/or screenshot

https://user-images.githubusercontent.com/74011196/216913536-8a596bb6-1396-4756-a3e9-5bf25dce14d7.mov

**Comment by wuwinson** [comment]
Now that [Boards is part of the Mattermost suite](https://github.com/mattermost/focalboard/discussions/4645), we are considering options to merge our API docs with https://api.mattermost.com/. Closing out this ticket since it will no longer be relevant. Thanks!
