### ISSUE TITLE
Bug: Category menu opens behind the centre pane

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#4553]
## Steps to reproduce the behavior

1. Go to Boards
2. In the sidebar, click on the `+` button and create a category
3. Click on `...` next to the category name
4. Note the menu is overlapped by the centre pane and the sidebar has horizontal scrolling

## Expected behavior

The menu should open on top of the centre pane

## Screenshots (optional)

**Observed**: 

<img width="469" alt="image" src="https://user-images.githubusercontent.com/15314183/216971836-e9ddbe72-1389-4107-be07-06024ecd79b5.png"> 

**Expected**:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/15314183/216972108-35662692-bf7d-4a8a-81e6-de45325dd7ef.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.8 on Cloud 
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment]
Cannot reproduce on Community.
