### ISSUE TITLE
Bug: Push notification on desktop and mobile not working on last version

### ISSUE THREAD

**Issue by dahlslett** [mattermost/focalboard#4564]
## Steps to reproduce the behavior

1. When replying in a thread notifications is not working even the setting to get notifications is on for both desktop and mobile push.

## Screenshots (optional)

Settings is on:
https://share.icloud.com/photos/05dwreCQHORqjTexGHHTV5DNw

## Edition and Platform

 - Edition: We run our own server with mattermost
 - Version: Current version
 - Browser and OS: OSX and iOS application

**Comment by wuwinson** [comment]
@amyblais Looks like a Channels bug - did you want us to transfer this ticket?

**Comment by amyblais** [comment]
@dahlslett Would you be open to posting about this either on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or at https://forum.mattermost.com/? One of our devs or community members will likely be able to help troubleshoot this issue.
