### ISSUE TITLE
Bug: use of closed network connection - websocket related

### ISSUE THREAD

**Issue by whysthatso** [mattermost/focalboard#4566]
running focalboard official docker image behind nginx proxy.

- working as expected until last docker image tagged "7.5.2"
- after updating to "7.8.0" i'm seeing this in the container logs:

```
focalboard  | error [2023-02-10 14:11:23.050 Z] ERROR WebSocket                          caller="ws/server.go:130" client="10.0.0.157:53076" error="read tcp 172.20.28.2:8000->10.0.0.157:53076: use of closed network connection"
```

10.0.0.157 is the private interface of the proxy
172.20.28.2 is the docker interface

nginx access log shows:

```
192.51.201.111 - - [10/Feb/2023:14:10:33 +0000] "GET /ws HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0"
```

browser console shows:

```
[1676038267.68] Unexpected close, re-opening websocket
```

site shows login screen, but trying to login shows: password incorrect (which is a bit confusing)

reverting back to image "7.5.2" solves the issue and i can use the app as expected.

## Edition and Platform

 - Edition: Personal Server 
 - Version: 7.8.0 (corresponding official docker image)

**Comment by ulysserevient** [comment]
Hi,
I encouter the same problem
Have you find a solution ?

**Comment by tuxthepenguin84** [comment]
I'm having the same issue, was using latest docker image but reverted back to 7.5.2 and errors have gone away and I can login again.

**Comment by ulysserevient** [comment]
I'm still stuck with this error
Have you find a solution ?

**Comment by whysthatso** [comment]
as focalboard is winding down its version for separate selfhosting i have decided to switch to todoist. 

i think the underlaying problem is a database migration issue, if that helps.

**Comment by mgdelacroix** [comment]
It seems that the websockets close is a consequence of something else happening probably at the server level. Could you please post the server startup logs to see if there is any issue there?

When you try to login from the interface, what's the response that appears in the network tab of the devtools when you click on the login button?

**Comment by h0mesmart** [comment]
Hi there,

If it's help here attached the server startup logs 
[starup.log](https://github.com/mattermost/focalboard/files/11238579/starup.log)
and the result of the network tab 
![network](https://user-images.githubusercontent.com/64425114/232190984-22a73460-f558-4777-8532-2fdbf2d153f2.png)

Hope it helps.

**Comment by mgdelacroix** [comment]
There is nothing in the startup logs it seems. Could you please post the logs for both the server and the browser for that same action? the full view of the network tab would be useful as well
