### ISSUE TITLE
Bug: Share dialog role dropdown is cut-off

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#4567]
## Steps to reproduce the behavior

1. Open the Share dialog from any board
2. Select the role dropdown on any board member
3. See error

## Expected behavior

Role dropdown should appear within the dialog

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/218138923-a73947d4-7432-4829-9d26-4ccfe97f8e51.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.9
 - Browser and OS: Chrome on Mac

**Comment by sbishel** [comment]
Caused by - https://github.com/mattermost/focalboard/pull/4411
