### ISSUE TITLE
Bug: Sysadmins joining public boards as an "admin" instead of the default board role

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#4569]
## Steps to reproduce the behavior

1. Sign in as a sysadmin
2. Search for a public board where you are not currently a member
3. Join the board
4. Open share dialog
5. See error - sysadmin is assigned the `admin` role instead of the default board role

## Expected behavior

Sysadmin should have full admin permissions, but the role on the dropdown should still indicate the default board role. See reasoning for this on [requirement 2.e.i from the spec.](https://docs.google.com/document/d/1BwXeEDeTXJzecFE1D8mjcKyL5nC3IK81sKziz3257uA/edit?pli=1#bookmark=id.vl6hz6mf1mxe)

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/218147087-0ade7bba-f15d-4665-939d-05cb7e2b8b2a.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.9
 - Browser and OS: Chrome on Mac

**Comment by sbishel** [comment]
Closing...it does work as designed. However, when elevating permissions, the dropdown displays the elevated permissions. However, if you remove their admin role, their permissions are set to the minimum board role.
