### ISSUE TITLE
Bug: Unknown column 'name' in 'field list'

### ISSUE THREAD

**Issue by shieldsjared** [mattermost/focalboard#4576]
## Steps to reproduce the behavior

1. Begin with an early version of Mattermost (unsure as to which version, but likely 6.x)
2. Remove the bundled focalboard plugin
3. Upgrade Mattermost progressively to the latest 7.7
4. Attempt to install _any_ version of the focalboard plugin
  - If the version is 7.1 or less, the plugin installs and starts successfully
  - If the version is 7.2 or greater, the following error message appears:

```
This plugin failed to start. error initializing the DB: driver: mysql, message: failed to fetch applied migrations, command: select_applied_migrations, originalError: Error 1054: Unknown column 'name' in 'field list', query: SELECT version, name FROM focalboard_schema_migrations
```

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Plugin Version: v7.2
 - Mattermost Version: 7.7
 - Browser and OS: n/a

## Additional context (optional)

The boards plugin was removed early on from our Mattermost implementation, and subsequent upgrades were progressively done since then.  Now that focalboard has matured, we'd like to install and try out the latest version.  Upon installing the latest version via the marketplace, the error message above is received.  Downgrades of the plugin were progressively performed and it seems that 7.1 is the latest version that will start, and all newer versions result in the error provided above.

**Comment by wuwinson** [comment]
@shieldsjared Can you try installing from https://github.com/mattermost/focalboard/releases/tag/v7.7.0? Let us know if that works. Thanks! cc @sbishel

**Comment by shieldsjared** [comment]
Hi @wuwinson -

I'm pretty sure I tried that previously but I went ahead and tried that again for my own sanity. Indeed, installing via the marketplace _or_ by manually downloading from the link provided result in the same error message.

**Comment by shieldsjared** [comment]
@wuwinson I wonder if this commit (935e5c68fd94d7b7fcc42c5b4893a0f2ff85d5eb) is the fix for this. 🤷‍♂️ I tried downloading 7.8.2 since that appears to possibly include that commit, but that requires MM 7.8 to be running so I couldn't verify.

**Comment by shieldsjared** [comment]
@wuwinson - I'm not sure how to go about removing the `Awaiting Submitter Action` tag on here... I assumed it would come off automatically once I responded, but it didnt.  Just want to make sure this doesn't get overlooked.

**Comment by sbishel** [comment]
@shieldsjared - There was a bug where old plugins were getting loaded. I can't find the PR for that, right now. But I'm pretty sure that's what is happening here because the Error message you're seeing does not exist in 'v7.7`, that table has been changed for several versions, to work around. 

Completely "remove" (not just disable) the Mattermost Boards plugin.
Then upload the the v7.7 release from the github link above.

**Comment by shieldsjared** [comment]
Hi @sbishel - I've already done that a bagillion times over, with every version from 7 forward. The only versions that work are <= 7.1.  Anything 7.2 and greater fail with the error provided.  Each time I try, I am completely removing and then installing.  (Not sure how else I would have installed and older version of a plugin without doing a _remove_ as suggested).

**Comment by sbishel** [comment]
Let's check you `focalboard_schema_migrations` table. It apparently isn't running the migration for that table.

**Comment by shieldsjared** [comment]
@sbishel 

| version | dirty |
| ---- | ---- |
| 17 | 0 |

**Comment by sbishel** [comment]
@mgdelacroix - Any idea why isSchemaMigrationNeeded() wouldn't be picking this up and migrating? Might be related to https://github.com/mattermost/focalboard/commit/935e5c68fd94d7b7fcc42c5b4893a0f2ff85d5eb, but this would not be using sqlLite.

**Comment by mgdelacroix** [comment]
Hi @shieldsjared, I'm investigating the issue to see how to move further, could you please post the list of tables that your database has? Thanks!

**Comment by mgdelacroix** [comment]
In the meantime, you can try this workaround to migrate the `schema_migrations` table manually and then update the plugin version. Please do take a backup of the `focalboard_` prefixed tables before following these steps in case anything goes wrong:
1. Stop and remove the `focalboard` plugin.
2. Drop the old `focalboard_schema_migrations` table.
3. Create the new one running `CREATE TABLE IF NOT EXISTS focalboard_schema_migrations (Version bigint NOT NULL, Name varchar(64) NOT NULL, PRIMARY KEY (Version));`.
4. Insert the migrations that already have run (up to and including 17, as per the contents of the old `focalboard_schema_migrations` table) with the following `INSERT`:

```sql
INSERT INTO focalboard_schema_migrations (Version, Name) VALUES
(1, 'init'),
(2, 'system_settings_table'),
(3, 'blocks_rootid'),
(4, 'auth_table'),
(5, 'blocks_modifiedby'),
(6, 'sharing_table'),
(7, 'workspaces_table'),
(8, 'teams'),
(9, 'blocks_history'),
(10, 'blocks_created_by'),
(11, 'match_collation'),
(12, 'match_column_collation'),
(13, 'millisecond_timestamps'),
(14, 'add_not_null_constraint'),
(15, 'blocks_history_no_nulls'),
(16, 'subscriptions_table'),
(17, 'add_file_info');
```

5. Install a plugin version greater than `v7.1`.

These steps can be performed while the Mattermost server is running, and in case anything goes wrong, the process to recover the data would be to remove the installed `focalboard` plugin and restore the `focalboard_` prefixed tables.

**Comment by shieldsjared** [comment]
@mgdelacroix - Here are the tables that I'm currently seeing:
- focalboard_blocks
- focalboard_blocks_history
- focalboard_file_info
- focalboard_notification_hints
- focalboard_schema_migrations
- focalboard_sessions
- focalboard_sharing
- focalboard_subscriptions
- focalboard_system_settings
- focalboard_users
- focalboard_workspaces

I've gone ahead and implemented the workaround and things are working great! Thanks so much for your help :D

**Comment by sbishel** [comment]
Thanks @mgdelacroix. Closing.....
