### ISSUE TITLE
Bug: Boards Bot notifications displaying incorrectly

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#4594]
## Steps to reproduce the behavior

1. Sign-in as user A and follow any card
2. Sign-in as user B and make changes to the same card
3. Go back to user A and wait for the change notification from Boards Bot
4. See error - Field IDs are displayed instead of the property name, and old values are crossed out, but the new values are not shown in the notification. Seems to occur on non `SELECT` property types.

## Expected behavior

Property names and new values are displayed in the notification.

### Current
<img width="289" alt="image" src="https://user-images.githubusercontent.com/93531870/220479008-bd48b483-7c03-4a5c-81f4-a154fc31a393.png">
<img width="450" alt="image2" src="https://user-images.githubusercontent.com/93531870/220479018-823b7139-48ee-4037-a43b-73d4a0e9860c.png">

### Expected
![Screen Shot 2023-02-21 at 6 07 04 PM](https://user-images.githubusercontent.com/93531870/220479094-5c2c922e-324b-458f-a9b6-3a6896a38f71.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.8
 - Browser and OS:

**Comment by sbishel** [comment]
@crspeller This was probably caused by a recent change.

**Comment by wuwinson** [comment]
@crspeller I wasn't able to reproduce this issue on Community (v7.9). @jprusch Feel free to add any additional details here. Thanks!

**Comment by jprusch** [comment]
Was working with 7.8
I'll restart the server tomorrow & retry. 
Does debug logging help here?

**Comment by crspeller** [comment]
Can't reproduce on main as well.

**Comment by jprusch** [comment]
We still see this error on the notification received.

I restarted the Mattermost server (7.8.0). Board plugin is 7.8.2. Database scheme is 101 (mysql).

On startup we still get:

```
error [2023-03-01 08:52:32.654 +01:00] Failed to sync plugin from file store         caller="app/plugin.go:366" bundle=plugins/focalboard.tar.gz error="installExtractedPlugin: Unable to restart plugin on upgrade., error initializing the DB: Error 1054: Unknown column 'dirty' in 'field list' in line 0: SELECT version, dirty FROM `focalboard_schema_migrations` LIMIT 1"
```

Not sure if this is relevant, but the following is logged, when moving a card:
```
error [2023-03-01 08:26:37.801 +01:00] Cannot parse properties for old block         caller="app/plugin_api.go:976" plugin_id=focalboard block_id=c8gtmm69qegnep7di9kbersmfre error=""could not p
arse property value (ekbo3bcsojy8bbhndh6t8y9ijw): multiPerson property type: invalid property value type""
error [2023-03-01 08:26:37.801 +01:00] Cannot parse properties for new block         caller="app/plugin_api.go:976" plugin_id=focalboard block_id=c8gtmm69qegnep7di9kbersmfre error=""could not p
arse property value (ekbo3bcsojy8bbhndh6t8y9ijw): multiPerson property type: invalid property value type""
error [2023-03-01 08:26:39.605 +01:00] Cannot parse properties for old block         caller="app/plugin_api.go:976" plugin_id=focalboard block_id=cyrmdbkpfo4mcrshkxnfwd4jdfa error=""could not p
arse property value (6pkw11zuwigkmbd3nuwd1rueqa): multiPerson property type: invalid property value type""
error [2023-03-01 08:26:39.605 +01:00] Cannot parse properties for new block         caller="app/plugin_api.go:976" plugin_id=focalboard block_id=cyrmdbkpfo4mcrshkxnfwd4jdfa error=""could not p
arse property value (6pkw11zuwigkmbd3nuwd1rueqa): multiPerson property type: invalid property value type""
```

A card looks like this:
<img width="505" alt="image" src="https://user-images.githubusercontent.com/9337414/222079411-f8adc083-94e2-479b-9a48-9b4994ccdf61.png">
