### ISSUE TITLE
Bug: Fresh Docker image installation is not starting up

### ISSUE THREAD

**Issue by orbatschow** [mattermost/focalboard#4601]
## Steps to reproduce the behavior

1. Try to run the official Docker image according to the documentation:

```shell
docker run -it -p 80:8000 mattermost/focalboard:7.8.0
```

2. The container freezes during startup for an unlimited amount of time.

Logs:

```
debug [2023-02-23 15:04:25.587 Z] Closing migration engine                 caller="sqlstore/migrate.go:208"
info  [2023-02-23 15:04:25.587 Z] Initialized notification backend         caller="notify/service.go:60" name=notifyLogger
debug [2023-02-23 15:04:25.587 Z] Fetched template boards                  caller="app/templates.go:30" count=0
debug [2023-02-23 15:04:25.587 Z] Importing new default templates          caller="app/templates.go:38" reason="no default templates found" size=6176812
debug [2023-02-23 15:04:25.587 Z] Removed default templates                caller="sqlstore/templates.go:52" count=0
debug [2023-02-23 15:04:25.587 Z] importing archive                        caller="app/import.go:56"
debug [2023-02-23 15:04:31.288 Z] import archive - done                    caller="app/import.go:65" boards_imported=13
info  [2023-02-23 15:04:31.297 Z] initialized team                         caller="app/teams.go:30"
info  [2023-02-23 15:04:31.303 Z] Server.Start                             caller="server/server.go:243"
info  [2023-02-23 15:04:31.303 Z] http server started                      caller="web/webserver.go:125" port=8000
info  [2023-02-23 15:04:31.304 Z] Starting unix socket server              caller="server/server.go:403"
```

## Expected behavior

The container should start the HTTP server and serve requests. 

## Edition and Platform

OS: Arch Linux x86_64
Kernel: 6.1.12-arch1-1

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround

**Comment by orbatschow** [comment]
Okay, this seems to be an issue on my site. I started the container and forwarded the wrong port to my local machine. The last log line I saw was:

```
Starting unix socket server              caller="server/server.go:403"
```

Because the port was not forwarded correctly I assumed, that the server start was somehow broken and the server will hang forever. I think this can be closed, sorry!

**Comment by pravnkay** [comment]
Can you please explain how to solve this ?
I am also trying to run the docker container on a new DigitalOcean droplet and getting struck at same spot.
