### ISSUE TITLE
Bug:  infinite redirection loop when clicking table view

### ISSUE THREAD

**Issue by notaprodev** [mattermost/focalboard#4606]
## Steps to reproduce the behavior

1. Go to a board that has a view
2. Click Table view on that board
3. See error loop for about 1 minute.

## Expected behavior

Get the view of that board 

## Screenshots (optional)

If applicable, add screenshots or a screen recording to elaborate on the problem.

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: Mattermost 7.8
 - Browser and OS: Firefox on Ubuntu 20.04

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 2: Affects major functionality with a difficult or non-obvious workaround

**Comment by wuwinson** [comment]
@notaprodev Can you share any screen recordings and logs? Does this happen for all boards or only a certain board? What about other views? Any details you can provide would be helpful. Thanks!
