### ISSUE TITLE
Feature Idea: Table column aggregations

### ISSUE THREAD

**Issue by Johennes** [mattermost/focalboard#461]
**Summary:**

The table view type would be even more useful if it allowed for user-defined column aggregations. I'd be most interested in seeing a sum aggregation being implemented for number types. Other interesting numeric aggregations are minimum, maximum and average. Additionally, a count and unique count aggregation would be great to have irrespective of the data type.

**How important this is to me and why:**

Importance: Medium

Use cases:

1. I have a table of vacation days and want to compute the sum of days taken
2. I have a table of tasks and want to known the average story points / time estimate per task
3. I have a table of anything and want to know how many rows it contains

**Additional context / similar features:**

Here's a screenshot of the same feature in Notion.

![Screenshot 2021-05-24 at 19 44 48](https://user-images.githubusercontent.com/1137962/119387036-a43eeb00-bcc8-11eb-9bc3-ea2e4f0a6a64.png)

I don't think we'd need all of the aggregations Notion offers, at least not from the start.

**Comment by harshilsharma63** [comment]
FYI I'm working on this.

**Comment by harshilsharma63** [comment]
This was implemented in #761
