### ISSUE TITLE
Bug: High CPU usage caused by infinte redirection loop when personal server is stopped

### ISSUE THREAD

**Issue by anx-ag** [mattermost/focalboard#4632]
## Steps to reproduce the behavior

1. Open Chrome or Microsoft Edge and visit the website of your focalboard personal server
2. Stop the focalboard server
3. Watch the addressbar, it will start printing redirects
4. Watch CPU usage, it will spike to 100%

## Expected behavior

The web application should handle a server disconnect gracefully.

## Edition and Platform

 - Edition: Personal Server
 - Version: 7.9.1
 - Browser and OS: Chrome and Edge on Windows, Firefox is _NOT_ affected because it stops the redirect loop after a few seconds

P.S.:
I was unable to reproduce that with Boards as part of Mattermost, since after killing the plugin, it gets restarted automatically and after disabling the plugin, the page automatically and immediately blanks, which seems to work around this issue.

**Comment by sbishel** [comment]
@mgdelacroix - This appears to be happening because we constantly attempt to reconnect the websocket.

**Comment by mgdelacroix** [comment]
Fixed via https://github.com/mattermost/focalboard/pull/4722
