### ISSUE TITLE
Bug: Custom Emoji not rendering

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#4633]
## Steps to reproduce the behavior

1. Go to a board
2. Click on the emoji that was generated for the board
3. Hover over Pick icon
4. Observe: emoji don't render

## Expected behavior

Emoji render

## Screenshots (optional)
Win10/Chrome
![image](https://user-images.githubusercontent.com/13020833/224814383-6096093d-9f97-4750-ad04-c1570d73c31c.png)
macOS/Safari
![image](https://user-images.githubusercontent.com/13020833/224814458-ee6905ef-5719-4152-9989-9a1863c14f95.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin) 
 - Version: v7.9.1
 - Browser and OS: Win10/Chrome & macOS/Safari

## Jira ticket

 - https://mattermost.atlassian.net/browse/MM-51358

**Comment by MioAtSwivel** [comment]
Can confirm on this issue, affecting all emojis not just the custom one.

**Comment by lindy65** [comment]
@MioAtSwivel - a fix for this has been merged https://github.com/mattermost/focalboard/pull/4635

**Comment by MioAtSwivel** [comment]
I'll update it and confirm the fix, thanks for the reminder 👍
