### ISSUE TITLE
Bug: no new container images published to Docker Hub

### ISSUE THREAD

**Issue by spantaleev** [mattermost/focalboard#4651]
The last tag published for the [container image to Docker Hub](https://hub.docker.com/r/mattermost/focalboard) is `7.8.0`, released more than a month ago (on 7th of February 2023).

The up-to-date versions right now are `7.8.3` (on the 7.8.x branch) and 7.9.2 (on the 7.9.x branch).

For some reason, publishing images to Docker Hub stopped more than a month ago. I could find a few issues (#4600, #4637) from people failing to build the image themselves. I could not find another issue about prebuilt images not being published to Docker Hub anymore.

Is this intentional? Perhaps the docs should be updated to tell people to build their own images if they'd like to be up-to-date.

Or is this a bug with the build pipeline?

**Comment by sbishel** [comment]
https://github.com/mattermost/focalboard/issues/91

**Comment by spantaleev** [comment]
Yes, I found some instructions for building the image, but:

- the [Personal Edition / Personal Server (Docker)](https://www.focalboard.com/download/personal-edition/docker/) page still tells you to pull `mattermost/focalboard` (= `mattermost/focalboard:latest`) from Docker Hub, which is outdated

- I don't see it being acknowledged anywhere that one should disregard the (outdated) `mattermost/focalboard` image and instead build the image manually

I take it that (despite the documentation/website not being updated), the stance is that the `mattermost/focalboard` image published to Docker Hub has been abandoned and people are recommended to build the image themselves?

**Comment by sbishel** [comment]
related to https://github.com/mattermost/focalboard/issues/4637
Will need to create dot releases to update dockerhub for release builds but `edge` is now working.

**Comment by sbishel** [comment]
This has been fixed and latest versions have been published.
