### ISSUE TITLE
Bug: Personal Desktop App not starting on Windows without Admin rights

### ISSUE THREAD

**Issue by KaiDroste** [mattermost/focalboard#4658]
## Steps to reproduce the behavior

1. Sign in as a Windows user without admin rights.
2. start Focalboard 7.9.2 from the downloaded and unzipped release.
3. nothing happens.

Since the Windows app store is blocked on my computer, I need to download focalboard from GitHub. 
Now I am running v7.5.2 without problems. But when I try to download and start a newer version it is not possible.
If I login into the PC with the administrator account focalboard starts without problems. 
Starting focalboard with the restricted user and admin rights fails also since edge has now read and write access to the admin's user folder. 

## Edition and Platform

 - Edition: Personal Desktop
 - Version: [7.9.2]
 - Browser and OS: [Edge on Windows]

**Comment by KaiDroste** [comment]
@crspeller Thank you for your response. As far as I know, I have not started the binary as administrator for the first time. 

Is there a debug modus or a log file where I can look at what happens during the startup?

**Comment by crspeller** [comment]
@KaiDroste You can press `Ctrl-Shift+I` That will bring up the dev tools. There might be something helpful in the console logs there.

**Comment by KaiDroste** [comment]
@crspeller for me no dev-tools are starting. As well in the currently running v7.5.2 as in v7.9.2.

**Comment by crspeller** [comment]
Hmm, not sure why that could be. Why do you mention Edge at all in your report? The boards app brings up its own thing. Could you be more detailed in what steps you took to reproduce?

**Comment by KaiDroste** [comment]
I mentioned Edge because when starting focalboard with the admin rights it says that there is no read and write access for MS Edge. Isn't focalboard using edge for the interface? 

For me, the steps are: 

1. Download the .zip from the release files on github
2. extract the folder to c:/focalboard. 
3. start the focalboard.exe 
4. without admin rights: nothing will happen / with admin rights: it will show that there are missing permission. 

That is the prompt:
![image](https://user-images.githubusercontent.com/59448194/229810233-725ca66c-39eb-4259-a601-e4249cfeec16.png)

**Comment by crspeller** [comment]
@KaiDroste Could you try extracting the folder to a user folder like the desktop or your `Documents` folder and see if you see the same issue?

**Comment by KaiDroste** [comment]
I have tested different folders on my pc without any changes. 
Furthermore, I have tested another PC with the same user account restrictions as mine. On this Pc, Focalboard starts without problems. 
Since the Windows Smart Screen window appears during the first startup on my PC, I think the startup could be blocked by the smartscreen filter or something else. I also tried to deactivate the smart screen filter, but this makes no difference.

**Comment by crspeller** [comment]
It might be the case that your permissions on the boards DB file is not correct. Did you check the permissions on those files? (`Documents/Focalboard`)

**Comment by KaiDroste** [comment]
So, I have deleted/renamed the focalboard folder within Documents. After this, I was able to start V7.9.3 without problems. From my side, the issue can then be closed.

**Comment by crspeller** [comment]
No problem! Glad we got it solved.
