### ISSUE TITLE
Manually updating Windows personal client from ZIP file

### ISSUE THREAD

**Issue by citydelver** [mattermost/focalboard#467]
Hello. This isn't a bug nor a feature request, just a question. I can't use the Microsoft Store version because I'm on Windows 8.1, so I am using the zip file (thanks for it!). How should I update though, to ensure there's no data loss?

**Comment by Johennes** [comment]
@citydelver you could try to export / import it via the settings menu.

![Screenshot 2021-05-25 at 18 23 30](https://user-images.githubusercontent.com/1137962/119533637-5983a880-bd86-11eb-96ff-d663a52154b6.png)

The [user guide](https://www.focalboard.com/guide/user/) actually seems to recommend this for transferring data between different installations. The only current limitation appears to be that images and other file attachments won't be migrated.

> Note that the archive does not (currently) include image and file attachments, such as images included in a card.

**Comment by citydelver** [comment]
Thanks!
