### ISSUE TITLE
Bug: Personal Desktop migration error

### ISSUE THREAD

**Issue by roukmoute** [mattermost/focalboard#4676]
## Steps to reproduce the behavior

1. Go to the connection page
2. Enter your login credentials
3. Click on the 'Connect' button
4. See the "login failed" error message

## Expected behavior

I expected to be able to log in successfully as I have been able to do so before the recent update.

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/2140469/228540980-e1f4f190-1db3-402d-98ea-621444afb5d4.png)

![image](https://user-images.githubusercontent.com/2140469/228540667-a8408907-e4ec-4037-850b-30de53ac5019.png)

## Edition and Platform

- Edition: Docker on Unraid
- Version: `mattermost/focalboard                      latest           6a5c766fb943   7 weeks ago     126MB`
- Browser and OS: Firefox 111.0.1 on Windows 11

## Additional context (optional)

After checking the logs, I noticed the following message looping continuously:

```
debug [2023-03-29 14:41:15.832 +02:00] Command: AUTH caller="ws/server.go:149" client="172.18.0.5:59884"
debug [2023-03-29 14:41:15.832 +02:00] authenticateListener caller="ws/server.go:436" token=k4a44ui48a78pp8ajqkrmcgfwtw wsSession.userID=
error [2023-03-29 14:41:15.832 +02:00] ERROR WebSocket caller="ws/server.go:130" client="172.18.0.5:59884" error="read tcp 172.18.0.6:8000->172.18.0.5:59884: use of closed network connection"
debug [2023-03-29 14:41:15.832 +02:00] DISCONNECT WebSocket caller="ws/server.go:119" client="172.18.0.5:59884"
```

Severity: Sev 2 - Affects major functionality with a difficult or non-obvious workaround.

**Comment by roukmoute** [comment]
It is with regret that I inform you of my decision to stop using this tool for the moment, although it is very well designed when we start from zero. Unfortunately, I have encountered several problems during updates, despite using the Docker image update, which should normally ensure optimal operation.

During the first update,[ I lost data in the left menu](https://github.com/mattermost/focalboard/issues/4293), and now, following another update, I can't connect because the database has been overwritten. These problems have a significant impact and prevent me from continuing to use this tool in good conditions.

I thank you for your understanding and I hope that these problems can be solved in the future.

**Comment by mgdelacroix** [comment]
hi @roukmoute. I'm sorry for the trouble you've gone through with the docker images, and hope you decide to give the tool a try in the future. The issue you faced is related to the database migrations, and it should have not deleted any data (although you may have seen it absent on the interface). If you're interested on debugging the issue further, I'd need the output of running `.schema` on the sqlite database and the contents of the `schema_migrations` table to see what's the state of the migrations.

@ulysserevient what action are you trying to perform when you see these logs? Could you please post the server logs for the startup process and the ones for when the error happens?

**Comment by mgdelacroix** [comment]
Closing the issue as there is currently no way of investigating further, please feel free to reopen if necessary
