### ISSUE TITLE
Bug: Http handler panic

### ISSUE THREAD

**Issue by KakEgorka** [mattermost/focalboard#4691]
In Logs:
`{"timestamp":"2023-04-03 11:08:09.574 +05:00","level":"info","msg":"can't open new logfile: open focalboard_errors.log: permission denied\ncan't open new logfile: open focalboard_errors.log: permission denied\ncan't open new logfile: open focalboard_errors.log: permission denied\n","caller":"io/io.go:428","plugin_id":"focalboard","source":"plugin_stderr"}
{"timestamp":"2023-04-03 11:08:09.575 +05:00","level":"error","msg":"Http handler panic","caller":"app/plugin_api.go:976","plugin_id":"focalboard","panic":"\"runtime error: invalid memory address or nil pointer dereference\"","stack":"\"goroutine 546658 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/mattermost/focalboard/server/api.(*API).panicHandler.func1.1()\n\tgithub.com/mattermost/focalboard/server/api/api.go:127 +0x125\npanic({0x1252880, 0x24a71f0})\n\truntime/panic.go:838 +0x207\ngithub.com/mattermost/focalboard/server/api.(*API).handleServeFile(0xc000be1c80, {0x16335d8, 0xc001b3cb00}, 0x1628101?)\n\tgithub.com/mattermost/focalboard/server/api/files.go:173 +0xb92\ngithub.com/mattermost/focalboard/server/api.(*API).attachSession.func1({0x16335d8, 0xc001b3cb00}, 0xc0016ff400)\n\tgithub.com/mattermost/focalboard/server/api/auth.go:369 +0x9a8\nnet/http.HandlerFunc.ServeHTTP(0xc001a06a50?, {0x16335d8?, 0xc001b3cb00?}, 0xc0017d2f90?)\n\tnet/http/server.go:2084 +0x2f\ngithub.com/mattermost/focalboard/server/api.(*API).requireCSRFToken.func1({0x16335d8, 0xc001b3cb00}, 0xc0016ff400)\n\tgithub.com/mattermost/focalboard/server/api/api.go:146 +0xa5\nnet/http.HandlerFunc.ServeHTTP(0x90?, {0x16335d8?, 0xc001b3cb00?}, 0xc00117b508?)\n\tnet/http/server.go:2084 +0x2f\ngithub.com/mattermost/focalboard/server/api.(*API).panicHandler.func1({0x16335d8?, 0xc001b3cb00?}, 0xc0017d2f90?)\n\tgithub.com/mattermost/focalboard/server/api/api.go:134 +0x92\nnet/http.HandlerFunc.ServeHTTP(0xc0016ff300?, {0x16335d8?, 0xc001b3cb00?}, 0xc00189cd58?)\n\tnet/http/server.go:2084 +0x2f\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc00053a780, {0x16335d8, 0xc001b3cb00}, 0xc00159e500)\n\tgithub.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf\ngithub.com/mattermost/focalboard/mattermost-plugin/server/boards.(*BoardsApp).ServeHTTP(...)\n\tgithub.com/mattermost/focalboard/mattermost-plugin/server/boards/boardsapp.go:226\nmain.(*Plugin).ServeHTTP(0x7f54435c0008?, 0x13449c0?, {0x16335d8?, 0xc001b3cb00?}, 0x3?)\n\tgithub.com/mattermost/focalboard/mattermost-plugin/server/plugin.go:110 +0x4f\ngithub.com/mattermost/mattermost-server/v6/plugin.(*hooksRPCServer).ServeHTTP(0xc00035e140, 0xc001f48020, 0x1?)\n\tgithub.com/mattermost/mattermost-server/v6/plugin/client_rpc.go:453 +0x378\nreflect.Value.call({0xc000501320?, 0xc0005067e0?, 0x13?}, {0x13abf43, 0x4}, {0xc000e6bef8, 0x3, 0x3?})\n\treflect/value.go:556 +0x845\nreflect.Value.Call({0xc000501320?, 0xc0005067e0?, 0x0?}, {0xc001218ef8, 0x3, 0x3})\n\treflect/value.go:339 +0xbf\nnet/rpc.(*service).call(0xc0003ccf80, 0xc0001141e0?, 0x0?, 0xc000116230, 0xc00018d080, 0xc001218f48?, {0x11aff60?, 0xc001f48020?, 0xc00053a000?}, {0x11c0620, ...}, ...)\n\tnet/rpc/server.go:381 +0x226\ncreated by net/rpc.(*Server).ServeCodec\n\tnet/rpc/server.go:478 +0x3fe\n\"","uri":"/api/v2/files/teams/o1drkygwnffq3ywrsegc6r83io/bqbj7zgei77bk38hkzmw1x46rje/7it6sekq5yfne7xjgqnbczqs9pc.png"}
{"timestamp":"2023-04-03 11:08:09.575 +05:00","level":"error","msg":"http handler panic","caller":"app/plugin_api.go:976","plugin_id":"focalboard"}
{"timestamp":"2023-04-03 11:08:09.575 +05:00","level":"error","msg":"API ERROR","caller":"app/plugin_api.go:976","plugin_id":"focalboard","code":"500","error":"\"http handler panic\"","api":"/api/v2/files/teams/o1drkygwnffq3ywrsegc6r83io/bqbj7zgei77bk38hkzmw1x46rje/7it6sekq5yfne7xjgqnbczqs9pc.png"}
`

Please tell me where the file should be focalboard_errors.log ?

And why do you need a license for boards?

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.7.1
 - Browser and OS: all

**Comment by wiggin77** [comment]
@KakEgorka the user under which Boards is run does not have file permissions to write log files.  That is the source of the first error.  The main error is a panic caught and handled when the client requests a file, such as card image or file attachment.  It happens when the error is something other than `not found`, such as no read permissions for the file store.  It could also be a connectivity error if you are using S3.

The panic is fixed via https://github.com/mattermost/focalboard/pull/4693 in that it will no longer panic, however the underlying error (permissions or connectivity to the file store) will need to be resolved for images/files to appear.

**Comment by KakEgorka** [comment]
Can you please tell me in which directory the log file should be written?

**Comment by KakEgorka** [comment]
> @KakEgorka the user under which Boards is run does not have file permissions to write log files. That is the source of the first error. The main error is a panic caught and handled when the client requests a file, such as card image or file attachment. It happens when the error is something other than `not found`, such as no read permissions for the file store. It could also be a connectivity error if you are using S3.
> 
> The panic is fixed via #4693 in that it will no longer panic, however the underlying error (permissions or connectivity to the file store) will need to be resolved for images/files to appear.

Can you please tell me in which directory the log file should be written?

**Comment by KakEgorka** [comment]
> @KakEgorka it depends on your setup (docker versus standalone) but generally it will write logs to the working directory when the binary is run. That could be the same directory as the binary or somewhere else if you have a start-up script that calls the binary with a direct path.

We have rights for the mattermost user on the "/opt/mattermost/logs" folder open and logs from mattermost are written there. But there are no more places where the logs are written.
