### ISSUE TITLE
Bug: Infinite redirect loop

### ISSUE THREAD

**Issue by pesicnikola** [mattermost/focalboard#4710]
We have been affected by redirection loop when we try opening the board. Board itself gets into some kind of loop, continuously loads and never load. While redirecting url keeps expanding and adding new /boards path (see the screenshot bellow).

![board](https://user-images.githubusercontent.com/130546366/231398499-a9c98303-a982-4c4f-b32e-cd66d868d4de.png)

We're using Mattermost Comunity version 7.8.1 hosted on our local server and version 7.8.2 of focalboard plugin.

**Comment by wuwinson** [comment]
@pesicnikola Can you share server and browser logs with us? cc @sbishel

**Comment by wuwinson** [comment]
Closing out. If you're still running into this issue, please feel free to file a new issue following [these instructions](https://github.com/mattermost/focalboard/issues/4721). Thanks!
