### ISSUE TITLE
Is this a reliable project?

### ISSUE THREAD

**Issue by AuspeXeu** [mattermost/focalboard#4714]
Since development seems rather sluggish and same for responses to issues. As a business owner, I am wondering if I can rely on focalboard to be around in, let's say 1 year, 5 years? Or is this just an internal porject gone open source which will later be abandoned?

**Comment by wuwinson** [comment]
Hi @AuspeXeu, thanks for reaching out and sorry for any issues you've encountered. To answer your question - yes this is a reliable project, but the Focalboard team will be prioritizing our focus on the Boards product within the Mattermost platform. My sincerest apologies if we did not communicate this clearly. Please see [this discussion](https://github.com/mattermost/focalboard/discussions/4645) for more details. Hope that helps clear things up, but please don't hesitate to reach out if you have any questions.

**Comment by AuspeXeu** [comment]
@wuwinson might be worth creating an issue that refences your discussion and pin it so that everyone who navigates to the issues section of this repo will read it?

**Comment by wuwinson** [comment]
Thanks for the suggestion @AuspeXeu! Pinned https://github.com/mattermost/focalboard/issues/4721.
