### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by PeterQuach** [mattermost/focalboard#4715]
## Steps to reproduce the behavior

1. Go to ...Board
2. Select  ...Overview tasks
3. Select header column. Sort on Ascending order for a field has data as input
4. See error and flashing screen on one of the board

## Expected behavior

display task overview with sorted data

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/131202056/232887822-bf605aa9-b7b9-4d91-8f2c-89a1242c3148.png)

## Edition and Platform

 - Edition: Personal Desktop / Personal Server / Mattermost Boards (plugin)
 - Version: [e.g. v0.15.0]
 - Browser and OS: [e.g. Chrome on Mac, Edge on Windows]

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by sbishel** [comment]
@PeterQuach - Could you see if there is any information in logs?

**Comment by wuwinson** [comment]
Closing out. If you're still running into this issue, please feel free to file a new issue following [these instructions](https://github.com/mattermost/focalboard/issues/4721). Thanks!
