### ISSUE TITLE
Bug: Card banners use light background in dark theme

### ISSUE THREAD

**Issue by Johennes** [mattermost/focalboard#472]
**Summary:**

Banner views on cards are currently using a light background in the dark theme which makes them illegible.

**Steps to reproduce the behavior:**

1. Open a board
2. Click New > New template
3. Notice the light banner with illegible text

**Expected behavior:**

The banner should have a suitable dark background.

**Screenshots:**

![Screenshot 2021-05-25 at 18 46 40](https://user-images.githubusercontent.com/1137962/119536936-dd8b5f80-bd89-11eb-8880-b48360a6d688.png)

**Platform:**
 - Firefox 88.0.1
 - macOs
 - Focalboard from current main branch

**Additional context:**

Looks like the color might be fixed in [dialog.scss](https://github.com/mattermost/focalboard/blob/main/webapp/src/components/dialog.scss#L47).

**Comment by chenilim** [comment]
Should be fixed by #336.
