### ISSUE TITLE
:warning: PLEASE READ ME FIRST :warning:

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#4721]
Focalboard Personal Server and Personal Desktop editions will transition to being fully community supported as of April 30th, 2023. This Focalboard repository will become the Personal Edition repository, and will remain open indefinitely. However, we won’t be adding any new enhancements, and will only address Sev-1 level bugs until April 30th, 2023.

The Boards plugin version will be integrated into Mattermost as a core in-product feature, and will no longer be supported as a plugin as of release v7.11 (May 2023). The plugin code will be merged into the [Mattermost-server repository](https://github.com/mattermost/mattermost-server) where future enhancements will be added to moving forward. **New pull requests and issues for should be filed against https://github.com/mattermost/mattermost-server.**

Please see https://github.com/mattermost/focalboard/discussions/4645 for more details.

**Comment by sbishel** [comment]
No longer relevant or true
