### ISSUE TITLE
Bug: Get stuck when paste picture from clipboard

### ISSUE THREAD

**Issue by xingwen7** [mattermost/focalboard#4735]
## Steps to reproduce the behavior

1. Go to any chat window
2. Copy a picture from anywhere
3. Paste the picture into the input block
4. App stuck

## Expected behavior

Quick response and smooth operation when pasting pictures

## Edition and Platform

 - Edition: Personal Desktop
 - Version: [e.g. v5.39.3]
 - Browser and OS: [e.g. Chrome on Mac, Chrome on Ubuntu 20.04]

## Additional context (optional)

This problem exist both in Desktop App and web.

**Comment by wuwinson** [comment]
@xingwen7 Can you share a screen recording of your issue? The Personal Desktop edition does not have a chat component to it. Thanks!

**Comment by xingwen7** [comment]
> @xingwen7 Can you share a screen recording of your issue? The Personal Desktop edition does not have a chat component to it. Thanks!

It's OK now, the issue can be closed.
