### ISSUE TITLE
Feature Idea: Reorder comments on cards

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#479]
**Summary:**
Display comments on cards - newest first. (or switchable)

**How important this is to me and why:**
Medium - 
Importance: High/Medium/Low

Use cases:
1. If lots of comments, scrolling to bottom would be cumbersome to see latest comments.
2.

**Additional context / similar features:**
Any examples of good implementations of this capability.
Jira allows this capability.

**Comment by chenilim** [comment]
Initial reaction is to add a toggle to change sort order.

**Comment by michaelgamble** [comment]
@asaadmahmood I unassigned myself off in favor of you taking this over

**Comment by sbishel** [comment]
complete
