### ISSUE TITLE
Bug: Server not starting due to admin local socket file lock

### ISSUE THREAD

**Issue by balajib-b** [mattermost/focalboard#481]
**Summary:**
2021/05/26 18:50:23 Focalboard Server
2021/05/26 18:50:23 Version: 0.6.7
2021/05/26 18:50:23 Edition: linux
2021/05/26 18:50:23 Build Number: 836453774
2021/05/26 18:50:23 Build Date: Wed May 12 18:22:51 UTC 2021
2021/05/26 18:50:23 Build Hash: 8a29fff01e57a623e1a39be22096e4a860280026
2021/05/26 18:50:23 readConfigFile
2021/05/26 18:50:23 {ServerRoot:http://localhost:9800 Port:9800 DBType:sqlite3 DBConfigString:./focalboard.db DBTablePrefix: UseSSL:false SecureCookie:false WebPath:./pack FilesPath:./files Telemetry:false WebhookUpdate:[] Secret:hidden SessionExpireTime:2592000 SessionRefreshTime:18000 LocalOnly:false EnableLocalMode:true LocalModeSocketLocation:/var/tmp/focalboard_local.socket AuthMode:native MattermostURL: MattermostClientID:hidden MattermostClientSecret:hidden}
2021/05/26 18:50:23 connectDatabase sqlite3 ./focalboard.db
{"level":"info","ts":1622035223.5264194,"caller":"server/server.go:186","msg":"Server.Start"}
2021/05/26 18:50:23 http server started on :9800
2021/05/26 18:50:23 Unable to unlink socket.no such file or directory
2021/05/26 18:50:23 server.Start ERROR: no such file or directory

**Steps to reproduce the behavior:**
I have changed port in config.json and nginx upstream
Install as per the documentation and got to /opt/focalboard
run bin/focalboard-server

**Expected behavior:**
server must start successfully

**Screenshots:**
![image](https://user-images.githubusercontent.com/64471553/119667129-9d90af00-be53-11eb-8a4e-9a492732c582.png)

**Platform:**
 - Browser and version: firefox 88
 - OS and version: ubuntu 20.04

**Additional context:**

**Comment by chenilim** [comment]
Thanks @balajib-b. This sounds like an error initializing the local socket file used for the [admin interface](https://www.focalboard.com/guide/admin/#resetting-passwords).

I have seen this bug before too, where the local socket file gets locked by a previous process. Does anyone have more insights into how to avoid this?

As a workaround, try the following:
* Change the `localModeSocketLocation` filename setting in the [config](https://www.focalboard.com/guide/admin/#personal-server-configuration).
  * e.g. to `/var/tmp/focalboard_local-1.socket`
* Or turn off the admin interface by setting `enableLocalMode` to false

**Comment by deepss1** [comment]
> Thanks @balajib-b. This sounds like an error initializing the local socket file used for the [admin interface](https://www.focalboard.com/guide/admin/#resetting-passwords).
> 
> I have seen this bug before too, where the local socket file gets locked by a previous process. Does anyone have more insights into how to avoid this?
> 
> As a workaround, try the following:
> 
> * Change the `localModeSocketLocation` filename setting in the [config](https://www.focalboard.com/guide/admin/#personal-server-configuration).
>   
>   * e.g. to `/var/tmp/focalboard_local-1.socket`
> * Or turn off the admin interface by setting `enableLocalMode` to false

Just faced the same issue on Ubuntu 20.04

Changing filename did not work for me. It looked like focalboard was trying to delete a non existent file.

The second solution however worked for me. But no Admin interface in this case

**Comment by Pafzedog** [comment]
I tried this as a workaround:

`touch /var/tmp/focalboard_local.socket`

Admin interface seems to be working as I was able to change an user password with reset-password.sh script.

**Comment by pydubreucq** [comment]
Hi,
I had the same issue here.
Setting enableLocalMode to false worked for me.
Bye

**Comment by pono** [comment]
I needed to run `touch /var/tmp/focalboard_local.socket` as well. Debian 10 using the standard server install.

**Comment by balajib-b** [comment]
> I tried this as a workaround:
> 
> `touch /var/tmp/focalboard_local.socket`
> 
> Admin interface seems to be working as I was able to change an user password with reset-password.sh script.

Thank you, This one worked for me.
