### ISSUE TITLE
Bug: Can't see cursor in task description text area on Safari

### ISSUE THREAD

**Issue by mkraft** [mattermost/focalboard#482]
**Summary:**

Can't see cursor in task description text area on Safari making it really hard to input and edit text.

**Steps to reproduce the behavior:**
1. Go to a Project Tasks board using Safari browser on focalboard-community.octo.mattermost.com
2. Create a new task
3. Edit the description text
4. See that cursor is not visible

**Expected behavior:**
Normal cursor visibility.

**Platform:**
* Safari on macOS 11.4
* Focalboard v0.6.7 beta

**Comment by chenilim** [comment]
Thanks @mkraft! This is a regression. Confirmed that the cursor is not visible on the Mac App (v0.6.7) too, on both the default and dark themes.

**Comment by Ashvith** [comment]
Can confirm, this bug is also on the Linux version.

**Comment by harshilsharma63** [comment]
This fix now fixed on the main branch.
