### ISSUE TITLE
Bug: Mac app not available in Canada.

### ISSUE THREAD

**Issue by shavelli** [mattermost/focalboard#4928]
## Steps to reproduce the behavior

1. Navigate to the official website's downlaod section
2. Select the mac (app store download)
3. Try to download the app with a Canadian apple account)

## Expected behaviour
3. User is able to download the app

## Edition and Platform

 - Edition: Personal Desktop
 - Version: Latest
 - Browser and OS: Mac

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround

**Comment by NeckBeardPrince** [comment]
Also showing as not available in the United States

**Comment by NeckBeardPrince** [comment]
![CleanShot 2023-11-08 at 09 25 31](https://github.com/mattermost/focalboard/assets/6558867/7812e834-e0cd-4e96-97a8-e8ed4c77679e)

**Comment by CalArcher** [comment]
Also cannot find this in the US

**Comment by Drizzle-Lee** [comment]
appstore中国也是不可以下载

**Comment by Xeb0** [comment]
Same issue Poland :/

**Comment by mtheuma** [comment]
Same issue in the UK

**Comment by surf-rbood** [comment]
Same in the Netherlands

**Comment by BurnLoch** [comment]
Same issue in the Latvia...

**Comment by shavelli** [comment]
To all the people who have been waiting for this to get fixed. I found a workaround which works very well.

If you're able to install Docker, follow the docker setup instructions on the focalboard website. I've been using that temporarily. When the mac client comes out, if you need to switch, i believe you can just export the data and then import it into the mac client.

Hope that helps you too :).

**Comment by NeckBeardPrince** [comment]
Remarkable this has not even been acknowledged.

**Comment by NeckBeardPrince** [comment]
I checked today and it's now showing up in the US App Store.

**Comment by NeckBeardPrince** [comment]
Wait, is this right? The App Store version hasn't been updated in almost two years?

![CleanShot 2023-11-30 at 13 05 38](https://github.com/mattermost/focalboard/assets/6558867/ccf06789-d104-4e3d-8574-3b7e7cff1102)

![CleanShot 2023-11-30 at 13 04 29](https://github.com/mattermost/focalboard/assets/6558867/af21713f-061d-46db-9b9a-a928b5801dd8)
