### ISSUE TITLE
Bug: When using the empty board template dragging a card on top of another sends it to 'No Status'

### ISSUE THREAD

**Issue by coltoneshaw** [mattermost/focalboard#493]
**Summary:**
When dragging a card on top of another card it will automatically send the card back to `No Status`. This only happens when using the Empty Board template.

**Steps to reproduce the behavior:**
1. Create a new board with the `Empty Board` template and ensure you're in `Board View`.
2. Add a new group
3. Add two cards to the new group (They don't need names)
4. Drag one card on top of the other where it changes the color of the below card
5. You should see the card you're dragging go back to the `No Status` column.

**Expected behavior:**
When you use other templates you see this simply put the card you're dragging on top of the other card. I've tested the other templates and cannot recreate this behavior.

**Screenshots:**

Below I show this with the steps listed above in recreate, and using a template.

https://user-images.githubusercontent.com/46071821/120052646-45dd7980-bff4-11eb-96c0-28acdd2f733d.mov

**Platform:**
 - Browser and version: N/A - Focalboard app 0.6.7
 - OS and version: MacOS Big Sur 11.3.1

**Additional context:**
I cannot get this behavior to reproduce in the web app version tied to Mattermost.

**Comment by chenilim** [comment]
Thanks @coltoneshaw! I'm able to repro this on the Mac and Windows apps (v0.6.7), but (same as you) not on the web. Should be a fun one to debug! :)

**Comment by jespino** [comment]
This is no longer happening in main branch. My guess is it was related to old/not-full-on-sync data messing around.
