### ISSUE TITLE
Bug: A card will autofill the text from the previous comment

### ISSUE THREAD

**Issue by coltoneshaw** [mattermost/focalboard#498]
**Summary:**
If you submit a comment while on a card, your next comment will autofill that same text again. If you exit the card and come back the auto filled text will be gone.

**Steps to reproduce the behavior:**
1. Open a card
2. Leave a comment
3. Attempt to leave a second comment, see the autofilled text.

**Expected behavior:**
The comment section to not auto-fill the text.

**Screenshots:**

https://user-images.githubusercontent.com/46071821/120118111-ea7bca80-c15e-11eb-9e20-b5c62875f8df.mov

**Platform:**
 - Browser and version: Downloaded app - 0.6.7
 - OS and version: MacOS Big Sur

**Additional context:**

**Comment by coltoneshaw** [comment]
Looks like this might be a duplicate of https://github.com/mattermost/focalboard/issues/387

**Comment by chenilim** [comment]
Thanks @coltoneshaw! Yes, this appears to be a dup of #387.
