### ISSUE TITLE
Missing Edit icon

### ISSUE THREAD

**Issue by haardikdharma10** [mattermost/focalboard#50]
### Summary

The Edit and Delete options are misaligned when selecting a new board template.

### Steps to reproduce

1. Click on Add Board.
2. Click on `...` on the right hand side of any template.

### Observed behaviour (that appears unintentional) 

<img width="239" alt="Screenshot 2021-02-04 at 12 42 24 PM" src="https://user-images.githubusercontent.com/53044263/106858048-158d6a80-66e7-11eb-9695-5c52a7dad791.png">

### Expected behaviour 

Edit and Delete should be aligned. (Maybe add an icon for Edit)

**Comment by it33** [comment]
@chenilim could I get edit rights on this repro so I can add a "Bug" or "Improvement" label depending on which you feel it is?

**Comment by chenilim** [comment]
@it33, added you to the repo. This issue is a bug (missing Edit icon). Updated the label.

**Comment by it33** [comment]
Thanks @chenilim. @haardikdharma10 I've updated the title. Is this a bug you'd be interested in helping us fix?

**Comment by asaadmahmood** [comment]
Updating all the icons with a specific icon font may be something we take as a separate project, but for now we can use this one.
[edit_icon.svg.zip](https://github.com/mattermost/focalboard/files/6096681/edit_icon.svg.zip)

**Comment by jespino** [comment]
Done in main branch! :)
