### ISSUE TITLE
Bug: "Edit/Delete" menu is slightly hidden on the left-hand-side when clicking "Add Board" > 3-dots to the right of Board name

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#502]
Submitted on behalf of contributor `coltoneshaw`

**Summary:**
Clicking the three dots when adding a board brings up "Edit / Delete". A portion of that screen is hidden behind the edge.				

**Steps to reproduce the behavior:**
1. Click on Add Board
2. Click on 3-dots to the right of any board

**Expected behavior:**
Menu to Edit or Delete board appears but is slightly hidden on the left-hand-side

**Screenshots:**
![image](https://user-images.githubusercontent.com/13020833/120155591-48f18900-c1f1-11eb-8656-d48b23b8f7fa.png)

**Platform:**
 - Browser and version: Safari
 - OS and version: macOS Big Sur

**Comment by haardikdharma10** [comment]
Hey @lindy65, can you also have a look at this [discussion](https://github.com/mattermost/focalboard/discussions/397#discussioncomment-720787) :)

**Comment by lindy65** [comment]
Aah, thanks @haardikdharma10 - So difficult to find pre-existing reports ;)  I'll close this one off then as a dupe of (or covered in) https://github.com/mattermost/focalboard/discussions/397#discussioncomment-720787 👍 

//cc @coltoneshaw
