### ISSUE TITLE
Feature Idea: Release Focalboard Server 8.0

### ISSUE THREAD

**Issue by ThaDaVos** [mattermost/focalboard#5021]
## Summary

What the new capability is.

Please release a 8.0 version of Focalboard Server if possible

## How important this is to me and why

Importance: High/**Medium**/Low

Use cases:
1. Run the new version

## Additional context/similar features

Any examples of good implementations of this capability.

**Comment by alerque** [comment]
v8 has been released. This issue can be closed as completed.

**Comment by ThaDaVos** [comment]
Where can one get the Focalboard Server 8.0?

**Comment by vladaviedov** [comment]
There hasn't been a standalone release since 7.11.3
Is it really just plugin changes? Dependency updates don't justify a release?

**Comment by alerque** [comment]
The personal server and desktop editions were deprecated some time ago (#4721) and the plugin edition is basically in minimal maintenance mode. My request for them to pass the baton (complete with the current issue tracker and PRs) off to a community maintainer (#4875) has gone unanswered.
