### ISSUE TITLE
Bug: Various missing translations (see description/repro steps)

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#504]
Submitted on behalf of contributor `jprusch`

**Summary:**
Various missing translations (see description/repro steps below)

**Steps to reproduce the behavior:**
1. Opening the app > Not translated: Add or select a board from the sidebar to get started
2. Create new board > Wrong translation in German: Keine Status should be Kein Status
3. Create new board > New group > Missing translation on a new group created: New group
4. Create card template > Missing translations: Empty, New Property, Edit text, text, image, divider, checkbox

**Expected behavior:**
Translations are present and correct

**Platform:**
 - OS and version: Windows 10

**Comment by chenilim** [comment]
Weblate dashboard: https://translate.mattermost.com/projects/focalboard/webapp/

**Comment by chenilim** [comment]
Translations are set up and tracked via the Weblate platform, and anyone can contribute translations here: https://translate.mattermost.com/projects/focalboard/webapp/. In general, non-English languages will lag as new strings are added.
