### ISSUE TITLE
Bug: Scroll bars on a board remain visible even if all content is displayed on screen

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#505]
Submitted on behalf of contributor `jprusch`

**Summary:**
Scroll bars on a board remain visible even if all content is displayed on screen

**Steps to reproduce the behavior:**
1. Open Roadmap board
2. Observe horizontal and vertical scroll bars are visible
3. Resize the content on your screen so everything is within the view
4. Observed: Scroll bars remain visible

**Expected behavior:**
Scroll bars are visible only if there is content outside of your view

**Screenshots:**
![image](https://user-images.githubusercontent.com/13020833/120166352-c5d63000-c1fc-11eb-9f9a-cfc9f405ce74.png)

**Platform:**
 - OS and version: Windows 10

**Comment by chenilim** [comment]
Please retest against change with new scrolling.

**Comment by harshilsharma63** [comment]
This is probably fixed by https://github.com/mattermost/focalboard/pull/447 .
