### ISSUE TITLE
Bug: Highlight text is hidden on MacOS desktop app.

### ISSUE THREAD

**Issue by coltoneshaw** [mattermost/focalboard#506]
**Summary:**
When you highlight text on the macOS desktop application the highlighter (not official term) is hidden. 

On Firefox / Safari this works fine. It's isolated to the downloadable desktop app.

**Steps to reproduce the behavior:**
1. Go to any card
2. Highlight text (you won't see it highlighted)
3. type a key (this will delete the text like you'd expect)

**Expected behavior:**
To see the fun blue highlighted text.

**Screenshots:**

https://user-images.githubusercontent.com/46071821/120226780-dba41f00-c215-11eb-903d-d99c10903de1.mov

**Platform:**
 - Browser and version: MacOS downloaded app - 0.6.7
 - OS and version: MacOS big Sur.

**Additional context:**
This is related to - https://github.com/mattermost/focalboard/issues/407 however the behavior is slightly different as you can select.

**Comment by harshilsharma63** [comment]
This fix now fixed on the main branch.
