### ISSUE TITLE
Bug: 502 Bad Gateway on personal server installation

### ISSUE THREAD

**Issue by seungjaeryanlee** [mattermost/focalboard#513]
**Summary:**
Following the official personal server setup guide, I get 502 Bad Gateway.

**Steps to reproduce the behavior:**
1. Follow the [Personal Server (Ubuntu) setup](https://www.focalboard.com/download/personal-edition/ubuntu/)
    - Changed `server_name` to my custom domain.
    - Ran `certbot --nginx` and reloaded NGINX
2. Visiting my custom domain, I get **502 Bad Gateway | nginx/1.14.0 (Ubuntu)**.

**Expected behavior:**
I expected to see the Focalboard website.

**Screenshots:**
N/A

**Platform:**
 - Browser and version: Chrome 90.0.4430.212 (how I visited the website)
 - OS and version: Ubuntu 18.04 LTS (where the server is installed)

**Additional context:**
The personal server is on a DigitalOcean droplet with Ubuntu 18.04 LTS. It is the smallest droplet with 1 vCPU, 1 GB RAM. I did not install Postgresql yet, and I used Focalboard release v0.6.7.

Here are the outputs to the curl commands:

```bash
$ curl localhost:8000
curl: (7) Failed to connect to localhost port 8000: Connection refused
$ curl localhost
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>
```

NGINX logs in case it helps.

```bash
$ tail -f /var/log/nginx/error.log
...
2021/06/03 18:29:35 [notice] 2812#2812: signal process started
2021/06/03 18:29:42 [error] 2813#2813: *41 connect() failed (111: Connection refused) while connecting to upstream, client: 122.37.7.120, server: focalboard.example.io, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "focalboard.example.io"
2021/06/03 18:29:42 [error] 2813#2813: *41 connect() failed (111: Connection refused) while connecting to upstream, client: 122.37.7.120, server: focalboard.example.io, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8000/favicon.ico", host: "focalboard.example.io", referrer: "https://focalboard.example.io/"
````

**Comment by chenilim** [comment]
Thanks @seungjaeryanlee! The `curl localhost:8000` failed, indicating that the focalboard server is not running. Were you able to [run Focalboard as a service](https://www.focalboard.com/download/personal-edition/ubuntu/#configure-focalboard-to-run-as-a-service) successfully?

To debug, manually run:
```
cd /opt/focalboard
./bin/focalboard-server
```
Does the server run ok?

**Comment by seungjaeryanlee** [comment]
Thanks for the reply! I was able to set systemd without any errors following the [Configure Focalboard to run as a service](https://www.focalboard.com/download/personal-edition/ubuntu/#configure-focalboard-to-run-as-a-service) that you linked. 

Here is what I get when I run the two lines you mentioned above:

```
2021/06/04 22:57:09 Focalboard Server
2021/06/04 22:57:09 Version: 0.6.7
2021/06/04 22:57:09 Edition: linux
2021/06/04 22:57:09 Build Number: 836453774
2021/06/04 22:57:09 Build Date: Wed May 12 18:22:51 UTC 2021
2021/06/04 22:57:09 Build Hash: 8a29fff01e57a623e1a39be22096e4a860280026
2021/06/04 22:57:09 readConfigFile
2021/06/04 22:57:09 {ServerRoot:http://localhost:8000 Port:8000 DBType:sqlite3 DBConfigString:./focalboard.db DBTablePrefix: UseSSL:false SecureCookie:false WebPath:./pack FilesPath:./files Telemetry:true WebhookUpdate:[] Secret:hidden SessionExpireTime:2592000 SessionRefreshTime:18000 LocalOnly:false EnableLocalMode:true LocalModeSocketLocation:/var/tmp/focalboard_local.socket AuthMode:native MattermostURL: MattermostClientID:hidden MattermostClientSecret:hidden}
2021/06/04 22:57:09 connectDatabase sqlite3 ./focalboard.db
{"level":"info","ts":1622847429.8915217,"caller":"server/server.go:186","msg":"Server.Start"}
2021/06/04 22:57:09 http server started on :8000
2021/06/04 22:57:09 Unable to unlink socket.no such file or directory
2021/06/04 22:57:09 server.Start ERROR: no such file or directory
```

**Comment by penguin321** [comment]
I got the exact same Problem on my end.

**Comment by flo-eberle** [comment]
i have the same issue as well.
i'm currently testing on a virtual machine running ubuntu 21.04.

focalboard.service is not running:
`systemctl status focalboard.service `
```bash
● focalboard.service - Focalboard server
     Loaded: loaded (/lib/systemd/system/focalboard.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Thu 2021-06-10 12:14:00 UTC; 2s ago
    Process: 2097 ExecStart=/opt/focalboard/bin/focalboard-server (code=exited, status=1/FAILURE)
   Main PID: 2097 (code=exited, status=1/FAILURE)

Jun 10 12:14:00 focalboard systemd[1]: focalboard.service: Main process exited, code=exited, status=1/FAILURE
Jun 10 12:14:00 focalboard systemd[1]: focalboard.service: Failed with result 'exit-code'.
```

when i try to run the focalboard server manually:
```/opt/focalboard$ ./bin/focalboard-server```
```bash
2021/06/10 12:11:10 Focalboard Server
2021/06/10 12:11:10 Version: 0.6.7
2021/06/10 12:11:10 Edition: linux
2021/06/10 12:11:10 Build Number: 836453774
2021/06/10 12:11:10 Build Date: Wed May 12 18:22:51 UTC 2021
2021/06/10 12:11:10 Build Hash: 8a29fff01e57a623e1a39be22096e4a860280026
2021/06/10 12:11:10 readConfigFile
2021/06/10 12:11:10 {ServerRoot:http://localhost:8000 Port:8000 DBType:postgres DBConfigString:postgres://user:password@localhost/boards?sslmode=disable&connect_timeout=10 DBTablePrefix: UseSSL:false SecureCookie:false WebPath:./pack FilesPath:./files Telemetry:true WebhookUpdate:[] Secret:hidden SessionExpireTime:2592000 SessionRefreshTime:18000 LocalOnly:false EnableLocalMode:true LocalModeSocketLocation:/var/tmp/focalboard_local.socket AuthMode:native MattermostURL: MattermostClientID:hidden MattermostClientSecret:hidden}
2021/06/10 12:11:10 connectDatabase postgres postgres://user:password@localhost/boards?sslmode=disable&connect_timeout=10
{"level":"info","ts":1623327070.086109,"caller":"server/server.go:186","msg":"Server.Start"}
2021/06/10 12:11:10 http server started on :8000
2021/06/10 12:11:10 Unable to unlink socket.no such file or directory
2021/06/10 12:11:10 server.Start ERROR: no such file or directory
```

**Comment by numphileo** [comment]
I found a solution to this problem. 

The problem arises as there is no sock file in /var/tmp. So this is what I did. 

`cd /var/tmp`
And then - created a file by using following command
`touch focalboard_local.socket`
And finally, restarted nginx - by using following command
`sudo systemctl restart nginx`
Reload the page - and it worked!

**Comment by penguin321** [comment]
> 
> 
> I found a solution to this problem.
> 
> The problem arises as there is no sock file in /var/tmp. So this is what I did.
> 
> `cd /var/tmp`
> And then - created a file by using following command
> `touch focalboard_local.socket`
> And finally, restarted nginx - by using following command
> `sudo systemctl restart nginx`
> Reload the page - and it worked!

Worked for me too !

**Comment by seungjaeryanlee** [comment]
Thank you @numphileo for the solution! It worked for me as well. Closing the issue.

To Focalboard devs (@chenilim): I think this solution might be worth mentioning in the official guide?

**Comment by chenilim** [comment]
Thank you @seungjaeryanlee! @justinegeffen, adding the documentation tag - might issues like this be good for a KB article or troubleshooting section?

**Comment by justinegeffen** [comment]
Thanks, @chenilim! Yep, this would be great for Troubleshooting. Thanks for the heads-up! :)

**Comment by nkimran94** [comment]
> cd /var/tmp

can't find this directory "cd /var/tmp"

**Comment by nkimran94** [comment]
> ./bin/focalboard-server
running this command i get this error:

[2022-01-19 15:11:52.674 +06:00] FocalBoard Server                        caller="mlog/mlog.go:218" version=0.9.2 edition=linux build_number=1320942631 build_date="Fri Oct  8 15:36:12 UTC 2021" build_hash=c632409feb1c6ea66851f99db8e0f92472b953fc
error [2022-01-19 15:11:52.677 +06:00] Database Ping failed                     caller="mlog/mlog.go:228" error="pq: password authentication failed for user "boardsuser""
fatal [2022-01-19 15:11:52.677 +06:00] server.NewStore ERROR                    caller="mlog/mlog.go:234" error="pq: password authentication failed for user "boardsuser""
  github.com/mattermost/focalboard/server/services/mlog.(*Logger).Fatal
      /home/runner/work/focalboard/focalboard/server/services/mlog/mlog.go"234
  main.main
      /home/runner/work/focalboard/focalboard/server/main/main.go"165
