### ISSUE TITLE
Bug: Drag & Drop of a card onto another card in the same status clears the status to "Empty"

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#523]
Submitted on behalf of contributor `jprusch`

**Summary:**
Drag & Drop of a card onto another card in the same status clears the status to "Empty" (see screen grab)

**Steps to reproduce the behavior:**

https://user-images.githubusercontent.com/13020833/120787195-62ffd400-c52f-11eb-8eab-55203443c9f3.mp4

**Expected behavior:**
Status is not cleared (made "empty") and original status of the card is retained.

**Platform:**
 - OS and version: Windows 10  20H2 Build 19042.985

**Comment by chenilim** [comment]
Thanks @lindy65! I'm not able to repro this (tried v0.6.7 web, win, and mac app). Could we get an [export](https://www.focalboard.com/guide/user/#archives) of that board's archive? Thanks.

**Comment by chenilim** [comment]
Nevermind @lindy65! This appears to be a dup of #493, which does repro for me.

**Comment by jespino** [comment]
This is not longer happening in main branch.
