### ISSUE TITLE
Feature Idea: Have a unique link / URL for each card, that I can copy & paste somewhere else

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#526]
Submitted on behalf of contributor `jprusch`

**Summary:**
Have a unique link / URL for each card, that I can copy & paste somewhere else (Hint: Mattermost channel).

**How important this is to me and why:**
Importance: Medium
It would make it easy to get approved/authenticated users directly on a card, when they click on the URL.

**Additional context / similar features:**
Mattermost channels

**Comment by chenilim** [comment]
Thanks @lindy65 and jprusch! This currently works, though it isn't obvious:
* When viewing a card, select and copy the URL from the browser
* The URL is updated as the active view or card changes, and opens the visible view or card

What we can do to improve this is add a "copy link" option to the card menu, which should simply copy the current URL.

**Comment by dineshkumar12004** [comment]
can i work on this issue, if it's still not fixed.

**Comment by chenilim** [comment]
Thanks @dineshkumar12004! You got it!

I think there are 3 changes needed:
* Add a "copy link" option to the card menu, which should simply copy the current URL
* Add a "copy link" option to the card menu off the **board view**, which should simply copy the current URL
* Add a "copy link" option to the card menu off the **gallery view**, which should simply copy the current URL

LMK if you have any questions. Thanks!

**Comment by dineshkumar12004** [comment]
Thank you for assigning me. I'm still figuring out, I will give my best shot :)

**Comment by chmac** [comment]
How does this work in the desktop version of the app where there is no URL bar?

**Comment by hahmadia** [comment]
@ogi-m merged to main and ready for testing
