### ISSUE TITLE
Feature Idea: Consider having blank board templates

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#531]
Submitted on behalf of contributor `ewwollesen` 

**Summary:**
Consider having blank board templates.

**How important this is to me and why:**
Importance: Medium

I liked that there are templates for potentially commonly used features like "Personal goals" etc. I didn't like that they were pre-populated with items because then I had to do a bunch of work to delete/edit everything. Maybe a preview image you could dismiss would be better, or the ability to turn that feature on/off.

**Comment by chenilim** [comment]
Thanks @lindy65 and `ewwollesen`. There currently is an "Empty Board" option when clicking on "+ Add Board".

<img width="266" alt="Empty board option" src="https://user-images.githubusercontent.com/46905241/122622161-accadd00-d04c-11eb-971c-d4d8e1ede9a5.png">

Please reopen if this doesn't work as intended.
