### ISSUE TITLE
Bug: Space missing between "Show/hide Description" on a Board

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#535]
Submitted on behalf of contributor `jgilliam17`

**Summary:**
Space missing between "Show/hide Description" on a Board

**Steps to reproduce the behavior:**
1. Open a board
2. Hover over the area top left above the board name
3. Observed: space missing between icon and wording (show/hide description) - see screenshot

**Expected behavior:**
A space between icon and "show/hide description"

**Screenshots:**
![image](https://user-images.githubusercontent.com/13020833/120990181-91c0b900-c780-11eb-9d79-fe6c3fc0e6a8.png)

**Platform:**
 - Browser and version: Safari 14
 - OS and version: macOS

**Comment by chenilim** [comment]
Thanks @lindy65 and `jgilliam17`! Looks like a regression. Hopefully a really easy CSS fix - seems to be some padding / margin missing. Opening this up to any takers. cc @sbishel.

**Comment by dineshkumar12004** [comment]
I couldn't see that show description in Board view ? How to reproduce this issue ? I'm using ubuntu 20.04

**Comment by lindy65** [comment]
Hi @dineshkumar12004 - If you hover above the board name, you will see a "Show/Hide Description" appear

**Comment by dineshkumar12004** [comment]
Got it now I can see 👍
