### ISSUE TITLE
Bug: Sidebar 3-dot menu for a board disappears when you move your mouse away and reappears when you mouse over the area again

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#538]
Submitted on behalf of contributor `jgilliam17`

**Summary:**
Sidebar 3-dot menu for a board disappears when you move your mouse away and reappears when you mouse over the area again.

**Steps to reproduce the behavior:**
1. Click the 3-dots to the right of a board in the sidebar
2. Move your mouse away from the sidebar
3. Observed: menu disappears
4. Move your mouse back to the board in the sidebar
5. Observerd: menu reappears

https://user-images.githubusercontent.com/13020833/121055972-06feaf00-c7be-11eb-9b50-5eb510b229b0.mov

**Expected behavior:**
Menu remains visible until you click the 3-dots again

**Platform:**
 - Browser and version: Safari 13
 - OS and version: macOS

**Comment by chenilim** [comment]
Thanks @lindy65 and `jgilliam17`! This looks like a possible CSS issue. The other menus do not disappear when the cursor moves away. Opening it up for any takers. Thanks!

cc @sbishel.

**Comment by kamre** [comment]
@chenilim looks like there are redundant rules for `.MenuWrapper` inside `sidebarBoardItem.scss`: [1](https://github.com/mattermost/focalboard/blob/main/webapp/src/components/sidebar/sidebarBoardItem.scss#L14-L16) and [2](https://github.com/mattermost/focalboard/blob/main/webapp/src/components/sidebar/sidebarBoardItem.scss#L57-L59). Removing them seems to fix this issue.

**Comment by chenilim** [comment]
Thanks @kamre! Would you (or anyone else) like to submit a PR?
