### ISSUE TITLE
Bug: Column Headers no longer scroll horizonally

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#541]
**Summary:**
Column headers have been frozen for vertical scroll.  However, they also don't scroll with columns when scrolling horizontally.

**Steps to reproduce the behavior:**
1. Go to Table View with columns wider than screen
2. Scroll horizontally
3. See column headers do not scroll with column data.

**Expected behavior:**
Column headers should scroll horizontally with column data.

**Screenshots:**

https://user-images.githubusercontent.com/12704875/121084436-e0308080-c79d-11eb-83b7-e1bc8d3b42c0.mp4

**Platform:**
 - Browser and version: Chrome 91.0.4472.77
 - OS and version: macOS 11.4

**Comment by harshilsharma63** [comment]
This has been fixed now.
