### ISSUE TITLE
Doc: Explain how to change order of "Group By" categories

### ISSUE THREAD

**Issue by it33** [mattermost/focalboard#549]
**Summary**
It's unclear how "Group By" columns in the Kanban view can be re-ordered. Propose docs are updated to explain how this works 

**Link to documentation page If applicable**
https://www.focalboard.com/guide/user/#renaming-boards

**(Optional) Additional context and/or screenshot:**
![image](https://user-images.githubusercontent.com/177788/121271482-a08a9700-c878-11eb-9df7-797534ce806e.png)
**Summary:**

**Comment by chenilim** [comment]
Thanks @it33, and also for creating the new [Documentation request template](https://github.com/mattermost/focalboard/issues/new?assignees=&labels=documentation&template=doc_improvement.md&title=Doc%3A+)!

FYI @justinegeffen - LMK how you would like to manage these. We can use the `documentation` label, and / or please assign these to yourself when you get to them.

The code for the [focalboard.com user's guide](https://www.focalboard.com/guide/user/) is [here](https://github.com/mattermost/focalboard/blob/main/website/site/content/guide/user/_index.md). Right now, updates are manual (done by me, on demand), but we can improve this. We can also decide how we want to manage the process for updating the docs on focalboard.com along with docs.mattermost.com over time.

**Comment by justinegeffen** [comment]
This is addressed in the latest doc updates (WIP), thank you! :)
