### ISSUE TITLE
Feature Idea: Different date formats

### ISSUE THREAD

**Issue by Talismanian** [mattermost/focalboard#550]
**Summary:**

Ability to change how dates are displayed. The default MM/DD/YYYY format is extremely confusing for anyone outside of North America who isn't expecting it.

Alternative options an include YYYY-MM-DD or DD/MM/YYYY and could be tied with language/localisation settings.

**How important this is to me and why:**

Importance: Medium

Use cases:
1. Avoid confusion over dates involving low month numbers (e.g. 6/9/2021).
2. Better cater to users outside of North America.
3. Adoption of unambiguous date formats that are readily understood across regions.

**Additional context / similar features:**

A number of other web-based apps provide the option to change date formats. They're often tied to user settings and may not be the default.

**Comment by chenilim** [comment]
Thanks @Talismanian! I've created a [card to track this](https://focalboard-community.octo.mattermost.com/workspace/qgsck6cts3fwpqwyjiupjm5cde/shared?id=47aa9bb4-6967-4a96-83c7-11bd6b20f1eb&v=ca1a5441-4c1c-4d0e-856e-88cc744576c8&r=762db9c6-305c-4d13-8ce6-9f11e5232c24&c=1b73e464-84cd-4d14-823f-a41a80c38ff7). Agree that we should at least support a MM/DD/YYYY or DD/MM/YYYY display format.

cc @sbishel, @michaelgamble.

**Comment by darkLord19** [comment]
@chenilim can i work on this?

**Comment by chenilim** [comment]
Thanks @darkLord19, you got it! Here's the basic spec:
1. Add an additional user setting to toggle the date format
  * For now, only support "M/D/YYYY" or "D/M/YYYY"
  * We can expand this in the future to support other custom formats
2. Store this preferred date format in the localStorage settings
3. When reading the format, if it is missing or invalid, default to the current behavior of "M/D/YYYY"
4. Also add this new setting to the user settings to persist in the native apps
  * See #376 for reference

That should do it for a first cut. LMK if you have any questions. Thanks!

**Comment by chenilim** [comment]
Just a heads up that we are taking a closer look at this in #715, and the [updated design proposal](https://github.com/mattermost/focalboard/issues/715#issuecomment-881922287) is to use MMMM DD, YYYY (e.g. June 09, 2021) as the default display, while keeping MM/DD/YYYY or DD/MM/YYYY (based on the user setting) as the edit-time format. Overall, I think this is a better default as it is unambiguous internationally, but please chime in there if you have any additional thoughts or feedback. Thanks!
