### ISSUE TITLE
Doc: Explain how to define "Select" properties options

### ISSUE THREAD

**Issue by nmatton** [mattermost/focalboard#551]
**Summary:**
It is unclear to me how to update the list of available options in a select property

**(Optional) Additional context and/or screenshot:**
For example, when creating a new category of type "Select", I am unable to edit the options nor find a way to do so.
It is the same for default existing created property (like priority, etc.)

![image](https://user-images.githubusercontent.com/6585327/121318747-d3319f80-c90b-11eb-9999-435d5d979088.png)

Maybe it is still a feature to be developped ?
Thanks !

**Comment by chenilim** [comment]
Thanks @nmatton! The steps should be:
* From the Card Editor
* Add a new property, give it a name, and set its type to "Select" (or Multi-Select)
* Click on the value, and start typing the name of a new option. Press Enter to accept

<img width="288" alt="Add option" src="https://user-images.githubusercontent.com/46905241/122604055-2f8e7080-d02a-11eb-973a-bb27685a1c0e.png">

Please LMK if these steps don't work for you.

Alternatively, you can also add new options from a board:
* Open a board view
* Group by a Select property
* Click on "+ Add a group"

This will add a new column, which corresponds to a new value option for the Select prroperty.

cc @justinegeffen.

**Comment by nmatton** [comment]
Great ! Thanks for this explanation ! That worked for me, but not was trivial without knowing the how to :) 👍

**Comment by xuoguoto** [comment]
To add to this discussion:

Also missing is how to order each value in a select list. For example if I add a new status, say TESTING, it goes after completed. Couldn't figure out how to move it after in progress.

**Comment by justinegeffen** [comment]
Completed and available here: https://docs.mattermost.com/boards/work-with-cards.html#define-a-select-or-multi-select-property
