### ISSUE TITLE
Bug: Right-margin breaks when indented bullet-item under a numbered-list item

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#558]
**Steps to reproduce the behavior:**
1. Crate or open a card
2. Paste the following as the description:
```
1. This is a bullet-list item under a numbered list item, indented with two tabs:
		- Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla libero lorem, fringilla tristique pellentesque in, laoreet ut lorem. Mauris aliquam magna quis rhoncus suscipit. Sed id erat luctus nunc dictum vulputate. Maecenas velit erat, ultricies in mattis in, molestie eu leo. Donec metus sem, rutrum et condimentum vitae, fringilla sit amet massa. Aenean non tortor id leo sagittis eleifend. Proin luctus luctus leo, at luctus eros vestibulum at. Ut tempus faucibus ipsum eget vestibulum.

Notice how it breaks the right-side margin / clipping.
```
3. Save
4. Notice that the item doesn't wrap and goes past the right margin.

<img width="1003" alt="Indentation bug" src="https://user-images.githubusercontent.com/46905241/121606646-65689f00-ca03-11eb-9676-11d5b08cf224.png">

**Expected behavior:**
The bullet-item wraps within the margin.

**Screenshots:**

**Platform:**
 - Chrome 91, v0.7.0 RC1 Mac app, and v0.6.7 web app
 - MacOS 10.15.7

**Additional context:**
This only happens with that specific (two or more tabs) indentation.
Check if this is an existing / know issue with SimpleMDE / CodeMirror.

**Comment by AbdelilahRami** [comment]
I will work on this issue

**Comment by chenilim** [comment]
Thanks @AbdelilahRami, you got it!

**Comment by sbishel** [comment]
closing, as retest appears fix, please reopen if you still see an issue
