### ISSUE TITLE
Bug: Person property shows "no options"

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#559]
**Steps to reproduce the behavior:**
1. Install or upgrade to [Mattermost v5.36 RC1](https://community.mattermost.com/core/channels/release-discussion/3w7q4fac7i8fmqdjscf93mn5rr) or later
2. Enable [custom plugins](https://docs.mattermost.com/administration/plugins.html#custom-plugins) for the server
3. Download the focalboard plugin for [0.7.0 RC1](https://github.com/mattermost/focalboard/releases/tag/v0.7.0-rc1)
4. Upload and enable it
5. Open Focalboard, create a board, and a card
6. Create a person property on the card
7. Click on the value to set it
8. "No options" is shown

**Expected behavior:**
A list of available users on the Mattermost server is shown, allowing me to pick one.

**Screenshots:**
<img width="285" alt="Person no options" src="https://user-images.githubusercontent.com/46905241/121609006-d4e08d80-ca07-11eb-8c24-7d1e7990d078.png">

**Platform:**
 - Chrome 91, macOS 10.15.7
 - Mattermost v5.36 RC1, Focalboard plugin v0.7.0 RC1

**Comment by jespino** [comment]
It should be fixed in the #564

**Comment by harshilsharma63** [comment]
Fixed with #564
