### ISSUE TITLE
Bug: Cards should be sorted alphabetically when sorting by select/multi select property

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#562]
**Summary:**
Cards should be sorted alphabetically when sorting by select/multi select property

**Steps to reproduce the behavior:**
1. Open any board.
2. Add a select property to card and populate it's value for some cards.
3. Sort the board by the sleect/multi select property just created.

**Expected behavior:**
Cards should be sorted based on alphabetical order of select/multi-select property value.

**Observed behavior:**
Cards are sortred based on the insertion order of select/mult-select property options.

**Screenshots:**
![sorting-icons](https://user-images.githubusercontent.com/18575143/121636679-e5dfdc00-caa5-11eb-8b42-f93792b3ea70.gif)

**Platform:**
 - Browser and version: Browser independent
 - OS and version: Platform independent

**Additional context:**
The issue is at this line - https://github.com/mattermost/focalboard/blob/bc36e253a028df5cf9bfdd2cb0bba39d546eff5b/webapp/src/viewModel/boardTree.ts#L396

There we need to decide order based on value rather than the index.

**Comment by Shahzayb** [comment]
> Cards should be sorted based on alphabetical order of select/multi-select property value.

It's working as expected.

https://github.com/mattermost/focalboard/blob/6bbbecf3663bea83255ac66332ec5615aa7d637b/webapp/src/viewModel/boardTree.ts#L436-L441

**Comment by jespino** [comment]
Great @Shahzayb thanks for the heads up. Closing this issue.
