### ISSUE TITLE
Bug: Sidebar icon disappears when minimized.

### ISSUE THREAD

**Issue by haardikdharma10** [mattermost/focalboard#567]
**Summary:**
The sidebar icon disappears when the sidebar is minimized.

**Steps to reproduce the behavior:**
Refer to the video below.

**Expected behavior:**
Sidebar icon should appear so that the user can open the sidebar as many times he/she wants to.

**Screenshots:**

https://user-images.githubusercontent.com/53044263/121750036-3cdac500-cb29-11eb-8770-0d827aef0f3f.mov

**Platform:**
 - Browser and version: Chrome
 - OS and version:  macOS 11.2.3

**Comment by haardikdharma10** [comment]
Update: I have updated my Mac desktop app to v0.7.0 and this is now on the desktop app!

/cc @chenilim, @jespino

**Comment by chenilim** [comment]
Thanks @haardikdharma10! @harshilsharma63 or @hahmadia, can you help investigate? It's a regression, and likely due to css or html hierarchy changes. cc @sbishel.
