### ISSUE TITLE
Where to report Security Vulnerabilities? 

### ISSUE THREAD

**Issue by jagdishbharucha** [mattermost/focalboard#57]
**Summary:**
I need to report a security vulnerability. Where can I do that?

**Comment by chenilim** [comment]
Hi, thanks for reaching out. For now, please [DM me in Mattermost here](https://community.mattermost.com/core/messages/@chen-i.lim), or email me at chen [at] mattermost.com. Thanks!

**Comment by it33** [comment]
@jagdishbharucha thanks for the question! @chenilim FYI, proposing a Responsible Disclosure Policy is added? https://github.com/mattermost/focalboard/pull/59

**Comment by it33** [comment]
Closing now that we have an RDP in place,
