### ISSUE TITLE
Feature Idea: Role-Based Permissions

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#584]
### Summary:
P1: Allow Admins to assign **Roles** to **Users** per **Board** (and other **Artifacts**)
P1: Roles have fixed **Rights** (draft mapping below), that are enforced at the API-level
P2: Assign Roles to **Groups** (e.g. group of users, members of a team? Members of a channel?)

### DRAFT Roles and their Rights:

| Role / Rights | Admin | Editor | Commenter | Viewer |
| --- | --- | --- | --- | --- |
| Modify permissions | X | | | |
| Share board | X | | | |
| Delete board | X | | | |
| Rename board | X | X | | |
| Add, edit, and delete views | X | X | | |
| Add, edit, and delete cards | X | X | | |
| Comment | X | X | X | |
| View | X | X | X | X |

**Additional context / similar features:**
Other comparable systems (e.g. Notion, Trello, Asana, Google Docs) have a similar Role system.

Comments and feedback welcome! Would you like to see anything different or extra in a permission system?

**Comment by lonix1** [comment]
*Long-term this is the way to go!*

But from experience, this is not a trivial feature, and could get out of hand very quickly - so it would take forever to develop.

I assume "P1" / "P2" means "phases"? I agree that is the best way to keep to the focalboard philosophy and "keep it simple"

phase 1
- add concept of "admin" and "non-admin" users; admin user is first to register with app
- admin user can grant/revoke board access to other users
- more secure than current anyone-with-a-magic-link-can-use-system approach
- keep current "sharing" feature for those who want it, but add a config option to disable it

phase 2
- add sophisticated RBAC as per table above

**Comment by biva** [comment]
Hello, Congrats for your work, and sorry to ask if it has been updated somewhere, but were you able to make progress here? One of our user has deleted a board accidentally, and we lost it.

Would it be possible, as a first step, to make the board deletion only possible for admins?

**Comment by chenilim** [comment]
@biva, sorry for the delayed response, but short answer is yes! The upcoming permissions system will restrict board deletion to admins. Please see [this note](https://github.com/mattermost/focalboard/discussions/2436) for more details. Closing this issue as the feature has been merged to main, and is planned for an upcoming release. Thanks everyone for your input! Feel free to continue the discussion in the linked note, or file new issues and enhancement requests.
