### ISSUE TITLE
Bug: server not bind to any port (mattermost-plugin)

### ISSUE THREAD

**Issue by serge-kilimoff** [mattermost/focalboard#592]
Hello,

I have a port problem on the mattermost plugin for focalbord. The error message is as follows when I click on focalboard icon :

```
2021-06-18T10:41:39.832+0200 info go-plugin@v1.4.0/stream.go:15 {"level":"info","ts":1624005699.8301227,"caller":"server/server.go:206","msg":"Server.Start"} {"plugin_id": "focalboard", "source": "plugin_stderr"}
2021-06-18T10:41:39.833+0200 info go-plugin@v1.4.0/stream.go:15 2021/06/18 10:41:39 server not bind to any port {"plugin_id": "focalboard", "source": "plugin_stderr"}
2021-06-18T10:41:43.121+0200 info go-plugin@v1.4.0/stream.go:15 2021/06/18 10:41:43 Unable to serve the index.html fil, err: open plugins/focalboard/pack/index.html: no such file or directory {"plugin_id": "focalboard", "source": "plugin_stderr"}
```

This file exists on my disk (in `/opt/plugins/focalboard/pack/index.html`.  I have a custom entry for `PluginSettings.Directory` in my config.json.

I'm trying to set a port number in mattermost's config.json, in the PluginSettings entry, like other plugins, but it doesn't seem to do anything.
Nginx has been configured as indicated on your documentation.

**Comment by chenilim** [comment]
Thanks @serge-kilimoff! #593 was also recently filed - is your Mattermost installation off a subdir by any chance? It might be the same issue. FYI @jespino, @mgdelacroix.

**Comment by jespino** [comment]
When we run this in the plugin we are not binding it to any port, that is ok, the `PluginSettings.Directory` can be the problem (I don't think is related to subdirectory problem). @mgdelacroix do you want to pick this one?

**Comment by jespino** [comment]
Depending on the decision made around embedding the whole webapp in the plugin it can be fixed as part of that effort.

**Comment by serge-kilimoff** [comment]
> Thanks @serge-kilimoff! #593 was also recently filed - is your Mattermost installation off a subdir by any chance? It might be the same issue. FYI @jespino, @mgdelacroix.

No, sorry, my Mattermost installation is at the root of my domain.

**Comment by chenilim** [comment]
Thanks @serge-kilimoff. @jespino could you help investigate this? From the error message, `server not bind to any port`, one quick thought is maybe the default port (8000) is in use by another service? This should be configurable in Focalboard's `config.json`, though I'm not exactly sure if / how this works when run as a plugin.

**Comment by serge-kilimoff** [comment]
![image](https://user-images.githubusercontent.com/6053927/122632479-5785de80-d0d3-11eb-8712-57014185d757.png)

I confirm that port 8000 is not used.

**Comment by richilp** [comment]
Same problem here.
I can confirm too that Mattermost is on root and port 8000 is not in use.

**Comment by mgdelacroix** [comment]
@jespino @chenilim I'll take a look

**Comment by richilp** [comment]
Thanks for the fix 👏 
Should we just remove the pluging and donwload it again?

**Comment by jespino** [comment]
@richilp this is only applied on the main branch now, you should need to wait until the next release of the plugin or compile the plugin by yourself using the main branch (that means certain extra inestability).

Other option is to get the last stable version branch, apply the patch, and compile from there.

**Comment by richilp** [comment]
Gracias Jesús ;)
