### ISSUE TITLE
Bug: the plugin is not aware of a subdir installation (mattermost plugin)

### ISSUE THREAD

**Issue by florencebiree** [mattermost/focalboard#593]
**Summary:**
When mattermost is installed on a subdir in the webserver (say https://server/mattermost/ ), the focalboard button doesn't work, and send the user to https://server/plugins/focalboard/workspace/[...] instead of https://server/mattermost/plugins/focalboard/workspace/[...]

**Steps to reproduce the behavior:**
1. Go to mattermost
2. Click on the focalboard button
3. You are redirected to the wrong /plugin/focalboard url instead of /mattermost/plugin/focalboard

**Expected behavior:**
Add the mattermost root url in the focalbaord url

**Platform:**
 - Browser and version: Firefox 88.0.1
 - OS and version: Debian unstable

**Comment by chenilim** [comment]
@jespino or @mgdelacroix, could you investigate please?
cc @sbishel.

**Comment by jespino** [comment]
Yes, we should take that into consideration. Shouldn't be a hard problem.

**Comment by chenilim** [comment]
Thanks @jespino. Assigning this to you for now. Please reassign as necessary. Also check if #592 is a dup of this.

**Comment by jespino** [comment]
This is working fine for me.

**Comment by chenilim** [comment]
Thanks @jespino. To clarify, do you think this is fixed because of #609? If so, this will be fixed in 0.8.0.

**Comment by jespino** [comment]
@chenilim I don't think is necesarily related, that is about the filesystem directory and this more about the application url.

**Comment by jespino** [comment]
This is already fixed.
