### ISSUE TITLE
Bug: Loading a table is very slow

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#601]
**Steps to reproduce the behavior:**
1. Open a large table view in v0.7.0 or later
  a. E.g. use an export of [the v1 Focalboard table](https://focalboard-community.octo.mattermost.com/workspace/qgsck6cts3fwpqwyjiupjm5cde?id=47aa9bb4-6967-4a96-83c7-11bd6b20f1eb&v=ca1a5441-4c1c-4d0e-856e-88cc744576c8)
2. Notice that it takes several seconds to load

**Expected behavior:**
The table view should load quickly (under a second at the most).

**Platform:**
 - v0.7.0 macOS app on 10.15.7

**Additional context:**
The same table view loads within a second in v0.6.7.

**Comment by chenilim** [comment]
@jespino, I think you mentioned you were already looking into table performance issues? Is this on your list already? I believe it's a regression.

cc @sbishel.

**Comment by jespino** [comment]
Yes, whenever you have a bunch of things on the table it start to go slow because the rendering of the react-select items, we need to differenciate when you are editting or viewing and only show the react-select on editting.

**Comment by chenilim** [comment]
Thanks @jespino. Assigning this to you to track. Is the PR #607 related to this? Are there other changes in the pipeline? Thanks.

Please cherry-pick the relevant perf fixes to the release-0.7.0 branch, then close this issue when complete. We want to cut a 0.7.1 build with this fix for the Mattermost v5.37 release. FYI @sbishel, @mgdelacroix.

**Comment by jespino** [comment]
I think we can close this for now, but in the future I think we need to rethink the table view entirely and make it more "Spreadsheet" code, than just throwing rows there.

**Comment by jespino** [comment]
@chenilim I cherry-picked this late, so It is going to go in 0.7.2, if we release that.
