### ISSUE TITLE
Bug: Links in Card properties (like PR/Commit URL/GitHub Issue) should be clickable.

### ISSUE THREAD

**Issue by haardikdharma10** [mattermost/focalboard#602]
**Summary:**
Links such as **PR/Commit URL/GitHub Issue** in a card should be clickable.

**Expected behavior:**
Links should be clickable so that they redirect to the desired webpage.

**Screenshots:**

<img width="982" alt="Screenshot 2021-06-19 at 1 39 56 AM" src="https://user-images.githubusercontent.com/53044263/122611881-b9c4ec00-d09f-11eb-9d58-7a4a6fc33453.png">

**Platform:**
 - Browser and version: Platform independent.
 - OS and version: OS independent.

**Additional context:**
Links in **Card description** are indeed clickable. Maybe apply the same logic here?

**Comment by chenilim** [comment]
Thanks @haardikdharma10! This should be fixed in [v0.7.0](https://github.com/mattermost/focalboard/releases/tag/v0.7.0), where there is a link button that appears next to the URL property. Please re-open if this does not work for you. Thanks.
