### ISSUE TITLE
Feature Idea: Don't close dropdown on click or toggling switches

### ISSUE THREAD

**Issue by fmiqbal** [mattermost/focalboard#606]
**Summary:**
When clicking the `properties` or column inside `filter`, the dropdown should be able to multi select values without opening up again

**How important this is to me and why:**

Importance: Low
Just some quality of life improvement

Use cases:
1. Create new view on the existing board
2. I need to adjust what properties need to be shown, eg I have (`status`, `project`, `due_date`, `type`) I need `status` and `type`
3. Open `properties` , dropdown for all properties, click `project`, click `type`. Done
4. (currently, I open `properties` click `project`, open `properties` again, click `type`, repeat)
![image](https://user-images.githubusercontent.com/8409391/122662722-5cc05780-d1bf-11eb-955a-393c9c379ddd.png)

**Additional context / similar features:**
Trello when adding labels
![image](https://user-images.githubusercontent.com/8409391/122662699-3995a800-d1bf-11eb-86f9-30c9a9978b37.png)

**Comment by kamre** [comment]
@chenilim @wuwinson I suppose this was already fixed.

**Comment by wuwinson** [comment]
Good catch, thanks @kamre! Closing out.
