### ISSUE TITLE
Bug: Invite Users code link is broken

### ISSUE THREAD

**Issue by kevinen98** [mattermost/focalboard#613]
**Summary:**
The link to share with other people so that they can register adds one to many '/' after the top-domain part and with that the link is broken.

**Steps to reproduce the behavior:**
1. Click on Focalboard menu
2. Click on Invite Users
3. Right click and copy link.
4. Open the link while not logged in.

**Expected behavior:**
When opening the link you should be taken to the register page and be able to register

**Screenshots:**
This is how it looks like right now:
`https://example.com//register?t=<code>`

How it should look like:
`https://example.com/register?t=<code>`

**Platform:**
 - Browser and version: Firefox Daylight 34.0 (IOS)
 - Server OS and version: Debian 10.10

**Comment by chenilim** [comment]
Thanks @kevinen98! This is a bug, but does your browser automatically strip out the extra '/'? It appears that Chrome (91), FireFox, and Safari do this on macOS. Still, we should fix this. Opening it up for grabs. Should be an easy fix.

**Comment by kevinen98** [comment]
> This is a bug, but does your browser automatically strip out the extra '/'?

No, both firefox for ios and linux do not automatically strip out the extra '/'. I get redirected to login page.

**Comment by chenilim** [comment]
Thanks @kevinen98! Let's raise the priority on this then. @sbishel, could someone on your team take a quick look at this? Should be an easy fix. Though there may be other similar instances of '//'.
