### ISSUE TITLE
Bug: Mattermost SqlSetting.MaxOpenConns is not respected

### ISSUE THREAD

**Issue by Vorlif** [mattermost/focalboard#616]
**Summary:**
We have a Mattermost instance with few users and the Focalboard plugin running. We use PostgreSQL as database and allow a maximum of 100 connections. Since we still use other applications, the number of connections for Mattermost is limited to 50. Unfortunately, Mattermost does not respect this limit and often uses all connections. This results in other applications not being able to connect to the database. 

If I understand the program code correctly, Focalboard establishes its own connection to the database. I therefore think that this is where the problem arises. 

**Steps to reproduce the behavior:**
1. Install Mattermost with Focalboard Plugin
2. Set the number of database connections to a low value
3. Wait a few hours

**Expected behavior:**
The Mattermost plugin respects the limit set in the Mattermost configuration

**Platform:**
 - Mattermost-Version: 5.36.0
 - Focalboard (focalboard - 0.7.0)
 - PostgreSQL 13
 - Server: Debian GNU/Linux 10 (buster)

**Additional context:**

```sql
select count(*) from pg_stat_activity where usename = 'mattermost';

95

select query, state from pg_catalog.pg_stat_activity where usename = 'mattermost'
```

```
query                                                                               |state|
------------------------------------------------------------------------------------+-----+
SELECT COUNT(*) AS count FROM focalboard_workspaces                                 |idle |
SELECT COUNT(*) AS count FROM focalboard_workspaces                                 |idle |
SELECT COUNT(*) AS count FROM focalboard_workspaces                                 |idle |
SELECT COUNT(*) AS count FROM focalboard_workspaces                                 |idle |
SELECT COUNT(*) AS count FROM focalboard_workspaces                                 |idle |
SELECT COUNT(*) AS count FROM focalboard_workspaces                                 |idle |
SELECT COUNT(*) AS count FROM focalboard_workspaces                                 |idle |
...
```

**Comment by chenilim** [comment]
Thanks @Vorlif! Is this something you can help investigate @jespino? Or redirect as needed? Thanks. cc @sbishel.

**Comment by chenilim** [comment]
Updating with the [current plan of record](https://community.mattermost.com/core/pl/h3c45szb7p8ttm5d1mrkkirwao):

Add the following settings and defaults to `config.json`:
* MaxOpenConns: 300
* MaxIdleConns: 20
* ConnMaxLifetimeMilliseconds: 3600000 (60 minutes)
* ConnMaxIdleTimeMilliseconds: 300000 (5 minutes)

Then set them as the db settings when initializing the store, e.g.:
```
db.SetMaxIdleConns(*settings.MaxIdleConns)
db.SetMaxOpenConns(*settings.MaxOpenConns)
db.SetConnMaxLifetime(time.Duration(*settings.ConnMaxLifetimeMilliseconds) * time.Millisecond)
db.SetConnMaxIdleTime(time.Duration(*settings.ConnMaxIdleTimeMilliseconds) * time.Millisecond)
``` 

As a separate step, update the defaults for cloud deployments.

**Comment by gustavotrott** [comment]
I was facing problems while running Mattermost and Focalboard in the same server.
After one or two days, Mattermost was stopping to work properly.
I didn't have time to investigate yet, I just stopped Focalboard and Mattermost seems to be running good now.
Do you think this was the problem (pg connections)? This new config will solve the problem?

**Comment by jespino** [comment]
@gustavotrott we added a set of environment variables to allow to modify this in the `0.7.1` but this is a temporary solution, we want to fix it properly (making the focalboard plugin use the mattermost database connections) for the next version. The solution actually is already in master, but we haven't created the release yet. Also that is only going to be available for mattermost >= 5.37, because needs some server changes.

**Comment by gustavotrott** [comment]
> @gustavotrott we added a set of environment variables to allow to modify this in the `0.7.1` but this is a temporary solution, we want to fix it properly (making the focalboard plugin use the mattermost database connections) for the next version. The solution actually is already in master, but we haven't created the release yet. Also that is only going to be available for mattermost >= 5.37, because needs some server changes.

Awesome! Thank you @jespino 
I am looking forward for next release! I intend to use daily and help reporting any issues.

**Comment by jespino** [comment]
Glad to hear that @gustavotrott, we really appreciate all this feedback.

**Comment by jespino** [comment]
I going to close this because I think is already addressed through the environment variables and the new DB RPC approach.
