### ISSUE TITLE
Feature Idea: Property Popover in Kanban view

### ISSUE THREAD

**Issue by hahmadia** [mattermost/focalboard#629]
**Summary:**
What the new capability is.
Hovering over a property in Kanban view and having it display what property it is. Currently there is no way of knowing what property is what without explicitly opening the card and inspecting the properties.

**How important this is to me and why:**

Importance: Medium

Use cases:
1. Getting more detailed view while in Kanban view

**Additional context / similar features:**
Any examples of good implementations of this capability.

Focalboard UX member, Michael Gamble, has proposed that the popover should look like this (where it shows priority). 
![image](https://user-images.githubusercontent.com/17804942/123264308-e75acc80-d4c7-11eb-8b98-3323029dc5dd.png)

For example, if I hover on the `TODO` in the image below, a popover should display showing `Status` since that's the property.

![image](https://user-images.githubusercontent.com/17804942/123264971-8ed7ff00-d4c8-11eb-9024-4e29fb255040.png)

**Comment by chenilim** [comment]
Thanks @hahmadia! Opening this up for grabs. The easy fix would be to add a `title` property to the property values / tags in the card preview. Bonus points if the popover can be styled as above.

**Comment by lordinkavu** [comment]
Can I take this up ?

**Comment by hahmadia** [comment]
@lordinkavu 

> Can I take this up ? 

Sure thing! Good luck and have fun!

**Comment by lordinkavu** [comment]
@ditsemto No issues. I've unassigned myself @hahmadia

**Comment by hahmadia** [comment]
Sorry about that @lordinkavu . Thanks for the understanding.
