### ISSUE TITLE
Doc: Add a description to a board

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#631]
**Summary:**
To add a description to a board:
* Hover above the board title
* Click on **Show description**, then
* Click on **Add a description...** to add / edit it.

**Link to documentation page:**
`https://www.focalboard.com/guide/user/`

**Comment by chenilim** [comment]
[Related thread](https://community.mattermost.com/core/pl/km7og4dt6i8t8qmb64omxnfk6e).

**Comment by chenilim** [comment]
And related discoverability issue: #630.

**Comment by haardikdharma10** [comment]
@chenilim, I am on it!

**Comment by chenilim** [comment]
Thanks @haardikdharma10! No worries, really appreciate your enthusiasm! Justine is working on refactoring our documentation, and the issues marked with the [documentation tag](https://github.com/mattermost/focalboard/labels/documentation) are on her queue.

**Comment by justinegeffen** [comment]
This is included in: https://docs.mattermost.com/boards/working-with-boards.html. Closing. :)
