### ISSUE TITLE
Bug: Focalboard v0.7.0 plugin crashes in cloud

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#632]
**Steps to reproduce the behavior:**
1. Create a test cloud instance (link in header of [FY22: Cloud channel](https://community.mattermost.com/private-core/channels/fy21-cloud)
2. Go to the plugin marketplace, install, then enable the Focalboard v0.7.0 plugin
3. Open a Focalboard workspace
4. Create a board, and use it for a few minutes
5. 500 errors start occurring, and the plugin eventually crashes

**Expected behavior:**
The plugin should not crash

**Screenshots:**
<img width="572" alt="Focalboard v0 7 0 cloud crash" src="https://user-images.githubusercontent.com/46905241/123345385-c8c9f500-d50a-11eb-9679-9a6d0f00edf2.png">

**Platform:**
 - Mattermost Cloud, Jun 24 2021 build
 - Chrome 91, macOS 10.15.17

**Comment by chenilim** [comment]
Additional notes:
* Everything seemed to work ok for a few minutes
* I was able to create boards, cards, drag / edit cards, share boards successfully
* Then API calls started returning 500 errors, and the plugin eventually crashed

**Comment by chenilim** [comment]
I'm not sure if this is exactly the cause, but the 500 errors seem to start right after I selected the "Random icon" option for the board icon. I tried this on a separate test cloud server, and 500 errors seem to start right after that action, or picking a board icon, or toggling the "show description" for a board, or adding a column to a board.

It did not seem to happen when changing the icon for cards. Editing the board title similarly seems to be ok. I can't think of why these particular actions may cause the server to go unstable, but it doesn't appear to be just a coincidence.

I am able to add and edit cards without issue, including adding multiple content blocks to a card. The errors seem to start when actions that affect the board happen. My only quick guess is that the WorkspaceListener listens to changes to board and view objects, but I don't know why that would cause an error, when the CardListener does not.

**Comment by wiggin77** [comment]
@chenilim the 500 errors should have more detail in the logs.  Can you provide them?

**Comment by chenilim** [comment]
It's a Cloud test instance. Do you know how I can retrieve the logs? There isn't a Logging section in the System Console.

**Comment by jespino** [comment]
This is also already fixed.
