### ISSUE TITLE
Add visual indication for active view in left sidebar

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#633]
**Summary:**
Add a visual indication for active view in the left sidebar. This will make it easier to spot the current view and switch to a different view.

**How important this is to me and why:**

Importance: Medium

**Additional context / similar features:**
This is how it should look like.
https://www.figma.com/file/UPbYxPDsg1aIzozyysRPeO/Issue-633-Sidebar-Active-State?node-id=66%3A9496

![Sidebar Active State - Issue 633](https://user-images.githubusercontent.com/11034289/125617851-7d16fbbf-ab8a-4642-b897-18749b038d6f.png)

Please touch base with @asaadmahmood for any design questions.

**Comment by chenilim** [comment]
@michaelgamble, do you have a suggestion on what the highlight style should be?

**Comment by chenilim** [comment]
@asaadmahmood, assigning this to you for now to think about in the context of the broader re-design. If you decide this is worth changing in the current design, please specify the CSS highlight color and put it up for grabs. Thanks.
