### ISSUE TITLE
Add some `good first issue` tickets

### ISSUE THREAD

**Issue by it33** [mattermost/focalboard#64]
@chenilim wondering your thoughts on adding some `good first issue` tickets? The below prompt came up when I checked out the repo this morning: 

![image](https://user-images.githubusercontent.com/177788/110249591-aeecae00-7f2b-11eb-9ce8-b4f45e0b383e.png)

Also, @haardikdharma10, are there certain tickets you'd be interested in working on in this repo?

**Comment by chenilim** [comment]
Thanks @it33. I marked a few existing issues as "good first issue", but anyone should feel free to pick up the ones marked "help wanted". In general, the following are great places to start if you are new to the codebase:
* Internationalize hardcoded strings (#33): Incrementally fix hardcoded UI strings.
* Fix server lint issues (#31): Incrementally fix lint warnings
* Add unit tests (e.g. #47): Particularly for server APIs
