### ISSUE TITLE
Bug: mattermost plugin not working 

### ISSUE THREAD

**Issue by arunzco** [mattermost/focalboard#648]
Using Bitnami Mattermost stack , getting the following error 

plugin","missing_plugin_id":"focalboard","url":"/plugins/focalboard/workspace/r7qnsi6psfrdxqghx1z9pyxmih","error":"plugin not found: focalboard"}

**Comment by chenilim** [comment]
Thanks @arunzco! to confirm, did you set up the [Mattermost Bitnami stack from here](https://bitnami.com/stack/mattermost/cloud)? What are the repro steps? Did this error occur immediately?

cc @ogi-m, @sbishel - we should try to repro this and determine the root cause.

**Comment by arunzco** [comment]
@chenilim 
Yes I have used the official Bitnami Stack,
Did the following 
1.Configured the latest plugin
2.Tried the focalboard button 

It shows a 500 server error on browser were as in mattermost app a blank windows appears and the log says the error I mentioned. also found the following logs 

{"level":"error","ts":1625021130.5641432,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"focalboard","error":"connection is shut down"}
{"level":"error","ts":1625021135.5650318,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, muxBroker couldn't accept connection","plugin_id":"focalboard","serve_http_stream_id":4,"error":"timeout waiting for accept"}
{"level":"error","ts":1625021135.565191,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connection","plugin_id":"focalboard","error":"timeout waiting for accept"}

I have also tried it with official mattermost setup instructions tried with  and without proxy servers   it also produces the same error. 
DB used is mysql 
https://docs.mattermost.com/install/install-ubuntu-1804.html#installing-ubuntu-server-18-04-lts

**Comment by chenilim** [comment]
Thanks @arunzco! @sbishel, do you think @harshilsharma63 or someone else could take a look at this? From the error log, it appears to be an issue between the plugin and Mattermost plugin framework. First thing would be to check if the versions on Bitnami are what we expect (Mattermost v5.36 and Focalboard 0.6.7). cc @jespino.

**Comment by harshilsharma63** [comment]
@arunzco do you see Focalboard in the list of installed plugins in System Console?

**Comment by arunzco** [comment]
Yes

**Comment by harshilsharma63** [comment]
Can you restart the plugin and record the logs from that point? The logs you shared show the plugin crashed. So the actual cause would be a bit above in the logs.

**Comment by arunzco** [comment]
Latest Logs 
[mattermost.log](https://github.com/mattermost/focalboard/files/6747956/mattermost.log)

**Comment by mgdelacroix** [comment]
Hi @arunzco. Please, can you confirm that you have the `SiteURL` property of the configuration set? You can find it on the `System Console`, in the `Web Server` tab.

**Comment by harshilsharma63** [comment]
@arunzco please add `charset=utf8mb4` to the database connection string in Mattermost configuration. With that added and the server restarted, the plugin should work fine.

Let us know if it doesn't work for you.

**Comment by arunzco** [comment]
@mgdelacroix  It already had siteurl set (ipaddress) i just pointed a new dns name and set that as siteurl and focalboard worked , and it also started working over all the ip on server or with any other dns pointed to server. 
I have reconfirmed this with a fresh deployment and that too worked. 

**And its not working on bitnami stack based deployments.**  

{"level":"info","ts":1625576488.7827826,"caller":"go-plugin@v1.4.0/stream.go:15","msg":"\u001b[31merror\u001b[0m [2021-07-06 13:01:28.782 Z] Unable to serve the index.html file \u001b[31merror\u001b[0m=\"open plugins/focalboard/pack/index.html: no such file or directory\"","plugin_id":"focalboard","source":"plugin_stdout"}

**Comment by arunzco** [comment]
> @arunzco please add `charset=utf8mb4` to the database connection string in Mattermost configuration. With that added and the server restarted, the plugin should work fine.
> 
> Let us know if it doesn't work for you.
@harshilsharma63 
Charset was already defined, without out this the plugin doesn't even start.

Currently issue is only with Bitnami Stack deployments.

**Comment by harshilsharma63** [comment]
> @mgdelacroix It already had siteurl set (ipaddress) i just pointed a new dns name and set that as siteurl and focalboard worked , and it also started working over all the ip on server or with any other dns pointed to server.
> I have reconfirmed this with a fresh deployment and that too worked.
> 
> **And its not working on bitnami stack based deployments.**
> 
> {"level":"info","ts":1625576488.7827826,"caller":"go-plugin@v1.4.0/stream.go:15","msg":"\u001b[31merror\u001b[0m [2021-07-06 13:01:28.782 Z] Unable to serve the index.html file \u001b[31merror\u001b[0m="open plugins/focalboard/pack/index.html: no such file or directory"","plugin_id":"focalboard","source":"plugin_stdout"}

1. Can you try reinstalling the plugin?
2. Try verifying if that file `plugins/focalboard/pack/index.html` actually exists on the filesystem or not. If it does and you still get the error, it could be a permission issue. Make sure the system user though which Mattermost is being run has complete access to the data dir.

**Comment by arunzco** [comment]
@harshilsharma63 File exists and its not the permission issue, can you try this on a bitnami mattermost stack.

**Comment by harshilsharma63** [comment]
@arunzco I did try on a fresh Bitnami installation and it worked for me.

**Comment by harshilsharma63** [comment]
Can you set file log level to debug?

**Comment by arunzco** [comment]
i have tried deploying bitnami in multiple instances and none worked, as i observed it looks like the plugin folder path is different in bitnami , mattermost is inside the 'apps' folder and the plugins resides in 'data' , and the root files is in apps/mattermost/server i believe .  
I have copied the 'data'  folder to 'apps/mattermost/server'  and renamed it to plugins and everything starts working . 
though the plugin directory is defined in config file but looks like focalboard is not working with that .

**Comment by mgdelacroix** [comment]
Yes, #609 should fix the issue, but it is not present on the `0.7.X` versions. @chenilim should we cherry-pick the fix to the `0.7` release branch so it's included in future dot releases?

**Comment by harshilsharma63** [comment]
Hmm, this is interesting. How did it work for my Bitnami image then? I created a new EC2 in AWS directly from the BItnami Mattermost TE image. This is strange.

**Comment by arunzco** [comment]
Its working with latest build. thanks guys.
