### ISSUE TITLE
Text editor is black on white even in dark mode

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#65]
**Summary:**
Adding card text shows a black-on-white text editor in dark mode.

**Steps to reproduce the behavior:**
1. Turn on dark mode
2. Open a card and tap "add content" at the bottom
3. Text editor appears black on white

**Expected behavior:**
Expect a dark mode text editor, with light text on dark background

**Screenshots:**
<img width="792" alt="Focalboard - dark mode text" src="https://user-images.githubusercontent.com/46905241/110369459-48d15b00-7fff-11eb-8830-fcd891a5a297.png">

**Platform:**
 - Chrome 88 on macOS 10.15.7

**Comment by jespino** [comment]
Fixed in main branch :)
