### ISSUE TITLE
Bug: Group actions header is fixed, not scrolling horizontally with other board items

### ISSUE THREAD

**Issue by jgilliam17** [mattermost/focalboard#652]
**Summary:**
Group header is fixed, not scrolling horizontally with other items, also causes `+add new group` button to be pushed out of view

**Steps to reproduce the behavior:**
1.  Select any board
2. Add enough columns to trigger horizontal scroll (make app full screen to add groups, than reduce in size, as the button to add groups may be out of view after few columns are added)
3. Scroll over to see the last group

**Expected behavior:**
Group actions header scrolls synchronously with other board items.

**Screenshots:**

https://user-images.githubusercontent.com/52937121/123844689-5168dc80-d8e1-11eb-8433-188b09645bed.mov

**Platform:**
 - OS and version: macOS Catalina 10.15.7, Focalboard Desktop app Version 0.7.0 (20)

**Additional context:**
n/a

**Comment by mcastellaneta** [comment]
Same for me. 

Windows 10, 10.0.19041, Focalboard v0.7.0 (focalboard-win.zip)

**Comment by chenilim** [comment]
Thanks @mcastellaneta and @mcastellaneta! This should be a dup of #585, so closing as a dup. @harshilsharma63, please verify this is fixed too with the fix for #585. Thanks.
