### ISSUE TITLE
Bug: Unable to add board with Focalboard plugin v0.7.1 on Cloud

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#655]
**Steps to reproduce the behavior:**
1. Create a test cloud instance (or use [my test instance, focalboarddev-9](https://focalboarddev-9.test.mattermost.cloud/signup_user_complete/?id=5kgckdtq5j8bmkcourzp3fnyte))
2. Install Focalboard v0.7.1 from the Marketplace, and enable it
3. Open a Focalboard workspace
4. Click + Add Board
5. Notice there are no templates
6. Add an empty board
7. No board appears
8. Refreshing still does not display any boards

**Expected behavior:**
Templates appear in the list, and you can create a new board

**Platform:**
 - Chrome 91 on macOS
 - Focalboard plugin v0.7.1 on Mattermost Cloud (test instance)

**Additional context:**
This is the behavior after raising the DB connection limit to 2 ([thread](https://community.mattermost.com/core/pl/q1yfwn8mcp8g3dm87n1d6dhbor)).

It looks like the initialization that creates the templates may have failed.

This appears to work correctly when the Focalboard 0.7.1 plugin is [installed manually](https://www.focalboard.com/download/mattermost/latest-plugin/) on an on-prem v5.36 instance, even with the same 2 DB connection restriction (by [setting the env vars in the Mattermost service](https://serverfault.com/questions/413397/how-to-set-environment-variable-in-systemd-service)).

**Comment by jprusch** [comment]
Hi,
I experienced the same with the 0.7.1 beta plugin. Upgrading to the latest 0.7.3 beta might have solved the issue. Not sure, if it works after upgrading or after deactivation/activation of the plugin.

Environment:
Focalboard Plugin 0.7.1
Mattermost Desktop 4.7 Windows 10
Mattermost Server 5.36.1

Hint: Focalboard version # doesn't get updated to 0.7.3 in System Console and the board window after upgrade and still displays 0.7.1. This has been reported already.

**Comment by jespino** [comment]
This is already fixed.
