### ISSUE TITLE
Bug: Hard to read labels in dark mode

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#678]
**Steps to reproduce the behavior:**
1. Create a board while in dark mode
2. Add a few columns
3. Notice that the column labels are low contrast (white on gray)

**Expected behavior:**
Labels should be more readable in dark mode.

**Screenshots:**
![Low contrast in dark mode](https://user-images.githubusercontent.com/46905241/124635156-f6346e00-de3b-11eb-9141-a59c7dae7fff.png)

**Additional context:**
We should do a general review and scrub of the dark mode theme, and also align with the Mattermost dark theme.

**Comment by chenilim** [comment]
Assigning to you @asaadmahmood to think about. Not a high priority, but we should incorporate this into any overall review / refactoring of the design. Thanks.

**Comment by asaadmahmood** [comment]
Should be fixed by my PR.
