### ISSUE TITLE
Bug: Double-clicking on a multi-select table column resizes too large

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#684]
**Steps to reproduce the behavior:**
1. Open a table with a multi-select column
2. Set one of the multi-select values to at least 2 or 3 items
3. Double click on the column border to auto-size it
4. The column autosizes too large (by over double)

**Expected behavior:**
The auto-size fits the maximum number of displayed items with a reasonable margin.

**Screenshots:**
https://user-images.githubusercontent.com/46905241/124798667-7922fa80-df08-11eb-92af-5de4f12f88f9.mov

**Platform:**
- Focalboard plugin v0.7.3
- Chrome 91 on macOS 11.4

**Additional context:**
Having additional selected items may cause the size error % to be even greater.

**Comment by chenilim** [comment]
This appears to be a bug in the table column resize logic. Setting it as up for grabs. cc @sbishel.

**Comment by sbishel** [comment]
Yes, multiSelect is not implemented [here](https://github.com/mattermost/focalboard/blob/main/webapp/src/octoUtils.tsx#L19)

**Comment by Shahzayb** [comment]
Hey @sbishel, I've done some debugging and found this. Hope that'll be useful.

`columnRefs` only contains refs of the cells of last card/row in a table, which is making it difficult to actually pick the multiSelect cell with max number of options. We need a multiSelect cell with max selected options to properly calculate the `padding`.
https://github.com/mattermost/focalboard/blob/caedc771b48ddf42ba7a738ccb88f24250a25748/webapp/src/components/table/table.tsx#L85-L89

And the `multiSelect` case in the `OctoUtils.propertyDisplayValue` can be implemented like this.

```
        case 'multiSelect': {
            if (propertyValue?.length) {
                const options = propertyTemplate.options.filter((o) => propertyValue.includes(o.id))
                if (!options?.length) {
                    Utils.assertFailure(`Invalid multiSelect option IDs ${propertyValue}, block.title: ${block.title}`)
                }
                const optionValues = options?.map((o) => o.value)
                displayValue = optionValues?.length ? optionValues.join(' ') : '(Unknown)'
            }
            break
        }
```
Also need to handle a `multiSelect` case in here:
https://github.com/mattermost/focalboard/blob/caedc771b48ddf42ba7a738ccb88f24250a25748/webapp/src/components/table/table.tsx#L91

**Comment by sbishel** [comment]
@Shahzayb 
Thanks for your information, it was helpful. By adding an empty label, if nothing is selected, and some other trickery, I was able to determine the padding per item, which then allows me to determine the correct padding for each set of values.
