### ISSUE TITLE
Bug:  Credentials stop working, start working again after service rebooted

### ISSUE THREAD

**Issue by ZevSwe** [mattermost/focalboard#685]
**Summary:**
When my session has expired I sometimes can't login again, it says the password or username is incorrect. If I login to the backend server and restart the service they start working again. No data seems to be lost. I use a password manager so it's not a typo, it has also happened twice now.

**Steps to reproduce the behavior:**
1. Start a server and create a user
2. Wait for session to expire plus a bit
3. Try login in again.

**Expected behavior:**
Login should not fail.

**Platform:**
Client
 - Firefox 89.0.2 (64-bit)
Server
 - Linux 4.15.0-106-generic #107-Ubuntu x86_64 x86_64 x86_64 GNU/Linux
 - Focalboard v0 7 0

**Comment by chenilim** [comment]
Thanks @zefhemel! To clarify, this is on Focalboard Personal Server (not the Mattermost Plugin) right?
If you see this repro again, please open the browser debug console and capture any network and/or console errors. From the description, it appears that the login API call fails.

There probably is a token expiry handling bug in there somewhere - my guess is the client think the token is valid, but the server knows it's not, but the client isn't clearing the stake token. FYI @sbishel.

**Comment by pydubreucq** [comment]
Hi,
I have the same problem here.
I've updated my Focalboard Personal Server to 7.0.0 and I've the same problem. Not before update.
I've made screenshot about network and console panel :

![Capture d’écran de 2021-07-08 10-38-37](https://user-images.githubusercontent.com/1188199/124892330-0f732100-dfda-11eb-83a3-c5592f142cfa.png)

![Capture d’écran de 2021-07-08 10-40-38](https://user-images.githubusercontent.com/1188199/124895508-e56f2e00-dfdc-11eb-8f81-3355d28e4e76.png)

When I restart Focalboard server, I can login again

Regards

**Comment by ZevSwe** [comment]
I've tested this again, it seems it does not on a browser I have not used for focalboard before. Thus the theory of session cookies seems to be out. I also get a 401 back.

**Comment by chenilim** [comment]
Hi @ZevSwe and @pydubreucq, just following up on this old issue. Are you still seeing problems with more recent builds? E.g. v0.9.2: https://github.com/mattermost/focalboard/releases/tag/v0.9.2

**Comment by ZevSwe** [comment]
Sorry for a late comment. I haven't seen this being a problem for the last few months.

**Comment by mlang38** [comment]
For me, I've run the Docker version with SQLite db. A while ago I couldn't log in again. I've kept the _focalboard.db_ in a volume. I've pulled new version of the image. But impossible to log in again. By the time I've perhaps forgot my password, but I've tried all the passwords I usually use.
Is there a way for me to change or remove my password directly in the _users_ table in the database ?

**Comment by riidom** [comment]
I have this problem currently, but with the Personal Desktop version. The fix to restart the server - can it be applied in that case at all? I don't know what to do here.

The problem is most likely due to a forced restart of the whole PC (couldn't properly exit Focalboard before rebooting). I kept Focalboard running for 4-5 days before. Not sure if I actually hit some expiration limit here.

Anyhow, what can I do access Focalboard again?

**Comment by chenilim** [comment]
Cleaning up old issues. Closing this because the original issues appears to have been resolved. Please open a new issue with details if you are still seeing it. For 500 errors, please attach a server log if it's available. Thanks.
