### ISSUE TITLE
Bug: Group message channel display name is displayed incorrectly

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#693]
**Summary:**

**Steps to reproduce the behavior:**
1. Create a Direct/Group Message between two (or more) users
2. Launch Focalboard
3. Observe spacing issues in the workspace name

**Expected behavior:**
In the case below, it should show "edwin_roberts, jlee, vlee".

**Screenshots:**
![FB_SPACING_Direct_Messaging](https://user-images.githubusercontent.com/46905241/124960818-966fcb80-dfd1-11eb-8238-3cd68cb229fe.jpg)

**Platform:**
 - Focalboard v0.7.3 plugin

**Comment by jespino** [comment]
This is fixed on main branch, I think.
