### ISSUE TITLE
Bug: Adding a new view does not switch to it on v0.8.0 plugin

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#718]
**Steps to reproduce the behavior:**
1. Install Focalboard plugin v0.8.0 on Mattermost 5.37
2. Create a board (e.g. the Project Tasks template)
3. Add a new view, e.g. a Gallery view (but any will do)
4. The new view does not appear
5. And clicking on the new view name in the sidebar does not open it
6. Only after a refresh (Cmd+R), can I open the new view

**Expected behavior:**
The new view should open immediately after creating.

**Platform:**
- Focalboard plugin v0.8.0 on MM 5.37
- Chrome 91 on macOS

**Additional context:**
This does not repro on the v0.8.0 standalone macOS app. Appears to be related to the plugin, and appears to be a regression.

**Comment by chenilim** [comment]
@harshilsharma63, could you help with the initial investigation of this, and reassign if appropriate? It's a pretty bad regression that we will want to cherry pick for 0.8.x. You can repro this on [mysql.test](https://mysql.test.mattermost.com/ogis-test-team/channels/town-square) if needed. Thanks.

**Comment by harshilsharma63** [comment]
@chenilim This PR by @jespino fixed this issue as a side effect - https://github.com/mattermost/focalboard/pull/649

**Comment by chenilim** [comment]
@jespino please fix this on release-0.8.0.

**Comment by jespino** [comment]
This is already fixed in the redux branch, I think we can wait until get that branch merged.

**Comment by jespino** [comment]
Already merged in main, closing this.

**Comment by chenilim** [comment]
We need to fix this on the `release-0.8.0' branch in order to ship to Cloud prod. Can you make the fix on `release-0.8.0`?

Without this fix, it would delay pushing Focalboard to Cloud. Unfortunately, the redux change is fairly large, so I don't think this can simply be cherry picked, and will need to be re-fixed on the old code. cc @sbishel

**Comment by jespino** [comment]
Submitted a solution for 0.8.0
