### ISSUE TITLE
Bug: Dragging multiple cards does not work

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#719]
**Steps to reproduce the behavior:**
1. Install Focalboard plugin v0.8.0 on Mattermost 5.37 (or macOS app, or Personal Server)
2. Or repro this on [mysql.test](https://mysql.test.mattermost.com/ogis-test-team/channels/town-square)
2. Create or open a board with 3 or more cards
3. In a board view, drag all cards to one column
4. Hold Shift, click on the top card
5. Hold Shift+Cmd, and click on the bottom card to select all 3
6. Drag the 3 cards to another column
7. Only one card is moved

**Expected behavior:**
All cards should move

**Screenshots:**
https://user-images.githubusercontent.com/46905241/125519445-80c2dc22-f755-4c56-8614-3c56b686729f.mov

**Platform:**
 - Focalboard plugin v0.8.0 on Mattermost v5.37 RC2, macOS app, and Personal Server

**Additional context:**
This appears to be a regression. Repros on c0.8.0 macOS app, plugin, and Personal Server. This worked on v0.7.3.

**Comment by chenilim** [comment]
Updated: I'm able to repro this on v0.8.0 macOS App and on a fresh install of Personal Server, so this is not specific to the plugin or HA. Updated the steps. Reassigning to you @hahmadia for the initial investigation. Please reassign if appropriate. My first guess is this is a regression due to a front-end change.

**Comment by hahmadia** [comment]
Not able to reproduce in Main
