### ISSUE TITLE
Feature Idea: Please release the .dmg and .exe files on GitHub

### ISSUE THREAD

**Issue by thompsonbrian** [mattermost/focalboard#721]
**Summary:**

It would be very convenient to have the .dmg and .exe (or .msi) files available on GitHub.

**How important this is to me and why:**

I'm dying to try focalboard on my corporate Mac, but I cannot because the App Store is blocked!  [Mostly] anything released on the App Store has been taken down from the Homebrew artifact archives, so that is not an option either.

Importance: ***High***

**Comment by apothecary-anchovy** [comment]
Agreed!

**Comment by haardikdharma10** [comment]
Thanks @thompsonbrian for raising this! Related to https://github.com/mattermost/focalboard/issues/638

/cc @chenilim

**Comment by thompsonbrian** [comment]
Referencing #99 and closing.
