### ISSUE TITLE
Bug: Websocket connection interrupted via Apache2

### ISSUE THREAD

**Issue by mzch** [mattermost/focalboard#728]
**Summary:**
Using Apache2 as a reverse proxy, focalboard show `Websocket connection closed. connection interrupted.` Could you tell me how to fix this issue?

**Steps to reproduce the behavior:**
1. Install focalboard
2. Start focalboad
3. Access focalboard via my browser.

**Expected behavior:**
No error.

**Screenshots:**
<img width="1494" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/125721670-e56c9f23-aec8-4d7d-87c7-f5fbd79aee0c.png">

**Platform:**
 - Browser and version: Chrome 91.0.4472.114
 - OS and version: Debian 10.10
 - Reverse Proxy: Apache2

**Additional context:**
- Apache config
```apache
<IfModule mod_ssl.c>
<VirtualHost *:443>

	ServerName f.gtd.jp
	ServerAdmin webmaster@gtd.jp
	SSLCertificateFile /etc/letsencrypt/live/gtd.jp/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/gtd.jp/privkey.pem

	RequestHeader set X-Forwarded-Proto "https"
	ProxyPreserveHost On

	<Location /ws>
		ProxyPass ws://127.0.0.1:8000/ws
		ProxyPassReverse ws://127.0.0.1:8000/ws
	</Location>
	<Location />
		ProxyPass http://127.0.0.1:8000/
		ProxyPassReverse http://127.0.0.1:8000/
	</Location>

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
</IfModule>
```
- config.json
```json
{
	"serverRoot": "https://f.gtd.jp",
	"port": 8000,
	"dbtype": "postgres",
	"dbconfig": "postgres://focalboard:password@192.168.207.10:5432/focalboard?sslmode=disable",
	"postgres_dbconfig": "dbname=focalboard sslmode=disable",
	"useSSL": false,
	"webpath": "./pack",
	"filespath": "../files",
    "telemetry": true,
    "session_expire_time": 2592000,
    "session_refresh_time": 18000,
    "localOnly": false,
    "enableLocalMode": false,
    "localModeSocketLocation": "/var/tmp/focalboard_local.socket"
}
```

**Comment by chenilim** [comment]
Hi @mzch, do the [Apache config steps in the download guide here](https://www.focalboard.com/download/mattermost/#with-apache-unofficial) work for you? Thanks.

**Comment by mzch** [comment]
Great! Thanks! :)
