### ISSUE TITLE
Bug: Drag to columns doesn't work as expected

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#733]
**Steps to reproduce the behavior:**
1. Create a card with multiple text content blocks
2. Drag one item to the same column as another - this works
3. Drag the right item to the left
4. The order is unchanged

**Expected behavior:**
The order in the column should change

**Screenshots:**
https://user-images.githubusercontent.com/46905241/125814746-fe6c1ae3-1c55-4c52-a1c1-821f85efbbed.mov

**Platform:**
 - Latest build on macOS
 - Chrome 91

**Additional context:**
Other issues:
1. Dragging 3 items to the same column results in the right-most item disappearing
2. (Not sure if this is a limitation): Can't drag an item to the right-most column
3. (Might be a separate issue): Dragging an item shows "ghosting" as if you are dragging all the content

**Comment by jespino** [comment]
Looks lie this is working on main branch.
