### ISSUE TITLE
Bug: Wide table horizontal scrollbar appears in the middle of page

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#738]
**Steps to reproduce the behavior:**
1. Open a table with a few row but many columns (or resize the browser narrower than its width)
2. Notice that the horizontal scrollbar appears in the middle of the page

**Expected behavior:**
The scrollbar (if any) should appear at the bottom of the page

**Screenshots:**
<img width="1682" alt="H table scrollbar" src="https://user-images.githubusercontent.com/46905241/125978777-c3d20895-101f-422e-9205-d068604a217d.png">

**Platform:**
 - Focalboard plugin v0.8.1, Chrome 91 on macOS

**Additional context:**
This is a regression.

**Comment by chenilim** [comment]
@harshilsharma63, could you help investigate this? It appears to be a regression, and may be related to recent CSS changes. Thanks.

**Comment by kamre** [comment]
Regression was introduced in #586 when `overflow: auto` [was added](https://github.com/mattermost/focalboard/pull/586/files#diff-8cfe234ced0d8ff8513c392fbdff38c79b43ab48be429ff0ed7589502e368b2dR148) to `&.octo-table-body`

**Comment by kamre** [comment]
@harshilsharma63 @chenilim if the width of the browser window is small enough there will be two scroll bars at the bottom:
![GH-738-TwoScrollBars](https://user-images.githubusercontent.com/5587620/126158777-b612a52e-cdc5-4ad0-9868-18ce1e0cb521.gif)
Is this the expected behaviour?

**Comment by kamre** [comment]
@harshilsharma63 @chenilim kanban board has the same issue with scrollbar in the middle of page.

Should this issue be reopened or a new one created?

**Comment by chenilim** [comment]
Hi @kamre, sorry for the delay. Are you still seeing issues on the build in `main`? If so, please file a new issue, thanks!

**Comment by kamre** [comment]
Hello @chenilim, kanban horizontal scrollbar in the middle of page was fixed in #825 

For double scrollbars I have filed #889
