### ISSUE TITLE
Bug: Group sorting causes other boards to fall out of alignment

### ISSUE THREAD

**Issue by tjbortz1s** [mattermost/focalboard#740]
**Summary:**
When sorting groups moving one board will seem to randomly (or pseudo randomly) cause groups to go out of order.

**Steps to reproduce the behavior:**
This occurs any time I attempt to sort boards into the order they're meant to be in.  

**Expected behavior:**
When I drop a board into a spot, it should not leave that spot until I drop another board into its position

**Screenshots:**
![BrokenBoardSorting](https://user-images.githubusercontent.com/6193065/125980275-736bea79-109d-44d0-846c-e3db27b0b816.gif)

**Platform:**
 - WPF v0.8.0

**Additional context:**
I began to notice these issues after making and trying to move items into a new property - after going back to the original property everything was out of order and I wasn't able to get it back into order.

**Comment by tjbortz1s** [comment]
Experimenting with this today, I managed to get everything back in order by moving a board, flipping between the two boards using the left bar, and moving the board again. I moved the boards one at a time to adjacent columns only.  Moving a board twice without swapping between boards seemed to cause issues with jumbling.

**Comment by chenilim** [comment]
@harshilsharma63, looks like a dup / additional repro of #420 on v0.8.

**Comment by harshilsharma63** [comment]
Fixed with #789
