### ISSUE TITLE
Bug: Swapping between board group by status causes hidden groups to unhide

### ISSUE THREAD

**Issue by tjbortz1s** [mattermost/focalboard#741]
**Summary:**
swapping status on group by causes hidden groups to unhide.

Rearranging boards can also cause this to occur, but that seems to happen less consistently?
(edit - just watched it happen so this for sure is a thing)

**Steps to reproduce the behavior:**
Hide a group.
Change group by option
Change back
Group will be unhidden.

**Expected behavior:**
Group remains hidden.

**Screenshots:**
![BoardUnhiddenByGroupByChange](https://user-images.githubusercontent.com/6193065/125981097-fb06ecf6-ec0f-484e-aca2-b6b5d8a54067.gif)

**Platform:**
WPF 0.8.0

**Comment by tjbortz1s** [comment]
This is also caused by dragging an item between two groups.

**Comment by chenilim** [comment]
Thanks @tjbortz1s! @harshilsharma63, this might be related to #773.

**Comment by jespino** [comment]
@tjbortz1s what do you mean with "Between two groups" I'm not able to reproduce that case.

The other case it that way because is how the data is design. The hidden groups are cleaned after you change the group by, to "give space" to the new hidden groups based on the new group by. We can think how to solve that, for example, not cleaning that up.

**Comment by tjbortz1s** [comment]
> 
> 
> @tjbortz1s what do you mean with "Between two groups" I'm not able to reproduce that case.
> 
> The other case it that way because is how the data is design. The hidden groups are cleaned after you change the group by, to "give space" to the new hidden groups based on the new group by. We can think how to solve that, for example, not cleaning that up.

In my case - dragging one of the cards between, say "open" and "complete" would cause the hidden groups to be lost after the card ended up at its destination.  It seems like that it has only happened intermittently or in some very odd situations - as I'm dragging the cards between groups now and it's working fine.
