### ISSUE TITLE
Bug: Clicking on a Markdown link should open it in a new tab

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#753]
**Steps to reproduce the behavior:**
1. Open a card with a link in the Markdown description (or add one)
2. Click on the link
3. The card enters edit mode, then the link is opened in the same tab

**Expected behavior:**
The link should open in a new (_blank) tab, without entering edit mode.

**Screenshots:**
https://user-images.githubusercontent.com/46905241/126238307-fc2b1fb8-d573-4b43-b1af-dc2e70b4222b.mov

**Platform:**
 - Focalboard plugin 0.8.1 on community server, Chrome 91 on macOS

**Additional context:**
This is a regression.

**Comment by chenilim** [comment]
@hahmadia can you help investigate? Not sure what caused this regression, but I recommend starting with the MarkdownEditor control. cc @harshilsharma63.

**Comment by kamre** [comment]
@chenilim @jespino regression happened during the changes in #579, in particular when this check was added to `Utils.htmlFromMarkdown`:
```ts
if ((window as any).openInNewBrowser) {
   ...
}
```
because `openInNewBrowser` is `undefined`.
