### ISSUE TITLE
Bug: DB connections timeout on updates (Insert POST Block API requests)

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#756]
**Steps to reproduce the behavior:**
1. Use the Focalboard plugin v0.8.1 on Mattermost v5.37 for a while
2. Updates (e.g. move cards to different column) fail to complete

**Expected behavior:**
Updates work.

**Platform:**
 - Focalboard plugin v0.8.1 on Mattermost v5.37 with MySQL
 - Chrome 91 on macOS

**Additional context:**
Views (GET requests) still work fine.
See the following error in the server logs: `Error 1205: Lock wait timeout exceeded; try restarting transaction`

**Comment by chenilim** [comment]
@jespino, assigning this to you to track the issue and to merge the [fix in the release-0.8.0 branch](https://github.com/mattermost/focalboard/commit/1b8d46998691d089ab76089c1a1177a3bf14be08) to main. Thanks.

**Comment by jespino** [comment]
This is done
