### ISSUE TITLE
Download file is a zip file, not a tar.gz as documented

### ISSUE THREAD

**Issue by proffalken** [mattermost/focalboard#77]
**Summary:**

https://www.focalboard.com/download/personal-edition/ubuntu/#install-focalboard states that a user should download and unpack a file named https://releases.mattermost.com/focalboard/0.5.0/focalboard-server-linux-amd64.tar.gz however this file is actually a zip file with the tar.gz file inside it named the same.

**Steps to reproduce the behavior:**
1. https://www.focalboard.com/download/personal-edition/ubuntu/#install-focalboard
2. Download the installation archive
3. Try to unpack it with `tar -zxvf focalboard-server-linux-amd64.tar.gz`

**Expected behavior:**
File should be a .tar.gz *or* a .zip file, not one inside the other with incorrect file endings.

**Comment by proffalken** [comment]
Looks like it's to do with this: https://github.com/actions/upload-artifact#zipped-artifact-downloads

I can't find a reference to the `download-artifact` call however, so it's weird that it's being zipped as well as .tgz'd

**Comment by jespino** [comment]
Thanks for the pointer @proffalken!

**Comment by chenilim** [comment]
Thanks, I've uploaded the server binaries to the [GitHub releases](https://github.com/mattermost/focalboard/releases) and updated [the docs](https://www.focalboard.com/download/personal-edition/ubuntu/), dupe issue in #114. E.g. this should download the latest 0.6.1 server: `wget https://github.com/mattermost/focalboard/releases/download/v0.6.1/focalboard-server-linux-amd64.tar.gz`.

Sorry all for the confusion. It looks like we did originally run into the GitHub double-zip issue, and missed it in the file hosted on releases.mattermost.com. For now, we'll put the release binaries in the GitHub releases, streamlining our process. If you don't mind, could you test that URL in the docker, and update the dockerfile if it works ok? Thanks.

**Comment by proffalken** [comment]
@chenilim good work, thanks.  Dockerfile updated and ready to go at https://github.com/mattermost/focalboard/pull/122

One thing I did notice was that when I ran it even though it downloads 0.6.1, it shows 0.6.0 as the version inside the container on the Web UI?

**Comment by chenilim** [comment]
Thanks @proffalken! I've fixed the display version in #136, with more details. We rev'ed to 0.6.1 for the Mac App Store (and 0.6.2 for Windows) even though the server version was 0.6.0.
