### ISSUE TITLE
Bug: Dragging a card to another column then back doesn't work

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#773]
**Summary:**
**Steps to reproduce the behavior:**
1. Create a new board, e.g. using the Roadmap template
2. Drag a card from column A to column B
3. Drag the card back from column B to column A
4. Nothing happens

**Expected behavior:**
The card returns to column A

**Screenshots:**
https://user-images.githubusercontent.com/46905241/126744015-70847796-e499-4f78-8e2a-af271a3e713e.mov

**Platform:**
 - Focalboard 0.8.1 on Mattermost v5.37 (community server)
 - Chroms 91 on macOS

**Additional context:**
If you first drag another card to column A, then drag the original card to column A, that works.

**Comment by chenilim** [comment]
@harshilsharma63, could you help investigate this one too? Not sure if this is already fixed in main. If so, please also fix on the `release-0.8.0` branch.

I have noticed some general instability with sequential drag operations like this one.

**Comment by tjbortz1s** [comment]
This may be relevant:
https://github.com/mattermost/focalboard/issues/740

**Comment by chenilim** [comment]
Is this a dup of #708? Please close if so, and cherry pick / verify that fix on `release-0.8.0`. Thanks.

**Comment by harshilsharma63** [comment]
@chenilim yes it's a duplicate of #708 and is fixed on main. Can you give it another try?

**Comment by chenilim** [comment]
Thanks Harshil. If it's fixed in main, please cherry-pick or re-fix on `release-0.8.0`. Thanks.

**Comment by harshilsharma63** [comment]
@chenilim done. Cherrypicked into `release-0.8.0`.

**Comment by hahmadia** [comment]
Since #708 is close should we close this too?

**Comment by harshilsharma63** [comment]
@hahmadia yes. @chenilim can you just try it out on the latest `release-0.8.0` branch? I just want to make sure I got it.

**Comment by chenilim** [comment]
Thanks @harshilsharma63! I'm out until next week. @ogi-m, can you help Harshil test this? Thanks.

**Comment by ogi-m** [comment]
✔️ Confirmed this is now fixed - no issues with when moving cards between columns
