### ISSUE TITLE
Bug: Unable to access other views after adding a board title

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#774]
**Summary:**
If a user creates a new board, gives it a title and then adds several other views, the user is unable to navigate to any of the newly created views. A refresh fixes the issue.

**Steps to reproduce the behavior:**
1. Open Focalboard
2. Click on Add Board > Empty Board
3. Add a title to the new board
4. Click on the arrow next to board view to open the dropdown
5. In the dropdown click Add View > Table
6. Click on the Table view item in the sidebar

**Expected behavior:**
Table view opens

**Observed behavior:**
Nothing happens, user is stuck on Board view

**Platform:**
Plugin v0.8.1

**Comment by chenilim** [comment]
Thanks @ogi-m. Looks like this is a dup of #718, and is a high priority to fix for 0.8.
