### ISSUE TITLE
Bug: All dates should appear in MMMM DD, YYYY format

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#779]
**Summary:**
Per our updated design, dates in general should appear in the `MMMM DD, YYYY` format. The places where this needs to be fixed includes:
* Created Date properties
* Updated Date / Time

On both the in-card display and in the card preview on boards.

**Steps to reproduce the behavior:**
1. Open a card with a Created and Updated Date property
2. The format is not MMMM DD, YYYY

**Expected behavior:**
The format should be MMMM DD, YYYY, e.g. `September 28, 2021`. Note that the month should be fully spelled out, and not include the day name.

For updated time, it should include both the date and time, e.g. `September 28, 2021 4:20PM`

**Screenshots:**
Card date properties:
<img width="384" alt="In card date formats" src="https://user-images.githubusercontent.com/46905241/126916973-fb7e9480-61ab-482a-9c0e-707c5cf939d8.png">

Board card preview:
<img width="275" alt="Board card preview date formats" src="https://user-images.githubusercontent.com/46905241/126916976-983f776f-cec5-4011-b7e9-81727bb05508.png">

**Platform:**
 - Focalboard v0.8.1 (community server)

**Additional context:**
Related to #715.

**Comment by kamre** [comment]
@chenilim After using `Utils.displayDateTime` with `long` option for month inside `Comment`/`CreatedAt`/`LastModifiedAt` components it looks like this:

![image](https://user-images.githubusercontent.com/5587620/127088107-83d6a807-bff8-4fbc-a8e7-01d3d08e4e04.png)
and
![GH-779-Board-Card-Preview](https://user-images.githubusercontent.com/5587620/127088273-0ee04564-b854-4480-9b4a-046c113bb425.gif)

@asaadmahmood FYI

**Comment by chenilim** [comment]
Thanks @kamre! I guess I forgot to specify it in this ticket, but if the year is the current year, then let's omit it. i.e.:
* July 29 (for date)
* July 27, 9:55 AM (for date-time)

It looks like this was implemented for `displayDate`. Can you also help implement it in `displayDateTime`? Thanks!

**Comment by kamre** [comment]
@chenilim yes, sure it will be easy to implement.

**Comment by kamre** [comment]
@asaadmahmood editable date uses input with date picker and its text is not properly aligned with the text inside div for created/updated date and time (added temporary borders with red one for the input):
![image](https://user-images.githubusercontent.com/5587620/127107757-a15a6507-8e11-48db-95fa-fee86841fcbe.png)
Is this an issue? Should we try to fix this?
