### ISSUE TITLE
Bug: Cards with long titles look bad in kanban board

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#780]
**Summary:**
Cards with long titles look bad in kanban board

**Steps to reproduce the behavior:**
1. Go to any kanban view board.
1. Create a card (or use existing card) with a really long title.

**Expected behavior:**
A card with a long title shouldn't extend infinitely vertically.

**Screenshots:**
<img width="557" alt="Screenshot 2021-07-26 at 10 27 10 AM" src="https://user-images.githubusercontent.com/18575143/126935211-e0fc26ec-075b-494e-b4c7-ff68a3e324f4.png">

**Platform:**
 - Browser and version: Firefox 90
 - OS and version: MacOS 11.4

**Additional context:**
NA

**Comment by harshilsharma63** [comment]
@asaadmahmood assigning this to you for UX.

**Comment by jespino** [comment]
@asaadmahmood probably the simplest solution for this (for kanban and gallery view) is to truncate the card title to a certain amount of characters. I can create a PR with that approach easily.

**Comment by kamre** [comment]
Notion and Trello don't cut titles:
![image](https://user-images.githubusercontent.com/5587620/127764781-d75888f1-61af-4ea8-bb38-61f1cdaab71b.png)
![image](https://user-images.githubusercontent.com/5587620/127764814-e4cc0b79-5560-433b-bc5b-f36486fb897e.png)

**Comment by asaadmahmood** [comment]
@jespino I don't think this is a big issue to begin with, we can truncate it at 3 lines if we want. But I'm not sure if its that important for users. Let's keep it as is and see if a lot of users are finding an issue with this.

**Comment by jespino** [comment]
Ok, lets close this and see if somebody complains in the future.
