### ISSUE TITLE
Bug: Invalid Registration Link

### ISSUE THREAD

**Issue by gaoyan198** [mattermost/focalboard#796]
**Summary:**
Unable to register new users

**Steps to reproduce the behavior:**
1. Go to log in page
2. Click on "or create an account ...."
3. Fill in the details
4. Error message of "invalid registration link" pops out

**Expected behavior:**
Supposed to go through and create the user for me

**Platform:**
 - Brower: Safari 14.1.1.1

**Comment by jespino** [comment]
Currently focalboard is an "invitation only" system, the first account can be created without invitation link, but after that, you have to share the invitation link (you can get it in the top left header button), with that invitation link the registration should work.

@asaadmahmood clearly here we have a UX problem, should we hide the "o create an account" link when the server has already the first account? Also we can add a setting for the "allowRegistrationWithoutInvite" (but with a better setting name), but anyway the logic for "not showing the link when is not needed" I think should be done.

**Comment by asaadmahmood** [comment]
@jespino Yes, we should hide it if the first user is created.
And we can also have a config that shows/hide that link and make Focalboard work for creating users without invitation as well. But the first step is removing the link.

**Comment by gaoyan198** [comment]
Thanks @jespino ! Got confused and used the "register" button at the login page.

**Comment by kamre** [comment]
@jespino will checking that "the server has already the first account" require a new server API endpoint or existing ones should be enough?

**Comment by jespino** [comment]
@kamre I think is going to need a new one, we can build other tricks, but I think is fine to have another API for that.
