### ISSUE TITLE
Bug: Drag and drop card onto itself causes card to jump to top of screen.

### ISSUE THREAD

**Issue by tjbortz1s** [mattermost/focalboard#801]
**Summary:**
Dragging and dropping a card onto itself causes the card to appear at the top of the list

**Expected behavior:**
The card does not move

**Screenshots:**
![DragDropOntoSelfBug](https://user-images.githubusercontent.com/6193065/127498851-25f34dc4-8e1a-4697-9e82-a7814d7fc5f3.gif)

**Platform:**
WPF 8.0.0

**Comment by kamre** [comment]
Reproducible on `main` branch on standalone server.

Can be fixed by checking if the card is the same one:
```ts
    const onDropToCard = async (srcCard: Card, dstCard: Card) => {
        if (srcCard.id === dstCard.id) {
            return
        }
        ...
    }
```
Should I create pull request with this change?

**Comment by jespino** [comment]
@kamre yes, feel free to create the PR, looks like the correct solution. Thanks! :)
