### ISSUE TITLE
Update Menu to common component

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#808]
The menus in CardDialog.tsx, GalleryCard.tsx, and KanbanCard.tsx are all very similar and in two cases identical. 

We should create a common component for the menu and reuse on each card. All cards should support Delete, Duplicate, Copy Link. Additional menu items such as for CardDialog should be able to be added.

**Comment by majidsajadi** [comment]
i would like to work on this. please assign to me if possible.

**Comment by sbishel** [comment]
Awesome @majidsajadi its all yours. Let me know if you need additional information.

**Comment by Paul0908** [comment]
I would like to fix the issue. It would be nice if you could assigne me.

**Comment by sbishel** [comment]
Thanks @Paul0908 - all yours.
