### ISSUE TITLE
Bug: Not able to rename a new card from "Untitled" (macOS & Win10)

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#809]
Reproduced on AWS "latest" builds for macOS and Win10

**Summary:**
Text flashes between "Untitled" and "new_card_name" 

https://user-images.githubusercontent.com/13020833/127748317-18d681fd-0e40-48f1-a993-97e54dc37208.mp4

**Comment by kamre** [comment]
The issue is reproducible for standalone server and started to happen after the merge of #807

@jespino FYI

**Comment by jespino** [comment]
Thanks for the heads up @kamre, I'll take a look.
