### ISSUE TITLE
Doc: udpate download to latest!!!

### ISSUE THREAD

**Issue by TOWUK** [mattermost/focalboard#814]
**Summary:**
set latest version!!!

**Link to documentation page:**
https://www.focalboard.com/download/personal-edition/ubuntu/

**(Optional) Additional context and/or screenshot:**
![image](https://user-images.githubusercontent.com/28830162/127765976-bbefb2eb-5f71-431c-8875-b5b07b9183a0.png)

**Comment by justinegeffen** [comment]
Thank you for raising this issue. :) The documentation has been updated for clarity and will be available on the Mattermost product documentation site shortly.
