### ISSUE TITLE
Bug: Auto Size Column Doesn't Work In Firefox

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#817]
**Summary:**
Auto sizing of columns doesn't work in Firefox. Also worth checking Safari.

**Steps to reproduce the behaviour:**
1. Open Focalboard in Firefox.
1. Create a new Roadmap board.
2. The initial board should display a board with a Priority column header truncated to Priorit...
3. Double click the resize handle on the right side of the Priority column.
4. The column size would still be the same/

**Expected behaviour:**
Double-clicking column resize handler should auto-resize column in Firefox and Safari.

**Platform:**
 - Browser and version: Firefox 90
 - OS and version: MacOS Big Sur

**Additional context:**
The feature works fine in Chrome.

**Comment by kamre** [comment]
@harshilsharma63 this is interesting! I am going to look into this.

Some initial debugging in Firefox on Windows shows that `borderLeft` and `borderRight` for the computed style are empty strings and this leads to `NaN` because of `parseInt` usage.

At the same time `borderLeft`/`borderRight` in Chrome are like this: `1px solid rgba(0, 0, 0, 0)`

**Comment by harshilsharma63** [comment]
@kamre Hmm, that's interesting. If you'd like to work on this, I can assign it to you and remove the up for grabs label.

**Comment by kamre** [comment]
Please assign to me.

**Comment by harshilsharma63** [comment]
There you go!

**Comment by kamre** [comment]
Looks like Firefox doesn't support shorthands for computed style, i.e. `borderLeftWidth` is available and is equal to `1px` and `borderLeft` is just empty.

Very similar thing with shorthand for `font`, different parts like `fontSize`/`fontFamily` are available but the string for `font` is just empty.
