### ISSUE TITLE
WebApp Unit Tests ./webapp/src/components/flashMessages.tsx

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#832]
Write Unit Tests for ./webapp/src/components/flashMessages.tsx

see `./webapp/src/components/table/*` or `./webapp/src/components/properties/dateRange/dateRange.test.tsx for sample test`

**Comment by Bhavin789** [comment]
Hi @sbishel , may I add a test to this? Possible to assign it to me? Thanks!
