### ISSUE TITLE
WebApp Unit Tests for ./webapp/src/components/propertyValueEditor.tsx

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#835]
Write Unit Tests for ./webapp/src/components/propertyValueEditor.tsx

see `./webapp/src/components/table/*` or `./webapp/src/components/properties/dateRange/dateRange.test.tsx for sample test`

**Comment by jufab** [comment]
This component appears to be unknown.
Maybe it's `propertyValueElement` now?
But there are already tests for this component.
@sbishel I think you can close this problem 😉

**Comment by sbishel** [comment]
closing as file no longer exists
