### ISSUE TITLE
WebApp Unit Tests for ./webapp/src/components/cardDetail/cardDetailContents.tsx

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#842]
Write Unit Tests for `./webapp/src/components/cardDetail/cardDetailContents.tsx`

see `./webapp/src/components/table/*` or`./webapp/src/components/properties/dateRange/dateRange.test.tsx` for sample tests

**Comment by hahmadia** [comment]
I will take this on

**Comment by kamre** [comment]
@sbishel @hahmadia will this be only snapshot unit tests?

**Comment by hahmadia** [comment]
@kamre 

I'm working on this right now. I can tag you on the PR once I finish so you can see what tests I've written.
Did you have suggestions for particular test we should write? It will mainly be snapshot but also some other tests to cover some logic things

**Comment by kamre** [comment]
@hahmadia yes, I see that you are working on this. Please tag me when there will be a PR.

There are many other issues for adding unit tests for `webapp`. So I wanted to work on some of them. And just want to understand how it is better to write such unit tests.

Looking at the existing unit tests I see that many of them are snapshot tests. Is this the recommended way?

**Comment by hahmadia** [comment]
@kamre  @Shahzayb 

Here is the link to my PR. It's under review but you can get an idea of some tests I've written

https://github.com/mattermost/focalboard/pull/884
