### ISSUE TITLE
Write Unit Tests for ./webapp/src/components/cardDetail/commentsList.tsx

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#846]
Write Unit Tests for `./webapp/src/components/cardDetail/commentsList.tsx`

see `./webapp/src/components/table/*` or`./webapp/src/components/properties/dateRange/dateRange.test.tsx` for sample tests

**Comment by gagandeepp** [comment]
interested please assign

**Comment by jufab** [comment]
Hi @gagandeepp , 
Still interested or can I do it?

**Comment by jufab** [comment]
@sbishel  Finally, this test already exists. you can close this PR 😊
