### ISSUE TITLE
WebApp Unit Tests for ./webapp/src/components/properties/multiSelect.tsx

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#858]
Write Unit Tests for `./webapp/src/components/properties/multiSelect.tsx`

see `./webapp/src/components/table/*` or`./webapp/src/components/properties/dateRange/dateRange.test.tsx` for sample test

**Comment by Shahzayb** [comment]
I'd like to work on this.

**Comment by Shahzayb** [comment]
I'm working on this.

**Comment by Shahzayb** [comment]
I'm not gonna mock `react-select/creatable`. Instead, I'm gonna use this lib https://github.com/romgain/react-select-event
