### ISSUE TITLE
Documentation for linux personal desktop is incorrect

### ISSUE THREAD

**Issue by archaeogeek** [mattermost/focalboard#87]
**Summary:**
The information for downloading and installing linux personal desktop at https://www.focalboard.com/download/personal-edition/desktop/ is incorrect. On downloading and extracting focalboard-linux.tar.gz from github (for 0.6.1 at least) the directory listing is as shown in the screenshot below.

Rather than "Open focalboard from within the focalboard folder" , you have to run `focalboard-app` from the `focalboard-app` folder.

**Expected behavior:**
The documentation should match the folder and file name provided in the download

**Screenshots:**
![Screenshot from 2021-03-18 09-10-05](https://user-images.githubusercontent.com/1544849/111601013-dcf2ad80-87c9-11eb-8e0b-53e0be93c5fe.png)

**Platform:**
 - Ubuntu 20.04

**Comment by jespino** [comment]
Thanks @archaeogeek. Fixed in the documentation, It is going to be right in the next deploy of the documentation.
