### ISSUE TITLE
Bug: The selection of an icon makes the new properties disappear

### ISSUE THREAD

**Issue by miguelcorreia19** [mattermost/focalboard#871]
**Summary:**
On Project Tasks, when we change the icon, the new properties disappear.

**Steps to reproduce the behavior:**
1. Add Board > Project Tasks
2. Open a Task (can be one of the existing defaults)
3. Add a property and close the Dialog Box
4. On the left of the Project Tasks name, select Pick icon
5. Choose anyone

**Expected behavior:**
The new property, that was created on point 3, had disappeared

**Platform:**
 - Focalboard App 0.8.0 (21)
 - macOS 11.4 (20F71)

**Additional context:**
If you select a Random icon or Remove icon, on step 4, the new properties stay

Thanks

**Comment by jespino** [comment]
@miguelcorreia19 submitted a PR fixing that, thanks for the heads up! :+1:
