### ISSUE TITLE
Website fonts are hard to see

### ISSUE THREAD

**Issue by Arteneko** [mattermost/focalboard#88]
**Summary:**

The top-right navigation bar's font is too thin to be readable, and the links inside the the presentation speech under the screenshot [on the homepage](https://www.focalboard.com/) are too low-contrast from the background.

**Comment by jespino** [comment]
@asaadmahmood can you take a look on this? what do you think? I agree with that, probably a font-weight of 400 would be better option. And probably the links color is not selected right. Can you provide your opinion? what color and font-weight would you use?

The changes in this page probably needs to be reflected [here](https://developers.mattermost.com/) too.

**Comment by asaadmahmood** [comment]
@jespino Is the html for the homepage in this repo?
I can fix it.
The font weight needs to be fixed, and we should also probably remove the opacity, we can have an underline on hover.

**Comment by jespino** [comment]
@asaadmahmood yes, it is in the website folder in this repo. It is not an HTML it is an hugo site.

**Comment by chenilim** [comment]
Cleaning up old issues. Looks like this has been addressed, so closing.
