### ISSUE TITLE
Bug: Popup menu is clipped.

### ISSUE THREAD

**Issue by whooperlove** [mattermost/focalboard#881]
**Summary:**
Popup menu is clipped in roadmap page.
<img width="1214" alt="Screen Shot 2021-08-04 at 7 00 54 AM" src="https://user-images.githubusercontent.com/9650829/128092075-8d55d006-5316-4708-84ac-52b3d41df1cc.png">

**Steps to reproduce the behavior:**
1. Launch Forcalboard mac app.
2. Create a board from 'Roadmap' template.
3. Click on 'P1' in the list.
4. Popup menu is not fully visible because it's clipped by container.

**Expected behavior:**
Popup menu shall be fully visible without being clipped.

**Screenshots:**
Please find attached screenshot.

**Platform:**
 - Browser and version: Firefox 90.0.2
 - OS and version: macOs 11.4
 
**Additional context:**

**Comment by kamre** [comment]
Looks like #815 that was fixed recently in `main`.

**Comment by jespino** [comment]
Yes, that is fixed on main. Thanks for reporting it. The fix will be available in 0.9.0
