### ISSUE TITLE
Bug: double horizontal scrollbars for narrow viewport

### ISSUE THREAD

**Issue by kamre** [mattermost/focalboard#889]
**Summary:**
In kanban view when the viewport is narrow two horizontal scrollbars appear.

**Steps to reproduce the behavior:**
1. Create board from Roadmap template
2. Resize the window making the width small enough
3. At some breakpoint there is single scrollbar
4. Making it even more narrow produces double scrollbars

**Expected behavior:**
Single horizontal scrollbar should be enough?

**Screenshots:**
![GH-738-TwoScrollBars](https://user-images.githubusercontent.com/5587620/126158777-b612a52e-cdc5-4ad0-9868-18ce1e0cb521.gif)

**Platform:**
 - Browser and version: Chrome 92
 - OS and version: Windows 10

**Additional context:**
There was a [question about this](https://community.mattermost.com/core/pl/1ye65bpoffnp7coyhei9ku3h7e) in the focalboard channel.

**Comment by chenilim** [comment]
Thanks @kamre! Assigning this to you to start @harshilsharma63 as this appears related to #738. Let's target this fix for v0.9. Thanks.

**Comment by ogi-m** [comment]
Tested and passed on v0.9.0 RC4 plugin - no double scroll bars
