### ISSUE TITLE
Change link on Focalboard.com to point straight to Github repo 

### ISSUE THREAD

**Issue by it33** [mattermost/focalboard#89]
![image](https://user-images.githubusercontent.com/177788/111611661-eebc5c80-8799-11eb-8b5e-9e393f9e9d58.png)

Reason: 

Focalboard.com was trending #2 on HackerNews (which is awesome!) and it was difficult to find the repo from the Focalboard main page. In future, we would want the GitHub repo to trend to get more stars and engagement. All said, though, super awesome to be trending!!

![image](https://user-images.githubusercontent.com/177788/111611957-3e028d00-879a-11eb-8b26-baeb2429c9f2.png)

**Comment by jespino** [comment]
Done, this will be visible in the next deploy.
