### ISSUE TITLE
Add a "Share feedback | View Source Code" links in the UI

### ISSUE THREAD

**Issue by it33** [mattermost/focalboard#90]
Add a "Share feedback | View Source Code" links in the UI. 

Point both links to a re-direct under focalboard.com so we can change the links at any time (important for those that are self-hosting older versions if we want to change links)

View Source Code redirect to https://github.com/mattermost/focalboard

Share feedback re-direct to https://github.com/mattermost/focalboard/wiki/Share-your-feedback!

![image](https://user-images.githubusercontent.com/177788/111613548-de0ce600-879b-11eb-9b4c-1b1839db5f42.png)

We want to focus traffic on the GitHub page initially so we get more star ratings and interactions from community.

**Comment by jespino** [comment]
@asaadmahmood what do you think about it, where would you put it? Do you mind taking care of this change?

**Comment by orthoxerox** [comment]
Since the code is released under AGPL the URL of "View Source Code" should be explicitly provided by the user/buildbot during compilation. This way users won't forget to fulfil the requirements of the license.

**Comment by jespino** [comment]
Interesting point of view, yes, I think we can make it an environment variable included during the build process, or maybe a config setting.

**Comment by asaadmahmood** [comment]
I don't think these should be visible in the UI at all times. I'd put them under a dropdown somewhere.

**Comment by asaadmahmood** [comment]
@jespino

**Comment by asaadmahmood** [comment]
No longer applicable as we already have a feedback button and it can be expanded more.
