### ISSUE TITLE
Update Icon for plugin

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#900]
Use the glyph named `icon-product-boards` from https://mattermost.github.io/compass-icons/ as the main icon.

Once the icons are updated, the glyph will automatically be updated and we won't have to manually do that.

Note: We may need to include the compass glyphs if we haven't already.

**Comment by chenilim** [comment]
@jespino assigning this to you, per the [thread here](https://community.mattermost.com/core/pl/smg31q1atfbyieo7sstdbwodbw). Please update that as part of the Global Nav work item (or separate PR). Thanks. cc @asaadmahmood.

Note that this should only affect the plugin for now. Personal Editions will use the existing branding and logo.

**Comment by jespino** [comment]
This is fixed
