### ISSUE TITLE
Bug: Selecting a new theme for the team doesn't get applied in focalboard

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#902]
**Summary:**
When the user changes the theme for the team, focalboard continues to use the previous theme that was set for the theme. Refreshing after changing the theme doesn't fix it.

**Steps to reproduce the behavior:**
1. Install and enable the plugin
2. Open Team A - current theme is default (white/blue)
3. Open focalboard - default theme also applied
4. In Team A, change the theme to Mattermost Dark
5. Open focalboard - theme not updated, still shows the default light theme

**Expected behavior:**
Focalboard should switch to the newly applied dark theme

**Comment by jespino** [comment]
It should be fixed as part of the #923 PR.
