### ISSUE TITLE
Bug: Focalboard logo font is incorrect

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#909]
**Steps to reproduce the behavior:**
1. Build and run the latest on main (on Aug 9 2021), or run a build from [this commit](https://github.com/mattermost/focalboard/pull/908/checks?check_run_id=3283633273)
2. See the font of the "Focalboard" logo, it appears to be Helvetica:
<img width="181" alt="v0 9 title" src="https://user-images.githubusercontent.com/46905241/128762642-816b3c3f-2fff-4561-8a7e-a71d8434c159.png">

**Expected behavior:**
Previously the Focalboard logo was an svg:
<img width="186" alt="v0 8 title" src="https://user-images.githubusercontent.com/46905241/128762634-7522fb45-dea7-4970-a6b5-923ced9e7b01.png">

**Platform:**
 - Chrome 91 on macOS

***Context:**
* Looks like the title is now [defined as a string here](https://github.com/mattermost/focalboard/blob/main/webapp/src/components/sidebar/sidebarUserMenu.tsx#L39).

**Comment by chenilim** [comment]
@asaadmahmood, what font should we use for the logo title? Or should we create and use svg paths for it? If so, we will need one for "Focalboard" and another for "Boards". FYI @jespino.

**Comment by jespino** [comment]
Done!
