### ISSUE TITLE
Feature Idea: Show more title text on cards 

### ISSUE THREAD

**Issue by it33** [mattermost/focalboard#914]
**Summary:**
Show more title text on cards (see screen mockup) 

**How important this is to me and why:**

Can't understand cards when I try to read them when title is overly truncated. 

Importance: Medium

Use cases:
1. Read a card 

**Additional context / similar features:**
Any examples of good implementations of this capability.

![image](https://user-images.githubusercontent.com/177788/128892787-a15541b8-f6cb-4189-9e2a-4acbbd607b6e.png)

**Comment by jespino** [comment]
This is already fixed in 0.9.0, that is going to be released soon. Thanks for the report.
