### ISSUE TITLE
Bug: Cannot change language to Chinese Simplified in 0.8.2

### ISSUE THREAD

**Issue by MFYDev** [mattermost/focalboard#928]
**Summary:**
In Mattermost 5.37.1, I installed FocalBoard 0.8.2, and I found when I tried to change language to Chinese Simplified, it doesn't work, the language is still English.

**Steps to reproduce the behavior:**
1. Install Mattermost 5.37.1
2. Install FocalBoard 0.8.2 from Github Release
3. Change language to Chinese Simplified

**Expected behavior:**
The language should be changed immediately

**Screenshots:**
![image](https://user-images.githubusercontent.com/53750381/128961072-a0557af7-e22b-45bf-891b-1cf1fde77bd3.png)

**Platform:**
 - Browser and version: Microsoft Edge latest version
 - OS and version: Ubuntu 20.04 LTS

**Comment by jespino** [comment]
@MFYDev thanks for reporting it, I added a PR to fix this for the next 0.9.0 release.
