### ISSUE TITLE
On Focalboard.com change "Home" to "View Source" pointing to https://github.com/mattermost/focalboard

### ISSUE THREAD

**Issue by it33** [mattermost/focalboard#93]
View Source is one of our biggest differentiators, and we should drive traffic to our GitHub page and get more star rating and community engagement. 

Logo on the left brings people to the home page, so we don't lose functionality. 

![image](https://user-images.githubusercontent.com/177788/111614720-24167980-879d-11eb-9657-db5a65043d9a.png)

**Comment by jespino** [comment]
Done
