### ISSUE TITLE
Bug: Table column calculations > Calculate dropdown height is limited by the table height

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#930]
**Summary:**
_Calculate_ dropdown height is limited by the table height, so where there are only a few items in the table it appears cut off and doesn't display all the options 

**Steps to reproduce the behavior:**
1. Open table view and make sure there's only a few rows
2. Add a number type property
3. Click on calculate below the numbers column

**Expected behavior:**
Dropdown opens fully and reveals all 10 options.

**Screenshots:**
![Screenshot (21)](https://user-images.githubusercontent.com/15314183/129032231-49351c5b-0f59-41ae-abf5-258304dc94da.png) ![Screenshot (19)](https://user-images.githubusercontent.com/15314183/129032221-07fb9eaa-2ff8-416d-9e03-e8bec4cac2f7.png)

**Comment by chenilim** [comment]
Let's try to fix this for v0.9 - looks like a straightforward css z-index problem? cc @sbishel.

**Comment by harshilsharma63** [comment]
@chenilim I've cherrypicked this to v0.9.0.
