### ISSUE TITLE
Bug: Hamburger menu is not shown after collapsing sidebar

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#934]
**Summary:**

**Steps to reproduce the behavior:**
1. Open a board
2. Click on the hide-sidebar button
4. Hamburger menu that shows sidebar is not shown

**Expected behavior:**
Hamburger menu that shows sidebar is shown when sidebar is collapsed.

**Screenshots:**
https://user-images.githubusercontent.com/46905241/129077549-0bc1f41f-da62-4a7f-8865-474973da293f.mov

**Platform:**
 - v0.9.0 RC2 on Mattermost v5.38 RC1

**Comment by chenilim** [comment]
@sbishel, assigning to you to reassign. This blocks mobile scenarios, as the user is unable to switch to other boards without the sidebar (among other things), so we should take this for v0.9.

**Comment by sbishel** [comment]
Only duplicates as a plugin.

**Comment by jespino** [comment]
The plugin now doesn't have collapse button, we need to define how we want to show it and where, because the removal of the whole board title and header makes it harder. @asaadmahmood any suggestion?

**Comment by asaadmahmood** [comment]
@jespino I mentioned it to @chenilim , but the ideal behavior is.
We remove the collapse button on both the desktop and mobile layouts altogether. No collapsing functionality is present.

On mobile, we also don't have the collapsing button, rather the sidebar is hidden by default, similar to what we see in Mattermost.

In the center channel, we have a hamburger menu (only on mobile) that is used to open the sidebar on mobile.

The sidebar on mobile opens up, it gets closed anytime the user interacts with the item in the sidebar (i.e. clicks on a board/view), or in the center channel. 
So even on mobile, the collapse sidebar button is not needed.

**Comment by chenilim** [comment]
I took a look at this, and implemented the proposed fix:
* Add the hide button on the same row as the workspace (channel) name
* Fix showing the show-sidebar (hamburger) button when hidden (this was a css conflict with the .hidden class)

Will submit a PR shortly, but here's the new behavior:
https://user-images.githubusercontent.com/46905241/129250319-2f25163b-1280-4282-8c90-00d71e6dfef0.mov
