### ISSUE TITLE
Bug: Card text editing does not display correctly

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#936]
**Steps to reproduce the behavior:**
1. Open a card
2. Click on "Add a description" at the bottom
3. Displays extra boxes above and below cursor, text does not appear correctly

**Expected behavior:**
WYSIWYG markdown editing, as before.

**Screenshots:**
<img width="804" alt="Text content bug" src="https://user-images.githubusercontent.com/46905241/129096198-195c0c3f-1125-49d7-82cf-439dff59e7ee.png">

https://user-images.githubusercontent.com/46905241/129096170-d5df3530-27f2-4cba-8e1b-78f3d62ee8da.mov

**Platform:**
 - Focalboard v0.9.0 RC3 on Mattermost 5.38 RC1 (Community server)

**Comment by sbishel** [comment]
Only duplicates when run as a plugin.
