### ISSUE TITLE
Bug: Need to scroll down to add board when sidebar is full

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#937]
**Steps to reproduce the behavior:**
1. Open a workspace with many boards (e.g. [our team workspace](https://community-daily.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/2510923b-40de-4a48-871f-cb8f85517a0b/effcc895-53a6-4af5-8320-9aabac657178))
2. Need to scroll down in order to add a board

**Expected behavior:**
The add board button should always be on top at the bottom of the screen. There should not be a scrollbar on the main window (right side of window).

**Screenshots:**
https://user-images.githubusercontent.com/46905241/129099097-ce96bdc8-fe79-492f-bc25-e2d5d9dba7ca.mov

**Platform:**
 - v0.9.0 RC3 (community server)

**Comment by sbishel** [comment]
Only duplicates in plugin mode.

**Comment by ogi-m** [comment]
Tested and passed on RC4 - Add board button is always visible, no scrollbar
