### ISSUE TITLE
Bug: Table Calculations -> Calculation Row should not be included in scroll.

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#938]
**Summary:**
Don't include the calculation row when scrolling

**Steps to reproduce the behavior:**
1. Open a board with a large number of items
3. Scroll the page
4. As you scroll, you will see the items behind the calculation row

**Expected behavior:**
scroll should not include calculation row.

**Screenshots:**

https://user-images.githubusercontent.com/12704875/129099284-509eaaf5-4487-4372-814c-01af68127644.mp4

**Comment by harshilsharma63** [comment]
@sbishel @chenilim I've cherry-picked this to v0.9.0 branch as well.

**Comment by ogi-m** [comment]
Tested and passed on 0.9 RC4 - items don't scroll behind the calculation row
