### ISSUE TITLE
Bug: Boards option does not line up in App Switcher

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#940]
**Steps to reproduce the behavior:**
1. Click on the App Switcher
2. "Boards" title does not line up with "Channels

**Expected behavior:**
Should line up.

**Screenshots:**
<img width="296" alt="App Switcher" src="https://user-images.githubusercontent.com/46905241/129111951-7b1b951a-6929-460e-8e0a-ccac2a2d8147.png">

**Platform:**
 - v0.9.0 RC3 on community server

**Comment by jespino** [comment]
I fixed that in the PR #947
