### ISSUE TITLE
Bug: App Switcher stays open after switching to Boards

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#943]
**Steps to reproduce the behavior:**
1. Open the App Switcher and select Boards
2. The App Switcher menu remains open

**Expected behavior:**
The App Switcher menu should close after selection

**Screenshots:**
https://user-images.githubusercontent.com/46905241/129115105-e1bab0ae-85cd-4f2c-8c4d-4bfe132c7672.mov

**Platform:**
 - v0.9.0 RC3 on Community

**Additional context:**
The App Switcher menu closes after switching from Boards to Channels.

**Comment by chenilim** [comment]
@jespino, assigning to you for investigation - this might be an App Switcher bug? FYI @asaadmahmood, @sbishel.

**Comment by asaadmahmood** [comment]
Yup, does look like a bug.

**Comment by jespino** [comment]
I'm addressing this on the mattermost-webapp side.
