### ISSUE TITLE
Bug: Opening a view without the full schema results in a page error

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#945]
**Steps to reproduce the behavior:**
1. Import the attached archive:
[view-without-collapsedOptionIds.focalboard.zip](https://github.com/mattermost/focalboard/files/6972721/view-without-collapsedOptionIds.focalboard.zip)

2. Open it
3. Page error "Something went wrong"
4. Error in console: "Cannot read property 'indexOf' of undefined"

**Expected behavior:**
View loads

**Platform:**
 - v0.9.0 RC3 plugin on Community
 - Chrome 91 on macOS

**Additional context:**
The view in the archive lacks a "collapsedOptionIds" field, which was missing in earlier schemas.

**Comment by chenilim** [comment]
This bug demonstrates a general issue when downloaded blocks are missing fields on the latest schema.

**Comment by ogi-m** [comment]
@chenilim The "Something went wrong" error still pops up when first uploading and opening the board. Board loads after refresh.
