### ISSUE TITLE
Bug: Links are not highlighted in the card markdown content

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#955]
**Steps to reproduce the behavior:**
1. Create a card
2. Add a link to the description, e.g. `Here's [a link](http://www.focalboard.com)`
3. Exit editing
4. The link is not highlighted (e.g. underlined and in blue)

**Expected behavior:**
Links are obvious in descriptions.

**Screenshots:**
The link "Thread in Analytics channel" is not highlighted:
<img width="462" alt="Links not highlighted" src="https://user-images.githubusercontent.com/46905241/129221542-6945a635-f7a2-47fa-8fc2-1eaed7eb8277.png">

But it is on hover:
<img width="482" alt="Links not highlighted - hover" src="https://user-images.githubusercontent.com/46905241/129221563-17b6d763-f61a-4798-b9b0-196c5925730b.png">

**Platform:**
 - v0.9.0 RC3 plugin on Community
 - Chrome 91 on macOS

**Comment by chenilim** [comment]
@sbishel, assigning to you to reassign. Looks like a regression, and may be related to general issues when running as a plugin with the Mattermost webapp CSS?

**Comment by sbishel** [comment]
@hahmadia - May be related to https://github.com/mattermost/focalboard/issues/936
