### ISSUE TITLE
Bug: Global header > Opening Boards from Threads page doesn't work

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#956]
**Summary:**
Opening boards from the Threads page doesn't work as there's no workspace associated to the Threads page. Trying to access boards from Threads just reloads the page.

**Steps to reproduce the behavior:**
1. In Channels, open Threads view
2. Click on the app switcher and select boards

**Expected behavior:**
Boards should open to the workspace associated with the channel to which the first thread in the list belongs to.
([see thread here](https://community-daily.mattermost.com/core/pl/pu96wign8fnufbqeettycthqnc))

**Platform**:
Focalboard v0.9.0 RC3 on Mattermost 5.38 & master (community/community-daily)

**Comment by chenilim** [comment]
This is going to be an issue until the permissions / sidebar redesign. Even if a thread is selected, clicking on Boards in the App Switcher doesn't currently do anything.

I propose:
* If a thread is selected, open the workspace associated with the channel for that thread
* If no thread is selected, open the workspace for the Town Square (or first, default channel)
  * The idea is that they can switch to another workspace with the [temporary switcher](https://community.mattermost.com/plugins/focalboard/workspace/qgsck6cts3fwpqwyjiupjm5cde/47aa9bb4-6967-4a96-83c7-11bd6b20f1eb/7e38eab4-890a-4fc3-8f48-a1f9bd1ab822?c=25315c3c-f53b-4288-8565-8e1142ca9bbf).

I'm maybe 2/5, an open to better suggestions. As Threads rolls out, this will be an issue for more customers. I think that if we could do the first item above, we'll be ok. cc @asaadmahmood, @jespino, @sbishel.

**Comment by asaadmahmood** [comment]
@chenilim I already made a suggestion, that it opens the first thread in the list in the threaded view if nothing is selected.
And obviously the temporary switcher may help and once we disconnect boards from channels, a lot of our issues would be resolved.

**Comment by chenilim** [comment]
Thanks @asaadmahmood, in that case we only have to address the first issue: To open the workspace for the selected thread. Assigning to you @sbishel to reassign (not sure if this should start with @jespino) - let's investigate if this is (hopefully) a straightforward fix.

**Comment by jespino** [comment]
I have a solution for this already in a PR, basically i store the last viewed channel and if there is no current channel i use the last viewed one.

**Comment by chenilim** [comment]
Thanks @jespino, sounds like this is PR #974. I *think* that's ok as an interim solution for the Threads as well. It's definitely better than it is now.
