### ISSUE TITLE
Bug: Table view header has a gap when scrolling

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#959]
**Steps to reproduce the behavior:**
1. Open a table with many rows
2. Scroll down
3. The rows appear in a gap above the header

**Expected behavior:**
No gap.
There also appears to be extra padding in the header.

**Screenshots:**
<img width="891" alt="Table gap" src="https://user-images.githubusercontent.com/46905241/129241181-8348f2ef-6cb5-49a5-a7c4-893fc7290361.png">

**Platform:**
 - v0.9.0 RC4 on Community
 - Chrome 91 on macOS

**Comment by chenilim** [comment]
FYI @asaadmahmood. The P1 issue here is the gap, but it looks like we need a UI pass on the table in general, to tighten up the padding, alignment (e.g. text and icons don't vertically align), etc.

**Comment by asaadmahmood** [comment]
@chenilim I can take this one.

**Comment by chenilim** [comment]
Just a quick note that this gap appears in the Board view (and maybe Gallery view) as well. It's likely the same code or fix, but please file additional issues if not. Thanks.

**Comment by sbishel** [comment]
FYI, I just noticed this occurs in the Kanban Board as well.

**Comment by kamre** [comment]
Is the overlap of kanban card with the header like this one:
![KanbanCardHeaderOverlap](https://user-images.githubusercontent.com/5587620/129873179-a8524a5d-1a3e-441e-a323-b1c97e1d1db3.gif)
also related to this issue?

**Comment by ogi-m** [comment]
Verified this is fixed on RC6
