### ISSUE TITLE
Only show table calculate controls on hover

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#960]
**Summary:**
Currently, the table calculate row is always visible:
<img width="765" alt="Table calculate row" src="https://user-images.githubusercontent.com/46905241/129242266-93e7c08b-af83-4a40-bd25-338f52475286.png">

This adds visual noise, and is mostly unnecessary as users will typically set this once or a few times, and only for a few columns.

Proposal:
* Hide the un-set (default state) calculate controls until the user hovers over them
* But always show the controls that are set

**Comment by chenilim** [comment]
What do you think @asaadmahmood? If you agree and it's an easy fix, I'd recommend taking it for 0.9, otherwise, we can consider for later. FYI @sbishel, @harshilsharma63.

**Comment by asaadmahmood** [comment]
@chenilim Makes sense to me, and it should be an easy fix.

**Comment by chenilim** [comment]
Thanks, do you want to take a crack at it, or should this be assigned to @harshilsharma63, as we need to differentiate the set and unset controls?

**Comment by chenilim** [comment]
Thanks @asaadmahmood, assigning it to you @harshilsharma63. Let's try to take this for 0.9 if it's an easy fix. FYI @sbishel.

**Comment by harshilsharma63** [comment]
@chenilim @asaadmahmood  doesn't this make the feature less discoverable? Same as #449 ?

**Comment by asaadmahmood** [comment]
@harshilsharma63 It does slightly, but ideally we should have the `count` on the first row displayed at all times so the user knows he can do the calculations from there (similar to notion).

**Comment by harshilsharma63** [comment]
@chenilim I'vemerged into `main` and cherrypicked in `release-0.9.0`.

**Comment by ogi-m** [comment]
Tested and passed on v0.9.0 RC11
