### ISSUE TITLE
Bug: Gallery view does not scroll

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#964]
**Steps to reproduce the behavior:**
1. Open a Gallery view with many items, or items with long content (e.g. paste lorem ipsum as a card's title)
2. Cannot scroll down

**Expected behavior:**
Should be able to scroll

**Screenshots:**
<img width="1056" alt="Gallery no scroll" src="https://user-images.githubusercontent.com/46905241/129261971-4edae3da-7650-4052-9deb-fa44b988d084.png">

**Platform:**
 - v0.9.0 RC4 on Community
 - Chrome 91 on macOS

**Additional context:**
This is a regression from v0.8, and repros on the Personal Desktop Mac app as well.

**Comment by chenilim** [comment]
More more regression to reassign @sbishel. FYI @asaadmahmood.

**Comment by ogi-m** [comment]
Tested and passed on v0.9.0 RC5
