### ISSUE TITLE
Bug: Global nav right-side buttons are spaced too far apart

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#965]
**Steps to reproduce the behavior:**
1. Open boards
2. Notice that the right-side nav bar buttons are spaced farther than Channels

**Expected behavior:**
Should have consistent spacing

**Screenshots:**
Boards:
![boards nav](https://user-images.githubusercontent.com/46905241/129267989-078ba472-1992-4cee-9b06-9ad0195cefcc.png)

Channels:
![channels nav](https://user-images.githubusercontent.com/46905241/129268002-2186036f-bf84-497a-89d5-5dc7961d7d01.png)

**Platform:**
 - v0.9.0 plugin on Community
 - Chrome 91 on macOS

**Comment by chenilim** [comment]
@asaadmahmood, not sure if this is something you can just go in and fix the CSS on, or if we need @jespino to update the code.

**Comment by jespino** [comment]
I think this should be just css code.
