### ISSUE TITLE
Bug: Should not show "Empty" label for empty table cells

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#966]
**Steps to reproduce the behavior:**
1. Create a table with cards that have URL, text, and date properties (among others)
2. These property types (and likely others) show an "Empty" placeholder
3. Also, empty dates have an "Empty" label with a darker color and larger font

**Expected behavior:**
Remove all "Empty" labels and placeholders in tables - show empty cells instead.

**Screenshots:**
<img width="387" alt="empty label" src="https://user-images.githubusercontent.com/46905241/129270976-7e4a8395-e860-491e-b391-b78d6bb09da5.png">

**Platform:**
 - v0.9.0 RC4 Mac App

**Comment by chenilim** [comment]
@asaadmahmood, I think we should simply remove the "Empty" placeholder on tables. I don't think this is a high priority, but might be part of cleaning up the table styles. FYI @sbishel.

**Comment by asaadmahmood** [comment]
That makes sense to me.
