### ISSUE TITLE
Bug: URL properties overflow table cells

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#967]
**Steps to reproduce the behavior:**
1. Open a table with a URL property cell
2. The contents of the URL overflow the cell

**Expected behavior:**
Content should not overflow cells

**Screenshots:**
<img width="387" alt="URL cell overflow" src="https://user-images.githubusercontent.com/46905241/129271732-710868dc-7ea2-4097-a06f-349bf3bf417f.png">

**Platform:**
 - v0.9.0 RC4 Mac App

**Comment by chenilim** [comment]
FYI @asaadmahmood, we can leave this as a help wanted ticket, or something to check as part of the table styles cleanup. cc @sbishel.

**Comment by jufab** [comment]
@chenilim Can I try to do this one? (not cleanup but to fix this bug...and for my first PR on this project 😊 )
