### ISSUE TITLE
Bug: Last board / view is not opened when using the App Switcher

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#976]
**Steps to reproduce the behavior:**
1. Switch to Boards via the app switcher
2. Open a view
3. Switch back to Channels
4. Switch to Boards again
5. No board / view is shown

**Expected behavior:**
The last view should be opened by default. This is what happens when using the Channel Header button.

**Platform:**
 - v0.9.0 RC5 on Community
 - Chrome 91 on macOS

**Additional context:**
The lastBoardId and lastViewId appear to be correctly set in the browser LocalStorage.

**Comment by chenilim** [comment]
@sbishel, while I don't think this is a high severity issue, it's concerning that the load behavior is different when opened via the App Switcher. I think it's worth investigating to make sure there isn't a bigger issue. FYI @jespino.

**Comment by jespino** [comment]
That is fixed in the #972 PR.

**Comment by ogi-m** [comment]
Tested and passed on RC6 - the last view opens by default when accessing from the app switcher
