### ISSUE TITLE
Bug: Uncollapse button hidden by the global nav

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#977]
**Summary:**
There's no apparent way for the user to uncollapse the sidebar after collapsing it.

**Steps to reproduce the behavior:**
1. Install RC5
2. Open Boards
3. Click on the collapse button in the sidebar

**Expected behavior:**

Board collapses and the uncollapse button is displayed

**Screenshots:**
![SharedScreenshot](https://user-images.githubusercontent.com/15314183/129393722-6d9ca653-97f6-41ff-851b-65ed6e1d2314.jpg)

**Platform:**
 - v0.9.0 RC5 on master (community-daily)

**Comment by chenilim** [comment]
Given that the fix is relatively simple, and this is technically a regression from 0.8, I've marked it for 0.9 and will cherry-pick. FYI @sbishel.

**Comment by ogi-m** [comment]
Tested and passed on RC6, button to open the collapsed menu is now visible
