### ISSUE TITLE
Feature Idea: Open the first board if there is one

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#978]
**Summary:**
Currently, no initial board is opened (if there isn't a last-opened board / view). To save a click, we should open the first view of the first board if there is one.

**How important this is to me and why:**

Importance: Low

Use cases:
1. Save the user a click, and avoid an empty page

**Comment by jespino** [comment]
I want to rewrite all the redirection logic that we have already into the router, to make it simpler and easier.

**Comment by chenilim** [comment]
Synched up with Winson and Scott - let's "won't fix" this for now since we have the template picker instead of an empty screen. Will revisit later.
