### ISSUE TITLE
Bug: Hide column and show it again doesn't respect the previous order

### ISSUE THREAD

**Issue by jespino** [mattermost/focalboard#988]
**Summary:**
If I hide a column and show it again is not restoring the old order.

**Steps to reproduce the behavior:**
1. Go to a kanban view with multiple columns
2. Hide one of the columns (not the first one, and remember which was the position)
3. Show again that column.
4. You can see the column wasn't restored in the previous position

**Expected behavior:**
Column should be in the same position that was before

**Platform:**
 - Browser and version: Firefox
 - OS and version: Linux

**Additional context:**
This probably can be addressed together with the enhancement #544

**Comment by chenilim** [comment]
With a closer look, I believe this is a dup of #544, so I added some more notes there, put that up for grabs, and closing this as a dup.
