### ISSUE TITLE
Bug: Shared Boards URL is Incorrect for Focalboard as a Plugin

### ISSUE THREAD

**Issue by hahmadia** [mattermost/focalboard#989]
**Summary:**
When you share a board in focalboard when focalboard is a plugin of Mattermost, the shared link is incorrect resulting in incorrect behaviour. 

**Steps to reproduce the behavior:**
1. Go to a board
2. Click `...` and `Share board`
3. Link is (for example) 
`http://localhost:8065/workspace/...`

**Expected behavior:**
`http://localhost:8065/boards/workspace/...`

There should be a `boards` before the `workspace`

**Screenshots:**

![image](https://user-images.githubusercontent.com/17804942/129592109-e44f1e93-9b9a-4543-bbdd-55d26f5d8563.png)

**Comment by chenilim** [comment]
Good catch. We definitely want to fix this, which should hopefully be straight forward. @sbishel, assigning to you to reassign. Note that there is a "frontendBaseURL" property used in the plugin webapp code. We might want to review / refactor to make sure there's a consistent base URL that works across the plugin and Personal Editions. cc @jespino, @mgdelacroix, @ogi-m.
