### ISSUE TITLE
Bug: Add padding to `...` dropdown of boards

### ISSUE THREAD

**Issue by hahmadia** [mattermost/focalboard#990]
**Summary:**
`...` dropdown menu needs padding

**Expected behavior:**
![image](https://user-images.githubusercontent.com/17804942/129592574-61f7ac63-2beb-42e6-b4ef-6217013cdd4f.png)

The above dropdown should have padding added so the contents are not stuck to the borders

**Comment by chenilim** [comment]
Thanks @hahmadia, while you filed this first, I already assigned #1005, so duping this issue to that one.
