### ISSUE TITLE
Bug: Refresh Focalboard loses theme from Mattermost

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#991]
**Summary:**
When launching focalboard from GlobalNavbar, the theme follows. However a refresh in focalboard and the theme returns to focalboard theme.

**Steps to reproduce the behavior:**
1. Go to Channels
2. Click on Focalboard from Global nav bar.
3. Refresh focalboard.
4. Notice theme change.

**Expected behavior:**
Theme should survive a hard refresh.

**Screenshots:**

https://user-images.githubusercontent.com/12704875/129593038-2f56d3c2-d6f0-4835-871f-c68de230d8bb.mp4

**Comment by ogi-m** [comment]
Probably relates to https://github.com/mattermost/focalboard/issues/901

**Comment by chenilim** [comment]
@jespino is this a dup of #901? In any case, I believe this should work as expected, even after a hard refresh.

**Comment by jespino** [comment]
This can be related to the multiple teams themes. If you have multiple team themes, you have the "default theme", the team X theme, the team Y theme, and so on. The default theme is never shown, but is the only one that focalboard is able to support without the teams concept.
