### ISSUE TITLE
Bug: Make page shown after turning off board sharing more descriptive rather than a blank page

### ISSUE THREAD

**Issue by hahmadia** [mattermost/focalboard#992]
**Summary:**
No indication the board sharing has been turned off

**Steps to reproduce the behavior:**
1. Share a board
2. Access URL via incognito
3. Turn off board sharing
4. Refresh page and you are shown a page that is blank without indication that sharing for that board is turned off

**Currently**
![image](https://user-images.githubusercontent.com/17804942/129593152-71f26bea-b052-4add-bdb2-670084ca8768.png)

**Expected behavior:**
The page should be saying something like `Sharing for this board has been turned off and is no longer accessible` or something along those lines

**Comment by hahmadia** [comment]
@chenilim 

Thoughts on how to improve this?

**Comment by chenilim** [comment]
In this case, and error banner with the text "Board may be deleted or access revoked." should be shown. This text is already in the translation table as `BoardPage.syncFailed`. It looks like this is a regression from v0.8, where this error was handled by BoardPage. From the browser console, I see an error, which may be unhandled:

<img width="637" alt="Permission error in console" src="https://user-images.githubusercontent.com/46905241/129602616-20df595c-bc25-4614-bacc-87cf3bc47460.png">

While this is relatively low severity, I think we should investigate for 0.9 and fix if possible. There may be other unintended issues when not properly handling this code path.

**Comment by ogi-m** [comment]
Tested and passed on RC7 - "Board may be deleted or access revoked" error is now displayed
