### ISSUE TITLE
Bug: When exporting to CSV, card title is exported as "Title" but shown as "Name" on table view

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/focalboard#993]
**Steps to reproduce the behavior:**
1. Go to a board
2. Select a table view of the board
3. Export that view as CSV

**Expected behavior:**
Both names in the view and the exported CSV file should be consistent.

**Screenshots:**
![image](https://user-images.githubusercontent.com/223323/129592929-c54d8541-1b90-4e39-9bbd-235cc56032eb.png)

The equivalent export is:

```csv
Title,Type,Summary
"Nov 2","Standup","Green light!"
"Other stuff","Weekly Sync",""
```

which shows `Title` instead of showing `Name` as the web view does

**Comment by chenilim** [comment]
This is a relatively minor issue, but agree that the CSV headers should be consistent with the table. We should grab the "Name" string from the translation table. Putting this up for grabs. cc @sbishel, @ogi-m.

**Comment by b4sen** [comment]
Hi, can I take this issue?

**Comment by sbishel** [comment]
Thanks @b4sen, its all yours.

**Comment by b4sen** [comment]
> This is a relatively minor issue, but agree that the CSV headers should be consistent with the table. We should grab the "Name" string from the translation table. Putting this up for grabs. cc @sbishel, @ogi-m.

If I grab the "Name" from the translation table, should I get the rest of the headers too?
This is how I would approach it:
`const row: string[] = [intl.formatMessage({id: 'TableComponent.name'})]`

**Comment by sbishel** [comment]
@b4sen I don't think that is necessary as "Name" is the only hard coded property name. All other properties are user defined and not translated.  Thanks for checking.

**Comment by sbishel** [comment]
closing as fixed
