### ISSUE TITLE
Bug: App switcher text color doesn't match the theme

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#994]
**Summary:**
The text for Channels, Playbooks and Boards in the channel switcher shows up as purple regardless of the set theme.

**Steps to reproduce the behavior:**
1. Set a dark theme
2. Open Boards
3. Open the app switcher in the top left and observe the text color

**Expected behavior:**
The text should have the same color as in Channels

**Screenshots:**
App switcher text color in Boards:

![appswitcher_boards](https://user-images.githubusercontent.com/15314183/129593575-34a35404-1144-4e8a-8fca-6d7c3ea53f96.jpg)

App switcher text color in Channels:

![appswitcher_channels](https://user-images.githubusercontent.com/15314183/129593571-d072b6a2-f322-438b-81e0-7114215fe625.jpg)

**Platform:**
 - Focalbooard v.0.9.0-RC5 plugin on master (community-daily)

**Comment by chenilim** [comment]
Could you help investigate @asaadmahmood? Not sure if this is a bug on our side, or something the Global Nav team needs to fix. cc @sbishel.

**Comment by asaadmahmood** [comment]
@chenilim Global, this is an issue that I see on the channel side as well on `community-daily`.
![Screenshot 2021-08-16 at 10 10 24 PM](https://user-images.githubusercontent.com/11034289/129602611-a36b9fe9-f1d1-433e-b2e1-92bd981adeb1.png)

**Comment by jespino** [comment]
Closed by #1012

**Comment by ogi-m** [comment]
Verified the text color is now fixed but I've [opened anew issue](https://github.com/mattermost/focalboard/issues/1095) for icon color.

**Comment by ogi-m** [comment]
Tested and passed on v0.10
