### ISSUE TITLE
Bug: Clicking on Account Settings or Custom Status in the avatar dropdown doesn't work

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#996]
**Summary:**
Nothing happens when clicking on the Custom Status or Account Settings options in the navbar avatar dropdown. 
When the user returns to Channels, the modals pop up then.

These options should either open the expected modals immediately or they should be hidden from the dropdown.

**Steps to reproduce the behavior:**
1. Go to Boards
2. Click on the avatar in the top right
3. Click on Account Settings

**Expected behavior:**
Account Settings modal opens immediately

**Platform:**
 - Focalbooard v.0.9.0-RC5 plugin on master (community-daily)

**Comment by chenilim** [comment]
All the menu settings should work as expected. @sbishel, assigning to you to reassign. Not sure if this should go to @jespino or someone else.

**Comment by jespino** [comment]
I think that should go to mattermost-webapp team and should go to the global header team. Probably exposing the modals at the global header level.

**Comment by sbishel** [comment]
Created Jira issue for the UI Platform Team

https://mattermost.atlassian.net/browse/MM-37963

**Comment by jespino** [comment]
Created a PR here: https://github.com/mattermost/mattermost-webapp/pull/8621

**Comment by jespino** [comment]
Fixed on mattermost/mattermost-webapp#8621
