### ISSUE TITLE
Bug: Images in multiple columns content overlaps outside the column size

### ISSUE THREAD

**Issue by jespino** [mattermost/focalboard#998]
**Summary:**
Images in multi-column content overflows outside of the column size.

**Steps to reproduce the behavior:**
1. Go to a card
2. Add 2 dividers and an image
3. Drag and drop all of them to put them in one single row
4. The image overflows the column expected size.

**Expected behavior:**
The image adjust to the column size if the image is too big.

**Screenshots:**
![imagen](https://user-images.githubusercontent.com/290303/129595164-369c9dd3-b49d-4be4-aa34-73d2c3496f94.png)

**Platform:**
 - Browser and version: Firefox
 - OS and version: Linux

**Comment by ogi-m** [comment]
Tested and passed on RC5
